import type { BlockNode, BlockType, DocumentEditorContent } from './editor';
import type { AppSource } from './types';

export interface TemplateDefinition {
  slug: string;
  title: string;
  description: string;
  appSource: AppSource;
  documentType: string;
  mergeFields: Array<{ key: string; label: string; description?: string; required?: boolean }>;
  content: DocumentEditorContent;
}

function block(
  type: BlockType,
  text: string,
  extra: Partial<Omit<BlockNode, 'id' | 'type' | 'children'>> = {},
): BlockNode {
  return { id: Math.random().toString(36).slice(2, 10), type, children: [{ text }], ...extra };
}

export const DOCUMENT_TEMPLATES: TemplateDefinition[] = [
  // ─── DOMAINE ────────────────────────────────────────────────────────────────
  {
    slug: 'terra-deal-memo',
    title: 'Deal Memo',
    description: 'Internal deal summary memo for commercial real estate transactions',
    appSource: 'terra',
    documentType: 'deal_memo',
    mergeFields: [
      { key: '{{client_name}}', label: 'Client Name', required: true },
      { key: '{{property_address}}', label: 'Property Address', required: true },
      { key: '{{deal_value}}', label: 'Deal Value', required: true },
      { key: '{{closing_date}}', label: 'Closing Date' },
      { key: '{{agent_name}}', label: 'Agent Name' },
      { key: '{{property_type}}', label: 'Property Type' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Deal Memorandum'),
        block('heading3', '{{property_address}} | {{property_type}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Transaction Summary'),
        block('paragraph', 'Client: {{client_name}}'),
        block('paragraph', 'Deal Value: {{deal_value}}'),
        block('paragraph', 'Target Closing: {{closing_date}}'),
        block('paragraph', 'Lead Agent: {{agent_name}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Property Overview'),
        block(
          'paragraph',
          'Provide a brief overview of the property, its current condition, and key attributes.',
        ),
        block('horizontal_rule', ''),
        block('heading2', 'Investment Thesis'),
        block('paragraph', 'Describe the strategic rationale for this transaction.'),
        block('horizontal_rule', ''),
        block('heading2', 'Risk Factors'),
        block('bullet_list', 'Market risk'),
        block('bullet_list', 'Environmental risk'),
        block('bullet_list', 'Tenant risk'),
        block('horizontal_rule', ''),
        block('heading2', 'Next Steps'),
        block('ordered_list', 'Execute Letter of Intent'),
        block('ordered_list', 'Conduct due diligence'),
        block('ordered_list', 'Close transaction'),
      ],
    },
  },
  {
    slug: 'terra-offer-letter',
    title: 'Offer Letter',
    description: 'Formal offer letter for real estate acquisition',
    appSource: 'terra',
    documentType: 'offer_letter',
    mergeFields: [
      { key: '{{client_name}}', label: 'Buyer Name', required: true },
      { key: '{{property_address}}', label: 'Property Address', required: true },
      { key: '{{deal_value}}', label: 'Offer Price', required: true },
      { key: '{{closing_date}}', label: 'Proposed Closing Date' },
      { key: '{{agent_name}}', label: 'Agent Name' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Letter of Intent — Real Estate Purchase'),
        block('paragraph', 'Date: {{closing_date}}'),
        block('horizontal_rule', ''),
        block(
          'paragraph',
          'This Letter of Intent ("LOI") is submitted by {{client_name}} ("Buyer") regarding the acquisition of the property located at {{property_address}} ("Property").',
        ),
        block('heading2', 'Offer Terms'),
        block('paragraph', 'Purchase Price: {{deal_value}}'),
        block('heading2', 'Conditions'),
        block('bullet_list', 'Subject to satisfactory due diligence'),
        block('bullet_list', 'Subject to financing approval'),
        block('bullet_list', 'Subject to clear title'),
        block('heading2', 'Confidentiality'),
        block(
          'paragraph',
          'This LOI is confidential and shall not be disclosed without prior written consent.',
        ),
        block('heading2', 'Acceptance'),
        block('paragraph', 'Please indicate acceptance by signing below.'),
        block('paragraph', ''),
        block('paragraph', 'Buyer: {{client_name}}'),
        block('paragraph', 'Agent: {{agent_name}}'),
      ],
    },
  },
  {
    slug: 'terra-property-report',
    title: 'Property Intelligence Report',
    description: 'Comprehensive property analysis report',
    appSource: 'terra',
    documentType: 'property_report',
    mergeFields: [
      { key: '{{property_address}}', label: 'Property Address', required: true },
      { key: '{{property_type}}', label: 'Property Type' },
      { key: '{{client_name}}', label: 'Prepared For' },
      { key: '{{agent_name}}', label: 'Prepared By' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Property Intelligence Report'),
        block('heading3', '{{property_address}}'),
        block('paragraph', 'Prepared For: {{client_name}} | Prepared By: {{agent_name}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Executive Summary'),
        block('paragraph', 'Provide a concise executive summary of key findings.'),
        block('heading2', 'Property Details'),
        block('table', '', {
          tableData: [
            ['Attribute', 'Value'],
            ['Property Type', '{{property_type}}'],
            ['Address', '{{property_address}}'],
            ['Year Built', ''],
            ['Square Footage', ''],
            ['Zoning', ''],
          ],
        }),
        block('heading2', 'Market Analysis'),
        block(
          'paragraph',
          'Describe current market conditions, comparable sales, and pricing trends.',
        ),
        block('heading2', 'Financial Analysis'),
        block('paragraph', 'Include cap rate, NOI, and investment return projections.'),
        block('heading2', 'Risk Assessment'),
        block('paragraph', 'Identify and evaluate key risk factors.'),
        block('heading2', 'Recommendation'),
        block('paragraph', 'State the final recommendation and suggested next steps.'),
      ],
    },
  },
  {
    slug: 'terra-investor-packet',
    title: 'Investor Packet',
    description: 'Investor presentation and data package',
    appSource: 'terra',
    documentType: 'investor_packet',
    mergeFields: [
      { key: '{{client_name}}', label: 'Investor Name', required: true },
      { key: '{{deal_value}}', label: 'Investment Amount' },
      { key: '{{property_address}}', label: 'Asset Address' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Investment Opportunity Package'),
        block('heading3', 'Confidential — Prepared for {{client_name}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Investment Summary'),
        block('paragraph', 'Total Investment: {{deal_value}}'),
        block('heading2', 'Asset Overview'),
        block('paragraph', 'Property: {{property_address}}'),
        block('heading2', 'Return Profile'),
        block('table', '', {
          tableData: [
            ['Metric', 'Projected'],
            ['IRR', ''],
            ['Equity Multiple', ''],
            ['Cash-on-Cash', ''],
            ['Hold Period', ''],
          ],
        }),
        block('heading2', 'Disclaimer'),
        block(
          'blockquote',
          'This document is for informational purposes only and does not constitute an offer to sell securities. Past performance is not indicative of future results.',
        ),
      ],
    },
  },

  // ─── PARAGON ────────────────────────────────────────────────────────────────
  {
    slug: 'aegis-incident-report',
    title: 'Incident Report',
    description: 'Security incident formal report and timeline',
    appSource: 'aegis',
    documentType: 'incident_report',
    mergeFields: [
      { key: '{{incident_id}}', label: 'Incident ID', required: true },
      { key: '{{incident_title}}', label: 'Incident Title', required: true },
      { key: '{{severity}}', label: 'Severity Level', required: true },
      { key: '{{reported_by}}', label: 'Reported By' },
      { key: '{{affected_systems}}', label: 'Affected Systems' },
      { key: '{{remediation_steps}}', label: 'Remediation Steps' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Security Incident Report'),
        block('paragraph', 'Incident ID: {{incident_id}} | Severity: {{severity}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Incident Overview'),
        block('paragraph', 'Title: {{incident_title}}'),
        block('paragraph', 'Reported By: {{reported_by}}'),
        block('paragraph', 'Affected Systems: {{affected_systems}}'),
        block('heading2', 'Timeline'),
        block('table', '', {
          tableData: [
            ['Time', 'Event'],
            ['T+0', 'Initial detection'],
            ['T+1h', 'Containment initiated'],
            ['T+4h', 'Root cause identified'],
            ['T+8h', 'Remediation complete'],
          ],
        }),
        block('heading2', 'Impact Assessment'),
        block('paragraph', 'Describe business impact, data exposure, and affected users.'),
        block('heading2', 'Root Cause Analysis'),
        block('paragraph', 'Provide root cause analysis and contributing factors.'),
        block('heading2', 'Remediation Steps'),
        block('paragraph', '{{remediation_steps}}'),
        block('heading2', 'Lessons Learned'),
        block('paragraph', 'Document process improvements and preventive measures.'),
      ],
    },
  },
  {
    slug: 'aegis-vulnerability-assessment',
    title: 'Vulnerability Assessment',
    description: 'Technical vulnerability assessment and remediation plan',
    appSource: 'aegis',
    documentType: 'vulnerability_assessment',
    mergeFields: [
      { key: '{{affected_systems}}', label: 'Target Systems', required: true },
      { key: '{{risk_score}}', label: 'Overall Risk Score' },
      { key: '{{compliance_framework}}', label: 'Compliance Framework' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Vulnerability Assessment Report'),
        block('paragraph', 'Target: {{affected_systems}} | Risk Score: {{risk_score}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Scope & Methodology'),
        block('paragraph', 'Describe the assessment scope, tools used, and methodology.'),
        block('heading2', 'Executive Summary'),
        block('paragraph', 'Critical findings summary and overall risk posture.'),
        block('heading2', 'Vulnerability Findings'),
        block('table', '', {
          tableData: [
            ['CVE', 'Severity', 'CVSS Score', 'Affected System', 'Status'],
            ['', '', '', '', ''],
          ],
        }),
        block('heading2', 'Compliance Status'),
        block('paragraph', 'Framework: {{compliance_framework}}'),
        block('heading2', 'Remediation Roadmap'),
        block('ordered_list', 'Critical vulnerabilities — immediate remediation'),
        block('ordered_list', 'High vulnerabilities — patch within 30 days'),
        block('ordered_list', 'Medium vulnerabilities — patch within 90 days'),
      ],
    },
  },
  {
    slug: 'aegis-compliance-evidence',
    title: 'Compliance Evidence Package',
    description: 'Compliance attestation and evidence collection',
    appSource: 'aegis',
    documentType: 'compliance_evidence',
    mergeFields: [
      { key: '{{compliance_framework}}', label: 'Framework', required: true },
      { key: '{{reported_by}}', label: 'Compliance Officer' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Compliance Evidence Package'),
        block('paragraph', 'Framework: {{compliance_framework}} | Prepared by: {{reported_by}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Control Evidence'),
        block('table', '', {
          tableData: [
            ['Control ID', 'Control Description', 'Evidence Type', 'Status', 'Last Tested'],
            ['', '', '', '', ''],
          ],
        }),
        block('heading2', 'Attestation'),
        block(
          'paragraph',
          'I hereby attest that the controls described in this document are implemented and operating effectively as of the date of this document.',
        ),
        block('paragraph', ''),
        block('paragraph', 'Signature: _______________________'),
        block('paragraph', 'Date: _______________________'),
      ],
    },
  },
  {
    slug: 'aegis-pentest-summary',
    title: 'Penetration Test Summary',
    description: 'Executive summary of penetration testing engagement',
    appSource: 'aegis',
    documentType: 'penetration_test_summary',
    mergeFields: [
      { key: '{{affected_systems}}', label: 'Target Scope', required: true },
      { key: '{{risk_score}}', label: 'Overall Risk Score' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Penetration Test Executive Summary'),
        block('paragraph', 'Scope: {{affected_systems}} | Risk Score: {{risk_score}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Engagement Summary'),
        block('paragraph', 'Describe engagement objectives, timeline, and methodology.'),
        block('heading2', 'Key Findings'),
        block('table', '', {
          tableData: [
            ['Finding', 'Severity', 'CVSS', 'Status'],
            ['', '', '', ''],
          ],
        }),
        block('heading2', 'Attack Paths Demonstrated'),
        block('paragraph', 'Document successful attack chains and escalation paths.'),
        block('heading2', 'Recommendations'),
        block('ordered_list', 'Immediate action items'),
        block('ordered_list', 'Short-term improvements'),
        block('ordered_list', 'Long-term strategic changes'),
      ],
    },
  },

  // ─── Carlota Jo ───────────────────────────────────────────────────────────
  {
    slug: 'carlota-engagement-letter',
    title: 'Engagement Letter',
    description: 'Professional services engagement letter',
    appSource: 'carlota_jo',
    documentType: 'engagement_letter',
    mergeFields: [
      { key: '{{client_name}}', label: 'Client Name', required: true },
      { key: '{{client_company}}', label: 'Client Company' },
      { key: '{{engagement_type}}', label: 'Engagement Type', required: true },
      { key: '{{start_date}}', label: 'Start Date' },
      { key: '{{retainer_amount}}', label: 'Retainer Amount' },
      { key: '{{scope_of_work}}', label: 'Scope of Work' },
      { key: '{{payment_terms}}', label: 'Payment Terms' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Engagement Letter'),
        block('paragraph', 'Date: {{start_date}}'),
        block('paragraph', 'Client: {{client_name}}, {{client_company}}'),
        block('horizontal_rule', ''),
        block('paragraph', 'Dear {{client_name}},'),
        block(
          'paragraph',
          'We are pleased to confirm our engagement to provide {{engagement_type}} services as described herein.',
        ),
        block('heading2', 'Scope of Work'),
        block('paragraph', '{{scope_of_work}}'),
        block('heading2', 'Fees & Payment'),
        block('paragraph', 'Retainer: {{retainer_amount}}'),
        block('paragraph', 'Payment Terms: {{payment_terms}}'),
        block('heading2', 'Term'),
        block(
          'paragraph',
          'This engagement shall commence on {{start_date}} and continue until the completion of the described services or terminated by either party with 30 days written notice.',
        ),
        block('heading2', 'Acceptance'),
        block('paragraph', 'Please sign below to acknowledge your acceptance of these terms.'),
        block('paragraph', ''),
        block('paragraph', 'Client Signature: _______________________'),
        block('paragraph', 'Carlota Jo Consulting: _______________________'),
      ],
    },
  },
  {
    slug: 'carlota-nda',
    title: 'Non-Disclosure Agreement',
    description: 'Mutual or one-way NDA template',
    appSource: 'carlota_jo',
    documentType: 'nda',
    mergeFields: [
      { key: '{{client_name}}', label: 'Receiving Party', required: true },
      { key: '{{client_company}}', label: 'Company' },
      { key: '{{nda_effective_date}}', label: 'Effective Date' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Non-Disclosure Agreement'),
        block('paragraph', 'Effective Date: {{nda_effective_date}}'),
        block('horizontal_rule', ''),
        block(
          'paragraph',
          'This Non-Disclosure Agreement ("Agreement") is entered into as of {{nda_effective_date}} between Carlota Jo Consulting ("Disclosing Party") and {{client_name}}, {{client_company}} ("Receiving Party").',
        ),
        block('heading2', '1. Confidential Information'),
        block(
          'paragraph',
          '"Confidential Information" means any information disclosed by one party to the other that is marked as confidential or reasonably should be understood to be confidential.',
        ),
        block('heading2', '2. Obligations'),
        block(
          'paragraph',
          'The Receiving Party agrees to: (a) hold Confidential Information in strict confidence; (b) not disclose to third parties without prior written consent; (c) use only for the purpose of evaluating or pursuing a business relationship.',
        ),
        block('heading2', '3. Term'),
        block(
          'paragraph',
          'This Agreement shall remain in effect for three (3) years from the Effective Date.',
        ),
        block('heading2', '4. Governing Law'),
        block('paragraph', 'This Agreement shall be governed by applicable law.'),
        block('heading2', 'Signatures'),
        block('paragraph', 'Disclosing Party: Carlota Jo Consulting'),
        block('paragraph', 'Receiving Party: {{client_name}}'),
      ],
    },
  },
  {
    slug: 'carlota-service-agreement',
    title: 'Service Agreement',
    description: 'Professional services master agreement',
    appSource: 'carlota_jo',
    documentType: 'service_agreement',
    mergeFields: [
      { key: '{{client_name}}', label: 'Client Name', required: true },
      { key: '{{client_company}}', label: 'Company' },
      { key: '{{start_date}}', label: 'Start Date' },
      { key: '{{retainer_amount}}', label: 'Fee Amount' },
      { key: '{{payment_terms}}', label: 'Payment Terms' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Master Service Agreement'),
        block('paragraph', 'Parties: Carlota Jo Consulting & {{client_name}}, {{client_company}}'),
        block('horizontal_rule', ''),
        block('heading2', '1. Services'),
        block(
          'paragraph',
          'Carlota Jo Consulting agrees to provide professional consulting services as agreed upon via Statements of Work (SOWs).',
        ),
        block('heading2', '2. Compensation'),
        block('paragraph', 'Client agrees to pay {{retainer_amount}} per {{payment_terms}}.'),
        block('heading2', '3. Intellectual Property'),
        block(
          'paragraph',
          'All work product created under this Agreement shall be owned by Client upon payment in full.',
        ),
        block('heading2', '4. Limitation of Liability'),
        block(
          'paragraph',
          'Neither party shall be liable for indirect, incidental, or consequential damages.',
        ),
        block('heading2', '5. Termination'),
        block('paragraph', 'Either party may terminate with 30 days written notice.'),
        block('heading2', 'Signatures'),
        block('paragraph', 'Client: {{client_name}}'),
        block('paragraph', 'Provider: Carlota Jo Consulting'),
      ],
    },
  },
  {
    slug: 'carlota-confidential-memo',
    title: 'Confidential Memo',
    description: 'Internal confidential memorandum',
    appSource: 'carlota_jo',
    documentType: 'confidential_memo',
    mergeFields: [
      { key: '{{client_name}}', label: 'To', required: true },
      { key: '{{engagement_type}}', label: 'Re' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'CONFIDENTIAL MEMORANDUM'),
        block('horizontal_rule', ''),
        block('paragraph', 'TO: {{client_name}}'),
        block('paragraph', 'FROM: Carlota Jo Consulting'),
        block('paragraph', 'RE: {{engagement_type}}'),
        block('paragraph', 'DATE: {{start_date}}'),
        block('horizontal_rule', ''),
        block(
          'blockquote',
          'CONFIDENTIAL — This memorandum contains privileged and confidential information. Distribution or reproduction without prior written consent is prohibited.',
        ),
        block('heading2', 'Purpose'),
        block('paragraph', 'Describe the purpose of this memorandum.'),
        block('heading2', 'Background'),
        block('paragraph', 'Provide relevant background and context.'),
        block('heading2', 'Analysis'),
        block('paragraph', 'Present your analysis and findings.'),
        block('heading2', 'Recommendations'),
        block('paragraph', 'State your recommendations.'),
      ],
    },
  },

  // ─── SEXTANT ──────────────────────────────────────────────────────────────
  {
    slug: 'vessels-voyage-report',
    title: 'Voyage Report',
    description: 'End-of-voyage operational report',
    appSource: 'vessels',
    documentType: 'voyage_report',
    mergeFields: [
      { key: '{{vessel_name}}', label: 'Vessel Name', required: true },
      { key: '{{imo_number}}', label: 'IMO Number' },
      { key: '{{voyage_id}}', label: 'Voyage ID', required: true },
      { key: '{{departure_port}}', label: 'Departure Port' },
      { key: '{{arrival_port}}', label: 'Arrival Port' },
      { key: '{{cargo_type}}', label: 'Cargo Type' },
      { key: '{{eta}}', label: 'Arrival Date' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Voyage Report'),
        block('paragraph', 'Vessel: {{vessel_name}} (IMO: {{imo_number}}) | Voyage: {{voyage_id}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Voyage Summary'),
        block('table', '', {
          tableData: [
            ['Field', 'Value'],
            ['Departure Port', '{{departure_port}}'],
            ['Arrival Port', '{{arrival_port}}'],
            ['Arrival Date', '{{eta}}'],
            ['Cargo', '{{cargo_type}}'],
          ],
        }),
        block('heading2', 'Operational Events'),
        block('paragraph', 'Document significant events during the voyage.'),
        block('heading2', 'Fuel Consumption'),
        block('table', '', {
          tableData: [
            ['Fuel Type', 'Consumption (MT)'],
            ['HFO', ''],
            ['MGO', ''],
            ['LNG', ''],
          ],
        }),
        block('heading2', 'Weather Encountered'),
        block('paragraph', 'Document significant weather events and their impact on operations.'),
        block('heading2', "Master's Comments"),
        block('paragraph', 'Additional observations and recommendations.'),
      ],
    },
  },
  {
    slug: 'vessels-charter-party',
    title: 'Charter Party Agreement',
    description: 'Vessel charter party agreement',
    appSource: 'vessels',
    documentType: 'charter_party',
    mergeFields: [
      { key: '{{vessel_name}}', label: 'Vessel Name', required: true },
      { key: '{{imo_number}}', label: 'IMO Number' },
      { key: '{{charter_rate}}', label: 'Charter Rate', required: true },
      { key: '{{departure_port}}', label: 'Loading Port' },
      { key: '{{arrival_port}}', label: 'Discharge Port' },
      { key: '{{cargo_type}}', label: 'Cargo' },
      { key: '{{eta}}', label: 'Laycan Date' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Charter Party Agreement'),
        block('horizontal_rule', ''),
        block(
          'paragraph',
          'This Charter Party is entered into between the Owners of the Vessel "{{vessel_name}}" (IMO: {{imo_number}}) and the Charterers.',
        ),
        block('heading2', 'Part I — Principal Terms'),
        block('table', '', {
          tableData: [
            ['Term', 'Details'],
            ['Vessel', '{{vessel_name}}'],
            ['Loading Port', '{{departure_port}}'],
            ['Discharge Port', '{{arrival_port}}'],
            ['Cargo', '{{cargo_type}}'],
            ['Charter Rate', '{{charter_rate}}'],
            ['Laycan', '{{eta}}'],
          ],
        }),
        block('heading2', 'Part II — General Terms & Conditions'),
        block('heading3', '1. Payment'),
        block('paragraph', 'Freight to be paid at the rate of {{charter_rate}} per metric ton.'),
        block('heading3', '2. Laytime & Demurrage'),
        block(
          'paragraph',
          'Laytime shall be as stated in Part I. Demurrage shall be calculated at the agreed rate.',
        ),
        block('heading3', '3. General Average'),
        block('paragraph', 'General Average shall be adjusted according to York-Antwerp Rules.'),
        block('heading2', 'Signatures'),
        block('paragraph', 'Owners: _______________________'),
        block('paragraph', 'Charterers: _______________________'),
      ],
    },
  },

  // ─── Alloy ────────────────────────────────────────────────────────────────
  {
    slug: 'alloy-approval-memo',
    title: 'Workflow Approval Memo',
    description: 'Formal workflow change approval memorandum',
    appSource: 'alloy',
    documentType: 'workflow_approval_memo',
    mergeFields: [
      { key: '{{workflow_name}}', label: 'Workflow Name', required: true },
      { key: '{{requestor_name}}', label: 'Requestor', required: true },
      { key: '{{change_description}}', label: 'Change Description' },
      { key: '{{impact_assessment}}', label: 'Impact Assessment' },
      { key: '{{approval_authority}}', label: 'Approval Authority' },
      { key: '{{effective_date}}', label: 'Effective Date' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Workflow Approval Memorandum'),
        block('paragraph', 'Workflow: {{workflow_name}} | Requestor: {{requestor_name}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Change Request Summary'),
        block('paragraph', 'Description: {{change_description}}'),
        block('paragraph', 'Effective Date: {{effective_date}}'),
        block('heading2', 'Impact Assessment'),
        block('paragraph', '{{impact_assessment}}'),
        block('heading2', 'Risk Analysis'),
        block('table', '', {
          tableData: [
            ['Risk', 'Likelihood', 'Impact', 'Mitigation'],
            ['', '', '', ''],
          ],
        }),
        block('heading2', 'Approval'),
        block('paragraph', 'Approval Authority: {{approval_authority}}'),
        block('paragraph', ''),
        block('paragraph', 'Approved By: _______________________'),
        block('paragraph', 'Date: _______________________'),
      ],
    },
  },
  {
    slug: 'alloy-integration-spec',
    title: 'Integration Specification',
    description: 'Technical integration specification document',
    appSource: 'alloy',
    documentType: 'integration_spec',
    mergeFields: [
      { key: '{{workflow_name}}', label: 'Integration Name', required: true },
      { key: '{{requestor_name}}', label: 'Author' },
    ],
    content: {
      version: 1,
      blocks: [
        block('heading1', 'Integration Specification'),
        block('paragraph', '{{workflow_name}} | Author: {{requestor_name}}'),
        block('horizontal_rule', ''),
        block('heading2', 'Overview'),
        block('paragraph', 'Describe the integration purpose and business value.'),
        block('heading2', 'Architecture'),
        block('heading3', 'Data Flow'),
        block('paragraph', 'Describe the data flow between systems.'),
        block('heading3', 'Authentication'),
        block('paragraph', 'Describe authentication and authorization mechanisms.'),
        block('heading2', 'API Endpoints'),
        block('table', '', {
          tableData: [
            ['Method', 'Endpoint', 'Description', 'Auth Required'],
            ['GET', '/api/v1/...', '', 'Yes'],
          ],
        }),
        block('heading2', 'Error Handling'),
        block('paragraph', 'Describe error codes, retry logic, and fallback behavior.'),
        block('heading2', 'Testing Plan'),
        block('ordered_list', 'Unit tests'),
        block('ordered_list', 'Integration tests'),
        block('ordered_list', 'Load tests'),
      ],
    },
  },
];

export function getTemplatesByApp(appSource: AppSource): TemplateDefinition[] {
  return DOCUMENT_TEMPLATES.filter((t) => t.appSource === appSource);
}

export function getTemplateBySlug(slug: string): TemplateDefinition | undefined {
  return DOCUMENT_TEMPLATES.find((t) => t.slug === slug);
}
