// Publish the latest canonical Putnam-2025 gauge to szl-holdings/agi-forecast
// via the GitHub Contents API. Honest: we push the unmodified gauge.json +
// leaderboard.json + a tiny human-readable summary; no fudging.
//
//   GH_WORKFLOW_TOKEN=... tsx src/cli/publish-agi-forecast.ts

process.on("uncaughtException", (e) => { console.error("UNCAUGHT", (e as Error).stack); process.exit(2); });
process.on("unhandledRejection", (e) => { console.error("UNHANDLED", e); process.exit(3); });

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const OWNER = "szl-holdings";
const REPO = "agi-forecast";
const BRANCH = "main";
const TOKEN = process.env.GH_WORKFLOW_TOKEN;
if (!TOKEN) { console.error("GH_WORKFLOW_TOKEN required"); process.exit(1); }

const ROOT = join(process.cwd(), "dist", "eval");
const dirs = readdirSync(ROOT)
  .filter((d) => d.startsWith("canonical-"))
  .map((d) => ({ d, m: statSync(join(ROOT, d)).mtimeMs }))
  .sort((a, b) => b.m - a.m);
if (!dirs[0]) { console.error("no canonical-* run found"); process.exit(1); }
const src = join(ROOT, dirs[0].d);
console.log(`▶ publishing ${src}`);

const gauge = JSON.parse(readFileSync(join(src, "gauge.json"), "utf8"));
const leaderboard = JSON.parse(readFileSync(join(src, "leaderboard.json"), "utf8"));
const rootHash = readFileSync(join(src, "receipt-chain-root.txt"), "utf8").trim();

const ts = gauge.issuedAt.slice(0, 10);
const targetDir = `runtime/putnam-2025/${ts}`;

const summary = [
  `# Putnam-2025 — Honest Receipt-Attested Run`,
  ``,
  `- **Issued**: ${gauge.issuedAt}`,
  `- **Receipt class**: \`${gauge.receiptClass}\``,
  `- **Receipt-chain root**: \`${rootHash}\``,
  `- **Chain head**: \`${gauge.receiptChainHead}\``,
  `- **Tenant**: \`${gauge.tenant}\``,
  ``,
  `## Result`,
  ``,
  `- score01 = **${gauge.score01.toFixed(3)}** (${gauge.totalAwarded}/${gauge.totalPossible} pts)`,
  `- correct = **${gauge.problemsCorrect}** · partial = ${gauge.problemsPartial} · incorrect = ${gauge.problemsIncorrect} · abstained = ${gauge.problemsAbstained}`,
  `- wall = ${gauge.wallSeconds.toFixed(1)}s (sum of candidate generation only)`,
  ``,
  `## Models`,
  gauge.modelRoster.map((m: string) => `- \`${m}\``).join("\n"),
  ``,
  `## SZL primitives exercised`,
  gauge.primitiveRoster.map((m: string) => `- \`${m}\``).join("\n"),
  ``,
  `## Honesty notes`,
  ...Object.entries(leaderboard.honesty).filter(([k]) => k !== "doctrineV6").map(([, v]) => `- ${v}`),
  ``,
  `## Per-problem`,
  leaderboard.perProblem.map((p: { problemIdx: number; verdict: string; awarded: number; possible: number; pickedStrategy: string | null }) => `- P${String(p.problemIdx).padStart(2, "0")} — ${p.verdict} ${p.awarded}/${p.possible} (strategy: ${p.pickedStrategy ?? "n/a"})`).join("\n"),
  ``,
  `_Generated by \`packages/putnam-harness/src/cli/publish-agi-forecast.ts\`._`,
].join("\n");

async function putFile(path: string, content: string, message: string) {
  // Get sha if exists
  const headRes = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}?ref=${BRANCH}`, {
    headers: { authorization: `Bearer ${TOKEN}`, accept: "application/vnd.github+json" },
  });
  const existing = headRes.status === 200 ? await headRes.json() as { sha?: string } : null;
  const body = {
    message,
    content: Buffer.from(content, "utf8").toString("base64"),
    branch: BRANCH,
    ...(existing?.sha ? { sha: existing.sha } : {}),
  };
  const res = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`, {
    method: "PUT",
    headers: { authorization: `Bearer ${TOKEN}`, accept: "application/vnd.github+json", "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const json = await res.json() as { content?: { sha?: string; html_url?: string }; message?: string };
  if (!res.ok) { throw new Error(`PUT ${path} -> ${res.status}: ${json.message ?? "?"}`); }
  console.log(`  ✓ ${path} sha=${json.content?.sha?.slice(0, 8)} url=${json.content?.html_url}`);
}

(async () => {
  await putFile(`${targetDir}/gauge.json`, JSON.stringify(gauge, null, 2), `putnam-2025 ${ts}: gauge (${gauge.totalAwarded}/${gauge.totalPossible})`);
  await putFile(`${targetDir}/leaderboard.json`, JSON.stringify(leaderboard, null, 2), `putnam-2025 ${ts}: leaderboard`);
  await putFile(`${targetDir}/README.md`, summary, `putnam-2025 ${ts}: human summary`);
  await putFile(`runtime/putnam-2025/latest.json`, JSON.stringify({
    issuedAt: gauge.issuedAt,
    score01: gauge.score01,
    awarded: gauge.totalAwarded,
    possible: gauge.totalPossible,
    correct: gauge.problemsCorrect,
    partial: gauge.problemsPartial,
    incorrect: gauge.problemsIncorrect,
    abstained: gauge.problemsAbstained,
    receiptChainHead: gauge.receiptChainHead,
    receiptChainRoot: rootHash,
    sourceDir: targetDir,
    modelRoster: gauge.modelRoster,
    primitiveRoster: gauge.primitiveRoster,
  }, null, 2), `putnam-2025: latest.json pointer -> ${ts}`);
  console.log("");
  console.log(`▶ published. https://github.com/${OWNER}/${REPO}/tree/${BRANCH}/${targetDir}`);
})();
