import type { DomainConfig } from '../types.js';

export const carlotaJoConfig: DomainConfig = {
  appSlug: 'carlota-jo',
  appName: 'Carlota Jo Consulting',
  domain: 'brand-consulting',
  description: 'Brand health, client engagement, and strategic consulting impact observability',
  connectors: ['googleCalendar', 'gmail'],
  domainLensLabels: {
    signal: 'Brand health alerts ranked by sentiment shift',
    impact: 'Brand equity value, campaign ROI',
    anticipation: 'Sentiment trend prediction, competitive positioning forecast',
    topology: 'Brand-audience-channel relationship map',
    posture: 'Brand Health Score',
    velocity: 'Brand lift trend, engagement growth rate',
    postureScoreName: 'Brand Health Score',
    topSignalLabel: 'Sentiment shift detected — engagement dropping 12%',
    velocityTrendLabel: 'Brand lift trend',
  },
  metrics: [
    {
      id: 'brand_alert_rank',
      name: 'Brand Alerts (Sentiment Ranked)',
      description: 'Brand alerts ranked by sentiment shift magnitude',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'sentiment_shift_rate',
      name: 'Sentiment Shift Rate',
      description: 'Rate of brand sentiment changes detected',
      unit: '/hr',
      pillar: 'signal',
      type: 'counter',
    },
    {
      id: 'booking_signal',
      name: 'Booking Conversion Signal',
      description: 'Significant movements in consultation booking rate',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'brand_equity_value',
      name: 'Brand Equity Value',
      description: 'Estimated brand equity score across channels',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'campaign_roi',
      name: 'Campaign ROI',
      description: 'Return on investment for consulting campaigns',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'strategic_impact_score',
      name: 'Strategic Impact Score',
      description: 'Measured impact of consulting engagements',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'sentiment_trend_prediction',
      name: 'Sentiment Trend Prediction',
      description: 'Accuracy of brand sentiment trajectory forecasting',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'competitive_positioning_forecast',
      name: 'Competitive Positioning Forecast',
      description: 'Predicted market position trajectory',
      unit: 'score',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'demand_forecast',
      name: 'Booking Demand Forecast',
      description: 'Predicted booking volume accuracy',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'brand_audience_graph',
      name: 'Brand-Audience Graph Coverage',
      description: 'Percentage of audience segments mapped to brand touchpoints',
      unit: '%',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'channel_relationship_health',
      name: 'Channel Relationship Health',
      description: 'Health of brand-audience-channel topology',
      unit: 'score',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'brand_health_score',
      name: 'Brand Health Score',
      description: 'Composite brand health metric',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
      thresholds: { warning: 70, critical: 50, direction: 'below' },
    },
    {
      id: 'consultation_booking_rate',
      name: 'Consultation Booking Rate',
      description: 'Rate of completed consultation bookings',
      unit: '%',
      pillar: 'posture',
      type: 'gauge',
    },
    {
      id: 'brand_lift_trend',
      name: 'Brand Lift Trend',
      description: 'Week-over-week brand lift improvement',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'engagement_growth_rate',
      name: 'Engagement Growth Rate',
      description: 'Rate of engagement growth across channels',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'deploy_frequency',
      name: 'Campaign Deployment Frequency',
      description: 'New consulting campaigns launched per month',
      unit: 'count',
      pillar: 'velocity',
      type: 'counter',
    },
  ],
  kpis: [
    {
      id: 'brand_health',
      name: 'Brand Health Score',
      pillar: 'posture',
      format: 'score',
      target: 85,
    },
    {
      id: 'equity_value',
      name: 'Brand Equity Value',
      pillar: 'impact',
      format: 'score',
      target: 80,
    },
    {
      id: 'sentiment_accuracy',
      name: 'Sentiment Forecast Accuracy',
      pillar: 'anticipation',
      format: 'percent',
      target: 85,
    },
    {
      id: 'brand_lift',
      name: 'Brand Lift Trend',
      pillar: 'velocity',
      format: 'percent',
      target: 10,
    },
  ],
  healthSignals: [
    {
      id: 'sentiment_alert',
      name: 'Sentiment Shift Critical',
      pillar: 'signal',
      severity: 'critical',
      condition: 'Sentiment score drops > 15% in 24h',
    },
    {
      id: 'equity_at_risk',
      name: 'Brand Equity at Risk',
      pillar: 'impact',
      severity: 'warning',
      condition: 'Brand equity value score < 60',
    },
    {
      id: 'sentiment_negative_forecast',
      name: 'Negative Sentiment Trending',
      pillar: 'anticipation',
      severity: 'warning',
      condition: 'Sentiment trend prediction shows continued decline',
    },
    {
      id: 'brand_health_low',
      name: 'Brand Health Below Target',
      pillar: 'posture',
      severity: 'critical',
      condition: 'Brand Health Score < 50',
    },
  ],
};
