import type { DomainConfig } from '../types.js';

export const dreamscapeConfig: DomainConfig = {
  appSlug: 'alloy-creative',
  appName: 'Alloy Creative Engine',
  domain: 'creative',
  description: 'Asset pipeline, campaign performance, and creative workflow observability',
  connectors: ['ai', 'storage', 'elevenlabs'],
  domainLensLabels: {
    signal: 'Campaign alerts ranked by launch deadline proximity',
    impact: 'Missed-window cost, brand exposure value',
    anticipation: 'Campaign performance prediction, content calendar risk',
    topology: 'Asset-campaign-channel dependency graph',
    posture: 'Creative Pipeline Health Score',
    velocity: 'Content production throughput, approval cycle speed',
    postureScoreName: 'Creative Pipeline Health Score',
    topSignalLabel: 'Campaign deadline at risk — 72h to launch',
    velocityTrendLabel: 'Content production throughput',
  },
  metrics: [
    {
      id: 'campaign_alert_rank',
      name: 'Campaign Alerts (Deadline Ranked)',
      description: 'Active campaign alerts ranked by deadline proximity',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'asset_render_time',
      name: 'Asset Render Time',
      description: 'Time to render creative assets',
      unit: 'ms',
      pillar: 'signal',
      type: 'histogram',
      thresholds: { warning: 3000, critical: 8000, direction: 'above' },
    },
    {
      id: 'deadline_risk_count',
      name: 'Deadlines at Risk',
      description: 'Number of campaigns with deadline risk',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'missed_window_cost',
      name: 'Missed-Window Cost Exposure',
      description: 'Revenue exposure from delayed campaign launches',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'brand_exposure_value',
      name: 'Brand Exposure Value',
      description: 'Estimated brand value at stake per campaign',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'campaign_conversion_lift',
      name: 'Campaign Conversion Lift',
      description: 'Improvement in conversion from creative optimization',
      unit: '%',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'campaign_performance_pred',
      name: 'Campaign Performance Prediction',
      description: 'Accuracy of predicted campaign outcomes',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'content_calendar_risk',
      name: 'Content Calendar Risk Score',
      description: 'Risk score for upcoming content calendar items',
      unit: 'score',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'trend_prediction_accuracy',
      name: 'Creative Trend Forecast Accuracy',
      description: 'Accuracy of creative trend predictions',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'asset_campaign_graph',
      name: 'Asset-Campaign Topology Coverage',
      description: 'Percentage of assets with full campaign dependency mapping',
      unit: '%',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'channel_dependency_health',
      name: 'Channel Dependency Health',
      description: 'Health of asset-campaign-channel graph',
      unit: 'score',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'creative_pipeline_score',
      name: 'Creative Pipeline Health Score',
      description: 'Composite creative pipeline health',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
      thresholds: { warning: 70, critical: 50, direction: 'below' },
    },
    {
      id: 'brand_consistency_score',
      name: 'Brand Consistency Score',
      description: 'Adherence to brand guidelines across assets',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
    },
    {
      id: 'content_throughput',
      name: 'Content Production Throughput',
      description: 'Assets produced and approved per week',
      unit: 'count',
      pillar: 'velocity',
      type: 'counter',
    },
    {
      id: 'approval_cycle_speed',
      name: 'Approval Cycle Speed',
      description: 'Week-over-week improvement in approval cycle time',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'deploy_frequency',
      name: 'Campaign Deployment Frequency',
      description: 'Campaigns launched per week',
      unit: 'count',
      pillar: 'velocity',
      type: 'counter',
    },
  ],
  kpis: [
    {
      id: 'pipeline_health',
      name: 'Creative Pipeline Health',
      pillar: 'posture',
      format: 'score',
      target: 85,
    },
    {
      id: 'window_exposure',
      name: 'Missed-Window Cost Exposure',
      pillar: 'impact',
      format: 'currency',
      target: 0,
    },
    {
      id: 'perf_prediction',
      name: 'Performance Prediction Accuracy',
      pillar: 'anticipation',
      format: 'percent',
      target: 85,
    },
    {
      id: 'content_velocity',
      name: 'Content Throughput',
      pillar: 'velocity',
      format: 'number',
      target: 30,
    },
  ],
  healthSignals: [
    {
      id: 'deadline_critical',
      name: 'Campaign Deadline Critical',
      pillar: 'signal',
      severity: 'critical',
      condition: 'Campaign deadline < 24h with incomplete assets',
    },
    {
      id: 'window_exposure_high',
      name: 'Missed-Window Exposure High',
      pillar: 'impact',
      severity: 'warning',
      condition: 'Missed-window cost exposure > 70 score',
    },
    {
      id: 'calendar_risk_high',
      name: 'Content Calendar at Risk',
      pillar: 'anticipation',
      severity: 'warning',
      condition: 'Content calendar risk score > 80',
    },
    {
      id: 'pipeline_health_low',
      name: 'Creative Pipeline Health Low',
      pillar: 'posture',
      severity: 'critical',
      condition: 'Creative Pipeline Health Score < 50',
    },
  ],
};
