import type { DomainConfig } from '../types.js';

export const firestormConfig: DomainConfig = {
  appSlug: 'firestorm',
  appName: 'Firestorm Security Simulation',
  domain: 'cybersecurity',
  description: 'Threat detection, incident response, and security posture observability',
  connectors: ['ai', 'slack'],
  domainLensLabels: {
    signal: 'Threat feed ranked by blast radius',
    impact: 'Potential breach cost & compliance fine exposure',
    anticipation: 'Attack trajectory prediction & threat actor modeling',
    topology: 'Attack surface graph with kill chain mapping',
    posture: 'Security Posture Score',
    velocity: 'MTTR improvement, detection-to-containment speedup',
    postureScoreName: 'Security Posture Score',
    topSignalLabel: 'Active lateral movement — blast radius: critical',
    velocityTrendLabel: 'Detection-to-containment speed',
  },
  metrics: [
    {
      id: 'threat_detection_rate',
      name: 'Threat Detection Rate',
      description: 'Threats identified per hour ranked by severity',
      unit: '/hr',
      pillar: 'signal',
      type: 'counter',
    },
    {
      id: 'detection_latency',
      name: 'Detection Latency',
      description: 'Time from threat emergence to detection',
      unit: 'ms',
      pillar: 'signal',
      type: 'histogram',
      thresholds: { warning: 500, critical: 2000, direction: 'above' },
    },
    {
      id: 'alert_blast_radius',
      name: 'Alert Blast Radius Score',
      description: 'AI-ranked blast radius of top active alert',
      unit: 'score',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'breach_cost_exposure',
      name: 'Breach Cost Exposure',
      description: 'Estimated cost of potential breach in progress',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'compliance_fine_exposure',
      name: 'Compliance Fine Exposure',
      description: 'Regulatory fine exposure from current posture',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'risk_reduction_roi',
      name: 'Risk Reduction ROI',
      description: 'Return on security investment via risk reduction',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'threat_forecast_accuracy',
      name: 'Threat Forecast Accuracy',
      description: 'Predictive model accuracy for threat trajectory',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'attack_trajectory_score',
      name: 'Attack Trajectory Score',
      description: 'Predicted severity of current threat trajectory',
      unit: 'score',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'behavioral_baseline_drift',
      name: 'Behavioral Baseline Drift',
      description: 'Deviation from established behavioral baselines',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'attack_surface_graph',
      name: 'Attack Surface Graph Coverage',
      description: 'Percentage of attack surface mapped with kill chains',
      unit: '%',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'mitre_coverage',
      name: 'MITRE ATT&CK Coverage',
      description: 'Percentage of MITRE techniques with detection rules',
      unit: '%',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'security_posture_score',
      name: 'Security Posture Score',
      description: 'Composite security posture rating',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
      thresholds: { warning: 60, critical: 40, direction: 'below' },
    },
    {
      id: 'compliance_score',
      name: 'Compliance Posture Score',
      description: 'Overall regulatory compliance rating',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
      thresholds: { warning: 70, critical: 50, direction: 'below' },
    },
    {
      id: 'endpoint_coverage',
      name: 'Endpoint Coverage',
      description: 'Percentage of endpoints with active monitoring',
      unit: '%',
      pillar: 'posture',
      type: 'gauge',
    },
    {
      id: 'mttr',
      name: 'Mean Time to Containment',
      description: 'Average time to contain security threats',
      unit: 'seconds',
      pillar: 'velocity',
      type: 'gauge',
      thresholds: { warning: 300, critical: 600, direction: 'above' },
    },
    {
      id: 'detection_velocity',
      name: 'Detection-to-Containment Speed',
      description: 'Week-over-week improvement in D2C speed',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'vuln_remediation_velocity',
      name: 'Vulnerability Remediation Rate',
      description: 'Rate of vulnerability resolution per week',
      unit: '/hr',
      pillar: 'velocity',
      type: 'gauge',
    },
  ],
  kpis: [
    {
      id: 'security_posture',
      name: 'Security Posture Score',
      pillar: 'posture',
      format: 'score',
      target: 85,
    },
    {
      id: 'breach_exposure',
      name: 'Breach Cost Exposure',
      pillar: 'impact',
      format: 'currency',
      target: 0,
    },
    {
      id: 'trajectory',
      name: 'Threat Trajectory Score',
      pillar: 'anticipation',
      format: 'score',
      target: 20,
    },
    {
      id: 'd2c_velocity',
      name: 'Detection-to-Containment',
      pillar: 'velocity',
      format: 'duration',
      target: 60,
    },
  ],
  healthSignals: [
    {
      id: 'critical_threat_open',
      name: 'Critical Threat Uncontained',
      pillar: 'signal',
      severity: 'critical',
      condition: 'Critical severity threat open > 30min',
    },
    {
      id: 'breach_exposure_high',
      name: 'Breach Cost Exposure Critical',
      pillar: 'impact',
      severity: 'critical',
      condition: 'Breach cost exposure > 80 score',
    },
    {
      id: 'trajectory_escalating',
      name: 'Attack Trajectory Escalating',
      pillar: 'anticipation',
      severity: 'warning',
      condition: 'Attack trajectory score increasing > 15% hour-over-hour',
    },
    {
      id: 'posture_low',
      name: 'Security Posture Below Threshold',
      pillar: 'posture',
      severity: 'critical',
      condition: 'Security Posture Score < 40',
    },
  ],
};
