import type { DomainConfig } from "../types.js";

export const mspConfig: DomainConfig = {
  appSlug: "msp",
  appName: "MSP Command Center",
  domain: "managed-services",
  description: "Managed service provider operations, client management, and service delivery observability",
  connectors: ["ticketing", "monitoring", "rmm"],
  maturityLevel: 3,
  businessContext: "Revenue-driving service delivery platform — every SLA violation costs trust and margin",
  domainLensLabels: {
    signal: "Client health alerts ranked by MRR at risk",
    impact: "Revenue impact of downtime per client",
    anticipation: "Infrastructure failure prediction, ticket volume forecasting",
    topology: "Client-device-service dependency map",
    posture: "NOC Health Score",
    velocity: "Ticket resolution speed trend, patch compliance rate",
    postureScoreName: "NOC Health Score",
    topSignalLabel: "Client SLA breach — MRR at risk: $47K",
    velocityTrendLabel: "Ticket resolution throughput",
  },
  metrics: [
    { id: "client_alert_rank", name: "Active Client Alerts (MRR Ranked)", description: "Client alerts ranked by MRR at risk", unit: "count", pillar: "signal", type: "gauge" },
    { id: "noc_response_time", name: "NOC Response Time", description: "Time from alert to first response in NOC", unit: "seconds", pillar: "signal", type: "histogram", thresholds: { warning: 300, critical: 900, direction: "above" } },
    { id: "sla_breach_risk", name: "SLA Breach Risk", description: "Number of tickets approaching SLA breach", unit: "count", pillar: "signal", type: "gauge" },
    { id: "mrr_at_risk", name: "MRR at Risk", description: "Monthly recurring revenue at risk due to active incidents", unit: "score", pillar: "impact", type: "gauge" },
    { id: "downtime_cost", name: "Downtime Cost Exposure", description: "Revenue impact of current client downtime", unit: "score", pillar: "impact", type: "gauge" },
    { id: "sla_compliance", name: "SLA Compliance Rate", description: "Percentage of tickets meeting SLA targets", unit: "%", pillar: "impact", type: "gauge", thresholds: { warning: 95, critical: 90, direction: "below" } },
    { id: "device_failure_prediction", name: "Device Failure Prediction", description: "Accuracy of predictive device failure alerts", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "ticket_volume_forecast", name: "Ticket Volume Forecast", description: "Accuracy of ticket volume prediction", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "capacity_forecast", name: "Capacity Forecast Accuracy", description: "Accuracy of client infrastructure capacity predictions", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "client_device_map", name: "Client-Device Topology Health", description: "Health of client-device-service dependency graph", unit: "score", pillar: "topology", type: "gauge" },
    { id: "service_dependency_health", name: "Service Dependency Health", description: "Health of inter-service dependencies", unit: "score", pillar: "topology", type: "gauge" },
    { id: "noc_health_score", name: "NOC Health Score", description: "Composite NOC operational health", unit: "score", pillar: "posture", type: "gauge", thresholds: { warning: 70, critical: 50, direction: "below" } },
    { id: "endpoint_protection", name: "Endpoint Protection Coverage", description: "Percentage of managed devices with active protection", unit: "%", pillar: "posture", type: "gauge", thresholds: { warning: 95, critical: 90, direction: "below" } },
    { id: "patch_compliance", name: "Patch Compliance Rate", description: "Percentage of devices fully patched", unit: "%", pillar: "posture", type: "gauge" },
    { id: "ticket_resolution_trend", name: "Ticket Resolution Speed Trend", description: "Week-over-week improvement in ticket resolution speed", unit: "%", pillar: "velocity", type: "gauge" },
    { id: "automation_coverage", name: "Automation Coverage", description: "Percentage of routine tasks automated", unit: "%", pillar: "velocity", type: "gauge" },
    { id: "deploy_frequency", name: "Configuration Deployments", description: "Configuration deployments per day", unit: "count", pillar: "velocity", type: "counter" },
  ],
  kpis: [
    { id: "noc_health", name: "NOC Health Score", pillar: "posture", format: "score", target: 85 },
    { id: "mrr_risk", name: "MRR at Risk", pillar: "impact", format: "currency", target: 0 },
    { id: "failure_predict", name: "Failure Prediction Accuracy", pillar: "anticipation", format: "percent", target: 90 },
    { id: "resolution_velocity", name: "Resolution Velocity", pillar: "velocity", format: "percent", target: 15 },
  ],
  healthSignals: [
    { id: "sla_breach", name: "SLA Breach Risk", pillar: "signal", severity: "critical", condition: "SLA compliance < 90%" },
    { id: "mrr_exposure", name: "MRR Exposure Critical", pillar: "impact", severity: "critical", condition: "MRR at risk > $50K" },
    { id: "device_failure_imminent", name: "Device Failure Predicted", pillar: "anticipation", severity: "warning", condition: "Failure prediction score > 80" },
    { id: "noc_health_low", name: "NOC Health Below Target", pillar: "posture", severity: "critical", condition: "NOC Health Score < 50" },
  ],
};
