import type { DomainConfig } from "../types.js";

export const mspConfig: DomainConfig = {
  appSlug: "msp",
  appName: "MSP Command Center",
  domain: "managed-services",
  description: "Managed service provider operations, client management, and service delivery observability",
  connectors: ["ticketing", "monitoring", "rmm"],
  maturityLevel: 3,
  businessContext: "Revenue-driving service delivery platform — every SLA violation costs trust and margin",
  metrics: [
    { id: "ticket_resolution_time", name: "Ticket Resolution Time", description: "Average time to resolve service tickets", unit: "seconds", pillar: "performance", type: "histogram", thresholds: { warning: 3600, critical: 14400, direction: "above" } },
    { id: "noc_response_time", name: "NOC Response Time", description: "Time from alert to first response in NOC", unit: "seconds", pillar: "performance", type: "histogram", thresholds: { warning: 300, critical: 900, direction: "above" } },
    { id: "device_sync_latency", name: "Device Sync Latency", description: "Time to sync device inventory from RMM", unit: "ms", pillar: "performance", type: "gauge" },
    { id: "mrr", name: "Monthly Recurring Revenue", description: "Total contracted monthly recurring revenue", unit: "score", pillar: "business", type: "gauge" },
    { id: "client_churn_rate", name: "Client Churn Rate", description: "Monthly client cancellation rate", unit: "%", pillar: "business", type: "gauge", thresholds: { warning: 5, critical: 10, direction: "above" } },
    { id: "sla_compliance", name: "SLA Compliance Rate", description: "Percentage of tickets meeting SLA targets", unit: "%", pillar: "business", type: "gauge", thresholds: { warning: 95, critical: 90, direction: "below" } },
    { id: "revenue_per_device", name: "Revenue Per Device", description: "Average monthly revenue per managed device", unit: "score", pillar: "business", type: "gauge" },
    { id: "portal_satisfaction", name: "Client Portal Satisfaction", description: "Client satisfaction with self-service portal", unit: "score", pillar: "userExperience", type: "gauge" },
    { id: "tech_utilization", name: "Technician Utilization", description: "Percentage of technician time on billable work", unit: "%", pillar: "userExperience", type: "gauge" },
    { id: "first_contact_resolution", name: "First Contact Resolution", description: "Tickets resolved on first interaction", unit: "%", pillar: "userExperience", type: "gauge" },
    { id: "device_failure_prediction", name: "Device Failure Prediction", description: "Accuracy of predictive device failure alerts", unit: "%", pillar: "predictiveHealth", type: "gauge" },
    { id: "capacity_forecast", name: "Capacity Forecast Accuracy", description: "Accuracy of client infrastructure capacity predictions", unit: "%", pillar: "predictiveHealth", type: "gauge" },
    { id: "rmm_health", name: "RMM Platform Health", description: "Remote monitoring and management tool availability", unit: "score", pillar: "operational", type: "gauge" },
    { id: "psa_integration", name: "PSA Integration Health", description: "Professional services automation sync status", unit: "score", pillar: "operational", type: "gauge" },
    { id: "client_lifetime_value", name: "Client Lifetime Value", description: "Average projected revenue per client", unit: "score", pillar: "strategic", type: "gauge" },
    { id: "market_penetration", name: "Market Penetration Index", description: "Service adoption rate across client base", unit: "score", pillar: "strategic", type: "gauge" },
    { id: "threat_surface_score", name: "Threat Surface Score", description: "Composite attack surface exposure rating", unit: "score", pillar: "securityPosture", type: "gauge", thresholds: { warning: 60, critical: 40, direction: "below" } },
    { id: "compliance_drift", name: "Compliance Drift Index", description: "Deviation from baseline compliance posture", unit: "%", pillar: "securityPosture", type: "gauge", thresholds: { warning: 10, critical: 25, direction: "above" } },
    { id: "endpoint_protection", name: "Endpoint Protection Coverage", description: "Percentage of managed devices with active protection", unit: "%", pillar: "securityPosture", type: "gauge", thresholds: { warning: 95, critical: 90, direction: "below" } },
    { id: "deploy_frequency", name: "Deployment Frequency", description: "Configuration deployments per day", unit: "count", pillar: "innovationVelocity", type: "counter" },
    { id: "change_failure_rate", name: "Change Failure Rate", description: "Percentage of changes causing incidents", unit: "%", pillar: "innovationVelocity", type: "gauge", thresholds: { warning: 15, critical: 30, direction: "above" } },
    { id: "automation_coverage", name: "Automation Coverage", description: "Percentage of routine tasks automated", unit: "%", pillar: "innovationVelocity", type: "gauge" },
  ],
  kpis: [
    { id: "sla_rate", name: "SLA Compliance", pillar: "business", format: "percent", target: 99 },
    { id: "mrr_target", name: "MRR Growth", pillar: "business", format: "currency", target: 100000 },
    { id: "resolution_sla", name: "Resolution Time", pillar: "performance", format: "duration", target: 3600 },
    { id: "security_score", name: "Security Posture", pillar: "securityPosture", format: "score", target: 90 },
    { id: "automation_rate", name: "Automation Rate", pillar: "innovationVelocity", format: "percent", target: 70 },
  ],
  healthSignals: [
    { id: "sla_breach", name: "SLA Breach", pillar: "business", severity: "critical", condition: "SLA compliance < 90%" },
    { id: "noc_overload", name: "NOC Overload", pillar: "operational", severity: "warning", condition: "NOC queue > 50 tickets" },
    { id: "endpoint_gap", name: "Endpoint Protection Gap", pillar: "securityPosture", severity: "critical", condition: "Unprotected devices > 5%" },
    { id: "high_churn", name: "High Client Churn", pillar: "business", severity: "critical", condition: "Monthly churn > 10%" },
  ],
};
