import type { DomainConfig } from "../types.js";

export const readinessReportConfig: DomainConfig = {
  appSlug: "readiness-report",
  appName: "Readiness Report",
  domain: "compliance-readiness",
  description: "Compliance gaps, audit readiness, and framework adherence observability",
  connectors: ["ai", "notion"],
  domainLensLabels: {
    signal: "Compliance gaps ranked by audit deadline proximity",
    impact: "Non-compliance fine exposure, certification risk",
    anticipation: "Compliance drift forecasting, audit readiness projection",
    topology: "Control-framework-vendor risk graph",
    posture: "Compliance Readiness Score",
    velocity: "Gap closure rate, evidence collection speed",
    postureScoreName: "Compliance Readiness Score",
    topSignalLabel: "NIST CSF gap — audit deadline: 14 days",
    velocityTrendLabel: "Gap closure rate",
  },
  metrics: [
    { id: "compliance_gap_rank", name: "Compliance Gaps (Deadline Ranked)", description: "Active compliance gaps ranked by audit deadline proximity", unit: "count", pillar: "signal", type: "gauge" },
    { id: "audit_deadline_proximity", name: "Audit Deadline Proximity Score", description: "Urgency score based on nearest audit deadline", unit: "score", pillar: "signal", type: "gauge" },
    { id: "unresolved_controls", name: "Unresolved Controls", description: "Number of unresolved control failures", unit: "count", pillar: "signal", type: "gauge" },
    { id: "fine_exposure", name: "Non-Compliance Fine Exposure", description: "Estimated regulatory fine exposure from current gaps", unit: "score", pillar: "impact", type: "gauge" },
    { id: "certification_risk", name: "Certification Risk Score", description: "Risk of losing or failing certification due to gaps", unit: "score", pillar: "impact", type: "gauge" },
    { id: "compliance_score", name: "Current Compliance Score", description: "Aggregate compliance score across all frameworks", unit: "score", pillar: "impact", type: "gauge" },
    { id: "compliance_drift_forecast", name: "Compliance Drift Forecast", description: "Predicted compliance trajectory over 90 days", unit: "score", pillar: "anticipation", type: "gauge" },
    { id: "audit_readiness_projection", name: "Audit Readiness Projection", description: "Projected readiness score at next audit date", unit: "score", pillar: "anticipation", type: "gauge" },
    { id: "gap_identification_accuracy", name: "Gap Identification Accuracy", description: "Accuracy of identified readiness gaps", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "control_framework_graph", name: "Control-Framework Graph Coverage", description: "Percentage of controls mapped to frameworks", unit: "%", pillar: "topology", type: "gauge" },
    { id: "vendor_risk_graph", name: "Vendor Risk Graph Health", description: "Health of vendor-control risk dependency graph", unit: "score", pillar: "topology", type: "gauge" },
    { id: "compliance_readiness_score", name: "Compliance Readiness Score", description: "Composite compliance readiness metric", unit: "score", pillar: "posture", type: "gauge", thresholds: { warning: 70, critical: 50, direction: "below" } },
    { id: "framework_adherence", name: "Framework Adherence Score", description: "Overall adherence to NIST CSF / ISO 27001 / CMMC", unit: "score", pillar: "posture", type: "gauge" },
    { id: "gap_closure_rate", name: "Gap Closure Rate", description: "Number of compliance gaps closed per week", unit: "count", pillar: "velocity", type: "counter" },
    { id: "evidence_collection_speed", name: "Evidence Collection Speed", description: "Week-over-week improvement in evidence collection", unit: "%", pillar: "velocity", type: "gauge" },
    { id: "assessment_throughput", name: "Assessment Throughput", description: "Assessments completed per week", unit: "count", pillar: "velocity", type: "counter" },
  ],
  kpis: [
    { id: "readiness_score", name: "Compliance Readiness Score", pillar: "posture", format: "score", target: 85 },
    { id: "fine_exposure_kpi", name: "Fine Exposure", pillar: "impact", format: "currency", target: 0 },
    { id: "drift_forecast", name: "Compliance Drift Forecast", pillar: "anticipation", format: "score", target: 90 },
    { id: "gap_closure", name: "Gap Closure Rate", pillar: "velocity", format: "number", target: 10 },
  ],
  healthSignals: [
    { id: "audit_deadline_critical", name: "Audit Deadline Critical", pillar: "signal", severity: "critical", condition: "Audit deadline < 30 days with open critical gaps" },
    { id: "fine_exposure_high", name: "Fine Exposure Critical", pillar: "impact", severity: "critical", condition: "Fine exposure score > 80" },
    { id: "compliance_drift_alert", name: "Compliance Drift Detected", pillar: "anticipation", severity: "warning", condition: "Projected compliance score dropping > 10 points" },
    { id: "readiness_low", name: "Compliance Readiness Below Target", pillar: "posture", severity: "critical", condition: "Compliance Readiness Score < 50" },
  ],
};
