import type { DomainConfig } from '../types.js';

export const stephenSiteConfig: DomainConfig = {
  appSlug: 'stephen-site',
  appName: 'Stephen Lutar',
  domain: 'personal-brand',
  description:
    'Personal brand performance, thought leadership reach, and audience engagement observability',
  connectors: ['stripe', 'ai'],
  domainLensLabels: {
    signal: 'Audience engagement alerts ranked by reach impact',
    impact: 'Brand equity value, thought leadership ROI',
    anticipation: 'Audience growth prediction, content performance forecast',
    topology: 'Content-audience-channel relationship map',
    posture: 'Brand Authority Score',
    velocity: 'Audience growth rate, content engagement velocity',
    postureScoreName: 'Brand Authority Score',
    topSignalLabel: 'Content spike detected — thought leadership reach +340%',
    velocityTrendLabel: 'Audience growth velocity',
  },
  metrics: [
    {
      id: 'engagement_signal_rank',
      name: 'Engagement Signals (Reach Ranked)',
      description: 'Audience engagement alerts ranked by reach impact',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'content_performance_signal',
      name: 'Content Performance Signal',
      description: 'Significant content engagement movements detected',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'page_performance',
      name: 'Page Performance Score',
      description: 'Core Web Vitals composite score',
      unit: 'score',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'brand_equity_value',
      name: 'Brand Equity Value',
      description: 'Estimated personal brand equity across channels',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'thought_leadership_roi',
      name: 'Thought Leadership ROI',
      description: 'Return on thought leadership content investment',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'checkout_revenue',
      name: 'Revenue from Brand',
      description: 'Revenue driven by brand presence',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'audience_growth_prediction',
      name: 'Audience Growth Prediction',
      description: 'Predicted audience growth trajectory accuracy',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'content_performance_forecast',
      name: 'Content Performance Forecast',
      description: 'Predicted content engagement outcomes',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'engagement_trend',
      name: 'Engagement Trend Prediction',
      description: 'Predicted engagement trajectory',
      unit: 'score',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'content_audience_graph',
      name: 'Content-Audience Topology Coverage',
      description: 'Percentage of content mapped to audience segments',
      unit: '%',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'channel_influence_map',
      name: 'Channel Influence Map Health',
      description: 'Health of content-audience-channel relationship graph',
      unit: 'score',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'brand_authority_score',
      name: 'Brand Authority Score',
      description: 'Composite personal brand authority metric',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
      thresholds: { warning: 70, critical: 50, direction: 'below' },
    },
    {
      id: 'domain_authority',
      name: 'Domain Authority',
      description: 'Domain authority and influence measure',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
    },
    {
      id: 'audience_growth_rate',
      name: 'Audience Growth Rate',
      description: 'Week-over-week audience growth',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'content_engagement_velocity',
      name: 'Content Engagement Velocity',
      description: 'Rate of content engagement growth',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'deploy_frequency',
      name: 'Content Publish Frequency',
      description: 'New content published per week',
      unit: 'count',
      pillar: 'velocity',
      type: 'counter',
    },
  ],
  kpis: [
    {
      id: 'brand_authority',
      name: 'Brand Authority Score',
      pillar: 'posture',
      format: 'score',
      target: 80,
    },
    {
      id: 'brand_equity',
      name: 'Brand Equity Value',
      pillar: 'impact',
      format: 'score',
      target: 75,
    },
    {
      id: 'audience_forecast',
      name: 'Growth Forecast Accuracy',
      pillar: 'anticipation',
      format: 'percent',
      target: 85,
    },
    {
      id: 'growth_velocity',
      name: 'Audience Growth Velocity',
      pillar: 'velocity',
      format: 'percent',
      target: 10,
    },
  ],
  healthSignals: [
    {
      id: 'engagement_drop',
      name: 'Engagement Drop Detected',
      pillar: 'signal',
      severity: 'warning',
      condition: 'Engagement rate drops > 20% week-over-week',
    },
    {
      id: 'equity_declining',
      name: 'Brand Equity Declining',
      pillar: 'impact',
      severity: 'warning',
      condition: 'Brand equity value score < 60',
    },
    {
      id: 'growth_stalling',
      name: 'Audience Growth Stalling',
      pillar: 'anticipation',
      severity: 'warning',
      condition: 'Growth prediction shows flat trajectory',
    },
    {
      id: 'authority_low',
      name: 'Brand Authority Below Target',
      pillar: 'posture',
      severity: 'warning',
      condition: 'Brand Authority Score < 50',
    },
  ],
};
