import type { DomainConfig } from "../types.js";

export const szlHoldingsConfig: DomainConfig = {
  appSlug: "szl-holdings",
  appName: "SZL Holdings",
  domain: "portfolio-management",
  description: "Portfolio operations, subsidiary performance, and holdings intelligence observability",
  connectors: ["stripe", "hubspot"],
  domainLensLabels: {
    signal: "Portfolio signals ranked by capital exposure",
    impact: "Portfolio value at risk, investment yield impact",
    anticipation: "Market trend forecasting, portfolio risk projection",
    topology: "Venture-domain-capital relationship ecosystem map",
    posture: "Portfolio Health Score",
    velocity: "Portfolio growth velocity, deployment cadence",
    postureScoreName: "Portfolio Health Score",
    topSignalLabel: "Subsidiary performance signal — capital exposure flagged",
    velocityTrendLabel: "Portfolio growth velocity",
  },
  metrics: [
    { id: "portfolio_signal_rank", name: "Portfolio Signals (Capital Ranked)", description: "Portfolio signals ranked by capital at risk", unit: "count", pillar: "signal", type: "gauge" },
    { id: "subsidiary_alert_count", name: "Subsidiary Alert Count", description: "Active alerts across portfolio companies", unit: "count", pillar: "signal", type: "gauge" },
    { id: "data_freshness", name: "Portfolio Data Freshness", description: "Latency of portfolio intelligence updates", unit: "seconds", pillar: "signal", type: "gauge" },
    { id: "portfolio_value_at_risk", name: "Portfolio Value at Risk", description: "Capital exposure from active risk signals", unit: "score", pillar: "impact", type: "gauge" },
    { id: "investment_yield", name: "Investment Yield", description: "Return on portfolio investments", unit: "%", pillar: "impact", type: "gauge" },
    { id: "subsidiary_performance", name: "Subsidiary Performance Index", description: "Aggregate subsidiary health score", unit: "score", pillar: "impact", type: "gauge" },
    { id: "market_trend_accuracy", name: "Market Trend Forecast Accuracy", description: "Accuracy of portfolio market trend predictions", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "risk_forecast", name: "Portfolio Risk Forecast", description: "Projected portfolio risk trajectory", unit: "score", pillar: "anticipation", type: "gauge" },
    { id: "portfolio_growth_prediction", name: "Portfolio Growth Prediction", description: "Predicted portfolio value growth trajectory", unit: "score", pillar: "anticipation", type: "gauge" },
    { id: "ecosystem_topology", name: "Ecosystem Topology Coverage", description: "Percentage of ventures with full relationship mapping", unit: "%", pillar: "topology", type: "gauge" },
    { id: "capital_flow_graph", name: "Capital Flow Graph Health", description: "Health of venture-domain-capital dependency graph", unit: "score", pillar: "topology", type: "gauge" },
    { id: "portfolio_health_score", name: "Portfolio Health Score", description: "Composite portfolio health metric", unit: "score", pillar: "posture", type: "gauge", thresholds: { warning: 70, critical: 50, direction: "below" } },
    { id: "compliance_system_health", name: "Compliance System Health", description: "Regulatory compliance system availability", unit: "score", pillar: "posture", type: "gauge" },
    { id: "portfolio_growth_velocity", name: "Portfolio Growth Velocity", description: "Quarter-over-quarter portfolio value growth rate", unit: "%", pillar: "velocity", type: "gauge" },
    { id: "deployment_cadence", name: "Capital Deployment Cadence", description: "Rate of new capital deployments per quarter", unit: "count", pillar: "velocity", type: "counter" },
    { id: "subsidiary_improvement_rate", name: "Subsidiary Improvement Rate", description: "Rate of subsidiary performance improvement", unit: "%", pillar: "velocity", type: "gauge" },
  ],
  kpis: [
    { id: "portfolio_health", name: "Portfolio Health Score", pillar: "posture", format: "score", target: 85 },
    { id: "capital_at_risk", name: "Capital at Risk", pillar: "impact", format: "currency", target: 0 },
    { id: "market_forecast", name: "Market Forecast Accuracy", pillar: "anticipation", format: "percent", target: 85 },
    { id: "growth_velocity", name: "Growth Velocity", pillar: "velocity", format: "percent", target: 15 },
  ],
  healthSignals: [
    { id: "capital_exposure", name: "Capital Exposure Critical", pillar: "signal", severity: "critical", condition: "Portfolio value at risk score > 80" },
    { id: "subsidiary_declining", name: "Subsidiary Performance Declining", pillar: "impact", severity: "warning", condition: "Subsidiary performance index < 60" },
    { id: "risk_forecast_high", name: "Portfolio Risk Forecast Elevated", pillar: "anticipation", severity: "warning", condition: "Portfolio risk forecast > 70 score" },
    { id: "portfolio_health_low", name: "Portfolio Health Below Target", pillar: "posture", severity: "critical", condition: "Portfolio Health Score < 50" },
  ],
};
