import type { DomainConfig } from "../types.js";

export const terraConfig: DomainConfig = {
  appSlug: "terra",
  appName: "Terra Real Estate Intelligence",
  domain: "real-estate",
  description: "Property portfolio, market intelligence, and investment analysis observability",
  connectors: ["zillow", "mls", "costar"],
  maturityLevel: 3,
  businessContext: "Investment-grade real estate intelligence — every data delay costs opportunity",
  metrics: [
    { id: "property_valuation_time", name: "Valuation Computation Time", description: "Time to compute property fair market value", unit: "ms", pillar: "performance", type: "histogram", thresholds: { warning: 1000, critical: 3000, direction: "above" } },
    { id: "market_data_refresh", name: "Market Data Refresh Rate", description: "Frequency of market intelligence updates", unit: "seconds", pillar: "performance", type: "gauge" },
    { id: "api_response_time", name: "API Response Time", description: "Backend query response latency", unit: "ms", pillar: "performance", type: "histogram" },
    { id: "portfolio_noi", name: "Portfolio Net Operating Income", description: "Total NOI across managed properties", unit: "score", pillar: "business", type: "gauge" },
    { id: "occupancy_rate", name: "Occupancy Rate", description: "Percentage of units currently occupied", unit: "%", pillar: "business", type: "gauge", thresholds: { warning: 90, critical: 80, direction: "below" } },
    { id: "cap_rate_accuracy", name: "Cap Rate Accuracy", description: "Accuracy of projected vs actual cap rates", unit: "%", pillar: "business", type: "gauge" },
    { id: "deal_pipeline_velocity", name: "Deal Pipeline Velocity", description: "Average time from opportunity to close", unit: "seconds", pillar: "business", type: "gauge" },
    { id: "investor_portal_engagement", name: "Investor Portal Engagement", description: "Session depth on investor-facing dashboards", unit: "count", pillar: "userExperience", type: "gauge" },
    { id: "report_generation_time", name: "Report Generation Time", description: "Time to generate investment analysis reports", unit: "ms", pillar: "userExperience", type: "histogram" },
    { id: "search_relevance", name: "Property Search Relevance", description: "Quality score of property search results", unit: "score", pillar: "userExperience", type: "gauge" },
    { id: "market_trend_accuracy", name: "Market Trend Forecast Accuracy", description: "Accuracy of predictive market analytics", unit: "%", pillar: "predictiveHealth", type: "gauge" },
    { id: "vacancy_prediction", name: "Vacancy Prediction Score", description: "Accuracy of predicted vacancy rates", unit: "%", pillar: "predictiveHealth", type: "gauge" },
    { id: "mls_feed_health", name: "MLS Feed Health", description: "MLS data integration availability", unit: "score", pillar: "operational", type: "gauge" },
    { id: "valuation_model_health", name: "Valuation Model Health", description: "ML model serving status", unit: "score", pillar: "operational", type: "gauge" },
    { id: "irr_performance", name: "Portfolio IRR", description: "Internal rate of return across portfolio", unit: "score", pillar: "strategic", type: "gauge" },
    { id: "market_positioning", name: "Market Positioning Index", description: "Competitive advantage score vs market peers", unit: "score", pillar: "strategic", type: "gauge" },
    { id: "data_privacy_score", name: "Data Privacy Compliance", description: "Investor data protection compliance rating", unit: "score", pillar: "securityPosture", type: "gauge", thresholds: { warning: 80, critical: 60, direction: "below" } },
    { id: "access_control_audit", name: "Access Control Audit Score", description: "Role-based access control compliance", unit: "score", pillar: "securityPosture", type: "gauge" },
    { id: "compliance_drift", name: "Compliance Drift Index", description: "Deviation from regulatory baseline", unit: "%", pillar: "securityPosture", type: "gauge", thresholds: { warning: 10, critical: 25, direction: "above" } },
    { id: "deploy_frequency", name: "Deployment Frequency", description: "Platform deployments per week", unit: "count", pillar: "innovationVelocity", type: "counter" },
    { id: "feature_lead_time", name: "Feature Lead Time", description: "Time from request to production", unit: "seconds", pillar: "innovationVelocity", type: "gauge" },
    { id: "model_retraining_freq", name: "Model Retraining Frequency", description: "How often valuation models are retrained", unit: "count", pillar: "innovationVelocity", type: "counter" },
  ],
  kpis: [
    { id: "occupancy", name: "Occupancy Rate", pillar: "business", format: "percent", target: 95 },
    { id: "noi_target", name: "Portfolio NOI", pillar: "business", format: "currency", target: 5000000 },
    { id: "forecast_accuracy", name: "Forecast Accuracy", pillar: "predictiveHealth", format: "percent", target: 90 },
    { id: "security_score", name: "Data Privacy Score", pillar: "securityPosture", format: "score", target: 90 },
    { id: "deploy_freq", name: "Deploy Frequency", pillar: "innovationVelocity", format: "number", target: 3 },
  ],
  healthSignals: [
    { id: "low_occupancy", name: "Low Occupancy Alert", pillar: "business", severity: "critical", condition: "Occupancy < 80%" },
    { id: "mls_outage", name: "MLS Feed Outage", pillar: "operational", severity: "critical", condition: "MLS data stale > 24h" },
    { id: "privacy_violation", name: "Data Privacy Risk", pillar: "securityPosture", severity: "critical", condition: "Privacy score < 60" },
    { id: "deal_stall", name: "Deal Pipeline Stalled", pillar: "business", severity: "warning", condition: "No pipeline movement > 14 days" },
  ],
};
