import type { DomainConfig } from '../types.js';

export const vesselsConfig: DomainConfig = {
  appSlug: 'vessels',
  appName: 'Vessels Maritime Intelligence',
  domain: 'maritime',
  description: 'Fleet operations, voyage optimization, and maritime intelligence observability',
  connectors: ['shipping', 'stormglass', 'weather'],
  domainLensLabels: {
    signal: 'Fleet alerts ranked by cargo value at risk',
    impact: 'Fuel cost, demurrage & sanctions exposure in USD',
    anticipation: 'ETA predictions, weather-route optimization',
    topology: 'Vessel-port-route network graph',
    posture: 'Fleet Readiness Score',
    velocity: 'Port turnaround improvement trend',
    postureScoreName: 'Fleet Readiness Score',
    topSignalLabel: 'High-value cargo vessel off-route',
    velocityTrendLabel: 'Port turnaround speed',
  },
  metrics: [
    {
      id: 'route_calc_time',
      name: 'Route Calculation Time',
      description: 'Time to compute optimal voyage route',
      unit: 'ms',
      pillar: 'signal',
      type: 'histogram',
      thresholds: { warning: 500, critical: 2000, direction: 'above' },
    },
    {
      id: 'ais_data_latency',
      name: 'AIS Data Latency',
      description: 'Delay in receiving vessel position updates',
      unit: 'ms',
      pillar: 'signal',
      type: 'gauge',
      thresholds: { warning: 300, critical: 1000, direction: 'above' },
    },
    {
      id: 'fleet_alert_count',
      name: 'Active Fleet Alerts',
      description: 'Number of AI-ranked active alerts across fleet',
      unit: 'count',
      pillar: 'signal',
      type: 'gauge',
    },
    {
      id: 'cargo_value_at_risk',
      name: 'Cargo Value at Risk',
      description: 'Dollar value of cargo on at-risk vessels',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'fuel_cost_exposure',
      name: 'Fuel Cost Exposure',
      description: 'Projected fuel cost delta from route deviation',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
    },
    {
      id: 'demurrage_risk',
      name: 'Demurrage Risk',
      description: 'Port delay cost exposure in USD',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
      thresholds: { warning: 60, critical: 80, direction: 'above' },
    },
    {
      id: 'co2_compliance',
      name: 'CO2 Compliance Score',
      description: 'Fleet-wide emissions compliance rating',
      unit: 'score',
      pillar: 'impact',
      type: 'gauge',
      thresholds: { warning: 70, critical: 50, direction: 'below' },
    },
    {
      id: 'eta_prediction_accuracy',
      name: 'ETA Prediction Accuracy',
      description: 'Accuracy of estimated arrival predictions',
      unit: '%',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'weather_route_forecast',
      name: 'Weather Route Forecast',
      description: 'Hours ahead predicted for optimal routing',
      unit: 'count',
      pillar: 'anticipation',
      type: 'gauge',
    },
    {
      id: 'anomaly_detection_rate',
      name: 'Anomaly Detection Rate',
      description: 'Behavioral anomalies detected per hour',
      unit: '/hr',
      pillar: 'anticipation',
      type: 'counter',
    },
    {
      id: 'vessel_port_connections',
      name: 'Active Route Connections',
      description: 'Live vessel-port route relationships tracked',
      unit: 'count',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'network_health',
      name: 'Network Topology Health',
      description: 'Health of vessel-port-route graph',
      unit: 'score',
      pillar: 'topology',
      type: 'gauge',
    },
    {
      id: 'fleet_readiness_score',
      name: 'Fleet Readiness Score',
      description: 'Composite fleet operational readiness',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
      thresholds: { warning: 70, critical: 50, direction: 'below' },
    },
    {
      id: 'safety_index',
      name: 'Maritime Safety Index',
      description: 'Composite fleet safety score',
      unit: 'score',
      pillar: 'posture',
      type: 'gauge',
    },
    {
      id: 'port_turnaround_trend',
      name: 'Port Turnaround Trend',
      description: 'Week-over-week improvement in port turnaround speed',
      unit: '%',
      pillar: 'velocity',
      type: 'gauge',
    },
    {
      id: 'deploy_frequency',
      name: 'Deployment Frequency',
      description: 'Platform updates deployed per day',
      unit: 'count',
      pillar: 'velocity',
      type: 'counter',
    },
    {
      id: 'mttr',
      name: 'Fleet Issue MTTR',
      description: 'Mean time to resolve fleet operational issues',
      unit: 'seconds',
      pillar: 'velocity',
      type: 'gauge',
      thresholds: { warning: 3600, critical: 14400, direction: 'above' },
    },
  ],
  kpis: [
    {
      id: 'fleet_readiness',
      name: 'Fleet Readiness Score',
      pillar: 'posture',
      format: 'score',
      target: 85,
    },
    {
      id: 'eta_accuracy',
      name: 'ETA Prediction Accuracy',
      pillar: 'anticipation',
      format: 'percent',
      target: 95,
    },
    {
      id: 'fuel_cost',
      name: 'Fuel Cost Exposure',
      pillar: 'impact',
      format: 'currency',
      target: 0,
    },
    {
      id: 'port_turnaround',
      name: 'Port Turnaround Velocity',
      pillar: 'velocity',
      format: 'percent',
      target: 10,
    },
  ],
  healthSignals: [
    {
      id: 'vessel_offline',
      name: 'Vessel AIS Signal Lost',
      pillar: 'signal',
      severity: 'critical',
      condition: 'Vessel AIS signal lost > 30min',
    },
    {
      id: 'high_demurrage',
      name: 'Demurrage Exposure Critical',
      pillar: 'impact',
      severity: 'warning',
      condition: 'Demurrage risk score > 60',
    },
    {
      id: 'eta_drift',
      name: 'ETA Prediction Drift',
      pillar: 'anticipation',
      severity: 'warning',
      condition: 'ETA accuracy below 80%',
    },
    {
      id: 'fleet_readiness_low',
      name: 'Fleet Readiness Below Target',
      pillar: 'posture',
      severity: 'critical',
      condition: 'Fleet Readiness Score < 50',
    },
  ],
};
