import type { DomainConfig } from "../types.js";

export const incaConfig: DomainConfig = {
  appSlug: "inca",
  appName: "INCA AI Research Command Center",
  domain: "ai-research",
  description: "Experiment tracking, model performance, and research pipeline observability",
  connectors: ["ai", "huggingface", "storage"],
  domainLensLabels: {
    signal: "Experiment alerts ranked by compute cost",
    impact: "GPU cost per insight, model accuracy vs. training investment",
    anticipation: "Training convergence prediction, resource exhaustion forecasting",
    topology: "Model-dataset-experiment lineage graph",
    posture: "Research Pipeline Health Score",
    velocity: "Experiment throughput, model improvement rate",
    postureScoreName: "Research Pipeline Health Score",
    topSignalLabel: "Training run diverging — A100 cluster at 94% utilization",
    velocityTrendLabel: "Experiment throughput",
  },
  metrics: [
    { id: "experiment_alerts_ranked", name: "Experiment Alerts (Cost Ranked)", description: "Alerts ranked by GPU cost impact", unit: "count", pillar: "signal", type: "gauge" },
    { id: "model_drift_detection", name: "Model Drift Detection Rate", description: "Rate of detected model performance drift", unit: "/hr", pillar: "signal", type: "counter" },
    { id: "gpu_utilization", name: "GPU Utilization", description: "Compute resource utilization rate", unit: "%", pillar: "signal", type: "gauge" },
    { id: "gpu_cost_per_insight", name: "GPU Cost Per Insight", description: "Compute cost normalized per research finding", unit: "score", pillar: "impact", type: "gauge" },
    { id: "training_investment_roi", name: "Training Investment ROI", description: "Model accuracy gain per dollar of training compute", unit: "score", pillar: "impact", type: "gauge" },
    { id: "experiment_success_rate", name: "Experiment Success Rate", description: "Percentage of experiments meeting objectives", unit: "%", pillar: "impact", type: "gauge", thresholds: { warning: 60, critical: 40, direction: "below" } },
    { id: "training_convergence_pred", name: "Training Convergence Prediction", description: "Accuracy of convergence forecasting", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "resource_exhaustion_forecast", name: "Resource Exhaustion Forecast", description: "Hours until compute exhaustion at current rate", unit: "count", pillar: "anticipation", type: "gauge" },
    { id: "data_quality_score", name: "Data Quality Score", description: "Input data quality assessment", unit: "score", pillar: "anticipation", type: "gauge" },
    { id: "model_lineage_graph", name: "Model-Dataset Lineage Coverage", description: "Percentage of models with full lineage tracked", unit: "%", pillar: "topology", type: "gauge" },
    { id: "experiment_dependencies", name: "Experiment Dependency Health", description: "Health of cross-experiment dependency graph", unit: "score", pillar: "topology", type: "gauge" },
    { id: "pipeline_health_score", name: "Research Pipeline Health Score", description: "Composite research pipeline health", unit: "score", pillar: "posture", type: "gauge", thresholds: { warning: 70, critical: 50, direction: "below" } },
    { id: "compute_cluster_health", name: "Compute Cluster Health", description: "Training infrastructure status", unit: "score", pillar: "posture", type: "gauge" },
    { id: "model_accuracy_improvement", name: "Model Improvement Rate", description: "Week-over-week model accuracy gain", unit: "%", pillar: "velocity", type: "gauge" },
    { id: "experiment_throughput", name: "Experiment Throughput", description: "Experiments completed per week", unit: "count", pillar: "velocity", type: "counter" },
    { id: "deploy_frequency", name: "Model Deployment Frequency", description: "Models deployed to production per week", unit: "count", pillar: "velocity", type: "counter" },
  ],
  kpis: [
    { id: "pipeline_health", name: "Research Pipeline Health", pillar: "posture", format: "score", target: 85 },
    { id: "gpu_cost_efficiency", name: "GPU Cost Per Insight", pillar: "impact", format: "score", target: 50 },
    { id: "convergence_accuracy", name: "Convergence Prediction", pillar: "anticipation", format: "percent", target: 90 },
    { id: "exp_throughput", name: "Experiment Throughput", pillar: "velocity", format: "number", target: 20 },
  ],
  healthSignals: [
    { id: "high_cost_experiment", name: "High-Cost Experiment Alert", pillar: "signal", severity: "warning", condition: "GPU cost per insight > 80 score" },
    { id: "gpu_exhaustion", name: "GPU Resource Exhaustion Predicted", pillar: "anticipation", severity: "critical", condition: "Resource exhaustion forecast < 4 hours" },
    { id: "model_degradation", name: "Model Performance Degradation", pillar: "anticipation", severity: "warning", condition: "Model accuracy dropped > 5% in 24h" },
    { id: "pipeline_health_low", name: "Pipeline Health Below Target", pillar: "posture", severity: "critical", condition: "Research Pipeline Health Score < 50" },
  ],
};
