import type { DomainConfig } from "../types.js";

export const lyteCommandCenterConfig: DomainConfig = {
  appSlug: "lyte-command-center",
  appName: "Lyte Command Center",
  domain: "operations-command",
  description: "Cross-portfolio operations, signal aggregation, and incident management observability",
  connectors: ["slack", "ai", "posthog"],
  domainLensLabels: {
    signal: "Operational anomalies ranked by service impact",
    impact: "SLA breach cost, user-facing degradation in dollars",
    anticipation: "Incident prediction from signal correlation",
    topology: "Full infrastructure topology with live health",
    posture: "Operational Readiness Score",
    velocity: "Incident resolution speed, deployment frequency",
    postureScoreName: "Operational Readiness Score",
    topSignalLabel: "Service degradation — SLA breach imminent",
    velocityTrendLabel: "Incident resolution throughput",
  },
  metrics: [
    { id: "signal_ingestion_rate", name: "Signal Ingestion Rate (Ranked)", description: "Operational anomalies processed and ranked per hour", unit: "/hr", pillar: "signal", type: "counter" },
    { id: "alert_noise_ratio", name: "Signal-to-Noise Ratio", description: "Ratio of actionable alerts vs noise", unit: "%", pillar: "signal", type: "gauge" },
    { id: "top_signal_severity", name: "Top Signal Severity Score", description: "Severity of highest-ranked active signal", unit: "score", pillar: "signal", type: "gauge" },
    { id: "sla_breach_cost", name: "SLA Breach Cost Exposure", description: "Estimated cost of SLA breaches in progress", unit: "score", pillar: "impact", type: "gauge" },
    { id: "user_degradation_cost", name: "User-Facing Degradation Cost", description: "Revenue impact of degraded user experience", unit: "score", pillar: "impact", type: "gauge" },
    { id: "incident_cost_savings", name: "Incident Cost Savings", description: "Estimated cost savings from fast resolution", unit: "score", pillar: "impact", type: "gauge" },
    { id: "incident_prediction", name: "Incident Prediction Accuracy", description: "Accuracy of predictive incident detection from correlation", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "correlation_engine_latency", name: "Correlation Engine Latency", description: "Time to correlate cross-signal incidents", unit: "ms", pillar: "anticipation", type: "histogram", thresholds: { warning: 200, critical: 1000, direction: "above" } },
    { id: "capacity_forecast", name: "Capacity Forecast Accuracy", description: "Infrastructure capacity prediction accuracy", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "topology_coverage", name: "Topology Coverage", description: "Percentage of infrastructure mapped in live topology", unit: "%", pillar: "topology", type: "gauge" },
    { id: "dependency_health", name: "Dependency Graph Health", description: "Health of monitored dependency relationships", unit: "score", pillar: "topology", type: "gauge" },
    { id: "operational_readiness_score", name: "Operational Readiness Score", description: "Composite operations health and readiness", unit: "score", pillar: "posture", type: "gauge", thresholds: { warning: 70, critical: 50, direction: "below" } },
    { id: "reliability_budget", name: "Reliability Budget Remaining", description: "Error budget consumption status", unit: "%", pillar: "posture", type: "gauge" },
    { id: "sla_compliance", name: "SLA Compliance Rate", description: "Percentage of incidents resolved within SLA", unit: "%", pillar: "posture", type: "gauge", thresholds: { warning: 90, critical: 80, direction: "below" } },
    { id: "mttr", name: "Mean Time to Resolution", description: "Average incident resolution time", unit: "seconds", pillar: "velocity", type: "gauge" },
    { id: "deploy_frequency", name: "Deployment Frequency", description: "Deployments per day", unit: "count", pillar: "velocity", type: "counter" },
    { id: "resolution_velocity_trend", name: "Resolution Velocity Trend", description: "Week-over-week improvement in incident resolution speed", unit: "%", pillar: "velocity", type: "gauge" },
  ],
  kpis: [
    { id: "ops_readiness", name: "Operational Readiness Score", pillar: "posture", format: "score", target: 85 },
    { id: "sla_breach_cost_kpi", name: "SLA Breach Cost Exposure", pillar: "impact", format: "currency", target: 0 },
    { id: "incident_predict", name: "Incident Prediction Accuracy", pillar: "anticipation", format: "percent", target: 90 },
    { id: "mttr_kpi", name: "MTTR", pillar: "velocity", format: "duration", target: 1800 },
  ],
  healthSignals: [
    { id: "top_signal_critical", name: "Critical Signal Active", pillar: "signal", severity: "critical", condition: "Top signal severity score > 80" },
    { id: "sla_breach_imminent", name: "SLA Breach Cost Rising", pillar: "impact", severity: "critical", condition: "SLA breach cost exposure > 80 score" },
    { id: "cascade_failure", name: "Cascade Failure Risk", pillar: "anticipation", severity: "critical", condition: "Multiple correlated failures detected" },
    { id: "readiness_low", name: "Operational Readiness Below Target", pillar: "posture", severity: "critical", condition: "Operational Readiness Score < 50" },
  ],
};
