import type { DomainConfig } from "../types.js";

export const terraConfig: DomainConfig = {
  appSlug: "terra",
  appName: "Terra Real Estate Intelligence",
  domain: "real-estate",
  description: "Property portfolio, market intelligence, and investment analysis observability",
  connectors: ["zillow", "mls", "costar"],
  maturityLevel: 3,
  businessContext: "Investment-grade real estate intelligence — every data delay costs opportunity",
  domainLensLabels: {
    signal: "Market movement alerts ranked by portfolio exposure",
    impact: "Property value at risk, rental income impact",
    anticipation: "Market trend forecasting, climate risk projection",
    topology: "Property-market-tenant relationship graph",
    posture: "Portfolio Health Score",
    velocity: "Deal pipeline velocity, occupancy trend",
    postureScoreName: "Portfolio Health Score",
    topSignalLabel: "Market shift detected — 3 properties in affected zone",
    velocityTrendLabel: "Deal pipeline velocity",
  },
  metrics: [
    { id: "market_alert_rank", name: "Market Alerts (Exposure Ranked)", description: "Market alerts ranked by portfolio exposure", unit: "count", pillar: "signal", type: "gauge" },
    { id: "occupancy_signal", name: "Occupancy Trend Signal", description: "Significant occupancy movements detected", unit: "count", pillar: "signal", type: "gauge" },
    { id: "market_data_refresh", name: "Market Data Freshness", description: "Latency of market intelligence updates", unit: "seconds", pillar: "signal", type: "gauge" },
    { id: "property_value_at_risk", name: "Property Value at Risk", description: "Portfolio value exposed to current market risk", unit: "score", pillar: "impact", type: "gauge" },
    { id: "rental_income_exposure", name: "Rental Income Exposure", description: "Rental income at risk from current signals", unit: "score", pillar: "impact", type: "gauge" },
    { id: "portfolio_noi", name: "Portfolio NOI", description: "Total net operating income across managed properties", unit: "score", pillar: "impact", type: "gauge" },
    { id: "market_trend_accuracy", name: "Market Trend Forecast Accuracy", description: "Accuracy of predictive market analytics", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "vacancy_prediction", name: "Vacancy Prediction Accuracy", description: "Accuracy of predicted vacancy rates", unit: "%", pillar: "anticipation", type: "gauge" },
    { id: "climate_risk_projection", name: "Climate Risk Projection", description: "Climate risk score for portfolio properties", unit: "score", pillar: "anticipation", type: "gauge" },
    { id: "property_market_graph", name: "Property-Market Graph Coverage", description: "Percentage of properties with full market relationship mapping", unit: "%", pillar: "topology", type: "gauge" },
    { id: "tenant_relationship_health", name: "Tenant Relationship Health", description: "Health of property-tenant dependency graph", unit: "score", pillar: "topology", type: "gauge" },
    { id: "portfolio_health_score", name: "Portfolio Health Score", description: "Composite portfolio operational health", unit: "score", pillar: "posture", type: "gauge", thresholds: { warning: 70, critical: 50, direction: "below" } },
    { id: "occupancy_rate", name: "Occupancy Rate", description: "Percentage of units currently occupied", unit: "%", pillar: "posture", type: "gauge", thresholds: { warning: 90, critical: 80, direction: "below" } },
    { id: "deal_pipeline_velocity", name: "Deal Pipeline Velocity", description: "Average time from opportunity to close", unit: "seconds", pillar: "velocity", type: "gauge" },
    { id: "occupancy_trend", name: "Occupancy Trend Rate", description: "Week-over-week occupancy improvement", unit: "%", pillar: "velocity", type: "gauge" },
    { id: "model_retraining_freq", name: "Model Retraining Frequency", description: "How often valuation models are retrained", unit: "count", pillar: "velocity", type: "counter" },
  ],
  kpis: [
    { id: "portfolio_health", name: "Portfolio Health Score", pillar: "posture", format: "score", target: 85 },
    { id: "value_at_risk", name: "Property Value at Risk", pillar: "impact", format: "currency", target: 0 },
    { id: "market_forecast", name: "Market Forecast Accuracy", pillar: "anticipation", format: "percent", target: 90 },
    { id: "deal_velocity", name: "Deal Pipeline Velocity", pillar: "velocity", format: "duration", target: 30 },
  ],
  healthSignals: [
    { id: "portfolio_exposure", name: "Portfolio Value Exposure Critical", pillar: "signal", severity: "critical", condition: "Value at risk score > 80" },
    { id: "low_occupancy", name: "Occupancy Below Target", pillar: "posture", severity: "critical", condition: "Occupancy < 80%" },
    { id: "market_shift", name: "Market Shift Predicted", pillar: "anticipation", severity: "warning", condition: "Market trend forecast shows >10% deviation" },
    { id: "deal_stall", name: "Deal Pipeline Stalled", pillar: "velocity", severity: "warning", condition: "No pipeline movement > 14 days" },
  ],
};
