import type { Outcome } from '../schema.js';

const h = (hours: number) => new Date(Date.now() - hours * 3_600_000).toISOString();
const m = (mins: number) => new Date(Date.now() - mins * 60_000).toISOString();

export const SEED_OUTCOMES: Outcome[] = [
  {
    id: 'out-001',
    title: 'Recover Mid-Market Churn — Q2 2026',
    description: 'Re-engage three at-risk mid-market accounts through executive outreach and targeted relief program to prevent $180K ARR churn.',
    vertical: 'lyte-revenue',
    status: 'in_progress',
    owner: 'Head of Customer Success, KORA',
    targetDate: '2026-05-31',
    successMetric: 'All three accounts issue cancellation withdrawal',
    currentValue: 1,
    targetValue: 3,
    unit: 'accounts retained',
    linkedSignalIds: ['sig-lyte-002'],
    createdAt: h(18),
    updatedAt: h(2),
  },
  {
    id: 'out-002',
    title: 'Resolve Wilshire Covenant Breach — 30 Days',
    description: 'Execute lease-up strategy to reduce Wilshire office vacancy below 30% covenant threshold within 30 days.',
    vertical: 'terra-real-estate',
    status: 'in_progress',
    owner: 'Portfolio Director, LA',
    targetDate: '2026-05-25',
    successMetric: 'Vacancy rate below 30% and lender notified of remediation plan',
    currentValue: 34,
    targetValue: 29,
    unit: '% vacancy',
    linkedSignalIds: ['sig-terra-001'],
    createdAt: h(2),
    updatedAt: h(1),
  },
  {
    id: 'out-003',
    title: 'Remediate CMMC Level 2 Gaps — Pre-Audit',
    description: 'Close 14 non-compliant CMMC Level 2 controls before the October certification audit to protect $42M in DoD contract renewals.',
    vertical: 'aegis-defense',
    status: 'in_progress',
    owner: 'Compliance Officer, PARAGON',
    targetDate: '2026-09-30',
    successMetric: 'All 14 controls achieving passing status in pre-audit self-assessment',
    currentValue: 3,
    targetValue: 14,
    unit: 'controls remediated',
    linkedSignalIds: ['sig-aegis-003'],
    createdAt: h(120),
    updatedAt: h(48),
  },
  {
    id: 'out-004',
    title: 'Resolve SIRE 2.0 Non-Compliance — 4 SEXTANT',
    description: 'Bring all 4 tankers below SIRE 2.0 threshold to 75+ score through targeted safety culture and operational improvements.',
    vertical: 'vessels-maritime',
    status: 'pending',
    owner: 'Fleet Compliance Officer',
    targetDate: '2026-07-31',
    successMetric: 'All 4 vessels achieving SIRE 2.0 score ≥75',
    currentValue: 0,
    targetValue: 4,
    unit: 'vessels compliant',
    linkedSignalIds: ['sig-vessels-002'],
    createdAt: h(36),
    updatedAt: h(12),
  },
  {
    id: 'out-005',
    title: 'Reduce Signal Mesh Latency Below Threshold',
    description: 'Resolve state engine snapshot contention causing P95 signal ingestion latency to drop below 200ms threshold.',
    vertical: 'alloy-core',
    status: 'in_progress',
    owner: 'Platform Engineering, A11oy',
    targetDate: '2026-04-26',
    successMetric: 'P95 signal ingestion latency sustained below 200ms for 24h',
    currentValue: 340,
    targetValue: 200,
    unit: 'ms P95 latency',
    linkedSignalIds: ['sig-alloy-001'],
    createdAt: h(2),
    updatedAt: m(30),
  },
];
