import type { ProofCarryingExecutionContract } from '../schema.js';

export const SEED_PCE_CONTRACTS: ProofCarryingExecutionContract[] = [
  {
    id: 'pce-001',
    actionId: 'act-001',
    originSignalId: 'sig-lyte-002',
    causalChainIds: ['sig-lyte-002', 'twin-lyte-revenue'],
    policyEvaluationId: 'pe-001',
    approvalRecordId: 'ar-001',
    executionTraceId: 'trace-001',
    proofPacketId: 'proof-001',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-002',
    actionId: 'act-002',
    originSignalId: 'sig-terra-001',
    causalChainIds: ['sig-terra-001', 'twin-terra-la'],
    policyEvaluationId: 'pe-002',
    approvalRecordId: 'ar-002',
    executionTraceId: 'trace-002',
    proofPacketId: 'proof-002',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-003',
    actionId: 'act-003',
    originSignalId: 'sig-aegis-003',
    causalChainIds: ['sig-aegis-003'],
    policyEvaluationId: 'pe-003',
    executionTraceId: 'trace-003',
    proofPacketId: 'proof-003',
    mode: 'autonomous',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-004',
    actionId: 'act-004',
    originSignalId: 'sig-vessels-002',
    causalChainIds: ['sig-vessels-002'],
    policyEvaluationId: 'pe-004',
    executionTraceId: 'trace-004',
    proofPacketId: 'proof-004',
    mode: 'supervised',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-005',
    actionId: 'act-005',
    originSignalId: 'sig-alloy-001',
    causalChainIds: ['sig-alloy-001'],
    policyEvaluationId: 'pe-005',
    executionTraceId: 'trace-005',
    proofPacketId: 'proof-005',
    mode: 'demo',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-006',
    actionId: 'act-006',
    originSignalId: 'sig-carlota-001',
    causalChainIds: ['sig-carlota-001'],
    policyEvaluationId: 'pe-006',
    executionTraceId: 'trace-006',
    proofPacketId: 'proof-006',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-007',
    actionId: 'act-007',
    originSignalId: 'sig-counsel-001',
    causalChainIds: ['sig-counsel-001'],
    policyEvaluationId: 'pe-007',
    executionTraceId: 'trace-007',
    proofPacketId: 'proof-007',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-008',
    actionId: 'act-008',
    originSignalId: 'sig-lyte-003',
    causalChainIds: ['sig-lyte-003'],
    policyEvaluationId: 'pe-008',
    executionTraceId: 'trace-008',
    proofPacketId: 'proof-008',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-009',
    actionId: 'act-009',
    originSignalId: 'sig-terra-003',
    causalChainIds: ['sig-terra-003'],
    policyEvaluationId: 'pe-009',
    executionTraceId: 'trace-009',
    proofPacketId: 'proof-009',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-010',
    actionId: 'act-010',
    originSignalId: 'sig-aegis-001',
    causalChainIds: ['sig-aegis-001'],
    policyEvaluationId: 'pe-010',
    approvalRecordId: 'ar-010',
    executionTraceId: 'trace-010',
    proofPacketId: 'proof-010',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-011',
    actionId: 'act-011',
    originSignalId: 'sig-vessels-001',
    causalChainIds: ['sig-vessels-001'],
    policyEvaluationId: 'pe-011',
    executionTraceId: 'trace-011',
    proofPacketId: 'proof-011',
    mode: 'supervised',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-012',
    actionId: 'act-012',
    originSignalId: 'sig-counsel-004',
    causalChainIds: ['sig-counsel-004'],
    policyEvaluationId: 'pe-012',
    approvalRecordId: 'ar-012',
    executionTraceId: 'trace-012',
    proofPacketId: 'proof-012',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-013',
    actionId: 'act-013',
    originSignalId: 'sig-lyte-001',
    causalChainIds: ['sig-lyte-001'],
    policyEvaluationId: 'pe-013',
    executionTraceId: 'trace-013',
    proofPacketId: 'proof-013',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-014',
    actionId: 'act-014',
    originSignalId: 'sig-terra-005',
    causalChainIds: ['sig-terra-005'],
    policyEvaluationId: 'pe-014',
    approvalRecordId: 'ar-014',
    executionTraceId: 'trace-014',
    proofPacketId: 'proof-014',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-015',
    actionId: 'act-015',
    originSignalId: 'sig-aegis-004',
    causalChainIds: ['sig-aegis-004'],
    policyEvaluationId: 'pe-015',
    executionTraceId: 'trace-015',
    proofPacketId: 'proof-015',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-016',
    actionId: 'act-016',
    originSignalId: 'sig-vessels-004',
    causalChainIds: ['sig-vessels-004'],
    policyEvaluationId: 'pe-016',
    executionTraceId: 'trace-016',
    proofPacketId: 'proof-016',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-017',
    actionId: 'act-017',
    originSignalId: 'sig-counsel-003',
    causalChainIds: ['sig-counsel-003'],
    policyEvaluationId: 'pe-017',
    executionTraceId: 'trace-017',
    proofPacketId: 'proof-017',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-018',
    actionId: 'act-018',
    originSignalId: 'sig-carlota-004',
    causalChainIds: ['sig-carlota-004'],
    policyEvaluationId: 'pe-018',
    executionTraceId: 'trace-018',
    proofPacketId: 'proof-018',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-019',
    actionId: 'act-019',
    originSignalId: 'sig-alloy-002',
    causalChainIds: ['sig-alloy-002'],
    policyEvaluationId: 'pe-019',
    executionTraceId: 'trace-019',
    proofPacketId: 'proof-019',
    mode: 'demo',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pce-020',
    actionId: 'act-020',
    originSignalId: 'sig-lyte-006',
    causalChainIds: ['sig-lyte-006'],
    policyEvaluationId: 'pe-020',
    executionTraceId: 'trace-020',
    proofPacketId: 'proof-020',
    mode: 'governed',
    isVerified: true,
    verifiedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];
