import type { CovenantPolicy } from '../schema.js';

export const SEED_POLICIES: CovenantPolicy[] = [
  {
    id: 'pol-001',
    name: 'No Financial Commitments Without Executive Approval',
    description: 'Any action creating or modifying a financial commitment exceeding $50K requires executive-tier approval before execution.',
    vertical: 'global',
    enforcement: 'require_approval',
    conditions: [{ field: 'action.financialImpactUSD', operator: 'gt', value: 50000 }],
    approvalRequirements: { tier: 'executive', quorum: 1 },
    active: true,
    version: 2,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },
  {
    id: 'pol-002',
    name: 'Block Critical-Severity Actions Without Proof',
    description: 'Actions responding to critical-severity signals must carry a valid ProofCarryingExecution contract before they may proceed.',
    vertical: 'global',
    enforcement: 'block',
    conditions: [
      { field: 'signal.severity', operator: 'eq', value: 'critical' },
      { field: 'action.proofPacketId', operator: 'eq', value: null },
    ],
    active: true,
    version: 1,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'pol-003',
    name: 'Defense — Require Board Approval for ISR Posture Changes',
    description: 'Any change to ISR asset posture, tasking, or coverage sector requires board-level approval.',
    vertical: 'aegis-defense',
    enforcement: 'require_approval',
    conditions: [{ field: 'action.category', operator: 'eq', value: 'isr_posture_change' }],
    approvalRequirements: { tier: 'board', quorum: 2 },
    active: true,
    version: 1,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'pol-004',
    name: 'Maritime — Automatic Demurrage Alert on Diversion',
    description: 'When a vessel diversion is confirmed, automatically log a demurrage exposure alert and assign to operations controller.',
    vertical: 'vessels-maritime',
    enforcement: 'log',
    conditions: [{ field: 'signal.tags', operator: 'contains', value: 'diversion' }],
    active: true,
    version: 1,
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
  },
  {
    id: 'pol-005',
    name: 'Legal — Warn on Contract Unsigned >45 Days',
    description: 'When a contract in the CLM pipeline has been pending signature for more than 45 days, issue a priority warning to legal operations.',
    vertical: 'prism-counsel',
    enforcement: 'warn',
    conditions: [{ field: 'contract.daysPendingSignature', operator: 'gt', value: 45 }],
    active: true,
    version: 1,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
  },
];
