import type { BusinessSignal } from '../schema.js';

const minus = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString();
const now = () => new Date().toISOString();

export const SEED_SIGNALS: BusinessSignal[] = [
  {
    id: 'sig-lyte-001',
    vertical: 'lyte-revenue',
    entity: 'Lyte Platform — Enterprise ARR',
    title: 'ARR Growth Rate Deceleration',
    description: 'Enterprise ARR growth rate has declined from 34% to 21% QoQ — below the 28% target threshold.',
    severity: 'high',
    status: 'active',
    businessImpact: 'At current trajectory, Q3 ARR target of $4.2M will be missed by ~$680K.',
    evidenceRefs: ['lyte/billing/arr-2026-q2', 'lyte/crm/pipeline-stage-analysis'],
    owner: 'VP Revenue, Lyte',
    detectedAt: minus(6),
    updatedAt: minus(2),
    tags: ['revenue', 'arr', 'growth', 'enterprise'],
    metadata: { currentGrowthRate: 0.21, targetGrowthRate: 0.28, arrUSD: 3520000 },
  },
  {
    id: 'sig-lyte-002',
    vertical: 'lyte-revenue',
    entity: 'Lyte Platform — Churn',
    title: 'Mid-Market Churn Spike',
    description: 'Three mid-market accounts (combined $180K ARR) have issued cancellation notices in the past 7 days.',
    severity: 'critical',
    status: 'escalated',
    businessImpact: 'Immediate $180K ARR at risk; contagion risk estimated at $340K if not contained.',
    evidenceRefs: ['lyte/crm/churn-notices-2026-04', 'lyte/cs/account-health-scores'],
    owner: 'Head of Customer Success, Lyte',
    detectedAt: minus(18),
    updatedAt: minus(1),
    tags: ['churn', 'mid-market', 'critical', 'cancellation'],
    metadata: { churnedARR: 180000, atRiskARR: 340000, accountCount: 3 },
  },
  {
    id: 'sig-lyte-003',
    vertical: 'lyte-revenue',
    entity: 'Lyte Platform — Pipeline',
    title: 'Enterprise Pipeline Coverage Below 3x',
    description: 'Enterprise pipeline coverage ratio has dropped to 2.6x against Q3 quota. Target is 3.5x.',
    severity: 'medium',
    status: 'active',
    businessImpact: 'Forecast risk of $420K against $1.1M Q3 enterprise quota.',
    evidenceRefs: ['lyte/crm/pipeline-q3-2026', 'lyte/sales/quota-tracker'],
    owner: 'VP Sales, Lyte',
    detectedAt: minus(12),
    updatedAt: minus(3),
    tags: ['pipeline', 'enterprise', 'forecast', 'coverage'],
    metadata: { coverageRatio: 2.6, targetRatio: 3.5, quotaUSD: 1100000 },
  },
  {
    id: 'sig-lyte-004',
    vertical: 'lyte-revenue',
    entity: 'Lyte Platform — NPS',
    title: 'NPS Decline in Enterprise Tier',
    description: 'Enterprise NPS dropped from 62 to 47 following the Q1 pricing change rollout.',
    severity: 'medium',
    status: 'active',
    businessImpact: '15% elevated churn risk in the enterprise tier over the next 90 days.',
    evidenceRefs: ['lyte/cs/nps-q2-2026', 'lyte/product/pricing-change-impact'],
    owner: 'Head of Product, Lyte',
    detectedAt: minus(48),
    updatedAt: minus(24),
    tags: ['nps', 'enterprise', 'product', 'satisfaction'],
    metadata: { currentNPS: 47, previousNPS: 62, deltaNPS: -15 },
  },
  {
    id: 'sig-lyte-005',
    vertical: 'lyte-revenue',
    entity: 'Lyte Platform — Expansion',
    title: 'Upsell Signal: 8 Accounts at Expansion Threshold',
    description: 'Usage analytics identify 8 accounts operating near plan capacity limits — prime expansion candidates.',
    severity: 'info',
    status: 'active',
    businessImpact: 'Estimated $210K expansion ARR opportunity if engaged within 30 days.',
    evidenceRefs: ['lyte/analytics/usage-thresholds', 'lyte/crm/expansion-candidates'],
    owner: 'VP Revenue, Lyte',
    detectedAt: minus(3),
    updatedAt: now(),
    tags: ['expansion', 'upsell', 'opportunity', 'usage'],
    metadata: { accountCount: 8, expansionOpportunityUSD: 210000, avgDaysToClose: 18 },
  },
  {
    id: 'sig-lyte-006',
    vertical: 'lyte-revenue',
    entity: 'Lyte Platform — Product Adoption',
    title: 'AI Module Adoption Rate at 18% — Target 40% by Q3',
    description: 'New AI module launched in Q1 has achieved only 18% adoption across the install base, well below the 40% Q3 target.',
    severity: 'medium',
    status: 'active',
    businessImpact: 'Low adoption risks $320K in AI tier upgrade revenue and weakens competitive differentiation.',
    evidenceRefs: ['lyte/product/ai-module-adoption-2026-q2', 'lyte/analytics/feature-usage'],
    owner: 'Head of Product, Lyte',
    detectedAt: minus(96),
    updatedAt: minus(24),
    tags: ['product', 'adoption', 'ai-module', 'revenue'],
    metadata: { currentAdoptionPct: 0.18, targetAdoptionPct: 0.40, upgradeRevenueAtRiskUSD: 320000 },
  },
  {
    id: 'sig-vessels-001',
    vertical: 'vessels-maritime',
    entity: 'MV Meridian Star — IMO 9234817',
    title: 'Unscheduled Port Diversion — Panama Canal Congestion',
    description: 'MV Meridian Star diverted to Balboa anchorage due to Panama Canal congestion. ETA now +72 hours.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Cargo delivery delay affects 3 customers with $840K demurrage exposure.',
    evidenceRefs: ['vessels/ais/IMO9234817/track', 'vessels/ops/canal-congestion-2026-04'],
    owner: 'Operations Controller, Vessels',
    detectedAt: minus(4),
    updatedAt: minus(1),
    tags: ['diversion', 'canal', 'delay', 'demurrage'],
    metadata: { etaSlipHours: 72, demurrageUSD: 840000, affectedCustomers: 3 },
  },
  {
    id: 'sig-vessels-002',
    vertical: 'vessels-maritime',
    entity: 'Tanker Fleet — Caribbean Corridor',
    title: 'SIRE 2.0 Compliance Gap: 4 Vessels Below Threshold',
    description: 'SIRE 2.0 audit scores reveal 4 tankers below the major charterer minimum of 75 points.',
    severity: 'critical',
    status: 'active',
    businessImpact: 'Charter revenue at risk: $4.8M if charterers enforce vetting requirements.',
    evidenceRefs: ['vessels/sire/2026-q2-audits', 'vessels/charter/vetting-requirements'],
    owner: 'Fleet Compliance Officer',
    detectedAt: minus(36),
    updatedAt: minus(12),
    tags: ['sire', 'compliance', 'tanker', 'vetting'],
    metadata: { vesselCount: 4, lowestScore: 61, charterRevenueAtRiskUSD: 4800000 },
  },
  {
    id: 'sig-vessels-003',
    vertical: 'vessels-maritime',
    entity: 'Bulk Carrier Fleet — Asia-Pacific',
    title: 'Bunker Price Spike: +18% Above Budget Baseline',
    description: 'VLSFO prices spiked to $720/MT in Singapore — 18% above the annual budget baseline of $610/MT.',
    severity: 'high',
    status: 'acknowledged',
    businessImpact: 'Cost overrun on active voyages estimated at $380K over the next 45 days.',
    evidenceRefs: ['vessels/bunker/singapore-prices-2026-04', 'vessels/finance/bunker-budget-2026'],
    owner: 'Fleet Chartering Manager',
    detectedAt: minus(8),
    updatedAt: minus(2),
    tags: ['bunker', 'cost', 'fuel', 'vlsfo'],
    metadata: { vlsfoPriceMT: 720, budgetBaselineMT: 610, overrunUSD: 380000 },
  },
  {
    id: 'sig-vessels-004',
    vertical: 'vessels-maritime',
    entity: 'MV Coastal Phoenix — IMO 9401233',
    title: 'Port State Control Detention Risk — Deficiency Accumulation',
    description: 'MV Coastal Phoenix has accumulated 7 PSC deficiencies in 6 months, placing it in the high-risk detention band.',
    severity: 'high',
    status: 'escalated',
    businessImpact: 'Detention risk: 14–21 days revenue loss estimated at $620K plus reputational damage.',
    evidenceRefs: ['vessels/psc/deficiency-log-IMO9401233', 'vessels/ops/detention-risk-model'],
    owner: 'Technical Superintendent',
    detectedAt: minus(24),
    updatedAt: minus(6),
    tags: ['psc', 'detention', 'compliance', 'risk'],
    metadata: { deficiencyCount: 7, detentionRiskScore: 0.81, revenueAtRiskUSD: 620000 },
  },
  {
    id: 'sig-vessels-005',
    vertical: 'vessels-maritime',
    entity: 'Fleet-Wide — CII Rating',
    title: 'CII Rating on Track for "D" — IMO Penalty Zone',
    description: '5 vessels in the fleet are projected to achieve a CII "D" rating by year-end based on current consumption data.',
    severity: 'medium',
    status: 'active',
    businessImpact: '$2.1M charter revenue at risk due to charterer preference for A/B-rated vessels.',
    evidenceRefs: ['vessels/cii/2026-ytd-projections', 'vessels/esg/carbon-intensity-model'],
    owner: 'Environmental Compliance Manager',
    detectedAt: minus(72),
    updatedAt: minus(24),
    tags: ['cii', 'esg', 'carbon', 'compliance'],
    metadata: { vesselCount: 5, projectedRating: 'D', charterRevenueAtRiskUSD: 2100000 },
  },
  {
    id: 'sig-vessels-006',
    vertical: 'vessels-maritime',
    entity: 'Dry Bulk Fleet — Atlantic Route',
    title: 'Freight Rate Collapse: Baltic Dry Index -28% in 30 Days',
    description: 'Baltic Dry Index has declined 28% over the past 30 days, compressing voyage margins on 3 open positions.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Open positions forecast to yield $180K below budgeted freight contribution.',
    evidenceRefs: ['vessels/freight/bdi-tracker-2026-04', 'vessels/chartering/open-positions'],
    owner: 'Fleet Chartering Manager',
    detectedAt: minus(48),
    updatedAt: minus(6),
    tags: ['freight', 'bdi', 'dry-bulk', 'margin'],
    metadata: { bdiDeclinePct: 0.28, openPositions: 3, marginShortfallUSD: 180000 },
  },
  {
    id: 'sig-terra-001',
    vertical: 'terra-real-estate',
    entity: 'Wilshire Portfolio — Los Angeles',
    title: 'Office Vacancy Rate at 34% — Above Debt Covenant Threshold',
    description: 'Wilshire Ave office portfolio vacancy has reached 34%, breaching the 30% debt covenant threshold.',
    severity: 'critical',
    status: 'escalated',
    businessImpact: 'Covenant breach triggers lender notification; potential acceleration of $28M debt facility.',
    evidenceRefs: ['terra/leasing/wilshire-2026-q2', 'terra/finance/debt-covenant-tracker'],
    owner: 'Portfolio Director, LA',
    detectedAt: minus(2),
    updatedAt: minus(1),
    tags: ['vacancy', 'covenant', 'debt', 'critical', 'lender'],
    metadata: { vacancyRate: 0.34, covenantThreshold: 0.30, debtFacilityUSD: 28000000 },
  },
  {
    id: 'sig-terra-002',
    vertical: 'terra-real-estate',
    entity: 'Marina District Industrial — San Francisco',
    title: 'Lease Expiry Concentration Risk: $4.2M Expiring Q4',
    description: '6 industrial leases totaling $4.2M annual rent expire in Q4 2026, with 2 tenants confirmed non-renewal.',
    severity: 'high',
    status: 'active',
    businessImpact: 'If remaining 4 leases not renewed: $2.8M revenue gap in 2027.',
    evidenceRefs: ['terra/leasing/marina-expiry-tracker', 'terra/tenant/renewal-intents'],
    owner: 'Leasing Director, Northern CA',
    detectedAt: minus(96),
    updatedAt: minus(48),
    tags: ['lease-expiry', 'industrial', 'renewal', 'revenue'],
    metadata: { totalExpiringARR: 4200000, confirmedNonRenewalCount: 2, revenueGapUSD: 2800000 },
  },
  {
    id: 'sig-terra-003',
    vertical: 'terra-real-estate',
    entity: 'Sunset Residential Portfolio',
    title: 'NOI Compression: Operating Costs Up 22% YoY',
    description: 'Insurance (+38%), utilities (+24%), and property taxes (+15%) are driving 22% NOI compression across the residential portfolio.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Portfolio cap rate compression reducing total equity value by an estimated $14M.',
    evidenceRefs: ['terra/ops/cost-analysis-2026', 'terra/finance/noi-compression-model'],
    owner: 'CFO, Terra',
    detectedAt: minus(168),
    updatedAt: minus(72),
    tags: ['noi', 'costs', 'insurance', 'compression'],
    metadata: { noiCompressionPct: 0.22, equityValueImpactUSD: 14000000, insuranceIncreasePct: 0.38 },
  },
  {
    id: 'sig-terra-004',
    vertical: 'terra-real-estate',
    entity: 'Downtown Mixed-Use — Seattle',
    title: 'Zoning Variance Approval: Development Upside $18M',
    description: 'City of Seattle approved a density variance for the Pioneer Square parcel enabling 12-story mixed-use development.',
    severity: 'info',
    status: 'active',
    businessImpact: 'Development value creation estimated at $18M over a 36-month horizon.',
    evidenceRefs: ['terra/dev/pioneer-square-variance', 'terra/valuations/pioneer-square-upside'],
    owner: 'Development Director, Pacific NW',
    detectedAt: minus(12),
    updatedAt: minus(6),
    tags: ['development', 'zoning', 'opportunity', 'upside'],
    metadata: { developmentValueUSD: 18000000, buildoutMonths: 36, floors: 12 },
  },
  {
    id: 'sig-terra-005',
    vertical: 'terra-real-estate',
    entity: 'Tech Corridor Office — Austin',
    title: 'Anchor Tenant Non-Renewal: 42K sqft at Risk',
    description: 'Primary anchor tenant confirmed non-renewal for the 42,000 sqft lease expiring in 120 days.',
    severity: 'critical',
    status: 'escalated',
    businessImpact: 'Full vacancy exposure of $1.8M ARR; DSCR drops to 0.92x on loss.',
    evidenceRefs: ['terra/leasing/austin-anchor-2026', 'terra/finance/dscr-model'],
    owner: 'Portfolio Director, Texas',
    detectedAt: minus(48),
    updatedAt: minus(6),
    tags: ['non-renewal', 'anchor-tenant', 'vacancy', 'dscr'],
    metadata: { sqft: 42000, annualRentUSD: 1800000, daysToExpiry: 120, dscr: 0.92 },
  },
  {
    id: 'sig-aegis-001',
    vertical: 'aegis-defense',
    entity: 'Aegis Platform — Threat Intelligence',
    title: 'APT Attribution: Novel TTPs Matching State-Level Adversary',
    description: 'Threat intelligence fusion identifies 3 novel TTPs matching known state-level APT pattern. High-confidence attribution.',
    severity: 'critical',
    status: 'active',
    businessImpact: 'Client network at risk. Immediate escalation and active defense posture required.',
    evidenceRefs: ['aegis/ti/apt-analysis-2026-04', 'aegis/mitre/ttp-mapping'],
    owner: 'Threat Intelligence Lead, Aegis',
    detectedAt: minus(1),
    updatedAt: minus(0.25),
    tags: ['apt', 'threat-intel', 'ttp', 'attribution', 'critical'],
    metadata: { ttpCount: 3, confidenceLevel: 0.92, adversaryClass: 'state-level' },
  },
  {
    id: 'sig-aegis-002',
    vertical: 'aegis-defense',
    entity: 'Aegis Platform — Mission Readiness',
    title: 'ISR Asset Availability Below 80% Threshold',
    description: 'Intelligence, Surveillance and Reconnaissance asset availability at 74% due to maintenance cycle overlaps.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Coverage gap in Sector 7 creating intelligence blind spot during elevated threat period.',
    evidenceRefs: ['aegis/ops/isr-availability-2026-04', 'aegis/ops/coverage-map'],
    owner: 'Operations Director, Aegis',
    detectedAt: minus(8),
    updatedAt: minus(2),
    tags: ['isr', 'readiness', 'maintenance', 'coverage'],
    metadata: { availabilityPct: 0.74, threshold: 0.80, affectedSectors: ['S7'] },
  },
  {
    id: 'sig-aegis-003',
    vertical: 'aegis-defense',
    entity: 'Aegis Platform — Contract Compliance',
    title: 'CMMC Level 2 Gap Assessment: 14 Controls Non-Compliant',
    description: 'Internal CMMC Level 2 gap assessment found 14 controls below threshold ahead of October certification audit.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Non-compliance risks $42M in DoD contract renewals requiring CMMC certification.',
    evidenceRefs: ['aegis/compliance/cmmc-gap-2026', 'aegis/contracts/dod-renewal-list'],
    owner: 'Compliance Officer, Aegis',
    detectedAt: minus(120),
    updatedAt: minus(48),
    tags: ['cmmc', 'compliance', 'dod', 'certification'],
    metadata: { nonCompliantControls: 14, contractValueAtRiskUSD: 42000000, certAuditDays: 165 },
  },
  {
    id: 'sig-aegis-004',
    vertical: 'aegis-defense',
    entity: 'Aegis Platform — Cyber Operations',
    title: 'Supply Chain Compromise Indicator: 3rd-Party SDK Under Review',
    description: 'CISA advisory flagged a 3rd-party SDK in use across 2 client environments. Indicators of compromise under active review.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Potential lateral movement risk in 2 classified client environments requiring immediate isolation assessment.',
    evidenceRefs: ['aegis/cyber/cisa-advisory-2026-04-25', 'aegis/asset/sdk-inventory'],
    owner: 'Deputy CISO, Aegis',
    detectedAt: minus(3),
    updatedAt: minus(0.5),
    tags: ['supply-chain', 'cisa', 'sdk', 'compromise'],
    metadata: { affectedClientEnvs: 2, sdkVersion: '4.2.1', cveId: 'CVE-2026-11842' },
  },
  {
    id: 'sig-counsel-001',
    vertical: 'prism-counsel',
    entity: 'Counsel Platform — Matter Portfolio',
    title: 'Legal Spend Concentration: Top 3 Matters = 61% of Budget',
    description: '3 active matters consuming 61% of annual legal budget. Phase 2 billing projections show budget exhaustion in 9 weeks.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Budget exhaustion forces either supplemental approval ($280K) or matter scope reduction.',
    evidenceRefs: ['counsel/billing/matter-analysis-2026-q2', 'counsel/finance/legal-budget-tracker'],
    owner: 'General Counsel',
    detectedAt: minus(24),
    updatedAt: minus(12),
    tags: ['legal-spend', 'budget', 'matter', 'concentration'],
    metadata: { topMattersPct: 0.61, budgetExhaustionWeeks: 9, supplementalUSD: 280000 },
  },
  {
    id: 'sig-counsel-002',
    vertical: 'prism-counsel',
    entity: 'Counsel Platform — Contract Lifecycle',
    title: '23 Contracts Pending Signature >30 Days',
    description: '23 contracts in signature queue for more than 30 days — blocking deal closures and vendor onboarding.',
    severity: 'medium',
    status: 'active',
    businessImpact: 'Revenue delayed: $1.4M in deals contingent on executed contracts.',
    evidenceRefs: ['counsel/clm/signature-queue-2026-04', 'counsel/sales/blocked-deals'],
    owner: 'Head of Legal Operations',
    detectedAt: minus(72),
    updatedAt: minus(24),
    tags: ['contracts', 'signature', 'clm', 'velocity'],
    metadata: { pendingCount: 23, avgDaysWaiting: 38, revenueAtRiskUSD: 1400000 },
  },
  {
    id: 'sig-counsel-003',
    vertical: 'prism-counsel',
    entity: 'Counsel Platform — Regulatory',
    title: 'EU AI Act Compliance Gap: 8 Systems Require Classification',
    description: '8 AI systems deployed in EU jurisdiction lack required EU AI Act risk classification documentation.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Non-compliance exposure: up to €30M fine per system or 6% global turnover.',
    evidenceRefs: ['counsel/regulatory/eu-ai-act-inventory', 'counsel/compliance/ai-register'],
    owner: 'Chief Privacy Officer',
    detectedAt: minus(168),
    updatedAt: minus(48),
    tags: ['eu-ai-act', 'regulatory', 'compliance', 'ai'],
    metadata: { systemsCount: 8, maxFinePerSystem: 30000000, complianceDeadline: '2027-08-02' },
  },
  {
    id: 'sig-counsel-004',
    vertical: 'prism-counsel',
    entity: 'Counsel Platform — Litigation',
    title: 'Adverse Judgment Risk: $4.1M Exposure in IP Matter',
    description: 'Independent counsel risk assessment raised probability of adverse judgment from 28% to 51% following new prior art discovery.',
    severity: 'critical',
    status: 'escalated',
    businessImpact: 'Worst-case liability of $4.1M plus legal costs; settlement window open for 45 days.',
    evidenceRefs: ['counsel/litigation/ip-matter-2024-cv-0891', 'counsel/risk/adverse-judgment-model'],
    owner: 'General Counsel',
    detectedAt: minus(12),
    updatedAt: minus(2),
    tags: ['litigation', 'ip', 'judgment', 'settlement'],
    metadata: { adverseJudgmentProbability: 0.51, liabilityExposureUSD: 4100000, settlementWindowDays: 45 },
  },
  {
    id: 'sig-carlota-001',
    vertical: 'carlota-jo',
    entity: 'Carlota Jo Consulting — Capacity',
    title: 'Consultant Utilization Exceeds 95% — Delivery Risk',
    description: 'All billable consultants are operating above 95% capacity utilization, creating delivery risk on active engagements.',
    severity: 'high',
    status: 'active',
    businessImpact: '$340K in qualified pipeline at risk due to insufficient capacity to onboard new engagements.',
    evidenceRefs: ['carlota/capacity/utilization-2026-04', 'carlota/pipeline/new-engagement-forecast'],
    owner: 'Managing Director, Carlota Jo',
    detectedAt: minus(6),
    updatedAt: minus(2),
    tags: ['capacity', 'utilization', 'delivery', 'pipeline'],
    metadata: { avgUtilization: 0.96, pipelineAtRiskUSD: 340000, billableConsultants: 12 },
  },
  {
    id: 'sig-carlota-002',
    vertical: 'carlota-jo',
    entity: 'Carlota Jo Consulting — Invoicing',
    title: 'Outstanding AR >60 Days: $218K at Collection Risk',
    description: '$218K in invoices outstanding beyond 60-day payment terms across 4 client accounts.',
    severity: 'medium',
    status: 'active',
    businessImpact: 'Cash flow impact on the next payroll cycle if not resolved within 14 days.',
    evidenceRefs: ['carlota/ar/aging-report-2026-04', 'carlota/finance/cash-flow-forecast'],
    owner: 'Finance Director, Carlota Jo',
    detectedAt: minus(48),
    updatedAt: minus(24),
    tags: ['ar', 'invoicing', 'collections', 'cash-flow'],
    metadata: { outstandingUSD: 218000, accountCount: 4, payrollCycleImpact: true },
  },
  {
    id: 'sig-carlota-003',
    vertical: 'carlota-jo',
    entity: 'Carlota Jo Consulting — Client Retention',
    title: 'Client Satisfaction Decline: 2 Accounts at Risk',
    description: '2 accounts rated below 7/10 in quarterly CSAT survey, indicating elevated non-renewal risk for Q3 retainers.',
    severity: 'medium',
    status: 'active',
    businessImpact: 'Q3 retainer renewal risk: $84K ARR at elevated churn probability.',
    evidenceRefs: ['carlota/csat/q2-2026-results', 'carlota/retainer/renewal-pipeline'],
    owner: 'Director of Client Services',
    detectedAt: minus(36),
    updatedAt: minus(12),
    tags: ['csat', 'retention', 'retainer', 'renewal'],
    metadata: { atRiskAccounts: 2, retainerARR: 84000, avgCSAT: 6.3 },
  },
  {
    id: 'sig-carlota-004',
    vertical: 'carlota-jo',
    entity: 'Carlota Jo Consulting — Talent',
    title: 'Key Principal Departure Risk: 2 Senior Consultants Exploring Exit',
    description: 'HR intelligence indicates 2 senior principals are in active conversations with competing advisory firms.',
    severity: 'high',
    status: 'active',
    businessImpact: 'Loss of both principals would remove $620K in billable capacity and client relationships worth $1.1M ARR.',
    evidenceRefs: ['carlota/hr/retention-risk-2026-04', 'carlota/finance/principal-revenue-attribution'],
    owner: 'Managing Director, Carlota Jo',
    detectedAt: minus(18),
    updatedAt: minus(6),
    tags: ['talent', 'retention', 'principal', 'risk'],
    metadata: { atRiskPrincipals: 2, billableCapacityUSD: 620000, clientARRAtRiskUSD: 1100000 },
  },
  {
    id: 'sig-alloy-001',
    vertical: 'alloy-core',
    entity: 'A11oy Platform — Fabric Health',
    title: 'Signal Ingestion Latency P95 Elevated: 340ms',
    description: 'Signal Mesh P95 ingestion latency elevated to 340ms, exceeding the 200ms threshold due to state engine snapshot contention.',
    severity: 'medium',
    status: 'acknowledged',
    businessImpact: 'Delayed signal processing reduces real-time decision quality across all verticals.',
    evidenceRefs: ['a11oy/metrics/signal-latency-2026-04-25', 'a11oy/fabric/state-engine-telemetry'],
    owner: 'Platform Engineering, A11oy',
    detectedAt: minus(2),
    updatedAt: minus(0.5),
    tags: ['latency', 'fabric', 'signal-mesh', 'performance'],
    metadata: { p95LatencyMs: 340, thresholdMs: 200, rootCause: 'state-engine-contention' },
  },
  {
    id: 'sig-alloy-002',
    vertical: 'alloy-core',
    entity: 'A11oy Platform — Proof Ledger',
    title: 'Proof Ledger Verification Queue: 847 Backlogged',
    description: 'Proof verification queue has accumulated 847 unprocessed items. Normal queue depth: <50.',
    severity: 'medium',
    status: 'active',
    businessImpact: 'Delayed proof issuance impacts audit completeness and compliance reporting.',
    evidenceRefs: ['a11oy/proof-ledger/queue-metrics', 'a11oy/fabric/ledger-telemetry'],
    owner: 'Platform Engineering, A11oy',
    detectedAt: minus(1),
    updatedAt: minus(0.25),
    tags: ['proof-ledger', 'queue', 'backlog', 'compliance'],
    metadata: { queueDepth: 847, normalDepth: 50, estimatedClearTimeMin: 23 },
  },
  {
    id: 'sig-alloy-003',
    vertical: 'alloy-core',
    entity: 'A11oy Platform — Policy Engine',
    title: 'Covenant Policy Coverage Gap: 3 Verticals Without Active Policies',
    description: 'Coverage graph shows carlota-jo, prism-counsel, and alloy-core verticals lack active blocking covenant policies.',
    severity: 'low',
    status: 'active',
    businessImpact: 'Actions in uncovered verticals bypass covenant evaluation — governance gap.',
    evidenceRefs: ['a11oy/covenant/coverage-report-2026-04', 'a11oy/governance/policy-registry'],
    owner: 'Governance Lead, A11oy',
    detectedAt: minus(12),
    updatedAt: minus(6),
    tags: ['policy', 'covenant', 'coverage', 'governance'],
    metadata: { uncoveredVerticals: ['carlota-jo', 'prism-counsel', 'alloy-core'], policyGapCount: 3 },
  },
];

export const SIGNAL_COUNT = SEED_SIGNALS.length;
