import type { Vertical } from '../types.js';

export interface Tool {
  id: string;
  name: string;
  category: 'api-caller' | 'document-reader' | 'crm-query' | 'policy-checker' | 'email-sender' | 'slack-notify' | 'pdf-generator' | 'data-analyzer' | 'risk-scorer' | 'approval-gateway' | 'evidence-packager' | 'twin-updater' | 'proof-issuer' | 'mirror-eval-runner' | 'knowledge-retriever';
  description: string;
  vertical: Vertical | 'global';
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  governanceFlags: string[];
}

export const SEED_TOOLS: Tool[] = [
  {
    id: 'tool-api-caller',
    name: 'Generic API Caller',
    category: 'api-caller',
    description: 'Executes REST API calls to authenticated endpoints.',
    vertical: 'global',
    inputSchema: { url: 'string', method: 'string', body: 'object' },
    outputSchema: { status: 'number', data: 'object' },
    governanceFlags: ['external-network', 'secret-access'],
  },
  {
    id: 'tool-doc-reader',
    name: 'Intelligent Document Reader',
    category: 'document-reader',
    description: 'Parses PDFs, Word docs, and images using OCR and LLM extraction.',
    vertical: 'global',
    inputSchema: { fileUri: 'string', extractFields: 'string[]' },
    outputSchema: { content: 'string', extractedData: 'object' },
    governanceFlags: ['data-privacy-sensitive'],
  },
  {
    id: 'tool-crm-query',
    name: 'CRM Data Connector',
    category: 'crm-query',
    description: 'Queries Salesforce, HubSpot, or internal CRM systems.',
    vertical: 'lyte-revenue',
    inputSchema: { query: 'string', entity: 'string' },
    outputSchema: { records: 'object[]', count: 'number' },
    governanceFlags: ['pii-access'],
  },
  {
    id: 'tool-policy-checker',
    name: 'Covenant Policy Engine',
    category: 'policy-checker',
    description: 'Evaluates actions against defined covenant policies.',
    vertical: 'global',
    inputSchema: { action: 'object', context: 'object' },
    outputSchema: { verdict: 'string', matchedPolicies: 'string[]' },
    governanceFlags: ['compliance-critical'],
  },
  {
    id: 'tool-email-sender',
    name: 'Enterprise Email Relay',
    category: 'email-sender',
    description: 'Sends authenticated enterprise emails.',
    vertical: 'global',
    inputSchema: { to: 'string', subject: 'string', body: 'string' },
    outputSchema: { messageId: 'string', status: 'string' },
    governanceFlags: ['external-communication'],
  },
  {
    id: 'tool-slack-notify',
    name: 'Slack Notification Bridge',
    category: 'slack-notify',
    description: 'Posts updates and alerts to Slack channels.',
    vertical: 'global',
    inputSchema: { channel: 'string', text: 'string', attachments: 'object[]' },
    outputSchema: { ts: 'string', ok: 'boolean' },
    governanceFlags: ['external-communication'],
  },
  {
    id: 'tool-pdf-generator',
    name: 'Legal PDF Generator',
    category: 'pdf-generator',
    description: 'Generates formatted PDFs from templates and data.',
    vertical: 'prism-counsel',
    inputSchema: { templateId: 'string', data: 'object' },
    outputSchema: { fileUri: 'string', checksum: 'string' },
    governanceFlags: ['document-archival'],
  },
  {
    id: 'tool-data-analyzer',
    name: 'Analytical Engine',
    category: 'data-analyzer',
    description: 'Performs statistical analysis and trend detection.',
    vertical: 'global',
    inputSchema: { dataset: 'object[]', operations: 'string[]' },
    outputSchema: { insights: 'string[]', metrics: 'object' },
    governanceFlags: ['compute-intensive'],
  },
  {
    id: 'tool-risk-scorer',
    name: 'Dynamic Risk Scorer',
    category: 'risk-scorer',
    description: 'Calculates multi-dimensional risk scores for business events.',
    vertical: 'global',
    inputSchema: { signals: 'object[]', weights: 'object' },
    outputSchema: { score: 'number', dimensions: 'object' },
    governanceFlags: ['risk-modeling'],
  },
  {
    id: 'tool-approval-gateway',
    name: 'Human-in-the-Loop Gateway',
    category: 'approval-gateway',
    description: 'Routes requests for manual human approval.',
    vertical: 'global',
    inputSchema: { request: 'object', tier: 'string' },
    outputSchema: { decision: 'string', approverId: 'string', timestamp: 'string' },
    governanceFlags: ['hitl-required'],
  },
  {
    id: 'tool-evidence-packager',
    name: 'Evidence Ledger Packager',
    category: 'evidence-packager',
    description: 'Collects and bundles evidence for proof packet issuance.',
    vertical: 'global',
    inputSchema: { sourceIds: 'string[]', metadata: 'object' },
    outputSchema: { packageId: 'string', manifest: 'object' },
    governanceFlags: ['audit-trail'],
  },
  {
    id: 'tool-twin-updater',
    name: 'Business Twin Sync',
    category: 'twin-updater',
    description: 'Updates the state of a digital business twin.',
    vertical: 'global',
    inputSchema: { twinId: 'string', statePatch: 'object' },
    outputSchema: { newState: 'object', version: 'number' },
    governanceFlags: ['state-mutation'],
  },
  {
    id: 'tool-proof-issuer',
    name: 'Proof Ledger Issuer',
    category: 'proof-issuer',
    description: 'Issues cryptographically signed proof packets.',
    vertical: 'global',
    inputSchema: { payload: 'object', entityType: 'string', entityId: 'string' },
    outputSchema: { proofPacketId: 'string', hash: 'string' },
    governanceFlags: ['cryptographic-signing'],
  },
  {
    id: 'tool-mirror-eval-runner',
    name: 'MirrorEval Runner',
    category: 'mirror-eval-runner',
    description: 'Runs secondary evaluation of agent outputs for governance.',
    vertical: 'global',
    inputSchema: { targetOutput: 'object', criteria: 'string[]' },
    outputSchema: { verdict: 'string', score: 'number', dimensions: 'object' },
    governanceFlags: ['quality-assurance'],
  },
  {
    id: 'tool-knowledge-retriever',
    name: 'Semantic Knowledge Retriever',
    category: 'knowledge-retriever',
    description: 'Retrieves relevant facts from the long-term memory fabric.',
    vertical: 'global',
    inputSchema: { query: 'string', context: 'object' },
    outputSchema: { facts: 'object[]', relevanceScores: 'number[]' },
    governanceFlags: ['memory-access'],
  },
];
