import type { Workcell } from '../schema.js';

export const SEED_WORKCELL_TIMESTAMP = '2026-04-16T00:00:00.000Z';
export const SEED_WORKCELL_EVIDENCE_REASON =
  'Repository-seeded demonstration fixture; not an authenticated production execution record.';

const now = () => SEED_WORKCELL_TIMESTAMP;

const SEED_WORKCELL_FIXTURES: Array<Omit<Workcell, 'evidenceState' | 'evidenceReason'>> = [
  {
    id: 'wc-001',
    name: 'Revenue Friction Remediation',
    vertical: 'lyte-revenue',
    status: 'running',
    objective: 'Investigate and remediate enterprise ARR growth deceleration.',
    signals: ['sig-lyte-001', 'sig-lyte-002'],
    contextPack: { threshold: 0.28, current: 0.21, gap: 0.07 },
    agentSequence: [
      { agentId: 'analyst-1', role: 'Data Analyst', action: 'Identify churn drivers' },
      { agentId: 'strategist-1', role: 'Revenue Strategist', action: 'Propose recovery plan' },
    ],
    actionBrief: {
      id: 'act-001',
      title: 'Executive Outreach Program',
      description: 'Initiate executive-level engagement with at-risk accounts.',
      vertical: 'lyte-revenue',
      status: 'pending_approval',
      recommendedBy: 'strategist-1',
      priority: 'high',
      estimatedImpact: 'Recover $180K ARR',
      requiresApproval: true,
      approvalTier: 'executive',
      linkedSignalIds: ['sig-lyte-002'],
      linkedOutcomeIds: ['out-001'],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-001',
      targetId: 'act-001',
      targetType: 'action',
      verdict: 'pass',
      score: 0.95,
      dimensions: [
        { name: 'strategic-alignment', score: 0.98, rationale: 'Matches churn reduction goals.' },
      ],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-001',
    requiresApproval: true,
    mockExecutionResult: { status: 'success', emailsSent: 3 },
    verificationResult: { status: 'passed', checksum: 'sha256:abc123' },
    proofPacketId: 'proof-001',
    executionTraceId: 'trace-001',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-002',
    name: 'SOW Aging Monitoring',
    vertical: 'carlota-jo',
    status: 'idle',
    objective: 'Monitor and accelerate unsigned SOWs in the pipeline.',
    signals: ['sig-carlota-002'],
    contextPack: { limitDays: 30, pendingCount: 12 },
    agentSequence: [{ agentId: 'ops-1', role: 'Ops Lead', action: 'Scan signature queue' }],
    actionBrief: {
      id: 'act-002',
      title: 'Automated SOW Reminders',
      description: 'Send automated follow-ups for SOWs pending > 15 days.',
      vertical: 'carlota-jo',
      status: 'approved',
      recommendedBy: 'ops-1',
      priority: 'normal',
      estimatedImpact: 'Reduce DSO by 5 days',
      requiresApproval: false,
      approvalTier: 'auto',
      linkedSignalIds: ['sig-carlota-002'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-002',
      targetId: 'act-002',
      targetType: 'action',
      verdict: 'pass',
      score: 0.88,
      dimensions: [{ name: 'compliance', score: 0.9, rationale: 'Standard follow-up procedure.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-006',
    requiresApproval: false,
    mockExecutionResult: { remindersSent: 12 },
    verificationResult: { status: 'passed', checksum: 'sha256:def456' },
    proofPacketId: 'proof-006',
    executionTraceId: 'trace-006',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-003',
    name: 'Duplicate ScopeStack Detection',
    vertical: 'alloy-core',
    status: 'idle',
    objective: 'Identify and merge duplicate capability definitions in the fabric.',
    signals: ['sig-alloy-002'],
    contextPack: { duplicationThreshold: 0.85 },
    agentSequence: [
      { agentId: 'architect-1', role: 'Fabric Architect', action: 'Analyze scope overlap' },
    ],
    actionBrief: {
      id: 'act-003',
      title: 'Deduplicate ScopeStack',
      description: 'Merge overlapping capability definitions in the core fabric.',
      vertical: 'alloy-core',
      status: 'recommended',
      recommendedBy: 'architect-1',
      priority: 'low',
      estimatedImpact: 'Reduce fabric complexity',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-alloy-002'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-003',
      targetId: 'act-003',
      targetType: 'action',
      verdict: 'warn',
      score: 0.75,
      dimensions: [
        { name: 'risk', score: 0.6, rationale: 'Potential for service interruption during merge.' },
      ],
      flags: ['high-risk-mutation'],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-005',
    requiresApproval: true,
    mockExecutionResult: { status: 'dry-run-ok' },
    verificationResult: { status: 'passed', checksum: 'sha256:ghi789' },
    proofPacketId: 'proof-005',
    executionTraceId: 'trace-005',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-004',
    name: 'Salesforce/RevOps Mismatch Sync',
    vertical: 'lyte-revenue',
    status: 'error',
    objective: 'Reconcile data discrepancies between Salesforce and RevOps database.',
    signals: ['sig-lyte-003'],
    contextPack: { mismatchCount: 42 },
    agentSequence: [{ agentId: 'data-bot', role: 'Data Integrity Bot', action: 'Diff datasets' }],
    actionBrief: {
      id: 'act-004',
      title: 'Data Re-sync',
      description: 'Trigger full re-sync from Salesforce to RevOps.',
      vertical: 'lyte-revenue',
      status: 'failed',
      recommendedBy: 'data-bot',
      priority: 'high',
      estimatedImpact: 'Restore data integrity',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-lyte-003'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-004',
      targetId: 'act-004',
      targetType: 'action',
      verdict: 'pass',
      score: 0.92,
      dimensions: [{ name: 'correctness', score: 0.95, rationale: 'Standard sync protocol.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-008',
    requiresApproval: true,
    mockExecutionResult: { error: 'Connection timeout' },
    verificationResult: { status: 'failed', checksum: 'sha256:error' },
    proofPacketId: 'proof-008',
    executionTraceId: 'trace-008',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-005',
    name: 'Low-Margin Closed/Won Audit',
    vertical: 'lyte-revenue',
    status: 'completed',
    objective: 'Analyze root cause for high volume of low-margin deals.',
    signals: ['sig-lyte-001'],
    contextPack: { marginThreshold: 0.15 },
    agentSequence: [
      { agentId: 'finance-agent', role: 'Finance Analyst', action: 'Review deal pricing' },
    ],
    actionBrief: {
      id: 'act-005',
      title: 'Update Pricing Guardrails',
      description: 'Enforce stricter discount limits in CRM.',
      vertical: 'lyte-revenue',
      status: 'completed',
      recommendedBy: 'finance-agent',
      priority: 'high',
      estimatedImpact: 'Improve blended margin by 4%',
      requiresApproval: true,
      approvalTier: 'executive',
      linkedSignalIds: ['sig-lyte-001'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-005',
      targetId: 'act-005',
      targetType: 'action',
      verdict: 'pass',
      score: 0.99,
      dimensions: [
        { name: 'margin-protection', score: 1.0, rationale: 'Directly addresses the leak.' },
      ],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-013',
    requiresApproval: true,
    mockExecutionResult: { guardrailsUpdated: true },
    verificationResult: { status: 'passed', checksum: 'sha256:verified' },
    proofPacketId: 'proof-013',
    executionTraceId: 'trace-013',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-006',
    name: 'Voyage Risk Assessment',
    vertical: 'vessels-maritime',
    status: 'running',
    objective: 'Assess and mitigate risks for active maritime voyages.',
    signals: ['sig-vessels-001', 'sig-vessels-003'],
    contextPack: { weatherStatus: 'adverse', fuelPrice: 720 },
    agentSequence: [{ agentId: 'ops-agent', role: 'Ops Controller', action: 'Calculate ETA slip' }],
    actionBrief: {
      id: 'act-006',
      title: 'Route Optimization',
      description: 'Reroute vessels to avoid Panama Canal congestion.',
      vertical: 'vessels-maritime',
      status: 'executing',
      recommendedBy: 'ops-agent',
      priority: 'urgent',
      estimatedImpact: 'Save $120K in demurrage',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-vessels-001'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-006',
      targetId: 'act-006',
      targetType: 'action',
      verdict: 'pass',
      score: 0.94,
      dimensions: [{ name: 'efficiency', score: 0.96, rationale: 'Optimal path found.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-011',
    requiresApproval: true,
    mockExecutionResult: { status: 'rerouted' },
    verificationResult: { status: 'passed', checksum: 'sha256:vessel' },
    proofPacketId: 'proof-011',
    executionTraceId: 'trace-011',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-007',
    name: 'AIS Gap Investigation',
    vertical: 'vessels-maritime',
    status: 'idle',
    objective: 'Investigate periods of AIS signal loss in sensitive corridors.',
    signals: ['sig-vessels-004'],
    contextPack: { gapDuration: '4h', location: 'Red Sea' },
    agentSequence: [
      {
        agentId: 'security-agent',
        role: 'Security Analyst',
        action: 'Cross-reference satellite data',
      },
    ],
    actionBrief: {
      id: 'act-007',
      title: 'Emergency Communication Ping',
      description: 'Establish direct SATCOM link with vessel.',
      vertical: 'vessels-maritime',
      status: 'recommended',
      recommendedBy: 'security-agent',
      priority: 'urgent',
      estimatedImpact: 'Confirm vessel safety',
      requiresApproval: false,
      approvalTier: 'auto',
      linkedSignalIds: ['sig-vessels-004'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-007',
      targetId: 'act-007',
      targetType: 'action',
      verdict: 'pass',
      score: 0.9,
      dimensions: [{ name: 'urgency', score: 1.0, rationale: 'Safety first.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-016',
    requiresApproval: false,
    mockExecutionResult: { linkEstablished: true },
    verificationResult: { status: 'passed', checksum: 'sha256:satcom' },
    proofPacketId: 'proof-016',
    executionTraceId: 'trace-016',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-008',
    name: 'Sanctions Watch Re-scan',
    vertical: 'aegis-defense',
    status: 'completed',
    objective: 'Re-evaluate all active counterparts against updated SDN list.',
    signals: ['sig-aegis-002'],
    contextPack: { sdnUpdateVersion: '2026-04-25' },
    agentSequence: [
      { agentId: 'compliance-bot', role: 'Compliance Officer', action: 'Fuzzy match entities' },
    ],
    actionBrief: {
      id: 'act-008',
      title: 'Freeze High-Risk Account',
      description: 'Restrict transactions for entity matching SDN criteria.',
      vertical: 'aegis-defense',
      status: 'completed',
      recommendedBy: 'compliance-bot',
      priority: 'urgent',
      estimatedImpact: 'Prevent sanctions breach',
      requiresApproval: true,
      approvalTier: 'board',
      linkedSignalIds: ['sig-aegis-002'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-008',
      targetId: 'act-008',
      targetType: 'action',
      verdict: 'pass',
      score: 1.0,
      dimensions: [{ name: 'legal-compliance', score: 1.0, rationale: 'Required by law.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-010',
    requiresApproval: true,
    mockExecutionResult: { accountFrozen: true },
    verificationResult: { status: 'passed', checksum: 'sha256:sdn' },
    proofPacketId: 'proof-010',
    executionTraceId: 'trace-010',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-009',
    name: 'Terra Capex Variance Audit',
    vertical: 'terra-real-estate',
    status: 'running',
    objective: 'Identify source of 22% capex overrun in residential portfolio.',
    signals: ['sig-terra-003'],
    contextPack: { budget: 5000000, actual: 6100000 },
    agentSequence: [{ agentId: 'audit-bot', role: 'Audit Lead', action: 'Categorize invoices' }],
    actionBrief: {
      id: 'act-009',
      title: 'Halt Non-Essential Renovations',
      description: 'Pause all non-safety related renovation projects.',
      vertical: 'terra-real-estate',
      status: 'executing',
      recommendedBy: 'audit-bot',
      priority: 'high',
      estimatedImpact: 'Save $400K monthly',
      requiresApproval: true,
      approvalTier: 'executive',
      linkedSignalIds: ['sig-terra-003'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-009',
      targetId: 'act-009',
      targetType: 'action',
      verdict: 'pass',
      score: 0.85,
      dimensions: [
        { name: 'fiscal-responsibility', score: 0.9, rationale: 'Necessary for covenant health.' },
      ],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-009',
    requiresApproval: true,
    mockExecutionResult: { projectsPaused: 5 },
    verificationResult: { status: 'passed', checksum: 'sha256:capex' },
    proofPacketId: 'proof-009',
    executionTraceId: 'trace-009',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-010',
    name: 'Vendor SLA Breach Remediation',
    vertical: 'alloy-core',
    status: 'idle',
    objective: 'Enforce service level agreements against failing cloud provider.',
    signals: ['sig-alloy-001'],
    contextPack: { slaTarget: 0.999, actual: 0.995 },
    agentSequence: [
      { agentId: 'procurement-agent', role: 'Vendor Manager', action: 'Calculate service credits' },
    ],
    actionBrief: {
      id: 'act-010',
      title: 'Issue SLA Credit Claim',
      description: 'Formally request $50K service credit from provider.',
      vertical: 'alloy-core',
      status: 'recommended',
      recommendedBy: 'procurement-agent',
      priority: 'normal',
      estimatedImpact: 'Recover $50K',
      requiresApproval: false,
      approvalTier: 'auto',
      linkedSignalIds: ['sig-alloy-001'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-010',
      targetId: 'act-010',
      targetType: 'action',
      verdict: 'pass',
      score: 0.91,
      dimensions: [{ name: 'accuracy', score: 0.95, rationale: 'Calculations verified.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-019',
    requiresApproval: false,
    mockExecutionResult: { claimGenerated: true },
    verificationResult: { status: 'passed', checksum: 'sha256:sla' },
    proofPacketId: 'proof-019',
    executionTraceId: 'trace-019',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-011',
    name: 'Aegis Incident Triage',
    vertical: 'aegis-defense',
    status: 'running',
    objective: 'Contain state-level APT threat identified in intelligence fusion.',
    signals: ['sig-aegis-001'],
    contextPack: { threatLevel: 'critical', attribution: 'state-actor' },
    agentSequence: [
      { agentId: 'ir-agent', role: 'Incident Responder', action: 'Isolate affected subnets' },
    ],
    actionBrief: {
      id: 'act-011',
      title: 'Network Lockdown',
      description: 'Apply micro-segmentation rules to isolate suspected nodes.',
      vertical: 'aegis-defense',
      status: 'executing',
      recommendedBy: 'ir-agent',
      priority: 'urgent',
      estimatedImpact: 'Prevent lateral movement',
      requiresApproval: true,
      approvalTier: 'board',
      linkedSignalIds: ['sig-aegis-001'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-011',
      targetId: 'act-011',
      targetType: 'action',
      verdict: 'pass',
      score: 0.97,
      dimensions: [{ name: 'safety', score: 1.0, rationale: 'Standard IR protocol.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-010',
    requiresApproval: true,
    mockExecutionResult: { subnetsIsolated: 3 },
    verificationResult: { status: 'passed', checksum: 'sha256:lockdown' },
    proofPacketId: 'proof-010',
    executionTraceId: 'trace-010',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-012',
    name: 'Vulnerability SLA Tracker',
    vertical: 'aegis-defense',
    status: 'idle',
    objective: 'Ensure all critical vulnerabilities are patched within 24h SLA.',
    signals: ['sig-aegis-004'],
    contextPack: { cve: 'CVE-2026-11842', environments: 2 },
    agentSequence: [
      { agentId: 'patch-agent', role: 'Patch Manager', action: 'Verify patch availability' },
    ],
    actionBrief: {
      id: 'act-012',
      title: 'Emergency Patch Rollout',
      description: 'Deploy hotfix to classified environments.',
      vertical: 'aegis-defense',
      status: 'recommended',
      recommendedBy: 'patch-agent',
      priority: 'urgent',
      estimatedImpact: 'Close critical exploit window',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-aegis-004'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-012',
      targetId: 'act-012',
      targetType: 'action',
      verdict: 'pass',
      score: 0.93,
      dimensions: [{ name: 'timeliness', score: 1.0, rationale: 'Action taken within SLA.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-015',
    requiresApproval: true,
    mockExecutionResult: { patchesDeployed: 2 },
    verificationResult: { status: 'passed', checksum: 'sha256:patch' },
    proofPacketId: 'proof-015',
    executionTraceId: 'trace-015',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-013',
    name: 'PRISM Deadline Monitor',
    vertical: 'prism-counsel',
    status: 'running',
    objective: 'Track and alert on impending legal and regulatory deadlines.',
    signals: ['sig-counsel-002', 'sig-counsel-003'],
    contextPack: { systemsCount: 8, deadline: '2027-08-02' },
    agentSequence: [
      { agentId: 'legal-bot', role: 'Legal Assistant', action: 'Draft compliance roadmap' },
    ],
    actionBrief: {
      id: 'act-013',
      title: 'EU AI Act Classification',
      description: 'Kick off risk classification for 8 EU systems.',
      vertical: 'prism-counsel',
      status: 'executing',
      recommendedBy: 'legal-bot',
      priority: 'high',
      estimatedImpact: 'Avoid €30M potential fines',
      requiresApproval: true,
      approvalTier: 'executive',
      linkedSignalIds: ['sig-counsel-003'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-013',
      targetId: 'act-013',
      targetType: 'action',
      verdict: 'pass',
      score: 0.89,
      dimensions: [{ name: 'risk-reduction', score: 0.95, rationale: 'Proactive compliance.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-017',
    requiresApproval: true,
    mockExecutionResult: { assessmentStarted: true },
    verificationResult: { status: 'passed', checksum: 'sha256:euai' },
    proofPacketId: 'proof-017',
    executionTraceId: 'trace-017',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-014',
    name: 'PRISM Proof Chain Auditor',
    vertical: 'prism-counsel',
    status: 'idle',
    objective: 'Audit the integrity of proof chains for executive decisions.',
    signals: ['sig-counsel-004'],
    contextPack: { exposure: 4100000 },
    agentSequence: [
      { agentId: 'auditor-1', role: 'Governance Auditor', action: 'Verify causal links' },
    ],
    actionBrief: {
      id: 'act-014',
      title: 'Verify Decision Chain',
      description: 'Complete audit of the IP matter settlement decision chain.',
      vertical: 'prism-counsel',
      status: 'recommended',
      recommendedBy: 'auditor-1',
      priority: 'high',
      estimatedImpact: 'Ensure defensible record',
      requiresApproval: true,
      approvalTier: 'board',
      linkedSignalIds: ['sig-counsel-004'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-014',
      targetId: 'act-014',
      targetType: 'action',
      verdict: 'pass',
      score: 0.98,
      dimensions: [{ name: 'integrity', score: 1.0, rationale: 'Full chain present.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-012',
    requiresApproval: true,
    mockExecutionResult: { auditComplete: true },
    verificationResult: { status: 'passed', checksum: 'sha256:audit' },
    proofPacketId: 'proof-012',
    executionTraceId: 'trace-012',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-015',
    name: 'Carlota Residence Concierge',
    vertical: 'carlota-jo',
    status: 'running',
    objective: 'Coordinate high-touch services for ultra-high-net-worth clients.',
    signals: ['sig-carlota-003'],
    contextPack: { csatScore: 6.3 },
    agentSequence: [
      { agentId: 'concierge-1', role: 'Lead Concierge', action: 'Personalize recovery gift' },
    ],
    actionBrief: {
      id: 'act-015',
      title: 'VIP Recovery Outreach',
      description: 'Schedule in-person meeting with dissatisfied principals.',
      vertical: 'carlota-jo',
      status: 'executing',
      recommendedBy: 'concierge-1',
      priority: 'high',
      estimatedImpact: 'Retain $84K retainer',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-carlota-003'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-015',
      targetId: 'act-015',
      targetType: 'action',
      verdict: 'pass',
      score: 0.82,
      dimensions: [{ name: 'empathy', score: 0.9, rationale: 'Appropriate tone.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-018',
    requiresApproval: true,
    mockExecutionResult: { meetingsScheduled: 2 },
    verificationResult: { status: 'passed', checksum: 'sha256:vip' },
    proofPacketId: 'proof-018',
    executionTraceId: 'trace-018',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-016',
    name: 'Privacy-Sensitive Family Office Sync',
    vertical: 'prism-counsel',
    status: 'idle',
    objective: 'Manage sensitive data transfers for family office clients.',
    signals: ['sig-counsel-003'],
    contextPack: { dataClass: 'highly-sensitive' },
    agentSequence: [{ agentId: 'privacy-bot', role: 'Privacy Officer', action: 'Encrypt payload' }],
    actionBrief: {
      id: 'act-016',
      title: 'Secure Data Transfer',
      description: 'Execute PGP-encrypted transfer of family office docs.',
      vertical: 'prism-counsel',
      status: 'recommended',
      recommendedBy: 'privacy-bot',
      priority: 'normal',
      estimatedImpact: 'Zero-leak transfer',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-counsel-003'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-016',
      targetId: 'act-016',
      targetType: 'action',
      verdict: 'pass',
      score: 0.96,
      dimensions: [{ name: 'privacy', score: 1.0, rationale: 'Encryption standards met.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-017',
    requiresApproval: true,
    mockExecutionResult: { status: 'transferred' },
    verificationResult: { status: 'passed', checksum: 'sha256:family' },
    proofPacketId: 'proof-017',
    executionTraceId: 'trace-017',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-017',
    name: 'Board Packet Assembler',
    vertical: 'alloy-core',
    status: 'completed',
    objective: 'Automatically generate comprehensive board-level risk packets.',
    signals: ['sig-alloy-002', 'sig-lyte-002', 'sig-terra-001'],
    contextPack: { period: 'Q2 2026' },
    agentSequence: [
      { agentId: 'report-bot', role: 'Reporting Agent', action: 'Synthesize cross-vertical risks' },
    ],
    actionBrief: {
      id: 'act-017',
      title: 'Generate Q2 Board Packet',
      description: 'Bundle all high-severity signals and remediations into a PDF.',
      vertical: 'alloy-core',
      status: 'completed',
      recommendedBy: 'report-bot',
      priority: 'high',
      estimatedImpact: 'Board readiness',
      requiresApproval: true,
      approvalTier: 'executive',
      linkedSignalIds: ['sig-alloy-002', 'sig-lyte-002', 'sig-terra-001'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-017',
      targetId: 'act-017',
      targetType: 'action',
      verdict: 'pass',
      score: 0.94,
      dimensions: [{ name: 'completeness', score: 0.98, rationale: 'All key risks included.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-019',
    requiresApproval: true,
    mockExecutionResult: { packetUri: 's3://a11oy-reports/board-q2.pdf' },
    verificationResult: { status: 'passed', checksum: 'sha256:board' },
    proofPacketId: 'proof-019',
    executionTraceId: 'trace-019',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-018',
    name: 'Connector Health Watchdog',
    vertical: 'alloy-core',
    status: 'running',
    objective: 'Monitor and auto-remediate external data connector health.',
    signals: ['sig-alloy-001'],
    contextPack: { latencyThreshold: 200, current: 340 },
    agentSequence: [
      { agentId: 'watchdog-1', role: 'SRE Agent', action: 'Analyze snapshot contention' },
    ],
    actionBrief: {
      id: 'act-018',
      title: 'Optimize State Snapshotting',
      description: 'Adjust snapshot frequency to reduce contention.',
      vertical: 'alloy-core',
      status: 'executing',
      recommendedBy: 'watchdog-1',
      priority: 'high',
      estimatedImpact: 'Restore P95 latency',
      requiresApproval: false,
      approvalTier: 'auto',
      linkedSignalIds: ['sig-alloy-001'],
      linkedOutcomeIds: ['out-005'],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-018',
      targetId: 'act-018',
      targetType: 'action',
      verdict: 'pass',
      score: 0.88,
      dimensions: [{ name: 'technical-soundness', score: 0.9, rationale: 'Addresses root cause.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-005',
    requiresApproval: false,
    mockExecutionResult: { configUpdated: true },
    verificationResult: { status: 'passed', checksum: 'sha256:watchdog' },
    proofPacketId: 'proof-005',
    executionTraceId: 'trace-005',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-019',
    name: 'Cross-Vertical Risk Fusion',
    vertical: 'alloy-core',
    status: 'idle',
    objective: 'Detect systemic risks that span multiple business verticals.',
    signals: ['sig-lyte-002', 'sig-terra-001', 'sig-vessels-002'],
    contextPack: { correlationFactor: 0.72 },
    agentSequence: [
      {
        agentId: 'fusion-bot',
        role: 'Risk Architect',
        action: 'Perform multi-variate correlation',
      },
    ],
    actionBrief: {
      id: 'act-019',
      title: 'Systemic Risk Alert',
      description: 'Issue a cross-vertical risk warning to the investment committee.',
      vertical: 'alloy-core',
      status: 'recommended',
      recommendedBy: 'fusion-bot',
      priority: 'urgent',
      estimatedImpact: 'Prevent compounding failures',
      requiresApproval: true,
      approvalTier: 'board',
      linkedSignalIds: ['sig-lyte-002', 'sig-terra-001', 'sig-vessels-002'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-019',
      targetId: 'act-019',
      targetType: 'action',
      verdict: 'pass',
      score: 0.95,
      dimensions: [{ name: 'insight', score: 1.0, rationale: 'Non-obvious link detected.' }],
      flags: ['systemic-risk'],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-019',
    requiresApproval: true,
    mockExecutionResult: { alertIssued: true },
    verificationResult: { status: 'passed', checksum: 'sha256:fusion' },
    proofPacketId: 'proof-019',
    executionTraceId: 'trace-019',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'wc-020',
    name: 'Code Audit Automat',
    vertical: 'alloy-core',
    status: 'completed',
    objective: 'Automated audit of new fabric capability implementations.',
    signals: ['sig-alloy-002'],
    contextPack: { codeRepo: 'a11oy-fabric-core', pr: 1142 },
    agentSequence: [
      { agentId: 'audit-agent', role: 'Security Auditor', action: 'Scan for credential leaks' },
    ],
    actionBrief: {
      id: 'act-020',
      title: 'Approve Deployment',
      description: 'Authorize deployment of audited fabric capability.',
      vertical: 'alloy-core',
      status: 'completed',
      recommendedBy: 'audit-agent',
      priority: 'normal',
      estimatedImpact: 'Safe feature rollout',
      requiresApproval: true,
      approvalTier: 'operator',
      linkedSignalIds: ['sig-alloy-002'],
      linkedOutcomeIds: [],
      createdAt: now(),
      updatedAt: now(),
    },
    mirrorEvalResult: {
      id: 'me-020',
      targetId: 'act-020',
      targetType: 'action',
      verdict: 'pass',
      score: 0.91,
      dimensions: [{ name: 'thoroughness', score: 0.95, rationale: 'Full scan complete.' }],
      flags: [],
      evaluatorModel: 'gpt-4-eval',
      evaluatedAt: now(),
    },
    pceContractId: 'pce-019',
    requiresApproval: true,
    mockExecutionResult: { deployAuthorized: true },
    verificationResult: { status: 'passed', checksum: 'sha256:code' },
    proofPacketId: 'proof-019',
    executionTraceId: 'trace-019',
    createdAt: now(),
    updatedAt: now(),
  },
];

export const SEED_WORKCELLS: Workcell[] = SEED_WORKCELL_FIXTURES.map((workcell) => ({
  ...workcell,
  evidenceState: 'DEMO',
  evidenceReason: SEED_WORKCELL_EVIDENCE_REASON,
}));
