-- Migration: CORTEX Action Drafts
-- Persistent store for autonomous action drafts generated by the CORTEX intelligence engine.
-- Draft lifecycle: pending → approved | dismissed.
-- Approved drafts are surfaced to the Alloy governance execution queue.

CREATE TABLE IF NOT EXISTS cortex_action_drafts (
  id            SERIAL PRIMARY KEY,
  draft_uuid    TEXT NOT NULL UNIQUE,
  org_id        INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
  alert_id      TEXT NOT NULL,
  alert_title   TEXT NOT NULL,
  domain        TEXT NOT NULL,
  draft_type    TEXT NOT NULL CHECK (draft_type IN (
    'legal_hold', 'lp_notification', 'insurance_claim',
    'route_change', 'compliance_memo', 'incident_report', 'risk_brief'
  )),
  title         TEXT NOT NULL,
  content       TEXT NOT NULL,
  recipient     TEXT,
  priority      TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('urgent', 'high', 'normal')),
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'dismissed')),
  metadata      JSONB DEFAULT '{}',
  generated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
  approved_at   TIMESTAMP,
  approved_by   TEXT,
  dismissed_at  TIMESTAMP,
  dismissed_by  TEXT
);

CREATE INDEX IF NOT EXISTS cortex_action_drafts_alert_idx       ON cortex_action_drafts (alert_id);
CREATE INDEX IF NOT EXISTS cortex_action_drafts_status_idx      ON cortex_action_drafts (status);
CREATE INDEX IF NOT EXISTS cortex_action_drafts_domain_idx      ON cortex_action_drafts (domain);
CREATE INDEX IF NOT EXISTS cortex_action_drafts_generated_at_idx ON cortex_action_drafts (generated_at);
CREATE INDEX IF NOT EXISTS cortex_action_drafts_org_idx         ON cortex_action_drafts (org_id);
