CREATE TABLE IF NOT EXISTS "pulse_exec_briefs" (
  "id" text PRIMARY KEY NOT NULL,
  "briefing_id" text,
  "domain" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "headline" text NOT NULL,
  "situation" text NOT NULL,
  "autonomy_tier" text NOT NULL,
  "confidence" numeric NOT NULL,
  "overall_risk" text NOT NULL,
  "verifier_status" text NOT NULL DEFAULT 'pending',
  "verifier_feedback" text,
  "what_we_believe" jsonb NOT NULL DEFAULT '[]',
  "why_citations" jsonb NOT NULL DEFAULT '[]',
  "what_we_recommend" jsonb NOT NULL DEFAULT '[]',
  "source_trace_ids" jsonb NOT NULL DEFAULT '[]',
  "entity_provenance" jsonb NOT NULL DEFAULT '[]',
  "sections" jsonb NOT NULL DEFAULT '[]',
  "scheduled" boolean NOT NULL DEFAULT false,
  "generated_at" timestamp NOT NULL DEFAULT now(),
  "created_at" timestamp NOT NULL DEFAULT now()
);
