-- skill_library schema audit — no table rename required
--
-- Background
-- ----------
-- lib/db/src/schema/skill_library.ts previously defined two tables whose
-- pgTable() first argument matched the canonical cognitive-runtime tables:
--
--   pgTable('skills', ...)       — owned by cognitive_runtime.ts (migration 0046)
--   pgTable('skill_runs', ...)   — owned by cognitive_runtime.ts (migration 0046)
--
-- To eliminate the duplicate TypeScript export and the duplicate-index-name
-- warnings from drizzle-kit, the table name strings inside skill_library.ts
-- were updated to 'skill_library' and 'skill_library_runs', and the file was
-- removed from lib/db/src/schema/index.ts so it is no longer part of the
-- Drizzle schema at all.
--
-- Why no migration is needed
-- --------------------------
-- Because skill_library.ts was excluded from the schema index *before* any
-- Drizzle migration ever ran for those renamed table names, the tables
-- 'skill_library' and 'skill_library_runs' were NEVER created in the
-- database.  No data exists in those table names; nothing needs renaming.
--
-- The canonical 'skills' and 'skill_runs' tables (created by migration 0046)
-- remain intact.  persistence-init.ts reads and writes them via the
-- skillsTable / skillRunsTable exports from cognitive_runtime.ts — no change
-- required there either.
--
-- This file exists solely to record that analysis and to keep the migration
-- journal continuous.  It contains no DDL statements.
