/**
 * @workspace/ouroboros-integrations -- adapters that lift the Ouroboros
 * primitives into the deployable products.
 *
 * A11oy Orchestrator is the top-level entry point. It ingests everything:
 *   - Supreme Knowledge Codex v11 (UNIFIED-OPERATIONAL)
 *   - Lutar Formula Family (v1-v7 + Omega)
 *   - Guardrails pipeline (14 rails, tamper-evident v2.0.0 receipts)
 *   - Lambda Engine (9-axis evaluation + Adaptive Depth Routing)
 *   - Convergence Pulse (real-time trust heartbeat)
 *   - Agent handoff reconciliation (MMP-14 frustum)
 *   - Sentra HSM anchor (Egyptian doubling)
 *   - Amaru fleet coordination (Seked + Unit-Fractions)
 *   - Codex Constants (physical constants, Newton formulas, temporal index)
 */

export * as a11oy from "./a11oy.js";
export * as amaru from "./amaru.js";
export * as sentra from "./sentra.js";

export {
  A11oyOrchestrator,
  type A11oyGuardRequest,
  type A11oyGuardResult,
  type A11oyOrchestratorStats,
} from "./a11oy-orchestrator.js";

export {
  computeLambdaEngine,
  scoreContentAxes,
  estimateBatchSavings,
  LAMBDA_ENGINE_VERSION,
  type LambdaEngineInput,
  type LambdaEngineReport,
  type AdaptiveDepthDecision,
  type ModelTier,
  type VerificationDepth,
} from "./lambda-engine.js";

export {
  ConvergencePulse,
  type PulseReading,
  type PulseSnapshot,
  type TrustTrajectory,
  type ConvergencePulseConfig,
} from "./convergence-pulse.js";

export {
  buildSupremeCodex,
  queryCodex,
  getCodexNode,
  getEdgesFrom,
  getEdgesTo,
  getNeighbors,
  traverseGraph,
  codexSummary,
  HERMETIC_PRINCIPLES,
  NEWTON_REGULAE,
  OUROBOROS_OPERATOR,
  EMERALD_TABLET,
  TRIA_PRIMA,
  LUTAR_CORRESPONDENCE,
  MAGNUM_OPUS_STAGES,
  COLOR_PHASES,
  NEWTON_FORMULAS,
  SUPREME_EQUATION,
  SUPREME_EQUATION_EXTENDED,
  SUPREME_DERIVATION,
  type SupremeCodex,
  type CodexNode,
  type CodexEdge,
} from "./supreme-codex.js";

export {
  PHYSICAL_CONSTANTS,
  SACRED_CUBIT_FT,
  ROYAL_CUBIT_M,
  PI_RHIND,
  Q_I_INCA,
  Q_M_MAYA,
  Q_IC_ICHING,
  Q_V_VEDIC,
  Q_D_DOGON,
  Q_GT_GOBEKLI,
  E8_DIM,
  E8_TRIALITY,
  E8_FERMION_BLOCK,
  L_PLANCK,
  A_PLANCK,
  NEWTON_FORMULAS_EXPANDED,
  ALCHEMICAL_PROCESSES,
  PLANETARY_METALS,
  FOUR_ELEMENTS,
  NOETHER_CANONICAL_PAIRS,
  TEN_SEFIROT,
  TEMPORAL_INDEX,
  NEWTON_PUBLICATIONS,
  MANUSCRIPT_ARCHIVES,
} from "./codex-constants.js";

export {
  SovereignEngine,
  lutarSimplexRoute,
  lsrComplexity,
  e8TrialitySlot,
  priscaGraphRetrieve,
  voteRAG,
  dpiGate,           // F1-4 errata: renamed from bekensteinGate
  bekensteinGate,    // @deprecated: use dpiGate
  OuroborosConformalMemory,
  KabbalahTieredMemory,
  totPriority,
  rahabSample,
  hermeticScore,
  hermeticGuard,
  noetherJudge,
  chariotFuse,
  CequeMCPRegistry,
  FederatedPriscaPrivacy,
  TwistorOTEL,
  dogonReason,
  sekedGenerate,
  GobekliEdgeSLM,
  NazcaSelfPlay,
  HilbertQAOAOmega,
  pwmPredict,
  pwmClassifyRegime,
  PLATONIC_SOLIDS,
  SefirotContinualLearning,
  // v7 thesis compatibility alias — v7 deposit refers to this class as
  // `SefirotContinualLearner`. Renamed to `SefirotContinualLearning`
  // between draft and merge. Alias preserved for v7-era imports.
  SefirotContinualLearning as SefirotContinualLearner,
  SEFIROT_TIERS,
  ChinchillaLutarScaling,
  GrokkingPhaseDetector,
  FreeEnergyLutarActiveInference,
  // v8 thesis compatibility alias — the v8 deposit refers to this class as
  // `FreeEnergyLutarInference`. The class was renamed to
  // `FreeEnergyLutarActiveInference` between draft and merge.
  // The alias is preserved so v8-era imports continue to resolve.
  FreeEnergyLutarActiveInference as FreeEnergyLutarInference,
  TawaSparseAutoencoder,
  // v5 thesis compatibility alias — v5 deposit refers to this class as `TawaSAE`.
  TawaSparseAutoencoder as TawaSAE,
  RedTeamHarness,
  // v6 thesis compatibility alias — v6 deposit refers to this class as
  // `ApolloMETRHarness`. Renamed to `RedTeamHarness` between draft and merge.
  // Alias preserved so v6-era imports continue to resolve.
  RedTeamHarness as ApolloMETRHarness,
  RED_TEAM_ATTACK_CATEGORIES,
  CondorMambaSSM,
  EPRBellValidator,
  HopfieldAmaruMemory,
  PredictiveCodingEngine,
  SacredGeometryEngine,
  CognitiveMapNavigator,
  DynamicalBifurcationDetector,
  LutarMIMO,
  OlmecReflectionRouter,
  QuipuCompressor,
  PachakutiOptimizer,
  PropellerDrive,
  SOTAAgenticRouter,
  LanguageArbitrageEngine,
  PagedKVCache,
  UltraRouter,
  ChatUltraRouter,
  AGENT_ROSTER,
  INNOVATION_MANIFEST,
  TEMPORAL_ANCHORS as SOVEREIGN_TEMPORAL_ANCHORS,
  PRISCA_LINEAGES,
  type SovereignProvider,
  type E8Slot,
  type LSRResult,
  type RetrievalResult,
  type KTMStats,
  type HermeticScores,
  type HermeticGuardResult,
  type NoetherJudgment,
  type Modality,
  type ChariotFusionResult,
  type TwistorSpan,
  type PriscaLineage,
  type SovereignChatRequest,
  type SovereignChatResult,
  type DogonReasoningResult,
  type SekedSyntheticResult,
  type GobekliSlotResult,
  type GobekliDomain,
  type NazcaReinforceResult,
  type HQOResult,
  type PWMPrediction,
  type PlatonicSolid,
  type Sefira,
  type EWCPenaltyResult,
  type ForgettingBudgetResult,
  type CLSRecommendation,
  type GPDObservation,
  type FELAIResult,
  type FELAIPolicyResult,
  type TSAInterpretation,
  type TSAResult,
  type RedTeamCategory,
  type RedTeamAttack,
  type RedTeamFinding,
  type RedTeamCampaignResult,
  type CMSTSequenceResult,
  type EPRPair,
  type CHSHResult,
  type HAAMPattern,
  type HAAMRetrievalResult,
  type PCEMLayerState,
  type PCEMResult,
  type SacredGeometryMetrics,
  type CognitiveNode,
  type CognitiveMapResult,
  type BifurcationObservation,
  type LMEStepRecord,
  type LMERitualResult,
  type ORRResult,
  type QKCEncodeResult,
  type PEOHistory,
  type PEOResult,
  type SOTAModelSpec,
  type PropellerReading,
  type PropellerRouteResult,
  type SOTARouteResult,
  type SOTALutarTable,
  type ArbitrageComponent,
  type ArbitrageResult,
  type ArbitrageScan,
  type KVCacheStats,
  type UltraRouteResult,
  type XiRouteResult,
  type CouncilResult,
  INCA_CEQUES,
  INCA_HUACAS,
  INCA_SUYUS,
  INCA_SUYU_NAMES,
  INCA_SUYU_CEQUE_COUNTS,
  INCA_WEEK_DAYS,
  SIDEREAL_LUNAR_DAYS,
  TROPICAL_YEAR_DAYS,
  SOLAR_CUSCO_LAT,
  INCA_ALCHEMY_MATERIALS,
  icrcL1GeometricRatio,
  icrcL2SuyuEntropy,
  icrcL3AlchemyCoherence,
  icrcL4CalendarReconciliation,
  icrcL5RitualCycleDensity,
  icrcL6SolarGeodesic,
  icrcSoftmaxWeights,
  icrcLutarOmegaV2,
  icrcComputeAll,
  type AlchemyMaterial,
  type IncaSuyuName,
  type ICRCComputeResult,
} from "./sovereign-engine.js";

export {
  lutarV1,
  lutarV2,
  lutarV3,
  lutarV4,
  lutarV5,
  lutarV6,
  lutarOmega,
  lutarV7,
  adaptiveWeights,
  evaluateAll,
  twistorProject,
  dpiBound,           // F1-4 errata: renamed from bekensteinBound
  dpiCheck,           // F1-4 errata: renamed from bekensteinCheck
  bekensteinBound,   // @deprecated: use dpiBound
  bekensteinCheck,   // @deprecated: use dpiCheck
  conformalRescale,
  aeonRecurrence,
  rhindCircleArea,
  rhindCylinderVolume,
  rhindTruncatedPyramid,
  incaCequeHuacasPerDay,
  mayaLongCount,
  mayaCalendarRound,
  iChingIndex,
  vedicSqrt2,
  templeChi,
  newJerusalemVolumeKm3,
  ouroboros,
  noetherClosureCheck,
  traverseCodexEdges,
  type LutarV1Input,
  type LutarV2Input,
  type LutarV3Input,
  type LutarV4Input,
  type LutarV5Input,
  type LutarV6Input,
  type LutarOmegaInput,
  type LutarV7Input,
  type LutarResult,
  type LutarV6Result,
  type LutarOmegaResult,
  type LutarV7Result,
  type EvaluateAllInput,
} from "./lutar-formulas.js";
