import type { OrgSummary, RepoEntry } from "./types.js";

// Sourced from /tmp/payload/github_pro/github_inventory.json crossed with
// /tmp/payload/github_pro/clone_manifest.json. Latest commit SHA pulled from
// the clone manifest; everything else from the inventory record.
export const REPOS: ReadonlyArray<RepoEntry> = [
  {
    name: "amaru",
    fullName: "szl-holdings/amaru",
    description:
      "Convergent multi-source data sync. Append-only delta logs, hash-verified ingest, and bounded loops with measurable convergence.",
    defaultBranch: "main",
    latestCommitSha: "6e1614d541d66fb95557a57d05dfe3c788e34c46",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "716fd4c22b97fdda0826e92fb5a0d5ffba4400f0",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T12:58:31Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/amaru.git",
  },
  {
    name: "a11oy",
    fullName: "szl-holdings/a11oy",
    description:
      "Governed agentic execution fabric. Policy gates, signal mesh, proof ledger, and Λ invariant runtime.",
    defaultBranch: "main",
    latestCommitSha: "3d0f98412ee6738102634b47f7d8618a6e4cd2b5",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "284ab434eb52424b83499567f8cb8e0d780864d3",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T20:48:09Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/a11oy.git",
  },
  {
    name: "sentra",
    fullName: "szl-holdings/sentra",
    description:
      "Cyber resilience command. Threat modeling, posture drift detection, incident response, and policy-gated remediation with full audit trails.",
    defaultBranch: "main",
    latestCommitSha: "2ac304a9511ccbcf20414cdfcc164f9aed5b5092",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "d02cbdbd4b00ab747a804af46106dadbdb2ba676",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T05:33:18Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/sentra.git",
  },
  {
    name: "terra",
    fullName: "szl-holdings/terra",
    description:
      "Real estate intelligence. Deal pipeline scoring, portfolio analytics, market signals, and AI-assisted underwriting.",
    defaultBranch: "main",
    latestCommitSha: "2ffac59c45550220772602f974fc95293a6754a2",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "c45d6ca2861fe7623056264566c8dc2ce93f9c59",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T14:40:14Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/terra.git",
  },
  {
    name: "vessels",
    fullName: "szl-holdings/vessels",
    description:
      "Maritime fleet intelligence. Sanctions screening, dark-vessel detection, ownership graph analysis, and voyage analytics.",
    defaultBranch: "main",
    latestCommitSha: "11e51f628353b0c8b6bb5b1e0b51236662452f76",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "64e0bd024a642f8cca51c4efe14cb60de3e1d70f",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T03:48:32Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/vessels.git",
  },
  {
    name: "counsel",
    fullName: "szl-holdings/counsel",
    description:
      "Legal matter command. Policy-gated AI workflows, document review, obligation mapping, and proof-chain delivery.",
    defaultBranch: "main",
    latestCommitSha: "4decc1c773c06a877bfe6684ea23665e3775943a",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "ff0c594395656ac813d639706bc02a56b535d1e8",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T03:48:33Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/counsel.git",
  },
  {
    name: "carlota-jo",
    fullName: "szl-holdings/carlota-jo",
    description:
      "Private advisory operations. Concierge workflow with proof-chain delivery and multi-party coordination for high-net-worth clients.",
    defaultBranch: "main",
    latestCommitSha: "d1a4ce0beccfffb19e6936a729c9831bfa9b4261",
    latestTag: {
      name: "v1.0.0-alpha",
      sha: "f572913a64dd4db7e6d6054af4cd26737eb798aa",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T08:23:22Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/carlota-jo.git",
  },
  {
    name: "ouroboros",
    fullName: "szl-holdings/ouroboros",
    description:
      "Bounded-loop runtime implementing the Lutar Invariant Λ. Audit-closure operator with sub-millisecond per-request overhead. 172/172 tests, Apache-2.0.",
    defaultBranch: "main",
    latestCommitSha: "d64748cc9ad67296be296c1ef6752ae181413fd7",
    latestTag: {
      name: "v6.3.0",
      sha: "d64748cc9ad67296be296c1ef6752ae181413fd7",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T03:47:54Z",
    scorecard: 6.8,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/ouroboros.git",
  },
  {
    name: "ouroboros-thesis",
    fullName: "szl-holdings/ouroboros-thesis",
    description:
      "The Ouroboros Thesis — peer-reviewable preprints on bounded recursive computation and audit-closure operators for governed AI. Zenodo DOI-pinned. CC BY 4.0.",
    defaultBranch: "main",
    latestCommitSha: "060eb8c8c8a1957b2e1682bf01e99e9ef0dafa4c",
    latestTag: {
      name: "v11.0.0",
      sha: "d495cdff6f2a4cb4f2d4198ef5e52db6b3ef1f4c",
    },
    latestRelease: null,
    pushedAt: "2026-05-15T19:08:22Z",
    scorecard: 7.2,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 6,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/ouroboros-thesis.git",
  },
  {
    name: "lutar-lean",
    fullName: "szl-holdings/lutar-lean",
    description:
      "Machine-checked Lean 4 proofs of the Lutar Invariant (Λ_k) — uniqueness theorem and Egyptian-exact weights. Companion to Paper v12.",
    defaultBranch: "main",
    latestCommitSha: "fcae1aed26a3d8b7fec8aa3dcbd4f334220efa09",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T19:04:05Z",
    scorecard: 7.1,
    branchProtectionStrict: false,
    openCodeScanningAlerts: 5,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/lutar-lean.git",
  },
  {
    name: "szl-trust",
    fullName: "szl-holdings/szl-trust",
    description:
      "SZL Holdings Public Trust Portal — Covenant Proof Standard (CPS) run artifacts. E4 Codex Kernel reference run with 12 receipts (mocked:false), Dresden Codex + IAU citations, deterministic replay.",
    defaultBranch: "main",
    latestCommitSha: "24fd1238d5c06bf249625c60517c008eb9a2f253",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T03:50:33Z",
    scorecard: 6.9,
    branchProtectionStrict: false,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/szl-trust.git",
  },
  {
    name: "szl-cookbook",
    fullName: "szl-holdings/szl-cookbook",
    description:
      "SZL Holdings engineering cookbook — Anthropic skills pattern. 9 skills covering pre-flight thinking, refactoring, review, debugging, dependencies, dead code, docs, and commit hygiene.",
    defaultBranch: "main",
    latestCommitSha: "0593de09406cd524be701ab4d8719f99aeba8f4f",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T03:50:49Z",
    scorecard: 6.9,
    branchProtectionStrict: false,
    openCodeScanningAlerts: 6,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/szl-cookbook.git",
  },
  {
    name: "szl-brand",
    fullName: "szl-holdings/szl-brand",
    description:
      "SZL Holdings brand assets — social preview images (1280×640 PNG), logo monograms, and brand guidance. Upload these to repo Settings → Social preview.",
    defaultBranch: "main",
    latestCommitSha: "d86a37d5305a30886f7884cc4114cda48a8a3402",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T03:52:31Z",
    scorecard: 6.9,
    branchProtectionStrict: false,
    openCodeScanningAlerts: 6,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/szl-brand.git",
  },
  {
    name: ".github",
    fullName: "szl-holdings/.github",
    description: "SZL Holdings organization profile and community files.",
    defaultBranch: "main",
    latestCommitSha: "ae4e7ad21edac4451688e043727790da36f6c4b2",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T03:53:36Z",
    scorecard: 6.5,
    branchProtectionStrict: true,
    openCodeScanningAlerts: 15,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/.github.git",
  },
  {
    name: "vsp-otel",
    fullName: "szl-holdings/vsp-otel",
    description:
      "Verifiable Span Protocol — cryptographically-verifiable OpenTelemetry GenAI bridge. Lutar, Stephen P. ORCID 0009-0001-0110-4173",
    defaultBranch: "main",
    latestCommitSha: "7aca58d2d7ceecbd2ab7f576b63b320f94cacda1",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T18:12:44Z",
    scorecard: 5.0,
    branchProtectionStrict: false,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/vsp-otel.git",
  },
  {
    name: "agi-forecast",
    fullName: "szl-holdings/agi-forecast",
    description:
      "Lutar-Forecast Gauge — receipt-attested AGI capability gauges (METR, Epoch, ARC, Apollo, AISI, RSP, FSF). Lutar, Stephen P. ORCID 0009-0001-0110-4173",
    defaultBranch: "main",
    latestCommitSha: "2c729680a2d9f1ef3918baeab9d84d6201605330",
    latestTag: null,
    latestRelease: null,
    pushedAt: "2026-05-15T18:12:44Z",
    scorecard: 5.0,
    branchProtectionStrict: false,
    openCodeScanningAlerts: 7,
    openDependabotHighCritical: 0,
    cloneUrl: "https://github.com/szl-holdings/agi-forecast.git",
  },
];

export const ORG_SUMMARY: OrgSummary = {
  reposTotal: 16,
  ciFailing: 0,
  openPrs: 64,
  openAlertsCodeScanning: 115,
  openDependabotHighCritical: 0,
  scorecardAvg: 6.62,
  branchProtectionCompliant: 10,
  branchProtectionWeak: 6,
  hygieneGaps: ["vsp-otel", "agi-forecast"],
};
