import { colors, effects, motion, spacing, typography } from './tokens';

export const surfaceCard = {
  base: {
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
  },
  raised: {
    background: effects.surface.raised.background,
    border: effects.surface.raised.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    boxShadow: effects.surface.raised.boxShadow,
  },
  elevated: {
    background: effects.surface.overlay.background,
    border: effects.surface.overlay.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    boxShadow: effects.surface.overlay.boxShadow,
  },
  interactive: {
    background: effects.surface.interactive.background,
    border: effects.surface.interactive.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    transition: `background ${motion.duration.fast} ${motion.easing.default}, border-color ${motion.duration.fast} ${motion.easing.default}, box-shadow ${motion.duration.fast} ${motion.easing.default}`,
    cursor: 'pointer',
  },
  interactiveHover: {
    background: effects.surface.interactiveHover.background,
    border: effects.surface.interactiveHover.border,
    boxShadow: effects.shadow.sm,
  },
} as const;

export const premiumCard = {
  platform: {
    background: effects.cardVariants.platform.background,
    border: effects.cardVariants.platform.border,
    borderRadius: effects.cardVariants.platform.borderRadius,
    boxShadow: effects.cardVariants.platform.boxShadow,
    padding: spacing.card.paddingRelaxed,
    transition: `background ${motion.duration.fast} ${motion.easing.smooth}, border-color ${motion.duration.fast} ${motion.easing.smooth}, box-shadow ${motion.duration.normal} ${motion.easing.smooth}`,
    cursor: 'pointer',
  },
  platformHover: {
    background: effects.surface.cardHover.background,
    border: effects.surface.cardHover.border,
    boxShadow: effects.shadow.lg,
  },
  feature: {
    background: effects.cardVariants.feature.background,
    border: effects.cardVariants.feature.border,
    borderRadius: effects.cardVariants.feature.borderRadius,
    boxShadow: effects.cardVariants.feature.boxShadow,
    padding: spacing.card.padding,
    transition: `background ${motion.duration.fast} ${motion.easing.smooth}, border-color ${motion.duration.fast} ${motion.easing.smooth}`,
    cursor: 'pointer',
  },
  featureHover: {
    background: effects.surface.cardHover.background,
    border: effects.surface.cardHover.border,
    boxShadow: effects.shadow.md,
  },
  kpi: {
    background: effects.cardVariants.kpi.background,
    border: effects.cardVariants.kpi.border,
    borderRadius: effects.cardVariants.kpi.borderRadius,
    boxShadow: effects.cardVariants.kpi.boxShadow,
    padding: spacing.card.padding,
  },
  commandPanel: {
    background: effects.cardVariants.commandPanel.background,
    border: effects.cardVariants.commandPanel.border,
    borderRadius: effects.cardVariants.commandPanel.borderRadius,
    boxShadow: effects.cardVariants.commandPanel.boxShadow,
    padding: spacing.card.paddingRelaxed,
  },
  agent: {
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.md,
    padding: spacing.card.paddingCompact,
    boxShadow: effects.shadow.xs,
  },
  status: {
    background: effects.surface.raised.background,
    border: effects.surface.raised.border,
    borderRadius: effects.borderRadius.md,
    padding: spacing.card.padding,
  },
} as const;

export const glassCard = {
  base: {
    background: effects._legacy.glassmorphism.background,
    backdropFilter: effects._legacy.glassmorphism.backdropFilter,
    border: effects._legacy.glassmorphism.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
  },
  elevated: {
    background: effects._legacy.glassmorphismStrong.background,
    backdropFilter: effects._legacy.glassmorphismStrong.backdropFilter,
    border: effects._legacy.glassmorphismStrong.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    boxShadow: effects.shadow.lg,
  },
  interactive: {
    background: effects._legacy.glassmorphism.background,
    backdropFilter: effects._legacy.glassmorphism.backdropFilter,
    border: effects._legacy.glassmorphism.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    transition: `all ${motion.duration.fast} ${motion.easing.default}`,
    cursor: 'pointer',
  },
} as const;

export const premiumButton = {
  primary: {
    background: colors.text.primary,
    color: colors.background.primary,
    border: '1px solid transparent',
    borderRadius: effects.borderRadius.md,
    padding: '0.625rem 1.375rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    letterSpacing: '-0.005em',
    transition: `all ${motion.duration.fast} ${motion.easing.smooth}`,
    cursor: 'pointer',
  },
  primaryHover: {
    background: colors.neutral.warmOffWhite,
    boxShadow: effects.shadow.md,
  },
  secondary: {
    background: 'transparent',
    color: colors.text.secondary,
    border: `1px solid ${colors.border.DEFAULT}`,
    borderRadius: effects.borderRadius.md,
    padding: '0.625rem 1.375rem',
    fontSize: '0.875rem',
    fontWeight: '500',
    letterSpacing: '-0.005em',
    transition: `all ${motion.duration.fast} ${motion.easing.smooth}`,
    cursor: 'pointer',
  },
  secondaryHover: {
    color: colors.text.primary,
    borderColor: colors.border.strong,
    background: 'hsla(0 0% 100% / 0.04)',
  },
  ghost: {
    background: 'transparent',
    color: colors.text.muted,
    border: '1px solid transparent',
    borderRadius: effects.borderRadius.md,
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
    fontWeight: '500',
    transition: `all ${motion.duration.fast} ${motion.easing.smooth}`,
    cursor: 'pointer',
  },
  ghostHover: {
    color: colors.text.primary,
    background: 'hsla(0 0% 100% / 0.04)',
  },
  icon: {
    background: 'transparent',
    color: colors.text.muted,
    border: `1px solid ${colors.border.DEFAULT}`,
    borderRadius: effects.borderRadius.md,
    padding: '0.5rem',
    transition: `all ${motion.duration.fast} ${motion.easing.smooth}`,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
} as const;

export const premiumBadge = {
  base: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.3125rem',
    padding: '0.1875rem 0.5rem',
    borderRadius: effects.borderRadius.sm,
    fontSize: '0.6875rem',
    fontWeight: '600' as const,
    letterSpacing: '0.05em',
    lineHeight: '1.4',
    whiteSpace: 'nowrap' as const,
    transition: `opacity ${motion.duration.fast} ${motion.easing.default}`,
  },
  severity: {
    critical: {
      color: colors.semantic.critical,
      background: colors.semantic.criticalMuted,
      border: `1px solid ${colors.semantic.criticalMuted}`,
    },
    high: {
      color: colors.semantic.high,
      background: colors.semantic.highMuted,
      border: `1px solid ${colors.semantic.highMuted}`,
    },
    medium: {
      color: colors.semantic.medium,
      background: colors.semantic.mediumMuted,
      border: `1px solid ${colors.semantic.mediumMuted}`,
    },
    low: {
      color: colors.semantic.low,
      background: colors.semantic.lowMuted,
      border: `1px solid ${colors.semantic.lowMuted}`,
    },
    stable: {
      color: colors.semantic.stable,
      background: colors.semantic.stableMuted,
      border: `1px solid ${colors.semantic.stableMuted}`,
    },
  },
  productState: {
    live: {
      color: colors.productState.live.color,
      background: colors.productState.live.bg,
      border: `1px solid ${colors.productState.live.border}`,
    },
    pilotReady: {
      color: colors.productState.pilotReady.color,
      background: colors.productState.pilotReady.bg,
      border: `1px solid ${colors.productState.pilotReady.border}`,
    },
    inBuild: {
      color: colors.productState.inBuild.color,
      background: colors.productState.inBuild.bg,
      border: `1px solid ${colors.productState.inBuild.border}`,
    },
    strategic: {
      color: colors.productState.strategic.color,
      background: colors.productState.strategic.bg,
      border: `1px solid ${colors.productState.strategic.border}`,
    },
    internal: {
      color: colors.productState.internal.color,
      background: colors.productState.internal.bg,
      border: `1px solid ${colors.productState.internal.border}`,
    },
    privateDemo: {
      color: colors.productState.privateDemo.color,
      background: colors.productState.privateDemo.bg,
      border: `1px solid ${colors.productState.privateDemo.border}`,
    },
  },
  neutral: {
    color: colors.text.muted,
    background: 'hsla(0 0% 100% / 0.05)',
    border: `1px solid ${colors.border.DEFAULT}`,
  },
} as const;

export const dataUI = {
  kpiTile: {
    container: {
      ...premiumCard.kpi,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '0.75rem',
    },
    label: {
      color: colors.text.muted,
      fontSize: '0.75rem',
      fontWeight: '500',
      letterSpacing: '0.04em',
      textTransform: 'uppercase' as const,
    },
    value: {
      color: colors.text.primary,
      fontSize: '2.25rem',
      fontWeight: '600',
      lineHeight: '1.1',
      letterSpacing: '-0.02em',
      fontFamily: typography.fontFamily.display,
    },
    unit: {
      color: colors.text.muted,
      fontSize: '1rem',
      fontWeight: '400',
    },
    trend: {
      up: {
        color: colors.semantic.low,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        fontSize: '0.8125rem',
        fontWeight: '500',
      },
      down: {
        color: colors.semantic.critical,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        fontSize: '0.8125rem',
        fontWeight: '500',
      },
      neutral: {
        color: colors.text.muted,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.25rem',
        fontSize: '0.8125rem',
        fontWeight: '500',
      },
    },
  },
  signalCard: {
    container: {
      ...premiumCard.feature,
      position: 'relative' as const,
      overflow: 'hidden' as const,
    },
    header: {
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: '0.75rem',
    },
    title: {
      color: colors.text.primary,
      fontSize: '0.9375rem',
      fontWeight: '600',
      letterSpacing: '-0.005em',
      lineHeight: '1.4',
    },
    body: {
      color: colors.text.secondary,
      fontSize: '0.875rem',
      lineHeight: '1.58',
    },
    meta: {
      color: colors.text.muted,
      fontSize: '0.75rem',
      fontWeight: '500',
    },
  },
  modularPanel: {
    container: {
      ...premiumCard.commandPanel,
      overflow: 'hidden' as const,
    },
    header: {
      padding: '1rem 1.5rem',
      borderBottom: `1px solid ${colors.border.DEFAULT}`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerTitle: {
      color: colors.text.primary,
      fontSize: '0.875rem',
      fontWeight: '600',
      letterSpacing: '-0.005em',
    },
    body: {
      padding: '1.25rem 1.5rem',
    },
    footer: {
      padding: '0.875rem 1.5rem',
      borderTop: `1px solid ${colors.border.subtle}`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
  },
  filterBar: {
    container: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      padding: '0.5rem 0',
    },
    chip: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.375rem',
      padding: '0.3125rem 0.75rem',
      borderRadius: effects.borderRadius.full,
      background: 'hsla(0 0% 100% / 0.05)',
      border: `1px solid ${colors.border.DEFAULT}`,
      color: colors.text.secondary,
      fontSize: '0.8125rem',
      fontWeight: '500',
      cursor: 'pointer',
      transition: `all ${motion.duration.fast} ${motion.easing.smooth}`,
    },
    chipActive: {
      background: 'hsla(0 0% 100% / 0.08)',
      border: `1px solid ${colors.border.strong}`,
      color: colors.text.primary,
    },
  },
  drawer: {
    overlay: {
      position: 'fixed' as const,
      inset: 0,
      background: 'hsla(0 0% 0% / 0.52)',
      backdropFilter: 'blur(4px)',
      zIndex: 300,
    },
    panel: {
      position: 'fixed' as const,
      top: 0,
      right: 0,
      bottom: 0,
      width: 'min(480px, 92vw)',
      background: colors.background.elevated,
      border: `1px solid ${colors.border.DEFAULT}`,
      borderRight: 'none',
      boxShadow: effects.shadow.xl,
      zIndex: 301,
      overflowY: 'auto' as const,
      display: 'flex',
      flexDirection: 'column' as const,
    },
  },
  chartContainer: {
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.lg,
    padding: '1.25rem',
  },
} as const;

export const dashboardLayout = {
  container: {
    display: 'grid',
    gridTemplateColumns: `${spacing.layout.sidebarWidth} 1fr`,
    minHeight: '100vh',
    background: colors.background.primary,
  },
  sidebar: {
    background: colors.background.secondary,
    borderRight: `1px solid ${colors.border.DEFAULT}`,
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.25rem',
    overflowY: 'auto' as const,
    height: '100vh',
    position: 'sticky' as const,
    top: 0,
  },
  sidebarHeader: {
    padding: '0.5rem 0.25rem 1rem',
    marginBottom: '0.25rem',
    borderBottom: `1px solid ${colors.border.subtle}`,
  },
  sidebarSection: {
    padding: '0.75rem 0 0.25rem',
    color: colors.text.muted,
    fontSize: '0.6875rem',
    fontWeight: '600',
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
  },
  sidebarItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.625rem',
    padding: '0.4375rem 0.625rem',
    borderRadius: effects.borderRadius.md,
    color: colors.text.secondary,
    fontSize: '0.875rem',
    fontWeight: '450',
    cursor: 'pointer',
    transition: `background ${motion.duration.fast} ${motion.easing.default}, color ${motion.duration.fast} ${motion.easing.default}`,
    userSelect: 'none' as const,
  },
  sidebarItemActive: {
    background: colors.primary.muted,
    color: colors.text.primary,
  },
  sidebarItemHover: {
    background: colors.surface.hover,
    color: colors.text.primary,
  },
  main: {
    padding: spacing.page.x,
    overflow: 'auto',
    minWidth: 0,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: spacing.layout.headerHeight,
    paddingBottom: '1.5rem',
    borderBottom: `1px solid ${colors.border.subtle}`,
    marginBottom: '2rem',
  },
  topbar: {
    height: spacing.layout.headerHeight,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 1.5rem',
    background: colors.background.secondary,
    borderBottom: `1px solid ${colors.border.DEFAULT}`,
    position: 'sticky' as const,
    top: 0,
    zIndex: 200,
  },
} as const;

export const setupLayout = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    background: colors.background.primary,
    backgroundImage: effects.gradient.meshDark,
    padding: spacing.page.x,
  },
  card: {
    ...surfaceCard.elevated,
    maxWidth: '440px',
    width: '100%',
    textAlign: 'center' as const,
  },
  title: {
    color: colors.text.primary,
    fontSize: '1.25rem',
    fontWeight: '600',
    letterSpacing: '-0.01em',
    marginBottom: '0.375rem',
  },
  description: {
    color: colors.text.secondary,
    fontSize: '0.9375rem',
    lineHeight: '1.6',
    marginBottom: '1.5rem',
  },
} as const;

export const emptyState = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem 2rem',
    textAlign: 'center' as const,
  },
  icon: {
    width: '3rem',
    height: '3rem',
    color: colors.text.muted,
    marginBottom: '1.25rem',
    opacity: 0.5,
    strokeWidth: 1.25,
  },
  title: {
    color: colors.text.primary,
    fontSize: '1.0625rem',
    fontWeight: '600',
    letterSpacing: '-0.005em',
    marginBottom: '0.375rem',
  },
  description: {
    color: colors.text.secondary,
    fontSize: '0.9375rem',
    lineHeight: '1.6',
    maxWidth: '22rem',
  },
  action: {
    marginTop: '1.75rem',
    background: colors.primary.DEFAULT,
    color: colors.background.primary,
    border: 'none',
    borderRadius: effects.borderRadius.md,
    padding: '0.5rem 1.125rem',
    fontSize: '0.875rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: `opacity ${motion.duration.fast} ${motion.easing.default}`,
  },
} as const;

export const statCard = {
  container: {
    ...surfaceCard.base,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  label: {
    color: colors.text.tertiary,
    fontSize: '0.75rem',
    fontWeight: '500',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  value: {
    color: colors.text.primary,
    fontSize: '2rem',
    fontWeight: '600',
    lineHeight: '1.1',
    letterSpacing: '-0.02em',
    fontFamily: typography.fontFamily.display,
  },
  unit: {
    color: colors.text.tertiary,
    fontSize: '1rem',
    fontWeight: '400',
    marginLeft: '0.25rem',
  },
  trend: {
    up: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.25rem',
      color: colors.semantic.low,
      fontSize: '0.8125rem',
      fontWeight: '500',
    },
    down: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.25rem',
      color: colors.semantic.error,
      fontSize: '0.8125rem',
      fontWeight: '500',
    },
    neutral: {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '0.25rem',
      color: colors.text.muted,
      fontSize: '0.8125rem',
      fontWeight: '500',
    },
  },
  footer: {
    borderTop: `1px solid ${colors.border.subtle}`,
    paddingTop: '0.75rem',
    marginTop: '0.25rem',
    color: colors.text.tertiary,
    fontSize: '0.8125rem',
  },
} as const;

export const hierarchy = {
  eyebrow: {
    color: colors.text.muted,
    fontSize: '0.6875rem',
    fontWeight: '500',
    letterSpacing: '0.10em',
    textTransform: 'uppercase' as const,
    marginBottom: '0.375rem',
  },
  display: {
    color: colors.text.primary,
    fontSize: 'clamp(2.75rem, 5.5vw, 4rem)',
    fontWeight: '700',
    letterSpacing: '-0.026em',
    lineHeight: '1.06',
  },
  heading: {
    color: colors.text.primary,
    fontSize: '1.5rem',
    fontWeight: '600',
    letterSpacing: '-0.01em',
    lineHeight: '1.28',
  },
  subheading: {
    color: colors.text.secondary,
    fontSize: '1rem',
    fontWeight: '400',
    lineHeight: '1.62',
  },
  lead: {
    color: colors.text.secondary,
    fontSize: '1.0625rem',
    fontWeight: '400',
    lineHeight: '1.65',
  },
  body: {
    color: colors.text.secondary,
    fontSize: '0.9375rem',
    fontWeight: '400',
    lineHeight: '1.62',
  },
  caption: {
    color: colors.text.tertiary,
    fontSize: '0.8125rem',
    fontWeight: '400',
    lineHeight: '1.5',
  },
  label: {
    color: colors.text.muted,
    fontSize: '0.75rem',
    fontWeight: '500',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  mono: {
    fontFamily: typography.fontFamily.mono,
    color: colors.text.secondary,
    fontSize: '0.8125rem',
    fontWeight: '400',
    letterSpacing: '0.01em',
  },
} as const;
