import { effects, colors, spacing, typography, motion } from "./tokens";

export const surfaceCard = {
  base: {
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
  },
  raised: {
    background: effects.surface.raised.background,
    border: effects.surface.raised.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    boxShadow: effects.surface.raised.boxShadow,
  },
  elevated: {
    background: effects.surface.overlay.background,
    border: effects.surface.overlay.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    boxShadow: effects.surface.overlay.boxShadow,
  },
  interactive: {
    background: effects.surface.interactive.background,
    border: effects.surface.interactive.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    transition: `background ${motion.duration.fast} ${motion.easing.default}, border-color ${motion.duration.fast} ${motion.easing.default}, box-shadow ${motion.duration.fast} ${motion.easing.default}`,
    cursor: "pointer",
  },
  interactiveHover: {
    background: effects.surface.interactiveHover.background,
    border: effects.surface.interactiveHover.border,
    boxShadow: effects.shadow.sm,
  },
} as const;

export const glassCard = {
  base: {
    background: effects._legacy.glassmorphism.background,
    backdropFilter: effects._legacy.glassmorphism.backdropFilter,
    border: effects._legacy.glassmorphism.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
  },
  elevated: {
    background: effects._legacy.glassmorphismStrong.background,
    backdropFilter: effects._legacy.glassmorphismStrong.backdropFilter,
    border: effects._legacy.glassmorphismStrong.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    boxShadow: effects.shadow.lg,
  },
  interactive: {
    background: effects._legacy.glassmorphism.background,
    backdropFilter: effects._legacy.glassmorphism.backdropFilter,
    border: effects._legacy.glassmorphism.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    transition: `all ${motion.duration.fast} ${motion.easing.default}`,
    cursor: "pointer",
    _hover: {
      background: colors._legacyGlass.glassHover,
      boxShadow: effects.shadow.md,
    },
  },
} as const;

export const dashboardLayout = {
  container: {
    display: "grid",
    gridTemplateColumns: `${spacing.layout.sidebarWidth} 1fr`,
    minHeight: "100vh",
    background: colors.background.primary,
  },
  sidebar: {
    background: colors.background.secondary,
    borderRight: `1px solid ${colors.border.DEFAULT}`,
    padding: "1rem",
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.25rem",
    overflowY: "auto" as const,
    height: "100vh",
    position: "sticky" as const,
    top: 0,
  },
  sidebarHeader: {
    padding: "0.5rem 0.25rem 1rem",
    marginBottom: "0.25rem",
    borderBottom: `1px solid ${colors.border.subtle}`,
  },
  sidebarSection: {
    padding: "0.75rem 0 0.25rem",
    color: colors.text.muted,
    fontSize: "0.6875rem",
    fontWeight: "600",
    letterSpacing: "0.06em",
    textTransform: "uppercase" as const,
  },
  sidebarItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.625rem",
    padding: "0.4375rem 0.625rem",
    borderRadius: effects.borderRadius.md,
    color: colors.text.secondary,
    fontSize: "0.875rem",
    fontWeight: "450",
    cursor: "pointer",
    transition: `background ${motion.duration.fast} ${motion.easing.default}, color ${motion.duration.fast} ${motion.easing.default}`,
    userSelect: "none" as const,
  },
  sidebarItemActive: {
    background: colors.primary.muted,
    color: colors.text.primary,
  },
  sidebarItemHover: {
    background: colors.surface.hover,
    color: colors.text.primary,
  },
  main: {
    padding: spacing.page.x,
    overflow: "auto",
    minWidth: 0,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: spacing.layout.headerHeight,
    paddingBottom: "1.5rem",
    borderBottom: `1px solid ${colors.border.subtle}`,
    marginBottom: "2rem",
  },
  topbar: {
    height: spacing.layout.headerHeight,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 1.5rem",
    background: colors.background.secondary,
    borderBottom: `1px solid ${colors.border.DEFAULT}`,
    position: "sticky" as const,
    top: 0,
    zIndex: 200,
  },
} as const;

export const setupLayout = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    background: colors.background.primary,
    backgroundImage: effects.gradient.meshDark,
    padding: spacing.page.x,
  },
  card: {
    ...surfaceCard.elevated,
    maxWidth: "440px",
    width: "100%",
    textAlign: "center" as const,
  },
  title: {
    color: colors.text.primary,
    fontSize: "1.25rem",
    fontWeight: "600",
    letterSpacing: "-0.01em",
    marginBottom: "0.375rem",
  },
  description: {
    color: colors.text.secondary,
    fontSize: "0.9375rem",
    lineHeight: "1.6",
    marginBottom: "1.5rem",
  },
} as const;

export const emptyState = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "4rem 2rem",
    textAlign: "center" as const,
  },
  icon: {
    width: "3rem",
    height: "3rem",
    color: colors.text.muted,
    marginBottom: "1.25rem",
    opacity: 0.5,
    strokeWidth: 1.25,
  },
  title: {
    color: colors.text.primary,
    fontSize: "1.0625rem",
    fontWeight: "600",
    letterSpacing: "-0.005em",
    marginBottom: "0.375rem",
  },
  description: {
    color: colors.text.secondary,
    fontSize: "0.9375rem",
    lineHeight: "1.6",
    maxWidth: "22rem",
  },
  action: {
    marginTop: "1.75rem",
    background: colors.primary.DEFAULT,
    color: colors.text.primary,
    border: "none",
    borderRadius: effects.borderRadius.md,
    padding: "0.5rem 1.125rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    cursor: "pointer",
    transition: `opacity ${motion.duration.fast} ${motion.easing.default}`,
  },
} as const;

export const statCard = {
  container: {
    ...surfaceCard.base,
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  label: {
    color: colors.text.tertiary,
    fontSize: "0.75rem",
    fontWeight: "500",
    letterSpacing: "0.04em",
    textTransform: "uppercase" as const,
  },
  value: {
    color: colors.text.primary,
    fontSize: "2rem",
    fontWeight: "600",
    lineHeight: "1.1",
    letterSpacing: "-0.02em",
    fontFamily: typography.fontFamily.display,
  },
  unit: {
    color: colors.text.tertiary,
    fontSize: "1rem",
    fontWeight: "400",
    marginLeft: "0.25rem",
  },
  trend: {
    up: {
      display: "inline-flex",
      alignItems: "center",
      gap: "0.25rem",
      color: colors.status.success,
      fontSize: "0.8125rem",
      fontWeight: "500",
    },
    down: {
      display: "inline-flex",
      alignItems: "center",
      gap: "0.25rem",
      color: colors.status.error,
      fontSize: "0.8125rem",
      fontWeight: "500",
    },
    neutral: {
      display: "inline-flex",
      alignItems: "center",
      gap: "0.25rem",
      color: colors.text.muted,
      fontSize: "0.8125rem",
      fontWeight: "500",
    },
  },
  footer: {
    borderTop: `1px solid ${colors.border.subtle}`,
    paddingTop: "0.75rem",
    marginTop: "0.25rem",
    color: colors.text.tertiary,
    fontSize: "0.8125rem",
  },
} as const;

export const hierarchy = {
  eyebrow: {
    color: colors.text.muted,
    fontSize: "0.6875rem",
    fontWeight: "600",
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    marginBottom: "0.375rem",
  },
  heading: {
    color: colors.text.primary,
    fontSize: "1.5rem",
    fontWeight: "600",
    letterSpacing: "-0.01em",
    lineHeight: "1.25",
  },
  subheading: {
    color: colors.text.secondary,
    fontSize: "1rem",
    fontWeight: "400",
    lineHeight: "1.6",
  },
  body: {
    color: colors.text.secondary,
    fontSize: "0.9375rem",
    fontWeight: "400",
    lineHeight: "1.65",
  },
  caption: {
    color: colors.text.tertiary,
    fontSize: "0.8125rem",
    fontWeight: "400",
    lineHeight: "1.5",
  },
  label: {
    color: colors.text.muted,
    fontSize: "0.75rem",
    fontWeight: "500",
    letterSpacing: "0.04em",
    textTransform: "uppercase" as const,
  },
  mono: {
    fontFamily: typography.fontFamily.mono,
    color: colors.text.secondary,
    fontSize: "0.8125rem",
    fontWeight: "400",
    letterSpacing: "0.01em",
  },
} as const;
