import { effects, colors, spacing, typography, motion } from "./tokens";

export const kpiRibbon = {
  container: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: spacing.grid.gap,
    padding: "0.5rem 0",
  },
  item: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.75rem",
    padding: spacing.card.paddingCompact,
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.md,
    transition: `background ${motion.duration.fast} ${motion.easing.default}, border-color ${motion.duration.fast} ${motion.easing.default}`,
  },
  itemHover: {
    background: effects.surface.raised.background,
    border: effects.surface.raised.border,
    boxShadow: effects.shadow.sm,
  },
  label: {
    color: colors.text.muted,
    fontSize: "0.75rem",
    fontWeight: "500",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  value: {
    color: colors.text.primary,
    fontSize: "1.625rem",
    fontWeight: "600",
    lineHeight: "1.15",
    letterSpacing: "-0.02em",
    fontFamily: typography.fontFamily.display,
  },
  delta: {
    positive: {
      display: "inline-flex",
      alignItems: "center",
      gap: "0.25rem",
      color: colors.status.success,
      fontSize: "0.8125rem",
      fontWeight: "500",
    },
    negative: {
      display: "inline-flex",
      alignItems: "center",
      gap: "0.25rem",
      color: colors.status.error,
      fontSize: "0.8125rem",
      fontWeight: "500",
    },
    neutral: {
      display: "inline-flex",
      alignItems: "center",
      gap: "0.25rem",
      color: colors.text.muted,
      fontSize: "0.8125rem",
      fontWeight: "500",
    },
  },
  sparkline: {
    height: "2rem",
    width: "100%",
    marginTop: "0.25rem",
    opacity: 0.7,
  },
} as const;

export const chartContainer = {
  wrapper: {
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.lg,
    padding: spacing.card.padding,
    display: "flex",
    flexDirection: "column" as const,
    gap: "1.25rem",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  title: {
    color: colors.text.primary,
    fontSize: "0.9375rem",
    fontWeight: "600",
    letterSpacing: "-0.005em",
    fontFamily: typography.fontFamily.display,
  },
  subtitle: {
    color: colors.text.tertiary,
    fontSize: "0.8125rem",
    marginTop: "0.25rem",
    lineHeight: "1.4",
  },
  controls: {
    display: "flex",
    gap: "0.375rem",
    alignItems: "center",
    flexShrink: 0,
  },
  body: {
    flex: "1",
    minHeight: "200px",
    position: "relative" as const,
  },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: "0.75rem",
    borderTop: `1px solid ${colors.border.subtle}`,
    color: colors.text.muted,
    fontSize: "0.75rem",
  },
} as const;

export const dataTableShell = {
  container: {
    background: effects.surface.base.background,
    border: effects.surface.base.border,
    borderRadius: effects.borderRadius.lg,
    overflow: "hidden",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.875rem 1.25rem",
    borderBottom: `1px solid ${colors.border.subtle}`,
    gap: "1rem",
  },
  searchInput: {
    background: colors.background.tertiary,
    border: `1px solid ${colors.border.DEFAULT}`,
    borderRadius: effects.borderRadius.md,
    padding: "0.4375rem 0.75rem",
    color: colors.text.primary,
    fontSize: "0.875rem",
    outline: "none",
    minWidth: "200px",
    transition: `border-color ${motion.duration.fast} ${motion.easing.default}`,
  },
  searchInputFocus: {
    borderColor: colors.border.focus,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  headerRow: {
    borderBottom: `1px solid ${colors.border.DEFAULT}`,
  },
  headerCell: {
    padding: "0.625rem 1.25rem",
    color: colors.text.muted,
    fontSize: "0.75rem",
    fontWeight: "600",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
    textAlign: "left" as const,
    whiteSpace: "nowrap" as const,
    userSelect: "none" as const,
    cursor: "pointer",
  },
  row: {
    borderBottom: `1px solid ${colors.border.subtle}`,
    transition: `background ${motion.duration.instant} ${motion.easing.default}`,
  },
  rowHover: {
    background: effects.surface.raised.background,
  },
  cell: {
    padding: "0.6875rem 1.25rem",
    color: colors.text.primary,
    fontSize: "0.875rem",
  },
  pagination: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.625rem 1.25rem",
    borderTop: `1px solid ${colors.border.subtle}`,
    color: colors.text.tertiary,
    fontSize: "0.8125rem",
  },
} as const;

export const statusPill = {
  base: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.3125rem",
    padding: "0.1875rem 0.625rem",
    borderRadius: effects.borderRadius.full,
    fontSize: "0.75rem",
    fontWeight: "500",
    letterSpacing: "0.01em",
    lineHeight: "1.4",
    whiteSpace: "nowrap" as const,
  },
  variants: {
    success: {
      background: colors.status.successMuted,
      color: colors.status.success,
      border: `1px solid hsla(152, 60%, 48%, 0.20)`,
    },
    warning: {
      background: colors.status.warningMuted,
      color: colors.status.warning,
      border: `1px solid hsla(38, 90%, 54%, 0.20)`,
    },
    error: {
      background: colors.status.errorMuted,
      color: colors.status.error,
      border: `1px solid hsla(4, 72%, 56%, 0.20)`,
    },
    info: {
      background: colors.status.infoMuted,
      color: colors.status.info,
      border: `1px solid hsla(210, 80%, 56%, 0.20)`,
    },
    neutral: {
      background: "hsla(0 0% 100% / 0.06)",
      color: colors.text.secondary,
      border: `1px solid ${colors.border.DEFAULT}`,
    },
  },
  dot: {
    width: "0.3125rem",
    height: "0.3125rem",
    borderRadius: "50%",
    flexShrink: 0,
  },
} as const;

export const alertBanner = {
  base: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.75rem",
    padding: "0.875rem 1rem",
    borderRadius: effects.borderRadius.md,
    fontSize: "0.875rem",
    lineHeight: "1.55",
  },
  variants: {
    info: {
      background: colors.status.infoMuted,
      border: `1px solid hsla(210, 80%, 56%, 0.18)`,
      color: colors.text.primary,
    },
    success: {
      background: colors.status.successMuted,
      border: `1px solid hsla(152, 60%, 48%, 0.18)`,
      color: colors.text.primary,
    },
    warning: {
      background: colors.status.warningMuted,
      border: `1px solid hsla(38, 90%, 54%, 0.18)`,
      color: colors.text.primary,
    },
    error: {
      background: colors.status.errorMuted,
      border: `1px solid hsla(4, 72%, 56%, 0.18)`,
      color: colors.text.primary,
    },
  },
  icon: {
    flexShrink: 0,
    width: "1.125rem",
    height: "1.125rem",
    marginTop: "0.125rem",
    strokeWidth: 2,
  },
  content: {
    flex: "1",
  },
  title: {
    fontWeight: "600",
    marginBottom: "0.1875rem",
  },
  dismiss: {
    flexShrink: 0,
    background: "none",
    border: "none",
    color: colors.text.muted,
    cursor: "pointer",
    padding: "0.125rem",
    borderRadius: effects.borderRadius.sm,
    transition: `color ${motion.duration.fast} ${motion.easing.default}`,
    lineHeight: 1,
  },
} as const;

export const modalDrawer = {
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "hsla(216 14% 3% / 0.72)",
    backdropFilter: "blur(2px)",
    zIndex: 300,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    background: effects.surface.overlay.background,
    border: effects.surface.overlay.border,
    borderRadius: effects.borderRadius.xl,
    boxShadow: effects.shadow["2xl"],
    width: "100%",
    maxWidth: "30rem",
    maxHeight: "85vh",
    overflow: "auto",
  },
  drawer: {
    position: "fixed" as const,
    top: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    maxWidth: "26rem",
    background: effects.surface.overlay.background,
    border: `1px solid ${colors.border.DEFAULT}`,
    boxShadow: effects.shadow["2xl"],
    zIndex: 400,
    overflow: "auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1.25rem 1.5rem",
    borderBottom: `1px solid ${colors.border.subtle}`,
  },
  headerTitle: {
    color: colors.text.primary,
    fontSize: "1.0625rem",
    fontWeight: "600",
    letterSpacing: "-0.005em",
    fontFamily: typography.fontFamily.display,
  },
  body: {
    padding: "1.5rem",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "0.625rem",
    padding: "1rem 1.5rem",
    borderTop: `1px solid ${colors.border.subtle}`,
  },
} as const;

export const skeletonLoader = {
  base: {
    background: `linear-gradient(90deg, ${effects.surface.base.background} 25%, ${effects.surface.raised.background} 50%, ${effects.surface.base.background} 75%)`,
    backgroundSize: "200% 100%",
    borderRadius: effects.borderRadius.sm,
    animation: "skeleton-shimmer 1.5s ease-in-out infinite",
  },
  text: {
    height: "0.875rem",
    width: "100%",
    borderRadius: effects.borderRadius.sm,
    marginBottom: "0.5rem",
  },
  heading: {
    height: "1.375rem",
    width: "60%",
    borderRadius: effects.borderRadius.sm,
    marginBottom: "0.75rem",
  },
  avatar: {
    width: "2.25rem",
    height: "2.25rem",
    borderRadius: effects.borderRadius.full,
  },
  card: {
    height: "8rem",
    borderRadius: effects.borderRadius.lg,
  },
  chart: {
    height: "12rem",
    borderRadius: effects.borderRadius.lg,
  },
  row: {
    height: "2.75rem",
    borderRadius: effects.borderRadius.sm,
    marginBottom: "0.375rem",
  },
} as const;

export const premiumFormElements = {
  inputGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.3125rem",
  },
  label: {
    color: colors.text.secondary,
    fontSize: "0.8125rem",
    fontWeight: "500",
    letterSpacing: "0.008em",
  },
  input: {
    background: colors.background.tertiary,
    border: `1px solid ${colors.border.DEFAULT}`,
    borderRadius: effects.borderRadius.md,
    padding: "0.5625rem 0.8125rem",
    color: colors.text.primary,
    fontSize: "0.875rem",
    lineHeight: "1.5",
    outline: "none",
    transition: `border-color ${motion.duration.fast} ${motion.easing.default}, box-shadow ${motion.duration.fast} ${motion.easing.default}`,
    width: "100%",
  },
  inputFocus: {
    borderColor: colors.border.focus,
    boxShadow: `0 0 0 3px ${colors.primary.muted}`,
  },
  inputError: {
    borderColor: colors.status.error,
    boxShadow: `0 0 0 3px ${colors.status.errorMuted}`,
  },
  select: {
    background: colors.background.tertiary,
    border: `1px solid ${colors.border.DEFAULT}`,
    borderRadius: effects.borderRadius.md,
    padding: "0.5625rem 2rem 0.5625rem 0.8125rem",
    color: colors.text.primary,
    fontSize: "0.875rem",
    appearance: "none" as const,
    cursor: "pointer",
    width: "100%",
  },
  textarea: {
    background: colors.background.tertiary,
    border: `1px solid ${colors.border.DEFAULT}`,
    borderRadius: effects.borderRadius.md,
    padding: "0.5625rem 0.8125rem",
    color: colors.text.primary,
    fontSize: "0.875rem",
    lineHeight: "1.6",
    resize: "vertical" as const,
    minHeight: "5rem",
    width: "100%",
  },
  checkbox: {
    wrapper: {
      display: "flex",
      alignItems: "center",
      gap: "0.5rem",
      cursor: "pointer",
    },
    box: {
      width: "1rem",
      height: "1rem",
      borderRadius: effects.borderRadius.xs,
      border: `1.5px solid ${colors.border.strong}`,
      transition: `all ${motion.duration.fast} ${motion.easing.default}`,
      flexShrink: 0,
    },
    boxChecked: {
      background: colors.primary.DEFAULT,
      borderColor: colors.primary.DEFAULT,
    },
  },
  helperText: {
    color: colors.text.muted,
    fontSize: "0.8125rem",
    marginTop: "0.3125rem",
    lineHeight: "1.5",
  },
  errorText: {
    color: colors.status.error,
    fontSize: "0.8125rem",
    marginTop: "0.3125rem",
    lineHeight: "1.5",
  },
  button: {
    primary: {
      background: colors.primary.DEFAULT,
      color: colors.text.primary,
      border: "none",
      borderRadius: effects.borderRadius.md,
      padding: "0.5625rem 1.125rem",
      fontSize: "0.875rem",
      fontWeight: "500",
      cursor: "pointer",
      transition: `opacity ${motion.duration.fast} ${motion.easing.default}`,
      lineHeight: "1.5",
    },
    secondary: {
      background: "transparent",
      color: colors.text.primary,
      border: `1px solid ${colors.border.strong}`,
      borderRadius: effects.borderRadius.md,
      padding: "0.5625rem 1.125rem",
      fontSize: "0.875rem",
      fontWeight: "450",
      cursor: "pointer",
      transition: `background ${motion.duration.fast} ${motion.easing.default}, border-color ${motion.duration.fast} ${motion.easing.default}`,
      lineHeight: "1.5",
    },
    ghost: {
      background: "transparent",
      color: colors.text.secondary,
      border: "none",
      borderRadius: effects.borderRadius.md,
      padding: "0.5625rem 0.875rem",
      fontSize: "0.875rem",
      fontWeight: "450",
      cursor: "pointer",
      transition: `background ${motion.duration.fast} ${motion.easing.default}, color ${motion.duration.fast} ${motion.easing.default}`,
      lineHeight: "1.5",
    },
    danger: {
      background: colors.status.error,
      color: colors.text.primary,
      border: "none",
      borderRadius: effects.borderRadius.md,
      padding: "0.5625rem 1.125rem",
      fontSize: "0.875rem",
      fontWeight: "500",
      cursor: "pointer",
      transition: `opacity ${motion.duration.fast} ${motion.easing.default}`,
      lineHeight: "1.5",
    },
    icon: {
      background: "transparent",
      color: colors.text.muted,
      border: `1px solid ${colors.border.DEFAULT}`,
      borderRadius: effects.borderRadius.md,
      padding: "0.4375rem",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      transition: `background ${motion.duration.fast} ${motion.easing.default}, color ${motion.duration.fast} ${motion.easing.default}, border-color ${motion.duration.fast} ${motion.easing.default}`,
      lineHeight: 1,
    },
  },
} as const;
