/**
 * Shared Sentra incident + alert store.
 *
 * Extracted from routes/sentra.ts so that geo-intel.ts and other modules can
 * read the live operational state (open incidents, active alerts) without
 * importing the Express router.
 */

export type IncidentSeverity = 'critical' | 'high' | 'medium' | 'low';
export type IncidentStatus = 'open' | 'triaging' | 'escalated' | 'contained' | 'resolved';

export interface TimelineEntry {
  id: string;
  type: 'detection' | 'system' | 'user' | 'escalation' | 'resolution';
  message: string;
  actor: string;
  timestamp: string;
}

export interface Incident {
  id: string;
  title: string;
  description: string;
  severity: IncidentSeverity;
  status: IncidentStatus;
  mitreStage: string;
  detectedAt: string;
  updatedAt: string;
  resolvedAt?: string;
  assignedTo?: string;
  affectedAssets: string[];
  tags: string[];
  timeline: TimelineEntry[];
}

export interface Alert {
  id: string;
  title: string;
  severity: IncidentSeverity;
  source: string;
  status: 'open' | 'acknowledged' | 'suppressed';
  description: string;
  asset?: string;
  detectedAt: string;
  linkedIncidentId?: string;
}

export const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString();
export const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const incidentsStore: Map<string, Incident> = new Map([
  [
    'INC-2026-0891',
    {
      id: 'INC-2026-0891',
      title: 'Ransomware-Adjacent OT Payload Detected',
      description:
        'Encrypted payload detected on 3 OT assets (SCADA, PLC). Anomalous C2 beaconing to known malicious IPs. Pattern consistent with LockBit-adjacent tooling.',
      severity: 'critical',
      status: 'triaging',
      mitreStage: 'Execution / C2',
      detectedAt: hoursAgo(4),
      updatedAt: minsAgo(12),
      assignedTo: 'SOC Lead',
      affectedAssets: ['asset-001', 'asset-003'],
      tags: ['ransomware', 'ot', 'c2'],
      timeline: [
        {
          id: 'tl-1',
          type: 'system',
          message: 'Isolation recommendation generated by Signal Mesh',
          actor: 'Signal Mesh',
          timestamp: minsAgo(12),
        },
        {
          id: 'tl-2',
          type: 'detection',
          message: 'Anomalous C2 beacon detected from PLC-003 to 45.227.252.12',
          actor: 'Network Sensor',
          timestamp: minsAgo(30),
        },
        {
          id: 'tl-3',
          type: 'detection',
          message: 'Ransomware payload signature matched on SCADA-01 (SHA-256: a3f1...c9e2)',
          actor: 'EDR Agent',
          timestamp: minsAgo(60),
        },
        {
          id: 'tl-4',
          type: 'system',
          message: 'Incident INC-2026-0891 initialized',
          actor: 'Sentra Engine',
          timestamp: hoursAgo(4),
        },
      ],
    },
  ],
  [
    'INC-2026-0874',
    {
      id: 'INC-2026-0874',
      title: 'Credential Spray on OT Admin Accounts',
      description:
        '14 failed login attempts on OT-Admin account from lateral IP. Pattern consistent with credential spraying targeting SCADA segment admin accounts.',
      severity: 'high',
      status: 'contained',
      mitreStage: 'Credential Access',
      detectedAt: hoursAgo(8),
      updatedAt: hoursAgo(2),
      assignedTo: 'IR Analyst',
      affectedAssets: ['asset-004'],
      tags: ['credential-spray', 'iam'],
      timeline: [
        {
          id: 'tl-c1',
          type: 'resolution',
          message: 'MFA re-enrollment forced on all OT-Admin accounts',
          actor: 'IR Analyst',
          timestamp: hoursAgo(2),
        },
        {
          id: 'tl-c2',
          type: 'user',
          message: 'Incident assigned and triaging started',
          actor: 'IR Analyst',
          timestamp: hoursAgo(6),
        },
        {
          id: 'tl-c3',
          type: 'detection',
          message: 'IAM detected 14 failed logins on OT-Admin in 30 minutes',
          actor: 'IAM Engine',
          timestamp: hoursAgo(8),
        },
      ],
    },
  ],
]);

export const alertsStore: Alert[] = [
  {
    id: 'ALT-2026-001',
    title: 'C2 Beacon Detected — 45.227.252.12',
    severity: 'critical',
    source: 'Network Sensor',
    status: 'open',
    description: 'Outbound beacon to known C2 infrastructure at 3-minute intervals from PLC-003.',
    asset: 'asset-003',
    detectedAt: minsAgo(4),
    linkedIncidentId: 'INC-2026-0891',
  },
  {
    id: 'ALT-2026-002',
    title: 'Malware Signature Match — LockBit Adjacent',
    severity: 'critical',
    source: 'EDR',
    status: 'open',
    description: 'Encrypted payload on SCADA Server matched LockBit-adjacent signature.',
    asset: 'asset-001',
    detectedAt: minsAgo(15),
    linkedIncidentId: 'INC-2026-0891',
  },
  {
    id: 'ALT-2026-003',
    title: 'MFA Bypass Attempt on Domain Controller',
    severity: 'high',
    source: 'IAM',
    status: 'acknowledged',
    description: 'Unusual authentication pattern detected — potential MFA bypass via legacy protocol.',
    asset: 'asset-004',
    detectedAt: minsAgo(43),
  },
  {
    id: 'ALT-2026-004',
    title: 'Backup Integrity Check Failed — SCADA-01',
    severity: 'high',
    source: 'Backup Engine',
    status: 'open',
    description: 'Scheduled backup integrity verification failed. Last verified backup: 72h ago.',
    asset: 'asset-001',
    detectedAt: hoursAgo(2),
  },
  {
    id: 'ALT-2026-005',
    title: 'Control Drift: Incident Response Plan',
    severity: 'medium',
    source: 'NIST CSF Scanner',
    status: 'open',
    description:
      'Respond family control RC.RP-1 failed automated playbook execution on legacy SCADA systems.',
    detectedAt: hoursAgo(6),
  },
  {
    id: 'ALT-2026-006',
    title: 'HMI Workstation — Patching Overdue',
    severity: 'medium',
    source: 'Patch Manager',
    status: 'suppressed',
    description: 'HMI workstation has pending security patches older than 30 days.',
    asset: 'asset-002',
    detectedAt: hoursAgo(24),
  },
];
