export type ToolRiskLevel = 'safe' | 'low' | 'medium' | 'high' | 'critical';

export interface ToolMetadata {
  id: string;
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  riskLevel: ToolRiskLevel;
  requiresApproval: boolean;
  allowedVerticals: string[];
  allowedRoles: string[];
  blockedActions: string[];
  rateLimit: number;
  timeoutMs: number;
  auditRequired: boolean;
  safeForAutonomy: boolean;
  demoSupported: boolean;
  isDestructive: boolean;
  category: string;
}

export type ToolResult = {
  ok: true;
  toolId: string;
  output: Record<string, unknown>;
  durationMs: number;
  isDemo: boolean;
} | {
  ok: false;
  toolId: string;
  error: string;
  durationMs: number;
};

type MockFn = (input: Record<string, unknown>, isDemoMode: boolean) => Record<string, unknown>;

const TOOL_CATALOGUE: ToolMetadata[] = [
  {
    id: 'createRevOpsUpdate',
    name: 'Create RevOps Update',
    description: 'Creates a RevOps status update with pipeline changes, deal risk flags, and recommended actions.',
    inputSchema: { opportunityId: 'string', updateType: 'string', summary: 'string' },
    outputSchema: { updateId: 'string', status: 'string', notified: 'boolean' },
    riskLevel: 'medium', requiresApproval: true, allowedVerticals: ['lyte-revenue', 'alloy-core'],
    allowedRoles: ['operator', 'executive', 'board'], blockedActions: ['delete_opportunity'],
    rateLimit: 20, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'revenue',
  },
  {
    id: 'draftTeamsMessage',
    name: 'Draft Teams Message',
    description: 'Drafts a Microsoft Teams message for stakeholder communication. Does not send without approval.',
    inputSchema: { channel: 'string', message: 'string', recipients: 'string[]' },
    outputSchema: { draftId: 'string', previewUrl: 'string', requiresSend: 'boolean' },
    riskLevel: 'low', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board', 'analyst'], blockedActions: [],
    rateLimit: 50, timeoutMs: 3000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'communication',
  },
  {
    id: 'generateExecutiveSummary',
    name: 'Generate Executive Summary',
    description: 'Synthesizes signals and outcomes into a structured executive briefing document.',
    inputSchema: { signalIds: 'string[]', outcomeIds: 'string[]', period: 'string' },
    outputSchema: { summaryId: 'string', content: 'string', wordCount: 'number' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board', 'analyst'], blockedActions: [],
    rateLimit: 100, timeoutMs: 10000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'reporting',
  },
  {
    id: 'createJiraTicket',
    name: 'Create Jira Ticket',
    description: 'Creates a Jira ticket for tracked remediation action items.',
    inputSchema: { project: 'string', summary: 'string', priority: 'string', assignee: 'string' },
    outputSchema: { ticketId: 'string', url: 'string', status: 'string' },
    riskLevel: 'low', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive'], blockedActions: [],
    rateLimit: 30, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'workflow',
  },
  {
    id: 'updateOpportunityStatus',
    name: 'Update Opportunity Status',
    description: 'Updates CRM opportunity status and next steps based on signal intelligence.',
    inputSchema: { opportunityId: 'string', newStatus: 'string', reason: 'string' },
    outputSchema: { success: 'boolean', previousStatus: 'string', newStatus: 'string' },
    riskLevel: 'high', requiresApproval: true, allowedVerticals: ['lyte-revenue'],
    allowedRoles: ['executive', 'board'], blockedActions: ['delete'],
    rateLimit: 10, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'revenue',
  },
  {
    id: 'flagDuplicateScopeStackEntry',
    name: 'Flag Duplicate ScopeStack Entry',
    description: 'Flags and routes duplicate entries in the ScopeStack contract pipeline for human review.',
    inputSchema: { entryId: 'string', duplicateOf: 'string', reason: 'string' },
    outputSchema: { flagId: 'string', routed: 'boolean', reviewAssignee: 'string' },
    riskLevel: 'medium', requiresApproval: false, allowedVerticals: ['prism-counsel', 'alloy-core'],
    allowedRoles: ['operator', 'analyst'], blockedActions: [],
    rateLimit: 30, timeoutMs: 3000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'legal',
  },
  {
    id: 'createMatterDeadlineAlert',
    name: 'Create Matter Deadline Alert',
    description: 'Creates a deadline alert for a legal matter, routing to counsel and operations.',
    inputSchema: { matterId: 'string', deadlineDate: 'string', urgency: 'string' },
    outputSchema: { alertId: 'string', notified: 'string[]', escalatedTo: 'string' },
    riskLevel: 'medium', requiresApproval: true, allowedVerticals: ['prism-counsel'],
    allowedRoles: ['operator', 'executive'], blockedActions: [],
    rateLimit: 20, timeoutMs: 3000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'legal',
  },
  {
    id: 'createVoyageRiskAlert',
    name: 'Create Voyage Risk Alert',
    description: 'Issues a voyage risk alert for maritime fleet operations and port authority notification.',
    inputSchema: { vesselId: 'string', riskType: 'string', coordinates: 'string', severity: 'string' },
    outputSchema: { alertId: 'string', notified: 'string[]', codiAdvisoryId: 'string' },
    riskLevel: 'high', requiresApproval: true, allowedVerticals: ['vessels-maritime'],
    allowedRoles: ['operator', 'executive'], blockedActions: [],
    rateLimit: 15, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'maritime',
  },
  {
    id: 'createVendorEscalation',
    name: 'Create Vendor Escalation',
    description: 'Creates a formal vendor escalation record with SLA tracking and escalation path.',
    inputSchema: { vendorId: 'string', issue: 'string', priority: 'string', slaDeadline: 'string' },
    outputSchema: { escalationId: 'string', slaTracked: 'boolean', assignedTo: 'string' },
    riskLevel: 'medium', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive'], blockedActions: [],
    rateLimit: 20, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'operations',
  },
  {
    id: 'createSecurityIncidentNote',
    name: 'Create Security Incident Note',
    description: 'Creates a formal security incident note for cyber operations response tracking.',
    inputSchema: { incidentId: 'string', severity: 'string', summary: 'string', affectedSystems: 'string[]' },
    outputSchema: { noteId: 'string', incidentStatus: 'string', escalated: 'boolean' },
    riskLevel: 'critical', requiresApproval: true, allowedVerticals: ['aegis-defense', 'alloy-core'],
    allowedRoles: ['executive', 'board'], blockedActions: [],
    rateLimit: 5, timeoutMs: 10000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'security',
  },
  {
    id: 'generateBoardPacket',
    name: 'Generate Board Packet',
    description: 'Generates a structured board-ready briefing packet from current signals, outcomes, and proof.',
    inputSchema: { period: 'string', verticals: 'string[]', includeProof: 'boolean' },
    outputSchema: { packetId: 'string', pdfUrl: 'string', sections: 'string[]', pageCount: 'number' },
    riskLevel: 'low', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['executive', 'board'], blockedActions: [],
    rateLimit: 5, timeoutMs: 30000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'reporting',
  },
  {
    id: 'generateProofPacket',
    name: 'Generate Proof Packet',
    description: 'Generates a cryptographically-linked proof packet for an executed action.',
    inputSchema: { actionId: 'string', traceId: 'string', approvalRecordId: 'string' },
    outputSchema: { packetId: 'string', hash: 'string', verified: 'boolean' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board', 'analyst'], blockedActions: [],
    rateLimit: 50, timeoutMs: 5000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'proof',
  },
  {
    id: 'runOutcomeDriftCheck',
    name: 'Run Outcome Drift Check',
    description: 'Evaluates deviation between predicted and actual outcome trajectories.',
    inputSchema: { outcomeId: 'string', lookbackDays: 'number' },
    outputSchema: { driftScore: 'number', trend: 'string', alerts: 'string[]' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive'], blockedActions: [],
    rateLimit: 100, timeoutMs: 5000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'analytics',
  },
  {
    id: 'runRevenueFrictionCheck',
    name: 'Run Revenue Friction Check',
    description: 'Analyzes pipeline friction points impeding revenue recognition.',
    inputSchema: { vertical: 'string', period: 'string', accountIds: 'string[]' },
    outputSchema: { frictionScore: 'number', blockers: 'string[]', recommendations: 'string[]' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['lyte-revenue', 'alloy-core'],
    allowedRoles: ['operator', 'analyst', 'executive'], blockedActions: [],
    rateLimit: 50, timeoutMs: 10000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'revenue',
  },
  {
    id: 'runDecisionLatencyCheck',
    name: 'Run Decision Latency Check',
    description: 'Measures elapsed time between signal detection and approval/execution decisions.',
    inputSchema: { signalId: 'string', actionId: 'string' },
    outputSchema: { latencyMs: 'number', phase: 'string', benchmark: 'string', status: 'string' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 200, timeoutMs: 2000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'analytics',
  },
  {
    id: 'runMirrorEval',
    name: 'Run MirrorEval',
    description: 'Runs the MirrorEval evaluation layer against an action brief or PCE contract.',
    inputSchema: { targetId: 'string', targetType: 'string', evidenceRefs: 'string[]', sourceCoverage: 'number' },
    outputSchema: { evalId: 'string', disposition: 'string', overallScore: 'number', flags: 'string[]' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 100, timeoutMs: 5000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'evaluation',
  },
  {
    id: 'reconstructProofTrail',
    name: 'Reconstruct Proof Trail',
    description: 'Reconstructs the full causal proof trail from signal ingestion to action execution.',
    inputSchema: { actionId: 'string', depth: 'number' },
    outputSchema: { trailId: 'string', nodes: 'object[]', edges: 'object[]', verified: 'boolean' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 50, timeoutMs: 10000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'proof',
  },
  {
    id: 'runAgentTrustScore',
    name: 'Run Agent Trust Score',
    description: 'Computes the trust score for an operator based on execution history, accuracy, and policy compliance.',
    inputSchema: { operatorId: 'string', lookbackDays: 'number' },
    outputSchema: { trustScore: 'number', trend: 'string', factors: 'object' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board'], blockedActions: [],
    rateLimit: 50, timeoutMs: 5000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'analytics',
  },
  {
    id: 'runConnectorHealthCheck',
    name: 'Run Connector Health Check',
    description: 'Validates the health and connectivity of registered external connectors.',
    inputSchema: { connectorId: 'string' },
    outputSchema: { connectorId: 'string', status: 'string', latencyMs: 'number', lastCheckedAt: 'string' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst'], blockedActions: [],
    rateLimit: 100, timeoutMs: 5000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'operations',
  },
  {
    id: 'createPCEContract',
    name: 'Create PCE Contract',
    description: 'Creates a Proof-Carrying Execution contract binding an action to its evidence chain.',
    inputSchema: { actionId: 'string', signalIds: 'string[]', mirrorEvalId: 'string', approvalRecordId: 'string' },
    outputSchema: { contractId: 'string', isValid: 'boolean', blockedReason: 'string | null' },
    riskLevel: 'medium', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board'], blockedActions: [],
    rateLimit: 30, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'governance',
  },
  {
    id: 'validatePCEContract',
    name: 'Validate PCE Contract',
    description: 'Validates an existing PCE contract\'s evidence chain and policy compliance.',
    inputSchema: { contractId: 'string' },
    outputSchema: { valid: 'boolean', violations: 'string[]', coverageScore: 'number' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 50, timeoutMs: 3000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'governance',
  },
  {
    id: 'runBusinessTwinDriftCheck',
    name: 'Run Business Twin Drift Check',
    description: 'Measures drift between the Business Twin model state and live signal data.',
    inputSchema: { twinId: 'string', vertical: 'string' },
    outputSchema: { driftScore: 'number', driftFields: 'string[]', recommendation: 'string' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive'], blockedActions: [],
    rateLimit: 50, timeoutMs: 5000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'analytics',
  },
  {
    id: 'generateBoardroomModeSummary',
    name: 'Generate Boardroom Mode Summary',
    description: 'Generates a condensed, executive-ready boardroom summary from the current fabric state.',
    inputSchema: { period: 'string', highlightCount: 'number' },
    outputSchema: { summaryId: 'string', content: 'string', keyMetrics: 'object' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['executive', 'board'], blockedActions: [],
    rateLimit: 20, timeoutMs: 10000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'reporting',
  },
  {
    id: 'queryOntology',
    name: 'Query Ontology',
    description: 'Queries the A11oy enterprise ontology for entity relationships, concept definitions, and knowledge graph traversal. Read-only, safe for autonomy.',
    inputSchema: { entity: 'string', depth: 'number', relationTypes: 'string[]' },
    outputSchema: { entityId: 'string', label: 'string', relations: 'object[]', conceptPath: 'string[]', confidence: 'number' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 200, timeoutMs: 3000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'knowledge',
  },
  {
    id: 'createTerraDeal',
    name: 'Create Terra Deal',
    description: 'Creates a new real estate deal record in Terra including property details, financing structure, and covenant tracking. Requires executive approval.',
    inputSchema: { dealName: 'string', propertyAddress: 'string', dealType: 'string', dealValueUsd: 'number', lenderId: 'string', covenantTerms: 'string' },
    outputSchema: { dealId: 'string', status: 'string', covenantWatchActive: 'boolean', lenderNotified: 'boolean' },
    riskLevel: 'high', requiresApproval: true, allowedVerticals: ['terra-real-estate'],
    allowedRoles: ['executive', 'board'], blockedActions: ['delete_deal'],
    rateLimit: 10, timeoutMs: 8000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'real-estate',
  },
  {
    id: 'createVesselsAlertRule',
    name: 'Create Vessels Alert Rule',
    description: 'Creates a persistent alert rule in the Vessels maritime intelligence system for vessel tracking, port authority notifications, and voyage risk triggers.',
    inputSchema: { ruleName: 'string', vesselIds: 'string[]', triggerCondition: 'string', severity: 'string', notifyChannels: 'string[]' },
    outputSchema: { ruleId: 'string', active: 'boolean', monitoredVessels: 'number', estimatedTriggerRatePerDay: 'number' },
    riskLevel: 'medium', requiresApproval: true, allowedVerticals: ['vessels-maritime'],
    allowedRoles: ['operator', 'executive'], blockedActions: [],
    rateLimit: 20, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'maritime',
  },
  {
    id: 'openCounselMatter',
    name: 'Open Counsel Matter',
    description: 'Opens a new legal matter in the Counsel system, assigns counsel, sets deadlines, and creates the ScopeStack contract entry. Requires operator approval.',
    inputSchema: { matterTitle: 'string', matterType: 'string', clientEntity: 'string', priority: 'string', assignedCounsel: 'string', deadlineDate: 'string' },
    outputSchema: { matterId: 'string', status: 'string', scopeStackEntryId: 'string', deadlineAlertCreated: 'boolean', counselNotified: 'boolean' },
    riskLevel: 'medium', requiresApproval: true, allowedVerticals: ['prism-counsel'],
    allowedRoles: ['operator', 'executive'], blockedActions: [],
    rateLimit: 20, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'legal',
  },
  {
    id: 'draftPulseBriefing',
    name: 'Draft Pulse Briefing',
    description: 'Drafts a structured AI executive briefing in Pulse. The briefing is staged for review and does not publish without explicit approval.',
    inputSchema: { title: 'string', audience: 'string', signalIds: 'string[]', period: 'string', tone: 'string' },
    outputSchema: { briefingId: 'string', previewUrl: 'string', wordCount: 'number', staged: 'boolean', requiresPublishApproval: 'boolean' },
    riskLevel: 'low', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'analyst', 'executive'], blockedActions: [],
    rateLimit: 30, timeoutMs: 10000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'reporting',
  },
  {
    id: 'terraDistressScan',
    name: 'Terra Distress Scan',
    description: 'Runs a live distress scan across a specified property or portfolio segment, returning distress score, cascade risk, and top contributing signals. Optionally triggers an ingestion refresh from connected data adapters.',
    inputSchema: { propertyId: 'string', portfolio: 'string', refreshAdapters: 'boolean', scenario: 'string' },
    outputSchema: { scanId: 'string', distressScore: 'number', cascadeRisk: 'number', topSignals: 'object[]', dataMode: 'string' },
    riskLevel: 'low', requiresApproval: false, allowedVerticals: ['terra-real-estate', '*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 60, timeoutMs: 15000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'intelligence',
  },
  {
    id: 'terraScenarioRerun',
    name: 'Terra Scenario Re-run',
    description: 'Reruns a named Terra scenario (e.g. "sunbelt-multifamily-2026") through the forecast engine and Monte Carlo pipeline, returning updated distress propagation, climate cap-rate, and owner-intent forecasts.',
    inputSchema: { scenarioId: 'string', overrides: 'object', includeMonteCarloIntervals: 'boolean' },
    outputSchema: { runId: 'string', scenarioId: 'string', heads: 'object[]', generatedAt: 'string', monteCarloScenarios: 'string[]' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['terra-real-estate', '*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 30, timeoutMs: 20000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'intelligence',
  },
  {
    id: 'terraWatchlistEdit',
    name: 'Terra Watchlist Edit',
    description: 'Adds or removes properties from the Terra watchlist. Can accept A11oy-originated signals as the trigger for watchlist inclusion. Emits a prism-bus domain_signal on change.',
    inputSchema: { action: 'string', propertyIds: 'string[]', reason: 'string', signalId: 'string' },
    outputSchema: { watchlistId: 'string', added: 'string[]', removed: 'string[]', currentSize: 'number', signalEmitted: 'boolean' },
    riskLevel: 'low', requiresApproval: true, allowedVerticals: ['terra-real-estate', '*'],
    allowedRoles: ['operator', 'analyst', 'executive'], blockedActions: [],
    rateLimit: 40, timeoutMs: 5000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'portfolio',
  },
  {
    id: 'terraOpenWatchlist',
    name: 'Terra Open Watchlist',
    description: 'Opens the Terra watchlist view for the current portfolio segment, optionally filtered by distress severity or asset class. Responds to inbound A11oy "open watchlist" actions.',
    inputSchema: { filter: 'string', severity: 'string', assetClass: 'string' },
    outputSchema: { deepLink: 'string', itemCount: 'number', previewItems: 'object[]' },
    riskLevel: 'safe', requiresApproval: false, allowedVerticals: ['terra-real-estate', '*'],
    allowedRoles: ['operator', 'analyst', 'executive', 'board'], blockedActions: [],
    rateLimit: 100, timeoutMs: 3000, auditRequired: false, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'navigation',
  },
  // ── Sentra tools ────────────────────────────────────────────────────────────
  {
    id: 'sentraAssetRiskScore',
    name: 'Score Asset Compromise Risk',
    description: 'Runs the Sentra asset-risk ML head to produce a calibrated 30-day compromise probability (P30d) for a given asset using live NVD CVSS, FIRST EPSS, CISA KEV, criticality, and internet-exposure inputs.',
    inputSchema: {
      assetId: 'string',
      cvssScore: 'number (0-10, optional)',
      epssScore: 'number (0-1, optional)',
      isKevListed: 'boolean (optional)',
      assetCriticality: 'enum: critical | high | medium | low',
      internetExposure: 'boolean',
      patchAge: 'integer days (optional)',
    },
    outputSchema: {
      assetId: 'string',
      p30dCompromise: 'number',
      riskLabel: 'enum: critical | high | medium | low',
      factors: 'object',
      modelVersion: 'string',
      modelVersionId: 'string',
      confidenceInterval: 'object',
    },
    riskLevel: 'low', requiresApproval: false,
    allowedVerticals: ['sentra', 'alloy-core'],
    allowedRoles: ['operator', 'executive', 'board', 'analyst', 'ops', 'super_admin', 'admin'],
    blockedActions: [],
    rateLimit: 60, timeoutMs: 8000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'security-intelligence',
  },
  {
    id: 'sentraIdentityBlastRadius',
    name: 'Forecast Identity Blast Radius',
    description: 'Runs the Sentra identity blast-radius ML head to forecast 7-day lateral movement probability and estimated blast radius for an identity (human, service-account, or machine) using privilege graph and posture features.',
    inputSchema: {
      identityId: 'string',
      identityType: 'enum: human | service-account | machine',
      currentPrivileges: 'string[]',
      accessibleSystems: 'integer',
      hasAdminRights: 'boolean',
      recentAnomalies: 'integer (optional)',
      lateralMoveRisk: 'enum: high | medium | low (optional)',
    },
    outputSchema: {
      identityId: 'string',
      p7dLateralPath: 'number',
      estimatedBlastRadius: 'integer',
      highRiskTargets: 'string[]',
      nextLikelyPivots: 'object[]',
      modelVersion: 'string',
      modelVersionId: 'string',
    },
    riskLevel: 'low', requiresApproval: false,
    allowedVerticals: ['sentra', 'alloy-core'],
    allowedRoles: ['operator', 'executive', 'board', 'analyst', 'ops', 'super_admin', 'admin'],
    blockedActions: [],
    rateLimit: 60, timeoutMs: 8000, auditRequired: true, safeForAutonomy: true,
    demoSupported: true, isDestructive: false, category: 'security-intelligence',
  },
  {
    id: 'sentraAdversaryReplay',
    name: 'Run Adversary Replay Simulation',
    description: 'Runs the Sentra adversary-replay ML head using CVE/EPSS/KEV + own attack surface to generate a MITRE ATT&CK-aligned attack chain, overall success probability, mean time to breakout, and recommended mitigations. Not generic playbooks — tailored to the specific CVE set provided.',
    inputSchema: {
      scenarioId: 'string (optional)',
      cveIds: 'string[] (max 50, optional)',
      epssScores: 'Record<cveId, number> (optional)',
      kevListedCves: 'string[] (optional)',
      targetSurface: 'object: { webApps, dbServers, endpoints, cloudAccounts } (optional)',
      adversaryProfile: 'string (optional)',
    },
    outputSchema: {
      scenarioId: 'string',
      attackChain: 'object[]',
      overallSuccessRate: 'number',
      meanTimeToBreakout: 'integer hours',
      confidenceInterval: 'object',
      recommendedMitigations: 'string[]',
      modelVersion: 'string',
      modelVersionId: 'string',
    },
    riskLevel: 'medium', requiresApproval: false,
    allowedVerticals: ['sentra', 'alloy-core'],
    allowedRoles: ['operator', 'executive', 'board', 'analyst', 'ops', 'super_admin', 'admin'],
    blockedActions: [],
    rateLimit: 30, timeoutMs: 15000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'security-intelligence',
  },
  {
    id: 'submitHfJob',
    name: 'Submit HF Job',
    description: 'Submits a Hugging Face Jobs compute job (UV or Docker) with specified hardware flavor, image, command, env vars, secrets, volumes, and timeout. The job runs on HF-managed GPU/CPU infrastructure under Guardian policy. Returns a job handle for status tracking.',
    inputSchema: {
      type: 'enum: uv | docker',
      image: 'string (required for docker)',
      command: 'string[]',
      flavor: 'string (e.g. cpu-basic, t4-small, a10g-small, a100-large)',
      env: 'Record<string, string>',
      secrets: 'Record<string, string>',
      volumes: 'Array<{ type, source, mount, readOnly }>',
      timeout: 'number | string (e.g. 3600, "30m", "1.5h", "1d")',
      namespace: 'string',
      labels: 'Record<string, string>',
    },
    outputSchema: {
      jobId: 'string',
      status: 'string',
      flavor: 'string',
      costPerMinute: 'number',
      namespace: 'string',
    },
    riskLevel: 'high', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board'], blockedActions: [],
    rateLimit: 10, timeoutMs: 30000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'compute',
  },
  {
    id: 'submitHfScheduledJob',
    name: 'Submit HF Scheduled Job',
    description: 'Creates a recurring Hugging Face Jobs schedule (cron expression) for automated compute tasks like nightly retraining, hourly batch inference, or periodic dataset processing. Runs under Guardian policy with full audit trail.',
    inputSchema: {
      type: 'enum: uv | docker',
      cron: 'string (cron expression or @daily/@hourly)',
      image: 'string',
      command: 'string[]',
      flavor: 'string',
      env: 'Record<string, string>',
      secrets: 'Record<string, string>',
      volumes: 'Array<{ type, source, mount, readOnly }>',
      timeout: 'number | string',
      namespace: 'string',
      labels: 'Record<string, string>',
    },
    outputSchema: {
      scheduleId: 'string',
      status: 'string',
      cron: 'string',
      flavor: 'string',
      namespace: 'string',
    },
    riskLevel: 'high', requiresApproval: true, allowedVerticals: ['*'],
    allowedRoles: ['operator', 'executive', 'board'], blockedActions: [],
    rateLimit: 5, timeoutMs: 15000, auditRequired: true, safeForAutonomy: false,
    demoSupported: true, isDestructive: false, category: 'compute',
  },
];

const MOCK_OUTPUTS: Record<string, MockFn> = {
  createRevOpsUpdate: (input, demo) => ({
    updateId: `rou-${Date.now()}`, status: 'created', notified: true,
    message: `RevOps update created for opportunity ${(input as { opportunityId?: string }).opportunityId ?? 'unknown'}`,
    demo,
  }),
  draftTeamsMessage: (input, demo) => ({
    draftId: `draft-${Date.now()}`, previewUrl: 'https://teams.microsoft.com/preview/demo',
    requiresSend: true,
    preview: `[DEMO] ${(input as { message?: string }).message?.slice(0, 100) ?? '...'}`,
    demo,
  }),
  generateExecutiveSummary: (input, demo) => ({
    summaryId: `sum-${Date.now()}`,
    content: `Executive Summary (${demo ? 'Demo' : 'Live'}): Analyzed ${((input as { signalIds?: unknown[] }).signalIds ?? []).length} signals and ${((input as { outcomeIds?: unknown[] }).outcomeIds ?? []).length} outcomes for period ${(input as { period?: string }).period ?? 'current'}. Overall business posture: elevated risk with identified remediation paths.`,
    wordCount: 47, demo,
  }),
  createJiraTicket: (_input, demo) => ({
    ticketId: `DEMO-${Math.floor(Math.random() * 9000) + 1000}`,
    url: 'https://jira.demo.a11oy.io/browse/DEMO-1234', status: 'open', demo,
  }),
  updateOpportunityStatus: (input, demo) => ({
    success: true, previousStatus: 'at_risk', newStatus: (input as { newStatus?: string }).newStatus ?? 'closed_won', demo,
  }),
  flagDuplicateScopeStackEntry: (input, demo) => ({
    flagId: `flag-${Date.now()}`, routed: true, reviewAssignee: 'counsel-team@demo.a11oy.io',
    entryId: (input as { entryId?: string }).entryId, demo,
  }),
  createMatterDeadlineAlert: (input, demo) => ({
    alertId: `alert-${Date.now()}`, notified: ['counsel@demo.a11oy.io'],
    escalatedTo: 'senior-counsel@demo.a11oy.io',
    deadline: (input as { deadlineDate?: string }).deadlineDate, demo,
  }),
  createVoyageRiskAlert: (input, demo) => ({
    alertId: `vra-${Date.now()}`, notified: ['ops@demo.vessels.io'],
    codiAdvisoryId: `codi-${Date.now()}`, vessel: (input as { vesselId?: string }).vesselId, demo,
  }),
  createVendorEscalation: (input, demo) => ({
    escalationId: `esc-${Date.now()}`, slaTracked: true,
    assignedTo: 'vendor-ops@demo.a11oy.io', vendor: (input as { vendorId?: string }).vendorId, demo,
  }),
  createSecurityIncidentNote: (input, demo) => ({
    noteId: `sec-${Date.now()}`, incidentStatus: 'open',
    escalated: (input as { severity?: string }).severity === 'critical', demo,
  }),
  generateBoardPacket: (_input, demo) => ({
    packetId: `bp-${Date.now()}`, pdfUrl: 'https://boardroom.demo.a11oy.io/packet/demo.pdf',
    sections: ['Executive Summary', 'Signal Analysis', 'Risk Assessment', 'Actions', 'Proof Ledger'],
    pageCount: 12, demo,
  }),
  generateProofPacket: (input, demo) => ({
    packetId: `pp-${Date.now()}`,
    hash: `sha256:${Buffer.from(JSON.stringify(input)).toString('base64').slice(0, 32)}`,
    verified: true, demo,
  }),
  runOutcomeDriftCheck: (_input, demo) => ({
    driftScore: 0.23, trend: 'improving', alerts: [], demo,
  }),
  runRevenueFrictionCheck: (_input, demo) => ({
    frictionScore: 0.41,
    blockers: ['Delayed contract signing', 'Pending legal review'],
    recommendations: ['Accelerate legal review cycle', 'Assign dedicated CSM to at-risk accounts'], demo,
  }),
  runDecisionLatencyCheck: (_input, demo) => ({
    latencyMs: 4320000, phase: 'approval_wait', benchmark: '2h',
    status: 'exceeded', demo,
  }),
  runMirrorEval: (_input, demo) => ({
    evalId: `eval-${Date.now()}`, disposition: 'pass', overallScore: 0.82,
    flags: [], demo,
  }),
  reconstructProofTrail: (_input, demo) => ({
    trailId: `trail-${Date.now()}`,
    nodes: [{ id: 'signal', type: 'signal' }, { id: 'analysis', type: 'operator' }, { id: 'action', type: 'action' }],
    edges: [{ from: 'signal', to: 'analysis' }, { from: 'analysis', to: 'action' }],
    verified: true, demo,
  }),
  runAgentTrustScore: (_input, demo) => ({
    trustScore: 0.91, trend: 'stable',
    factors: { accuracy: 0.94, policyCompliance: 0.89, approvalAccuracy: 0.92 }, demo,
  }),
  runConnectorHealthCheck: (input, demo) => ({
    connectorId: (input as { connectorId?: string }).connectorId ?? 'unknown',
    status: 'healthy', latencyMs: 42, lastCheckedAt: new Date().toISOString(), demo,
  }),
  createPCEContract: (input, demo) => ({
    contractId: `pce-${Date.now()}`, isValid: true, blockedReason: null,
    actionId: (input as { actionId?: string }).actionId, demo,
  }),
  validatePCEContract: (input, demo) => ({
    valid: true, violations: [], coverageScore: 0.88,
    contractId: (input as { contractId?: string }).contractId, demo,
  }),
  runBusinessTwinDriftCheck: (_input, demo) => ({
    driftScore: 0.12, driftFields: [],
    recommendation: 'Business Twin is aligned with live signals. No action required.', demo,
  }),
  generateBoardroomModeSummary: (_input, demo) => ({
    summaryId: `brs-${Date.now()}`,
    content: 'Boardroom Summary (Demo): 3 critical signals active across 2 verticals. 1 action pending executive approval. Proof coverage: 92%.',
    keyMetrics: { criticalSignals: 3, pendingActions: 1, proofCoverage: 0.92, fabricHealth: 'degraded' }, demo,
  }),
  queryOntology: (input, demo) => ({
    entityId: `ont-${(input as { entity?: string }).entity ?? 'unknown'}-${Date.now()}`,
    label: (input as { entity?: string }).entity ?? 'Unknown Entity',
    relations: [
      { type: 'owns', target: 'SZL Holdings', confidence: 0.97 },
      { type: 'regulates', target: 'Maritime Authority', confidence: 0.83 },
      { type: 'contracts_with', target: 'Lender HSBC', confidence: 0.91 },
    ],
    conceptPath: ['Enterprise', 'Portfolio', (input as { entity?: string }).entity ?? 'Unknown'],
    confidence: 0.89, demo,
  }),
  createTerraDeal: (input, demo) => ({
    dealId: `terra-deal-${Date.now()}`,
    status: 'pending_review',
    covenantWatchActive: true,
    lenderNotified: false,
    dealName: (input as { dealName?: string }).dealName,
    message: `Deal "${(input as { dealName?: string }).dealName ?? 'unnamed'}" created in Terra. Covenant watch activated. Lender notification pending approval.`,
    demo,
  }),
  createVesselsAlertRule: (input, demo) => ({
    ruleId: `vr-${Date.now()}`,
    active: true,
    monitoredVessels: ((input as { vesselIds?: string[] }).vesselIds ?? []).length,
    estimatedTriggerRatePerDay: 2.4,
    ruleName: (input as { ruleName?: string }).ruleName,
    demo,
  }),
  openCounselMatter: (input, demo) => ({
    matterId: `matter-${Date.now()}`,
    status: 'open',
    scopeStackEntryId: `ss-${Date.now()}`,
    deadlineAlertCreated: true,
    counselNotified: true,
    matterTitle: (input as { matterTitle?: string }).matterTitle,
    assignedCounsel: (input as { assignedCounsel?: string }).assignedCounsel,
    demo,
  }),
  draftPulseBriefing: (input, demo) => ({
    briefingId: `briefing-${Date.now()}`,
    previewUrl: `https://pulse.demo.a11oy.io/briefings/preview/${Date.now()}`,
    wordCount: 487,
    staged: true,
    requiresPublishApproval: true,
    title: (input as { title?: string }).title,
    demo,
  }),
  terraDistressScan: (input, demo) => ({
    scanId: `scan-${Date.now()}`,
    distressScore: 0.74,
    cascadeRisk: 0.61,
    topSignals: [
      { signal: 'dscr_below_1', value: 0.91, severity: 'critical' },
      { signal: 'loan_maturity_4mo', value: 4, severity: 'high' },
      { signal: 'occupancy_drop', value: 0.72, severity: 'high' },
    ],
    dataMode: demo ? 'demo' : 'live',
    scenario: (input as { scenario?: string }).scenario ?? 'sunbelt-multifamily-2026',
    propertyId: (input as { propertyId?: string }).propertyId ?? 'portfolio',
    generatedAt: new Date().toISOString(),
    deepLink: '/terra/distress-forecast?scenario=sunbelt-multifamily-2026',
    demo,
  }),
  terraScenarioRerun: (input, demo) => ({
    runId: `run-${Date.now()}`,
    scenarioId: (input as { scenarioId?: string }).scenarioId ?? 'sunbelt-multifamily-2026',
    heads: [
      { headName: 'terra:distress_propagation', point: 0.67, lower: 0.49, upper: 0.82, confidence: 0.70 },
      { headName: 'terra:climate_adjusted_cap_rate', point: 0.0641, lower: 0.0602, upper: 0.0682, confidence: 0.73 },
      { headName: 'terra:owner_intent', point: 0.74, lower: 0.55, upper: 0.88, confidence: 0.72 },
    ],
    generatedAt: new Date().toISOString(),
    monteCarloScenarios: ['terra/distress-propagation', 'terra/climate-adjusted-cap-rate'],
    demo,
  }),
  terraWatchlistEdit: (input, demo) => ({
    watchlistId: `wl-${Date.now()}`,
    added: (input as { action?: string }).action === 'add' ? ((input as { propertyIds?: string[] }).propertyIds ?? []) : [],
    removed: (input as { action?: string }).action === 'remove' ? ((input as { propertyIds?: string[] }).propertyIds ?? []) : [],
    currentSize: 7,
    signalEmitted: true,
    reason: (input as { reason?: string }).reason,
    demo,
  }),
  terraOpenWatchlist: (input, demo) => ({
    deepLink: `/terra/distress-engine?filter=${encodeURIComponent((input as { filter?: string }).filter ?? 'all')}&severity=${encodeURIComponent((input as { severity?: string }).severity ?? 'all')}`,
    itemCount: 7,
    previewItems: [
      { propertyId: 'prop-sunbelt-01', distressScore: 0.74, severity: 'critical' },
      { propertyId: 'prop-sunbelt-02', distressScore: 0.61, severity: 'high' },
      { propertyId: 'prop-sunbelt-03', distressScore: 0.48, severity: 'medium' },
    ],
    demo,
  }),
  sentraAssetRiskScore: (input, demo) => ({
    assetId: (input as { assetId?: string }).assetId ?? 'demo-asset-01',
    p30dCompromise: 0.623,
    riskLabel: 'high',
    factors: {
      cvssContribution: 0.126,
      epssContribution: 0.238,
      kevBonus: 0.27,
      criticalityMultiplier: 0.75,
      exposureMultiplier: 1.12,
    },
    modelVersion: '1.0.0',
    modelVersionId: 'sentra-asset_risk-prod-v1',
    confidenceInterval: { lower: 0.543, upper: 0.703 },
    inferenceMs: 12,
    demo,
  }),
  sentraIdentityBlastRadius: (input, demo) => ({
    identityId: (input as { identityId?: string }).identityId ?? 'demo-identity-01',
    p7dLateralPath: 0.512,
    estimatedBlastRadius: 51,
    highRiskTargets: ['DC-01', 'APP-02'],
    forecastHorizonDays: 7,
    nextLikelyPivots: [
      { system: 'DC-01', probability: 0.512, technique: 'Pass-the-Hash' },
      { system: 'APP-02', probability: 0.421, technique: 'Kerberoasting' },
      { system: 'DB-03', probability: 0.331, technique: 'SMB/Admin Share Abuse' },
    ],
    modelVersion: '1.0.0',
    modelVersionId: 'sentra-identity_blast-prod-v1',
    inferenceMs: 14,
    demo,
  }),
  submitHfJob: (input, demo) => ({
    jobId: `hf-${demo ? 'demo' : 'live'}-${Date.now().toString(36)}`,
    status: 'queued',
    flavor: (input as { flavor?: string }).flavor ?? 'cpu-basic',
    costPerMinute: 0.10,
    namespace: (input as { namespace?: string }).namespace ?? 'szl-holdings',
    message: `HF Job submitted (${(input as { type?: string }).type ?? 'docker'}) on ${(input as { flavor?: string }).flavor ?? 'cpu-basic'}`,
    demo,
  }),
  submitHfScheduledJob: (input, demo) => ({
    scheduleId: `hf-sched-${demo ? 'demo' : 'live'}-${Date.now().toString(36)}`,
    status: 'active',
    cron: (input as { cron?: string }).cron ?? '0 2 * * *',
    flavor: (input as { flavor?: string }).flavor ?? 'cpu-basic',
    namespace: (input as { namespace?: string }).namespace ?? 'szl-holdings',
    message: `HF scheduled job created with cron "${(input as { cron?: string }).cron ?? '0 2 * * *'}"`,
    demo,
  }),
  sentraAdversaryReplay: (input, demo) => ({
    scenarioId: (input as { scenarioId?: string }).scenarioId ?? `SIM-DEMO-${Date.now().toString(36).toUpperCase()}`,
    attackChain: [
      { step: 1, technique: 'Pass-the-Hash', techniqueId: 'T1550.002', tactic: 'Lateral Movement', successProbability: 0.61, detectionProbability: 0.28, outcome: 'succeeded' },
      { step: 2, technique: 'Kerberoasting', techniqueId: 'T1558.003', tactic: 'Credential Access', successProbability: 0.54, detectionProbability: 0.41, outcome: 'blocked' },
      { step: 3, technique: 'WMI Remote Execution', techniqueId: 'T1047', tactic: 'Execution', successProbability: 0.48, detectionProbability: 0.33, outcome: 'succeeded' },
    ],
    overallSuccessRate: 0.348,
    monteCarloRuns: 10000,
    meanTimeToBreakout: 93,
    confidenceInterval: { lower: 0.298, upper: 0.398 },
    recommendedMitigations: [
      'Enable EDR behavioral detection for scheduled tasks and LOLBins',
      'Enforce Credential Guard and LSASS protection on all endpoints',
      'Enable MFA on all privileged accounts',
    ],
    modelVersion: '1.0.0',
    modelVersionId: 'sentra-adversary_replay-prod-v1',
    inferenceMs: 24,
    demo,
  }),
};

const toolMap = new Map<string, ToolMetadata>(TOOL_CATALOGUE.map((t) => [t.id, t]));

export function getTool(toolId: string): ToolMetadata | undefined {
  return toolMap.get(toolId);
}

export function listTools(): ToolMetadata[] {
  return TOOL_CATALOGUE;
}

export function executeToolMock(toolId: string, input: Record<string, unknown>, isDemoMode: boolean): ToolResult {
  const tool = toolMap.get(toolId);
  if (!tool) {
    return { ok: false, toolId, error: `Tool "${toolId}" not found in registry.`, durationMs: 0 };
  }
  if (isDemoMode && !tool.demoSupported) {
    return { ok: false, toolId, error: `Tool "${toolId}" is not available in demo mode.`, durationMs: 0 };
  }
  const t = Date.now();
  const mockFn = MOCK_OUTPUTS[toolId];
  const output = mockFn ? mockFn(input, isDemoMode) : { status: 'ok', toolId, demo: isDemoMode };
  return { ok: true, toolId, output, durationMs: Date.now() - t, isDemo: isDemoMode };
}

export function getMcpToolDescriptions(): Array<{ name: string; description: string; inputSchema: Record<string, unknown> }> {
  return TOOL_CATALOGUE.map((t) => ({
    name: t.id,
    description: t.description,
    inputSchema: t.inputSchema,
  }));
}
