import {
  db,
  firestormAlertsTable,
  firestormAssessmentsTable,
  firestormAssetsTable,
  firestormCasesTable,
  firestormComplianceControlsTable,
  firestormFindingsTable,
  firestormHardeningControlsTable,
  firestormIncidentsTable,
  firestormMitreDetectionsTable,
} from '@szl-holdings/db';
import { sql } from 'drizzle-orm';

const ANALYSTS = [
  'J. Chen',
  'M. Rodriguez',
  'S. Park',
  'K. Wilson',
  'A. Thompson',
  'R. Davis',
  'L. Nguyen',
];

function daysAgo(n: number) {
  return new Date(Date.now() - n * 86400000);
}
function hoursAgo(n: number) {
  return new Date(Date.now() - n * 3600000);
}

export async function seedParagon() {

  const existingIncidents = await db
    .select({ id: firestormIncidentsTable.id })
    .from(firestormIncidentsTable)
    .limit(1);
  if (existingIncidents.length > 5) {
    return { skipped: true };
  }

  await db.execute(
    sql`TRUNCATE TABLE firestorm_incidents, firestorm_findings, firestorm_assets, firestorm_alerts, firestorm_hardening_controls, firestorm_compliance_controls, firestorm_cases, firestorm_mitre_detections, firestorm_assessments RESTART IDENTITY CASCADE`,
  );

  const [assessment] = await db
    .insert(firestormAssessmentsTable)
    .values({
      name: 'Q1 2026 Enterprise Security Assessment',
      description: 'Comprehensive quarterly security assessment across all production systems',
      assessmentType: 'penetration_test',
      status: 'completed',
      scope: 'All production systems, cloud infrastructure, and network perimeter',
      targetEnvironment: 'Production',
      assessorName: 'PARAGON Red Team',
      startDate: daysAgo(45),
      endDate: daysAgo(10),
      overallRiskScore: '7.4',
      executiveSummary:
        'Identified 23 critical findings requiring immediate remediation. Cloud IAM configuration and legacy database encryption are priority concerns.',
    })
    .returning();

  const assessmentId = assessment.id;

  const assets = await db
    .insert(firestormAssetsTable)
    .values([
      {
        name: 'prod-api-gateway-01',
        assetType: 'server',
        owner: 'Alex Chen',
        team: 'Platform',
        environment: 'production',
        exposureLevel: 'public',
        riskScore: '9.2',
        criticalFindings: 3,
        highFindings: 7,
        lastScannedAt: hoursAgo(2),
      },
      {
        name: 'auth-service-cluster',
        assetType: 'application',
        owner: 'Sarah Kim',
        team: 'Security',
        environment: 'production',
        exposureLevel: 'critical',
        riskScore: '8.7',
        criticalFindings: 2,
        highFindings: 4,
        lastScannedAt: hoursAgo(1),
      },
      {
        name: 'customer-data-db-primary',
        assetType: 'database',
        owner: 'Marcus Webb',
        team: 'Data',
        environment: 'production',
        exposureLevel: 'restricted',
        riskScore: '7.5',
        criticalFindings: 1,
        highFindings: 6,
        lastScannedAt: hoursAgo(4),
      },
      {
        name: 'aws-eks-prod-cluster',
        assetType: 'cloud_resource',
        owner: 'Jordan Alvarez',
        team: 'Infrastructure',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '6.8',
        criticalFindings: 0,
        highFindings: 8,
        lastScannedAt: hoursAgo(6),
      },
      {
        name: 'corporate-vpn-gateway',
        assetType: 'network_device',
        owner: 'Riley Torres',
        team: 'Network',
        environment: 'dmz',
        exposureLevel: 'public',
        riskScore: '8.1',
        criticalFindings: 2,
        highFindings: 3,
        lastScannedAt: hoursAgo(3),
      },
      {
        name: 'dev-k8s-cluster',
        assetType: 'container',
        owner: 'Sam Park',
        team: 'DevOps',
        environment: 'development',
        exposureLevel: 'internal',
        riskScore: '3.2',
        criticalFindings: 0,
        highFindings: 1,
        lastScannedAt: hoursAgo(12),
      },
      {
        name: 'payment-api-v3',
        assetType: 'api',
        owner: 'Alex Chen',
        team: 'Payments',
        environment: 'production',
        exposureLevel: 'public',
        riskScore: '9.5',
        criticalFindings: 4,
        highFindings: 9,
        lastScannedAt: hoursAgo(0.5),
      },
      {
        name: 'admin-portal-sso',
        assetType: 'iam_identity',
        owner: 'Morgan Lee',
        team: 'Security',
        environment: 'production',
        exposureLevel: 'critical',
        riskScore: '7.9',
        criticalFindings: 1,
        highFindings: 5,
        lastScannedAt: hoursAgo(8),
      },
      {
        name: 'legacy-fin-server-03',
        assetType: 'server',
        owner: 'Jordan Alvarez',
        team: 'Finance',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '5.4',
        criticalFindings: 0,
        highFindings: 3,
        lastScannedAt: hoursAgo(24),
      },
      {
        name: 'staging-api-cluster',
        assetType: 'application',
        owner: 'Sam Park',
        team: 'Platform',
        environment: 'staging',
        exposureLevel: 'internal',
        riskScore: '2.1',
        criticalFindings: 0,
        highFindings: 0,
        lastScannedAt: hoursAgo(48),
      },
      {
        name: 'endpoint-win-fleet',
        assetType: 'endpoint',
        owner: 'Riley Torres',
        team: 'IT',
        environment: 'internal',
        exposureLevel: 'internal',
        riskScore: '6.2',
        criticalFindings: 0,
        highFindings: 11,
        lastScannedAt: hoursAgo(2),
      },
      {
        name: 'ml-inference-api',
        assetType: 'api',
        owner: 'Marcus Webb',
        team: 'AI',
        environment: 'production',
        exposureLevel: 'restricted',
        riskScore: '4.8',
        criticalFindings: 0,
        highFindings: 2,
        lastScannedAt: hoursAgo(5),
      },
      {
        name: 'prod-redis-cluster',
        assetType: 'database',
        owner: 'Alex Chen',
        team: 'Platform',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '5.1',
        criticalFindings: 0,
        highFindings: 4,
        lastScannedAt: hoursAgo(6),
      },
      {
        name: 'web-app-frontend',
        assetType: 'application',
        owner: 'Morgan Lee',
        team: 'Frontend',
        environment: 'production',
        exposureLevel: 'public',
        riskScore: '4.3',
        criticalFindings: 0,
        highFindings: 2,
        lastScannedAt: hoursAgo(10),
      },
      {
        name: 'internal-dns-server',
        assetType: 'server',
        owner: 'Riley Torres',
        team: 'Network',
        environment: 'internal',
        exposureLevel: 'internal',
        riskScore: '3.8',
        criticalFindings: 0,
        highFindings: 1,
        lastScannedAt: hoursAgo(18),
      },
      {
        name: 'azure-ad-tenant',
        assetType: 'iam_identity',
        owner: 'Sarah Kim',
        team: 'Security',
        environment: 'production',
        exposureLevel: 'critical',
        riskScore: '8.4',
        criticalFindings: 2,
        highFindings: 6,
        lastScannedAt: hoursAgo(3),
      },
      {
        name: 'prod-s3-data-lake',
        assetType: 'cloud_resource',
        owner: 'Marcus Webb',
        team: 'Data',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '6.5',
        criticalFindings: 0,
        highFindings: 5,
        lastScannedAt: hoursAgo(7),
      },
      {
        name: 'monitoring-infra-grafana',
        assetType: 'application',
        owner: 'Sam Park',
        team: 'DevOps',
        environment: 'internal',
        exposureLevel: 'restricted',
        riskScore: '4.1',
        criticalFindings: 0,
        highFindings: 2,
        lastScannedAt: hoursAgo(14),
      },
      {
        name: 'firewall-edge-01',
        assetType: 'network_device',
        owner: 'Riley Torres',
        team: 'Network',
        environment: 'dmz',
        exposureLevel: 'public',
        riskScore: '7.3',
        criticalFindings: 1,
        highFindings: 4,
        lastScannedAt: hoursAgo(4),
      },
      {
        name: 'prod-kafka-cluster',
        assetType: 'server',
        owner: 'Jordan Alvarez',
        team: 'Infrastructure',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '5.7',
        criticalFindings: 0,
        highFindings: 3,
        lastScannedAt: hoursAgo(9),
      },
      {
        name: 'reporting-db-replica',
        assetType: 'database',
        owner: 'Marcus Webb',
        team: 'Data',
        environment: 'production',
        exposureLevel: 'restricted',
        riskScore: '4.9',
        criticalFindings: 0,
        highFindings: 2,
        lastScannedAt: hoursAgo(11),
      },
      {
        name: 'ci-cd-jenkins',
        assetType: 'application',
        owner: 'Sam Park',
        team: 'DevOps',
        environment: 'internal',
        exposureLevel: 'internal',
        riskScore: '6.1',
        criticalFindings: 0,
        highFindings: 4,
        lastScannedAt: hoursAgo(15),
      },
      {
        name: 'backup-storage-nas',
        assetType: 'server',
        owner: 'Jordan Alvarez',
        team: 'Infrastructure',
        environment: 'internal',
        exposureLevel: 'restricted',
        riskScore: '3.5',
        criticalFindings: 0,
        highFindings: 1,
        lastScannedAt: hoursAgo(36),
      },
      {
        name: 'email-gateway',
        assetType: 'application',
        owner: 'Riley Torres',
        team: 'IT',
        environment: 'dmz',
        exposureLevel: 'public',
        riskScore: '5.9',
        criticalFindings: 0,
        highFindings: 3,
        lastScannedAt: hoursAgo(5),
      },
      {
        name: 'prod-elasticsearch',
        assetType: 'database',
        owner: 'Marcus Webb',
        team: 'Data',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '5.3',
        criticalFindings: 0,
        highFindings: 3,
        lastScannedAt: hoursAgo(8),
      },
      {
        name: 'zero-trust-gateway',
        assetType: 'network_device',
        owner: 'Sarah Kim',
        team: 'Security',
        environment: 'dmz',
        exposureLevel: 'public',
        riskScore: '6.4',
        criticalFindings: 0,
        highFindings: 3,
        lastScannedAt: hoursAgo(6),
      },
      {
        name: 'mobile-api-backend',
        assetType: 'api',
        owner: 'Alex Chen',
        team: 'Mobile',
        environment: 'production',
        exposureLevel: 'public',
        riskScore: '7.1',
        criticalFindings: 1,
        highFindings: 5,
        lastScannedAt: hoursAgo(3),
      },
      {
        name: 'analytics-pipeline',
        assetType: 'cloud_resource',
        owner: 'Marcus Webb',
        team: 'Data',
        environment: 'production',
        exposureLevel: 'internal',
        riskScore: '4.4',
        criticalFindings: 0,
        highFindings: 2,
        lastScannedAt: hoursAgo(12),
      },
      {
        name: 'workstation-devops-01',
        assetType: 'endpoint',
        owner: 'Sam Park',
        team: 'DevOps',
        environment: 'internal',
        exposureLevel: 'internal',
        riskScore: '3.7',
        criticalFindings: 0,
        highFindings: 1,
        lastScannedAt: hoursAgo(20),
      },
      {
        name: 'secrets-vault-prod',
        assetType: 'application',
        owner: 'Sarah Kim',
        team: 'Security',
        environment: 'production',
        exposureLevel: 'critical',
        riskScore: '8.9',
        criticalFindings: 2,
        highFindings: 3,
        lastScannedAt: hoursAgo(1),
      },

      ...Array.from({ length: 170 }, (_, i) => ({
        name: `asset-${String(i + 31).padStart(3, '0')}-${['server', 'endpoint', 'container', 'api', 'database'][i % 5]}`,
        assetType: ['server', 'endpoint', 'container', 'api', 'database'][i % 5] as any,
        owner: ANALYSTS[i % ANALYSTS.length],
        team: ['Platform', 'Security', 'Data', 'Infrastructure', 'DevOps', 'Network', 'IT'][i % 7],
        environment: ['production', 'staging', 'development', 'internal', 'dmz'][i % 5] as any,
        exposureLevel: ['internal', 'internal', 'internal', 'public', 'restricted'][i % 5] as any,
        riskScore: String(Math.round((1 + Math.random() * 7) * 10) / 10),
        criticalFindings: Math.random() < 0.1 ? Math.floor(Math.random() * 3) : 0,
        highFindings: Math.floor(Math.random() * 5),
        lastScannedAt: hoursAgo(Math.floor(Math.random() * 72)),
      })),
    ])
    .returning();

  const findings = await db
    .insert(firestormFindingsTable)
    .values([
      {
        assessmentId,
        title: 'SQL Injection in Customer Search API',
        severity: 'critical',
        status: 'open',
        affectedAsset: 'payment-api-v3',
        cvssScore: '9.8',
        recommendation: 'Parameterize all SQL queries and validate user inputs',
        description:
          'Unvalidated input in the customer search endpoint allows attackers to inject arbitrary SQL.',
        remediationOwner: 'Alex Chen',
        dueDate: daysAgo(-7),
        auditTrail: [
          { action: 'Detected by DAST scanner', user: 'Scanner', at: daysAgo(5).toISOString() },
          { action: 'Assigned to Alex Chen', user: 'System', at: daysAgo(4).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Broken Authentication in Admin Portal',
        severity: 'critical',
        status: 'confirmed',
        affectedAsset: 'admin-portal-sso',
        cvssScore: '9.1',
        recommendation: 'Enforce MFA and implement proper session timeout',
        description: 'Admin portal allows bypass of authentication via crafted JWT token.',
        remediationOwner: 'Morgan Lee',
        dueDate: daysAgo(-3),
        auditTrail: [
          { action: 'Detected by Red Team', user: 'Red Team', at: daysAgo(6).toISOString() },
          { action: 'Confirmed by Security', user: 'Morgan Lee', at: daysAgo(5).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Unencrypted Data at Rest in Legacy DB',
        severity: 'high',
        status: 'open',
        affectedAsset: 'legacy-fin-server-03',
        cvssScore: '7.5',
        recommendation: 'Enable AES-256 encryption for all PII fields',
        description: 'Customer PII stored without encryption in legacy financial database.',
        remediationOwner: 'Marcus Webb',
        dueDate: daysAgo(-10),
        auditTrail: [{ action: 'Detected by Audit', user: 'Audit', at: daysAgo(8).toISOString() }],
      },
      {
        assessmentId,
        title: 'SSRF via Webhook URL Parameter',
        severity: 'high',
        status: 'open',
        affectedAsset: 'prod-api-gateway-01',
        cvssScore: '7.2',
        recommendation: 'Allowlist webhook target domains and block internal IP ranges',
        description:
          'The webhook integration endpoint accepts arbitrary URLs, allowing SSRF to internal services.',
        remediationOwner: 'Jordan Alvarez',
        dueDate: daysAgo(-8),
        auditTrail: [
          { action: 'Detected by Pen Test', user: 'Pen Test', at: daysAgo(7).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Outdated Container Base Image CVE-2024-21626',
        severity: 'high',
        status: 'mitigated',
        affectedAsset: 'aws-eks-prod-cluster',
        cvssScore: '8.6',
        recommendation: 'Rebuild all container images from patched base image',
        description: 'Container escape vulnerability in runc affects the production EKS cluster.',
        remediationOwner: 'Sam Park',
        dueDate: daysAgo(-1),
        auditTrail: [
          { action: 'Detected by Trivy Scan', user: 'Trivy Scan', at: daysAgo(10).toISOString() },
          { action: 'Patch applied', user: 'Sam Park', at: daysAgo(3).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Exposed Debug Endpoints in Staging',
        severity: 'medium',
        status: 'accepted',
        affectedAsset: 'staging-api-cluster',
        cvssScore: '5.3',
        recommendation: 'Remove debug endpoints before any promotion to production',
        description: 'Debug endpoints expose stack traces and internal configuration.',
        remediationOwner: 'Riley Torres',
        dueDate: daysAgo(-15),
        auditTrail: [
          { action: 'Risk Accepted', user: 'Riley Torres', at: daysAgo(2).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Missing HSTS Headers on Corporate VPN Portal',
        severity: 'medium',
        status: 'open',
        affectedAsset: 'corporate-vpn-gateway',
        cvssScore: '5.0',
        recommendation: 'Configure Strict-Transport-Security header with includeSubDomains',
        description: 'The VPN web portal does not enforce HTTPS via HSTS headers.',
        remediationOwner: 'Riley Torres',
        dueDate: daysAgo(-5),
        auditTrail: [
          { action: 'Detected by Web Scanner', user: 'Web Scanner', at: daysAgo(3).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Overly Permissive IAM Policy on S3 Buckets',
        severity: 'high',
        status: 'confirmed',
        affectedAsset: 'aws-eks-prod-cluster',
        cvssScore: '7.8',
        recommendation: 'Apply least-privilege IAM policies; remove s3:* wildcard permissions',
        description:
          'Service accounts with wildcard S3 permissions allow lateral movement to sensitive buckets.',
        remediationOwner: 'Jordan Alvarez',
        dueDate: daysAgo(-6),
        auditTrail: [
          {
            action: 'Detected by Cloud Scanner',
            user: 'Cloud Scanner',
            at: daysAgo(9).toISOString(),
          },
        ],
      },
      {
        assessmentId,
        title: 'Default Credentials on Network Device',
        severity: 'critical',
        status: 'open',
        affectedAsset: 'corporate-vpn-gateway',
        cvssScore: '10.0',
        recommendation: 'Change all default credentials immediately and audit all network devices',
        description: 'Network switch accessible with factory-default admin:admin credentials.',
        remediationOwner: 'Riley Torres',
        dueDate: daysAgo(-1),
        auditTrail: [
          {
            action: 'Detected by Network Audit',
            user: 'Network Audit',
            at: daysAgo(2).toISOString(),
          },
        ],
      },
      {
        assessmentId,
        title: 'Log4Shell in Internal Analytics Service',
        severity: 'low',
        status: 'false_positive',
        affectedAsset: 'ml-inference-api',
        cvssScore: '2.5',
        recommendation: 'Confirmed not exploitable in current configuration',
        description: 'Potential Log4Shell vector confirmed non-exploitable due to JVM version.',
        remediationOwner: 'Marcus Webb',
        dueDate: daysAgo(-20),
        auditTrail: [
          {
            action: 'Detected by DAST Scanner',
            user: 'DAST Scanner',
            at: daysAgo(12).toISOString(),
          },
          { action: 'Marked False Positive', user: 'Marcus Webb', at: daysAgo(9).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Azure AD Conditional Access Policy Gaps',
        severity: 'critical',
        status: 'open',
        affectedAsset: 'azure-ad-tenant',
        cvssScore: '9.0',
        recommendation: 'Enforce MFA for all admin accounts and implement RBAC least privilege',
        description:
          'Multiple admin accounts lack MFA enforcement, allowing takeover via credential stuffing.',
        remediationOwner: 'Sarah Kim',
        dueDate: daysAgo(-4),
        auditTrail: [
          { action: 'Identified in Entra audit', user: 'S. Kim', at: daysAgo(4).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Insecure Direct Object Reference in Payment API',
        severity: 'critical',
        status: 'confirmed',
        affectedAsset: 'payment-api-v3',
        cvssScore: '9.3',
        recommendation: 'Implement server-side authorization for all object references',
        description:
          "Payment API exposes sequential IDs allowing enumeration of other users' transactions.",
        remediationOwner: 'Alex Chen',
        dueDate: daysAgo(-3),
        auditTrail: [
          {
            action: 'Found during code review',
            user: 'Security Team',
            at: daysAgo(5).toISOString(),
          },
        ],
      },
      {
        assessmentId,
        title: 'Weak Secrets Rotation Policy in Vault',
        severity: 'high',
        status: 'open',
        affectedAsset: 'secrets-vault-prod',
        cvssScore: '7.1',
        recommendation: 'Implement automatic 90-day rotation for all production secrets',
        description:
          'Production secrets have not been rotated in 18 months, increasing blast radius of credential leaks.',
        remediationOwner: 'Sarah Kim',
        dueDate: daysAgo(-7),
        auditTrail: [
          { action: 'Flagged in access review', user: 'Audit Team', at: daysAgo(6).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Unpatched CVE-2024-3400 on Palo Alto Firewall',
        severity: 'critical',
        status: 'open',
        affectedAsset: 'firewall-edge-01',
        cvssScore: '10.0',
        recommendation: 'Apply vendor patch immediately; isolate firewall from management plane',
        description: 'PAN-OS GlobalProtect vulnerability allows unauthenticated RCE as root.',
        remediationOwner: 'Riley Torres',
        dueDate: daysAgo(-2),
        auditTrail: [
          { action: 'CISA KEV alert received', user: 'CISA Feed', at: daysAgo(3).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'CI/CD Pipeline Secret Exposure in Logs',
        severity: 'high',
        status: 'open',
        affectedAsset: 'ci-cd-jenkins',
        cvssScore: '7.4',
        recommendation: 'Audit all pipeline logs and rotate any exposed secrets immediately',
        description:
          'Jenkins pipeline logs contain plaintext AWS credentials and database passwords.',
        remediationOwner: 'Sam Park',
        dueDate: daysAgo(-5),
        auditTrail: [
          { action: 'Detected by SAST scan', user: 'SAST Scanner', at: daysAgo(4).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Unrestricted Outbound Firewall Rules',
        severity: 'medium',
        status: 'open',
        affectedAsset: 'firewall-edge-01',
        cvssScore: '5.8',
        recommendation: 'Implement allowlist-based egress filtering; block non-business traffic',
        description:
          'Firewall permits all outbound TCP/443 without destination filtering, enabling C2 over HTTPS.',
        remediationOwner: 'Riley Torres',
        dueDate: daysAgo(-14),
        auditTrail: [
          {
            action: 'Flagged in network review',
            user: 'Network Team',
            at: daysAgo(7).toISOString(),
          },
        ],
      },
      {
        assessmentId,
        title: 'Publicly Exposed Admin Interface on Monitoring',
        severity: 'high',
        status: 'open',
        affectedAsset: 'monitoring-infra-grafana',
        cvssScore: '7.6',
        recommendation: 'Place Grafana behind VPN or restrict by IP allowlist',
        description:
          'Grafana admin interface accessible from the internet with default admin credentials still set.',
        remediationOwner: 'Sam Park',
        dueDate: daysAgo(-6),
        auditTrail: [
          {
            action: 'Found via external scan',
            user: 'External Auditor',
            at: daysAgo(5).toISOString(),
          },
        ],
      },
      {
        assessmentId,
        title: 'Unencrypted Kafka Broker Communication',
        severity: 'medium',
        status: 'open',
        affectedAsset: 'prod-kafka-cluster',
        cvssScore: '6.1',
        recommendation: 'Enable TLS for all Kafka broker-to-broker and client-to-broker traffic',
        description:
          'Kafka cluster uses plaintext protocol for internal communication, exposing message content.',
        remediationOwner: 'Jordan Alvarez',
        dueDate: daysAgo(-10),
        auditTrail: [
          { action: 'Detected by network scan', user: 'Infra Team', at: daysAgo(6).toISOString() },
        ],
      },
      {
        assessmentId,
        title: 'Redis Cluster Accessible Without Authentication',
        severity: 'critical',
        status: 'open',
        affectedAsset: 'prod-redis-cluster',
        cvssScore: '9.8',
        recommendation: 'Enable Redis AUTH and bind to private network interfaces only',
        description:
          'Production Redis cluster accepts connections without password from any internal host.',
        remediationOwner: 'Alex Chen',
        dueDate: daysAgo(-2),
        auditTrail: [
          {
            action: 'Detected by internal scan',
            user: 'Platform Team',
            at: daysAgo(2).toISOString(),
          },
        ],
      },
      {
        assessmentId,
        title: 'Mobile API Missing Certificate Pinning',
        severity: 'medium',
        status: 'open',
        affectedAsset: 'mobile-api-backend',
        cvssScore: '5.4',
        recommendation: 'Implement certificate pinning in all mobile client applications',
        description:
          'Mobile API lacks certificate pinning, allowing MITM attacks on compromised networks.',
        remediationOwner: 'Alex Chen',
        dueDate: daysAgo(-12),
        auditTrail: [
          {
            action: 'Found in mobile security review',
            user: 'Mobile Team',
            at: daysAgo(8).toISOString(),
          },
        ],
      },

      ...Array.from({ length: 80 }, (_, i) => ({
        assessmentId,
        title:
          `${[
            'Insecure cookie attributes on session token',
            'Missing input validation on API endpoint',
            'Outdated TLS 1.0 configuration on legacy service',
            'Insufficient logging for privileged account actions',
            'Exposed internal service via misconfigured proxy',
            'Hardcoded credentials in configuration file',
            'Insufficient CSRF protection on form submission',
            'Path traversal in file upload handler',
            'XML external entity injection in import function',
            'Prototype pollution in JavaScript library',
            'Dependency with known critical CVE',
            'Missing rate limiting on authentication endpoint',
            'Cleartext password in error response body',
            'Unvalidated redirect in OAuth flow',
            'Server-side template injection via user input',
          ][i % 15]} (${String.fromCharCode(65 + (i % 26))}${i})`,
        severity: (['critical', 'high', 'high', 'medium', 'medium', 'medium', 'low'] as const)[
          i % 7
        ],
        status: (['open', 'open', 'confirmed', 'mitigated', 'accepted', 'false_positive'] as const)[
          i % 6
        ],
        affectedAsset: [
          'prod-api-gateway-01',
          'payment-api-v3',
          'auth-service-cluster',
          'legacy-fin-server-03',
          'aws-eks-prod-cluster',
          'corporate-vpn-gateway',
          'azure-ad-tenant',
          'ci-cd-jenkins',
        ][i % 8],
        cvssScore: String(Math.round((3 + Math.random() * 7) * 10) / 10),
        recommendation: 'Apply security patch and implement defense-in-depth controls.',
        description:
          'Security vulnerability detected during automated assessment requiring remediation.',
        remediationOwner: ANALYSTS[i % ANALYSTS.length],
        dueDate: daysAgo(-(5 + (i % 30))),
        auditTrail: [
          { action: 'Detected', user: 'Scanner', at: daysAgo(3 + (i % 10)).toISOString() },
        ],
      })),
    ])
    .returning();

  const incidents = await db
    .insert(firestormIncidentsTable)
    .values([
      {
        title: 'Lateral movement detected on DC-PROD-03',
        severity: 'critical',
        status: 'containment',
        assignedAnalyst: 'J. Chen',
        attackTechnique: 'T1021.002',
        description:
          'Attacker moved from WORKSTATION-142 to domain controller using stolen admin credentials. C2 traffic detected to known APT29 infrastructure.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(2).toISOString(),
            note: 'EDR alert triggered on anomalous SMB connections',
          },
          {
            stage: 'triage',
            at: daysAgo(1.9).toISOString(),
            note: 'Analyst confirmed lateral movement pattern',
          },
          {
            stage: 'containment',
            at: daysAgo(1.5).toISOString(),
            note: 'Isolated DC-PROD-03 from network segment',
          },
        ],
        detectedAt: daysAgo(2),
        affectedAssets: ['DC-PROD-03', 'WORKSTATION-142'],
      },
      {
        title: 'C2 beacon traffic to known APT29 infrastructure',
        severity: 'critical',
        status: 'investigation',
        assignedAnalyst: 'M. Rodriguez',
        attackTechnique: 'T1071.001',
        description:
          'Periodic beaconing traffic detected to IP 203.0.113.45 associated with APT29 COZY BEAR campaign. Beacon interval 4 hours, encrypted via HTTPS.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(3).toISOString(),
            note: 'Threat intel feed matched known IOC',
          },
          {
            stage: 'triage',
            at: daysAgo(2.8).toISOString(),
            note: 'Confirmed C2 pattern, escalated to senior analyst',
          },
        ],
        detectedAt: daysAgo(3),
        affectedAssets: ['WORKSTATION-089', 'WORKSTATION-142'],
      },
      {
        title: 'Ransomware precursor activity on FILE-SRV-02',
        severity: 'critical',
        status: 'remediation',
        assignedAnalyst: 'S. Park',
        attackTechnique: 'T1486',
        description:
          'Vssadmin.exe and wbadmin.exe executed to delete shadow copies. Stage-2 malware detected attempting to encrypt network shares.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(5).toISOString(),
            note: 'AV alert on vssadmin execution',
          },
          {
            stage: 'triage',
            at: daysAgo(4.9).toISOString(),
            note: 'Ransomware precursor confirmed',
          },
          {
            stage: 'containment',
            at: daysAgo(4.7).toISOString(),
            note: 'Isolated FILE-SRV-02, blocked propagation',
          },
          {
            stage: 'remediation',
            at: daysAgo(3).toISOString(),
            note: 'Restoring from clean backup',
          },
        ],
        detectedAt: daysAgo(5),
        resolvedAt: daysAgo(1),
        affectedAssets: ['FILE-SRV-02'],
      },
      {
        title: 'Credential dumping via Mimikatz on WORKSTATION-089',
        severity: 'high',
        status: 'closed',
        assignedAnalyst: 'K. Wilson',
        attackTechnique: 'T1003.001',
        description:
          'LSASS process memory dump detected. Mimikatz variant used to extract NTLM hashes. Affected credentials rotated.',
        timeline: [
          { stage: 'detection', at: daysAgo(7).toISOString(), note: 'EDR process injection alert' },
          { stage: 'triage', at: daysAgo(6.9).toISOString(), note: 'Confirmed Mimikatz execution' },
          { stage: 'containment', at: daysAgo(6.5).toISOString(), note: 'Isolated workstation' },
          {
            stage: 'remediation',
            at: daysAgo(5).toISOString(),
            note: 'Credentials rotated, malware removed',
          },
          { stage: 'closed', at: daysAgo(4).toISOString(), note: 'Incident closed, PIR complete' },
        ],
        detectedAt: daysAgo(7),
        resolvedAt: daysAgo(4),
        affectedAssets: ['WORKSTATION-089'],
      },
      {
        title: 'Brute force attack on VPN gateway — 847 failed logins',
        severity: 'high',
        status: 'closed',
        assignedAnalyst: 'A. Thompson',
        attackTechnique: 'T1110.001',
        description:
          'Sustained brute force from IP range 103.45.67.0/24 targeting VPN authentication. Account lockout triggered for 12 users.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(4).toISOString(),
            note: 'SIEM alert on excessive auth failures',
          },
          {
            stage: 'triage',
            at: daysAgo(3.9).toISOString(),
            note: 'Confirmed distributed brute force',
          },
          {
            stage: 'containment',
            at: daysAgo(3.8).toISOString(),
            note: 'Blocked source IP range at firewall',
          },
          {
            stage: 'closed',
            at: daysAgo(3).toISOString(),
            note: 'Attack stopped, no successful logins',
          },
        ],
        detectedAt: daysAgo(4),
        resolvedAt: daysAgo(3),
        affectedAssets: ['corporate-vpn-gateway'],
      },
      {
        title: 'Data exfiltration pattern: 2.3GB to external S3 bucket',
        severity: 'critical',
        status: 'triage',
        assignedAnalyst: 'R. Davis',
        attackTechnique: 'T1567.002',
        description:
          'DLP alert triggered on large data transfer to unrecognized S3 bucket. Transfer originated from prod-api-gateway-01, destination AWS account not in approved list.',
        timeline: [
          {
            stage: 'detection',
            at: hoursAgo(6).toISOString(),
            note: 'DLP rule triggered on outbound S3 traffic',
          },
          {
            stage: 'triage',
            at: hoursAgo(5).toISOString(),
            note: 'Investigating source process and data classification',
          },
        ],
        detectedAt: hoursAgo(6),
        affectedAssets: ['prod-api-gateway-01', 'prod-s3-data-lake'],
      },
      {
        title: 'Azure AD impossible travel anomaly — jsmith',
        severity: 'medium',
        status: 'closed',
        assignedAnalyst: 'J. Chen',
        attackTechnique: 'T1078',
        description:
          'User jsmith authenticated from New York then Moscow 45 minutes later. Physical travel impossible. Account temporarily suspended pending investigation.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(6).toISOString(),
            note: 'Entra ID risk alert on impossible travel',
          },
          {
            stage: 'triage',
            at: daysAgo(5.9).toISOString(),
            note: 'Confirmed travel impossibility, account suspended',
          },
          {
            stage: 'remediation',
            at: daysAgo(5.5).toISOString(),
            note: 'Password reset, MFA re-enrolled',
          },
          {
            stage: 'closed',
            at: daysAgo(5).toISOString(),
            note: 'Confirmed compromised, contained',
          },
        ],
        detectedAt: daysAgo(6),
        resolvedAt: daysAgo(5),
        affectedAssets: ['azure-ad-tenant'],
      },
      {
        title: 'Exposed RDP on 3 production servers',
        severity: 'medium',
        status: 'remediation',
        assignedAnalyst: 'L. Nguyen',
        attackTechnique: 'T1133',
        description:
          'External scan reveals RDP (3389) exposed to internet on three production servers. No NLA enforced. Risk of BlueKeep and credential attacks.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(9).toISOString(),
            note: 'External vulnerability scan alert',
          },
          {
            stage: 'triage',
            at: daysAgo(8.8).toISOString(),
            note: 'Confirmed public exposure, prioritized',
          },
          {
            stage: 'containment',
            at: daysAgo(8).toISOString(),
            note: 'Emergency firewall rules applied',
          },
          {
            stage: 'remediation',
            at: daysAgo(6).toISOString(),
            note: 'Configuring NLA and moving to VPN-only',
          },
        ],
        detectedAt: daysAgo(9),
        affectedAssets: ['legacy-fin-server-03', 'prod-api-gateway-01'],
      },
      {
        title: 'Supply chain compromise in npm dependency',
        severity: 'high',
        status: 'detection',
        attackTechnique: 'T1195.002',
        description:
          "Popular npm package 'colors-lite' updated with malicious code that phones home with environment variables. Package imported in 3 production services.",
        detectedAt: hoursAgo(2),
        affectedAssets: ['prod-api-gateway-01', 'payment-api-v3', 'mobile-api-backend'],
        timeline: [
          {
            stage: 'detection',
            at: hoursAgo(2).toISOString(),
            note: 'Dependabot alert on malicious package update',
          },
        ],
      },
      {
        title: 'Phishing campaign targeting finance team',
        severity: 'high',
        status: 'closed',
        assignedAnalyst: 'M. Rodriguez',
        attackTechnique: 'T1566.001',
        description:
          'Targeted spearphishing campaign against CFO and finance team. 3 users clicked malicious link. Credential harvesting page served from lookalike domain.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(12).toISOString(),
            note: 'Email security gateway alert on lookalike domain',
          },
          {
            stage: 'triage',
            at: daysAgo(11.8).toISOString(),
            note: 'Confirmed phishing, 3 users affected',
          },
          {
            stage: 'containment',
            at: daysAgo(11.5).toISOString(),
            note: 'Blocked domain, credentials reset',
          },
          {
            stage: 'remediation',
            at: daysAgo(11).toISOString(),
            note: 'Security awareness training triggered',
          },
          { stage: 'closed', at: daysAgo(10).toISOString(), note: 'No credential reuse detected' },
        ],
        detectedAt: daysAgo(12),
        resolvedAt: daysAgo(10),
        affectedAssets: ['email-gateway', 'azure-ad-tenant'],
      },
      {
        title: 'Web shell planted on DMZ web server',
        severity: 'critical',
        status: 'remediation',
        assignedAnalyst: 'S. Park',
        attackTechnique: 'T1505.003',
        description:
          'PHP web shell discovered in uploads directory of DMZ web server. Shell has been active for estimated 72 hours. Log tampering evidence present.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(3).toISOString(),
            note: 'File integrity monitor alert',
          },
          {
            stage: 'triage',
            at: daysAgo(2.9).toISOString(),
            note: 'Web shell confirmed, forensics started',
          },
          {
            stage: 'containment',
            at: daysAgo(2.5).toISOString(),
            note: 'Server isolated, shell removed',
          },
          {
            stage: 'remediation',
            at: daysAgo(1).toISOString(),
            note: 'System rebuild in progress',
          },
        ],
        detectedAt: daysAgo(3),
        affectedAssets: ['web-app-frontend', 'email-gateway'],
      },
      {
        title: 'Insider threat: unauthorized bulk data export',
        severity: 'high',
        status: 'investigation',
        assignedAnalyst: 'K. Wilson',
        attackTechnique: 'T1005',
        description:
          'Former employee account (30-day notice period) exported 15,000 customer records to personal cloud storage 2 hours before final day.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(8).toISOString(),
            note: 'DLP alert on bulk export to OneDrive personal',
          },
          {
            stage: 'triage',
            at: daysAgo(7.8).toISOString(),
            note: 'HR and legal notified, account suspended',
          },
          {
            stage: 'investigation',
            at: daysAgo(7).toISOString(),
            note: 'Forensic investigation of data exported',
          },
        ],
        detectedAt: daysAgo(8),
        affectedAssets: ['customer-data-db-primary', 'prod-s3-data-lake'],
      },
      {
        title: 'DNS tunneling exfiltration from workstation fleet',
        severity: 'high',
        status: 'closed',
        assignedAnalyst: 'A. Thompson',
        attackTechnique: 'T1048.001',
        description:
          'Dnscat2-style DNS tunneling detected from 7 workstations. Data exfiltrated via TXT record queries to attacker-controlled domain. Estimated 500MB exfiltrated.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(15).toISOString(),
            note: 'DNS analytics alert on excessive TXT queries',
          },
          { stage: 'triage', at: daysAgo(14.8).toISOString(), note: 'Confirmed tunneling pattern' },
          { stage: 'containment', at: daysAgo(14).toISOString(), note: 'Blocked at DNS level' },
          { stage: 'remediation', at: daysAgo(12).toISOString(), note: 'Workstations reimaged' },
          { stage: 'closed', at: daysAgo(10).toISOString(), note: 'Full remediation complete' },
        ],
        detectedAt: daysAgo(15),
        resolvedAt: daysAgo(10),
        affectedAssets: ['endpoint-win-fleet', 'internal-dns-server'],
      },
      {
        title: 'Kubernetes privilege escalation via misconfigured RBAC',
        severity: 'critical',
        status: 'closed',
        assignedAnalyst: 'L. Nguyen',
        attackTechnique: 'T1078.004',
        description:
          'Developer service account escalated to cluster-admin via misconfigured ClusterRoleBinding. Used to access secrets in all namespaces.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(20).toISOString(),
            note: 'K8s audit log alert on cluster-admin binding',
          },
          {
            stage: 'triage',
            at: daysAgo(19.8).toISOString(),
            note: 'Confirmed privilege escalation',
          },
          {
            stage: 'containment',
            at: daysAgo(19.5).toISOString(),
            note: 'RBAC corrected, service account revoked',
          },
          {
            stage: 'remediation',
            at: daysAgo(18).toISOString(),
            note: 'Secrets rotated, audit complete',
          },
          {
            stage: 'closed',
            at: daysAgo(16).toISOString(),
            note: 'PIR completed, RBAC controls tightened',
          },
        ],
        detectedAt: daysAgo(20),
        resolvedAt: daysAgo(16),
        affectedAssets: ['aws-eks-prod-cluster', 'secrets-vault-prod'],
      },
      {
        title: 'OAuth token theft via open redirect vulnerability',
        severity: 'high',
        status: 'closed',
        assignedAnalyst: 'R. Davis',
        attackTechnique: 'T1189',
        description:
          'OAuth authorization code intercepted via open redirect in third-party integration. 24 user tokens compromised and revoked.',
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(25).toISOString(),
            note: 'SIEM alert on anomalous token exchange',
          },
          {
            stage: 'triage',
            at: daysAgo(24.8).toISOString(),
            note: 'Open redirect confirmed, scope of impact assessed',
          },
          {
            stage: 'containment',
            at: daysAgo(24.5).toISOString(),
            note: 'Vulnerable redirect removed, tokens revoked',
          },
          {
            stage: 'closed',
            at: daysAgo(22).toISOString(),
            note: 'Patch deployed, users notified',
          },
        ],
        detectedAt: daysAgo(25),
        resolvedAt: daysAgo(22),
        affectedAssets: ['auth-service-cluster', 'web-app-frontend'],
      },

      ...Array.from({ length: 40 }, (_, i) => ({
        title:
          `${[
            'Suspicious PowerShell execution on endpoint',
            'Failed privilege escalation attempt detected',
            'Anomalous network scan from internal host',
            'Malware detected and quarantined',
            'Unauthorized API key usage detected',
            'Container escape attempt blocked',
            'Certificate transparency log anomaly',
            'BGP route hijack attempt detected',
            'Cloud storage bucket misconfiguration',
            'Password spray attack on Office 365',
          ][i % 10]} — Instance ${i + 1}`,
        severity: (['critical', 'high', 'high', 'medium', 'medium', 'low'] as const)[i % 6],
        status: (
          ['closed', 'closed', 'remediation', 'containment', 'triage', 'detection'] as const
        )[i % 6],
        assignedAnalyst: ANALYSTS[i % ANALYSTS.length],
        attackTechnique: [
          'T1059.001',
          'T1548',
          'T1046',
          'T1059.003',
          'T1078.004',
          'T1611',
          'T1567',
          'T1599',
          'T1530',
          'T1110.003',
        ][i % 10],
        description: 'Security incident detected and being actively investigated by SOC analysts.',
        detectedAt: daysAgo(3 + i),
        resolvedAt: i % 6 < 2 ? daysAgo(1 + i) : undefined,
        affectedAssets: [
          ['prod-api-gateway-01', 'endpoint-win-fleet'],
          ['aws-eks-prod-cluster'],
          ['corporate-vpn-gateway'],
        ][i % 3] as string[],
        timeline: [
          {
            stage: 'detection',
            at: daysAgo(3 + i).toISOString(),
            note: 'Automated detection triggered',
          },
        ],
      })),
    ])
    .returning();

  const alerts = await db
    .insert(firestormAlertsTable)
    .values([
      {
        title: 'Lateral movement detected — SMB connections to DC-PROD-03',
        severity: 'critical',
        source: 'CrowdStrike Falcon',
        status: 'investigating',
        relatedIncidentId: incidents[0].id,
        metadata: { technique: 'T1021.002', confidence: 96 },
      },
      {
        title: 'C2 beacon to known APT29 IP 203.0.113.45',
        severity: 'critical',
        source: 'Threat Intel Feed',
        status: 'investigating',
        relatedIncidentId: incidents[1].id,
        metadata: { ioc: '203.0.113.45', threat_actor: 'APT29' },
      },
      {
        title: 'Mimikatz process injection on WORKSTATION-089',
        severity: 'high',
        source: 'SentinelOne EDR',
        status: 'resolved',
        metadata: { technique: 'T1003.001', process: 'lsass.exe' },
      },
      {
        title: '847 failed VPN logins from 103.45.67.0/24',
        severity: 'high',
        source: 'Palo Alto NGFW',
        status: 'resolved',
        metadata: { source_ip: '103.45.67.0/24', failed_count: 847 },
      },
      {
        title: 'DLP: 2.3GB outbound transfer to external S3',
        severity: 'critical',
        source: 'Symantec DLP',
        status: 'investigating',
        relatedIncidentId: incidents[5].id,
        metadata: { bytes_transferred: 2463856123, destination: 's3://external-unknown' },
      },
      {
        title: 'Azure AD risky sign-in: impossible travel jsmith',
        severity: 'medium',
        source: 'Microsoft Entra ID',
        status: 'resolved',
        metadata: { user: 'jsmith', locations: ['New York', 'Moscow'] },
      },
      {
        title: 'PHP web shell detected: /uploads/img.php',
        severity: 'critical',
        source: 'CrowdStrike Falcon',
        status: 'acknowledged',
        metadata: { path: '/var/www/html/uploads/img.php', md5: 'a1b2c3d4e5f6' },
      },
      {
        title: 'DNS tunneling: 15K TXT queries to attacker domain',
        severity: 'high',
        source: 'Infoblox DNS Security',
        status: 'resolved',
        metadata: { domain: 'exfil.evil.com', query_count: 15234 },
      },
      {
        title: 'K8s ClusterRoleBinding escalation to cluster-admin',
        severity: 'critical',
        source: 'Falco Runtime Security',
        status: 'resolved',
        metadata: { service_account: 'dev-svc', namespace: 'default' },
      },
      {
        title: 'Open redirect OAuth token interception detected',
        severity: 'high',
        source: 'Web Application Firewall',
        status: 'resolved',
        metadata: { redirect_url: 'https://attacker.com/callback' },
      },
      {
        title: 'Vssadmin.exe executed — shadow copy deletion attempt',
        severity: 'critical',
        source: 'SentinelOne EDR',
        status: 'acknowledged',
        metadata: { command: 'vssadmin delete shadows /all', host: 'FILE-SRV-02' },
      },
      {
        title: 'Bulk data export to personal cloud storage — former employee',
        severity: 'high',
        source: 'Microsoft 365 DLP',
        status: 'acknowledged',
        relatedIncidentId: incidents[11].id,
        metadata: { user: 'jdoe@company.com', records: 15000 },
      },
      {
        title: "Supply chain: malicious npm package 'colors-lite@2.1.0'",
        severity: 'high',
        source: 'Dependabot / SAST',
        status: 'new',
        relatedIncidentId: incidents[8].id,
        metadata: { package: 'colors-lite', version: '2.1.0' },
      },
      {
        title: 'Unpatched CVE-2024-3400 active exploitation in the wild',
        severity: 'critical',
        source: 'CISA KEV Feed',
        status: 'new',
        metadata: { cve: 'CVE-2024-3400', asset: 'firewall-edge-01' },
      },
      {
        title: 'Redis cluster authentication bypass detected',
        severity: 'critical',
        source: 'Network IDS',
        status: 'new',
        metadata: { host: 'prod-redis-cluster', connection_count: 42 },
      },
      {
        title: 'Spearphishing email with weaponized Word doc detected',
        severity: 'high',
        source: 'Proofpoint Email Security',
        status: 'resolved',
        metadata: { target: 'cfo@company.com', attachment: 'Invoice_Q1.docx' },
      },
      {
        title: 'Container escape attempt in production EKS cluster',
        severity: 'high',
        source: 'Falco Runtime Security',
        status: 'acknowledged',
        metadata: { container: 'prod-worker-4892', technique: 'T1611' },
      },
      {
        title: 'Anomalous outbound data to Cloudflare Worker endpoint',
        severity: 'medium',
        source: 'Zscaler Cloud Security',
        status: 'new',
        metadata: { destination: '*.workers.dev', data_size_mb: 450 },
      },
      {
        title: 'SAMLjacking attack attempt on federated SSO',
        severity: 'high',
        source: 'Okta ThreatInsight',
        status: 'new',
        metadata: { idp: 'okta', attack_type: 'SAMLjacking' },
      },
      {
        title: 'BGP route hijack affecting /24 subnet',
        severity: 'medium',
        source: 'BGPmon',
        status: 'new',
        metadata: { prefix: '192.0.2.0/24', origin_asn: 64512 },
      },
      ...Array.from({ length: 30 }, (_, i) => ({
        title: `Security alert ${i + 21}: automated detection triggered`,
        severity: (['critical', 'high', 'medium', 'low'] as const)[i % 4],
        source: ['CrowdStrike', 'SentinelOne', 'Splunk SIEM', 'Palo Alto', 'Microsoft Defender'][
          i % 5
        ],
        status: (['new', 'acknowledged', 'investigating', 'resolved', 'dismissed'] as const)[i % 5],
        metadata: { auto_generated: true, index: i },
      })),
    ])
    .returning();

  await db.insert(firestormHardeningControlsTable).values([
    {
      controlId: 'MFA-001',
      name: 'Enforce MFA for All Admin Accounts',
      description:
        'All privileged and admin accounts must use hardware-backed MFA (FIDO2 or TOTP).',
      category: 'mfa_credential',
      status: 'implemented',
      priority: 'critical',
      owner: 'Sarah Kim',
      linkedAssets: ['azure-ad-tenant', 'admin-portal-sso'],
      recommendedAction: 'Audit all admin accounts quarterly for MFA compliance',
      lastReviewedAt: daysAgo(7),
      auditTrail: [
        { action: 'Implemented via Okta', user: 'S. Kim', at: daysAgo(30).toISOString() },
        {
          action: 'Verified in quarterly review',
          user: 'Audit Team',
          at: daysAgo(7).toISOString(),
        },
      ],
    },
    {
      controlId: 'MFA-002',
      name: 'Privileged Access Workstation (PAW) Deployment',
      description:
        'Dedicated hardened workstations for privileged account administration with no internet access.',
      category: 'mfa_credential',
      status: 'partial',
      priority: 'critical',
      owner: 'Riley Torres',
      linkedAssets: ['admin-portal-sso', 'azure-ad-tenant'],
      recommendedAction: 'Complete PAW deployment for remaining 8 admin accounts',
      dueDate: daysAgo(-30),
      auditTrail: [
        {
          action: 'Partial deployment — 12 of 20 accounts',
          user: 'R. Torres',
          at: daysAgo(14).toISOString(),
        },
      ],
    },
    {
      controlId: 'MFA-003',
      name: 'Password Complexity and History Policy',
      description:
        'Minimum 16 character passwords with complexity requirements and 12-password history.',
      category: 'mfa_credential',
      status: 'implemented',
      priority: 'high',
      owner: 'Sarah Kim',
      linkedAssets: ['azure-ad-tenant'],
      recommendedAction: 'Review policy annually and align with NIST 800-63b guidance',
      lastReviewedAt: daysAgo(30),
    },
    {
      controlId: 'MFA-004',
      name: 'Service Account Password Rotation',
      description: 'Automated 90-day rotation for all service account credentials via Vault.',
      category: 'mfa_credential',
      status: 'not_implemented',
      priority: 'critical',
      owner: 'Sarah Kim',
      linkedAssets: ['secrets-vault-prod', 'ci-cd-jenkins'],
      recommendedAction: 'Implement Vault dynamic secrets for all service accounts immediately',
      dueDate: daysAgo(-14),
      auditTrail: [
        {
          action: 'Risk identified — 18+ month old credentials',
          user: 'Audit Team',
          at: daysAgo(6).toISOString(),
        },
      ],
    },
    {
      controlId: 'MFA-005',
      name: 'Conditional Access Policies by Location',
      description: 'Enforce MFA and device compliance for sign-ins from untrusted networks.',
      category: 'mfa_credential',
      status: 'partial',
      priority: 'high',
      owner: 'Sarah Kim',
      linkedAssets: ['azure-ad-tenant'],
      recommendedAction: 'Extend conditional access to cover all SaaS applications',
    },
    {
      controlId: 'APP-001',
      name: 'Web Application Firewall (WAF) on All Public APIs',
      description: 'WAF with OWASP CRS enabled in blocking mode for all internet-facing APIs.',
      category: 'application_hardening',
      status: 'implemented',
      priority: 'critical',
      owner: 'Alex Chen',
      linkedAssets: ['prod-api-gateway-01', 'payment-api-v3', 'mobile-api-backend'],
      recommendedAction: 'Review WAF rule effectiveness monthly via blocked request analysis',
      lastReviewedAt: daysAgo(14),
    },
    {
      controlId: 'APP-002',
      name: 'SAST/DAST in CI/CD Pipeline',
      description:
        'Static and dynamic security testing integrated into all deployment pipelines with quality gates.',
      category: 'application_hardening',
      status: 'partial',
      priority: 'high',
      owner: 'Sam Park',
      linkedAssets: ['ci-cd-jenkins'],
      recommendedAction:
        'Enforce build failure on critical SAST findings; add DAST stage to 4 remaining pipelines',
      dueDate: daysAgo(-21),
    },
    {
      controlId: 'APP-003',
      name: 'Container Image Signing and Verification',
      description:
        'All production container images signed with Cosign and verified at deployment time.',
      category: 'application_hardening',
      status: 'not_implemented',
      priority: 'high',
      owner: 'Sam Park',
      linkedAssets: ['aws-eks-prod-cluster', 'dev-k8s-cluster'],
      recommendedAction:
        'Implement Sigstore/Cosign image signing pipeline with OPA admission policy',
      dueDate: daysAgo(-45),
    },
    {
      controlId: 'APP-004',
      name: 'API Rate Limiting and Throttling',
      description: 'Request rate limiting on all public APIs to prevent brute force and DDoS.',
      category: 'application_hardening',
      status: 'implemented',
      priority: 'high',
      owner: 'Alex Chen',
      linkedAssets: ['prod-api-gateway-01', 'payment-api-v3'],
    },
    {
      controlId: 'APP-005',
      name: 'Secrets Management via HashiCorp Vault',
      description:
        'All application secrets retrieved from Vault at runtime; no hardcoded credentials.',
      category: 'application_hardening',
      status: 'partial',
      priority: 'critical',
      owner: 'Sarah Kim',
      linkedAssets: ['secrets-vault-prod', 'ci-cd-jenkins'],
      recommendedAction:
        'Migrate remaining 6 applications from .env files to Vault dynamic secrets',
      dueDate: daysAgo(-7),
    },
    {
      controlId: 'CFG-001',
      name: 'CIS Benchmark Hardening — Server OS',
      description:
        'All servers hardened to CIS Level 2 benchmark with automated compliance checking.',
      category: 'config_hardening',
      status: 'partial',
      priority: 'high',
      owner: 'Jordan Alvarez',
      linkedAssets: ['prod-api-gateway-01', 'legacy-fin-server-03', 'prod-kafka-cluster'],
      recommendedAction: 'Complete hardening on legacy-fin-server-03 and backup-storage-nas',
      dueDate: daysAgo(-30),
    },
    {
      controlId: 'CFG-002',
      name: 'Network Segmentation and Micro-segmentation',
      description:
        'Production, staging, and development environments isolated with firewall rules; micro-segmentation within prod.',
      category: 'config_hardening',
      status: 'implemented',
      priority: 'critical',
      owner: 'Riley Torres',
      linkedAssets: ['firewall-edge-01', 'zero-trust-gateway'],
      lastReviewedAt: daysAgo(21),
    },
    {
      controlId: 'CFG-003',
      name: 'Immutable Infrastructure Pattern',
      description: 'No SSH/RDP to production servers; changes deployed via CI/CD pipeline only.',
      category: 'config_hardening',
      status: 'partial',
      priority: 'high',
      owner: 'Sam Park',
      linkedAssets: ['prod-api-gateway-01', 'legacy-fin-server-03'],
      recommendedAction: 'Migrate legacy-fin-server-03 to immutable infrastructure pattern',
    },
    {
      controlId: 'CFG-004',
      name: 'Kubernetes RBAC Least Privilege',
      description:
        'K8s service accounts use namespace-scoped roles; no cluster-admin except for break-glass accounts.',
      category: 'config_hardening',
      status: 'implemented',
      priority: 'critical',
      owner: 'Jordan Alvarez',
      linkedAssets: ['aws-eks-prod-cluster', 'dev-k8s-cluster'],
      lastReviewedAt: daysAgo(5),
      auditTrail: [
        {
          action: 'Emergency remediation after incident INC-K8S-001',
          user: 'L. Nguyen',
          at: daysAgo(16).toISOString(),
        },
      ],
    },
    {
      controlId: 'CFG-005',
      name: 'TLS 1.3 Enforcement on All Services',
      description:
        'TLS 1.0 and 1.1 disabled; TLS 1.2 deprecated; TLS 1.3 enforced where supported.',
      category: 'config_hardening',
      status: 'not_implemented',
      priority: 'medium',
      owner: 'Riley Torres',
      linkedAssets: ['prod-api-gateway-01', 'legacy-fin-server-03', 'prod-kafka-cluster'],
      recommendedAction:
        'Audit all service TLS configurations; enforce TLS 1.3 via nginx/HAProxy config',
      dueDate: daysAgo(-60),
    },
    {
      controlId: 'DEP-001',
      name: 'Software Bill of Materials (SBOM) Generation',
      description: 'SBOM generated for all production services and stored in artifact registry.',
      category: 'dependency_supply_chain',
      status: 'not_implemented',
      priority: 'high',
      owner: 'Sam Park',
      linkedAssets: ['ci-cd-jenkins', 'prod-api-gateway-01'],
      recommendedAction:
        'Integrate syft/grype into CI pipeline for SBOM generation and vulnerability scanning',
      dueDate: daysAgo(-45),
    },
    {
      controlId: 'DEP-002',
      name: 'Automated Dependency Vulnerability Scanning',
      description:
        'Dependabot or Renovate enabled on all repositories with auto-PR for security patches.',
      category: 'dependency_supply_chain',
      status: 'implemented',
      priority: 'critical',
      owner: 'Sam Park',
      linkedAssets: ['ci-cd-jenkins'],
      lastReviewedAt: daysAgo(1),
    },
    {
      controlId: 'DEP-003',
      name: 'Private Package Mirror and Supply Chain Controls',
      description:
        'All packages sourced from internal mirror; no direct internet package downloads in production builds.',
      category: 'dependency_supply_chain',
      status: 'partial',
      priority: 'high',
      owner: 'Sam Park',
      recommendedAction: 'Migrate Python and Ruby package installs to internal Artifactory mirror',
      dueDate: daysAgo(-30),
    },
    {
      controlId: 'DEP-004',
      name: 'Vendor Security Assessment Program',
      description:
        'Third-party vendors assessed against security questionnaire before integration; annual re-assessment.',
      category: 'dependency_supply_chain',
      status: 'partial',
      priority: 'medium',
      owner: 'Morgan Lee',
      recommendedAction: 'Complete assessments for 12 vendors added in last 6 months',
    },
    {
      controlId: 'VA-001',
      name: 'Continuous External Attack Surface Monitoring',
      description:
        'ASM tool monitors external attack surface 24/7 with real-time alerting on new exposures.',
      category: 'vulnerability_assessment',
      status: 'implemented',
      priority: 'critical',
      owner: 'Sarah Kim',
      linkedAssets: ['prod-api-gateway-01', 'corporate-vpn-gateway', 'web-app-frontend'],
      lastReviewedAt: daysAgo(1),
    },
    {
      controlId: 'VA-002',
      name: 'Weekly Authenticated Vulnerability Scanning',
      description:
        'Internal authenticated vulnerability scans run weekly across all production assets.',
      category: 'vulnerability_assessment',
      status: 'implemented',
      priority: 'critical',
      owner: 'Marcus Webb',
      lastReviewedAt: daysAgo(3),
    },
    {
      controlId: 'VA-003',
      name: 'Quarterly Penetration Testing',
      description:
        'Manual penetration testing by qualified external assessor on a quarterly schedule.',
      category: 'vulnerability_assessment',
      status: 'partial',
      priority: 'high',
      owner: 'Morgan Lee',
      recommendedAction:
        'Complete Q1 2026 pentest scope definition; issue RFP to qualified vendors',
      dueDate: daysAgo(-14),
    },
    {
      controlId: 'VA-004',
      name: 'Patch SLA Enforcement — Critical 24h, High 7d',
      description:
        'Critical vulnerabilities patched within 24 hours; high within 7 days. SLA tracked in ticketing system.',
      category: 'vulnerability_assessment',
      status: 'partial',
      priority: 'critical',
      owner: 'Marcus Webb',
      recommendedAction: '3 critical vulnerabilities exceed SLA — escalate to CISO immediately',
      dueDate: daysAgo(-3),
      auditTrail: [
        {
          action: 'SLA breach detected on 3 critical CVEs',
          user: 'Automation',
          at: daysAgo(1).toISOString(),
        },
      ],
    },
  ]);

  await db.insert(firestormComplianceControlsTable).values([
    {
      framework: 'nist_csf',
      category: 'Identify (ID)',
      controlId: 'ID.AM-1',
      controlName: 'Physical devices and systems inventoried',
      description: 'Physical devices and systems within the organization are inventoried.',
      status: 'implemented',
      owner: 'Jordan Alvarez',
      evidenceNotes: '200+ assets tracked in Aegis Asset Inventory with automated discovery',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'nist_csf',
      category: 'Identify (ID)',
      controlId: 'ID.AM-2',
      controlName: 'Software platforms and applications inventoried',
      description: 'Software platforms and applications within the organization are inventoried.',
      status: 'implemented',
      owner: 'Sam Park',
      evidenceNotes: 'SBOM generation in CI/CD; Software asset management in CMDB',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'nist_csf',
      category: 'Identify (ID)',
      controlId: 'ID.AM-6',
      controlName: 'Cybersecurity roles and responsibilities established',
      description:
        'Cybersecurity roles and responsibilities for the entire workforce are established.',
      status: 'implemented',
      owner: 'Sarah Kim',
      evidenceNotes: 'RACI matrix documented; Security handbook published',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Identify (ID)',
      controlId: 'ID.RA-1',
      controlName: 'Asset vulnerabilities identified and documented',
      description: 'Asset vulnerabilities are identified and documented.',
      status: 'implemented',
      owner: 'Marcus Webb',
      evidenceNotes: 'Continuous vulnerability scanning with 100+ findings tracked in Aegis',
      lastAssessedAt: daysAgo(1),
    },
    {
      framework: 'nist_csf',
      category: 'Identify (ID)',
      controlId: 'ID.RA-5',
      controlName: 'Threats, vulnerabilities, likelihoods, impacts used to determine risk',
      description: 'Threats, vulnerabilities, likelihoods, and impacts are used to determine risk.',
      status: 'partial',
      owner: 'Morgan Lee',
      evidenceNotes: 'Risk scoring methodology defined; quantitative impact analysis pending',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Identify (ID)',
      controlId: 'ID.GV-1',
      controlName: 'Organizational cybersecurity policy established',
      description: 'Organizational cybersecurity policy is established and communicated.',
      status: 'implemented',
      owner: 'Sarah Kim',
      evidenceNotes: 'Information Security Policy v3.2 approved by Board; published on intranet',
      lastAssessedAt: daysAgo(30),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.AC-1',
      controlName: 'Identities and credentials managed for authorized devices and users',
      description:
        'Identities and credentials are issued, managed, verified, revoked, and audited for authorized devices, users and processes.',
      status: 'implemented',
      owner: 'Sarah Kim',
      evidenceNotes: 'Active Directory + Okta IDP; automated provisioning/deprovisioning',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.AC-3',
      controlName: 'Remote access managed',
      description: 'Remote access is managed.',
      status: 'implemented',
      owner: 'Riley Torres',
      evidenceNotes: 'Zero trust VPN with MFA; network access control via NAC',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.AC-4',
      controlName: 'Access permissions managed',
      description:
        'Access permissions and authorizations are managed, incorporating the principles of least privilege and separation of duties.',
      status: 'partial',
      owner: 'Morgan Lee',
      evidenceNotes: 'Role-based access implemented; PAM deployment 60% complete',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.AT-1',
      controlName: 'Workforce trained in cybersecurity',
      description: 'All users are informed and trained.',
      status: 'implemented',
      owner: 'Morgan Lee',
      evidenceNotes: 'Annual security awareness training; phishing simulation quarterly',
      lastAssessedAt: daysAgo(30),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.DS-1',
      controlName: 'Data-at-rest protected',
      description: 'Data-at-rest is protected.',
      status: 'partial',
      owner: 'Marcus Webb',
      evidenceNotes: 'Production DB encrypted; legacy-fin-server-03 remediation in progress',
      lastAssessedAt: daysAgo(5),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.DS-2',
      controlName: 'Data-in-transit protected',
      description: 'Data-in-transit is protected.',
      status: 'partial',
      owner: 'Riley Torres',
      evidenceNotes: 'TLS on most services; Kafka cluster plaintext comm under remediation',
      lastAssessedAt: daysAgo(5),
    },
    {
      framework: 'nist_csf',
      category: 'Protect (PR)',
      controlId: 'PR.IP-1',
      controlName: 'Baseline configuration established',
      description:
        'A baseline configuration of information technology/industrial control systems is created and maintained.',
      status: 'partial',
      owner: 'Jordan Alvarez',
      evidenceNotes: 'CIS hardened images for cloud; legacy servers pending',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Detect (DE)',
      controlId: 'DE.CM-1',
      controlName: 'Network monitored to detect potential cybersecurity events',
      description: 'The network is monitored to detect potential cybersecurity events.',
      status: 'implemented',
      owner: 'Sarah Kim',
      evidenceNotes: 'Palo Alto NGFW + IDS; Zscaler cloud proxy; network behavioral analytics',
      lastAssessedAt: daysAgo(1),
    },
    {
      framework: 'nist_csf',
      category: 'Detect (DE)',
      controlId: 'DE.CM-3',
      controlName: 'Personnel activity monitored to detect potential cybersecurity events',
      description: 'Personnel activity is monitored to detect potential cybersecurity events.',
      status: 'implemented',
      owner: 'Sarah Kim',
      evidenceNotes: 'UEBA via Microsoft Sentinel; DLP monitoring all endpoints and cloud',
      lastAssessedAt: daysAgo(3),
    },
    {
      framework: 'nist_csf',
      category: 'Detect (DE)',
      controlId: 'DE.CM-7',
      controlName:
        'Monitoring for unauthorized personnel, connections, devices, and software performed',
      description:
        'Monitoring for unauthorized personnel, connections, devices, and software is performed.',
      status: 'implemented',
      owner: 'Riley Torres',
      evidenceNotes: 'NAC, MDM enrollment required; rogue device detection active',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'nist_csf',
      category: 'Detect (DE)',
      controlId: 'DE.AE-2',
      controlName: 'Detected events analyzed to understand attack targets and methods',
      description: 'Detected events are analyzed to understand attack targets and methods.',
      status: 'partial',
      owner: 'J. Chen',
      evidenceNotes: 'SIEM correlation rules active; manual triage required for complex chains',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'nist_csf',
      category: 'Detect (DE)',
      controlId: 'DE.AE-5',
      controlName: 'Incident alert thresholds established',
      description: 'Incident alert thresholds are established.',
      status: 'implemented',
      owner: 'Sarah Kim',
      evidenceNotes: 'Alert thresholds reviewed quarterly; severity matrix aligned with CVSS',
      lastAssessedAt: daysAgo(30),
    },
    {
      framework: 'nist_csf',
      category: 'Respond (RS)',
      controlId: 'RS.RP-1',
      controlName: 'Response plan executed during or after incident',
      description: 'Response plan is executed during or after an incident.',
      status: 'implemented',
      owner: 'J. Chen',
      evidenceNotes: 'IRP v4.2 maintained; tabletop exercise completed Q4 2025',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Respond (RS)',
      controlId: 'RS.CO-2',
      controlName: 'Incidents reported consistent with established criteria',
      description: 'Incidents are reported consistent with established criteria.',
      status: 'implemented',
      owner: 'J. Chen',
      evidenceNotes:
        'SIEM-to-ticketing integration; mandatory escalation for critical/high severity',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'nist_csf',
      category: 'Respond (RS)',
      controlId: 'RS.AN-1',
      controlName: 'Notifications from detection systems investigated',
      description: 'Notifications from detection systems are investigated.',
      status: 'implemented',
      owner: 'J. Chen',
      evidenceNotes: '24/7 SOC coverage; SLA: P1 15min, P2 1hr, P3 4hr response',
      lastAssessedAt: daysAgo(1),
    },
    {
      framework: 'nist_csf',
      category: 'Respond (RS)',
      controlId: 'RS.MI-1',
      controlName: 'Incidents contained',
      description: 'Incidents are contained.',
      status: 'implemented',
      owner: 'J. Chen',
      evidenceNotes: 'Automated containment playbooks for known attack patterns',
      lastAssessedAt: daysAgo(3),
    },
    {
      framework: 'nist_csf',
      category: 'Recover (RC)',
      controlId: 'RC.RP-1',
      controlName: 'Recovery plan executed during or after incident',
      description: 'Recovery plan is executed during or after a cybersecurity incident.',
      status: 'implemented',
      owner: 'Jordan Alvarez',
      evidenceNotes: 'BCP/DR plan tested annually; RTO 4h, RPO 1h for Tier 1 systems',
      lastAssessedAt: daysAgo(60),
    },
    {
      framework: 'nist_csf',
      category: 'Recover (RC)',
      controlId: 'RC.IM-1',
      controlName: 'Recovery plans incorporate lessons learned',
      description: 'Recovery plans incorporate lessons learned.',
      status: 'partial',
      owner: 'J. Chen',
      evidenceNotes: 'PIR process defined; 3 of 5 recent incidents have completed PIRs',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'nist_csf',
      category: 'Recover (RC)',
      controlId: 'RC.CO-1',
      controlName: 'Public relations managed',
      description: 'Public relations are managed.',
      status: 'not_implemented',
      owner: undefined,
      evidenceNotes: 'Communications playbook not yet finalized for cyber incidents',
      lastAssessedAt: daysAgo(30),
    },

    {
      framework: 'fedramp',
      category: 'Access Control (AC)',
      controlId: 'AC-1',
      controlName: 'Access Control Policy and Procedures',
      description: 'Develop, document, and disseminate access control policy and procedures.',
      status: 'implemented',
      owner: 'Sarah Kim',
      lastAssessedAt: daysAgo(30),
    },
    {
      framework: 'fedramp',
      category: 'Access Control (AC)',
      controlId: 'AC-2',
      controlName: 'Account Management',
      description:
        'Manage information system accounts, including establishing, activating, modifying, reviewing, disabling, and removing accounts.',
      status: 'implemented',
      owner: 'Sarah Kim',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'fedramp',
      category: 'Access Control (AC)',
      controlId: 'AC-6',
      controlName: 'Least Privilege',
      description:
        'Employ the concept of least privilege, allowing only authorized accesses required to accomplish assigned tasks.',
      status: 'partial',
      owner: 'Morgan Lee',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'fedramp',
      category: 'Audit and Accountability (AU)',
      controlId: 'AU-2',
      controlName: 'Audit Events',
      description:
        'Identify the types of events that the system is capable of logging in support of the audit function.',
      status: 'implemented',
      owner: 'Sarah Kim',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'fedramp',
      category: 'Audit and Accountability (AU)',
      controlId: 'AU-12',
      controlName: 'Audit Record Generation',
      description:
        'Allow designated organizational personnel to select which auditable events are to be logged.',
      status: 'implemented',
      owner: 'Sarah Kim',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'fedramp',
      category: 'Configuration Management (CM)',
      controlId: 'CM-2',
      controlName: 'Baseline Configuration',
      description:
        'Develop, document, and maintain under configuration control, a current baseline configuration of the information system.',
      status: 'partial',
      owner: 'Jordan Alvarez',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'fedramp',
      category: 'Incident Response (IR)',
      controlId: 'IR-1',
      controlName: 'Incident Response Policy and Procedures',
      description: 'Develop, document, and disseminate incident response policy and procedures.',
      status: 'implemented',
      owner: 'J. Chen',
      lastAssessedAt: daysAgo(30),
    },
    {
      framework: 'fedramp',
      category: 'Incident Response (IR)',
      controlId: 'IR-4',
      controlName: 'Incident Handling',
      description: 'Implement an incident handling capability for security incidents.',
      status: 'implemented',
      owner: 'J. Chen',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'fedramp',
      category: 'Risk Assessment (RA)',
      controlId: 'RA-5',
      controlName: 'Vulnerability Scanning',
      description: 'Scan for vulnerabilities in the information system and hosted applications.',
      status: 'implemented',
      owner: 'Marcus Webb',
      lastAssessedAt: daysAgo(1),
    },

    {
      framework: 'fisma',
      category: 'Risk Management (RM)',
      controlId: 'RM-1',
      controlName: 'Risk Management Strategy',
      description: 'Develop a comprehensive strategy for managing information security risk.',
      status: 'implemented',
      owner: 'Morgan Lee',
      lastAssessedAt: daysAgo(30),
    },
    {
      framework: 'fisma',
      category: 'Risk Management (RM)',
      controlId: 'RM-2',
      controlName: 'Risk Assessment',
      description: 'Conduct a thorough assessment of risk to organizational operations.',
      status: 'partial',
      owner: 'Marcus Webb',
      lastAssessedAt: daysAgo(14),
    },
    {
      framework: 'fisma',
      category: 'Security Assessment (CA)',
      controlId: 'CA-2',
      controlName: 'Security Assessments',
      description: 'Develop a security assessment plan; assess security controls.',
      status: 'implemented',
      owner: 'Morgan Lee',
      lastAssessedAt: daysAgo(10),
    },
    {
      framework: 'fisma',
      category: 'System and Communications (SC)',
      controlId: 'SC-7',
      controlName: 'Boundary Protection',
      description:
        'Monitor and control communications at the external boundary and key internal boundaries.',
      status: 'implemented',
      owner: 'Riley Torres',
      lastAssessedAt: daysAgo(7),
    },
    {
      framework: 'fisma',
      category: 'System and Information Integrity (SI)',
      controlId: 'SI-2',
      controlName: 'Flaw Remediation',
      description: 'Identify, report, and correct information system flaws; test software updates.',
      status: 'partial',
      owner: 'Marcus Webb',
      evidenceNotes: '3 critical CVEs past SLA — remediation in progress',
      lastAssessedAt: daysAgo(3),
    },
    {
      framework: 'fisma',
      category: 'System and Information Integrity (SI)',
      controlId: 'SI-3',
      controlName: 'Malicious Code Protection',
      description: 'Employ malicious code protection mechanisms at appropriate locations.',
      status: 'implemented',
      owner: 'Riley Torres',
      lastAssessedAt: daysAgo(7),
    },
  ]);

  await db.insert(firestormMitreDetectionsTable).values([
    {
      techniqueId: 'T1566.001',
      techniqueName: 'Spearphishing Attachment',
      tactic: 'Initial Access',
      detectionCount: 14,
      incidentCount: 2,
      lastDetectedAt: daysAgo(12),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1190',
      techniqueName: 'Exploit Public-Facing Application',
      tactic: 'Initial Access',
      detectionCount: 5,
      incidentCount: 1,
      lastDetectedAt: daysAgo(3),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1133',
      techniqueName: 'External Remote Services',
      tactic: 'Initial Access',
      detectionCount: 8,
      incidentCount: 1,
      lastDetectedAt: daysAgo(9),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1078',
      techniqueName: 'Valid Accounts',
      tactic: 'Initial Access',
      detectionCount: 11,
      incidentCount: 3,
      lastDetectedAt: daysAgo(6),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1195.002',
      techniqueName: 'Compromise Software Supply Chain',
      tactic: 'Initial Access',
      detectionCount: 1,
      incidentCount: 1,
      lastDetectedAt: hoursAgo(2),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1059.001',
      techniqueName: 'PowerShell',
      tactic: 'Execution',
      detectionCount: 22,
      incidentCount: 4,
      lastDetectedAt: daysAgo(1),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1059.003',
      techniqueName: 'Windows Command Shell',
      tactic: 'Execution',
      detectionCount: 11,
      incidentCount: 2,
      lastDetectedAt: daysAgo(2),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1204',
      techniqueName: 'User Execution',
      tactic: 'Execution',
      detectionCount: 7,
      incidentCount: 1,
      lastDetectedAt: daysAgo(12),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1047',
      techniqueName: 'Windows Management Instrumentation',
      tactic: 'Execution',
      detectionCount: 4,
      incidentCount: 0,
      lastDetectedAt: daysAgo(5),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1053',
      techniqueName: 'Scheduled Task/Job',
      tactic: 'Persistence',
      detectionCount: 4,
      incidentCount: 0,
      lastDetectedAt: daysAgo(15),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1505.003',
      techniqueName: 'Web Shell',
      tactic: 'Persistence',
      detectionCount: 1,
      incidentCount: 1,
      lastDetectedAt: daysAgo(3),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1547',
      techniqueName: 'Boot or Logon Autostart Execution',
      tactic: 'Persistence',
      detectionCount: 2,
      incidentCount: 0,
      lastDetectedAt: daysAgo(20),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1078.004',
      techniqueName: 'Cloud Accounts',
      tactic: 'Privilege Escalation',
      detectionCount: 5,
      incidentCount: 2,
      lastDetectedAt: daysAgo(20),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1548',
      techniqueName: 'Abuse Elevation Control Mechanism',
      tactic: 'Privilege Escalation',
      detectionCount: 3,
      incidentCount: 0,
      lastDetectedAt: daysAgo(8),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1055',
      techniqueName: 'Process Injection',
      tactic: 'Defense Evasion',
      detectionCount: 8,
      incidentCount: 2,
      lastDetectedAt: daysAgo(7),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1027',
      techniqueName: 'Obfuscated Files or Information',
      tactic: 'Defense Evasion',
      detectionCount: 18,
      incidentCount: 3,
      lastDetectedAt: daysAgo(4),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1036',
      techniqueName: 'Masquerading',
      tactic: 'Defense Evasion',
      detectionCount: 12,
      incidentCount: 2,
      lastDetectedAt: daysAgo(6),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1562',
      techniqueName: 'Impair Defenses',
      tactic: 'Defense Evasion',
      detectionCount: 3,
      incidentCount: 0,
      lastDetectedAt: daysAgo(14),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1003.001',
      techniqueName: 'LSASS Memory',
      tactic: 'Credential Access',
      detectionCount: 9,
      incidentCount: 1,
      lastDetectedAt: daysAgo(7),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1110.001',
      techniqueName: 'Password Guessing',
      tactic: 'Credential Access',
      detectionCount: 15,
      incidentCount: 1,
      lastDetectedAt: daysAgo(4),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1110.003',
      techniqueName: 'Password Spraying',
      tactic: 'Credential Access',
      detectionCount: 4,
      incidentCount: 0,
      lastDetectedAt: daysAgo(10),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1087',
      techniqueName: 'Account Discovery',
      tactic: 'Discovery',
      detectionCount: 13,
      incidentCount: 2,
      lastDetectedAt: daysAgo(3),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1046',
      techniqueName: 'Network Service Discovery',
      tactic: 'Discovery',
      detectionCount: 20,
      incidentCount: 3,
      lastDetectedAt: daysAgo(2),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1082',
      techniqueName: 'System Information Discovery',
      tactic: 'Discovery',
      detectionCount: 11,
      incidentCount: 2,
      lastDetectedAt: daysAgo(5),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1021.002',
      techniqueName: 'SMB/Windows Admin Shares',
      tactic: 'Lateral Movement',
      detectionCount: 8,
      incidentCount: 1,
      lastDetectedAt: daysAgo(2),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1550',
      techniqueName: 'Use Alternate Authentication Material',
      tactic: 'Lateral Movement',
      detectionCount: 5,
      incidentCount: 1,
      lastDetectedAt: daysAgo(7),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1005',
      techniqueName: 'Data from Local System',
      tactic: 'Collection',
      detectionCount: 7,
      incidentCount: 2,
      lastDetectedAt: daysAgo(8),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1074',
      techniqueName: 'Data Staged',
      tactic: 'Collection',
      detectionCount: 4,
      incidentCount: 1,
      lastDetectedAt: daysAgo(15),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1071.001',
      techniqueName: 'Web Protocols (C2)',
      tactic: 'Command and Control',
      detectionCount: 12,
      incidentCount: 2,
      lastDetectedAt: daysAgo(3),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1573',
      techniqueName: 'Encrypted Channel',
      tactic: 'Command and Control',
      detectionCount: 9,
      incidentCount: 1,
      lastDetectedAt: daysAgo(5),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1048.001',
      techniqueName: 'Exfiltration Over DNS',
      tactic: 'Exfiltration',
      detectionCount: 5,
      incidentCount: 1,
      lastDetectedAt: daysAgo(15),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1567.002',
      techniqueName: 'Exfiltration to Cloud Storage',
      tactic: 'Exfiltration',
      detectionCount: 4,
      incidentCount: 1,
      lastDetectedAt: hoursAgo(6),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1486',
      techniqueName: 'Data Encrypted for Impact',
      tactic: 'Impact',
      detectionCount: 3,
      incidentCount: 1,
      lastDetectedAt: daysAgo(5),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1490',
      techniqueName: 'Inhibit System Recovery',
      tactic: 'Impact',
      detectionCount: 2,
      incidentCount: 1,
      lastDetectedAt: daysAgo(5),
      coverageStatus: 'detected',
    },
    {
      techniqueId: 'T1189',
      techniqueName: 'Drive-by Compromise',
      tactic: 'Initial Access',
      detectionCount: 0,
      incidentCount: 0,
      lastDetectedAt: undefined,
      coverageStatus: 'not_covered',
    },
    {
      techniqueId: 'T1611',
      techniqueName: 'Escape to Host',
      tactic: 'Privilege Escalation',
      detectionCount: 2,
      incidentCount: 0,
      lastDetectedAt: daysAgo(12),
      coverageStatus: 'partial',
    },
    {
      techniqueId: 'T1070',
      techniqueName: 'Indicator Removal',
      tactic: 'Defense Evasion',
      detectionCount: 5,
      incidentCount: 1,
      lastDetectedAt: daysAgo(3),
      coverageStatus: 'partial',
    },
  ]);

  const incidentIds = incidents.slice(0, 14).map((i) => i.id);
  const findingIds = findings.slice(0, 20).map((f) => f.id);

  await db.insert(firestormCasesTable).values([
    {
      caseNumber: 'CASE-2026-001',
      title: 'APT29 Campaign — DC-PROD-03 Lateral Movement',
      description:
        'Active APT29 campaign involving lateral movement to domain controller and C2 beaconing. Linked to incidents INC-001 and INC-002.',
      status: 'in_progress',
      priority: 'p1_critical',
      assignedAnalyst: 'J. Chen',
      relatedIncidentIds: [incidentIds[0], incidentIds[1]],
      slaTriage: 15,
      slaResolve: 240,
      triagedAt: daysAgo(1.9),
      notes: [
        {
          content: 'Initial triage complete. Isolating affected hosts.',
          author: 'J. Chen',
          at: daysAgo(1.9).toISOString(),
        },
        {
          content: 'Forensic image captured from WORKSTATION-142.',
          author: 'J. Chen',
          at: daysAgo(1.5).toISOString(),
        },
      ],
      evidence: [
        {
          name: 'WORKSTATION-142 memory dump',
          type: 'forensic',
          addedAt: daysAgo(1.5).toISOString(),
        },
        { name: 'Network PCAP — C2 traffic', type: 'pcap', addedAt: daysAgo(1.4).toISOString() },
      ],
      auditTrail: [
        { action: 'Case created from INC-001', user: 'System', at: daysAgo(2).toISOString() },
        { action: 'Linked INC-002', user: 'J. Chen', at: daysAgo(1.9).toISOString() },
        { action: 'Escalated to P1', user: 'J. Chen', at: daysAgo(1.8).toISOString() },
      ],
    },
    {
      caseNumber: 'CASE-2026-002',
      title: 'Ransomware Precursor — FILE-SRV-02',
      description:
        'Ransomware preparation activities detected including shadow copy deletion and file encryption attempt. Contained and remediation in progress.',
      status: 'pending_review',
      priority: 'p1_critical',
      assignedAnalyst: 'S. Park',
      relatedIncidentIds: [incidentIds[2]],
      slaTriage: 15,
      slaResolve: 480,
      triagedAt: daysAgo(4.9),
      resolvedAt: daysAgo(1),
      notes: [
        {
          content: 'Ransomware confined to FILE-SRV-02. No propagation detected.',
          author: 'S. Park',
          at: daysAgo(4.7).toISOString(),
        },
      ],
      evidence: [
        {
          name: 'FILE-SRV-02 forensic image',
          type: 'forensic',
          addedAt: daysAgo(4.6).toISOString(),
        },
        {
          name: 'Malware sample analysis',
          type: 'malware_sample',
          addedAt: daysAgo(4).toISOString(),
        },
      ],
      auditTrail: [
        { action: 'Case created', user: 'System', at: daysAgo(5).toISOString() },
        { action: 'Containment achieved', user: 'S. Park', at: daysAgo(4.7).toISOString() },
        {
          action: 'Pending security review sign-off',
          user: 'S. Park',
          at: daysAgo(1).toISOString(),
        },
      ],
    },
    {
      caseNumber: 'CASE-2026-003',
      title: 'Data Exfiltration — External S3 Bucket Transfer',
      description:
        '2.3GB unauthorized data transfer to external AWS S3 bucket. Data classification and ownership investigation ongoing.',
      status: 'in_progress',
      priority: 'p2_high',
      assignedAnalyst: 'R. Davis',
      relatedIncidentIds: [incidentIds[5]],
      relatedFindingIds: [findingIds[7]],
      slaTriage: 60,
      slaResolve: 1440,
      triagedAt: hoursAgo(5),
      notes: [
        {
          content: 'Bucket identified as owned by external party. OSINT research started.',
          author: 'R. Davis',
          at: hoursAgo(4.5).toISOString(),
        },
      ],
      auditTrail: [
        { action: 'Case opened from DLP alert', user: 'System', at: hoursAgo(6).toISOString() },
        {
          action: 'Triaged — data classification in progress',
          user: 'R. Davis',
          at: hoursAgo(5).toISOString(),
        },
      ],
    },
    {
      caseNumber: 'CASE-2026-004',
      title: 'Insider Threat — Bulk Customer Data Export',
      description:
        'Departing employee exported 15,000 customer records to personal cloud storage. Legal review and forensics required.',
      status: 'in_progress',
      priority: 'p2_high',
      assignedAnalyst: 'K. Wilson',
      relatedIncidentIds: [incidentIds[11]],
      slaTriage: 60,
      slaResolve: 2880,
      triagedAt: daysAgo(7.8),
      notes: [
        {
          content: 'Legal hold placed on employee device and accounts.',
          author: 'K. Wilson',
          at: daysAgo(7.8).toISOString(),
        },
        {
          content: 'Coordinating with HR and Legal for next steps.',
          author: 'K. Wilson',
          at: daysAgo(7).toISOString(),
        },
      ],
      evidence: [
        { name: 'OneDrive activity logs', type: 'log', addedAt: daysAgo(7.5).toISOString() },
        { name: 'DLP policy match report', type: 'report', addedAt: daysAgo(7.4).toISOString() },
      ],
      auditTrail: [
        { action: 'DLP alert escalated to case', user: 'System', at: daysAgo(8).toISOString() },
        { action: 'HR notified', user: 'K. Wilson', at: daysAgo(7.9).toISOString() },
      ],
    },
    {
      caseNumber: 'CASE-2026-005',
      title: "Supply Chain Attack — npm Package 'colors-lite'",
      description:
        'Malicious code in npm package dependency affecting 3 production services. Scope of exposure being determined.',
      status: 'open',
      priority: 'p2_high',
      relatedIncidentIds: [incidentIds[8]],
      relatedFindingIds: [findingIds[3]],
      slaTriage: 60,
      slaResolve: 1440,
      auditTrail: [
        {
          action: 'Case auto-created from SAST alert',
          user: 'Automation',
          at: hoursAgo(2).toISOString(),
        },
      ],
    },
    {
      caseNumber: 'CASE-2026-006',
      title: 'Critical RCE — Palo Alto Firewall CVE-2024-3400',
      description:
        'Unpatched PAN-OS vulnerability with active exploitation in wild. Emergency patch and investigation required.',
      status: 'open',
      priority: 'p1_critical',
      relatedFindingIds: [findingIds[13]],
      slaTriage: 15,
      slaResolve: 120,
      auditTrail: [
        {
          action: 'Case created from CISA KEV alert',
          user: 'System',
          at: daysAgo(3).toISOString(),
        },
      ],
    },
    {
      caseNumber: 'CASE-2026-007',
      title: 'K8s Privilege Escalation via RBAC Misconfiguration',
      description:
        'Developer service account escalated to cluster-admin. Secrets potentially exposed. Post-incident review complete.',
      status: 'resolved',
      priority: 'p1_critical',
      assignedAnalyst: 'L. Nguyen',
      relatedIncidentIds: [incidentIds[13]],
      slaTriage: 15,
      slaResolve: 480,
      triagedAt: daysAgo(19.8),
      resolvedAt: daysAgo(16),
      notes: [
        {
          content: 'RBAC corrected. All cluster secrets rotated. No evidence of exfiltration.',
          author: 'L. Nguyen',
          at: daysAgo(16).toISOString(),
        },
      ],
      auditTrail: [
        { action: 'Escalated to P1', user: 'L. Nguyen', at: daysAgo(19.9).toISOString() },
        { action: 'Resolved — PIR complete', user: 'L. Nguyen', at: daysAgo(16).toISOString() },
      ],
    },
    {
      caseNumber: 'CASE-2026-008',
      title: 'OAuth Token Theft via Open Redirect',
      description:
        '24 user OAuth tokens compromised via open redirect vulnerability. All tokens revoked and patch deployed.',
      status: 'closed',
      priority: 'p2_high',
      assignedAnalyst: 'R. Davis',
      relatedIncidentIds: [incidentIds[14]],
      slaTriage: 60,
      slaResolve: 1440,
      triagedAt: daysAgo(24.8),
      resolvedAt: daysAgo(22),
      auditTrail: [
        { action: 'All tokens revoked', user: 'R. Davis', at: daysAgo(24.5).toISOString() },
        { action: 'Case closed — users notified', user: 'R. Davis', at: daysAgo(22).toISOString() },
      ],
    },
    {
      caseNumber: 'CASE-2026-009',
      title: 'Web Shell Persistence — DMZ Web Server',
      description:
        'PHP web shell active for 72+ hours on DMZ web server. Full forensic investigation and system rebuild required.',
      status: 'in_progress',
      priority: 'p1_critical',
      assignedAnalyst: 'S. Park',
      relatedIncidentIds: [incidentIds[10]],
      slaTriage: 15,
      slaResolve: 480,
      triagedAt: daysAgo(2.9),
      notes: [
        {
          content: 'Shell removed. Forensic analysis of attacker activity in progress.',
          author: 'S. Park',
          at: daysAgo(2.5).toISOString(),
        },
      ],
      auditTrail: [
        { action: 'Shell removed, host isolated', user: 'S. Park', at: daysAgo(2.5).toISOString() },
        {
          action: 'Forensic imaging started',
          user: 'Forensics Team',
          at: daysAgo(2.4).toISOString(),
        },
      ],
    },
    {
      caseNumber: 'CASE-2026-010',
      title: 'DNS Tunneling Exfiltration Campaign',
      description:
        'Multi-endpoint DNS tunneling detected. ~500MB estimated exfiltration over 72 hours. All 7 endpoints remediated.',
      status: 'closed',
      priority: 'p2_high',
      assignedAnalyst: 'A. Thompson',
      relatedIncidentIds: [incidentIds[12]],
      slaTriage: 60,
      slaResolve: 2880,
      triagedAt: daysAgo(14.8),
      resolvedAt: daysAgo(10),
      auditTrail: [
        { action: 'DNS blocking applied', user: 'A. Thompson', at: daysAgo(14).toISOString() },
        { action: 'All endpoints reimaged', user: 'IT Team', at: daysAgo(12).toISOString() },
        { action: 'Case closed', user: 'A. Thompson', at: daysAgo(10).toISOString() },
      ],
    },
  ]);

  return {
    assets: assets.length,
    findings: findings.length,
    incidents: incidents.length,
    alerts: alerts.length,
  };
}
