import type { CounterfactualDiff, PendingApproval, RunStage, SubstrateRun } from './types';

const now = Date.now();

export const MOCK_RUNS: SubstrateRun[] = [
  {
    id: 'run-vessels-001',
    workflow: 'Voyage P&L Optimization',
    vertical: 'vessels',
    tenant: 'Pacific Cargo Group',
    status: 'awaiting-approval',
    currentStage: 'policy',
    confidence: 0.88,
    policyStatus: 'pending',
    riskLevel: 'high',
    approver: 'elena.vasquez@szl.io',
    startedAt: new Date(now - 18 * 60_000).toISOString(),
    ageMs: 18 * 60_000,
    modelAdapter: 'gpt-4o',
    policyProfile: 'vessels-standard-v2',
    agentId: 'vessels-agent-01',
    objectiveText:
      'Optimize voyage routing to reduce fuel consumption by 12% while maintaining ETA within 6-hour window for Q2 contracts.',
    retriever: { source: 'synthetic', adapterId: null },
    stages: [
      {
        id: 's1',
        name: 'Signal Ingestion',
        kind: 'signal',
        status: 'completed',
        startedAt: new Date(now - 18 * 60_000).toISOString(),
        completedAt: new Date(now - 17 * 60_000).toISOString(),
        durationMs: 1200,
        confidence: 0.97,
        input: { aisData: '12 vessels', weather: 'live' },
        output: { signals: 47, anomalies: 3 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'span-001',
      },
      {
        id: 's2',
        name: 'Context Assembly',
        kind: 'context',
        status: 'completed',
        startedAt: new Date(now - 17 * 60_000).toISOString(),
        completedAt: new Date(now - 15 * 60_000).toISOString(),
        durationMs: 2100,
        confidence: 0.93,
        input: null,
        output: { contextTokens: 8200, entitiesResolved: 12 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [
          {
            refId: 'ev-001',
            source: 'AIS Feed',
            sourceType: 'sensor',
            content:
              'Vessel PACIFIC DAWN at 28.4°N 142.1°E, speed 14.2kn, heading 087°, ETA deviation +3.2h',
            relevanceScore: 0.94,
            timestamp: new Date(now - 16 * 60_000).toISOString(),
            citations: [
              {
                id: 'c1',
                text: 'Route efficiency index dropped 8.4% versus Q1 benchmark',
                confidence: 0.91,
              },
            ],
          },
        ],
        traceSpanId: 'span-002',
      },
      {
        id: 's3',
        name: 'Recommendation',
        kind: 'recommendation',
        status: 'completed',
        startedAt: new Date(now - 15 * 60_000).toISOString(),
        completedAt: new Date(now - 12 * 60_000).toISOString(),
        durationMs: 3400,
        confidence: 0.88,
        input: null,
        output: {
          recommendation:
            'Reroute via southern corridor, reducing fuel by 11.8% with ETA impact +1.4h',
        },
        redacted: false,
        policyResult: null,
        evidenceRefs: [
          {
            refId: 'ev-002',
            source: 'Route Optimizer',
            sourceType: 'agent',
            content:
              'Southern corridor shows 11.8% fuel reduction versus current heading; charter party deadline allows 4h margin',
            relevanceScore: 0.89,
            timestamp: new Date(now - 13 * 60_000).toISOString(),
            citations: [
              {
                id: 'c2',
                text: 'Charter party Article 14(b): ETA deviation < 6h does not trigger demurrage',
                confidence: 0.95,
              },
              {
                id: 'c3',
                text: 'Bunker price differential: $42/MT savings on 340MT consumption delta',
                confidence: 0.88,
              },
            ],
          },
        ],
        traceSpanId: 'span-003',
      },
      {
        id: 's4',
        name: 'Simulation',
        kind: 'simulation',
        status: 'completed',
        startedAt: new Date(now - 12 * 60_000).toISOString(),
        completedAt: new Date(now - 8 * 60_000).toISOString(),
        durationMs: 4100,
        confidence: 0.91,
        input: null,
        output: { scenarios: 3, bestCase: '11.8% savings', worstCase: '9.2% savings' },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'span-004',
      },
      {
        id: 's5',
        name: 'Policy Evaluation',
        kind: 'policy',
        status: 'running',
        startedAt: new Date(now - 8 * 60_000).toISOString(),
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: {
          policyId: 'pol-001',
          policyName: 'High-Risk Action Approval Gate',
          result: 'warn',
          blockedReason: 'Charter party amendment requires human approval (pol-001)',
          requiresApproval: true,
          violatedPolicies: ['pol-001'],
        },
        evidenceRefs: [],
        traceSpanId: 'span-005',
      },
      {
        id: 's6',
        name: 'Execution',
        kind: 'execution',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: true,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 's7',
        name: 'Proof Chain',
        kind: 'proof',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 's8',
        name: 'Outcome Recording',
        kind: 'outcome',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 's9',
        name: 'Learning Update',
        kind: 'learning',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
    ],
    approvalHistory: [],
    checkpoints: [
      {
        id: 'ckpt-001',
        runId: 'run-vessels-001',
        stageId: 's3',
        capturedAt: new Date(now - 12 * 60_000).toISOString(),
        worldStateHash: 'sha256:a4f92c1e8b3d',
        description: 'Post-recommendation state — vessel positions, charter terms, bunker prices',
        restorable: true,
      },
      {
        id: 'ckpt-002',
        runId: 'run-vessels-001',
        stageId: 's4',
        capturedAt: new Date(now - 8 * 60_000).toISOString(),
        worldStateHash: 'sha256:d7e81b2f0c5a',
        description: 'Post-simulation state — all scenario outputs captured',
        restorable: true,
      },
    ],
    traceSpans: [
      {
        spanId: 'span-001',
        parentSpanId: null,
        operationName: 'signal.ingest',
        service: 'vessels-agent',
        startTime: new Date(now - 18 * 60_000).toISOString(),
        durationMs: 1200,
        tags: { 'ais.count': '47', 'anomaly.count': '3' },
        status: 'ok',
      },
      {
        spanId: 'span-002',
        parentSpanId: 'span-001',
        operationName: 'context.assemble',
        service: 'context-builder',
        startTime: new Date(now - 17 * 60_000).toISOString(),
        durationMs: 2100,
        tags: { tokens: '8200', entities: '12' },
        status: 'ok',
      },
      {
        spanId: 'span-003',
        parentSpanId: 'span-002',
        operationName: 'recommendation.generate',
        service: 'gpt-4o-adapter',
        startTime: new Date(now - 15 * 60_000).toISOString(),
        durationMs: 3400,
        tags: { model: 'gpt-4o', confidence: '0.88' },
        status: 'ok',
      },
      {
        spanId: 'span-004',
        parentSpanId: 'span-003',
        operationName: 'simulation.run',
        service: 'sim-engine',
        startTime: new Date(now - 12 * 60_000).toISOString(),
        durationMs: 4100,
        tags: { scenarios: '3' },
        status: 'ok',
      },
      {
        spanId: 'span-005',
        parentSpanId: 'span-004',
        operationName: 'policy.evaluate',
        service: 'policy-engine',
        startTime: new Date(now - 8 * 60_000).toISOString(),
        durationMs: 480000,
        tags: { policy: 'pol-001', status: 'awaiting' },
        status: 'unset',
      },
    ],
  },
  {
    id: 'run-terra-001',
    workflow: 'Distressed Asset Acquisition',
    vertical: 'terra',
    tenant: 'Meridian Capital',
    status: 'running',
    currentStage: 'simulation',
    confidence: 0.76,
    policyStatus: 'compliant',
    riskLevel: 'medium',
    approver: null,
    startedAt: new Date(now - 7 * 60_000).toISOString(),
    ageMs: 7 * 60_000,
    modelAdapter: 'claude-3-5-sonnet',
    policyProfile: 'terra-conservative-v1',
    agentId: 'terra-agent-02',
    objectiveText:
      'Evaluate and recommend acquisition strategy for 3 distressed commercial properties in Phoenix metro, targeting 18% IRR.',
    retriever: { source: 'synthetic', adapterId: null },
    stages: [
      {
        id: 'ts1',
        name: 'Signal Ingestion',
        kind: 'signal',
        status: 'completed',
        startedAt: new Date(now - 7 * 60_000).toISOString(),
        completedAt: new Date(now - 6.5 * 60_000).toISOString(),
        durationMs: 900,
        confidence: 0.99,
        input: null,
        output: { properties: 3, signals: 28 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'tspan-001',
      },
      {
        id: 'ts2',
        name: 'Context Assembly',
        kind: 'context',
        status: 'completed',
        startedAt: new Date(now - 6.5 * 60_000).toISOString(),
        completedAt: new Date(now - 5 * 60_000).toISOString(),
        durationMs: 1800,
        confidence: 0.95,
        input: null,
        output: { contextTokens: 6100 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'tspan-002',
      },
      {
        id: 'ts3',
        name: 'Recommendation',
        kind: 'recommendation',
        status: 'completed',
        startedAt: new Date(now - 5 * 60_000).toISOString(),
        completedAt: new Date(now - 3 * 60_000).toISOString(),
        durationMs: 2200,
        confidence: 0.76,
        input: null,
        output: {
          recommendation: 'Acquire 2825 N 44th St at $4.2M; defer others pending market correction',
        },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'tspan-003',
      },
      {
        id: 'ts4',
        name: 'Simulation',
        kind: 'simulation',
        status: 'running',
        startedAt: new Date(now - 3 * 60_000).toISOString(),
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'tspan-004',
      },
      {
        id: 'ts5',
        name: 'Policy Evaluation',
        kind: 'policy',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 'ts6',
        name: 'Execution',
        kind: 'execution',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: true,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 'ts7',
        name: 'Proof Chain',
        kind: 'proof',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 'ts8',
        name: 'Outcome Recording',
        kind: 'outcome',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 'ts9',
        name: 'Learning Update',
        kind: 'learning',
        status: 'pending',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
    ],
    approvalHistory: [],
    checkpoints: [],
    traceSpans: [],
  },
  {
    id: 'run-alloy-001',
    workflow: 'Cross-Domain Risk Correlation',
    vertical: 'alloy',
    tenant: 'SZL Holdings',
    status: 'completed',
    currentStage: 'learning',
    confidence: 0.94,
    policyStatus: 'compliant',
    riskLevel: 'low',
    approver: null,
    startedAt: new Date(now - 45 * 60_000).toISOString(),
    ageMs: 45 * 60_000,
    modelAdapter: 'gpt-4o-mini',
    policyProfile: 'alloy-orchestrator-v3',
    agentId: 'alloy-orchestrator',
    objectiveText:
      'Correlate cross-domain risk signals from SEXTANT, DOMAINE, and PRISM to produce unified executive risk posture report.',
    retriever: { source: 'synthetic', adapterId: null },
    stages: [
      {
        id: 'as1',
        name: 'Signal Ingestion',
        kind: 'signal',
        status: 'completed',
        startedAt: new Date(now - 45 * 60_000).toISOString(),
        completedAt: new Date(now - 44 * 60_000).toISOString(),
        durationMs: 820,
        confidence: 0.99,
        input: null,
        output: { domains: 3, signals: 84 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-001',
      },
      {
        id: 'as2',
        name: 'Context Assembly',
        kind: 'context',
        status: 'completed',
        startedAt: new Date(now - 44 * 60_000).toISOString(),
        completedAt: new Date(now - 42 * 60_000).toISOString(),
        durationMs: 1600,
        confidence: 0.97,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-002',
      },
      {
        id: 'as3',
        name: 'Recommendation',
        kind: 'recommendation',
        status: 'completed',
        startedAt: new Date(now - 42 * 60_000).toISOString(),
        completedAt: new Date(now - 38 * 60_000).toISOString(),
        durationMs: 2800,
        confidence: 0.94,
        input: null,
        output: {
          recommendation:
            'Moderate overall risk posture; SEXTANT exposure elevated by 12% vs baseline',
        },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-003',
      },
      {
        id: 'as4',
        name: 'Simulation',
        kind: 'simulation',
        status: 'completed',
        startedAt: new Date(now - 38 * 60_000).toISOString(),
        completedAt: new Date(now - 34 * 60_000).toISOString(),
        durationMs: 3900,
        confidence: 0.96,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-004',
      },
      {
        id: 'as5',
        name: 'Policy Evaluation',
        kind: 'policy',
        status: 'completed',
        startedAt: new Date(now - 34 * 60_000).toISOString(),
        completedAt: new Date(now - 33 * 60_000).toISOString(),
        durationMs: 720,
        confidence: 1.0,
        input: null,
        output: { result: 'pass' },
        redacted: false,
        policyResult: {
          policyId: 'pol-004',
          policyName: 'Decision Journal Completeness',
          result: 'pass',
          blockedReason: null,
          requiresApproval: false,
          violatedPolicies: [],
        },
        evidenceRefs: [],
        traceSpanId: 'aspan-005',
      },
      {
        id: 'as6',
        name: 'Execution',
        kind: 'execution',
        status: 'completed',
        startedAt: new Date(now - 33 * 60_000).toISOString(),
        completedAt: new Date(now - 30 * 60_000).toISOString(),
        durationMs: 2400,
        confidence: 0.98,
        input: null,
        output: { reportId: 'RPT-2026-04-20-001', delivered: true },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-006',
      },
      {
        id: 'as7',
        name: 'Proof Chain',
        kind: 'proof',
        status: 'completed',
        startedAt: new Date(now - 30 * 60_000).toISOString(),
        completedAt: new Date(now - 29 * 60_000).toISOString(),
        durationMs: 340,
        confidence: 1.0,
        input: null,
        output: { proofRef: 'PROOF-ALLOY-001-ABC123' },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-007',
      },
      {
        id: 'as8',
        name: 'Outcome Recording',
        kind: 'outcome',
        status: 'completed',
        startedAt: new Date(now - 29 * 60_000).toISOString(),
        completedAt: new Date(now - 28 * 60_000).toISOString(),
        durationMs: 180,
        confidence: 1.0,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-008',
      },
      {
        id: 'as9',
        name: 'Learning Update',
        kind: 'learning',
        status: 'completed',
        startedAt: new Date(now - 28 * 60_000).toISOString(),
        completedAt: new Date(now - 27 * 60_000).toISOString(),
        durationMs: 210,
        confidence: 1.0,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'aspan-009',
      },
    ],
    approvalHistory: [],
    checkpoints: [
      {
        id: 'ackpt-001',
        runId: 'run-alloy-001',
        stageId: 'as3',
        capturedAt: new Date(now - 38 * 60_000).toISOString(),
        worldStateHash: 'sha256:b9c37d4e1f2a',
        description: 'Post-recommendation cross-domain state snapshot',
        restorable: false,
      },
    ],
    traceSpans: [],
  },
  {
    id: 'run-prism-001',
    workflow: 'Contract Compliance Review',
    vertical: 'prism',
    tenant: 'Meridian Capital',
    status: 'failed',
    currentStage: 'execution',
    confidence: 0.61,
    policyStatus: 'violated',
    riskLevel: 'critical',
    approver: 'james.okonkwo@szl.io',
    startedAt: new Date(now - 2 * 3600_000).toISOString(),
    ageMs: 2 * 3600_000,
    modelAdapter: 'claude-3-5-sonnet',
    policyProfile: 'prism-standard-v1',
    agentId: 'prism-agent-01',
    objectiveText:
      'Review 47 vendor contracts for GDPR compliance gaps and generate remediation notices where material violations are identified.',
    retriever: { source: 'synthetic', adapterId: null },
    stages: [
      {
        id: 'ps1',
        name: 'Signal Ingestion',
        kind: 'signal',
        status: 'completed',
        startedAt: new Date(now - 2 * 3600_000).toISOString(),
        completedAt: new Date(now - 2 * 3600_000 + 900).toISOString(),
        durationMs: 900,
        confidence: 0.99,
        input: null,
        output: { contracts: 47 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'pspan-001',
      },
      {
        id: 'ps2',
        name: 'Context Assembly',
        kind: 'context',
        status: 'completed',
        startedAt: new Date(now - 2 * 3600_000 + 900).toISOString(),
        completedAt: new Date(now - 2 * 3600_000 + 3100).toISOString(),
        durationMs: 2200,
        confidence: 0.92,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'pspan-002',
      },
      {
        id: 'ps3',
        name: 'Recommendation',
        kind: 'recommendation',
        status: 'completed',
        startedAt: new Date(now - 2 * 3600_000 + 3100).toISOString(),
        completedAt: new Date(now - 2 * 3600_000 + 7400).toISOString(),
        durationMs: 4300,
        confidence: 0.61,
        input: null,
        output: { violations: 12, notices: 12 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'pspan-003',
      },
      {
        id: 'ps4',
        name: 'Simulation',
        kind: 'simulation',
        status: 'completed',
        startedAt: new Date(now - 2 * 3600_000 + 7400).toISOString(),
        completedAt: new Date(now - 2 * 3600_000 + 11200).toISOString(),
        durationMs: 3800,
        confidence: 0.72,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'pspan-004',
      },
      {
        id: 'ps5',
        name: 'Policy Evaluation',
        kind: 'policy',
        status: 'completed',
        startedAt: new Date(now - 2 * 3600_000 + 11200).toISOString(),
        completedAt: new Date(now - 2 * 3600_000 + 12100).toISOString(),
        durationMs: 900,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: {
          policyId: 'pol-001',
          policyName: 'High-Risk Action Approval Gate',
          result: 'fail',
          blockedReason: 'Critical-risk action blocked — approval expired without verdict',
          requiresApproval: true,
          violatedPolicies: ['pol-001', 'pol-002'],
        },
        evidenceRefs: [],
        traceSpanId: 'pspan-005',
      },
      {
        id: 'ps6',
        name: 'Execution',
        kind: 'execution',
        status: 'failed',
        startedAt: new Date(now - 3600_000).toISOString(),
        completedAt: new Date(now - 3600_000 + 800).toISOString(),
        durationMs: 800,
        confidence: null,
        input: null,
        output: { error: 'ApprovalExpiredError: pending approval timed out after 3600s' },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'pspan-006',
      },
      {
        id: 'ps7',
        name: 'Proof Chain',
        kind: 'proof',
        status: 'skipped',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 'ps8',
        name: 'Outcome Recording',
        kind: 'outcome',
        status: 'skipped',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
      {
        id: 'ps9',
        name: 'Learning Update',
        kind: 'learning',
        status: 'skipped',
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      },
    ],
    approvalHistory: [
      {
        id: 'ap-001',
        runId: 'run-prism-001',
        stageId: 'ps5',
        actor: 'james.okonkwo@szl.io',
        verdict: 'escalated',
        justification: 'Escalated to legal — confidence threshold below 70% for GDPR notices',
        timestamp: new Date(now - 3600_000 + 400_000).toISOString(),
        proofRef: 'PROOF-APP-PRISM-ESC-001',
        riskLevel: 'critical',
        policyId: 'pol-001',
      },
    ],
    checkpoints: [],
    traceSpans: [],
  },
  {
    id: 'run-lyte-001',
    workflow: 'SLA Breach Prediction',
    vertical: 'lyte',
    tenant: 'Pacific Cargo Group',
    status: 'running',
    currentStage: 'context',
    confidence: 0.82,
    policyStatus: 'compliant',
    riskLevel: 'low',
    approver: null,
    startedAt: new Date(now - 3 * 60_000).toISOString(),
    ageMs: 3 * 60_000,
    modelAdapter: 'gpt-4o-mini',
    policyProfile: 'lyte-standard-v1',
    agentId: 'lyte-agent-03',
    objectiveText:
      'Predict and surface SLA breach risks across 24 active service contracts for Q2 review.',
    retriever: { source: 'synthetic', adapterId: null },
    stages: [
      {
        id: 'ls1',
        name: 'Signal Ingestion',
        kind: 'signal',
        status: 'completed',
        startedAt: new Date(now - 3 * 60_000).toISOString(),
        completedAt: new Date(now - 2.5 * 60_000).toISOString(),
        durationMs: 780,
        confidence: 0.99,
        input: null,
        output: { contracts: 24 },
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'lspan-001',
      },
      {
        id: 'ls2',
        name: 'Context Assembly',
        kind: 'context',
        status: 'running',
        startedAt: new Date(now - 2.5 * 60_000).toISOString(),
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        redacted: false,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: 'lspan-002',
      },
      ...(
        [
          { id: 'ls3', name: 'Recommendation', kind: 'recommendation' as const, redacted: false },
          { id: 'ls4', name: 'Simulation', kind: 'simulation' as const, redacted: false },
          { id: 'ls5', name: 'Policy Evaluation', kind: 'policy' as const, redacted: false },
          { id: 'ls6', name: 'Execution', kind: 'execution' as const, redacted: true },
          { id: 'ls7', name: 'Proof Chain', kind: 'proof' as const, redacted: false },
          { id: 'ls8', name: 'Outcome Recording', kind: 'outcome' as const, redacted: false },
          { id: 'ls9', name: 'Learning Update', kind: 'learning' as const, redacted: false },
        ] satisfies Array<{ id: string; name: string; kind: RunStage['kind']; redacted: boolean }>
      ).map((s) => ({
        ...s,
        status: 'pending' as const,
        startedAt: null,
        completedAt: null,
        durationMs: null,
        confidence: null,
        input: null,
        output: null,
        policyResult: null,
        evidenceRefs: [],
        traceSpanId: null,
      })),
    ],
    approvalHistory: [],
    checkpoints: [],
    traceSpans: [],
  },
];

export const MOCK_PENDING_APPROVALS: PendingApproval[] = [
  {
    id: 'pend-001',
    runId: 'run-vessels-001',
    workflow: 'Voyage P&L Optimization',
    vertical: 'vessels',
    tenant: 'Pacific Cargo Group',
    riskLevel: 'high',
    policyId: 'pol-001',
    policyName: 'High-Risk Action Approval Gate',
    action:
      'Amend charter party routing — southern corridor reroute, ETA +1.4h, fuel savings 11.8%',
    requestedAt: new Date(now - 8 * 60_000).toISOString(),
    requestedBy: 'vessels-agent-01',
    ageMs: 8 * 60_000,
    objectiveText:
      'Optimize voyage routing to reduce fuel consumption by 12% while maintaining ETA within 6-hour window.',
    evidenceSummary:
      'Route optimizer confirms 11.8% fuel reduction; charter party Article 14(b) allows ±4h ETA deviation without demurrage penalty. 3 simulation scenarios all within policy bounds.',
  },
  {
    id: 'pend-002',
    runId: 'run-firestorm-001',
    workflow: 'Counterparty Credit Limit Override',
    vertical: 'firestorm',
    tenant: 'SZL Holdings',
    riskLevel: 'critical',
    policyId: 'pol-001',
    policyName: 'High-Risk Action Approval Gate',
    action: 'Increase Meridian Capital credit limit from $50M to $75M for Q2 commodity trades',
    requestedAt: new Date(now - 22 * 60_000).toISOString(),
    requestedBy: 'firestorm-agent-01',
    ageMs: 22 * 60_000,
    objectiveText:
      'Evaluate and approve counterparty credit limit expansion to support Q2 structured trade volumes.',
    evidenceSummary:
      'Credit model confidence 0.79 — below 0.85 threshold. Meridian Capital D/E ratio elevated at 3.2x. Recommend additional due diligence before approval.',
  },
  {
    id: 'pend-003',
    runId: 'run-carlota-001',
    workflow: 'Executive Engagement Strategy',
    vertical: 'carlota-jo',
    tenant: 'Pacific Cargo Group',
    riskLevel: 'medium',
    policyId: 'pol-004',
    policyName: 'Decision Journal Completeness',
    action:
      'Dispatch board-level advisory communication — Q2 strategic positioning memo to 3 executives',
    requestedAt: new Date(now - 4 * 60_000).toISOString(),
    requestedBy: 'carlota-agent-01',
    ageMs: 4 * 60_000,
    objectiveText:
      'Prepare and dispatch strategic advisory memo to C-suite ahead of Q2 board review.',
    evidenceSummary:
      'Communication drafted per engagement framework. Tone assessment: authoritative, appropriate. No sensitive disclosures detected. Ready for review.',
  },
];

export const MOCK_COUNTERFACTUAL: CounterfactualDiff = {
  runId: 'cf-vessels-001-replay',
  originalRunId: 'run-vessels-001',
  modelAdapter: 'claude-3-5-sonnet',
  policyProfile: 'vessels-conservative-v1',
  replayedAt: new Date().toISOString(),
  stages: [
    {
      stageName: 'Recommendation',
      original: {
        recommendation:
          'Reroute via southern corridor, reducing fuel by 11.8% with ETA impact +1.4h',
        confidence: 0.88,
        keyEvidence: [
          'AIS deviation data',
          'Charter party Article 14(b)',
          'Bunker price delta $42/MT',
        ],
        policyResult: 'warn',
        requiresApproval: true,
      },
      counterfactual: {
        recommendation:
          'Maintain current heading, adjust speed to 13.0kn — fuel savings 6.2%, no ETA impact',
        confidence: 0.91,
        keyEvidence: [
          'Speed optimization model',
          'Weather routing consensus',
          'Fuel consumption curve',
        ],
        policyResult: 'pass',
        requiresApproval: false,
      },
      changed: true,
    },
    {
      stageName: 'Simulation',
      original: {
        recommendation: 'Best case: 11.8% fuel savings across 3 scenarios',
        confidence: 0.91,
        keyEvidence: ['Southern corridor weather clear', 'Port congestion low'],
        policyResult: 'pass',
        requiresApproval: false,
      },
      counterfactual: {
        recommendation: 'Best case: 6.2% fuel savings — conservative trajectory, lower variance',
        confidence: 0.95,
        keyEvidence: ['Speed curve validated', 'Historical comparison 94 voyages'],
        policyResult: 'pass',
        requiresApproval: false,
      },
      changed: true,
    },
    {
      stageName: 'Policy Evaluation',
      original: {
        recommendation: 'Blocked — pol-001 triggered, awaiting human approval',
        confidence: 0,
        keyEvidence: ['Charter party amendment required', 'High-risk action gate'],
        policyResult: 'fail',
        requiresApproval: true,
      },
      counterfactual: {
        recommendation: 'Compliant — all policies passed, no approval required',
        confidence: 1.0,
        keyEvidence: [
          'Speed adjustment within autonomous authority',
          'No contract amendment needed',
        ],
        policyResult: 'pass',
        requiresApproval: false,
      },
      changed: true,
    },
  ],
};
