const js = require('@eslint/js');
const tsPlugin = require('@typescript-eslint/eslint-plugin');
const tsParser = require('@typescript-eslint/parser');

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  indexedDB: 'readonly',
  fetch: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FileList: 'readonly',
  Event: 'readonly',
  CustomEvent: 'readonly',
  MouseEvent: 'readonly',
  KeyboardEvent: 'readonly',
  InputEvent: 'readonly',
  PointerEvent: 'readonly',
  TouchEvent: 'readonly',
  DragEvent: 'readonly',
  FocusEvent: 'readonly',
  WheelEvent: 'readonly',
  UIEvent: 'readonly',
  ClipboardEvent: 'readonly',
  ErrorEvent: 'readonly',
  MessageEvent: 'readonly',
  EventTarget: 'readonly',
  HTMLElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLFormElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLDivElement: 'readonly',
  HTMLSpanElement: 'readonly',
  HTMLAnchorElement: 'readonly',
  HTMLImageElement: 'readonly',
  HTMLVideoElement: 'readonly',
  HTMLAudioElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  HTMLTableElement: 'readonly',
  HTMLTableRowElement: 'readonly',
  HTMLTableCellElement: 'readonly',
  HTMLTableCaptionElement: 'readonly',
  HTMLTableSectionElement: 'readonly',
  HTMLHeadingElement: 'readonly',
  HTMLParagraphElement: 'readonly',
  HTMLUListElement: 'readonly',
  HTMLOListElement: 'readonly',
  HTMLLIElement: 'readonly',
  HTMLLabelElement: 'readonly',
  HTMLDialogElement: 'readonly',
  HTMLIFrameElement: 'readonly',
  HTMLScriptElement: 'readonly',
  HTMLStyleElement: 'readonly',
  HTMLLinkElement: 'readonly',
  HTMLMetaElement: 'readonly',
  HTMLBodyElement: 'readonly',
  HTMLHeadElement: 'readonly',
  HTMLHtmlElement: 'readonly',
  HTMLPreElement: 'readonly',
  HTMLProgressElement: 'readonly',
  HTMLAreaElement: 'readonly',
  HTMLBRElement: 'readonly',
  HTMLHRElement: 'readonly',
  HTMLCollectionBase: 'readonly',
  HTMLCollection: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  DocumentFragment: 'readonly',
  Document: 'readonly',
  ShadowRoot: 'readonly',
  Range: 'readonly',
  Selection: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  PerformanceObserver: 'readonly',
  WebSocket: 'readonly',
  EventSource: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  ReadableStream: 'readonly',
  WritableStream: 'readonly',
  TransformStream: 'readonly',
  Response: 'readonly',
  Request: 'readonly',
  Headers: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  structuredClone: 'readonly',
  queueMicrotask: 'readonly',
  globalThis: 'readonly',
  self: 'readonly',
  Worker: 'readonly',
  SharedWorker: 'readonly',
  Notification: 'readonly',
  MediaStream: 'readonly',
  RTCPeerConnection: 'readonly',
  WebGLRenderingContext: 'readonly',
  WebGL2RenderingContext: 'readonly',
  CanvasRenderingContext2D: 'readonly',
  ImageData: 'readonly',
  OffscreenCanvas: 'readonly',
  AudioContext: 'readonly',
  SpeechSynthesis: 'readonly',
  SpeechRecognition: 'readonly',
  CSS: 'readonly',
  CSSStyleDeclaration: 'readonly',
  IDBFactory: 'readonly',
  IDBDatabase: 'readonly',
  IDBTransaction: 'readonly',
  IDBObjectStore: 'readonly',
  IDBIndex: 'readonly',
  IDBCursor: 'readonly',
  IDBKeyRange: 'readonly',
  Geolocation: 'readonly',
  GeolocationPosition: 'readonly',
  Screen: 'readonly',
  Storage: 'readonly',
  XMLHttpRequest: 'readonly',
  WebAssembly: 'readonly',
  Proxy: 'readonly',
  Reflect: 'readonly',
  Symbol: 'readonly',
  BigInt: 'readonly',
  Int8Array: 'readonly',
  Uint8Array: 'readonly',
  Uint8ClampedArray: 'readonly',
  Int16Array: 'readonly',
  Uint16Array: 'readonly',
  Int32Array: 'readonly',
  Uint32Array: 'readonly',
  Float32Array: 'readonly',
  Float64Array: 'readonly',
  BigInt64Array: 'readonly',
  BigUint64Array: 'readonly',
  ArrayBuffer: 'readonly',
  DataView: 'readonly',
  SharedArrayBuffer: 'readonly',
  Atomics: 'readonly',
  React: 'readonly',
};

const nodeGlobals = {
  process: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  module: 'readonly',
  require: 'readonly',
  exports: 'readonly',
  global: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  queueMicrotask: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  fetch: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  ReadableStream: 'readonly',
  WritableStream: 'readonly',
  Response: 'readonly',
  Request: 'readonly',
  Headers: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
  structuredClone: 'readonly',
  globalThis: 'readonly',
  Symbol: 'readonly',
  BigInt: 'readonly',
  Int8Array: 'readonly',
  Uint8Array: 'readonly',
  Uint8ClampedArray: 'readonly',
  Int16Array: 'readonly',
  Uint16Array: 'readonly',
  Int32Array: 'readonly',
  Uint32Array: 'readonly',
  Float32Array: 'readonly',
  Float64Array: 'readonly',
  BigInt64Array: 'readonly',
  ArrayBuffer: 'readonly',
  DataView: 'readonly',
  MessageEvent: 'readonly',
  WebSocket: 'readonly',
};

module.exports = [
  js.configs.recommended,
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'warn',
    },
    rules: {
      'no-undef': 'off',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-redeclare': 'off',
      'no-useless-escape': 'warn',
    },
  },
  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/build/',
      '**/.next/',
      '**/coverage/',
      '.archive/',
      '.git-rewrite/',
      '.local/',
      '.agents/',
      '.cache/',
      '.config/',
      'attached_assets/',
      'exports/',
      'infra/',
      'social-content/',
      'docs/',
      'eslint.config.js',
      'lib/services/connectors/',
    ],
  },
  {
    files: ['artifacts/**/*.ts', 'artifacts/**/*.tsx', 'lib/**/*.ts', 'lib/**/*.tsx'],
    linterOptions: {
      reportUnusedDisableDirectives: 'warn',
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        ...browserGlobals,
        ...nodeGlobals,
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      'no-undef': 'off',
      'no-console': 'warn',
      'no-unused-vars': 'off',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-redeclare': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    files: ['scripts/**/*.ts', 'scripts/**/*.js'],
    linterOptions: {
      reportUnusedDisableDirectives: 'warn',
    },
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: nodeGlobals,
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      'no-undef': 'off',
      'no-console': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
];
