import { getRuntimeMode, isSeedDataAllowed } from '@szl-holdings/platform-registry';
import {
  db,
  terraAgentsTable,
  terraBrokeragesTable,
  terraInquiriesTable,
  terraListingsTable,
  terraPropertiesTable,
  terraTransactionsTable,
} from '@szl-holdings/db';
import { eq, sql } from 'drizzle-orm';

export async function seedTerraDemo() {
  if (!isSeedDataAllowed()) {
    const mode = getRuntimeMode();
    throw new Error(
      `[terra-seed] Attempted to seed Terra demo data in ${mode} mode. ` +
        `Seed data is only permitted in local-dev, internal-preview, and demo modes.`,
    );
  }

  // Task #2638 added a unique index on terra_properties (address, city, state)
  // so the property insert below is now genuinely idempotent via
  // onConflictDoNothing(). We still keep this all-tables early-return as a
  // cheap fast-path (skips ~50 inserts on hot reload) and surface partial
  // state explicitly so reseed regressions on the *other* terra_* tables
  // remain easy to diagnose.
  const counts = await Promise.all([
    db.select({ c: sql<number>`count(*)::int` }).from(terraBrokeragesTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraAgentsTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraPropertiesTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraListingsTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraInquiriesTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraTransactionsTable),
  ]);
  const brokerageCount = counts[0][0]?.c ?? 0;
  const agentCountExisting = counts[1][0]?.c ?? 0;
  const propCount = counts[2][0]?.c ?? 0;
  const listingCountExisting = counts[3][0]?.c ?? 0;
  const inquiryCount = counts[4][0]?.c ?? 0;
  const txCount = counts[5][0]?.c ?? 0;
  if (
    brokerageCount > 0 &&
    agentCountExisting > 0 &&
    propCount > 0 &&
    listingCountExisting > 0 &&
    inquiryCount > 0 &&
    txCount > 0
  ) {
    return;
  }
  if (propCount > 0 || agentCountExisting > 0 || brokerageCount > 0) {
    return;
  }

  await db.execute(sql`
    INSERT INTO feature_flags (key, name, description, is_enabled, rollout_percentage, scope, product)
    VALUES
      ('terra_map_mode_enabled', 'Terra Map Mode', 'Activates geospatial property map layer with distress and inquiry heat overlays.', true, 100, 'global', 'terra'),
      ('terra_broker_view_enabled', 'Terra Broker View', 'Enables brokerage-level rollup view with multi-agent comparative analytics.', true, 100, 'global', 'terra')
    ON CONFLICT (key) DO UPDATE SET
      is_enabled = EXCLUDED.is_enabled,
      updated_at = NOW()
  `);

  const [insertedBrokerage] = await db
    .insert(terraBrokeragesTable)
    .values({
      name: 'Terra Commercial',
      slug: 'terra-commercial',
      licenseNumber: 'NY-BRK-2024-001',
      city: 'New York',
      state: 'NY',
      specialty: 'Commercial — Office, Retail, Industrial, Mixed-Use',
      headCount: 4,
      activeListings: 6,
      closedVolumeLtm: '91100000',
      status: 'active',
      isDemo: true,
    })
    .onConflictDoNothing()
    .returning();

  let brokerageId: number;
  if (insertedBrokerage) {
    brokerageId = insertedBrokerage.id;
  } else {
    const [existing] = await db
      .select({ id: terraBrokeragesTable.id })
      .from(terraBrokeragesTable)
      .where(eq(terraBrokeragesTable.slug, 'terra-commercial'))
      .limit(1);
    if (!existing) {
      return;
    }
    brokerageId = existing.id;
  }

  const agentValues = [
    {
      brokerageId,
      firstName: 'Karla',
      lastName: 'Rivera',
      email: 'k.rivera@terra-commercial.com',
      phone: '+1-212-555-0101',
      licenseNumber: 'NY-AG-2020-4441',
      specialty: 'office' as const,
      status: 'active' as const,
      activeListings: 8,
      closedDealsLtm: 14,
      closeRatePct: '68.00',
      avgDaysToContract: 44,
      inquiryConversionPct: '31.00',
      isDemo: true,
    },
    {
      brokerageId,
      firstName: 'Michael',
      lastName: 'Chen',
      email: 'm.chen@terra-commercial.com',
      phone: '+1-212-555-0102',
      licenseNumber: 'NY-AG-2019-3812',
      specialty: 'mixed-use' as const,
      status: 'active' as const,
      activeListings: 6,
      closedDealsLtm: 9,
      closeRatePct: '52.00',
      avgDaysToContract: 62,
      inquiryConversionPct: '22.00',
      isDemo: true,
    },
    {
      brokerageId,
      firstName: 'Alejandro',
      lastName: 'Torres',
      email: 'a.torres@terra-commercial.com',
      phone: '+1-212-555-0103',
      licenseNumber: 'NY-AG-2018-2291',
      specialty: 'office' as const,
      status: 'active' as const,
      activeListings: 11,
      closedDealsLtm: 18,
      closeRatePct: '74.00',
      avgDaysToContract: 38,
      inquiryConversionPct: '38.00',
      isDemo: true,
    },
    {
      brokerageId,
      firstName: 'Joyce',
      lastName: 'Williams',
      email: 'j.williams@terra-commercial.com',
      phone: '+1-212-555-0104',
      licenseNumber: 'NY-AG-2021-5502',
      specialty: 'retail' as const,
      status: 'active' as const,
      activeListings: 4,
      closedDealsLtm: 6,
      closeRatePct: '45.00',
      avgDaysToContract: 78,
      inquiryConversionPct: '18.00',
      isDemo: true,
    },
  ];

  const agents = await db
    .insert(terraAgentsTable)
    .values(agentValues)
    .onConflictDoNothing()
    .returning();
  const agentMap: Record<string, number> = {};
  agents.forEach((a) => {
    agentMap[a.email] = a.id;
  });

  const propertyValues = [
    {
      address: '800 Fifth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10065',
      submarket: 'Midtown East',
      propertyType: 'office' as const,
      sqft: 142000,
      yearBuilt: 1978,
      floors: 28,
      latitude: '40.7636000',
      longitude: '-73.9717000',
      ownerName: 'Fifth Avenue Holdings LLC',
      ownerType: 'llc' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '1420 Harbor Blvd',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11231',
      submarket: 'Red Hook',
      propertyType: 'mixed-use' as const,
      sqft: 58000,
      yearBuilt: 2006,
      floors: 7,
      latitude: '40.6765000',
      longitude: '-74.0062000',
      ownerName: 'Harbor Realty Partners LP',
      ownerType: 'llc' as const,
      zoning: 'M1-6',
      isDemo: true,
    },
    {
      address: '340 Park Avenue South',
      city: 'New York',
      state: 'NY',
      zipCode: '10010',
      submarket: 'Flatiron / NoMad',
      propertyType: 'office' as const,
      sqft: 88000,
      yearBuilt: 1965,
      floors: 22,
      latitude: '40.7437000',
      longitude: '-73.9868000',
      ownerName: 'Park South Properties Trust',
      ownerType: 'trust' as const,
      zoning: 'C5-2',
      isDemo: true,
    },
    {
      address: '620 Atlantic Ave',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Boerum Hill',
      propertyType: 'retail' as const,
      sqft: 14200,
      yearBuilt: 1922,
      floors: 2,
      latitude: '40.6847000',
      longitude: '-73.9769000',
      ownerName: 'Atlantic Grove LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4',
      isDemo: true,
    },
    {
      address: '1800 Westchester Ave',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10472',
      submarket: 'Hunts Point',
      propertyType: 'industrial' as const,
      sqft: 76000,
      yearBuilt: 1994,
      floors: 1,
      latitude: '40.8194000',
      longitude: '-73.8632000',
      ownerName: 'South Bronx Industrial LP',
      ownerType: 'llc' as const,
      zoning: 'M3-1',
      isDemo: true,
    },
    {
      address: '55 Water Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10041',
      submarket: 'Financial District',
      propertyType: 'office' as const,
      sqft: 298000,
      yearBuilt: 1972,
      floors: 54,
      latitude: '40.7024000',
      longitude: '-74.0098000',
      ownerName: 'Water Street Ventures LLC',
      ownerType: 'corporate' as const,
      zoning: 'C6-9',
      isDemo: true,
    },
    {
      address: '125 Fulton Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10038',
      submarket: 'Financial District',
      propertyType: 'mixed-use' as const,
      sqft: 44000,
      yearBuilt: 1962,
      floors: 8,
      latitude: '40.7087000',
      longitude: '-74.0075000',
      ownerName: 'Fulton Heritage LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-4',
      isDemo: true,
    },
    {
      address: '30 Broad Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10004',
      submarket: 'Financial District',
      propertyType: 'office' as const,
      sqft: 67000,
      yearBuilt: 1931,
      floors: 18,
      latitude: '40.7067000',
      longitude: '-74.0118000',
      ownerName: 'Broad Street Capital Partners',
      ownerType: 'llc' as const,
      zoning: 'C5-5',
      isDemo: true,
    },
    {
      address: '250 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10007',
      submarket: 'Civic Center',
      propertyType: 'office' as const,
      sqft: 183000,
      yearBuilt: 1955,
      floors: 22,
      latitude: '40.7136000',
      longitude: '-74.0094000',
      ownerName: 'Broadway Civic Realty Corp',
      ownerType: 'corporate' as const,
      zoning: 'C6-4A',
      isDemo: true,
    },
    {
      address: '11 Park Place',
      city: 'New York',
      state: 'NY',
      zipCode: '10007',
      submarket: 'Tribeca / City Hall',
      propertyType: 'office' as const,
      sqft: 39000,
      yearBuilt: 1914,
      floors: 10,
      latitude: '40.7127000',
      longitude: '-74.0103000',
      ownerName: 'Park Place Acquisitions LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-4A',
      isDemo: true,
    },
    {
      address: '420 Lexington Ave',
      city: 'New York',
      state: 'NY',
      zipCode: '10170',
      submarket: 'Grand Central',
      propertyType: 'office' as const,
      sqft: 351000,
      yearBuilt: 1930,
      floors: 34,
      latitude: '40.7523000',
      longitude: '-73.9762000',
      ownerName: 'Graybar Building Owners LLC',
      ownerType: 'llc' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '405 Park Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      submarket: 'Park Avenue',
      propertyType: 'office' as const,
      sqft: 110000,
      yearBuilt: 1948,
      floors: 20,
      latitude: '40.7591000',
      longitude: '-73.9730000',
      ownerName: 'Park Ave Capital Partners',
      ownerType: 'corporate' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '666 Fifth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10103',
      submarket: 'Midtown',
      propertyType: 'office' as const,
      sqft: 508000,
      yearBuilt: 1957,
      floors: 41,
      latitude: '40.7591000',
      longitude: '-73.9770000',
      ownerName: 'Fifth Ave Tower Holdings Trust',
      ownerType: 'trust' as const,
      zoning: 'C5-2.5',
      isDemo: true,
    },
    {
      address: '1140 Avenue of the Americas',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      submarket: 'Midtown West',
      propertyType: 'office' as const,
      sqft: 424000,
      yearBuilt: 1972,
      floors: 37,
      latitude: '40.7569000',
      longitude: '-73.9815000',
      ownerName: 'Sixth Ave Properties LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-6',
      isDemo: true,
    },
    {
      address: '225 West 34th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10122',
      submarket: 'Penn Plaza / Midtown West',
      propertyType: 'office' as const,
      sqft: 215000,
      yearBuilt: 1925,
      floors: 16,
      latitude: '40.7500000',
      longitude: '-73.9939000',
      ownerName: 'Penn Plaza Ventures LP',
      ownerType: 'llc' as const,
      zoning: 'C6-4.5',
      isDemo: true,
    },
    {
      address: '520 Eighth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10018',
      submarket: 'Garment District',
      propertyType: 'office' as const,
      sqft: 178000,
      yearBuilt: 1948,
      floors: 17,
      latitude: '40.7532000',
      longitude: '-73.9959000',
      ownerName: 'Garment Center Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '350 West 42nd Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      submarket: "Hell's Kitchen",
      propertyType: 'mixed-use' as const,
      sqft: 62000,
      yearBuilt: 2001,
      floors: 11,
      latitude: '40.7584000',
      longitude: '-73.9952000',
      ownerName: 'Westies Gate LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-4',
      isDemo: true,
    },
    {
      address: '147 West 35th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      submarket: 'Midtown South',
      propertyType: 'office' as const,
      sqft: 91000,
      yearBuilt: 1967,
      floors: 14,
      latitude: '40.7505000',
      longitude: '-73.9918000',
      ownerName: 'Midtown South Realty Corp',
      ownerType: 'corporate' as const,
      zoning: 'C6-4M',
      isDemo: true,
    },
    {
      address: '40 West 25th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10010',
      submarket: 'Chelsea',
      propertyType: 'office' as const,
      sqft: 74000,
      yearBuilt: 1909,
      floors: 12,
      latitude: '40.7449000',
      longitude: '-73.9916000',
      ownerName: 'Chelsea Square Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2A',
      isDemo: true,
    },
    {
      address: '180 Tenth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10011',
      submarket: 'West Chelsea',
      propertyType: 'mixed-use' as const,
      sqft: 48000,
      yearBuilt: 2009,
      floors: 8,
      latitude: '40.7468000',
      longitude: '-74.0043000',
      ownerName: 'High Line Realty Group LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '112 West 18th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10011',
      submarket: 'Chelsea',
      propertyType: 'office' as const,
      sqft: 33000,
      yearBuilt: 1988,
      floors: 9,
      latitude: '40.7402000',
      longitude: '-73.9975000',
      ownerName: 'Chelsea Crossroads LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2A',
      isDemo: true,
    },
    {
      address: '40 East 52nd Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      submarket: 'Plaza District',
      propertyType: 'office' as const,
      sqft: 208000,
      yearBuilt: 1956,
      floors: 22,
      latitude: '40.7578000',
      longitude: '-73.9730000',
      ownerName: '52nd Street Holdings Corp',
      ownerType: 'corporate' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '780 Third Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10017',
      submarket: 'Turtle Bay',
      propertyType: 'office' as const,
      sqft: 264000,
      yearBuilt: 1983,
      floors: 36,
      latitude: '40.7562000',
      longitude: '-73.9694000',
      ownerName: 'Third Avenue Office LP',
      ownerType: 'llc' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '1501 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      submarket: 'Times Square',
      propertyType: 'office' as const,
      sqft: 476000,
      yearBuilt: 1969,
      floors: 42,
      latitude: '40.7571000',
      longitude: '-73.9869000',
      ownerName: 'Times Square Tower LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-7',
      isDemo: true,
    },
    {
      address: '130 Prince Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      submarket: 'SoHo',
      propertyType: 'retail' as const,
      sqft: 9800,
      yearBuilt: 1885,
      floors: 5,
      latitude: '40.7256000',
      longitude: '-74.0007000',
      ownerName: 'Prince Street Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-5B',
      isDemo: true,
    },
    {
      address: '72 Spring Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      submarket: 'SoHo',
      propertyType: 'mixed-use' as const,
      sqft: 21000,
      yearBuilt: 1890,
      floors: 6,
      latitude: '40.7242000',
      longitude: '-74.0001000',
      ownerName: 'Spring Street Loft Partners',
      ownerType: 'llc' as const,
      zoning: 'M1-5B',
      isDemo: true,
    },
    {
      address: '215 Lafayette Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      submarket: 'NoHo',
      propertyType: 'mixed-use' as const,
      sqft: 28000,
      yearBuilt: 1911,
      floors: 7,
      latitude: '40.7233000',
      longitude: '-73.9976000',
      ownerName: 'Lafayette Loft Trust',
      ownerType: 'trust' as const,
      zoning: 'M1-5B',
      isDemo: true,
    },
    {
      address: '115 East Houston Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10002',
      submarket: 'Lower East Side',
      propertyType: 'retail' as const,
      sqft: 6400,
      yearBuilt: 1928,
      floors: 3,
      latitude: '40.7226000',
      longitude: '-73.9935000',
      ownerName: 'Houston Street Corp',
      ownerType: 'corporate' as const,
      zoning: 'C4-5X',
      isDemo: true,
    },
    {
      address: '440 Kent Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11249',
      submarket: 'Williamsburg',
      propertyType: 'mixed-use' as const,
      sqft: 72000,
      yearBuilt: 2017,
      floors: 9,
      latitude: '40.7141000',
      longitude: '-73.9701000',
      ownerName: 'Kent Ave Development LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-4',
      isDemo: true,
    },
    {
      address: '25 Kent Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11249',
      submarket: 'Williamsburg North',
      propertyType: 'office' as const,
      sqft: 136000,
      yearBuilt: 2019,
      floors: 8,
      latitude: '40.7207000',
      longitude: '-73.9627000',
      ownerName: 'North Kent Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-4',
      isDemo: true,
    },
    {
      address: '160 Imlay Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11231',
      submarket: 'Red Hook',
      propertyType: 'industrial' as const,
      sqft: 92000,
      yearBuilt: 1947,
      floors: 4,
      latitude: '40.6781000',
      longitude: '-74.0087000',
      ownerName: 'Imlay Industrial Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'M2-1',
      isDemo: true,
    },
    {
      address: '365 Bond Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11231',
      submarket: 'Gowanus',
      propertyType: 'mixed-use' as const,
      sqft: 84000,
      yearBuilt: 2021,
      floors: 10,
      latitude: '40.6787000',
      longitude: '-73.9949000',
      ownerName: 'Gowanus Living LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-6D',
      isDemo: true,
    },
    {
      address: '540 Fourth Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11215',
      submarket: 'Park Slope South',
      propertyType: 'retail' as const,
      sqft: 8200,
      yearBuilt: 1939,
      floors: 2,
      latitude: '40.6641000',
      longitude: '-73.9851000',
      ownerName: 'Fourth Ave Properties LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '85 Fourth Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Boerum Hill',
      propertyType: 'retail' as const,
      sqft: 5100,
      yearBuilt: 1915,
      floors: 3,
      latitude: '40.6868000',
      longitude: '-73.9827000',
      ownerName: 'Fourth & Dean LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4',
      isDemo: true,
    },
    {
      address: '1000 Dean Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11238',
      submarket: 'Crown Heights West',
      propertyType: 'mixed-use' as const,
      sqft: 31000,
      yearBuilt: 2018,
      floors: 6,
      latitude: '40.6742000',
      longitude: '-73.9624000',
      ownerName: 'Dean Street Development LLC',
      ownerType: 'llc' as const,
      zoning: 'R7A',
      isDemo: true,
    },
    {
      address: '75 Flatbush Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Fort Greene',
      propertyType: 'office' as const,
      sqft: 43000,
      yearBuilt: 1977,
      floors: 7,
      latitude: '40.6890000',
      longitude: '-73.9783000',
      ownerName: 'Flatbush Office Holdings LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '265 Livingston Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11201',
      submarket: 'Brooklyn Heights',
      propertyType: 'office' as const,
      sqft: 27000,
      yearBuilt: 1949,
      floors: 8,
      latitude: '40.6899000',
      longitude: '-73.9870000',
      ownerName: 'Livingston Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '1 MetroTech Center',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11201',
      submarket: 'Downtown Brooklyn',
      propertyType: 'office' as const,
      sqft: 588000,
      yearBuilt: 1991,
      floors: 16,
      latitude: '40.6924000',
      longitude: '-73.9851000',
      ownerName: 'Brookfield MetroTech LLC',
      ownerType: 'corporate' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '2 Hanson Place',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Atlantic Terminal',
      propertyType: 'office' as const,
      sqft: 193000,
      yearBuilt: 1926,
      floors: 26,
      latitude: '40.6839000',
      longitude: '-73.9771000',
      ownerName: 'Hanson Place Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '1090 Jerome Avenue',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10452',
      submarket: 'Concourse Village',
      propertyType: 'retail' as const,
      sqft: 12600,
      yearBuilt: 1945,
      floors: 2,
      latitude: '40.8368000',
      longitude: '-73.9161000',
      ownerName: 'Jerome Ave Commerce LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4D',
      isDemo: true,
    },
    {
      address: '2500 Exterior Street',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10451',
      submarket: 'Port Morris',
      propertyType: 'industrial' as const,
      sqft: 143000,
      yearBuilt: 1967,
      floors: 2,
      latitude: '40.8094000',
      longitude: '-73.9248000',
      ownerName: 'Port Morris Industrial LP',
      ownerType: 'llc' as const,
      zoning: 'M1-1',
      isDemo: true,
    },
    {
      address: '1220 Zerega Avenue',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10462',
      submarket: 'Parkchester',
      propertyType: 'industrial' as const,
      sqft: 58000,
      yearBuilt: 1988,
      floors: 1,
      latitude: '40.8322000',
      longitude: '-73.8588000',
      ownerName: 'Zerega Industrial LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-1',
      isDemo: true,
    },
    {
      address: '3636 Third Avenue',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10456',
      submarket: 'Morrisania',
      propertyType: 'retail' as const,
      sqft: 7400,
      yearBuilt: 1963,
      floors: 1,
      latitude: '40.8274000',
      longitude: '-73.9114000',
      ownerName: 'Third Ave Bronx LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4D',
      isDemo: true,
    },
    {
      address: '670 Forest Avenue',
      city: 'Staten Island',
      state: 'NY',
      zipCode: '10310',
      submarket: 'Port Richmond',
      propertyType: 'retail' as const,
      sqft: 11200,
      yearBuilt: 1972,
      floors: 1,
      latitude: '40.6333000',
      longitude: '-74.1299000',
      ownerName: 'Forest Ave Holdings LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-1',
      isDemo: true,
    },
    {
      address: '1011 Bay Street',
      city: 'Staten Island',
      state: 'NY',
      zipCode: '10305',
      submarket: 'Stapleton',
      propertyType: 'mixed-use' as const,
      sqft: 18400,
      yearBuilt: 1921,
      floors: 3,
      latitude: '40.6238000',
      longitude: '-74.0739000',
      ownerName: 'Bay Street Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '101-15 Jamaica Avenue',
      city: 'Queens',
      state: 'NY',
      zipCode: '11418',
      submarket: 'Richmond Hill',
      propertyType: 'retail' as const,
      sqft: 9600,
      yearBuilt: 1953,
      floors: 2,
      latitude: '40.6998000',
      longitude: '-73.8344000',
      ownerName: 'Jamaica Ave Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '88-18 Sutphin Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11435',
      submarket: 'Jamaica',
      propertyType: 'office' as const,
      sqft: 54000,
      yearBuilt: 1982,
      floors: 8,
      latitude: '40.7023000',
      longitude: '-73.8079000',
      ownerName: 'Jamaica Sutphin Corp',
      ownerType: 'corporate' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '26-01 Queens Plaza North',
      city: 'Queens',
      state: 'NY',
      zipCode: '11101',
      submarket: 'Long Island City',
      propertyType: 'office' as const,
      sqft: 112000,
      yearBuilt: 2003,
      floors: 12,
      latitude: '40.7496000',
      longitude: '-73.9389000',
      ownerName: 'Queens Plaza Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '4545 Center Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11109',
      submarket: 'Hunters Point',
      propertyType: 'mixed-use' as const,
      sqft: 67000,
      yearBuilt: 2015,
      floors: 9,
      latitude: '40.7442000',
      longitude: '-73.9537000',
      ownerName: 'Hunters Point Dev LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-1A',
      isDemo: true,
    },
    {
      address: '38-01 Queens Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11101',
      submarket: 'Sunnyside',
      propertyType: 'retail' as const,
      sqft: 14800,
      yearBuilt: 1937,
      floors: 2,
      latitude: '40.7445000',
      longitude: '-73.9368000',
      ownerName: 'Queens Blvd Retail LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '14-21 College Point Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11356',
      submarket: 'College Point',
      propertyType: 'industrial' as const,
      sqft: 88000,
      yearBuilt: 1978,
      floors: 1,
      latitude: '40.7819000',
      longitude: '-73.8519000',
      ownerName: 'College Point Industrial LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-1',
      isDemo: true,
    },
    {
      address: '130-30 31st Avenue',
      city: 'Queens',
      state: 'NY',
      zipCode: '11354',
      submarket: 'Flushing',
      propertyType: 'mixed-use' as const,
      sqft: 24000,
      yearBuilt: 2008,
      floors: 5,
      latitude: '40.7614000',
      longitude: '-73.8319000',
      ownerName: 'Flushing Center LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4',
      isDemo: true,
    },
    {
      address: '40-24 College Point Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11354',
      submarket: 'Flushing West',
      propertyType: 'retail' as const,
      sqft: 8900,
      yearBuilt: 1961,
      floors: 2,
      latitude: '40.7568000',
      longitude: '-73.8355000',
      ownerName: 'Flushing Corridor Retail LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '22 Merrick Avenue',
      city: 'Queens',
      state: 'NY',
      zipCode: '11385',
      submarket: 'Ridgewood',
      propertyType: 'mixed-use' as const,
      sqft: 17600,
      yearBuilt: 1925,
      floors: 4,
      latitude: '40.7055000',
      longitude: '-73.9014000',
      ownerName: 'Ridgewood Realty Group LLC',
      ownerType: 'llc' as const,
      zoning: 'R6A',
      isDemo: true,
    },
  ];

  const properties = await db
    .insert(terraPropertiesTable)
    .values(propertyValues)
    .onConflictDoNothing()
    .returning();

  if (properties.length > 0 && agents.length > 0) {
    const getRivera = () => agentMap['k.rivera@terra-commercial.com'] ?? agents[0]?.id;
    const getChen = () => agentMap['m.chen@terra-commercial.com'] ?? agents[1]?.id;
    const getTorres = () => agentMap['a.torres@terra-commercial.com'] ?? agents[2]?.id;
    const getWilliams = () => agentMap['j.williams@terra-commercial.com'] ?? agents[3]?.id;

    const listingValues = [
      {
        propertyId: properties[0]?.id,
        agentId: getRivera(),
        brokerageId,
        status: 'active' as const,
        listPrice: '89500000',
        pricePerSqft: '630',
        originalListPrice: '89500000',
        capRate: '5.10',
        noi: '4565000',
        daysOnMarket: 38,
        inquiryCount: 14,
        viewCount: 82,
        priceReductions: 0,
        listDate: '2026-02-20',
        opportunityScore: 87,
        isDemo: true,
      },
      {
        propertyId: properties[1]?.id,
        agentId: getChen(),
        brokerageId,
        status: 'active' as const,
        listPrice: '24800000',
        pricePerSqft: '428',
        originalListPrice: '26500000',
        capRate: '4.80',
        noi: '1190400',
        daysOnMarket: 72,
        inquiryCount: 7,
        viewCount: 34,
        priceReductions: 1,
        listDate: '2026-01-17',
        opportunityScore: 62,
        isDemo: true,
      },
      {
        propertyId: properties[2]?.id,
        agentId: getTorres(),
        brokerageId,
        status: 'active' as const,
        listPrice: '47200000',
        pricePerSqft: '536',
        originalListPrice: '47200000',
        capRate: '5.80',
        noi: '2737600',
        daysOnMarket: 21,
        inquiryCount: 22,
        viewCount: 118,
        priceReductions: 0,
        listDate: '2026-03-07',
        opportunityScore: 94,
        isDemo: true,
      },
      {
        propertyId: properties[3]?.id,
        agentId: getWilliams(),
        brokerageId,
        status: 'active' as const,
        listPrice: '8900000',
        pricePerSqft: '627',
        originalListPrice: '9800000',
        capRate: '4.20',
        noi: '373800',
        daysOnMarket: 115,
        inquiryCount: 3,
        viewCount: 18,
        priceReductions: 2,
        listDate: '2025-12-05',
        opportunityScore: 44,
        isDemo: true,
      },
      {
        propertyId: properties[4]?.id,
        agentId: getRivera(),
        brokerageId,
        status: 'under_contract' as const,
        listPrice: '12400000',
        pricePerSqft: '163',
        originalListPrice: '12400000',
        capRate: '6.20',
        noi: '768800',
        daysOnMarket: 58,
        inquiryCount: 11,
        viewCount: 54,
        priceReductions: 0,
        listDate: '2026-01-31',
        opportunityScore: 79,
        isDemo: true,
      },
      {
        propertyId: properties[5]?.id,
        agentId: getChen(),
        brokerageId,
        status: 'active' as const,
        listPrice: '134000000',
        pricePerSqft: '450',
        originalListPrice: '158000000',
        capRate: '3.90',
        noi: '5226000',
        daysOnMarket: 189,
        inquiryCount: 4,
        viewCount: 22,
        priceReductions: 3,
        listDate: '2025-09-22',
        opportunityScore: 38,
        isDemo: true,
      },
    ];

    const listings = await db
      .insert(terraListingsTable)
      .values(listingValues)
      .onConflictDoNothing()
      .returning();

    if (listings.length > 0) {
      const inquiryValues = [
        {
          listingId: listings[2]?.id,
          assignedAgentId: getTorres(),
          buyerName: 'Apex Partners LP',
          buyerEmail: 'contact@apexpartners.com',
          buyerType: 'investor' as const,
          financingStatus: 'cash' as const,
          qualificationScore: 92,
          status: 'qualified' as const,
          source: 'referral' as const,
          message: 'Interested in full-floor acquisition. Can close in 45 days.',
          routingReason: 'Cash buyer — high score. Matched to A003 by office specialty.',
          isDemo: true,
        },
        {
          listingId: listings[0]?.id,
          assignedAgentId: getRivera(),
          buyerName: 'Midtown Capital Fund III',
          buyerEmail: 'acquisitions@midtowncapital.com',
          buyerType: 'family_office' as const,
          financingStatus: 'pre_approved' as const,
          qualificationScore: 84,
          status: 'showing_scheduled' as const,
          source: 'portal' as const,
          message: 'Looking for 60,000+ sf contiguous for HQ relocation.',
          routingReason: 'Pre-approved buyer. Office need matched to A001.',
          isDemo: true,
        },
        {
          listingId: listings[5]?.id,
          assignedAgentId: getChen(),
          buyerName: 'Cerberus RE Opportunities',
          buyerEmail: 're@cerberus.com',
          buyerType: 'investor' as const,
          financingStatus: 'cash' as const,
          qualificationScore: 78,
          status: 'contacted' as const,
          source: 'direct' as const,
          message: 'Monitoring distressed office for debt play. Need financials.',
          routingReason: 'Distress signal listing — investor profile. Routed to M002.',
          isDemo: true,
        },
        {
          listingId: listings[1]?.id,
          assignedAgentId: null,
          buyerName: 'Red Hook Development LLC',
          buyerEmail: 'info@redhookdev.com',
          buyerType: 'developer' as const,
          financingStatus: 'seeking_financing' as const,
          qualificationScore: 56,
          status: 'new' as const,
          source: 'web' as const,
          message: 'Mixed-use development interest. Need zoning details.',
          routingReason: 'Financing not secured — held for manual review.',
          isDemo: true,
        },
        {
          listingId: listings[3]?.id,
          assignedAgentId: getWilliams(),
          buyerName: 'Atlantic Strip Partners',
          buyerEmail: 'ops@atlanticstrip.com',
          buyerType: 'investor' as const,
          financingStatus: 'pre_approved' as const,
          qualificationScore: 67,
          status: 'qualified' as const,
          source: 'email' as const,
          message: 'Interested in NNN retail. Currently hold 3 Brooklyn retail assets.',
          routingReason: 'Retail investor matched to J004 by retail specialty.',
          isDemo: true,
        },
      ];
      const _inquiries = await db
        .insert(terraInquiriesTable)
        .values(inquiryValues)
        .onConflictDoNothing()
        .returning();

      const txPropertyIds = [properties[2]?.id, properties[1]?.id, properties[4]?.id];
      const txValues = [
        {
          propertyId: txPropertyIds[0],
          agentId: getTorres(),
          brokerageId,
          buyerName: 'Beacon Capital Partners',
          sellerName: 'William Holdings LLC',
          salePrice: '62400000',
          listPrice: '68000000',
          commission: '1248000',
          commissionPct: '2.00',
          daysOnMarket: 94,
          daysToClose: 58,
          closedDate: '2026-02-14',
          financingType: 'cmbs' as const,
          status: 'completed' as const,
          isDemo: true,
        },
        {
          propertyId: txPropertyIds[1],
          agentId: getRivera(),
          brokerageId,
          buyerName: 'North8 Capital',
          sellerName: 'Meserole Family Trust',
          salePrice: '18900000',
          listPrice: '19500000',
          commission: '378000',
          commissionPct: '2.00',
          daysOnMarket: 67,
          daysToClose: 42,
          closedDate: '2026-01-29',
          financingType: 'conventional' as const,
          status: 'completed' as const,
          isDemo: true,
        },
        {
          propertyId: txPropertyIds[2],
          agentId: getRivera(),
          brokerageId,
          buyerName: 'Skylar Logistics Inc',
          sellerName: 'South Bronx Industrial LLC',
          salePrice: '9800000',
          listPrice: '9800000',
          commission: '245000',
          commissionPct: '2.50',
          daysOnMarket: 41,
          daysToClose: 35,
          closedDate: '2026-01-08',
          financingType: 'conventional' as const,
          status: 'completed' as const,
          isDemo: true,
        },
      ];
      const _transactions = await db
        .insert(terraTransactionsTable)
        .values(txValues)
        .onConflictDoNothing()
        .returning();
    }
  }
}
