import { getRuntimeMode, isSeedDataAllowed } from '@szl-holdings/platform-registry';
import {
  db,
  terraAgentsTable,
  terraBrokeragesTable,
  terraConstructionProjectsTable,
  terraDealsTable,
  terraExchanges1031Table,
  terraInquiriesTable,
  terraLeadsTable,
  terraLeasesTable,
  terraListingsTable,
  terraProFormaProjectsTable,
  terraPropertiesTable,
  terraTaxAppealsTable,
  terraTenantApplicationsTable,
  terraTransactionsTable,
} from '@szl-holdings/db';
import { randomUUID } from 'crypto';
import { eq, sql } from 'drizzle-orm';

export async function seedTerraDemo() {
  if (!isSeedDataAllowed()) {
    const mode = getRuntimeMode();
    throw new Error(
      `[terra-seed] Attempted to seed Terra demo data in ${mode} mode. ` +
        `Seed data is only permitted in local-dev, internal-preview, and demo modes.`,
    );
  }

  // Task #2638 added a unique index on terra_properties (address, city, state)
  // so the property insert below is now genuinely idempotent via
  // onConflictDoNothing(). We still keep this all-tables early-return as a
  // cheap fast-path (skips ~50 inserts on hot reload) and surface partial
  // state explicitly so reseed regressions on the *other* terra_* tables
  // remain easy to diagnose.
  const counts = await Promise.all([
    db.select({ c: sql<number>`count(*)::int` }).from(terraBrokeragesTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraAgentsTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraPropertiesTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraListingsTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraInquiriesTable),
    db.select({ c: sql<number>`count(*)::int` }).from(terraTransactionsTable),
  ]);
  const brokerageCount = counts[0][0]?.c ?? 0;
  const agentCountExisting = counts[1][0]?.c ?? 0;
  const propCount = counts[2][0]?.c ?? 0;
  const listingCountExisting = counts[3][0]?.c ?? 0;
  const inquiryCount = counts[4][0]?.c ?? 0;
  const txCount = counts[5][0]?.c ?? 0;
  if (
    brokerageCount > 0 &&
    agentCountExisting > 0 &&
    propCount > 0 &&
    listingCountExisting > 0 &&
    inquiryCount > 0 &&
    txCount > 0
  ) {
    return;
  }
  if (propCount > 0 || agentCountExisting > 0 || brokerageCount > 0) {
    return;
  }

  await db.execute(sql`
    INSERT INTO feature_flags (key, name, description, is_enabled, rollout_percentage, scope, product)
    VALUES
      ('terra_map_mode_enabled', 'Terra Map Mode', 'Activates geospatial property map layer with distress and inquiry heat overlays.', true, 100, 'global', 'terra'),
      ('terra_broker_view_enabled', 'Terra Broker View', 'Enables brokerage-level rollup view with multi-agent comparative analytics.', true, 100, 'global', 'terra')
    ON CONFLICT (key) DO UPDATE SET
      is_enabled = EXCLUDED.is_enabled,
      updated_at = NOW()
  `);

  const [insertedBrokerage] = await db
    .insert(terraBrokeragesTable)
    .values({
      name: 'Terra Commercial',
      slug: 'terra-commercial',
      licenseNumber: 'NY-BRK-2024-001',
      city: 'New York',
      state: 'NY',
      specialty: 'Commercial — Office, Retail, Industrial, Mixed-Use',
      headCount: 4,
      activeListings: 6,
      closedVolumeLtm: '91100000',
      status: 'active',
      isDemo: true,
    })
    .onConflictDoNothing()
    .returning();

  let brokerageId: number;
  if (insertedBrokerage) {
    brokerageId = insertedBrokerage.id;
  } else {
    const [existing] = await db
      .select({ id: terraBrokeragesTable.id })
      .from(terraBrokeragesTable)
      .where(eq(terraBrokeragesTable.slug, 'terra-commercial'))
      .limit(1);
    if (!existing) {
      return;
    }
    brokerageId = existing.id;
  }

  const agentValues = [
    {
      brokerageId,
      firstName: 'Karla',
      lastName: 'Rivera',
      email: 'k.rivera@terra-commercial.com',
      phone: '+1-212-555-0101',
      licenseNumber: 'NY-AG-2020-4441',
      specialty: 'office' as const,
      status: 'active' as const,
      activeListings: 8,
      closedDealsLtm: 14,
      closeRatePct: '68.00',
      avgDaysToContract: 44,
      inquiryConversionPct: '31.00',
      isDemo: true,
    },
    {
      brokerageId,
      firstName: 'Michael',
      lastName: 'Chen',
      email: 'm.chen@terra-commercial.com',
      phone: '+1-212-555-0102',
      licenseNumber: 'NY-AG-2019-3812',
      specialty: 'mixed-use' as const,
      status: 'active' as const,
      activeListings: 6,
      closedDealsLtm: 9,
      closeRatePct: '52.00',
      avgDaysToContract: 62,
      inquiryConversionPct: '22.00',
      isDemo: true,
    },
    {
      brokerageId,
      firstName: 'Alejandro',
      lastName: 'Torres',
      email: 'a.torres@terra-commercial.com',
      phone: '+1-212-555-0103',
      licenseNumber: 'NY-AG-2018-2291',
      specialty: 'office' as const,
      status: 'active' as const,
      activeListings: 11,
      closedDealsLtm: 18,
      closeRatePct: '74.00',
      avgDaysToContract: 38,
      inquiryConversionPct: '38.00',
      isDemo: true,
    },
    {
      brokerageId,
      firstName: 'Joyce',
      lastName: 'Williams',
      email: 'j.williams@terra-commercial.com',
      phone: '+1-212-555-0104',
      licenseNumber: 'NY-AG-2021-5502',
      specialty: 'retail' as const,
      status: 'active' as const,
      activeListings: 4,
      closedDealsLtm: 6,
      closeRatePct: '45.00',
      avgDaysToContract: 78,
      inquiryConversionPct: '18.00',
      isDemo: true,
    },
  ];

  const agents = await db
    .insert(terraAgentsTable)
    .values(agentValues)
    .onConflictDoNothing()
    .returning();
  const agentMap: Record<string, number> = {};
  agents.forEach((a) => {
    agentMap[a.email] = a.id;
  });

  const propertyValues = [
    {
      address: '800 Fifth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10065',
      submarket: 'Midtown East',
      propertyType: 'office' as const,
      sqft: 142000,
      yearBuilt: 1978,
      floors: 28,
      latitude: '40.7636000',
      longitude: '-73.9717000',
      ownerName: 'Fifth Avenue Holdings LLC',
      ownerType: 'llc' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '1420 Harbor Blvd',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11231',
      submarket: 'Red Hook',
      propertyType: 'mixed-use' as const,
      sqft: 58000,
      yearBuilt: 2006,
      floors: 7,
      latitude: '40.6765000',
      longitude: '-74.0062000',
      ownerName: 'Harbor Realty Partners LP',
      ownerType: 'llc' as const,
      zoning: 'M1-6',
      isDemo: true,
    },
    {
      address: '340 Park Avenue South',
      city: 'New York',
      state: 'NY',
      zipCode: '10010',
      submarket: 'Flatiron / NoMad',
      propertyType: 'office' as const,
      sqft: 88000,
      yearBuilt: 1965,
      floors: 22,
      latitude: '40.7437000',
      longitude: '-73.9868000',
      ownerName: 'Park South Properties Trust',
      ownerType: 'trust' as const,
      zoning: 'C5-2',
      isDemo: true,
    },
    {
      address: '620 Atlantic Ave',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Boerum Hill',
      propertyType: 'retail' as const,
      sqft: 14200,
      yearBuilt: 1922,
      floors: 2,
      latitude: '40.6847000',
      longitude: '-73.9769000',
      ownerName: 'Atlantic Grove LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4',
      isDemo: true,
    },
    {
      address: '1800 Westchester Ave',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10472',
      submarket: 'Hunts Point',
      propertyType: 'industrial' as const,
      sqft: 76000,
      yearBuilt: 1994,
      floors: 1,
      latitude: '40.8194000',
      longitude: '-73.8632000',
      ownerName: 'South Bronx Industrial LP',
      ownerType: 'llc' as const,
      zoning: 'M3-1',
      isDemo: true,
    },
    {
      address: '55 Water Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10041',
      submarket: 'Financial District',
      propertyType: 'office' as const,
      sqft: 298000,
      yearBuilt: 1972,
      floors: 54,
      latitude: '40.7024000',
      longitude: '-74.0098000',
      ownerName: 'Water Street Ventures LLC',
      ownerType: 'corporate' as const,
      zoning: 'C6-9',
      isDemo: true,
    },
    {
      address: '125 Fulton Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10038',
      submarket: 'Financial District',
      propertyType: 'mixed-use' as const,
      sqft: 44000,
      yearBuilt: 1962,
      floors: 8,
      latitude: '40.7087000',
      longitude: '-74.0075000',
      ownerName: 'Fulton Heritage LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-4',
      isDemo: true,
    },
    {
      address: '30 Broad Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10004',
      submarket: 'Financial District',
      propertyType: 'office' as const,
      sqft: 67000,
      yearBuilt: 1931,
      floors: 18,
      latitude: '40.7067000',
      longitude: '-74.0118000',
      ownerName: 'Broad Street Capital Partners',
      ownerType: 'llc' as const,
      zoning: 'C5-5',
      isDemo: true,
    },
    {
      address: '250 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10007',
      submarket: 'Civic Center',
      propertyType: 'office' as const,
      sqft: 183000,
      yearBuilt: 1955,
      floors: 22,
      latitude: '40.7136000',
      longitude: '-74.0094000',
      ownerName: 'Broadway Civic Realty Corp',
      ownerType: 'corporate' as const,
      zoning: 'C6-4A',
      isDemo: true,
    },
    {
      address: '11 Park Place',
      city: 'New York',
      state: 'NY',
      zipCode: '10007',
      submarket: 'Tribeca / City Hall',
      propertyType: 'office' as const,
      sqft: 39000,
      yearBuilt: 1914,
      floors: 10,
      latitude: '40.7127000',
      longitude: '-74.0103000',
      ownerName: 'Park Place Acquisitions LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-4A',
      isDemo: true,
    },
    {
      address: '420 Lexington Ave',
      city: 'New York',
      state: 'NY',
      zipCode: '10170',
      submarket: 'Grand Central',
      propertyType: 'office' as const,
      sqft: 351000,
      yearBuilt: 1930,
      floors: 34,
      latitude: '40.7523000',
      longitude: '-73.9762000',
      ownerName: 'Graybar Building Owners LLC',
      ownerType: 'llc' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '405 Park Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      submarket: 'Park Avenue',
      propertyType: 'office' as const,
      sqft: 110000,
      yearBuilt: 1948,
      floors: 20,
      latitude: '40.7591000',
      longitude: '-73.9730000',
      ownerName: 'Park Ave Capital Partners',
      ownerType: 'corporate' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '666 Fifth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10103',
      submarket: 'Midtown',
      propertyType: 'office' as const,
      sqft: 508000,
      yearBuilt: 1957,
      floors: 41,
      latitude: '40.7591000',
      longitude: '-73.9770000',
      ownerName: 'Fifth Ave Tower Holdings Trust',
      ownerType: 'trust' as const,
      zoning: 'C5-2.5',
      isDemo: true,
    },
    {
      address: '1140 Avenue of the Americas',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      submarket: 'Midtown West',
      propertyType: 'office' as const,
      sqft: 424000,
      yearBuilt: 1972,
      floors: 37,
      latitude: '40.7569000',
      longitude: '-73.9815000',
      ownerName: 'Sixth Ave Properties LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-6',
      isDemo: true,
    },
    {
      address: '225 West 34th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10122',
      submarket: 'Penn Plaza / Midtown West',
      propertyType: 'office' as const,
      sqft: 215000,
      yearBuilt: 1925,
      floors: 16,
      latitude: '40.7500000',
      longitude: '-73.9939000',
      ownerName: 'Penn Plaza Ventures LP',
      ownerType: 'llc' as const,
      zoning: 'C6-4.5',
      isDemo: true,
    },
    {
      address: '520 Eighth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10018',
      submarket: 'Garment District',
      propertyType: 'office' as const,
      sqft: 178000,
      yearBuilt: 1948,
      floors: 17,
      latitude: '40.7532000',
      longitude: '-73.9959000',
      ownerName: 'Garment Center Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '350 West 42nd Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      submarket: "Hell's Kitchen",
      propertyType: 'mixed-use' as const,
      sqft: 62000,
      yearBuilt: 2001,
      floors: 11,
      latitude: '40.7584000',
      longitude: '-73.9952000',
      ownerName: 'Westies Gate LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-4',
      isDemo: true,
    },
    {
      address: '147 West 35th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      submarket: 'Midtown South',
      propertyType: 'office' as const,
      sqft: 91000,
      yearBuilt: 1967,
      floors: 14,
      latitude: '40.7505000',
      longitude: '-73.9918000',
      ownerName: 'Midtown South Realty Corp',
      ownerType: 'corporate' as const,
      zoning: 'C6-4M',
      isDemo: true,
    },
    {
      address: '40 West 25th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10010',
      submarket: 'Chelsea',
      propertyType: 'office' as const,
      sqft: 74000,
      yearBuilt: 1909,
      floors: 12,
      latitude: '40.7449000',
      longitude: '-73.9916000',
      ownerName: 'Chelsea Square Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2A',
      isDemo: true,
    },
    {
      address: '180 Tenth Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10011',
      submarket: 'West Chelsea',
      propertyType: 'mixed-use' as const,
      sqft: 48000,
      yearBuilt: 2009,
      floors: 8,
      latitude: '40.7468000',
      longitude: '-74.0043000',
      ownerName: 'High Line Realty Group LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '112 West 18th Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10011',
      submarket: 'Chelsea',
      propertyType: 'office' as const,
      sqft: 33000,
      yearBuilt: 1988,
      floors: 9,
      latitude: '40.7402000',
      longitude: '-73.9975000',
      ownerName: 'Chelsea Crossroads LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2A',
      isDemo: true,
    },
    {
      address: '40 East 52nd Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10022',
      submarket: 'Plaza District',
      propertyType: 'office' as const,
      sqft: 208000,
      yearBuilt: 1956,
      floors: 22,
      latitude: '40.7578000',
      longitude: '-73.9730000',
      ownerName: '52nd Street Holdings Corp',
      ownerType: 'corporate' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '780 Third Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10017',
      submarket: 'Turtle Bay',
      propertyType: 'office' as const,
      sqft: 264000,
      yearBuilt: 1983,
      floors: 36,
      latitude: '40.7562000',
      longitude: '-73.9694000',
      ownerName: 'Third Avenue Office LP',
      ownerType: 'llc' as const,
      zoning: 'C5-3',
      isDemo: true,
    },
    {
      address: '1501 Broadway',
      city: 'New York',
      state: 'NY',
      zipCode: '10036',
      submarket: 'Times Square',
      propertyType: 'office' as const,
      sqft: 476000,
      yearBuilt: 1969,
      floors: 42,
      latitude: '40.7571000',
      longitude: '-73.9869000',
      ownerName: 'Times Square Tower LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-7',
      isDemo: true,
    },
    {
      address: '130 Prince Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      submarket: 'SoHo',
      propertyType: 'retail' as const,
      sqft: 9800,
      yearBuilt: 1885,
      floors: 5,
      latitude: '40.7256000',
      longitude: '-74.0007000',
      ownerName: 'Prince Street Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-5B',
      isDemo: true,
    },
    {
      address: '72 Spring Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      submarket: 'SoHo',
      propertyType: 'mixed-use' as const,
      sqft: 21000,
      yearBuilt: 1890,
      floors: 6,
      latitude: '40.7242000',
      longitude: '-74.0001000',
      ownerName: 'Spring Street Loft Partners',
      ownerType: 'llc' as const,
      zoning: 'M1-5B',
      isDemo: true,
    },
    {
      address: '215 Lafayette Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10012',
      submarket: 'NoHo',
      propertyType: 'mixed-use' as const,
      sqft: 28000,
      yearBuilt: 1911,
      floors: 7,
      latitude: '40.7233000',
      longitude: '-73.9976000',
      ownerName: 'Lafayette Loft Trust',
      ownerType: 'trust' as const,
      zoning: 'M1-5B',
      isDemo: true,
    },
    {
      address: '115 East Houston Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10002',
      submarket: 'Lower East Side',
      propertyType: 'retail' as const,
      sqft: 6400,
      yearBuilt: 1928,
      floors: 3,
      latitude: '40.7226000',
      longitude: '-73.9935000',
      ownerName: 'Houston Street Corp',
      ownerType: 'corporate' as const,
      zoning: 'C4-5X',
      isDemo: true,
    },
    {
      address: '440 Kent Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11249',
      submarket: 'Williamsburg',
      propertyType: 'mixed-use' as const,
      sqft: 72000,
      yearBuilt: 2017,
      floors: 9,
      latitude: '40.7141000',
      longitude: '-73.9701000',
      ownerName: 'Kent Ave Development LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-4',
      isDemo: true,
    },
    {
      address: '25 Kent Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11249',
      submarket: 'Williamsburg North',
      propertyType: 'office' as const,
      sqft: 136000,
      yearBuilt: 2019,
      floors: 8,
      latitude: '40.7207000',
      longitude: '-73.9627000',
      ownerName: 'North Kent Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-4',
      isDemo: true,
    },
    {
      address: '160 Imlay Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11231',
      submarket: 'Red Hook',
      propertyType: 'industrial' as const,
      sqft: 92000,
      yearBuilt: 1947,
      floors: 4,
      latitude: '40.6781000',
      longitude: '-74.0087000',
      ownerName: 'Imlay Industrial Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'M2-1',
      isDemo: true,
    },
    {
      address: '365 Bond Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11231',
      submarket: 'Gowanus',
      propertyType: 'mixed-use' as const,
      sqft: 84000,
      yearBuilt: 2021,
      floors: 10,
      latitude: '40.6787000',
      longitude: '-73.9949000',
      ownerName: 'Gowanus Living LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-6D',
      isDemo: true,
    },
    {
      address: '540 Fourth Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11215',
      submarket: 'Park Slope South',
      propertyType: 'retail' as const,
      sqft: 8200,
      yearBuilt: 1939,
      floors: 2,
      latitude: '40.6641000',
      longitude: '-73.9851000',
      ownerName: 'Fourth Ave Properties LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '85 Fourth Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Boerum Hill',
      propertyType: 'retail' as const,
      sqft: 5100,
      yearBuilt: 1915,
      floors: 3,
      latitude: '40.6868000',
      longitude: '-73.9827000',
      ownerName: 'Fourth & Dean LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4',
      isDemo: true,
    },
    {
      address: '1000 Dean Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11238',
      submarket: 'Crown Heights West',
      propertyType: 'mixed-use' as const,
      sqft: 31000,
      yearBuilt: 2018,
      floors: 6,
      latitude: '40.6742000',
      longitude: '-73.9624000',
      ownerName: 'Dean Street Development LLC',
      ownerType: 'llc' as const,
      zoning: 'R7A',
      isDemo: true,
    },
    {
      address: '75 Flatbush Avenue',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Fort Greene',
      propertyType: 'office' as const,
      sqft: 43000,
      yearBuilt: 1977,
      floors: 7,
      latitude: '40.6890000',
      longitude: '-73.9783000',
      ownerName: 'Flatbush Office Holdings LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '265 Livingston Street',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11201',
      submarket: 'Brooklyn Heights',
      propertyType: 'office' as const,
      sqft: 27000,
      yearBuilt: 1949,
      floors: 8,
      latitude: '40.6899000',
      longitude: '-73.9870000',
      ownerName: 'Livingston Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '1 MetroTech Center',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11201',
      submarket: 'Downtown Brooklyn',
      propertyType: 'office' as const,
      sqft: 588000,
      yearBuilt: 1991,
      floors: 16,
      latitude: '40.6924000',
      longitude: '-73.9851000',
      ownerName: 'Brookfield MetroTech LLC',
      ownerType: 'corporate' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '2 Hanson Place',
      city: 'Brooklyn',
      state: 'NY',
      zipCode: '11217',
      submarket: 'Atlantic Terminal',
      propertyType: 'office' as const,
      sqft: 193000,
      yearBuilt: 1926,
      floors: 26,
      latitude: '40.6839000',
      longitude: '-73.9771000',
      ownerName: 'Hanson Place Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C6-2',
      isDemo: true,
    },
    {
      address: '1090 Jerome Avenue',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10452',
      submarket: 'Concourse Village',
      propertyType: 'retail' as const,
      sqft: 12600,
      yearBuilt: 1945,
      floors: 2,
      latitude: '40.8368000',
      longitude: '-73.9161000',
      ownerName: 'Jerome Ave Commerce LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4D',
      isDemo: true,
    },
    {
      address: '2500 Exterior Street',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10451',
      submarket: 'Port Morris',
      propertyType: 'industrial' as const,
      sqft: 143000,
      yearBuilt: 1967,
      floors: 2,
      latitude: '40.8094000',
      longitude: '-73.9248000',
      ownerName: 'Port Morris Industrial LP',
      ownerType: 'llc' as const,
      zoning: 'M1-1',
      isDemo: true,
    },
    {
      address: '1220 Zerega Avenue',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10462',
      submarket: 'Parkchester',
      propertyType: 'industrial' as const,
      sqft: 58000,
      yearBuilt: 1988,
      floors: 1,
      latitude: '40.8322000',
      longitude: '-73.8588000',
      ownerName: 'Zerega Industrial LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-1',
      isDemo: true,
    },
    {
      address: '3636 Third Avenue',
      city: 'Bronx',
      state: 'NY',
      zipCode: '10456',
      submarket: 'Morrisania',
      propertyType: 'retail' as const,
      sqft: 7400,
      yearBuilt: 1963,
      floors: 1,
      latitude: '40.8274000',
      longitude: '-73.9114000',
      ownerName: 'Third Ave Bronx LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4D',
      isDemo: true,
    },
    {
      address: '670 Forest Avenue',
      city: 'Staten Island',
      state: 'NY',
      zipCode: '10310',
      submarket: 'Port Richmond',
      propertyType: 'retail' as const,
      sqft: 11200,
      yearBuilt: 1972,
      floors: 1,
      latitude: '40.6333000',
      longitude: '-74.1299000',
      ownerName: 'Forest Ave Holdings LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-1',
      isDemo: true,
    },
    {
      address: '1011 Bay Street',
      city: 'Staten Island',
      state: 'NY',
      zipCode: '10305',
      submarket: 'Stapleton',
      propertyType: 'mixed-use' as const,
      sqft: 18400,
      yearBuilt: 1921,
      floors: 3,
      latitude: '40.6238000',
      longitude: '-74.0739000',
      ownerName: 'Bay Street Realty LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '101-15 Jamaica Avenue',
      city: 'Queens',
      state: 'NY',
      zipCode: '11418',
      submarket: 'Richmond Hill',
      propertyType: 'retail' as const,
      sqft: 9600,
      yearBuilt: 1953,
      floors: 2,
      latitude: '40.6998000',
      longitude: '-73.8344000',
      ownerName: 'Jamaica Ave Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '88-18 Sutphin Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11435',
      submarket: 'Jamaica',
      propertyType: 'office' as const,
      sqft: 54000,
      yearBuilt: 1982,
      floors: 8,
      latitude: '40.7023000',
      longitude: '-73.8079000',
      ownerName: 'Jamaica Sutphin Corp',
      ownerType: 'corporate' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '26-01 Queens Plaza North',
      city: 'Queens',
      state: 'NY',
      zipCode: '11101',
      submarket: 'Long Island City',
      propertyType: 'office' as const,
      sqft: 112000,
      yearBuilt: 2003,
      floors: 12,
      latitude: '40.7496000',
      longitude: '-73.9389000',
      ownerName: 'Queens Plaza Partners LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4A',
      isDemo: true,
    },
    {
      address: '4545 Center Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11109',
      submarket: 'Hunters Point',
      propertyType: 'mixed-use' as const,
      sqft: 67000,
      yearBuilt: 2015,
      floors: 9,
      latitude: '40.7442000',
      longitude: '-73.9537000',
      ownerName: 'Hunters Point Dev LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-1A',
      isDemo: true,
    },
    {
      address: '38-01 Queens Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11101',
      submarket: 'Sunnyside',
      propertyType: 'retail' as const,
      sqft: 14800,
      yearBuilt: 1937,
      floors: 2,
      latitude: '40.7445000',
      longitude: '-73.9368000',
      ownerName: 'Queens Blvd Retail LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '14-21 College Point Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11356',
      submarket: 'College Point',
      propertyType: 'industrial' as const,
      sqft: 88000,
      yearBuilt: 1978,
      floors: 1,
      latitude: '40.7819000',
      longitude: '-73.8519000',
      ownerName: 'College Point Industrial LLC',
      ownerType: 'llc' as const,
      zoning: 'M1-1',
      isDemo: true,
    },
    {
      address: '130-30 31st Avenue',
      city: 'Queens',
      state: 'NY',
      zipCode: '11354',
      submarket: 'Flushing',
      propertyType: 'mixed-use' as const,
      sqft: 24000,
      yearBuilt: 2008,
      floors: 5,
      latitude: '40.7614000',
      longitude: '-73.8319000',
      ownerName: 'Flushing Center LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-4',
      isDemo: true,
    },
    {
      address: '40-24 College Point Blvd',
      city: 'Queens',
      state: 'NY',
      zipCode: '11354',
      submarket: 'Flushing West',
      propertyType: 'retail' as const,
      sqft: 8900,
      yearBuilt: 1961,
      floors: 2,
      latitude: '40.7568000',
      longitude: '-73.8355000',
      ownerName: 'Flushing Corridor Retail LLC',
      ownerType: 'llc' as const,
      zoning: 'C4-2',
      isDemo: true,
    },
    {
      address: '22 Merrick Avenue',
      city: 'Queens',
      state: 'NY',
      zipCode: '11385',
      submarket: 'Ridgewood',
      propertyType: 'mixed-use' as const,
      sqft: 17600,
      yearBuilt: 1925,
      floors: 4,
      latitude: '40.7055000',
      longitude: '-73.9014000',
      ownerName: 'Ridgewood Realty Group LLC',
      ownerType: 'llc' as const,
      zoning: 'R6A',
      isDemo: true,
    },
  ];

  const properties = await db
    .insert(terraPropertiesTable)
    .values(propertyValues)
    .onConflictDoNothing()
    .returning();

  if (properties.length > 0 && agents.length > 0) {
    const getRivera = () => agentMap['k.rivera@terra-commercial.com'] ?? agents[0]?.id;
    const getChen = () => agentMap['m.chen@terra-commercial.com'] ?? agents[1]?.id;
    const getTorres = () => agentMap['a.torres@terra-commercial.com'] ?? agents[2]?.id;
    const getWilliams = () => agentMap['j.williams@terra-commercial.com'] ?? agents[3]?.id;

    const listingValues = [
      {
        propertyId: properties[0]?.id,
        agentId: getRivera(),
        brokerageId,
        status: 'active' as const,
        listPrice: '89500000',
        pricePerSqft: '630',
        originalListPrice: '89500000',
        capRate: '5.10',
        noi: '4565000',
        daysOnMarket: 38,
        inquiryCount: 14,
        viewCount: 82,
        priceReductions: 0,
        listDate: '2026-02-20',
        opportunityScore: 87,
        isDemo: true,
      },
      {
        propertyId: properties[1]?.id,
        agentId: getChen(),
        brokerageId,
        status: 'active' as const,
        listPrice: '24800000',
        pricePerSqft: '428',
        originalListPrice: '26500000',
        capRate: '4.80',
        noi: '1190400',
        daysOnMarket: 72,
        inquiryCount: 7,
        viewCount: 34,
        priceReductions: 1,
        listDate: '2026-01-17',
        opportunityScore: 62,
        isDemo: true,
      },
      {
        propertyId: properties[2]?.id,
        agentId: getTorres(),
        brokerageId,
        status: 'active' as const,
        listPrice: '47200000',
        pricePerSqft: '536',
        originalListPrice: '47200000',
        capRate: '5.80',
        noi: '2737600',
        daysOnMarket: 21,
        inquiryCount: 22,
        viewCount: 118,
        priceReductions: 0,
        listDate: '2026-03-07',
        opportunityScore: 94,
        isDemo: true,
      },
      {
        propertyId: properties[3]?.id,
        agentId: getWilliams(),
        brokerageId,
        status: 'active' as const,
        listPrice: '8900000',
        pricePerSqft: '627',
        originalListPrice: '9800000',
        capRate: '4.20',
        noi: '373800',
        daysOnMarket: 115,
        inquiryCount: 3,
        viewCount: 18,
        priceReductions: 2,
        listDate: '2025-12-05',
        opportunityScore: 44,
        isDemo: true,
      },
      {
        propertyId: properties[4]?.id,
        agentId: getRivera(),
        brokerageId,
        status: 'under_contract' as const,
        listPrice: '12400000',
        pricePerSqft: '163',
        originalListPrice: '12400000',
        capRate: '6.20',
        noi: '768800',
        daysOnMarket: 58,
        inquiryCount: 11,
        viewCount: 54,
        priceReductions: 0,
        listDate: '2026-01-31',
        opportunityScore: 79,
        isDemo: true,
      },
      {
        propertyId: properties[5]?.id,
        agentId: getChen(),
        brokerageId,
        status: 'active' as const,
        listPrice: '134000000',
        pricePerSqft: '450',
        originalListPrice: '158000000',
        capRate: '3.90',
        noi: '5226000',
        daysOnMarket: 189,
        inquiryCount: 4,
        viewCount: 22,
        priceReductions: 3,
        listDate: '2025-09-22',
        opportunityScore: 38,
        isDemo: true,
      },
    ];

    const listings = await db
      .insert(terraListingsTable)
      .values(listingValues)
      .onConflictDoNothing()
      .returning();

    if (listings.length > 0) {
      const inquiryValues = [
        {
          listingId: listings[2]?.id,
          assignedAgentId: getTorres(),
          buyerName: 'Apex Partners LP',
          buyerEmail: 'contact@apexpartners.com',
          buyerType: 'investor' as const,
          financingStatus: 'cash' as const,
          qualificationScore: 92,
          status: 'qualified' as const,
          source: 'referral' as const,
          message: 'Interested in full-floor acquisition. Can close in 45 days.',
          routingReason: 'Cash buyer — high score. Matched to A003 by office specialty.',
          isDemo: true,
        },
        {
          listingId: listings[0]?.id,
          assignedAgentId: getRivera(),
          buyerName: 'Midtown Capital Fund III',
          buyerEmail: 'acquisitions@midtowncapital.com',
          buyerType: 'family_office' as const,
          financingStatus: 'pre_approved' as const,
          qualificationScore: 84,
          status: 'showing_scheduled' as const,
          source: 'portal' as const,
          message: 'Looking for 60,000+ sf contiguous for HQ relocation.',
          routingReason: 'Pre-approved buyer. Office need matched to A001.',
          isDemo: true,
        },
        {
          listingId: listings[5]?.id,
          assignedAgentId: getChen(),
          buyerName: 'Cerberus RE Opportunities',
          buyerEmail: 're@cerberus.com',
          buyerType: 'investor' as const,
          financingStatus: 'cash' as const,
          qualificationScore: 78,
          status: 'contacted' as const,
          source: 'direct' as const,
          message: 'Monitoring distressed office for debt play. Need financials.',
          routingReason: 'Distress signal listing — investor profile. Routed to M002.',
          isDemo: true,
        },
        {
          listingId: listings[1]?.id,
          assignedAgentId: null,
          buyerName: 'Red Hook Development LLC',
          buyerEmail: 'info@redhookdev.com',
          buyerType: 'developer' as const,
          financingStatus: 'seeking_financing' as const,
          qualificationScore: 56,
          status: 'new' as const,
          source: 'web' as const,
          message: 'Mixed-use development interest. Need zoning details.',
          routingReason: 'Financing not secured — held for manual review.',
          isDemo: true,
        },
        {
          listingId: listings[3]?.id,
          assignedAgentId: getWilliams(),
          buyerName: 'Atlantic Strip Partners',
          buyerEmail: 'ops@atlanticstrip.com',
          buyerType: 'investor' as const,
          financingStatus: 'pre_approved' as const,
          qualificationScore: 67,
          status: 'qualified' as const,
          source: 'email' as const,
          message: 'Interested in NNN retail. Currently hold 3 Brooklyn retail assets.',
          routingReason: 'Retail investor matched to J004 by retail specialty.',
          isDemo: true,
        },
      ];
      const _inquiries = await db
        .insert(terraInquiriesTable)
        .values(inquiryValues)
        .onConflictDoNothing()
        .returning();

      const txPropertyIds = [properties[2]?.id, properties[1]?.id, properties[4]?.id];
      const txValues = [
        {
          propertyId: txPropertyIds[0],
          agentId: getTorres(),
          brokerageId,
          buyerName: 'Beacon Capital Partners',
          sellerName: 'William Holdings LLC',
          salePrice: '62400000',
          listPrice: '68000000',
          commission: '1248000',
          commissionPct: '2.00',
          daysOnMarket: 94,
          daysToClose: 58,
          closedDate: '2026-02-14',
          financingType: 'cmbs' as const,
          status: 'completed' as const,
          isDemo: true,
        },
        {
          propertyId: txPropertyIds[1],
          agentId: getRivera(),
          brokerageId,
          buyerName: 'North8 Capital',
          sellerName: 'Meserole Family Trust',
          salePrice: '18900000',
          listPrice: '19500000',
          commission: '378000',
          commissionPct: '2.00',
          daysOnMarket: 67,
          daysToClose: 42,
          closedDate: '2026-01-29',
          financingType: 'conventional' as const,
          status: 'completed' as const,
          isDemo: true,
        },
        {
          propertyId: txPropertyIds[2],
          agentId: getRivera(),
          brokerageId,
          buyerName: 'Skylar Logistics Inc',
          sellerName: 'South Bronx Industrial LLC',
          salePrice: '9800000',
          listPrice: '9800000',
          commission: '245000',
          commissionPct: '2.50',
          daysOnMarket: 41,
          daysToClose: 35,
          closedDate: '2026-01-08',
          financingType: 'conventional' as const,
          status: 'completed' as const,
          isDemo: true,
        },
      ];
      const _transactions = await db
        .insert(terraTransactionsTable)
        .values(txValues)
        .onConflictDoNothing()
        .returning();
    }
  }

}

export async function seedTerraOperatingModules() {
  if (!isSeedDataAllowed()) return;
  const [leaseCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraLeasesTable);
  const [taxCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraTaxAppealsTable);
  const [tenantCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraTenantApplicationsTable);
  const [exchangeCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraExchanges1031Table);
  const [proformaCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraProFormaProjectsTable);
  const [constructionCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraConstructionProjectsTable);

  const [dealCount_gate] = await db.select({ c: sql<number>`count(*)::int` }).from(terraDealsTable);
  const [leadCount_gate] = await db.select({ c: sql<number>`count(*)::int` }).from(terraLeadsTable);

  if (
    (leaseCount?.c ?? 0) > 0 &&
    (taxCount?.c ?? 0) > 0 &&
    (tenantCount?.c ?? 0) > 0 &&
    (exchangeCount?.c ?? 0) > 0 &&
    (proformaCount?.c ?? 0) > 0 &&
    (constructionCount?.c ?? 0) > 0 &&
    (dealCount_gate?.c ?? 0) > 0 &&
    (leadCount_gate?.c ?? 0) > 0
  ) {
    return;
  }

  if ((leaseCount?.c ?? 0) === 0) await db
    .insert(terraLeasesTable)
    .values([
      {
        externalId: randomUUID(),
        documentName: 'Meridian_Tech_Lease_Executed.pdf',
        tenant: 'Meridian Technologies Inc.',
        premises: 'Suite 1200, Floors 12–14',
        propertyAddress: '800 Fifth Avenue, New York, NY 10065',
        leaseType: 'Full Service Gross',
        commencementDate: '2022-01-01',
        expirationDate: '2029-12-31',
        baseRent: '48750',
        rentPerSqft: '3.25',
        sqft: 15000,
        escalations: '3% per annum on Jan 1 each lease year',
        options: [
          '2 × 5-year renewal options at 95% of then-market rent',
          'Right of first offer on contiguous space (Suite 1300)',
        ],
        cam: '8500',
        tiAllowance: '1200000',
        securityDeposit: '97500',
        terminationOption: "Tenant termination right effective Jan 1, 2027 with 12-month notice + 6 months' rent fee",
        exclusiveUse: 'No exclusive use clause',
        coTenancy: 'Not applicable',
        confidence: 94,
        flags: [
          { field: 'TI Allowance', issue: 'TI allowance disbursement schedule not specified', severity: 'warning' },
          { field: 'Termination Option', issue: 'Early termination fee of only 6 months may undercut lender hold period', severity: 'warning' },
        ],
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        documentName: 'BrightPath_Health_Lease_Amendment2.pdf',
        tenant: 'BrightPath Health Systems',
        premises: 'Suite 400, Floor 4',
        propertyAddress: '340 Park Avenue South, New York, NY 10010',
        leaseType: 'Modified Gross',
        commencementDate: '2023-06-01',
        expirationDate: '2028-05-31',
        baseRent: '22960',
        rentPerSqft: '2.80',
        sqft: 8200,
        escalations: '2.5% per annum',
        options: ['1 × 3-year renewal at market rent'],
        cam: '4100',
        tiAllowance: '410000',
        securityDeposit: '45920',
        terminationOption: 'None',
        exclusiveUse: 'Medical office use only',
        coTenancy: 'Not applicable',
        confidence: 91,
        flags: [
          { field: 'Use Clause', issue: 'Restrictive medical-only use clause limits re-tenanting options', severity: 'info' },
        ],
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        documentName: 'Vanguard_Legal_NNN_Lease.pdf',
        tenant: 'Vanguard Legal LLP',
        premises: 'Suite 300, Floor 3',
        propertyAddress: '340 Park Avenue South, New York, NY 10010',
        leaseType: 'NNN',
        commencementDate: '2021-03-01',
        expirationDate: '2026-02-28',
        baseRent: '18360',
        rentPerSqft: '2.70',
        sqft: 6800,
        escalations: '3% annual',
        options: [],
        cam: '3400',
        tiAllowance: '0',
        securityDeposit: '36720',
        terminationOption: 'None',
        exclusiveUse: 'General office',
        coTenancy: 'Not applicable',
        confidence: 97,
        flags: [
          { field: 'Expiration', issue: 'Lease expiring within 12 months — begin renewal negotiation', severity: 'warning' },
        ],
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        documentName: 'Apex_Financial_Sublease.pdf',
        tenant: 'Apex Financial Group',
        premises: 'Suite 200, Floor 2',
        propertyAddress: '800 Fifth Avenue, New York, NY 10065',
        leaseType: 'Full Service Gross',
        commencementDate: '2023-06-01',
        expirationDate: '2026-05-31',
        baseRent: '22960',
        rentPerSqft: '2.80',
        sqft: 8200,
        escalations: '2.5% annual',
        options: ['1 × 2-year renewal'],
        cam: '0',
        tiAllowance: '164000',
        securityDeposit: '45920',
        terminationOption: 'None',
        exclusiveUse: 'Financial services',
        coTenancy: 'Not applicable',
        confidence: 89,
        flags: [],
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        documentName: 'Harbor_Retail_Ground_Lease.pdf',
        tenant: 'Brooklyn Roasters LLC',
        premises: 'Ground Floor Retail, Unit A',
        propertyAddress: '1420 Harbor Blvd, Brooklyn, NY 11231',
        leaseType: 'NNN',
        commencementDate: '2024-01-15',
        expirationDate: '2033-12-31',
        baseRent: '12500',
        rentPerSqft: '4.17',
        sqft: 3000,
        escalations: '3% per annum with CPI cap',
        options: ['2 × 5-year renewals at 90% market'],
        cam: '1500',
        tiAllowance: '150000',
        securityDeposit: '37500',
        terminationOption: 'Co-tenancy kick-out if anchor tenant vacates',
        exclusiveUse: 'Coffee shop and café',
        coTenancy: 'Anchor tenant must maintain 70% occupancy in building',
        confidence: 92,
        flags: [
          { field: 'Co-Tenancy', issue: 'Co-tenancy clause may create cascading vacancy risk', severity: 'warning' },
        ],
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        documentName: 'Water_Street_Ventures_Office.pdf',
        tenant: 'Cerulean Capital Management',
        premises: 'Floors 40–42',
        propertyAddress: '55 Water Street, New York, NY 10041',
        leaseType: 'Full Service Gross',
        commencementDate: '2020-09-01',
        expirationDate: '2030-08-31',
        baseRent: '187500',
        rentPerSqft: '5.00',
        sqft: 37500,
        escalations: '2.5% per annum',
        options: ['1 × 10-year renewal at 95% market'],
        cam: '0',
        tiAllowance: '3750000',
        securityDeposit: '375000',
        terminationOption: 'None',
        exclusiveUse: 'Financial services office',
        coTenancy: 'Not applicable',
        confidence: 96,
        flags: [],
        isDemo: true,
      },
    ])
    .onConflictDoNothing();

  if ((taxCount?.c ?? 0) === 0) await db
    .insert(terraTaxAppealsTable)
    .values([
      {
        externalId: randomUUID(),
        name: 'Meridian Commerce Tower',
        address: '800 Fifth Avenue, New York, NY 10065',
        propertyType: 'Class A Office',
        sqft: 142000,
        assessedValue: '28400000',
        avmValue: '21800000',
        taxRate: '2.38',
        overAssessedPct: '30.3',
        annualTax: '675920',
        potentialSavings: '157080',
        appealDeadline: '2026-05-01',
        appealStatus: 'eligible',
        juris: 'New York County',
        comparables: [
          { address: '780 Third Ave', saleDate: 'Nov 2025', salePrice: 62500000, sqft: 264000, pricePerSqft: 237, distance: '0.4 mi' },
          { address: '420 Lexington Ave', saleDate: 'Sep 2025', salePrice: 85000000, sqft: 351000, pricePerSqft: 242, distance: '0.6 mi' },
          { address: '405 Park Ave', saleDate: 'Jul 2025', salePrice: 24200000, sqft: 110000, pricePerSqft: 220, distance: '0.3 mi' },
        ],
        appealStrength: 'strong',
        notes: 'Comparable sales indicate 23–30% over-assessment. File before May 1 deadline.',
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        name: 'Harbor Mixed-Use Complex',
        address: '1420 Harbor Blvd, Brooklyn, NY 11231',
        propertyType: 'Mixed-Use',
        sqft: 58000,
        assessedValue: '14200000',
        avmValue: '12100000',
        taxRate: '2.12',
        overAssessedPct: '17.4',
        annualTax: '301040',
        potentialSavings: '44560',
        appealDeadline: '2026-03-01',
        appealStatus: 'filed',
        juris: 'Kings County',
        comparables: [
          { address: '365 Bond St', saleDate: 'Dec 2025', salePrice: 18900000, sqft: 84000, pricePerSqft: 225, distance: '0.8 mi' },
          { address: '160 Imlay St', saleDate: 'Oct 2025', salePrice: 11400000, sqft: 92000, pricePerSqft: 124, distance: '0.5 mi' },
        ],
        appealStrength: 'moderate',
        notes: 'Appeal filed. Hearing scheduled for Q2 2026.',
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        name: 'Flatiron Office Building',
        address: '340 Park Avenue South, New York, NY 10010',
        propertyType: 'Class B Office',
        sqft: 88000,
        assessedValue: '22000000',
        avmValue: '19500000',
        taxRate: '2.38',
        overAssessedPct: '12.8',
        annualTax: '523600',
        potentialSavings: '59570',
        appealDeadline: '2026-05-01',
        appealStatus: 'eligible',
        juris: 'New York County',
        comparables: [
          { address: '40 W 25th St', saleDate: 'Jan 2026', salePrice: 15500000, sqft: 74000, pricePerSqft: 209, distance: '0.3 mi' },
        ],
        appealStrength: 'moderate',
        notes: 'Moderate over-assessment. Worth filing given low cost of appeal.',
        isDemo: true,
      },
    ])
    .onConflictDoNothing();

  if ((tenantCount?.c ?? 0) === 0) await db
    .insert(terraTenantApplicationsTable)
    .values([
      {
        externalId: randomUUID(),
        name: 'Marcus & Priya Thornton',
        type: 'individual',
        targetUnit: 'Suite 1200, 800 Fifth Avenue (Office)',
        proposedRent: '31250',
        leaseTermMonths: 60,
        submittedDate: '2026-04-01',
        status: 'approved',
        overallScore: 88,
        recommendation: 'approve',
        creditScore: 768,
        annualIncome: '4800000',
        incomeVerified: true,
        rentToIncomeRatio: '7.8',
        priorEvictions: 0,
        backgroundClear: true,
        screeningData: {
          providerName: 'TransUnion SmartMove',
          providerStatus: 'complete',
          creditHistory: 'Excellent — 12yr history, zero delinquencies',
          bankruptcies: 0,
          judgments: 0,
          radarScores: [
            { subject: 'Credit', score: 92 },
            { subject: 'Income', score: 95 },
            { subject: 'Rental Hist.', score: 88 },
            { subject: 'Overall', score: 88 },
          ],
        },
        flags: [
          { type: 'info', text: 'Business entity — verify corporate guarantee terms' },
        ],
        notes: 'Strong applicant. Recommend standard security deposit.',
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        name: 'Eastward Logistics Corp',
        type: 'entity',
        targetUnit: 'Unit 3A, 1800 Westchester Ave (Industrial)',
        proposedRent: '18500',
        leaseTermMonths: 36,
        submittedDate: '2026-04-10',
        status: 'conditional',
        overallScore: 62,
        recommendation: 'conditional',
        creditScore: 680,
        annualIncome: '2200000',
        incomeVerified: false,
        rentToIncomeRatio: '10.1',
        priorEvictions: 0,
        backgroundClear: true,
        screeningData: {
          providerName: 'TransUnion SmartMove',
          providerStatus: 'complete',
          creditHistory: 'Fair — 4yr history, 1 late payment',
          bankruptcies: 0,
          judgments: 0,
          radarScores: [
            { subject: 'Credit', score: 62 },
            { subject: 'Income', score: 55 },
            { subject: 'Rental Hist.', score: 70 },
            { subject: 'Overall', score: 62 },
          ],
        },
        flags: [
          { type: 'warning', text: 'Income not verified — request 2 years audited financials' },
          { type: 'warning', text: 'Rent-to-income ratio exceeds 8% threshold' },
        ],
        notes: 'Conditional approval pending income verification and additional security deposit.',
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        name: 'Sarah Kim',
        type: 'individual',
        targetUnit: 'Suite 600, 340 Park Avenue South (Office)',
        proposedRent: '14200',
        leaseTermMonths: 24,
        submittedDate: '2026-04-15',
        status: 'pending',
        overallScore: 45,
        recommendation: 'decline',
        creditScore: 590,
        annualIncome: '95000',
        incomeVerified: true,
        rentToIncomeRatio: '17.9',
        priorEvictions: 1,
        backgroundClear: false,
        screeningData: {
          providerName: 'TransUnion SmartMove',
          providerStatus: 'complete',
          creditHistory: 'Poor — multiple delinquencies, collections account',
          bankruptcies: 0,
          judgments: 1,
          radarScores: [
            { subject: 'Credit', score: 35 },
            { subject: 'Income', score: 28 },
            { subject: 'Rental Hist.', score: 40 },
            { subject: 'Overall', score: 45 },
          ],
        },
        flags: [
          { type: 'error', text: 'Prior eviction on record (2023)' },
          { type: 'error', text: 'Rent-to-income ratio exceeds 15% — severe affordability concern' },
          { type: 'warning', text: 'Outstanding judgment of $12,400' },
        ],
        notes: 'High risk applicant. Recommend decline or require guarantor.',
        isDemo: true,
      },
    ])
    .onConflictDoNothing();

  if ((exchangeCount?.c ?? 0) === 0) await db
    .insert(terraExchanges1031Table)
    .values([
      {
        externalId: randomUUID(),
        relinquishedProperty: 'Midtown Office Portfolio',
        relinquishedAddress: '420 Lexington Ave, New York, NY 10170',
        saleDate: '2026-03-15',
        salePrice: '85000000',
        adjustedBasis: '52000000',
        deferredGain: '33000000',
        qi: 'First American Exchange Company',
        qiContact: 'Jennifer Walsh, (212) 555-0190',
        status: 'identification',
        identificationDeadline: '2026-04-29',
        exchangeDeadline: '2026-09-11',
        identifiedProperties: [
          { address: '1200 Gateway Blvd, Dallas, TX', price: 48000000, type: 'Class A Office', sqft: 86000, capRate: 5.8 },
          { address: '500 N Michigan Ave, Chicago, IL', price: 62000000, type: 'Class A Office', sqft: 120000, capRate: 5.2 },
          { address: '100 Biscayne Blvd, Miami, FL', price: 38000000, type: 'Mixed-Use', sqft: 72000, capRate: 4.9 },
        ],
        complianceItems: [
          { item: '45-Day Identification', status: 'pending', deadline: '2026-04-29', notes: '3 properties identified' },
          { item: '180-Day Exchange', status: 'pending', deadline: '2026-09-11', notes: 'Awaiting property selection' },
          { item: 'Boot Analysis', status: 'complete', notes: 'No boot expected if full reinvestment' },
          { item: 'QI Escrow Verification', status: 'complete', notes: 'Funds deposited with First American' },
        ],
        taxSavings: '8580000',
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        relinquishedProperty: 'Red Hook Industrial Warehouse',
        relinquishedAddress: '160 Imlay Street, Brooklyn, NY 11231',
        saleDate: '2026-01-08',
        salePrice: '9800000',
        adjustedBasis: '6200000',
        deferredGain: '3600000',
        qi: 'IPX 1031',
        qiContact: 'David Martinez, (800) 555-1031',
        status: 'exchange',
        identificationDeadline: '2026-02-22',
        exchangeDeadline: '2026-07-07',
        identifiedProperties: [
          { address: '800 Commerce Dr, Charlotte, NC', price: 11200000, type: 'Industrial', sqft: 95000, capRate: 6.4 },
        ],
        complianceItems: [
          { item: '45-Day Identification', status: 'complete', deadline: '2026-02-22', notes: 'Property identified on time' },
          { item: '180-Day Exchange', status: 'in-progress', deadline: '2026-07-07', notes: 'Under contract, closing expected June 2026' },
          { item: 'Like-Kind Verification', status: 'complete', notes: 'Both properties qualify as real property' },
          { item: 'QI Escrow Verification', status: 'complete', notes: 'Funds in escrow' },
        ],
        taxSavings: '936000',
        isDemo: true,
      },
    ])
    .onConflictDoNothing();

  if ((proformaCount?.c ?? 0) === 0) await db
    .insert(terraProFormaProjectsTable)
    .values([
      {
        externalId: randomUUID(),
        projectName: 'Gateway Office Acquisition — Base Case',
        propertyType: 'Office',
        inputs: {
          purchasePrice: 47200000,
          closingCosts: 1416000,
          renovationBudget: 2800000,
          loanAmount: 33040000,
          interestRate: 5.25,
          amortizationYears: 30,
          holdPeriodYears: 7,
          exitCapRate: 5.5,
          rentableArea: 88000,
          currentOccupancy: 0.87,
          stabilizedOccupancy: 0.93,
          currentRentPerSqft: 52,
          marketRentPerSqft: 58,
          annualRentGrowth: 3.0,
          opexPerSqft: 18,
          opexGrowthRate: 2.5,
          capexReservePerSqft: 2,
          managementFeePct: 4,
        },
        results: {
          totalCost: 51416000,
          equityRequired: 18376000,
          yearOneNoi: 2737600,
          goingInCapRate: 5.8,
          stabilizedNoi: 3180000,
          exitPrice: 57818182,
          leveragedIrr: 14.2,
          unleveragedIrr: 9.8,
          equityMultiple: 2.1,
          cashOnCash: [5.2, 6.1, 6.8, 7.4, 7.9, 8.3, 8.7],
          debtServiceCoverage: 1.42,
        },
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        projectName: 'Harbor Mixed-Use Value-Add',
        propertyType: 'Mixed-Use',
        inputs: {
          purchasePrice: 24800000,
          closingCosts: 744000,
          renovationBudget: 4200000,
          loanAmount: 17360000,
          interestRate: 5.75,
          amortizationYears: 25,
          holdPeriodYears: 5,
          exitCapRate: 5.0,
          rentableArea: 58000,
          currentOccupancy: 0.72,
          stabilizedOccupancy: 0.95,
          currentRentPerSqft: 38,
          marketRentPerSqft: 52,
          annualRentGrowth: 3.5,
          opexPerSqft: 16,
          opexGrowthRate: 2.5,
          capexReservePerSqft: 3,
          managementFeePct: 5,
        },
        results: {
          totalCost: 29744000,
          equityRequired: 12384000,
          yearOneNoi: 1190400,
          goingInCapRate: 4.8,
          stabilizedNoi: 2088000,
          exitPrice: 41760000,
          leveragedIrr: 18.6,
          unleveragedIrr: 12.4,
          equityMultiple: 2.4,
          cashOnCash: [3.8, 5.9, 8.2, 10.1, 11.4],
          debtServiceCoverage: 1.18,
        },
        isDemo: true,
      },
    ])
    .onConflictDoNothing();

  if ((constructionCount?.c ?? 0) === 0) await db
    .insert(terraConstructionProjectsTable)
    .values([
      {
        externalId: randomUUID(),
        name: 'Harbor Blvd Renovation',
        address: '1420 Harbor Blvd, Brooklyn, NY 11231',
        type: 'Major Renovation',
        totalBudget: '4200000',
        totalSpent: '2730000',
        overallPct: 65,
        startDate: '2025-09-01',
        projectedCompletion: '2026-06-30',
        status: 'on-track',
        gc: 'Titan Construction Group',
        architect: 'Foster + Partners (Associate)',
        milestones: [
          { id: '1', label: 'Demolition & Abatement', dueDate: '2025-10-15', completedDate: '2025-10-12', status: 'complete' },
          { id: '2', label: 'Structural Reinforcement', dueDate: '2025-12-01', completedDate: '2025-12-05', status: 'complete' },
          { id: '3', label: 'MEP Rough-In', dueDate: '2026-02-15', completedDate: '2026-02-10', status: 'complete' },
          { id: '4', label: 'Interior Build-Out', dueDate: '2026-04-30', status: 'in-progress' },
          { id: '5', label: 'Final Inspection & CO', dueDate: '2026-06-30', status: 'upcoming' },
        ],
        budgetLines: [
          { category: 'Demolition', budgeted: 420000, spent: 415000, committed: 0 },
          { category: 'Structural', budgeted: 840000, spent: 825000, committed: 0 },
          { category: 'MEP Systems', budgeted: 1050000, spent: 890000, committed: 120000 },
          { category: 'Interior Finishes', budgeted: 1260000, spent: 480000, committed: 650000 },
          { category: 'Contingency', budgeted: 630000, spent: 120000, committed: 0 },
        ],
        photos: [],
        isDemo: true,
      },
      {
        externalId: randomUUID(),
        name: 'Water Street Lobby Modernization',
        address: '55 Water Street, New York, NY 10041',
        type: 'Tenant Improvement',
        totalBudget: '1800000',
        totalSpent: '360000',
        overallPct: 20,
        startDate: '2026-03-01',
        projectedCompletion: '2026-08-15',
        status: 'on-track',
        gc: 'Plaza Construction',
        architect: 'Gensler',
        milestones: [
          { id: '1', label: 'Design Development', dueDate: '2026-03-15', completedDate: '2026-03-14', status: 'complete' },
          { id: '2', label: 'Permitting', dueDate: '2026-04-15', status: 'in-progress' },
          { id: '3', label: 'Lobby Demolition', dueDate: '2026-05-01', status: 'upcoming' },
          { id: '4', label: 'Installation & Finishes', dueDate: '2026-07-15', status: 'upcoming' },
          { id: '5', label: 'Punch List & Turnover', dueDate: '2026-08-15', status: 'upcoming' },
        ],
        budgetLines: [
          { category: 'Design & Permits', budgeted: 270000, spent: 240000, committed: 30000 },
          { category: 'Demolition', budgeted: 180000, spent: 0, committed: 180000 },
          { category: 'Materials & Fixtures', budgeted: 720000, spent: 120000, committed: 350000 },
          { category: 'Labor', budgeted: 450000, spent: 0, committed: 0 },
          { category: 'Contingency', budgeted: 180000, spent: 0, committed: 0 },
        ],
        photos: [],
        isDemo: true,
      },
    ])
    .onConflictDoNothing();

  const [dealCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraDealsTable);
  if ((dealCount?.c ?? 0) === 0) {
    await db
      .insert(terraDealsTable)
      .values([
        {
          externalId: randomUUID(),
          address: '340 Park Avenue South, New York, NY',
          borough: 'Manhattan',
          county: 'New York',
          zipCode: '10010',
          stage: 'negotiation',
          type: 'acquisition',
          price: '47200000',
          askingPrice: '49500000',
          probability: 65,
          riskLevel: 'medium',
          ownerName: 'Karla Rivera',
          clientName: 'Apex Partners LP',
          nextAction: 'Submit revised LOI at $47.2M',
          notes: 'Seller countered at $49.5M. Client authorized up to $48M.',
          timeline: [
            { date: '2026-03-01', event: 'Initial inquiry received', type: 'inbound' },
            { date: '2026-03-10', event: 'Property tour completed', type: 'activity' },
            { date: '2026-03-18', event: 'LOI submitted at $45M', type: 'milestone' },
            { date: '2026-03-25', event: 'Seller counter at $49.5M', type: 'milestone' },
          ],
          documents: [
            { name: 'LOI - Draft', status: 'sent' },
            { name: 'Financials Package', status: 'received' },
            { name: 'Environmental Phase I', status: 'pending' },
          ],
          isActive: true,
        },
        {
          externalId: randomUUID(),
          address: '55 Water Street, New York, NY',
          borough: 'Manhattan',
          county: 'New York',
          zipCode: '10041',
          stage: 'under-contract',
          type: 'acquisition',
          price: '134000000',
          askingPrice: '158000000',
          probability: 80,
          riskLevel: 'low',
          ownerName: 'Michael Chen',
          clientName: 'Beacon Capital Partners',
          nextAction: 'Complete Phase II environmental',
          notes: 'Under contract at $134M. Due diligence period ends June 15.',
          timeline: [
            { date: '2025-11-15', event: 'Off-market opportunity identified', type: 'inbound' },
            { date: '2026-01-20', event: 'LOI accepted at $134M', type: 'milestone' },
            { date: '2026-02-10', event: 'PSA executed', type: 'milestone' },
            { date: '2026-03-01', event: 'Phase I environmental complete', type: 'activity' },
          ],
          documents: [
            { name: 'PSA - Executed', status: 'complete' },
            { name: 'Phase I ESA', status: 'complete' },
            { name: 'Phase II ESA', status: 'in-progress' },
            { name: 'Title Commitment', status: 'received' },
          ],
          isActive: true,
        },
        {
          externalId: randomUUID(),
          address: '620 Atlantic Ave, Brooklyn, NY',
          borough: 'Brooklyn',
          county: 'Kings',
          zipCode: '11217',
          stage: 'showing',
          type: 'acquisition',
          price: '8900000',
          askingPrice: '9800000',
          probability: 35,
          riskLevel: 'high',
          ownerName: 'Joyce Williams',
          clientName: 'Atlantic Strip Partners',
          nextAction: 'Schedule second property tour',
          notes: 'Client interested but concerned about retail foot traffic trends.',
          timeline: [
            { date: '2026-03-20', event: 'Listing identified', type: 'inbound' },
            { date: '2026-04-02', event: 'Initial tour completed', type: 'activity' },
          ],
          documents: [
            { name: 'Offering Memorandum', status: 'received' },
          ],
          isActive: true,
        },
        {
          externalId: randomUUID(),
          address: '1800 Westchester Ave, Bronx, NY',
          borough: 'Bronx',
          county: 'Bronx',
          zipCode: '10472',
          stage: 'closed',
          type: 'acquisition',
          price: '9800000',
          askingPrice: '9800000',
          probability: 100,
          riskLevel: 'low',
          ownerName: 'Karla Rivera',
          clientName: 'Skylar Logistics Inc',
          actualCloseDate: '2026-01-08',
          notes: 'Closed on schedule. Full asking price. All-cash buyer.',
          timeline: [
            { date: '2025-11-01', event: 'Buyer inquiry', type: 'inbound' },
            { date: '2025-11-20', event: 'Tour + LOI', type: 'milestone' },
            { date: '2025-12-05', event: 'PSA executed', type: 'milestone' },
            { date: '2026-01-08', event: 'Closed', type: 'milestone' },
          ],
          documents: [
            { name: 'Closing Statement', status: 'complete' },
            { name: 'Deed', status: 'recorded' },
          ],
          isActive: false,
        },
      ])
      .onConflictDoNothing();
  }

  const [leadCount] = await db.select({ c: sql<number>`count(*)::int` }).from(terraLeadsTable);
  if ((leadCount?.c ?? 0) === 0) {
    await db
      .insert(terraLeadsTable)
      .values([
        {
          externalId: randomUUID(),
          firstName: 'David',
          lastName: 'Harrington',
          email: 'david@harringtoncapital.com',
          phone: '+1-212-555-0201',
          type: 'investor',
          source: 'distress-engine',
          stage: 'hot',
          score: 88,
          conversionProbability: '0.72',
          ownerName: 'Alejandro Torres',
          lastContact: '2026-04-28',
          nextFollowUp: '2026-05-02',
          budget: { min: 10000000, max: 50000000 },
          desiredAreas: ['Midtown', 'FiDi', 'Chelsea'],
          notes: 'Active buyer. Pre-approved for $35M. Looking for distressed office.',
          tags: ['high-net-worth', 'cash-buyer', 'office'],
          timeline: [
            { date: '2026-04-01', event: 'Distress alert triggered lead', type: 'system' },
            { date: '2026-04-05', event: 'Initial call — strong interest', type: 'call' },
            { date: '2026-04-15', event: 'Toured 3 properties', type: 'tour' },
            { date: '2026-04-28', event: 'Narrowed to 340 Park Ave S', type: 'update' },
          ],
          nextAction: 'Send updated financials for 340 Park Ave S',
          isActive: true,
        },
        {
          externalId: randomUUID(),
          firstName: 'Elena',
          lastName: 'Vasquez',
          email: 'evasquez@redhookdev.com',
          phone: '+1-718-555-0302',
          type: 'buyer',
          source: 'website',
          stage: 'engaged',
          score: 56,
          conversionProbability: '0.35',
          ownerName: 'Michael Chen',
          lastContact: '2026-04-20',
          nextFollowUp: '2026-05-05',
          budget: { min: 15000000, max: 30000000 },
          desiredAreas: ['Red Hook', 'Gowanus', 'Williamsburg'],
          notes: 'Developer seeking mixed-use opportunities in Brooklyn waterfront.',
          tags: ['developer', 'brooklyn', 'mixed-use'],
          timeline: [
            { date: '2026-04-10', event: 'Website inquiry submitted', type: 'system' },
            { date: '2026-04-15', event: 'Qualification call', type: 'call' },
            { date: '2026-04-20', event: 'Sent 2 property packages', type: 'email' },
          ],
          nextAction: 'Schedule tours for Harbor Blvd and Bond St properties',
          isActive: true,
        },
        {
          externalId: randomUUID(),
          firstName: 'James',
          lastName: 'Okonkwo',
          email: 'jokonkwo@certuscapital.com',
          type: 'investor',
          source: 'referral',
          stage: 'new',
          score: 72,
          conversionProbability: '0.45',
          ownerName: 'Karla Rivera',
          desiredAreas: ['Midtown', 'Times Square'],
          notes: 'Referred by existing client. Institutional investor seeking office exposure.',
          tags: ['institutional', 'office', 'referral'],
          timeline: [
            { date: '2026-04-30', event: 'Referral from Beacon Capital', type: 'referral' },
          ],
          nextAction: 'Initial discovery call',
          isActive: true,
        },
      ])
      .onConflictDoNothing();
  }
}
