import { randomUUID } from 'crypto';
import { type IRouter, type Request, type Response, Router } from 'express';
import { z } from 'zod';
import { handleRouteError, sendCreated, sendError, sendNotFound, sendSuccess } from '../lib/api-response';
import { validateBody } from '../lib/validation';
import { logger } from '../lib/logger';

const router: IRouter = Router();

// ────────────────────────────────────────────────────────────────────────────
// In-memory stores — seeded with realistic demo data
// ────────────────────────────────────────────────────────────────────────────

type IncidentSeverity = 'critical' | 'high' | 'medium' | 'low';
type IncidentStatus = 'open' | 'triaging' | 'escalated' | 'contained' | 'resolved';

interface TimelineEntry {
  id: string;
  type: 'detection' | 'system' | 'user' | 'escalation' | 'resolution';
  message: string;
  actor: string;
  timestamp: string;
}

interface Incident {
  id: string;
  title: string;
  description: string;
  severity: IncidentSeverity;
  status: IncidentStatus;
  mitreStage: string;
  detectedAt: string;
  updatedAt: string;
  resolvedAt?: string;
  assignedTo?: string;
  affectedAssets: string[];
  tags: string[];
  timeline: TimelineEntry[];
}

const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString();
const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

const incidentsStore: Map<string, Incident> = new Map([
  [
    'INC-2026-0891',
    {
      id: 'INC-2026-0891',
      title: 'Ransomware-Adjacent OT Payload Detected',
      description:
        'Encrypted payload detected on 3 OT assets (SCADA, PLC). Anomalous C2 beaconing to known malicious IPs. Pattern consistent with LockBit-adjacent tooling.',
      severity: 'critical',
      status: 'triaging',
      mitreStage: 'Execution / C2',
      detectedAt: hoursAgo(4),
      updatedAt: minsAgo(12),
      assignedTo: 'SOC Lead',
      affectedAssets: ['asset-001', 'asset-003'],
      tags: ['ransomware', 'ot', 'c2'],
      timeline: [
        {
          id: 'tl-1',
          type: 'system',
          message: 'Isolation recommendation generated by Signal Mesh',
          actor: 'Signal Mesh',
          timestamp: minsAgo(12),
        },
        {
          id: 'tl-2',
          type: 'detection',
          message: 'Anomalous C2 beacon detected from PLC-003 to 45.227.252.12',
          actor: 'Network Sensor',
          timestamp: minsAgo(30),
        },
        {
          id: 'tl-3',
          type: 'detection',
          message: 'Ransomware payload signature matched on SCADA-01 (SHA-256: a3f1...c9e2)',
          actor: 'EDR Agent',
          timestamp: minsAgo(60),
        },
        {
          id: 'tl-4',
          type: 'system',
          message: 'Incident INC-2026-0891 initialized',
          actor: 'Sentra Engine',
          timestamp: hoursAgo(4),
        },
      ],
    },
  ],
  [
    'INC-2026-0874',
    {
      id: 'INC-2026-0874',
      title: 'Credential Spray on OT Admin Accounts',
      description: '14 failed login attempts on OT-Admin account from lateral IP. Pattern consistent with credential spraying targeting SCADA segment admin accounts.',
      severity: 'high',
      status: 'contained',
      mitreStage: 'Credential Access',
      detectedAt: hoursAgo(8),
      updatedAt: hoursAgo(2),
      assignedTo: 'IR Analyst',
      affectedAssets: ['asset-004'],
      tags: ['credential-spray', 'iam'],
      timeline: [
        {
          id: 'tl-c1',
          type: 'resolution',
          message: 'MFA re-enrollment forced on all OT-Admin accounts',
          actor: 'IR Analyst',
          timestamp: hoursAgo(2),
        },
        {
          id: 'tl-c2',
          type: 'user',
          message: 'Incident assigned and triaging started',
          actor: 'IR Analyst',
          timestamp: hoursAgo(6),
        },
        {
          id: 'tl-c3',
          type: 'detection',
          message: 'IAM detected 14 failed logins on OT-Admin in 30 minutes',
          actor: 'IAM Engine',
          timestamp: hoursAgo(8),
        },
      ],
    },
  ],
]);

interface Alert {
  id: string;
  title: string;
  severity: IncidentSeverity;
  source: string;
  status: 'open' | 'acknowledged' | 'suppressed';
  description: string;
  asset?: string;
  detectedAt: string;
  linkedIncidentId?: string;
}

const alertsStore: Alert[] = [
  {
    id: 'ALT-2026-001',
    title: 'C2 Beacon Detected — 45.227.252.12',
    severity: 'critical',
    source: 'Network Sensor',
    status: 'open',
    description: 'Outbound beacon to known C2 infrastructure at 3-minute intervals from PLC-003.',
    asset: 'asset-003',
    detectedAt: minsAgo(4),
    linkedIncidentId: 'INC-2026-0891',
  },
  {
    id: 'ALT-2026-002',
    title: 'Malware Signature Match — LockBit Adjacent',
    severity: 'critical',
    source: 'EDR',
    status: 'open',
    description: 'Encrypted payload on SCADA Server matched LockBit-adjacent signature.',
    asset: 'asset-001',
    detectedAt: minsAgo(15),
    linkedIncidentId: 'INC-2026-0891',
  },
  {
    id: 'ALT-2026-003',
    title: 'MFA Bypass Attempt on Domain Controller',
    severity: 'high',
    source: 'IAM',
    status: 'acknowledged',
    description: 'Unusual authentication pattern detected — potential MFA bypass via legacy protocol.',
    asset: 'asset-004',
    detectedAt: minsAgo(43),
  },
  {
    id: 'ALT-2026-004',
    title: 'Backup Integrity Check Failed — SCADA-01',
    severity: 'high',
    source: 'Backup Engine',
    status: 'open',
    description: 'Scheduled backup integrity verification failed. Last verified backup: 72h ago.',
    asset: 'asset-001',
    detectedAt: hoursAgo(2),
  },
  {
    id: 'ALT-2026-005',
    title: 'Control Drift: Incident Response Plan',
    severity: 'medium',
    source: 'NIST CSF Scanner',
    status: 'open',
    description: 'Respond family control RC.RP-1 failed automated playbook execution on legacy SCADA systems.',
    detectedAt: hoursAgo(6),
  },
  {
    id: 'ALT-2026-006',
    title: 'HMI Workstation — Patching Overdue',
    severity: 'medium',
    source: 'Patch Manager',
    status: 'suppressed',
    description: 'HMI workstation has pending security patches older than 30 days.',
    asset: 'asset-002',
    detectedAt: hoursAgo(24),
  },
];

// ────────────────────────────────────────────────────────────────────────────
// Zod schemas
// ────────────────────────────────────────────────────────────────────────────

const createIncidentSchema = z.object({
  title: z.string().min(3).max(200),
  description: z.string().min(10).max(2000),
  severity: z.enum(['critical', 'high', 'medium', 'low']),
  mitreStage: z.string().optional().default('Initial Access'),
  affectedAssets: z.array(z.string()).optional().default([]),
  tags: z.array(z.string()).optional().default([]),
  assignedTo: z.string().optional(),
});

const updateIncidentSchema = z.object({
  status: z.enum(['open', 'triaging', 'escalated', 'contained', 'resolved']).optional(),
  assignedTo: z.string().optional(),
  note: z.string().optional(),
  actor: z.string().optional(),
});

const acknowledgeAlertSchema = z.object({
  status: z.enum(['acknowledged', 'suppressed', 'open']),
});

// ────────────────────────────────────────────────────────────────────────────
// Routes
// ────────────────────────────────────────────────────────────────────────────

// GET /api/sentra/incidents
router.get('/sentra/incidents', (_req: Request, res: Response) => {
  try {
    const incidents = Array.from(incidentsStore.values()).sort(
      (a, b) => new Date(b.detectedAt).getTime() - new Date(a.detectedAt).getTime(),
    );
    sendSuccess(res, { incidents, total: incidents.length, source: 'live' });
  } catch (err) {
    handleRouteError(res, err, 'Failed to list incidents');
  }
});

// GET /api/sentra/incidents/:id
router.get('/sentra/incidents/:id', (req: Request, res: Response) => {
  try {
    const incident = incidentsStore.get(req.params.id as string);
    if (!incident) {
      sendNotFound(res, 'Incident');
      return;
    }
    sendSuccess(res, incident);
  } catch (err) {
    handleRouteError(res, err, 'Failed to get incident');
  }
});

// POST /api/sentra/incidents
router.post('/sentra/incidents', validateBody(createIncidentSchema), (req: Request, res: Response) => {
  try {
    const body = req.body as z.infer<typeof createIncidentSchema>;
    const id = `INC-${new Date().getFullYear()}-${String(Math.floor(Math.random() * 9000) + 1000)}`;
    const now = new Date().toISOString();
    const incident: Incident = {
      id,
      title: body.title,
      description: body.description,
      severity: body.severity,
      status: 'open',
      mitreStage: body.mitreStage ?? 'Initial Access',
      detectedAt: now,
      updatedAt: now,
      affectedAssets: body.affectedAssets ?? [],
      tags: body.tags ?? [],
      assignedTo: body.assignedTo,
      timeline: [
        {
          id: randomUUID(),
          type: 'system',
          message: `Incident ${id} created`,
          actor: body.assignedTo ?? 'Operator',
          timestamp: now,
        },
      ],
    };
    incidentsStore.set(id, incident);
    logger.info({ id }, '[sentra] incident created');
    sendCreated(res, incident);
  } catch (err) {
    handleRouteError(res, err, 'Failed to create incident');
  }
});

// PATCH /api/sentra/incidents/:id
router.patch('/sentra/incidents/:id', validateBody(updateIncidentSchema), (req: Request, res: Response) => {
  try {
    const incident = incidentsStore.get(req.params.id as string);
    if (!incident) {
      sendNotFound(res, 'Incident');
      return;
    }
    const body = req.body as z.infer<typeof updateIncidentSchema>;
    const now = new Date().toISOString();
    const prev = incident.status;

    if (body.status) incident.status = body.status;
    if (body.assignedTo !== undefined) incident.assignedTo = body.assignedTo;
    incident.updatedAt = now;

    if (body.status === 'resolved') {
      incident.resolvedAt = now;
    }

    const actor = body.actor ?? incident.assignedTo ?? 'Operator';
    const tlEntry: TimelineEntry = {
      id: randomUUID(),
      type:
        body.status === 'resolved'
          ? 'resolution'
          : body.status === 'escalated'
            ? 'escalation'
            : 'user',
      message:
        body.note ??
        (body.status && body.status !== prev
          ? `Status changed: ${prev} → ${body.status}`
          : body.assignedTo
            ? `Assigned to ${body.assignedTo}`
            : 'Incident updated'),
      actor,
      timestamp: now,
    };
    incident.timeline.unshift(tlEntry);
    incidentsStore.set(incident.id, incident);
    logger.info({ id: incident.id, status: incident.status }, '[sentra] incident updated');
    sendSuccess(res, incident);
  } catch (err) {
    handleRouteError(res, err, 'Failed to update incident');
  }
});

// GET /api/sentra/alerts
router.get('/sentra/alerts', (_req: Request, res: Response) => {
  try {
    const sorted = [...alertsStore].sort(
      (a, b) => new Date(b.detectedAt).getTime() - new Date(a.detectedAt).getTime(),
    );
    sendSuccess(res, { alerts: sorted, total: sorted.length, source: 'live' });
  } catch (err) {
    handleRouteError(res, err, 'Failed to list alerts');
  }
});

// PATCH /api/sentra/alerts/:id
router.patch('/sentra/alerts/:id', validateBody(acknowledgeAlertSchema), (req: Request, res: Response) => {
  try {
    const alert = alertsStore.find((a) => a.id === req.params.id);
    if (!alert) {
      sendNotFound(res, 'Alert');
      return;
    }
    const body = req.body as z.infer<typeof acknowledgeAlertSchema>;
    alert.status = body.status;
    logger.info({ id: alert.id, status: alert.status }, '[sentra] alert updated');
    sendSuccess(res, alert);
  } catch (err) {
    handleRouteError(res, err, 'Failed to update alert');
  }
});

// GET /api/sentra/summary
router.get('/sentra/summary', (_req: Request, res: Response) => {
  try {
    const incidents = Array.from(incidentsStore.values());
    const openIncidents = incidents.filter((i) => !['resolved', 'contained'].includes(i.status));
    const criticalAlerts = alertsStore.filter((a) => a.severity === 'critical' && a.status === 'open');
    sendSuccess(res, {
      source: 'live',
      activeIncidents: openIncidents.length,
      criticalAlerts: criticalAlerts.length,
      totalAlerts: alertsStore.filter((a) => a.status === 'open').length,
      lastUpdated: new Date().toISOString(),
    });
  } catch (err) {
    handleRouteError(res, err, 'Failed to get summary');
  }
});

export default router;
