import { TrendingUp, ArrowUpRight, ArrowDownRight, Minus } from "lucide-react";
import { Link } from "wouter";
import { DEMO_MATTERS } from "../data/demo-matters";

export default function ForecastPage() {
  return (
    <div className="p-6 max-w-[1200px] mx-auto space-y-5">
      <div>
        <h1 className="text-lg font-semibold text-slate-100">Forecast Center</h1>
        <p className="text-xs text-slate-500 mt-0.5">Settlement range forecasting and matter trajectory analysis</p>
      </div>

      <div className="space-y-3">
        {DEMO_MATTERS.map(m => (
          <div key={m.id} className="rounded-lg border border-white/[0.06] p-4" style={{ background: "#0c1220" }}>
            <div className="flex items-center justify-between mb-3">
              <Link href={`/prism-counsel/matters/${m.id}`}>
                <span className="text-sm font-medium text-slate-200 hover:text-[#d4a054] cursor-pointer">{m.title}</span>
              </Link>
              <span className="text-[10px] text-slate-500 font-mono">{m.caseNumber}</span>
            </div>
            <div className="grid grid-cols-4 gap-4">
              <div>
                <div className="text-[10px] text-slate-500 uppercase mb-1">Settlement Range</div>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono text-slate-400">${(m.settlementLow / 1000).toFixed(0)}K</span>
                  <div className="flex-1 h-2 bg-white/[0.06] rounded-full">
                    <div className="h-full rounded-full" style={{ background: "linear-gradient(90deg, #d4a054, #4a90b8)", width: "80%", opacity: 0.5 }} />
                  </div>
                  <span className="text-xs font-mono text-slate-400">${(m.settlementHigh / 1000).toFixed(0)}K</span>
                </div>
                <div className="text-center text-xs font-mono text-[#d4a054] mt-1">${(m.settlementMid / 1000).toFixed(0)}K mid</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500 uppercase mb-1">Total Exposure</div>
                <div className="text-lg font-mono text-slate-200">${(m.totalDamages / 1000).toFixed(0)}K</div>
                <div className="text-[10px] text-slate-500">damages + liens</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500 uppercase mb-1">Health Score</div>
                <div className="text-lg font-mono" style={{ color: m.healthScore >= 70 ? "#4a90b8" : m.healthScore >= 50 ? "#d4a054" : "#c45a4a" }}>{m.healthScore}</div>
                <div className="text-[10px] text-slate-500">{m.status.replace("_", " ")}</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500 uppercase mb-1">Offer Movement</div>
                {(m.offers || []).length >= 2 ? (
                  <>
                    <div className="flex items-center gap-1">
                      <ArrowUpRight className="w-3.5 h-3.5 text-[#4a90b8]" />
                      <span className="text-sm font-mono text-[#4a90b8]">Increasing</span>
                    </div>
                    <div className="text-[10px] text-slate-500">{m.offers.length} offers on record</div>
                  </>
                ) : (
                  <>
                    <div className="flex items-center gap-1">
                      <Minus className="w-3.5 h-3.5 text-slate-500" />
                      <span className="text-sm font-mono text-slate-400">No movement</span>
                    </div>
                    <div className="text-[10px] text-slate-500">{m.offers?.length || 0} offers</div>
                  </>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-lg border border-white/[0.06] p-4" style={{ background: "#0c1220" }}>
        <h3 className="text-xs font-semibold text-slate-300 mb-2">Forecasting Methodology</h3>
        <p className="text-[10px] text-slate-500 leading-relaxed">
          Settlement forecasts are generated by analyzing comparable matter outcomes, medical treatment trajectories, insurer offer patterns, and jurisdiction-specific data. All forecasts include contributing signal explanations, confidence levels, and require human review. Forecasts do not constitute legal advice and should be evaluated by the assigned attorney before informing case strategy.
        </p>
      </div>
    </div>
  );
}
