import type { PlatformFacts } from "./schema.js";

/**
 * Platform facts registry.
 * AUTO-GENERATED by scripts/generate-platform-metrics.ts on 2026-05-02T15:38:14.843Z
 *
 * DO NOT hand-edit structural counts — run the generation script instead.
 * Curated facts are preserved across regenerations.
 */
export const PLATFORM_FACTS: PlatformFacts = {
  generatedAt: "2026-05-02T15:38:14.843Z",
  generatedBy: "generate-platform-metrics",

  structural: {
    artifactCount: 6,
    activeArtifactCount: 2,
    packageCount: 98,
    libCount: 52,
    workerCount: 5,
    serviceCount: 8,
    appCount: 4,
    scriptCount: 91,
  },

  schema: {
    dbTableCount: 1067,
    dbSchemaFileCount: 197,
    dbSchemaDomainCount: 10,
  },

  api: {
    apiRouteGroupCount: 14,
    v1EndpointCount: 18,
    v1EndpointTarget: 18,
  },

  runtime: {
    domainPackCount: 6,
    agentRoleCount: 8,
    cognitiveLoopPhaseCount: 8,
    starterWorkflowCount: 10,
    rbacRoleCount: 11,
    embeddingBackendCount: 5,
    memoryTierCount: 4,
  },

  deployment: {
    deploymentTargets: ["Reserved VM", "Autoscale", "External Workers"],
    primaryRegion: "us-east",
  },

  curated: {
    platformVersion: '4.0.0',
    platformName: 'SZL Holdings Platform',
    platformCodename: 'AEEP',
    foundedYear: 2024,
    lastAuditDate: '2026-04-20',
    authProviders: ['Replit Auth (OIDC/PKCE)', 'Clerk'],
    aiProviders: ['OpenAI', 'Anthropic', 'Google Gemini', 'HuggingFace', 'NVIDIA NIM'],
    externalDataSources: [
      'AIS Maritime (MarineTraffic, AISHub, Digitraffic, BarentsWatch)',
      'STIX/TAXII Threat Intelligence',
      'AlienVault OTX',
      'MISP OSINT',
      'OFAC/UN/EU Sanctions Lists',
      'CISA KEV',
      'NVD CVE',
      'MITRE ATT&CK',
      'CourtListener Legal',
      'SEC EDGAR',
      'NYC Open Data',
      'Open-Meteo Marine Weather',
      'Mapbox Geospatial',
      'GitHub',
      'HubSpot CRM',
    ],
  },
};

export const AEEP_VERSION = PLATFORM_FACTS.curated.platformVersion;
export const AEEP_CODENAME = PLATFORM_FACTS.curated.platformCodename;
