import { useState, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { motion } from "framer-motion";
import {
  Settings, Save, RotateCcw, Clock, Shield, Bell, Archive,
  FileText, CheckCircle2, Loader2, Bot, Globe,
} from "lucide-react";
import { pulseFetch } from "./pulse-utils";

const TEXT = { primary: "hsl(38 8% 95%)", secondary: "hsl(214 7% 64%)", muted: "hsl(214 6% 42%)", faint: "hsl(214 5% 30%)" };
const BG = { surface: "hsla(214 12% 10% / 0.75)", card: "hsla(214 14% 6% / 0.95)" };
const BORDER = { subtle: "hsla(0 0% 100% / 0.055)" };
const PULSE_ACCENT = "hsl(191 92% 44%)";
const PULSE_DIM = "hsla(191 92% 44% / 0.10)";
const PULSE_BORDER = "hsla(191 92% 44% / 0.20)";

type PulseSettings = {
  classification: string;
  autoGenerateDaily: boolean;
  dailyGenerationTime: string;
  defaultDomains: string[];
  defaultAgents: string[];
  notifyOnCritical: boolean;
  dissentsRequireReview: boolean;
  archiveAfterDays: number;
  pdfBranding: string;
};

const ALL_DOMAINS = ["maritime", "security", "analytics", "legal", "infrastructure", "research", "real-estate", "readiness"];
const ALL_AGENTS = [
  { id: "helmsman", label: "Helmsman" },
  { id: "sentinel", label: "Sentinel" },
  { id: "beacon", label: "Terra Analytics" },
  { id: "inca", label: "INCA" },
  { id: "zeus", label: "Zeus" },
  { id: "compass", label: "Compass" },
  { id: "muse", label: "Muse" },
];

function ToggleSwitch({ value, onChange, label }: { value: boolean; onChange: (v: boolean) => void; label: string }) {
  return (
    <label style={{ display: "flex", alignItems: "center", gap: "0.75rem", cursor: "pointer" }}>
      <div
        onClick={() => onChange(!value)}
        style={{
          width: 40, height: 22, borderRadius: 11, position: "relative",
          background: value ? PULSE_ACCENT : "hsla(214 12% 20% / 0.6)",
          border: `1px solid ${value ? PULSE_BORDER : "hsla(0 0% 100% / 0.08)"}`,
          transition: "all 0.2s ease", cursor: "pointer",
        }}
      >
        <div style={{
          width: 16, height: 16, borderRadius: "50%", background: "#fff",
          position: "absolute", top: 2, left: value ? 21 : 2,
          transition: "left 0.2s ease", boxShadow: "0 1px 3px rgba(0,0,0,0.3)",
        }} />
      </div>
      <span style={{ fontSize: 13, color: TEXT.primary }}>{label}</span>
    </label>
  );
}

export default function PulseSettingsPage() {
  const queryClient = useQueryClient();
  const [dirty, setDirty] = useState(false);
  const [localSettings, setLocalSettings] = useState<PulseSettings | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["pulse-settings"],
    queryFn: () => pulseFetch<{ settings: PulseSettings }>("/pulse/settings"),
  });

  useEffect(() => {
    if (data?.settings && !localSettings) {
      setLocalSettings(data.settings);
    }
  }, [data, localSettings]);

  const saveMutation = useMutation({
    mutationFn: () => pulseFetch("/pulse/settings", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(localSettings),
    }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["pulse-settings"] });
      setDirty(false);
    },
  });

  function update<K extends keyof PulseSettings>(key: K, value: PulseSettings[K]) {
    setLocalSettings(prev => prev ? { ...prev, [key]: value } : prev);
    setDirty(true);
  }

  function toggleDomain(d: string) {
    if (!localSettings) return;
    const current = localSettings.defaultDomains;
    update("defaultDomains", current.includes(d) ? current.filter(x => x !== d) : [...current, d]);
  }

  function toggleAgent(id: string) {
    if (!localSettings) return;
    const current = localSettings.defaultAgents;
    update("defaultAgents", current.includes(id) ? current.filter(x => x !== id) : [...current, id]);
  }

  if (isLoading || !localSettings) {
    return (
      <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
        {[1, 2, 3].map(i => <div key={i} style={{ height: 120, borderRadius: 10, background: "hsla(214 12% 10% / 0.5)" }} />)}
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div>
          <h1 style={{ fontFamily: "var(--font-display, Space Grotesk, sans-serif)", fontWeight: 700, fontSize: 22, color: TEXT.primary, marginBottom: "0.375rem" }}>Pulse Settings</h1>
          <p style={{ fontSize: 14, color: TEXT.secondary }}>Configure briefing generation, delivery, and tradecraft preferences</p>
        </div>
        <div style={{ display: "flex", gap: "0.5rem" }}>
          <button
            onClick={() => { setLocalSettings(data?.settings ?? null); setDirty(false); }}
            disabled={!dirty}
            style={{
              display: "flex", alignItems: "center", gap: "0.375rem", padding: "0.5rem 0.875rem", borderRadius: 7,
              border: `1px solid ${BORDER.subtle}`, background: BG.surface, color: dirty ? TEXT.secondary : TEXT.faint,
              fontSize: 13, cursor: dirty ? "pointer" : "default",
            }}
          >
            <RotateCcw size={14} />Reset
          </button>
          <button
            onClick={() => saveMutation.mutate()}
            disabled={!dirty || saveMutation.isPending}
            style={{
              display: "flex", alignItems: "center", gap: "0.375rem", padding: "0.5rem 1rem", borderRadius: 7,
              border: "none", background: dirty ? `linear-gradient(135deg, ${PULSE_ACCENT}, hsl(218 70% 52%))` : "hsla(214 12% 10% / 0.6)",
              color: dirty ? "hsl(214 18% 3%)" : TEXT.muted, fontSize: 13, fontWeight: 700, cursor: dirty ? "pointer" : "default",
            }}
          >
            {saveMutation.isPending ? <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} /> : <Save size={14} />}
            {saveMutation.isPending ? "Saving…" : "Save Changes"}
          </button>
        </div>
      </div>

      {saveMutation.isSuccess && (
        <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}
          style={{ display: "flex", alignItems: "center", gap: "0.5rem", padding: "0.75rem 1rem", borderRadius: 8, background: "hsla(160 65% 42% / 0.08)", border: "1px solid hsla(160 65% 42% / 0.25)", fontSize: 13, color: "hsl(160 65% 48%)" }}>
          <CheckCircle2 size={15} />Settings saved successfully.
        </motion.div>
      )}

      {/* Classification */}
      <div style={{ background: BG.card, border: `1px solid ${BORDER.subtle}`, borderRadius: 10, padding: "1.25rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.875rem" }}>
          <Shield size={16} style={{ color: PULSE_ACCENT }} />
          <span style={{ fontSize: 13, fontWeight: 700, color: TEXT.primary }}>Classification & Branding</span>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.875rem" }}>
          <div>
            <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: TEXT.muted, textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: "0.375rem" }}>Default Classification Banner</label>
            <input
              value={localSettings.classification}
              onChange={e => update("classification", e.target.value)}
              style={{ width: "100%", padding: "0.5rem 0.75rem", borderRadius: 7, border: "1px solid hsla(0 0% 100% / 0.08)", background: "hsla(214 12% 10% / 0.6)", color: TEXT.primary, fontSize: 13, outline: "none", fontFamily: "var(--font-mono, monospace)" }}
            />
          </div>
          <div>
            <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: TEXT.muted, textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: "0.375rem" }}>PDF Branding</label>
            <select
              value={localSettings.pdfBranding}
              onChange={e => update("pdfBranding", e.target.value)}
              style={{ padding: "0.5rem 0.75rem", borderRadius: 7, border: "1px solid hsla(0 0% 100% / 0.08)", background: "hsla(214 12% 10% / 0.6)", color: TEXT.primary, fontSize: 13, cursor: "pointer" }}
            >
              <option value="szl-holdings">SZL Holdings</option>
              <option value="minimal">Minimal</option>
              <option value="executive">Executive</option>
            </select>
          </div>
        </div>
      </div>

      {/* Generation Schedule */}
      <div style={{ background: BG.card, border: `1px solid ${BORDER.subtle}`, borderRadius: 10, padding: "1.25rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.875rem" }}>
          <Clock size={16} style={{ color: PULSE_ACCENT }} />
          <span style={{ fontSize: 13, fontWeight: 700, color: TEXT.primary }}>Generation Schedule</span>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.875rem" }}>
          <ToggleSwitch value={localSettings.autoGenerateDaily} onChange={v => update("autoGenerateDaily", v)} label="Auto-generate daily briefing" />
          <div>
            <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: TEXT.muted, textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: "0.375rem" }}>Daily Generation Time (UTC)</label>
            <input
              type="time"
              value={localSettings.dailyGenerationTime}
              onChange={e => update("dailyGenerationTime", e.target.value)}
              style={{ padding: "0.5rem 0.75rem", borderRadius: 7, border: "1px solid hsla(0 0% 100% / 0.08)", background: "hsla(214 12% 10% / 0.6)", color: TEXT.primary, fontSize: 13, cursor: "pointer" }}
            />
          </div>
        </div>
      </div>

      {/* Default Domains */}
      <div style={{ background: BG.card, border: `1px solid ${BORDER.subtle}`, borderRadius: 10, padding: "1.25rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.875rem" }}>
          <Globe size={16} style={{ color: PULSE_ACCENT }} />
          <span style={{ fontSize: 13, fontWeight: 700, color: TEXT.primary }}>Default Intelligence Domains</span>
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.375rem" }}>
          {ALL_DOMAINS.map(d => {
            const active = localSettings.defaultDomains.includes(d);
            return (
              <button key={d} onClick={() => toggleDomain(d)} style={{
                padding: "0.375rem 0.75rem", borderRadius: 6, border: `1px solid ${active ? PULSE_BORDER : "hsla(0 0% 100% / 0.08)"}`,
                background: active ? PULSE_DIM : "hsla(214 12% 10% / 0.6)", color: active ? PULSE_ACCENT : TEXT.secondary,
                fontSize: 12, cursor: "pointer", fontWeight: active ? 600 : 400, textTransform: "capitalize",
              }}>
                {d}
              </button>
            );
          })}
        </div>
      </div>

      {/* Default Agents */}
      <div style={{ background: BG.card, border: `1px solid ${BORDER.subtle}`, borderRadius: 10, padding: "1.25rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.875rem" }}>
          <Bot size={16} style={{ color: PULSE_ACCENT }} />
          <span style={{ fontSize: 13, fontWeight: 700, color: TEXT.primary }}>Default Contributing Agents</span>
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.375rem" }}>
          {ALL_AGENTS.map(agent => {
            const active = localSettings.defaultAgents.includes(agent.id);
            return (
              <button key={agent.id} onClick={() => toggleAgent(agent.id)} style={{
                padding: "0.375rem 0.75rem", borderRadius: 6, border: `1px solid ${active ? PULSE_BORDER : "hsla(0 0% 100% / 0.08)"}`,
                background: active ? PULSE_DIM : "hsla(214 12% 10% / 0.6)", color: active ? PULSE_ACCENT : TEXT.secondary,
                fontSize: 12, cursor: "pointer", fontWeight: active ? 600 : 400,
              }}>
                {agent.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* Notifications & Dissent */}
      <div style={{ background: BG.card, border: `1px solid ${BORDER.subtle}`, borderRadius: 10, padding: "1.25rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.875rem" }}>
          <Bell size={16} style={{ color: PULSE_ACCENT }} />
          <span style={{ fontSize: 13, fontWeight: 700, color: TEXT.primary }}>Notifications & Dissent</span>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
          <ToggleSwitch value={localSettings.notifyOnCritical} onChange={v => update("notifyOnCritical", v)} label="Notify on critical-risk briefings" />
          <ToggleSwitch value={localSettings.dissentsRequireReview} onChange={v => update("dissentsRequireReview", v)} label="Dissents require mandatory review before resolution" />
        </div>
      </div>

      {/* Archive */}
      <div style={{ background: BG.card, border: `1px solid ${BORDER.subtle}`, borderRadius: 10, padding: "1.25rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.875rem" }}>
          <Archive size={16} style={{ color: PULSE_ACCENT }} />
          <span style={{ fontSize: 13, fontWeight: 700, color: TEXT.primary }}>Archive & Retention</span>
        </div>
        <div>
          <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: TEXT.muted, textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: "0.375rem" }}>Auto-archive briefings older than</label>
          <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
            <input
              type="number"
              value={localSettings.archiveAfterDays}
              onChange={e => update("archiveAfterDays", parseInt(e.target.value, 10) || 90)}
              min={7}
              max={365}
              style={{ width: 80, padding: "0.5rem 0.75rem", borderRadius: 7, border: "1px solid hsla(0 0% 100% / 0.08)", background: "hsla(214 12% 10% / 0.6)", color: TEXT.primary, fontSize: 13, textAlign: "center" }}
            />
            <span style={{ fontSize: 13, color: TEXT.secondary }}>days</span>
          </div>
        </div>
      </div>

      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
