import type { HeadDefinition } from '../types.js';

export const LYTE_HEADS: HeadDefinition[] = [
  {
    name: 'lyte:bottlenecks',
    lane: 'lyte',
    label: 'Workflow Bottleneck Risk',
    description: 'Forecasts the probability and severity of operational bottlenecks in active workflows.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '14d', '30d'],
    alertThreshold: 0.75,
  },
  {
    name: 'lyte:margin-risk',
    lane: 'lyte',
    label: 'Margin Risk Score',
    description: 'Forecasts the risk of margin compression across active engagements.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d', '90d'],
    alertThreshold: 0.7,
  },
  {
    name: 'lyte:ownership-drift',
    lane: 'lyte',
    label: 'Ownership Drift Velocity',
    description: 'Forecasts how quickly decision-ownership is drifting from assigned stakeholders.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d'],
    alertThreshold: 0.6,
  },
  {
    name: 'lyte:escalation-risk',
    lane: 'lyte',
    label: 'Escalation Risk',
    description: 'Forecasts the likelihood of workflow escalation to senior operators.',
    defaultAdapterId: 'safe-default',
    horizons: ['1d', '7d', '14d'],
    alertThreshold: 0.65,
  },
];

export const AEGIS_HEADS: HeadDefinition[] = [
  {
    name: 'aegis:alert-surge',
    lane: 'aegis',
    label: 'Alert Volume Surge',
    description: 'Forecasts surges in alert volume to enable proactive analyst staffing.',
    defaultAdapterId: 'safe-default',
    horizons: ['1d', '3d', '7d'],
    alertThreshold: 0.8,
  },
  {
    name: 'aegis:analyst-overload',
    lane: 'aegis',
    label: 'Analyst Overload Risk',
    description: 'Forecasts analyst queue saturation based on ticket velocity and staffing.',
    defaultAdapterId: 'safe-default',
    horizons: ['1d', '7d', '30d'],
    alertThreshold: 0.7,
  },
  {
    name: 'aegis:control-drift',
    lane: 'aegis',
    label: 'Control Drift Score',
    description: 'Forecasts the probability that security controls will drift below baseline.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d', '90d'],
    alertThreshold: 0.6,
  },
  {
    name: 'aegis:severity-clustering',
    lane: 'aegis',
    label: 'Severity Cluster Momentum',
    description: 'Forecasts the momentum of high-severity alert clusters.',
    defaultAdapterId: 'safe-default',
    horizons: ['1d', '3d', '7d'],
    alertThreshold: 0.75,
  },
];

export const VESSELS_HEADS: HeadDefinition[] = [
  {
    name: 'vessels:route-anomaly',
    lane: 'vessels',
    label: 'Route Anomaly Probability',
    description: 'Forecasts the probability of anomalous route deviations for tracked vessels.',
    defaultAdapterId: 'safe-default',
    horizons: ['6h', '24h', '72h'],
    alertThreshold: 0.65,
  },
  {
    name: 'vessels:sanctions-adjacency',
    lane: 'vessels',
    label: 'Sanctions Adjacency Risk',
    description: 'Forecasts the likelihood of vessels entering sanctions-adjacent proximity.',
    defaultAdapterId: 'safe-default',
    horizons: ['24h', '72h', '7d'],
    alertThreshold: 0.5,
  },
  {
    name: 'vessels:dark-activity',
    lane: 'vessels',
    label: 'Dark Activity Likelihood',
    description: 'Forecasts AIS darkness events and their correlation with illicit activity patterns.',
    defaultAdapterId: 'safe-default',
    horizons: ['6h', '24h', '72h'],
    alertThreshold: 0.55,
  },
  {
    name: 'vessels:insurance-exception',
    lane: 'vessels',
    label: 'Insurance Exception Risk',
    description: 'Forecasts the probability of voyage insurance exception triggers.',
    defaultAdapterId: 'safe-default',
    horizons: ['24h', '7d', '30d'],
    alertThreshold: 0.6,
  },
];

export const TERRA_HEADS: HeadDefinition[] = [
  {
    name: 'terra:distress',
    lane: 'terra',
    label: 'Distress Signal Score',
    description: 'Forecasts distress probability for properties in the monitored portfolio.',
    defaultAdapterId: 'safe-default',
    horizons: ['30d', '60d', '90d'],
    alertThreshold: 0.6,
  },
  {
    name: 'terra:deal-likelihood',
    lane: 'terra',
    label: 'Deal Likelihood',
    description: 'Forecasts the probability of a deal closing within each horizon.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d', '90d'],
  },
  {
    name: 'terra:neighborhood-momentum',
    lane: 'terra',
    label: 'Neighborhood Momentum Index',
    description: 'Forecasts directional momentum for neighborhoods in tracked markets.',
    defaultAdapterId: 'safe-default',
    horizons: ['30d', '90d', '180d'],
  },
  {
    name: 'terra:lead-conversion',
    lane: 'terra',
    label: 'Lead Conversion Rate',
    description: 'Forecasts lead-to-deal conversion rate for active pipeline leads.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d', '90d'],
  },
];

export const COUNSEL_HEADS: HeadDefinition[] = [
  {
    name: 'counsel:deadline-slippage',
    lane: 'counsel',
    label: 'Deadline Slippage Risk',
    description: 'Forecasts the probability of matter deadlines slipping beyond tolerance.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '14d', '30d'],
    alertThreshold: 0.65,
  },
  {
    name: 'counsel:filing-defect',
    lane: 'counsel',
    label: 'Filing Defect Probability',
    description: 'Forecasts the likelihood of filing defects given current document states.',
    defaultAdapterId: 'safe-default',
    horizons: ['1d', '7d', '30d'],
    alertThreshold: 0.5,
  },
  {
    name: 'counsel:recovery',
    lane: 'counsel',
    label: 'Recovery Likelihood',
    description: 'Forecasts the recovery probability for active matters.',
    defaultAdapterId: 'safe-default',
    horizons: ['30d', '90d', '180d'],
  },
  {
    name: 'counsel:staffing-pressure',
    lane: 'counsel',
    label: 'Staffing Pressure Score',
    description: 'Forecasts staffing pressure on matter teams based on deadline density.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '14d', '30d'],
    alertThreshold: 0.7,
  },
  {
    name: 'counsel:obligation-cascade',
    lane: 'counsel',
    label: 'Obligation Cascade Risk',
    description: 'Probability that one missed obligation triggers downstream failures (feature attribution cascade). Backed by Monte Carlo litigation outcome simulation.',
    defaultAdapterId: 'monte-carlo-litigation',
    horizons: ['7d', '14d', '30d'],
    alertThreshold: 0.65,
  },
  {
    name: 'counsel:settlement-likelihood',
    lane: 'counsel',
    label: 'Settlement Likelihood',
    description: 'Monte Carlo posterior — probability of pre-trial settlement across litigation simulation paths. Backed by Monte Carlo litigation outcome simulation.',
    defaultAdapterId: 'monte-carlo-litigation',
    horizons: ['30d', '60d', '90d'],
    alertThreshold: 0.4,
  },
  {
    name: 'counsel:risk-exposure',
    lane: 'counsel',
    label: 'Financial Risk Exposure ($M)',
    description: 'Per-matter total financial exposure distribution from PRISM Monte Carlo litigation cost model.',
    defaultAdapterId: 'monte-carlo-litigation',
    horizons: ['30d', '90d', '180d'],
    alertThreshold: 5,
  },
];

export const CARLOTA_JO_HEADS: HeadDefinition[] = [
  {
    name: 'carlota-jo:demand-spikes',
    lane: 'carlota-jo',
    label: 'Demand Spike Forecast',
    description: 'Forecasts demand spikes across service lines and booking channels.',
    defaultAdapterId: 'safe-default',
    horizons: ['3d', '7d', '14d'],
    alertThreshold: 0.75,
  },
  {
    name: 'carlota-jo:vendor-failure',
    lane: 'carlota-jo',
    label: 'Vendor Failure Risk',
    description: 'Forecasts the probability of critical vendor failures affecting delivery.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d'],
    alertThreshold: 0.6,
  },
  {
    name: 'carlota-jo:booking-conflict',
    lane: 'carlota-jo',
    label: 'Booking Conflict Probability',
    description: 'Forecasts the likelihood of booking conflicts under current capacity.',
    defaultAdapterId: 'safe-default',
    horizons: ['1d', '7d', '14d'],
    alertThreshold: 0.5,
  },
];

export const IMPERIUM_HEADS: HeadDefinition[] = [
  {
    name: 'imperium:cost-drift',
    lane: 'imperium',
    label: 'Cost Drift Score',
    description: 'Forecasts cloud and operational cost drift relative to budget baseline.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d', '90d'],
    alertThreshold: 0.6,
  },
  {
    name: 'imperium:policy-drift',
    lane: 'imperium',
    label: 'Policy Drift Score',
    description: 'Forecasts organizational policy drift from the approved posture.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d', '90d'],
    alertThreshold: 0.55,
  },
  {
    name: 'imperium:tenant-saturation',
    lane: 'imperium',
    label: 'Tenant Saturation Risk',
    description: 'Forecasts the approach to tenant resource saturation thresholds.',
    defaultAdapterId: 'safe-default',
    horizons: ['7d', '30d'],
    alertThreshold: 0.75,
  },
  {
    name: 'imperium:infra-health',
    lane: 'imperium',
    label: 'Infrastructure Health Score',
    description: 'Forecasts degradation in infrastructure health across monitored stacks.',
    defaultAdapterId: 'safe-default',
    horizons: ['24h', '7d', '30d'],
    alertThreshold: 0.4,
  },
];

export const ALL_HEADS: HeadDefinition[] = [
  ...LYTE_HEADS,
  ...AEGIS_HEADS,
  ...VESSELS_HEADS,
  ...TERRA_HEADS,
  ...COUNSEL_HEADS,
  ...CARLOTA_JO_HEADS,
  ...IMPERIUM_HEADS,
];
