apiVersion: v1
kind: Service
metadata:
  name: amaru
  namespace: amaru
  labels:
    app.kubernetes.io/name: amaru
    app.kubernetes.io/part-of: szl-mesh
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: amaru
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
