apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amaru-delta-log
  namespace: amaru
  labels:
    app.kubernetes.io/name: amaru
    app.kubernetes.io/part-of: szl-mesh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
