import { services } from '../../registry.js';
import { ToolConnector } from '../framework.js';
import type { AuthConfig, Capability, ConnectorCategory } from '../types.js';

export class SiemConnector extends ToolConnector {
  readonly id = 'siem';
  readonly name = 'SIEM';
  readonly description =
    'SIEM (Security Information and Event Management) — multi-format log ingestion (CEF, Syslog, Splunk HEC, Sentinel), event normalization, correlation rule evaluation, and alert generation';
  readonly category: ConnectorCategory = 'security';
  readonly version = '1.0.0';

  readonly authConfig: AuthConfig = {
    scheme: 'none',
    requiredEnvVars: [],
    optionalEnvVars: ['SIEM_WEBHOOK_SECRET'],
    description:
      'SIEM adapter operates locally with configurable ingest endpoints. No external API key required for the normalization engine. Set SIEM_WEBHOOK_SECRET to validate inbound event webhooks.',
  };

  readonly capabilities: Capability[] = [
    {
      id: 'ingest_cef',
      name: 'Ingest CEF Events',
      description: 'Ingest and normalize Common Event Format (CEF) log lines',
      parameters: [
        {
          name: 'lines',
          type: 'array',
          description: 'Array of CEF log line strings',
          required: true,
        },
      ],
      requiresAuth: false,
      tags: ['write', 'ingestion', 'cef'],
      rateLimit: { requestsPerMinute: 120, requestsPerHour: 3000 },
    },
    {
      id: 'ingest_syslog',
      name: 'Ingest Syslog Events',
      description: 'Ingest and normalize RFC 5424/3164 Syslog messages',
      parameters: [
        {
          name: 'lines',
          type: 'array',
          description: 'Array of Syslog message strings',
          required: true,
        },
      ],
      requiresAuth: false,
      tags: ['write', 'ingestion', 'syslog'],
      rateLimit: { requestsPerMinute: 120 },
    },
    {
      id: 'ingest_splunk_hec',
      name: 'Ingest Splunk HEC',
      description: 'Ingest events from Splunk HTTP Event Collector payload format',
      parameters: [
        {
          name: 'body',
          type: 'object',
          description: 'Splunk HEC payload body (single event or array)',
          required: true,
        },
      ],
      requiresAuth: false,
      tags: ['write', 'ingestion', 'splunk'],
    },
    {
      id: 'ingest_generic',
      name: 'Ingest Generic JSON Events',
      description: 'Ingest arbitrary JSON security events and normalize them to the SIEM schema',
      parameters: [
        {
          name: 'events',
          type: 'array',
          description: 'Array of JSON event objects',
          required: true,
        },
      ],
      requiresAuth: false,
      tags: ['write', 'ingestion'],
    },
    {
      id: 'get_correlated_alerts',
      name: 'Get Correlated Alerts',
      description: 'Retrieve security alerts generated by the correlation engine',
      parameters: [
        {
          name: 'limit',
          type: 'number',
          description: 'Maximum alerts to return (default 50)',
          required: false,
        },
      ],
      requiresAuth: false,
      tags: ['read', 'alerts'],
    },
    {
      id: 'get_correlation_rules',
      name: 'Get Correlation Rules',
      description: 'Retrieve all configured correlation detection rules',
      parameters: [],
      requiresAuth: false,
      tags: ['read', 'rules'],
    },
    {
      id: 'get_event_stats',
      name: 'Get Event Statistics',
      description:
        'Get ingestion statistics: event counts, severity distribution, source breakdown',
      parameters: [],
      requiresAuth: false,
      tags: ['read', 'analytics'],
    },
  ];

  protected async performCapability(
    capabilityId: string,
    params: Record<string, unknown>,
  ): Promise<unknown> {
    const adapter = services.siem;
    switch (capabilityId) {
      case 'ingest_cef':
        return adapter.ingestCef(Array.isArray(params['lines']) ? params['lines'].map(String) : []);
      case 'ingest_syslog':
        return adapter.ingestSyslog(
          Array.isArray(params['lines']) ? params['lines'].map(String) : [],
        );
      case 'ingest_splunk_hec':
        return adapter.ingestSplunkHec(params['body'] as Record<string, unknown>);
      case 'ingest_generic':
        return adapter.ingestGeneric(
          Array.isArray(params['events'])
            ? (params['events'] as Array<Record<string, unknown>>)
            : [],
        );
      case 'get_correlated_alerts':
        return adapter.getCorrelatedAlerts(params['limit'] ? Number(params['limit']) : 50);
      case 'get_correlation_rules':
        return adapter.getCorrelationRules();
      case 'get_event_stats':
        return adapter.getEventStats();
      default:
        throw new Error(`Unknown capability: ${capabilityId}`);
    }
  }

  protected override async performHealthCheck(): Promise<void> {
    services.siem.getCorrelationRules();
  }
}
