-- Daily Briefings table
-- Stores server-generated daily intelligence summaries keyed by (org_id, briefing_date).
-- Generated by BriefingAggregatorService and cached here for CORTEX daily digest.
-- Required for CORTEX tests to pass on fresh DBs (lib/db/src/schema/daily_briefings.ts).

CREATE TABLE IF NOT EXISTS daily_briefings (
  id                  SERIAL PRIMARY KEY,
  org_id              INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
  briefing_date       TEXT NOT NULL,
  headline            TEXT NOT NULL,
  executive_summary   TEXT NOT NULL,
  signals             JSONB NOT NULL DEFAULT '[]',
  domain_scores       JSONB NOT NULL DEFAULT '{}',
  total_alerts        INTEGER NOT NULL DEFAULT 0,
  critical_count      INTEGER NOT NULL DEFAULT 0,
  high_count          INTEGER NOT NULL DEFAULT 0,
  overall_health      TEXT NOT NULL DEFAULT 'nominal',
  generated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_published        BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS daily_briefings_org_date_idx ON daily_briefings (org_id, briefing_date);
CREATE INDEX IF NOT EXISTS daily_briefings_date_idx ON daily_briefings (briefing_date);
CREATE INDEX IF NOT EXISTS daily_briefings_generated_at_idx ON daily_briefings (generated_at);
