-- Sentra seed: initial incidents and alerts so the app is not empty on first boot.
-- Uses ON CONFLICT DO NOTHING so re-runs are safe.

INSERT INTO sentra_incidents (id, title, description, severity, status, mitre_stage, detected_at, updated_at, assigned_to, affected_assets, tags, timeline)
VALUES
(
  'INC-2026-0891',
  'Ransomware-Adjacent OT Payload Detected',
  'Encrypted payload detected on 3 OT assets (SCADA, PLC). Anomalous C2 beaconing to known malicious IPs. Pattern consistent with LockBit-adjacent tooling.',
  'critical',
  'triaging',
  'Execution / C2',
  NOW() - INTERVAL '4 hours',
  NOW() - INTERVAL '12 minutes',
  'SOC Lead',
  '["asset-001","asset-003"]'::jsonb,
  '["ransomware","ot","c2"]'::jsonb,
  ('[
    {"id":"tl-1","type":"system","message":"Isolation recommendation generated by Signal Mesh","actor":"Signal Mesh","timestamp":"' || (NOW() - INTERVAL '12 minutes')::TEXT || '"},
    {"id":"tl-2","type":"detection","message":"Anomalous C2 beacon detected from PLC-003 to 45.227.252.12","actor":"Network Sensor","timestamp":"' || (NOW() - INTERVAL '30 minutes')::TEXT || '"},
    {"id":"tl-3","type":"detection","message":"Ransomware payload signature matched on SCADA-01 (SHA-256: a3f1...c9e2)","actor":"EDR Agent","timestamp":"' || (NOW() - INTERVAL '60 minutes')::TEXT || '"},
    {"id":"tl-4","type":"system","message":"Incident INC-2026-0891 initialized","actor":"Sentra Engine","timestamp":"' || (NOW() - INTERVAL '4 hours')::TEXT || '"}
  ]')::jsonb
),
(
  'INC-2026-0874',
  'Credential Spray on OT Admin Accounts',
  '14 failed login attempts on OT-Admin account from lateral IP. Pattern consistent with credential spraying targeting SCADA segment admin accounts.',
  'high',
  'contained',
  'Credential Access',
  NOW() - INTERVAL '8 hours',
  NOW() - INTERVAL '2 hours',
  'IR Analyst',
  '["asset-004"]'::jsonb,
  '["credential-spray","iam"]'::jsonb,
  ('[
    {"id":"tl-c1","type":"resolution","message":"MFA re-enrollment forced on all OT-Admin accounts","actor":"IR Analyst","timestamp":"' || (NOW() - INTERVAL '2 hours')::TEXT || '"},
    {"id":"tl-c2","type":"user","message":"Incident assigned and triaging started","actor":"IR Analyst","timestamp":"' || (NOW() - INTERVAL '6 hours')::TEXT || '"},
    {"id":"tl-c3","type":"detection","message":"IAM detected 14 failed logins on OT-Admin in 30 minutes","actor":"IAM Engine","timestamp":"' || (NOW() - INTERVAL '8 hours')::TEXT || '"}
  ]')::jsonb
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sentra_alerts (id, title, severity, source, status, description, asset, detected_at, linked_incident_id)
VALUES
(
  'ALT-2026-001',
  'C2 Beacon Detected — 45.227.252.12',
  'critical',
  'Network Sensor',
  'open',
  'Outbound beacon to known C2 infrastructure at 3-minute intervals from PLC-003.',
  'asset-003',
  NOW() - INTERVAL '4 minutes',
  'INC-2026-0891'
),
(
  'ALT-2026-002',
  'Malware Signature Match — LockBit Adjacent',
  'critical',
  'EDR',
  'open',
  'Encrypted payload on SCADA Server matched LockBit-adjacent signature.',
  'asset-001',
  NOW() - INTERVAL '15 minutes',
  'INC-2026-0891'
),
(
  'ALT-2026-003',
  'MFA Bypass Attempt on Domain Controller',
  'high',
  'IAM',
  'acknowledged',
  'Unusual authentication pattern detected — potential MFA bypass via legacy protocol.',
  'asset-004',
  NOW() - INTERVAL '43 minutes',
  NULL
),
(
  'ALT-2026-004',
  'Backup Integrity Check Failed — SCADA-01',
  'high',
  'Backup Engine',
  'open',
  'Scheduled backup integrity verification failed. Last verified backup: 72h ago.',
  'asset-001',
  NOW() - INTERVAL '2 hours',
  NULL
),
(
  'ALT-2026-005',
  'Control Drift: Incident Response Plan',
  'medium',
  'NIST CSF Scanner',
  'open',
  'Respond family control RC.RP-1 failed automated playbook execution on legacy SCADA systems.',
  NULL,
  NOW() - INTERVAL '6 hours',
  NULL
),
(
  'ALT-2026-006',
  'HMI Workstation — Patching Overdue',
  'medium',
  'Patch Manager',
  'suppressed',
  'HMI workstation has pending security patches older than 30 days.',
  'asset-002',
  NOW() - INTERVAL '24 hours',
  NULL
)
ON CONFLICT (id) DO NOTHING;
