export { ServiceAdapter, type ServiceStatus, type ServiceHealthReport } from "./base.js";
export { ServiceRegistry, type IntegrationHealthMatrix, services } from "./registry.js";

export { AIAdapter, type ChatMessage, type ChatCompletionResult } from "./adapters/ai.js";
export { WeatherAdapter, type WeatherConditions, type WeatherForecastDay } from "./adapters/weather.js";
export { ShippingAdapter, type VesselPosition, type PortInfo } from "./adapters/shipping.js";
export { StripeAdapter, type StripeConnectionStatus, type StripeProduct } from "./adapters/stripe.js";
export { SlackAdapter, type SlackMessageResult } from "./adapters/slack.js";
export { TwilioAdapter, type SMSResult } from "./adapters/twilio.js";
export { GoogleAdapter, type GoogleAuthStatus } from "./adapters/google.js";
export { NotionAdapter, type NotionPage, type NotionDatabase } from "./adapters/notion.js";
export { StorageAdapter, type UploadResult, type StoredFile } from "./adapters/storage.js";
export { MonitoringAdapter, type ErrorReport, type AnalyticsEvent } from "./adapters/monitoring.js";
export { GitHubAdapter, type GitHubRepo, type GitHubWebhookEvent } from "./adapters/github.js";
export { GoogleCalendarAdapter, type CalendarEvent } from "./adapters/google-calendar.js";
export { GoogleDocsAdapter, type GoogleDoc } from "./adapters/google-docs.js";
export { GoogleDriveAdapter, type DriveFile } from "./adapters/google-drive.js";
export { DropboxAdapter, type DropboxFile } from "./adapters/dropbox.js";
export { OneDriveAdapter, type OneDriveFile } from "./adapters/onedrive.js";
export { StormGlassAdapter, type MarineWeather } from "./adapters/stormglass.js";
export { PostHogAdapter, type PostHogEvent, type PostHogInsight } from "./adapters/posthog.js";
export { GmailAdapter, type GmailMessage } from "./adapters/gmail.js";
export { ConfluenceAdapter, type ConfluencePage } from "./adapters/confluence.js";
export { HubSpotAdapter, type HubSpotContact, type HubSpotDeal } from "./adapters/hubspot.js";
export { ElevenLabsAdapter, type ElevenLabsVoice, type TTSResult } from "./adapters/elevenlabs.js";
export { FigmaAdapter, type FigmaFile, type FigmaProject } from "./adapters/figma.js";
