import { useState } from "react";
import { Sun, AlertTriangle, CheckCircle2, TrendingUp, TrendingDown, Shield, Ship, Anchor, ChevronRight, RefreshCw, Volume2, FileText, Zap, Clock, DollarSign } from "lucide-react";

const ACCENT = "hsl(205 70% 50%)";
const BG = { page: "#060e1a", surface: "#08121f", elevated: "#0c1628" } as const;
const BORDER = { subtle: "rgba(255,255,255,0.05)", muted: "rgba(255,255,255,0.09)" } as const;
const TEXT = { primary: "rgba(255,255,255,0.90)", secondary: "rgba(255,255,255,0.55)", tertiary: "rgba(255,255,255,0.28)" } as const;

type Priority = "critical" | "high" | "watch" | "opportunity";

interface BriefSection {
  id: string;
  priority: Priority;
  title: string;
  narrative: string;
  vessel?: string;
  category: string;
  valueAtRisk?: number;
  recommendedAction: string;
  confidence: number;
  timeToAct: string;
  autoGenerated: boolean;
}

const PRIORITY_CONFIG: Record<Priority, { color: string; bg: string; border: string; label: string }> = {
  critical: { color: "#ef4444", bg: "#ef444410", border: "#ef444430", label: "Act Now" },
  high: { color: "#f97316", bg: "#f9731610", border: "#f9731630", label: "Act Today" },
  watch: { color: "#f59e0b", bg: "#f59e0b10", border: "#f59e0b30", label: "Monitor" },
  opportunity: { color: "#22c55e", bg: "#22c55e10", border: "#22c55e30", label: "Opportunity" },
};

const TODAY = new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
const UTC_TIME = new Date().toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "UTC" }) + " UTC";

const BRIEF_ITEMS: BriefSection[] = [
  {
    id: "b-001", priority: "critical",
    title: "MV NOVA ATLAS — OFAC Breach Detected at 03:14 UTC",
    narrative: "At 03:14 UTC, the Autonomous Compliance Autopilot detected a full OFAC SDN designation against Meridian Asset Co, the beneficial owner of MV NOVA ATLAS. The vessel is currently 340nm southwest of Colombo, carrying an undeclared cargo manifest. All financial transactions involving this vessel are now prohibited under IEEPA. Legal hold has been applied automatically. A Suspicious Activity Report has been prepared and is awaiting your sign-off. The vessel's class insurer has been notified. Recommended action: do not process any further voyage-related payments until OFAC counsel confirms safe harbour.",
    vessel: "MV NOVA ATLAS", category: "Compliance Breach",
    valueAtRisk: 4_200_000,
    recommendedAction: "Sign the SAR filing, freeze all NOVA ATLAS accounts, notify P&I Club and charterers immediately. Do not release cargo documents.",
    confidence: 98, timeToAct: "Immediate", autoGenerated: true,
  },
  {
    id: "b-002", priority: "critical",
    title: "CV STELLARIS — Port Congestion Crisis at Singapore ETA +14h",
    narrative: "CV STELLARIS is on approach to Singapore with an ETA of 14 hours. The Predictive Congestion Engine is showing Port of Singapore at 94% berth utilization with 22 vessels in queue — the highest recorded level in 8 months. Based on current throughput rates and the vessel's cargo class, STELLARIS faces a projected 16-hour wait at anchorage. The optimal arrival window opens Friday at 06:00 local. The captain has not yet been advised. If STELLARIS maintains current speed, you will incur an estimated $84,000 in demurrage and detention costs. Slowing now to arrive Friday morning would eliminate 80% of this exposure.",
    vessel: "CV STELLARIS", category: "Port Congestion",
    valueAtRisk: 84_000,
    recommendedAction: "Advise captain to reduce speed to 11 knots, targeting arrival Friday 05:30 SGT. Pre-file all customs docs via MPA's single window today.",
    confidence: 89, timeToAct: "Next 2 hours", autoGenerated: true,
  },
  {
    id: "b-003", priority: "high",
    title: "MT BOREAL SEA — AIS Blackout 14 Hours, Gulf of Aden",
    narrative: "MT BOREAL SEA has been dark on AIS for 14 consecutive hours, last position recorded at the eastern approach to the Gulf of Aden. This is anomalous — the vessel's historical AIS uptime in this corridor is 99.8%. Based on piracy incident frequency models for this corridor and time of year, the risk of a maritime security incident is assessed at HIGH. The vessel is insured for $150M under Gard AS, but the P&I Club has not been notified of the blackout. The Bab-al Mandab Transit Escort Protocol has not been activated. UKMTO has not been filed.",
    vessel: "MT BOREAL SEA", category: "AIS Dark Event",
    valueAtRisk: 12_400_000,
    recommendedAction: "File UKMTO notification immediately. Attempt contact on satellite comms. If no response within 1 hour, activate armed escort protocol and notify Gard AS.",
    confidence: 83, timeToAct: "Next 1 hour", autoGenerated: true,
  },
  {
    id: "b-004", priority: "high",
    title: "MV ATLANTIS COMMAND — Dual-Use Cargo Export License Unresolved",
    narrative: "The cargo manifest for MV ATLANTIS COMMAND includes 14 line items classified under ECCN 5A002 (encryption-capable information security equipment) bound for Singapore. The required UK DIT export licence has not been verified against the consignee's end-user certificate. The vessel departs Port Salalah in approximately 22 hours. If the vessel departs without licence confirmation, it will be in breach of UK Export Control Order 2008. The Compliance Autopilot has raised a BIS check with UK DIT but no response has been received. A manual escalation to the export control team lead is recommended.",
    vessel: "MV ATLANTIS COMMAND", category: "Export Control",
    valueAtRisk: 680_000,
    recommendedAction: "Contact UK DIT export licence team directly. If licence not confirmed by 20:00 UTC tonight, segregate ECCN-classified items for offloading before departure.",
    confidence: 91, timeToAct: "Next 4 hours", autoGenerated: true,
  },
  {
    id: "b-005", priority: "watch",
    title: "Fleet Fuel Performance — ATLANTIC COMMAND Exceeds Budget by 8%",
    narrative: "MV ATLANTIS COMMAND's fuel consumption for the current voyage leg is running 8.2% above budget as of waypoint 3. The Voyage Digital Twin model attributes 5.1% of this to adverse currents in the Arabian Sea and 3.1% to suboptimal speed management between waypoints 1 and 2. If the current trajectory continues, the voyage will exceed its fuel budget by $28,400. The twin's optimal speed scenario (13.8 knots, not current 14.6) would recover most of this variance over the remaining 38 hours. This is within the captain's discretion but should be communicated operationally.",
    vessel: "MV ATLANTIS COMMAND", category: "Voyage Economics",
    recommendedAction: "Transmit revised speed instruction to captain: 13.8 knots from current position through Bab-al Mandab. Estimated fuel saving $22,000.",
    confidence: 86, timeToAct: "Today", autoGenerated: true,
  },
  {
    id: "b-006", priority: "opportunity",
    title: "Fuel Arbitrage — Rotterdam Bunker Spread +12% vs. Fujairah",
    narrative: "Current bunker price spread between Rotterdam (IFO 380: $478/MT) and Fujairah (IFO 380: $426/MT) has widened to 12.2%, the largest gap in 6 months. MT BOREAL SEA's final bunkering port was Jebel Ali at $431/MT. If the vessel's scheduled Rotterdam call can be adjusted to bunker here instead of at Rotterdam, the savings on its 3,400MT uplift would be approximately $176,000. Fleet procurement can lock in the Rotterdam slot for hedging purposes while optimising physical delivery at Fujairah on the next rotation.",
    category: "Fuel Arbitrage",
    recommendedAction: "Instruct procurement to hold Rotterdam hedging contract but route next MT BOREAL SEA bunkering via Fujairah. Lock Fujairah rate today — forward price valid until Thursday.",
    confidence: 78, timeToAct: "Today", autoGenerated: true,
  },
];

const FLEET_PULSE = [
  { label: "Vessels at sea", value: "8", color: ACCENT },
  { label: "In port", value: "3", color: "#22c55e" },
  { label: "AIS dark", value: "1", color: "#ef4444" },
  { label: "Active alerts", value: "6", color: "#f97316" },
  { label: "Compliance flags", value: "3", color: "#a78bfa" },
  { label: "Est. fleet P&L today", value: "$4.2M", color: "#22c55e" },
];

export default function FleetMorningBriefAi() {
  const [expanded, setExpanded] = useState<string | null>("b-001");
  const [played, setPlayed] = useState<Set<string>>(new Set());

  function toggleExpand(id: string) {
    setExpanded(prev => prev === id ? null : id);
  }

  const criticalCount = BRIEF_ITEMS.filter(b => b.priority === "critical").length;

  return (
    <div style={{ background: BG.page, minHeight: "100vh", color: TEXT.primary }}>
      {/* Header */}
      <div style={{ borderBottom: `1px solid ${BORDER.subtle}`, padding: "20px 28px 16px" }}>
        <div className="flex items-center gap-3 mb-3">
          <div style={{ width: 36, height: 36, borderRadius: 8, background: "#f9731618", border: "1px solid #f9731628", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <Sun style={{ color: "#f97316", width: 18, height: 18 }} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 style={{ fontSize: 18, fontWeight: 700, letterSpacing: "-0.01em" }}>Fleet Morning Brief</h1>
              <span style={{ fontSize: 10, padding: "2px 7px", borderRadius: 4, background: "#22c55e12", color: "#22c55e", border: "1px solid #22c55e25", fontWeight: 700 }}>AI NARRATIVE</span>
            </div>
            <p style={{ fontSize: 12, color: TEXT.tertiary, marginTop: 1 }}>{TODAY} · {UTC_TIME} · AI-generated executive intelligence</p>
          </div>
          <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
            <button style={{ display: "flex", alignItems: "center", gap: 4, padding: "6px 12px", borderRadius: 7, border: `1px solid ${BORDER.muted}`, background: BG.surface, color: TEXT.secondary, fontSize: 11, cursor: "pointer" }}>
              <RefreshCw style={{ width: 11, height: 11 }} />
              Regenerate
            </button>
            <button style={{ display: "flex", alignItems: "center", gap: 4, padding: "6px 12px", borderRadius: 7, border: `1px solid ${ACCENT}35`, background: `${ACCENT}12`, color: ACCENT, fontSize: 11, cursor: "pointer" }}>
              <FileText style={{ width: 11, height: 11 }} />
              Export Brief
            </button>
          </div>
        </div>

        {/* Fleet pulse */}
        <div style={{ display: "flex", gap: 12, overflowX: "auto", paddingBottom: 2 }}>
          {FLEET_PULSE.map(p => (
            <div key={p.label} style={{ background: BG.surface, borderRadius: 8, border: `1px solid ${BORDER.subtle}`, padding: "8px 14px", flexShrink: 0 }}>
              <div style={{ fontSize: 16, fontWeight: 700, color: p.color, fontVariantNumeric: "tabular-nums" }}>{p.value}</div>
              <div style={{ fontSize: 9, color: TEXT.tertiary, marginTop: 1, whiteSpace: "nowrap" }}>{p.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* AI intro paragraph */}
      <div style={{ padding: "20px 28px 0" }}>
        <div style={{ background: `${ACCENT}08`, border: `1px solid ${ACCENT}18`, borderRadius: 12, padding: "16px 18px", marginBottom: 20 }}>
          <div className="flex items-center gap-2 mb-3">
            <Zap style={{ width: 13, height: 13, color: ACCENT }} />
            <span style={{ fontSize: 10, fontWeight: 700, color: ACCENT, textTransform: "uppercase", letterSpacing: "0.08em" }}>Executive Intelligence Summary</span>
          </div>
          <p style={{ fontSize: 13, color: TEXT.primary, lineHeight: 1.75 }}>
            This morning's fleet status requires your immediate attention on <span style={{ color: "#ef4444", fontWeight: 700 }}>{criticalCount} critical issues</span>. The most urgent: a full OFAC sanctions breach has been detected against the beneficial owner of MV NOVA ATLAS — all transactions must cease immediately and a SAR filing awaits your signature. Separately, MT BOREAL SEA has been dark for 14 hours in a high-risk piracy corridor and requires an immediate UKMTO filing. On a positive note, a $176,000 bunker arbitrage opportunity is available for the MT BOREAL SEA rotation — recommend locking the Fujairah rate before Thursday.
          </p>
        </div>

        {/* Brief items */}
        <div style={{ display: "flex", flexDirection: "column", gap: 10, paddingBottom: 32 }}>
          {BRIEF_ITEMS.map(item => {
            const cfg = PRIORITY_CONFIG[item.priority];
            const isOpen = expanded === item.id;
            return (
              <div
                key={item.id}
                style={{
                  background: isOpen ? `${cfg.color}06` : BG.surface,
                  border: `1px solid ${isOpen ? cfg.color + "28" : BORDER.subtle}`,
                  borderRadius: 12, overflow: "hidden", transition: "all 0.15s",
                }}
              >
                {/* Header row */}
                <button
                  onClick={() => toggleExpand(item.id)}
                  className="w-full"
                  style={{ padding: "14px 18px", display: "flex", alignItems: "flex-start", gap: 12, cursor: "pointer", background: "none", border: "none", textAlign: "left" }}
                >
                  <div style={{ width: 8, height: 8, borderRadius: "50%", background: cfg.color, flexShrink: 0, marginTop: 5 }} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span style={{ fontSize: 9, padding: "2px 6px", borderRadius: 3, background: cfg.bg, color: cfg.color, fontWeight: 700, border: `1px solid ${cfg.border}`, flexShrink: 0 }}>{cfg.label}</span>
                      <span style={{ fontSize: 11, fontWeight: 700, color: TEXT.primary }}>{item.title}</span>
                    </div>
                    <div className="flex items-center gap-10 flex-wrap">
                      {item.vessel && <span style={{ fontSize: 10, color: TEXT.tertiary }}>{item.vessel}</span>}
                      <span style={{ fontSize: 10, color: TEXT.tertiary }}>{item.category}</span>
                      <span style={{ fontSize: 10, color: item.priority === "critical" ? "#ef4444" : TEXT.tertiary }}>
                        <Clock style={{ width: 9, height: 9, display: "inline", marginRight: 2 }} />
                        {item.timeToAct}
                      </span>
                      {item.valueAtRisk && (
                        <span style={{ fontSize: 10, color: "#f97316" }}>
                          <DollarSign style={{ width: 9, height: 9, display: "inline" }} />
                          {(item.valueAtRisk / 1000).toFixed(0)}K at risk
                        </span>
                      )}
                      {item.autoGenerated && (
                        <span style={{ fontSize: 9, color: ACCENT, background: `${ACCENT}10`, padding: "1px 5px", borderRadius: 3 }}>AI</span>
                      )}
                    </div>
                  </div>
                  <div style={{ flexShrink: 0, marginTop: 2 }}>
                    <ChevronRight style={{ width: 14, height: 14, color: TEXT.tertiary, transform: isOpen ? "rotate(90deg)" : "rotate(0)", transition: "transform 0.2s" }} />
                  </div>
                </button>

                {/* Expanded narrative */}
                {isOpen && (
                  <div style={{ padding: "0 18px 16px 38px" }}>
                    <div style={{ borderLeft: `2px solid ${cfg.color}30`, paddingLeft: 16, marginBottom: 14 }}>
                      <p style={{ fontSize: 13, color: TEXT.secondary, lineHeight: 1.75 }}>{item.narrative}</p>
                    </div>

                    <div style={{ background: `${cfg.color}08`, border: `1px solid ${cfg.color}20`, borderRadius: 9, padding: "10px 14px", marginBottom: 12 }}>
                      <div style={{ fontSize: 9, color: cfg.color, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 5 }}>Recommended Action</div>
                      <p style={{ fontSize: 12, color: TEXT.primary, lineHeight: 1.55, fontWeight: 500 }}>{item.recommendedAction}</p>
                    </div>

                    <div className="flex items-center gap-10">
                      <div style={{ fontSize: 10, color: TEXT.tertiary }}>
                        AI Confidence: <span style={{ color: TEXT.secondary, fontWeight: 600 }}>{item.confidence}%</span>
                      </div>
                      <div style={{ flex: 1, height: 3, borderRadius: 2, background: "rgba(255,255,255,0.06)" }}>
                        <div style={{ width: `${item.confidence}%`, height: "100%", borderRadius: 2, background: cfg.color }} />
                      </div>
                      <button
                        onClick={() => setPlayed(p => { const n = new Set(p); n.add(item.id); return n; })}
                        style={{ display: "flex", alignItems: "center", gap: 4, fontSize: 10, color: played.has(item.id) ? "#22c55e" : TEXT.tertiary, cursor: "pointer", background: "none", border: "none", padding: 0 }}
                      >
                        {played.has(item.id) ? <CheckCircle2 style={{ width: 12, height: 12 }} /> : <CheckCircle2 style={{ width: 12, height: 12 }} />}
                        {played.has(item.id) ? "Acknowledged" : "Acknowledge"}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
