export const HTTP_ATTRS = {
  METHOD: 'http.request.method',
  URL: 'url.full',
  TARGET: 'url.path',
  SCHEME: 'url.scheme',
  STATUS_CODE: 'http.response.status_code',
  ROUTE: 'http.route',
  CLIENT_IP: 'client.address',
  USER_AGENT: 'user_agent.original',
  SERVER_ADDRESS: 'server.address',
  SERVER_PORT: 'server.port',
  REQUEST_BODY_SIZE: 'http.request.body.size',
  RESPONSE_BODY_SIZE: 'http.response.body.size',
} as const;

export const SZL_ATTRS = {
  CORRELATION_ID: 'szl.correlation_id',
  REQUEST_ID: 'szl.request_id',
  TENANT_ID: 'szl.tenant_id',
  ORG_ID: 'szl.org_id',
  USER_ID: 'szl.user_id',
  SESSION_ID: 'szl.session_id',
  SERVICE_NAME: 'szl.service.name',
  SERVICE_VERSION: 'szl.service.version',
  ENVIRONMENT: 'szl.environment',
  DEPLOYMENT_ID: 'szl.deployment.id',
  DOMAIN: 'szl.domain',
  WORKFLOW_ID: 'szl.workflow_id',
  JOB_ID: 'szl.job_id',
  DURATION_MS: 'szl.duration_ms',
  DB_QUERY_MS: 'szl.db_query_ms',
  EXTERNAL_API_MS: 'szl.external_api_ms',
  SERIALIZATION_MS: 'szl.serialization_ms',
} as const;

export const SPAN_NAMES = {
  HTTP_REQUEST: 'http.server.request',
  HTTP_CLIENT: 'http.client.request',
  DB_QUERY: 'db.query',
  DB_TRANSACTION: 'db.transaction',
  CACHE_GET: 'cache.get',
  CACHE_SET: 'cache.set',
  QUEUE_PUBLISH: 'queue.publish',
  QUEUE_CONSUME: 'queue.consume',
  WORKFLOW_START: 'alloy.workflow.start',
  WORKFLOW_STEP: 'alloy.workflow.step.execute',
  WORKFLOW_COMPLETE: 'alloy.workflow.complete',
  AUTH_VERIFY: 'auth.verify',
  AUTH_TOKEN_REFRESH: 'auth.token.refresh',
  JOB_RUN: 'job.run',
  AGENT_INVOKE: 'agent.invoke',
} as const;
