import { useState, useEffect } from "react";
import { m, AnimatePresence } from "framer-motion";
import { Link } from "wouter";
import { Plus, Minus, ArrowRight, HelpCircle } from "lucide-react";
import { SiteNav } from "@/components/SiteNav";
import { SiteFooter } from "@/components/SiteFooter";
import { usePageMeta } from "@/hooks/usePageMeta";

const FAQ_GROUPS = [
  {
    group: "Company & Category",
    color: "hsl(38,52%,58%)",
    questions: [
      {
        q: "What is SZL Holdings?",
        a: "SZL Holdings is building governed decision infrastructure — the structural layer between signal detection and action execution. The core platform — Lyte + Counsel — is a shared execution fabric deployed across multiple domain-specific packs: Counsel (legal operations), Vessels (maritime), Aegis (security and defense), and Terra (real estate).",
      },
      {
        q: "What is business observability?",
        a: "Business observability is the capability to detect operational signals — approval latency, ownership gaps, execution risk, threshold crossings — and route them to the right people with the right context, in a structured and auditable workflow. It is not a dashboard. Dashboards show what happened. Observability shows what needs to happen next.",
      },
      {
        q: "What stage is the company?",
        a: "SZL Holdings is in the design-partner phase. The platform is live and functional — not vaporware. Active engagement with early enterprise teams is underway for Counsel. No fake revenue figures, client counts, or audit certifications are claimed.",
      },
      {
        q: "What is Lyte + Counsel?",
        a: "Lyte is the command layer — it surfaces signals from connected systems and presents them in a structured, prioritized format for operator action. Counsel is the execution fabric — it routes signals to recommendations, manages the human-in-the-loop approval chain, and executes approved actions through a connector mesh.",
      },
    ],
  },
  {
    group: "Product & Architecture",
    color: "var(--color-lyte-light)",
    questions: [
      {
        q: "How does the signal-to-action pipeline work?",
        a: "Signals are ingested from connected systems and classified by type, severity, and urgency. They are enriched with context (owner attribution, historical pattern, risk scoring) and passed to Counsel, which generates a structured recommendation. That recommendation is reviewed and approved by a human before any execution takes place. The full pipeline — signal, interpretation, recommendation, approval decision, execution, outcome — is written to an immutable audit trail.",
      },
      {
        q: "Does the AI make decisions autonomously?",
        a: "No. AI in Lyte + Counsel is advisory. Every consequential action requires explicit human approval before execution. Human-in-the-loop gates are built into the Counsel execution model at the action-type level. They cannot be bypassed without creating an explicit override record — which is itself logged and flagged for mandatory review.",
      },
      {
        q: "What is multi-tenant isolation?",
        a: "Each tenant has an isolated signal and workflow namespace. Cross-tenant data access is architecturally prevented — not just policy-enforced. Organization-scoped queries and middleware ensure that data from one tenant cannot be accessed by another, even by platform operators.",
      },
      {
        q: "What is a domain pack?",
        a: "Domain packs are vertical-specific configurations of the Lyte + Counsel platform. They provide domain-specific signal vocabulary, workflow logic, and twin models for a particular operating domain (legal, maritime, defense, real estate). They do not bypass the core governance model — they extend it.",
      },
      {
        q: "What is the Proof Chain?",
        a: "The Proof Chain is the complete lineage record for every output — document, report, or decision — generated by the platform. Every claim in an output links to the source signal, the twin state at decision time, and the approval record. This chain travels with the export for review, archive, and regulatory use.",
      },
    ],
  },
  {
    group: "Trust & Security",
    color: "hsl(145,62%,46%)",
    questions: [
      {
        q: "Is SOC 2 certified?",
        a: "SOC 2 Type II audit preparation is underway. Expected completion is Q3 2026. We do not claim certifications we do not have. Current security controls are documented on the Security and Trust Center pages.",
      },
      {
        q: "How is data handled?",
        a: "Data is collected and processed only to the extent necessary to deliver the service. It is not sold or shared for advertising. Multi-tenant isolation is enforced at the database and middleware layer. Demo data is fully synthetic — never derived from real customer data.",
      },
      {
        q: "How do I report a security vulnerability?",
        a: "Send a report to security@stephenl.dev. We acknowledge all reports within 48 hours. See the Security Disclosure Policy for full details on scope, process, safe harbor, and coordinated disclosure.",
      },
      {
        q: "What identity providers are supported?",
        a: "OpenID Connect with PKCE is the primary authentication model. Azure AD multi-tenant SSO is supported. SCIM 2.0 provisioning is available for automated user lifecycle management from enterprise identity providers.",
      },
    ],
  },
  {
    group: "Investment & Partnership",
    color: "hsl(38,52%,58%)",
    questions: [
      {
        q: "How do I engage as an investor?",
        a: "The clearest way to understand SZL Holdings is to see the product running. Start with the demo. For structured materials, request data room access. For a direct conversation, reach out via the contact form.",
      },
      {
        q: "What is a design partner?",
        a: "Design partners are enterprise teams who work with SZL in the pre-commercial phase to validate the product against real operational workflows. Each engagement creates reference architecture, operating evidence, and the beginning of a customer reference network. Design partners are not beta customers — they are proof-generation partners.",
      },
      {
        q: "What is the revenue model?",
        a: "The target model is enterprise SaaS — per-seat or per-tenant subscription, with professional services for implementation and customization in regulated or complex environments. We do not disclose specific pricing before commercial launch.",
      },
      {
        q: "Is there a white-label or OEM option?",
        a: "This is a consideration for the expansion phase. The architecture supports multi-tenant deployment and tenant-level branding. Formal OEM and white-label terms are not yet available. Inquiries are welcome.",
      },
    ],
  },
  {
    group: "Legal & Compliance",
    color: "hsl(258,55%,68%)",
    questions: [
      {
        q: "What legal documents govern use of the platform?",
        a: "The Terms of Service govern all use of SZL Holdings platforms. The Privacy Policy governs data handling. The Acceptable Use Policy defines permitted and prohibited conduct. The Security Disclosure Policy governs responsible vulnerability reporting.",
      },
      {
        q: "Is the platform GDPR compliant?",
        a: "Data processing agreements are in place. Data subject access request workflows are operational. Opt-out and deletion processes are implemented. GDPR compliance is an ongoing practice, not a one-time certification.",
      },
      {
        q: "Where is data stored?",
        a: "Platform data is stored in cloud infrastructure with encryption at rest and in transit. Specific data residency requirements (EU, US, etc.) can be addressed through enterprise agreements. Contact us to discuss your requirements.",
      },
    ],
  },
];

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderBottom: "1px solid var(--color-szl-border)" }}>
      <button
        onClick={() => setOpen(!open)}
        style={{ width: "100%", display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "1rem", padding: "1.125rem 0", background: "none", border: "none", cursor: "pointer", textAlign: "left" }}
      >
        <span style={{ fontSize: "0.9375rem", fontWeight: 500, color: "hsl(38,8%,88%)", lineHeight: 1.5 }}>{q}</span>
        <div style={{ flexShrink: 0, marginTop: "2px" }}>
          {open ? <Minus size={16} color="var(--color-szl-text-muted)" /> : <Plus size={16} color="var(--color-szl-text-muted)" />}
        </div>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <m.div
            key="answer"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: "easeInOut" }}
            style={{ overflow: "hidden" }}
          >
            <p style={{ fontSize: "0.9rem", lineHeight: 1.72, color: "hsl(214,7%,60%)", paddingBottom: "1.25rem" }}>{a}</p>
          </m.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FaqPage() {
  const __pageMeta = usePageMeta({
    title: "FAQ — SZL Holdings",
    description: "Frequently asked questions about SZL Holdings, Lyte + Counsel, platform architecture, security, investment, and legal topics.",
    canonical: "https://szlholdings.com/faq",
  });

  useEffect(() => {
    const allQA = FAQ_GROUPS.flatMap(g => g.questions);
    const faqLd = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": allQA.map(({ q, a }) => ({
        "@type": "Question",
        "name": q,
        "acceptedAnswer": { "@type": "Answer", "text": a },
      })),
    };
    const script = document.createElement("script");
    script.type = "application/ld+json";
    script.id = "faq-ld";
    script.textContent = JSON.stringify(faqLd);
    document.head.appendChild(script);
    return () => {
      const el = document.getElementById("faq-ld");
      if (el) el.remove();
    };
  }, []);

  return (
    <>
      {__pageMeta}
      <div style={{ minHeight: "100vh", background: "hsl(214,16%,4%)", color: "hsl(38,8%,95%)" }}>
        <SiteNav />
        <main id="main-content" >
  
          <section className="szl-grid-texture" style={{ paddingTop: "var(--space-hero-pt)", paddingBottom: "clamp(4rem,8vw,6rem)", borderBottom: "1px solid var(--color-szl-border)" }}>
            <div style={{ maxWidth: "1280px", margin: "0 auto", padding: "0 var(--space-content-x)" }}>
              <m.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
                <div style={{ display: "inline-flex", alignItems: "center", gap: "0.5rem", padding: "0.3rem 0.875rem", borderRadius: "99px", border: "1px solid var(--color-szl-border-hover)", background: "hsla(0,0%,100%,0.04)", marginBottom: "1.75rem" }}>
                  <HelpCircle size={13} color="var(--color-szl-text-muted)" />
                  <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.6875rem", fontWeight: 600, letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-szl-text-secondary)" }}>FAQ</span>
                </div>
                <h1 style={{ fontSize: "clamp(2.25rem,5vw,3.75rem)", fontWeight: 600, letterSpacing: "-0.03em", lineHeight: 1.06, maxWidth: "22ch", marginBottom: "1.5rem" }}>
                  Frequently asked questions.
                </h1>
                <p style={{ fontSize: "clamp(1rem,1.8vw,1.125rem)", lineHeight: 1.72, color: "hsl(214,7%,64%)", maxWidth: "52ch" }}>
                  Questions about the company, platform, architecture, security, investment, and legal
                  topics — answered directly. If your question isn't here, reach out.
                </p>
              </m.div>
            </div>
          </section>
  
          <section style={{ padding: "var(--space-section-md) 0" }}>
            <div style={{ maxWidth: "860px", margin: "0 auto", padding: "0 var(--space-content-x)" }}>
              {FAQ_GROUPS.map((group, gi) => (
                <m.div
                  key={group.group}
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: gi * 0.08 }}
                  style={{ marginBottom: "3.5rem" }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: "0.625rem", marginBottom: "1.5rem" }}>
                    <div style={{ width: "4px", height: "16px", borderRadius: "2px", background: group.color }} />
                    <p style={{ fontFamily: "var(--font-mono)", fontSize: "0.6875rem", fontWeight: 600, letterSpacing: "0.12em", textTransform: "uppercase", color: group.color }}>{group.group}</p>
                  </div>
                  {group.questions.map((item) => (
                    <FaqItem key={item.q} q={item.q} a={item.a} />
                  ))}
                </m.div>
              ))}
  
              <m.div initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.4 }} className="szl-card" style={{ borderRadius: "0.875rem", padding: "clamp(1.5rem,3vw,2rem)", marginTop: "2rem" }}>
                <h2 style={{ fontSize: "1.125rem", fontWeight: 600, letterSpacing: "-0.015em", marginBottom: "0.625rem" }}>Still have questions?</h2>
                <p style={{ fontSize: "0.9rem", lineHeight: 1.65, color: "hsl(214,7%,60%)", marginBottom: "1.25rem" }}>
                  For anything not covered here — demos, diligence conversations, partnership inquiries, or technical questions — reach out directly.
                </p>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "0.75rem" }}>
                  <Link href="/contact" className="szl-btn-primary">
                    Get in touch <ArrowRight size={14} />
                  </Link>
                  <Link href="/docs" className="szl-btn-secondary">Documentation →</Link>
                </div>
              </m.div>
            </div>
          </section>
  
        </main>
        <SiteFooter />
      </div>
        </>
  );
}
