/**
 * Mock / fallback data for the Ecosystem Command Center.
 * Used when the API is unreachable (demo mode / offline).
 */

import type { AgentSession, ToolEntry, TopologyData } from './types';

export const MOCK_TOPOLOGY: TopologyData = {
  generatedAt: new Date().toISOString(),
  nodes: [
    {
      id: 'szl-substrate-gateway',
      name: 'Substrate MCP Gateway',
      kind: 'gateway',
      domain: 'substrate',
      description: 'Sovereign Execution Substrate — policy-gated workflows, approval engine, proof chain.',
      policyTier: 'critical',
      endpoint: 'internal://substrate',
      color: '#22d3ee',
      toolCount: 11,
      callsLast24h: 847,
      avgLatencyMs: 134,
      governanceStatus: 'critical',
    },
    {
      id: 'szl-tool-mesh',
      name: 'SZL Tool Mesh',
      kind: 'domain',
      domain: 'core',
      description: 'Core SZL tool mesh — document retrieval, finance, security, graph-query, and operations tools.',
      policyTier: 'internal-workflow',
      endpoint: 'internal://tool-mesh',
      color: '#8b7ac8',
      toolCount: 8,
      callsLast24h: 312,
      avgLatencyMs: 89,
      governanceStatus: 'standard',
    },
    {
      id: 'szl-counsel-evidence',
      name: 'Counsel Evidence MCP',
      kind: 'domain',
      domain: 'counsel',
      description: 'Legal matter evidence packaging, contract analysis, and regulatory document tools.',
      policyTier: 'operator-assisted',
      endpoint: 'internal://counsel-evidence',
      color: '#a78bfa',
      toolCount: 2,
      callsLast24h: 56,
      avgLatencyMs: 201,
      governanceStatus: 'elevated',
    },
    {
      id: 'szl-terra-portfolio',
      name: 'Terra Portfolio MCP',
      kind: 'domain',
      domain: 'terra',
      description: 'Real estate portfolio analytics, anomaly detection, and property intelligence tools.',
      policyTier: 'internal-workflow',
      endpoint: 'internal://terra-portfolio',
      color: '#22c55e',
      toolCount: 2,
      callsLast24h: 128,
      avgLatencyMs: 156,
      governanceStatus: 'standard',
    },
    {
      id: 'szl-aegis-threat',
      name: 'AEGIS Threat Intelligence MCP',
      kind: 'domain',
      domain: 'aegis',
      description: 'Defense and intelligence threat triage, security signal analysis.',
      policyTier: 'operator-assisted',
      endpoint: 'internal://aegis-threat',
      color: '#ef4444',
      toolCount: 2,
      callsLast24h: 73,
      avgLatencyMs: 220,
      governanceStatus: 'elevated',
    },
    {
      id: 'szl-vessels-maritime',
      name: 'Vessels Maritime Intelligence MCP',
      kind: 'domain',
      domain: 'vessels',
      description: 'Maritime voyage anomaly detection, vessel tracking, and logistics intelligence tools.',
      policyTier: 'internal-workflow',
      endpoint: 'internal://vessels-maritime',
      color: '#4d8fcc',
      toolCount: 2,
      callsLast24h: 91,
      avgLatencyMs: 178,
      governanceStatus: 'standard',
    },
    {
      id: 'szl-cognitive-observability',
      name: 'Cognitive Observability MCP',
      kind: 'domain',
      domain: 'observability',
      description: 'Trace graph, metrics collection, run ledger, and agent reliability observability tools.',
      policyTier: 'internal-workflow',
      endpoint: 'internal://cognitive-observability',
      color: '#f59e0b',
      toolCount: 2,
      callsLast24h: 187,
      avgLatencyMs: 67,
      governanceStatus: 'standard',
    },
  ],
  edges: [
    { source: 'szl-substrate-gateway', target: 'szl-tool-mesh', toolFlow: 8 },
    { source: 'szl-substrate-gateway', target: 'szl-counsel-evidence', toolFlow: 2 },
    { source: 'szl-substrate-gateway', target: 'szl-terra-portfolio', toolFlow: 2 },
    { source: 'szl-substrate-gateway', target: 'szl-aegis-threat', toolFlow: 2 },
    { source: 'szl-substrate-gateway', target: 'szl-vessels-maritime', toolFlow: 2 },
    { source: 'szl-substrate-gateway', target: 'szl-cognitive-observability', toolFlow: 2 },
  ],
};

export const MOCK_SESSIONS: AgentSession[] = [
  {
    sessionId: 'session-claude-desktop-001',
    agentClass: 'claude-desktop',
    agentName: 'Claude Desktop',
    color: '#d97706',
    transport: 'HTTP/SSE',
    status: 'active',
    toolInvocations: [
      { tool: 'read_file', mcpServerId: 'mcp-filesystem', decision: 'allowed', reason: 'matches policy', latencyMs: 45, occurredAt: new Date(Date.now() - 120_000).toISOString() },
      { tool: 'brave_web_search', mcpServerId: 'mcp-filesystem', decision: 'allowed', reason: 'matches policy', latencyMs: 312, occurredAt: new Date(Date.now() - 60_000).toISOString() },
    ],
    invocationCount: 14,
    blockedCount: 0,
    quarantinedCount: 0,
    avgLatencyMs: 128,
    firstSeenAt: new Date(Date.now() - 3_600_000).toISOString(),
    lastSeenAt: new Date(Date.now() - 60_000).toISOString(),
  },
  {
    sessionId: 'session-cursor-001',
    agentClass: 'cursor',
    agentName: 'Cursor',
    color: '#3b82f6',
    transport: 'HTTP/SSE',
    status: 'active',
    toolInvocations: [
      { tool: 'read_file', mcpServerId: 'mcp-filesystem', decision: 'allowed', reason: 'matches policy', latencyMs: 38, occurredAt: new Date(Date.now() - 300_000).toISOString() },
      { tool: 'write_file', mcpServerId: 'mcp-filesystem', decision: 'allowed', reason: 'matches policy', latencyMs: 52, occurredAt: new Date(Date.now() - 240_000).toISOString() },
    ],
    invocationCount: 23,
    blockedCount: 1,
    quarantinedCount: 0,
    avgLatencyMs: 67,
    firstSeenAt: new Date(Date.now() - 7_200_000).toISOString(),
    lastSeenAt: new Date(Date.now() - 240_000).toISOString(),
  },
  {
    sessionId: 'session-codex-cli-001',
    agentClass: 'codex-cli',
    agentName: 'Codex CLI',
    color: '#8b5cf6',
    transport: 'stdio',
    status: 'quarantined',
    toolInvocations: [
      { tool: 'read_file', mcpServerId: 'mcp-filesystem', decision: 'quarantined', reason: 'Egress blocked for tier critical', latencyMs: null, occurredAt: new Date(Date.now() - 1_800_000).toISOString() },
    ],
    invocationCount: 3,
    blockedCount: 0,
    quarantinedCount: 2,
    avgLatencyMs: null,
    firstSeenAt: new Date(Date.now() - 10_800_000).toISOString(),
    lastSeenAt: new Date(Date.now() - 1_800_000).toISOString(),
  },
];

export const MOCK_TOOLS: ToolEntry[] = [
  {
    id: 'substrate_submit_run',
    name: 'substrate_submit_run',
    description: 'Submit a workflow run to the Sovereign Execution Substrate.',
    domainTags: ['analytics', 'infrastructure'],
    policyTier: 'critical',
    approvalRequired: true,
    inputSchema: {
      type: 'object',
      properties: {
        workflowId: { type: 'string', description: 'ID of a registered workflow' },
        input: { type: 'object', description: 'Workflow-specific input payload' },
        mode: { type: 'string', enum: ['live', 'dry-run'], description: 'Execution mode' },
      },
      required: ['workflowId', 'input'],
    },
    outputSchema: null,
    serverId: 'szl-substrate-gateway',
    serverName: 'Substrate MCP Gateway',
    domain: 'substrate',
    color: '#22d3ee',
    callsLast30d: 1204,
    blockedLast30d: 0,
    enabled: true,
  },
  {
    id: 'counsel_search_evidence',
    name: 'counsel_search_evidence',
    description: 'Search legal matter evidence packages and contract analysis results.',
    domainTags: ['legal', 'documents'],
    policyTier: 'operator-assisted',
    approvalRequired: false,
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search query' },
        matterId: { type: 'string', description: 'Optional matter ID filter' },
      },
      required: ['query'],
    },
    outputSchema: null,
    serverId: 'szl-counsel-evidence',
    serverName: 'Counsel Evidence MCP',
    domain: 'counsel',
    color: '#a78bfa',
    callsLast30d: 87,
    blockedLast30d: 2,
    enabled: true,
  },
  {
    id: 'terra_get_portfolio',
    name: 'terra_get_portfolio',
    description: 'Retrieve real estate portfolio summary and performance metrics.',
    domainTags: ['finance', 'analytics'],
    policyTier: 'internal-workflow',
    approvalRequired: false,
    inputSchema: {
      type: 'object',
      properties: {
        portfolioId: { type: 'string', description: 'Portfolio ID' },
        period: { type: 'string', description: 'Time period (e.g. Q1-2025)' },
      },
      required: ['portfolioId'],
    },
    outputSchema: null,
    serverId: 'szl-terra-portfolio',
    serverName: 'Terra Portfolio MCP',
    domain: 'terra',
    color: '#22c55e',
    callsLast30d: 312,
    blockedLast30d: 0,
    enabled: true,
  },
  {
    id: 'aegis_triage_threat',
    name: 'aegis_triage_threat',
    description: 'Triage and classify an incoming threat signal using adversarial pattern matching.',
    domainTags: ['security', 'analytics'],
    policyTier: 'operator-assisted',
    approvalRequired: false,
    inputSchema: {
      type: 'object',
      properties: {
        signalId: { type: 'string', description: 'Signal ID to triage' },
        severity: { type: 'string', description: 'Initial severity estimate' },
      },
      required: ['signalId'],
    },
    outputSchema: null,
    serverId: 'szl-aegis-threat',
    serverName: 'AEGIS Threat Intelligence MCP',
    domain: 'aegis',
    color: '#ef4444',
    callsLast30d: 156,
    blockedLast30d: 8,
    enabled: true,
  },
  {
    id: 'vessels_track_voyage',
    name: 'vessels_track_voyage',
    description: 'Track a maritime vessel voyage by IMO number and return current position and route.',
    domainTags: ['infrastructure', 'analytics'],
    policyTier: 'internal-workflow',
    approvalRequired: false,
    inputSchema: {
      type: 'object',
      properties: {
        imoNumber: { type: 'string', description: 'IMO vessel number' },
        includeHistory: { type: 'boolean', description: 'Include voyage history' },
      },
      required: ['imoNumber'],
    },
    outputSchema: null,
    serverId: 'szl-vessels-maritime',
    serverName: 'Vessels Maritime Intelligence MCP',
    domain: 'vessels',
    color: '#4d8fcc',
    callsLast30d: 201,
    blockedLast30d: 0,
    enabled: true,
  },
];
