/**
 * SZL Holdings — Agent Gateway: Diff Generator
 * Phase 11 — Agent Gateway
 *
 * Produces a manifest/PR diff record for agent actions that generate
 * proposed changes. For read-only capabilities, returns an empty diff
 * with a clear statement that no changes are proposed.
 *
 * The diff is advisory only — no change is applied without human approval
 * and PR-flow completion.
 */

import type { AgentActionRequest, ManifestDiff } from './types.js';

// ---------------------------------------------------------------------------
// Capabilities that produce non-empty diffs
// ---------------------------------------------------------------------------

const DIFF_PRODUCING_CAPABILITIES = new Set([
  'draft_prs',
  'propose_policy_fixes',
  'propose_architecture_diffs',
  'draft_runbooks',
  'generate_documentation',
  'generate_test_plans',
]);

// ---------------------------------------------------------------------------
// Diff builder
// ---------------------------------------------------------------------------

export function buildDiff(request: AgentActionRequest, agentOutput?: string): ManifestDiff {
  const target = request.target;
  const domain = request.domain;

  if (!DIFF_PRODUCING_CAPABILITIES.has(request.capability)) {
    return {
      additions: [],
      modifications: [],
      deletions: [],
      patchSummary: `No manifest or source changes proposed. Capability '${request.capability}' is read-only.`,
    };
  }

  // Construct a structured advisory diff record.
  // Actual file content comes from the agent output; the diff shape is standardised here.
  const outputRef = agentOutput
    ? `[Agent output: ${agentOutput.slice(0, 120)}${agentOutput.length > 120 ? '…' : ''}]`
    : '[Agent output: pending — will be populated after execution]';

  switch (request.capability) {
    case 'draft_prs':
      return {
        additions: [],
        modifications: [
          {
            path: target,
            before: '[current file contents — loaded at execution time]',
            after: outputRef,
            reason: 'Agent-drafted change; no PR is opened without human review and PR-flow approval.',
          },
        ],
        deletions: [],
        patchSummary: `Advisory PR diff for '${target}'. All changes require human review through the PR-flow gate before any SCM write.`,
      };

    case 'propose_policy_fixes':
      return {
        additions: [
          {
            path: `platform/policy/${domain}/agent-proposed-fix.rego`,
            after: outputRef,
            reason: 'Agent-proposed Rego amendment. Requires policy-approver review before merge.',
          },
        ],
        modifications: [
          {
            path: `platform/policy/${domain}/tests/agent-proposed-fix_test.rego`,
            after: '[Test cases generated by agent]',
            reason: 'Accompanying test file for proposed policy fix.',
          },
        ],
        deletions: [],
        patchSummary: `Advisory policy fix proposal for '${domain}'. No policy is applied without policy-approver sign-off.`,
      };

    case 'propose_architecture_diffs':
      return {
        additions: [
          {
            path: `docs/adrs/agent-proposed-${domain}-${Date.now()}.md`,
            after: outputRef,
            reason: 'Architecture Decision Record proposed by agent. Advisory only.',
          },
        ],
        modifications: [],
        deletions: [],
        patchSummary: `Advisory architecture diff for '${domain}'. No infrastructure change without explicit approval.`,
      };

    case 'draft_runbooks':
      return {
        additions: [
          {
            path: `infra/runbooks/${domain}/${target}.md`,
            after: outputRef,
            reason: 'Agent-drafted runbook. Requires human review before publication.',
          },
        ],
        modifications: [],
        deletions: [],
        patchSummary: `Advisory runbook draft for '${target}'.`,
      };

    case 'generate_documentation':
      return {
        additions: [
          {
            path: `docs/${domain}/${target}.md`,
            after: outputRef,
            reason: 'Agent-generated documentation. Requires human review before commit.',
          },
        ],
        modifications: [],
        deletions: [],
        patchSummary: `Advisory documentation for '${target}'.`,
      };

    case 'generate_test_plans':
      return {
        additions: [
          {
            path: `tests/${domain}/${target}-test-plan.md`,
            after: outputRef,
            reason: 'Agent-generated test plan. No test files modified; advisory only.',
          },
        ],
        modifications: [],
        deletions: [],
        patchSummary: `Advisory test plan for '${target}'.`,
      };

    default:
      return {
        additions: [],
        modifications: [],
        deletions: [],
        patchSummary: 'No changes proposed.',
      };
  }
}
