#!/usr/bin/env tsx
/**
 * generate-platform-metrics.ts
 *
 * Introspects the monorepo filesystem and generates updated structural facts
 * in packages/platform-metrics-registry/src/registry.ts.
 *
 * Usage:
 *   tsx scripts/generate-platform-metrics.ts
 *   tsx scripts/generate-platform-metrics.ts --dry-run
 *
 * The script reads curated facts from the existing registry, updates only the
 * structural counts, and writes back a type-safe registry file.
 */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname ?? process.cwd(), '..');
const DRY_RUN = process.argv.includes('--dry-run');

function countDir(path: string): number {
  if (!existsSync(path)) return 0;
  try {
    return readdirSync(path).filter((entry) => {
      const full = join(path, entry);
      return statSync(full).isDirectory();
    }).length;
  } catch {
    return 0;
  }
}

function countFiles(path: string, ext?: string): number {
  if (!existsSync(path)) return 0;
  try {
    return readdirSync(path).filter((entry) => {
      if (ext && !entry.endsWith(ext)) return false;
      const full = join(path, entry);
      return statSync(full).isFile();
    }).length;
  } catch {
    return 0;
  }
}

function countDbTables(schemaDir: string): number {
  if (!existsSync(schemaDir)) return 0;
  let count = 0;
  try {
    const files = readdirSync(schemaDir);
    for (const file of files) {
      const full = join(schemaDir, file);
      if (statSync(full).isFile() && (file.endsWith('.ts') || file.endsWith('.js'))) {
        const content = readFileSync(full, 'utf-8');
        const matches = content.match(/pgTable\s*\(/g);
        count += matches ? matches.length : 0;
      }
    }
  } catch {
    /* ignore */
  }
  return count;
}

function countRegisteredArtifacts(): number {
  const replitPath = join(ROOT, '.replit');
  if (!existsSync(replitPath)) return 0;
  const content = readFileSync(replitPath, 'utf-8');
  const matches = content.match(/\[\[artifacts\]\]/g);
  return matches ? matches.length : 0;
}

function countScripts(): number {
  const scriptsDir = join(ROOT, 'scripts');
  if (!existsSync(scriptsDir)) return 0;
  return readdirSync(scriptsDir).filter((f) => {
    const full = join(scriptsDir, f);
    return statSync(full).isFile();
  }).length;
}

// Structural counts
const structural = {
  artifactCount: countDir(join(ROOT, 'artifacts')),
  activeArtifactCount: countRegisteredArtifacts(),
  packageCount: countDir(join(ROOT, 'packages')),
  libCount: countDir(join(ROOT, 'lib')),
  workerCount: countDir(join(ROOT, 'workers')),
  serviceCount: countDir(join(ROOT, 'services')),
  appCount: countDir(join(ROOT, 'apps')),
  scriptCount: countScripts(),
};

// Schema counts
const dbSchemaDir = join(ROOT, 'lib', 'db', 'src', 'schema');
const schema = {
  dbTableCount: countDbTables(dbSchemaDir),
  dbSchemaFileCount: countFiles(dbSchemaDir, '.ts'),
  dbSchemaDomainCount: 10,
};
for (const [_key, _value] of Object.entries(structural)) {
}
for (const [_key, _value] of Object.entries(schema)) {
}

if (DRY_RUN) {
  process.exit(0);
}

// Read current registry to preserve curated facts
const registryPath = join(ROOT, 'packages', 'platform-metrics-registry', 'src', 'registry.ts');
const currentContent = existsSync(registryPath) ? readFileSync(registryPath, 'utf-8') : '';

// Extract curated block from current file (preserve manually maintained values)
const curatedMatch = currentContent.match(/curated:\s*\{[\s\S]*?\},\s*\n\s*\};/);
const curatedBlock = curatedMatch
  ? curatedMatch[0]
  : `curated: {
    platformVersion: "4.0.0",
    platformName: "SZL Holdings Platform",
    platformCodename: "AEEP",
    foundedYear: 2024,
    lastAuditDate: "${new Date().toISOString().split('T')[0]}",
    authProviders: ["Replit Auth (OIDC/PKCE)", "Clerk"],
    aiProviders: ["OpenAI", "Anthropic", "Google Gemini", "HuggingFace", "NVIDIA NIM"],
    externalDataSources: [],
  },
};`;

const newContent = `import type { PlatformFacts } from "./schema.js";

/**
 * Platform facts registry.
 * AUTO-GENERATED by scripts/generate-platform-metrics.ts on ${new Date().toISOString()}
 *
 * DO NOT hand-edit structural counts — run the generation script instead.
 * Curated facts are preserved across regenerations.
 */
export const PLATFORM_FACTS: PlatformFacts = {
  generatedAt: "${new Date().toISOString()}",
  generatedBy: "generate-platform-metrics",

  structural: {
    artifactCount: ${structural.artifactCount},
    activeArtifactCount: ${structural.activeArtifactCount},
    packageCount: ${structural.packageCount},
    libCount: ${structural.libCount},
    workerCount: ${structural.workerCount},
    serviceCount: ${structural.serviceCount},
    appCount: ${structural.appCount},
    scriptCount: ${structural.scriptCount},
  },

  schema: {
    dbTableCount: ${schema.dbTableCount},
    dbSchemaFileCount: ${schema.dbSchemaFileCount},
    dbSchemaDomainCount: ${schema.dbSchemaDomainCount},
  },

  api: {
    apiRouteGroupCount: 14,
    v1EndpointCount: 18,
    v1EndpointTarget: 18,
  },

  runtime: {
    domainPackCount: 6,
    agentRoleCount: 8,
    cognitiveLoopPhaseCount: 8,
    starterWorkflowCount: 10,
    rbacRoleCount: 11,
    embeddingBackendCount: 5,
    memoryTierCount: 4,
  },

  deployment: {
    deploymentTargets: ["Reserved VM", "Autoscale", "External Workers"],
    primaryRegion: "us-east",
  },

  ${curatedBlock}

export const AEEP_VERSION = PLATFORM_FACTS.curated.platformVersion;
export const AEEP_CODENAME = PLATFORM_FACTS.curated.platformCodename;
`;

writeFileSync(registryPath, newContent, 'utf-8');

// Regenerate docs/platform-facts.md from computed values
const today = new Date().toISOString().split('T')[0];
const totalPackages = structural.packageCount + structural.libCount;
const docsMarkdown = `# Platform Facts

**Source:** \`packages/platform-metrics-registry\` | **Generated:** ${today} | **Codename:** AEEP

This document is the canonical public reference for all SZL Holdings platform statistics.

All counts are derived from the platform metrics registry. **Do not edit this file directly** — update the registry or run the generation script.

---

## Platform Identity

| Fact | Value |
|------|-------|
| Platform name | SZL Holdings Platform |
| Codename | AEEP (Counsel Execution and Evidence Platform) |
| Version | 4.0.0 |
| Founded | 2024 |
| Last comprehensive audit | ${today} |

---

## Application Surface

| Metric | Count |
|--------|-------|
| Active registered artifacts | ${structural.activeArtifactCount} |
| Total artifacts (including archived) | ${structural.artifactCount} |
| Domain packs | 6 |
| Standalone applications | ${structural.appCount} |
| Background workers | ${structural.workerCount} |
| Hybrid services | ${structural.serviceCount} |

### Domain Packs

| Pack | Domain |
|------|--------|
| KORA | Decision Intelligence command surface |
| SEXTANT | Maritime fleet intelligence |
| DOMAINE | Real estate intelligence |
| PARAGON | Security and defense intelligence |
| PRISM | Legal matter command |
| Carlota | Premium advisory operations |

---

## Package Ecosystem

| Metric | Count |
|--------|-------|
| Domain packages (\`packages/\`) | ${structural.packageCount} |
| Shared library packages (\`lib/\`) | ${structural.libCount} |
| Total packages | ${totalPackages} |

---

## Data Layer

| Metric | Count |
|--------|-------|
| Database tables (Drizzle pgTable) | ${schema.dbTableCount} |
| Schema files | ${schema.dbSchemaFileCount} |
| Schema domains | ${schema.dbSchemaDomainCount} |

---

## API Surface

| Metric | Count |
|--------|-------|
| API route groups | 14 |
| AEEP v1 endpoints (active) | 18 |

### AEEP v1 Endpoint Map

| Endpoint | Service | Status |
|----------|---------|--------|
| \`POST /v1/tasks/plan\` | alloy-runtime-api | Active |
| \`POST /v1/tasks/execute\` | alloy-runtime-api | Active |
| \`POST /v1/memory/write\` | alloy-runtime-api | Active |
| \`POST /v1/memory/query\` | alloy-runtime-api | Active |
| \`DELETE /v1/memory/evict-stale\` | alloy-runtime-api | Active |
| \`POST /v1/workflows/start\` | alloy-runtime-api | Active |
| \`GET /v1/workflows\` | alloy-runtime-api | Active |
| \`GET /v1/workflows/:runId\` | alloy-runtime-api | Active |
| \`POST /v1/workflows/:runId/resume\` | alloy-runtime-api | Active |
| \`POST /v1/workflows/:runId/approve\` | alloy-runtime-api | Active |
| \`DELETE /v1/workflows/:runId\` | alloy-runtime-api | Active |
| \`POST /v1/search/hybrid\` | alloy-runtime-api | Active |
| \`POST /v1/embed\` | alloy-runtime-api | Active |
| \`POST /v1/rerank\` | alloy-runtime-api | Active |
| \`POST /v1/openai/embeddings\` | alloy-runtime-api | Active (compat) |
| \`POST /v1/index/rebuild\` | alloy-runtime-api | Active |
| \`GET /v1/index/verify\` | alloy-runtime-api | Active |
| \`POST /v1/evals/run\` | alloy-runtime-api | Active |

---

## Runtime Capabilities

| Metric | Count |
|--------|-------|
| Typed agent role contracts | 8 |
| Cognitive loop phases | 8 |
| Starter workflow definitions | 10 |
| Embedding backends | 5 |
| Memory tiers | 4 |

### Typed Agent Roles

MissionPlanner · RetrievalStrategist · MemoryCustodian · ToolOrchestrator · PolicyGuardian · ExecutionSupervisor · EvidenceSynthesizer · Evaluator

### Cognitive Loop Phases

perceive → orient → plan → execute → verify → reflect → update_self_model → update_memory

### Memory Tiers

working · episodic · semantic · governance

### Embedding Backends

cpu-local · external-http · gpu-stub · azure-stub · dev-hash

---

## Security and Access Control

| Metric | Value |
|--------|-------|
| RBAC roles | 11 |
| Authentication providers | Replit Auth (OIDC/PKCE), Clerk |
| Tenant isolation | Org-scoped, deny-by-default |

### RBAC Roles

\`anonymous_visitor\` · \`founder_admin\` · \`platform_admin\` · \`operator\` · \`analyst\` · \`executive_viewer\` · \`ops_manager\` · \`sales_delivery_user\` · \`maritime_ops_user\` · \`service_coordinator\` · \`pilot_customer_user\`

---

## AI Providers

OpenAI · Anthropic · Google Gemini · HuggingFace Inference · NVIDIA NIM

---

## Deployment

| Target | Use |
|--------|-----|
| Reserved VM | Always-on API and control plane |
| Autoscale | Variable-traffic application surfaces |
| External Workers | Heavier inference, reranking, and eval workloads |

---

## External Data Sources

| Category | Sources |
|----------|---------|
| Maritime | MarineTraffic, AISHub, Digitraffic, BarentsWatch, Open-Meteo Marine |
| Threat Intelligence | STIX/TAXII, AlienVault OTX, MISP OSINT, Shodan, GreyNoise, MalwareBazaar |
| Sanctions | OFAC SDN, EU Consolidated List, UN Security Council |
| Vulnerability | CISA KEV, NVD CVE, MITRE ATT&CK |
| Legal | CourtListener REST API |
| Government | Census/BLS, FEMA NRI, NYC Open Data, SEC EDGAR |
| CRM / Integration | GitHub API, HubSpot, Mapbox |

---

*Run \`tsx scripts/generate-platform-metrics.ts\` to regenerate with current filesystem counts.*
*Run \`tsx scripts/validate-platform-facts.ts\` to verify registry against filesystem.*
`;

const docsPath = join(ROOT, 'docs', 'platform-facts.md');
writeFileSync(docsPath, docsMarkdown, 'utf-8');
