import type { DomainKey } from './constants';

export const STATE_BOARD_KPIS = [
  {
    id: 'bs',
    label: 'Business Health',
    value: 76,
    unit: '/100',
    delta: '+3',
    trend: 'up' as const,
    color: '#22c55e',
    causal: 'SLA compliance improved after Lyte latency patch applied last week',
  },
  {
    id: 'rv',
    label: 'Value at Risk',
    value: '$8.4M',
    unit: '',
    delta: '−$420K',
    trend: 'down' as const,
    color: '#ef4444',
    causal: 'Carlota pipeline outage + Lyte SLA penalties contributing',
  },
  {
    id: 'vp',
    label: 'Value Protected',
    value: '$1.54M',
    unit: '',
    delta: '+12%',
    trend: 'up' as const,
    color: '#22c55e',
    causal: 'Automated incident response + AI pre-triage operational',
  },
  {
    id: 'vc',
    label: 'Value Created',
    value: '$960K',
    unit: 'MTD',
    delta: '+34%',
    trend: 'up' as const,
    color: '#a78bfa',
    causal: 'Lyte AI Signal Summarizer adoption surge driving ARR uplift',
  },
  {
    id: 'kc',
    label: 'KPI Compliance',
    value: '62.5%',
    unit: '',
    delta: '−1 SLA',
    trend: 'down' as const,
    color: '#f59e0b',
    causal: '5 of 8 SLAs healthy; 3 breaching across Lyte and Carlota',
  },
  {
    id: 'aw',
    label: 'Active Agents',
    value: 6,
    unit: ' agents',
    delta: '1 on probation',
    trend: 'flat' as const,
    color: '#4d8fcc',
    causal: 'Carlota Brand Sentiment agent trust score declining; review queued',
  },
];

export const CAUSAL_EVENTS = [
  {
    id: 'e1',
    time: '14:22',
    domain: 'carlota' as DomainKey,
    title: 'CRM Sync Pipeline Disconnected',
    description:
      'Real-time feed expired — 3h42m stale. Exceeds 1hr threshold. Root: credentials rotation missed.',
    severity: 'critical',
    causedBy: [] as string[],
    causeOf: ['e4'],
  },
  {
    id: 'e2',
    time: '13:18',
    domain: 'lyte' as DomainKey,
    title: 'API P95 Latency Breach (2.4s)',
    description:
      'Distress engine full table scan. Missing index on distress_score + borough fields.',
    severity: 'high',
    causedBy: [] as string[],
    causeOf: ['e5'],
  },
  {
    id: 'e3',
    time: '11:45',
    domain: 'aegis' as DomainKey,
    title: 'Aegis Bundle Size Threshold Warning',
    description:
      'Main bundle grew 8.3% this week (1.24MB → 1.34MB). MITRE ATT&CK module loaded eagerly.',
    severity: 'medium',
    causedBy: [] as string[],
    causeOf: [] as string[],
  },
  {
    id: 'e4',
    time: '10:30',
    domain: 'carlota' as DomainKey,
    title: 'Carlota Client Dashboard Showing Stale Data',
    description:
      'UI reflecting 3h+ stale data due to pipeline disconnect (e1). Client satisfaction risk.',
    severity: 'high',
    causedBy: ['e1'],
    causeOf: [] as string[],
  },
  {
    id: 'e5',
    time: '09:12',
    domain: 'terra' as DomainKey,
    title: 'Terra Distress Engine Slowdown Reported',
    description:
      'Users reporting slow load. Root: Lyte infrastructure latency ripple (e2) + own query issue.',
    severity: 'medium',
    causedBy: ['e2'],
    causeOf: [] as string[],
  },
  {
    id: 'e6',
    time: '08:55',
    domain: 'vessels' as DomainKey,
    title: 'Vessels Fleet Uptime: 99.8% (7th day)',
    description:
      'Fleet maintaining excellent uptime. Automated anomaly detection firing correctly.',
    severity: 'none',
    causedBy: [] as string[],
    causeOf: [] as string[],
  },
];

export const RECOMMENDATIONS = [
  {
    id: 'r1',
    rank: 1,
    title: 'Reconnect Carlota Jo CRM Pipeline',
    domain: 'carlota' as DomainKey,
    impact: 'high',
    effort: 'low',
    why: '3h+ data staleness causing client dashboard corruption. Revenue at risk if sustained >24h.',
    signals: [
      'Drift: data freshness critical',
      'Client satisfaction risk',
      'Genome: Real-Time Stub',
    ],
    action: 'Rotate Credentials & Reconnect',
  },
  {
    id: 'r2',
    rank: 2,
    title: 'Add DB Index — Lyte Distress Engine',
    domain: 'lyte' as DomainKey,
    impact: 'high',
    effort: 'low',
    why: 'P95 at 2.4s vs 2s budget. Full table scan confirmed. Index on distress_score + borough = instant fix.',
    signals: ['SLA breach', '2.4s P95 vs 2s target', 'Usage: 640 weekly rising'],
    action: 'Add Index & Measure',
  },
  {
    id: 'r3',
    rank: 3,
    title: 'Code-Split Aegis MITRE ATT&CK Module',
    domain: 'aegis' as DomainKey,
    impact: 'medium',
    effort: 'medium',
    why: 'Bundle 49% over budget. 280KB eager-loaded. Splitting will restore FCP/TTI and relieve memory pressure.',
    signals: ['Bundle 1.34MB vs 900KB', 'MITRE 280KB eager'],
    action: 'Lazy Load Module',
  },
  {
    id: 'r4',
    rank: 4,
    title: 'Implement PRISM & Carlota Webhooks',
    domain: 'prism' as DomainKey,
    impact: 'medium',
    effort: 'low',
    why: 'Both apps rated Missing/Stub. Blocks enterprise integrations. Shared webhook-engine lib available.',
    signals: ['Genome: Webhooks missing/stub', '3 enterprise deals blocked'],
    action: 'Ship Webhooks',
  },
];

export const ACTIONS = [
  {
    id: 'a1',
    title: 'Carlota CRM Credential Rotation',
    domain: 'carlota' as DomainKey,
    priority: 'urgent',
    status: 'pending',
    owner: 'Ops Lead',
    approver: 'CTO',
    due: 'Today 17:00',
    exposure: 'Client churn risk',
    description:
      'Expired CRM credentials preventing real-time data sync. Pipeline disconnected 3h42m.',
  },
  {
    id: 'a2',
    title: 'Lyte Distress Engine Index Migration',
    domain: 'lyte' as DomainKey,
    priority: 'high',
    status: 'pending',
    owner: 'Backend Eng',
    approver: 'Eng Lead',
    due: 'Tomorrow 12:00',
    exposure: 'SLA penalty liability',
    description: 'Add compound index on (distress_score, borough) to resolve P95 latency breach.',
  },
  {
    id: 'a3',
    title: 'LP Q1 Report — CFO Sign-off',
    domain: 'terra' as DomainKey,
    priority: 'high',
    status: 'blocked',
    owner: 'CFO',
    approver: 'CEO',
    due: 'Apr 20',
    exposure: '$180M LP portfolio',
    description: 'Quarterly report blocked pending CFO review. Template complete, data verified.',
    blockedReason: 'CFO review session not yet scheduled',
  },
  {
    id: 'a4',
    title: 'AI Model Governance Policy Approval',
    domain: 'aegis' as DomainKey,
    priority: 'medium',
    status: 'pending',
    owner: 'CISO',
    approver: 'CEO',
    due: 'Apr 25',
    exposure: 'Compliance requirement',
    description: 'Policy requires CISO then CEO approval. Legal review complete.',
  },
  {
    id: 'a5',
    title: 'Vessels Charter Rate Benchmarks Re-activation',
    domain: 'vessels' as DomainKey,
    priority: 'low',
    status: 'auto-executed',
    owner: 'Product Lead',
    approver: 'Auto',
    due: 'Done',
    exposure: 'Usage recovery',
    description: 'Feature re-activated via automated rollout. Usage monitoring underway.',
  },
];

export const HEATMAP_RISKS = [
  {
    id: 'hr1',
    title: 'Carlota CRM Disconnect',
    domain: 'carlota' as DomainKey,
    domainColor: '#c2a55a',
    probability: 0.92,
    impact: 0.85,
    level: 'critical' as const,
    mitigation: 'Rotate credentials, add freshness watchdog',
    owner: 'Ops Lead',
  },
  {
    id: 'hr2',
    title: 'Lyte API SLA Breach',
    domain: 'lyte' as DomainKey,
    domainColor: '#f59e0b',
    probability: 0.72,
    impact: 0.75,
    level: 'high' as const,
    mitigation: 'Add DB index on distress_score + borough',
    owner: 'Eng Team',
  },
  {
    id: 'hr3',
    title: 'Aegis Bundle Over-Budget',
    domain: 'aegis' as DomainKey,
    domainColor: '#6366f1',
    probability: 0.6,
    impact: 0.45,
    level: 'high' as const,
    mitigation: 'Lazy-load MITRE ATT&CK module',
    owner: 'Frontend Lead',
  },
  {
    id: 'hr4',
    title: 'Terra Ownership Graph Decline',
    domain: 'terra' as DomainKey,
    domainColor: '#4d7c0f',
    probability: 0.5,
    impact: 0.4,
    level: 'medium' as const,
    mitigation: 'AI-guided walkthrough + UX review',
    owner: 'Product Lead',
  },
  {
    id: 'hr5',
    title: 'LP Q1 Report Deadline',
    domain: 'terra' as DomainKey,
    domainColor: '#4d7c0f',
    probability: 0.42,
    impact: 0.8,
    level: 'medium' as const,
    mitigation: 'Fast-track CFO review session this week',
    owner: 'CFO',
  },
];

export const HEATMAP_OPPS = [
  {
    id: 'ho1',
    title: 'Lyte Signal Summarizer Expansion',
    domain: 'lyte' as DomainKey,
    domainColor: '#f59e0b',
    probability: 0.85,
    valueScore: 0.9,
    level: 'high' as const,
    action: 'Expand capacity + org-wide rollout',
    owner: 'Growth Lead',
  },
  {
    id: 'ho2',
    title: 'Terra Borough Filter Rollout',
    domain: 'terra' as DomainKey,
    domainColor: '#4d7c0f',
    probability: 0.82,
    valueScore: 0.55,
    level: 'high' as const,
    action: 'Prioritize this sprint — low effort',
    owner: 'Eng Team',
  },
  {
    id: 'ho3',
    title: 'PRISM Webhook Enterprise Unlock',
    domain: 'prism' as DomainKey,
    domainColor: '#a855f7',
    probability: 0.7,
    valueScore: 0.75,
    level: 'high' as const,
    action: 'Ship webhook-engine integration',
    owner: 'Backend Lead',
  },
  {
    id: 'ho4',
    title: 'Vessels Voyage Economics',
    domain: 'vessels' as DomainKey,
    domainColor: '#3b82f6',
    probability: 0.6,
    valueScore: 0.5,
    level: 'medium' as const,
    action: 'Charter rate benchmark re-activation',
    owner: 'Product Lead',
  },
];

export const CROSS_DOMAIN_IMPACTS = [
  { source: 'carlota', target: 'lyte', label: 'Stale data ops load', type: 'risk' as const },
  { source: 'lyte', target: 'terra', label: 'Latency ripple effect', type: 'risk' as const },
  { source: 'aegis', target: 'vessels', label: 'Threat intel sharing', type: 'positive' as const },
  { source: 'prism', target: 'terra', label: 'Deal compliance checks', type: 'positive' as const },
  { source: 'lyte', target: 'aegis', label: 'AI model ops dependency', type: 'neutral' as const },
];
