import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Link } from "wouter";

const doctrineSteps = [
  {
    phase: "Clarity",
    number: "01",
    title: "You can't act on what you can't see clearly",
    body: "The first job of any platform is to eliminate ambiguity. Not to show more data — to show the right data at the right resolution. Most enterprise software fails here by conflating volume with clarity. A dashboard with forty charts has clarity problems, not data problems. In practice, clarity means a single ranked view of what demands attention, with enough context to understand why. Terra's distress scoring, Vessels' exception queue, Aegis's correlated alert surface — all of these are clarity tools first, data platforms second.",
  },
  {
    phase: "Control",
    number: "02",
    title: "Visibility without control is just expensive anxiety",
    body: "The dominant enterprise UX pattern gives operators visibility into what's happening and then stops. The next step — deciding what to do about it — is left to a separate workflow, often a different tool, sometimes a spreadsheet. Control means the platform doesn't just show you the problem; it presents the decision with the information needed to make it. Vessels' command mode is the canonical example: an ETA deviation alert isn't closed until the operator has reviewed options, selected a course of action, and committed to it in the system. The audit chain runs from signal to decision to outcome.",
  },
  {
    phase: "Execution",
    number: "03",
    title: "Decisions that don't execute are just opinions",
    body: "Execution is where most enterprise platforms stop pretending. They route information to the people who need to act, but the action itself happens outside the system — in email, in a phone call, in another tool. The SZL approach is to close the loop inside the platform wherever possible. Alloy's workflow engine is the execution substrate for the portfolio: decisions made in Vessels, Lyte, or Aegis trigger workflows that move work forward, generate artifacts, escalate to humans where needed, and record what happened. Execution is not just doing the thing — it's creating the traceable record that you did it.",
  },
  {
    phase: "Outcome",
    number: "04",
    title: "Platforms are judged by what they change, not what they show",
    body: "An outcome is a before-and-after story. Before this platform, fleet operators ran voyage P&L in spreadsheets. After, it's a live calculation attached to every voyage. Before, compliance teams ran sanctions screening weekly. After, it's continuous. The product question that matters is not 'what does this feature do?' but 'what does the operator do differently because this feature exists?' Outcome thinking drives prioritisation: the highest-value work is the work that changes the workflow, not the work that adds to the dashboard.",
  },
  {
    phase: "Discovery",
    number: "05",
    title: "The ecosystem learns from its own operations",
    body: "The compounding advantage of a portfolio architecture is that the data generated by operating one platform makes the others better. Signals from Vessels feed Alloy's routing models. Intelligence generated by Aegis informs Lyte's anomaly baselines. Terra's distress patterns inform capital allocation conversations surfaced by SZL Holdings. Discovery is the feedback loop that closes the command cycle: operations generate intelligence, intelligence improves the next round of operations. This is why the SZL ecosystem is designed as a network, not a collection of standalone products.",
  },
];

const architectureChoices = [
  {
    title: "One codebase, not five",
    body: "All SZL platforms are built from the same monorepo. Shared UI components, shared authentication logic, shared utility libraries, shared type definitions. A change to the button component propagates to all six products. A security fix to the auth middleware applies everywhere simultaneously. The coordination cost of a shared codebase is real; the compounding benefit of consistent quality, security, and design is higher.",
  },
  {
    title: "One database cluster, not six",
    body: "Each platform has its own schema namespace within a shared PostgreSQL cluster. This is not the same as a shared database — tenant isolation is enforced at the schema and row-security level, and each platform's data model is fully independent. What's shared is the infrastructure: connection pooling, backup procedures, migration tooling, monitoring. Running six separate database clusters for six platforms at this stage of the portfolio would be six times the operational overhead for no additional isolation.",
  },
  {
    title: "One auth system, not many",
    body: "A single authentication and authorisation service handles identity across the full portfolio. A user authenticated in the SZL system can be provisioned access to any platform without re-registering. Role-based access control is consistent across platforms — the semantics of 'viewer', 'operator', 'admin', and 'ops' mean the same thing everywhere. This consistency reduces training overhead for multi-platform clients and eliminates the audit complexity of managing separate identity systems.",
  },
  {
    title: "Domain intelligence over generic tooling",
    body: "Generic tools optimise for breadth. Every SZL platform is built for a specific operational domain where breadth is a liability. Terra's distress scoring engine is not a generic scoring framework — it knows what a tax lien means in the context of a New York City property transfer. Vessels' dark vessel detection is not a generic anomaly detector — it knows what an AIS gap near a sanctioned port means in the context of a voyage fixture. The domain intelligence is the product. The technology is the delivery mechanism.",
  },
];

export function Thesis() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="max-w-3xl mx-auto px-6 lg:px-12 pt-28 pb-24">
        <div className="mb-12">
          <p className="text-[11px] font-semibold tracking-[0.2em] uppercase text-primary/60 mb-3">Thesis</p>
          <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-4">The SZL Doctrine</h1>
          <p className="text-muted-foreground text-[15px] leading-relaxed max-w-xl">
            A working model for how enterprise software should be built — and the architectural rationale behind the SZL portfolio. The doctrine has five phases. They form a closed loop.
          </p>
        </div>

        <div className="mb-3 py-4 px-5 rounded-lg bg-white/2 border border-white/5 flex items-center justify-between gap-4 overflow-x-auto">
          {doctrineSteps.map((step, i) => (
            <div key={step.phase} className="flex items-center gap-3 shrink-0">
              <span className="text-[11px] font-semibold text-primary tracking-wide">{step.phase}</span>
              {i < doctrineSteps.length - 1 && (
                <span className="text-white/15 text-[10px]">→</span>
              )}
            </div>
          ))}
          <div className="flex items-center gap-3 shrink-0">
            <span className="text-white/15 text-[10px]">→</span>
            <span className="text-[11px] font-semibold text-white/30 tracking-wide">repeat</span>
          </div>
        </div>

        <div className="space-y-10 mb-16">
          {doctrineSteps.map((step) => (
            <div key={step.number} className="border-t border-white/5 pt-8 grid md:grid-cols-12 gap-6">
              <div className="md:col-span-2">
                <span className="font-mono text-[10px] text-white/20 block mb-1">{step.number}</span>
                <span className="text-[10px] font-semibold tracking-[0.15em] uppercase text-primary/50">{step.phase}</span>
              </div>
              <div className="md:col-span-10">
                <h2 className="text-[17px] font-semibold text-foreground mb-3">{step.title}</h2>
                <p className="text-muted-foreground text-[14px] leading-[1.75]">{step.body}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="border-t border-white/5 pt-12 mb-16">
          <p className="text-[11px] font-semibold tracking-[0.2em] uppercase text-primary/60 mb-3">Architecture</p>
          <h2 className="text-2xl font-bold text-foreground mb-4">Why one of everything</h2>
          <p className="text-muted-foreground text-[14px] leading-relaxed mb-10">
            Every SZL platform shares three structural foundations: one codebase, one database cluster, one auth system. These choices are sometimes questioned by people who assume portfolio companies should be more independent. Here's the rationale.
          </p>
          <div className="space-y-8">
            {architectureChoices.map((choice) => (
              <div key={choice.title} className="border-t border-white/5 pt-6">
                <h3 className="text-[15px] font-semibold text-foreground mb-2">{choice.title}</h3>
                <p className="text-muted-foreground text-[14px] leading-[1.75]">{choice.body}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="border-t border-white/5 pt-10">
          <p className="text-muted-foreground text-[13px] mb-4">
            This doctrine is applied consistently across every platform in the SZL portfolio. It's not a mission statement — it's the design brief for every product decision.
          </p>
          <div className="flex items-center gap-6">
            <Link href="/work" className="text-[13px] font-medium text-primary hover:text-primary/80 transition-colors">
              See it in practice →
            </Link>
            <Link href="/writing" className="text-[13px] text-muted-foreground/50 hover:text-muted-foreground transition-colors">
              Read more in writing
            </Link>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}

export default Thesis;
