/**
 * @workspace/alloy — Open-Responses-style Agent Envelope
 *
 * Every request/response that travels through the Alloy coordinator uses
 * this typed envelope. Downstream services read the envelope to understand
 * what was asked, what was produced, and what the run-ledger entry ID is.
 */
import { z } from 'zod';

// ─── Request ──────────────────────────────────────────────────────────────────

export const AgentRequestSchema = z.object({
  /** Unique ID for this request; generated by caller if omitted. */
  requestId: z.string().optional(),
  /** Tenant (org) the request belongs to. */
  tenantId: z.string().optional(),
  /** Surface initiating the request (e.g. "lyte", "vessels", "terra"). */
  surface: z.string().default('unknown'),
  /** Stable domain label for routing and policy evaluation. */
  domain: z.string().default('general'),
  /** Human-readable objective the agent must accomplish. */
  objective: z.string().min(1),
  /** Pre-resolved autonomy mode; defaults to supervised. */
  autonomyMode: z
    .enum(['observe', 'recommend', 'draft', 'ask-to-act', 'approved-act'])
    .default('recommend'),
  /** Optional structured context forwarded to specialists. */
  context: z.record(z.string(), z.unknown()).default({}),
  /** Caller-supplied trace ID (propagated into ledger). */
  traceId: z.string().optional(),
  /** Additional metadata stored verbatim in the ledger. */
  metadata: z.record(z.string(), z.unknown()).default({}),
});

export type AgentRequest = z.infer<typeof AgentRequestSchema>;

// ─── Tool Call record (mirrors run-ledger shape) ──────────────────────────────

export const EnvelopeToolCallSchema = z.object({
  toolId: z.string(),
  toolName: z.string(),
  specialistRole: z.string(),
  success: z.boolean(),
  latencyMs: z.number().nonnegative().default(0),
  input: z.record(z.string(), z.unknown()).default({}),
  output: z.unknown().optional(),
  error: z.string().optional(),
  calledAt: z.string().datetime(),
});

export type EnvelopeToolCall = z.infer<typeof EnvelopeToolCallSchema>;

// ─── Policy gate ──────────────────────────────────────────────────────────────

export const EnvelopePolicyGateSchema = z.object({
  verdict: z.enum(['allowed', 'requires-approval', 'blocked']),
  reason: z.string(),
  evaluatedAt: z.string().datetime(),
  matchedRules: z.array(z.string()).default([]),
});

export type EnvelopePolicyGate = z.infer<typeof EnvelopePolicyGateSchema>;

// ─── Response ─────────────────────────────────────────────────────────────────

export const AgentResponseSchema = z.object({
  /** Echoes the incoming requestId (or a generated one). */
  requestId: z.string(),
  /** Run ID created by the coordinator for this execution. */
  runId: z.string(),
  /** Trace ID propagated from request or generated. */
  traceId: z.string(),
  /** Ledger entry ID for this run (for downstream queries). */
  ledgerId: z.string().optional(),
  /** Overall outcome. */
  status: z.enum(['completed', 'pending_approval', 'blocked', 'failed']),
  /** The primary recommendation / output produced by specialists. */
  recommendation: z
    .object({
      id: z.string(),
      title: z.string(),
      summary: z.string(),
      reasoning: z.string(),
      value: z.unknown().optional(),
      confidence: z.number().min(0).max(1),
      urgency: z.enum(['routine', 'moderate', 'urgent', 'critical']).default('routine'),
      juryScores: z
        .object({
          grounding: z.number().min(0).max(1),
          actionability: z.number().min(0).max(1),
          policyCompliance: z.number().min(0).max(1),
          reversibility: z.number().min(0).max(1),
          confidence: z.number().min(0).max(1),
          composite: z.number().min(0).max(1),
        })
        .optional(),
    })
    .optional(),
  /** All tool calls made during this run (written to the ledger). */
  toolCalls: z.array(EnvelopeToolCallSchema).default([]),
  /** Policy gate result (populated when policyCheck is required). */
  policyGate: EnvelopePolicyGateSchema.optional(),
  /** Approval request when policy says requires-approval. */
  approvalRequest: z
    .object({
      approvalId: z.string(),
      approverRole: z.string(),
      reason: z.string(),
    })
    .optional(),
  /** Specialist errors that were non-fatal (run still completed). */
  warnings: z.array(z.string()).default([]),
  /** Fatal error message when status is "failed". */
  error: z.string().optional(),
  /** Total wall-clock time for the coordinator run. */
  durationMs: z.number().nonnegative().default(0),
  /** ISO timestamp when the coordinator finished. */
  completedAt: z.string().datetime(),
});

export type AgentResponse = z.infer<typeof AgentResponseSchema>;
