export {
  type DelegationRequest,
  type DelegationResult,
  type DelegationStatus,
  type DelegationTaskRecord,
  delegateTask,
  getDelegationHistory,
  getDelegationTask,
} from './a2a-delegation.js';
export {
  A2ARegistryService,
  type AgentCard,
  a2aRegistry,
  type DiscoveryQuery,
  type DiscoveryResult,
} from './a2a-registry.js';
export {
  type ChatInterface,
  type ConversationMessage,
  DomainAgentRunner,
  getOrCreateConversation,
  MAX_TOOL_ROUNDS,
  type NativeToolCall,
  type StructuredCompletionResult,
} from './domain-agent-runner.js';
export {
  type EmbeddingAnalyticsReport,
  embeddingAnalytics,
} from './embedding/analytics.js';
export {
  createEmbeddingAnalyticsRouter,
  getEmbeddingAnalytics,
} from './embedding/analytics-endpoint.js';
export {
  type DomainEmbeddingConfig,
  type EmbeddingDomain,
  getAllDomainConfigs,
  getDomainModelConfig,
  inferDomain,
  RAG_DB_DIMENSIONS,
} from './embedding/domain-config.js';
export {
  type BatchEmbeddingResult,
  type BatchEmbedOptions,
  EmbeddingPipeline,
  type EmbeddingProviderType,
  type EmbeddingResult,
  type EmbedOptions,
  embeddingPipeline,
  getEmbedding,
  type ProviderHealth,
} from './embedding/provider.js';
export {
  aggregateHookStats,
  type DomainEvalContext,
  type EvalAssertion,
  type EvalHookFn,
  type EvalHookResult,
  getEvaluatorHook,
  getHookResults,
  listEvaluatorHooks,
  type RegisteredEvalHook,
  registerEvaluatorHook,
  runEvaluatorHooksForTrace,
  unregisterEvaluatorHook,
} from './evals/evaluator-hooks.js';
export { GOLDEN_SET } from './evals/golden-set.js';
export {
  autoEnqueueTrace,
  enqueueForReview,
  getReviewItem,
  getReviewQueueStats,
  hydrateReviewQueue,
  listReviewQueue,
  markInReview,
  type ReviewDecisionInput,
  type ReviewPriority,
  type ReviewQueueItem,
  type ReviewQueueStats,
  type ReviewVerdict,
  recordReviewDecision,
  registerReviewQueueSink,
} from './evals/review-queue.js';
export { type EvalReport, type EvalResult, runEvals } from './evals/run-evals.js';
export {
  type AITrace,
  aggregateTraces,
  captureTrace,
  getTrace,
  hydrateTraces,
  listTraces,
  REVIEW_CONFIDENCE_THRESHOLD,
  REVIEW_COST_THRESHOLD_USD,
  REVIEW_HIGH_RISK_LEVELS,
  type RecommendationType,
  registerTraceSink,
  registerTraceUpdateSink,
  type TraceAggregate,
  type TraceCaptureInput,
  type TraceDomain,
  type TraceStatus,
  updateTraceStatus,
} from './evals/trace-capture.js';
export {
  type DatasetExportResult,
  type ExportFormat,
  exportDPODataset,
  exportTrainingData,
  type HuggingFaceSample,
  type OpenAIDPOSample,
  type OpenAITrainingSample,
  serializeDPOToJSONL,
  serializeToHuggingFaceJSON,
  serializeToJSONL,
} from './fine-tuning/dataset-exporter.js';
export {
  type CuratedDatasetResult,
  curateAllDomainDatasets,
  curateDatasetForAgent,
  DOMAIN_CURATOR_CONFIGS,
  type DomainCuratorConfig,
  getAllSupportedAgents,
  getDomainCuratorConfig,
} from './fine-tuning/domain-curators.js';
export {
  cancelFineTuningJob,
  type FineTuningJobRequest,
  type FineTuningJobStatus,
  type FineTuningProvider,
  listFineTuningJobs,
  pollJobStatus,
  submitFineTuningJob,
} from './fine-tuning/job-manager.js';
export {
  type QualityCheckResult,
  runDataQualityGate,
} from './fine-tuning/data-quality-gate.js';
export {
  activateCanary,
  type CanaryRouteDecision,
  type CanaryStatus,
  getAllCanaryStatuses,
  getCanaryStatus,
  performCanaryPromotion,
  performCanaryRollback,
  recordCanaryOutcome,
  routeCanaryRequest,
  runIdleCanaryChecks,
} from './fine-tuning/canary-manager.js';
export {
  checkAndTriggerTraining,
  getPipelineHealth,
  getTriggerConfig,
  isAutonomousTrainingGloballyEnabled,
  runTriggerCheckForAllAgents,
  setGlobalTrainingKillSwitch,
  startScheduledTriggerChecks,
  stopScheduledTriggerChecks,
  type TriggerEvaluationResult,
  upsertTriggerConfig,
} from './fine-tuning/training-trigger.js';
export {
  deprecateFineTunedModel,
  type FineTunedModelInfo,
  getActiveFineTunedModel,
  getAllFineTunedModels,
  getModelLineage,
  invalidateModelCache,
  resolveModelForAgent,
} from './fine-tuning/model-registry-extension.js';
export {
  type ModelEvalScores,
  promoteFineTunedModel,
  runValidationGate,
  type ValidationGateResult,
} from './fine-tuning/validation-gate.js';
export {
  type CorrectionRecord,
  getRelevantCorrections,
  storeCorrection,
} from './learning/agent-corrections.js';
export {
  computeAgentCalibrations,
  getEvalHistory,
  getLatestEvalReport,
  persistEvalReport,
  startScheduledEvals,
  stopScheduledEvals,
} from './learning/eval-pipeline.js';
export {
  buildCalibrationInstruction,
  type ConfidenceCalibration,
  getConfidenceCalibration,
  getRelevantOutcomes,
  type OutcomeRecord,
  type OutcomeType,
  recordOutcome,
} from './learning/outcome-learning.js';
export { detectCrossPatterns, runPatternDetectionAndStore } from './learning/pattern-detector.js';
export {
  checkTenantPolicy,
  getRouterConfig,
  type ModelRouterTelemetry,
  type RouterCallOptions,
  type RouterCallResult,
  type RouterConfig,
  registerTelemetryHandler,
  routerCall,
  type TenantFeatureToggles,
} from './model-router.js';
export {
  AGENT_REGISTRY,
  AgentTelemetryTracker,
  agentTelemetry,
  CAUSAL_PATTERNS,
  CausalReasoningEngine,
  ConfidenceCalibrator,
  ConflictResolver,
  callAgent,
  causalEngine,
  computeRoutingScores,
  confidenceCalibrator,
  conflictResolver,
  consultAgent,
  DOMAIN_ROUTING_RULES,
  getSharedContext,
  NuroMeshOrchestrator,
  nuroMeshOrchestrator,
  routeToAgents,
  routeToAgentsWithA2A,
  runMakerChecker,
  SignalCorrelator,
  signalCorrelator,
  storeInsight,
} from './nuro-mesh.js';
export {
  chatCompletion,
  chatCompletionWithFallback,
  type HFChatMessage,
  type HFCompletionResult,
  type HFToolDef,
} from './providers/hf-client.js';
export {
  type CovenantRule,
  type CovenantVerdict,
  type GovernedCallOptions,
  type GovernedCallResult,
  governedStructuredCall,
  PolicyBlockError,
  proofChain,
  type ProofChainEntry,
  RefusalError,
  type RefusalIncident,
  type StructuredIntelligenceStats,
} from './governed-structured-call.js';
export {
  getModelSlots,
  getRouteConfig,
  type ModelSlot,
  type RouteClass,
  type RouteResult,
  routeModel,
} from './providers/hf-router.js';

export {
  type ChunkMetadata,
  chunkByParagraphs,
  chunkWithOverlap,
  createChunks,
  generateEmbedding,
  ingestAgentKnowledge,
  ingestAiDecision,
  ingestCaseMemory,
  ingestDocument,
  ingestIncidentReport,
  ingestToVectorStore,
  type RawChunk,
  runFullReindex,
} from './rag-ingestion.js';
export { chunkText, RAGPipeline } from './rag-pipeline.js';
export {
  deleteChunksByObjectId,
  getChunkCount,
  getKnowledgeBaseStats,
  type HybridSearchOptions,
  hybridSearch,
  type KeywordSearchOptions,
  keywordSearch,
  type RagChunk,
  type RagSearchResult,
  type SemanticSearchOptions,
  semanticSearch,
  upsertChunk,
  upsertChunksBatch,
} from './rag-vector-store.js';
export {
  AlloyRetrievalEngine,
  alloyRetrieval,
  type RerankResult,
  type RetrievalChunk,
  type RetrievalResult,
  type ScoredChunk,
} from './retrieval/alloy-retrieval.js';
export {
  ACTION_DECISION_SCHEMA,
  type ActionDecision,
  type AuditRecord,
  type DecisionMetadata,
  type EvidenceItem,
  safeFallbackDecision,
  validateActionDecision,
} from './schemas/action-decision.js';
export {
  type ApprovalRecommendation,
  validateApprovalRecommendation,
} from './schemas/approval-recommendation.js';
export {
  type EscalationRecommendation,
  validateEscalationRecommendation,
} from './schemas/escalation-recommendation.js';
export { type ExecutiveSummary, validateExecutiveSummary } from './schemas/executive-summary.js';
export {
  EXTRACT_ENTITY_SCHEMA,
  type ExtractedEntities,
  type ExtractedEntity,
  validateExtractedEntities,
} from './schemas/extract-entity.js';
export {
  type OwnershipAssignment,
  validateOwnershipAssignment,
} from './schemas/ownership-assignment.js';
export { type ResolutionSummary, validateResolutionSummary } from './schemas/resolution-summary.js';
export {
  RISK_DECISION_SCHEMA,
  type RiskDecision,
  validateRiskDecision,
} from './schemas/risk-decision.js';
export {
  TRIAGE_DECISION_SCHEMA,
  type TriageDecision,
  validateTriageDecision,
} from './schemas/triage-decision.js';
export type {
  AccessEvent,
  BehavioralBaseline,
  DetectedAnomaly,
  RiskAssessment,
} from './sentinel/behavioral-analytics.js';
export {
  batchRiskAssessment,
  buildBaseline,
  computeRiskAssessment,
} from './sentinel/behavioral-analytics.js';
export {
  ALLOY_TOOL_DEFINITIONS,
  checkToolPolicy,
  type ExecutionMode,
  executeToolCall,
  getExecutionMode,
  isHighRiskTool,
  type ToolAuditEntry,
  type ToolExecutionResult,
} from './tools/alloy-tools.js';
export type {
  AgentCallResult,
  AgentConsultationRequest,
  AgentConsultationResult,
  AgentDefinition,
  AgentPerformanceProfile,
  CausalChain,
  CausalLink,
  ConfidenceCalibrationEntry,
  ConflictResolution,
  CrossAgentInsight,
  DomainAgentConfig,
  DomainRoutingRule,
  OrchestrationTelemetry,
  ProactiveActivation,
  RAGChunk,
  RagSourceType,
  SemanticRoutingScore,
  SensitivityLevel,
  SignalCorrelation,
  StructuredToolCall,
  StructuredToolResult,
  ToolDefinition,
  ValidationResult,
} from './types.js';

export async function startCognitiveLearning(): Promise<void> {
  const { evidencePipeline } = await import('./tradecraft/evidence-pipeline.js');
  const { caseMemory } = await import('./tradecraft/case-memory.js');
  const { startScheduledEvals: _startScheduledEvals } = await import('./learning/eval-pipeline.js');
  await Promise.all([evidencePipeline.hydrateFromDb(), caseMemory.hydrateFromDb()]);
  await _startScheduledEvals();
}

export {
  type A2AAgentCard,
  type A2AJsonRpcRequest,
  type A2AJsonRpcResponse,
  type A2ASkill,
  type A2ATask,
  a2aTaskManager,
  buildAgentCard,
  buildMeshAgentIndex,
} from './a2a/agent-cards.js';
export {
  type AdversarialProbe,
  type AffectiveForecast,
  type AgentBeliefModel,
  type AgentCapabilityProfile,
  type AttentionFocus,
  type AttentionSchemaReport,
  buildConsciousnessContext,
  type CertaintyLevel,
  type CognitiveGoal,
  type CognitiveLoad,
  type CognitiveWorkspaceState,
  type ConsciousnessSnapshot,
  type ConsolidationReport,
  type CounterfactualScenario,
  type CuriositySignal,
  captureConsciousnessSnapshot,
  cognitiveWorkspace,
  type DialecticalTriple,
  type DiscoveredPattern,
  type DreamConsolidationState,
  type DreamReplay,
  dreamConsolidation,
  type EmotionalSignal,
  type EmotionalState,
  type EmotionalValence,
  type EmotionRegulationStrategy,
  type EmotionType,
  type EpisodicFutureSimulation,
  emotionalSignals,
  type FreeEnergyState,
  type GoalEngineState,
  type GoalInterference,
  type GoalPriority,
  type GoalStatus,
  type GWTBroadcast,
  goalEngine,
  type HallucinationRisk,
  type InnerMonologueState,
  type IntrinsicMotivation,
  innerMonologue,
  type MetacognitiveAssessment,
  type MetacognitiveState,
  type MetaGoal,
  type MonologueEntry,
  type MonologueType,
  type MultiHypothesisBranch,
  metacognitiveMonitor,
  type PerspectiveSimulation,
  type Prediction,
  type PredictionError,
  type PredictionModel,
  type PredictiveProcessingState,
  type PredictiveUncertainty,
  type ProspectiveMemoryItem,
  predictiveProcessing,
  type ReasoningQuality,
  type SchererAppraisal,
  type SocraticChain,
  type SystemIdentity,
  type SystemSelfModel,
  selfModelEngine,
  type TemporalAwarenessState,
  type TemporalDiscount,
  type TemporalMarker,
  type TemporalPattern,
  temporalAwareness,
  type WorkingMemoryItem,
} from './consciousness/index.js';
export {
  type BudgetConfig,
  type BudgetUsage,
  budgetManager,
  type CostEstimate,
  MODEL_PRICING,
  type ModelPricing,
  type SpendRecord,
} from './cost/budget-manager.js';
export {
  type PostureTwinState,
  type PredictedState,
  type PropertyTwinState,
  postureTwin,
  propertyTwin,
  type SimulationResult,
  type SimulationScenario,
  type TwinAlert,
  type TwinState,
  type TwinStatus,
  type TwinType,
  twinRegistry,
  type VesselTwinState,
  vesselTwin,
} from './digital-twins/twin-engine.js';
export {
  branchScenario,
  compareSnapshots,
  detectDrift,
  type ExtendedTwinType,
  getSnapshotHistory,
  IncidentTwin,
  type IncidentTwinState,
  incidentTwin,
  MatterTwin,
  type MatterTwinState,
  matterTwin,
  PortfolioTwin,
  type PortfolioTwinState,
  PortTwin,
  type PortTwinState,
  persistSnapshot,
  portfolioTwin,
  portTwin,
  replayState,
} from './digital-twins/twin-engine-spatial.js';
export {
  type AgentRoutingStep,
  type OrchestrateTrajectory,
  type QualityDimensions,
  type ToolCallRecord,
  type TrajectoryStatus,
  trajectoryStore,
} from './flywheel/trajectory-store.js';
export {
  type FusionAlert,
  type FusionAlertCategory,
  type FusionAlertSeverity,
  FusionCortex,
  type FusionCortexStats,
  type FusionEvidenceItem,
  type FusionPattern,
  type FusionScanResult,
  fusionCortex,
} from './fusion/fusion-cortex.js';
export {
  type CorrelationPattern,
  type PatternCategory,
  type PatternEvidence,
  type PatternFeedback,
  PatternLibrary,
  type PatternStatus,
  patternLibrary,
} from './fusion/pattern-library.js';
export {
  type CascadeHorizon,
  type CascadeImpactLevel,
  type CascadeNode,
  type CascadeTree,
  type DomainKey,
  type PredictiveAlert,
  PredictiveCascadeEngine,
  predictiveCascadeEngine,
} from './fusion/predictive-cascade.js';
export {
  executeWithKernel,
  getKernelAuditTrail,
  issueScopeCertificate,
  type KernelAuditEntry,
  type KernelExecutionOptions,
  type KernelExecutionResult,
  kernelAuditChain,
  type ScopeCertificate,
  verifyAuditChainIntegrity,
} from './kernel/agent-kernel.js';
export {
  type ApprovalFormConfig,
  buildApprovalFormComponent,
  buildChartComponent,
  buildDataTableComponent,
  buildMetricCardComponent,
  buildTimelineComponent,
  type ChartConfig,
  type DataTableConfig,
  isUIComponentResponse,
  MCP_APP_TOOLS,
  type MetricCardConfig,
  type TimelineConfig,
  type UIComponentResponse,
  type UIComponentType,
} from './mcp-apps/ui-tools.js';
export {
  type MemoryEntry,
  type MemoryOperation,
  type MemoryOperationResult,
  type MemoryRewardSignal,
  type MemoryTier,
  rlMemoryManager,
} from './memory/rl-memory.js';
// ML Pipeline Infrastructure
export * from './ml-pipeline/index.js';
export {
  behavioralTracer,
  type DecisionFork,
  type DecisionForkType,
  type DecisionTreeNode,
  type ExecutionTrace,
  type JudgeEvaluation,
} from './observability/behavioral-tracer.js';
export {
  type CrossDomainInsight,
  GraphRAGEngine,
  type GraphRAGQuery,
  type GraphRAGResult,
  type GraphScoredChunk,
  graphRAGEngine,
  type ReasoningStep,
} from './ontology/graph-rag.js';
export {
  type CrossDomainConnection,
  type EvidenceLink,
  type GraphNode,
  type GraphQueryResult,
  type GraphTraversalResult,
  OntologyEngine,
  type OntologyEntity,
  type OntologyEntityType,
  type OntologyRelationship,
  ontologyEngine,
  type RelationshipType,
} from './ontology/ontology-engine.js';
export {
  type AlloyDecision,
  type AlloyDecisionEvidenceRef,
  APPROVAL_MATRIX,
  createAlloyDecision,
  type DecisionStatus,
  getApprovalPolicy,
  mapConfidenceToRisk,
  type RiskLevel,
  validateAlloyDecision,
} from './schemas/alloy-decision.js';
export {
  type AgentAccuracyScore,
  type AlertSeverity,
  type AlertType,
  type AlternativeHypothesis,
  ANALYTIC_NOTE_TEMPLATES,
  type AnalyticAssumption,
  type AnalyticMode,
  type AnyDecisionObject,
  type ApprovalRecommendationObject,
  applyConfidenceAdjustment,
  type BaseDecisionObject,
  buildSelfReflectionContext,
  buildTradecraftPrompt,
  type CaseMemoryEntry,
  CaseMemoryStore,
  type ChainCompositionResult,
  type ChainExecutionPlan,
  CONFIDENCE_RUBRIC,
  type ConfidenceAlert,
  type ConfidenceCalibrationScore,
  type ConfidenceLabel,
  ConfidenceMonitor,
  type ControlGapFindingObject,
  caseMemory,
  confidenceMonitor,
  type DecisionDiff,
  type DecisionObjectType,
  type DecisionOutcomeRecord,
  type EscalationDecisionObject,
  type EvidenceIndexEntry,
  EvidencePipeline,
  type EvidenceQuery,
  type EvidenceQueryResult,
  type EvidenceRef,
  type EvidenceSourceType,
  type ExecutiveBriefObject,
  evidencePipeline,
  type ImpactLevel,
  type IncidentAssessmentObject,
  injectReflectionIntoPrompt,
  type MonitorConfig,
  persistReflectionSnapshot,
  type ReasoningAdjustment,
  type ResponsePlanObject,
  type RiskDecisionObject,
  ScoringEngine,
  type ScoringWindowConfig,
  type SelfReflectionConfig,
  type SelfReflectionContext,
  type SkillCapability,
  type SkillChain,
  type SkillChainMetadata,
  type SkillDomain,
  type SkillEffectivenessScore,
  type SkillInputField,
  SkillManager,
  type SkillManifest,
  type SkillOutputField,
  SkillRegistry,
  type SkillSelectionResult,
  type SkillTriggerCondition,
  scoringEngine,
  skillManager,
  skillRegistry,
  TRADECRAFT_PROMPT_LIBRARY,
  type TradecraftPromptTemplate,
  type TriageDecisionObject,
  type UrgencyLevel,
  validateAndBuildApprovalRecommendation,
  validateAndBuildControlGapFinding,
  validateAndBuildDecision,
  validateAndBuildEscalationDecision,
  validateAndBuildExecutiveBrief,
  validateAndBuildIncidentAssessment,
  validateAndBuildResponsePlan,
  validateAndBuildRiskDecision,
  validateAndBuildTriageDecision,
} from './tradecraft/index.js';
export {
  analyzeQueryComplexity,
  applyMetaLearningToRouting,
  buildCausalContext,
  buildFailoverSequence,
  CAUSAL_GRAPH,
  clearCache,
  computeCoalitionMembers,
  createCausalSignal,
  createSimpleJsonValidator,
  estimateCostUsd,
  extractCachePrefix,
  FAILOVER_CHAINS,
  formAndRunCoalition,
  getAllPriorAdjustments,
  getAffectedDomains,
  getBestModelForDomain,
  getBudgetForStakes,
  getCachedResponse,
  getCacheStats,
  getCostPerformanceScore,
  getContrarianLog,
  getContrarianStats,
  getDomainWinnerStats,
  getEdgesBetween,
  getFailoverChain,
  getMetaLearningStats,
  getModelsByCapability,
  getModelSpec,
  getPriorAdjustment,
  getRoutingDecisionLog,
  getRoutingStats,
  LANE_TOKEN_BUDGETS,
  MODEL_REGISTRY,
  propagateCausalSignal,
  recordStrategyOutcome,
  routeQuery,
  runExtendedThinking,
  runMetaReview,
  runShadowCouncil,
  runSpeculativeExecution,
  setCachedResponse,
  setCoalitionAgentCaller,
  setExtendedThinkingLlmCaller,
  setSpeculativeModelCaller,
  setStructuredOutputCaller,
  setShadowCouncilCaller,
  shouldFormCoalition,
  shouldRunShadowCouncil,
  shouldUseSpeculativeExecution,
  structuredOutputWithRetry,
  type CausalEdge,
  type CausalImpact,
  type CausalPropagationResult,
  type CausalSignal,
  type CacheEntry,
  type CacheStats,
  type CoalitionMember,
  type CoalitionResult,
  type ContrarianChallenge,
  type CostPerformanceRouterOptions,
  type Domain,
  type ExtendedThinkingOptions,
  type ExtendedThinkingResult,
  type JsonSchemaValidator,
  type MetaReviewReport,
  type ModelCapability,
  type ModelSpec,
  type ProviderName,
  type QueryComplexityScore,
  type ReasoningDepth,
  type RoutingDecision,
  type RoutingLane,
  type RoutingPriorAdjustment,
  type ScoredCandidate,
  type ShadowCouncilResult,
  type SpeculativeExecutionResult,
  type StrategyRecord,
  type StructuredOutputOptions,
  type StructuredOutputResult,
  type ThinkingBudget,
  type ThinkingPass,
} from './sovereign-intelligence.js';
