export const aegisFixtures = {
  alerts: [
    {
      id: 'a001',
      severity: 'critical',
      title: 'Lateral Movement Detected',
      description: 'Unusual east-west traffic between internal subnets detected by network sensor cluster',
      source: 'SIEM',
      status: 'open',
      createdAt: '2026-04-27T01:15:00Z',
      asset: 'srv-prod-db-01',
      tactic: 'Lateral Movement',
      technique: 'T1021',
      assignee: null,
      confidence: 94,
    },
    {
      id: 'a002',
      severity: 'high',
      title: 'Brute Force Login Attempt',
      description: '235 failed SSH login attempts from IP 198.51.100.42 over 12-minute window',
      source: 'IDS',
      status: 'investigating',
      createdAt: '2026-04-27T00:45:00Z',
      asset: 'bastion-host-01',
      tactic: 'Initial Access',
      technique: 'T1110',
      assignee: 'soc-analyst-02',
      confidence: 99,
    },
    {
      id: 'a003',
      severity: 'high',
      title: 'Anomalous Outbound Data Transfer',
      description: '3.2 GB transferred to unknown external endpoint 203.0.113.77 on port 443',
      source: 'DLP',
      status: 'open',
      createdAt: '2026-04-26T23:30:00Z',
      asset: 'workstation-eng-04',
      tactic: 'Exfiltration',
      technique: 'T1048',
      assignee: null,
      confidence: 87,
    },
    {
      id: 'a004',
      severity: 'medium',
      title: 'Certificate Expiry Warning',
      description: 'TLS certificate for api.internal expires in 14 days. Renewal required to prevent service disruption',
      source: 'PKI Monitor',
      status: 'acknowledged',
      createdAt: '2026-04-26T22:00:00Z',
      asset: 'api.internal',
      tactic: 'N/A',
      technique: 'N/A',
      assignee: 'infra-team',
      confidence: 100,
    },
    {
      id: 'a005',
      severity: 'critical',
      title: 'Ransomware Execution Attempt Blocked',
      description: 'EDR blocked execution of known ransomware dropper (SHA256: 4e2a…b31f) on finance workstation',
      source: 'EDR',
      status: 'contained',
      createdAt: '2026-04-26T20:11:00Z',
      asset: 'ws-finance-07',
      tactic: 'Execution',
      technique: 'T1204',
      assignee: 'incident-response',
      confidence: 98,
    },
    {
      id: 'a006',
      severity: 'medium',
      title: 'Privileged Account Used Outside Business Hours',
      description: 'Admin account "svc-backup" authenticated at 03:42 UTC from unrecognised subnet',
      source: 'SIEM',
      status: 'investigating',
      createdAt: '2026-04-26T18:42:00Z',
      asset: 'ad-domain-ctrl-01',
      tactic: 'Privilege Escalation',
      technique: 'T1078',
      assignee: 'soc-analyst-01',
      confidence: 76,
    },
    {
      id: 'a007',
      severity: 'low',
      title: 'Vulnerability Scanner Detected on Network',
      description: 'Shodan-style scan originating from internal IP 10.0.8.44 targeting prod VLAN',
      source: 'IDS',
      status: 'open',
      createdAt: '2026-04-26T17:05:00Z',
      asset: '10.0.8.44',
      tactic: 'Discovery',
      technique: 'T1046',
      assignee: null,
      confidence: 68,
    },
    {
      id: 'a008',
      severity: 'high',
      title: 'Supply Chain Dependency Compromise',
      description: 'CISA advisory: npm package "event-stream@3.3.6" injected with malicious payload; package found in dependency tree',
      source: 'Threat Intel',
      status: 'open',
      createdAt: '2026-04-26T14:30:00Z',
      asset: 'api-server',
      tactic: 'Initial Access',
      technique: 'T1195.002',
      assignee: null,
      confidence: 91,
    },
    {
      id: 'a009',
      severity: 'medium',
      title: 'Cloud Storage Bucket Made Public',
      description: 'S3 bucket "szl-prod-exports" ACL changed to public-read; automated remediation triggered',
      source: 'CSPM',
      status: 'remediated',
      createdAt: '2026-04-26T11:20:00Z',
      asset: 's3://szl-prod-exports',
      tactic: 'Collection',
      technique: 'T1530',
      assignee: 'cloud-ops',
      confidence: 100,
    },
    {
      id: 'a010',
      severity: 'low',
      title: 'Outdated Software Version in Production',
      description: 'Node.js v18.12.1 running on 3 prod hosts; v18.20.7 available with CVE patches',
      source: 'Vulnerability Scanner',
      status: 'acknowledged',
      createdAt: '2026-04-26T09:00:00Z',
      asset: 'api-cluster',
      tactic: 'N/A',
      technique: 'N/A',
      assignee: 'platform-team',
      confidence: 100,
    },
    {
      id: 'a011',
      severity: 'high',
      title: 'DNS Tunneling Activity Detected',
      description: 'Unusually high volume of TXT record queries from vessel ops subnet consistent with DNS exfil pattern',
      source: 'NDR',
      status: 'investigating',
      createdAt: '2026-04-26T06:15:00Z',
      asset: 'vessels-ops-vlan',
      tactic: 'Command and Control',
      technique: 'T1071.004',
      assignee: 'soc-analyst-03',
      confidence: 82,
    },
    {
      id: 'a012',
      severity: 'medium',
      title: 'Insider Threat Indicator — Mass Download',
      description: 'User john.doe@szl.com downloaded 14,000 files (2.8 GB) from SharePoint in 8-minute window before PTO',
      source: 'UBA',
      status: 'open',
      createdAt: '2026-04-25T16:55:00Z',
      asset: 'john.doe@szl.com',
      tactic: 'Exfiltration',
      technique: 'T1213',
      assignee: null,
      confidence: 73,
    },
  ],
  total: 12,
  open: 5,
  investigating: 3,
  contained: 1,
  remediated: 1,
  acknowledged: 2,
  critical: 2,
  high: 4,
  medium: 4,
  low: 2,
};
