export const conduitFixtures = {
  stats: {
    totalSyncs: 7,
    activeSyncs: 5,
    totalRuns: 214,
    successfulRuns: 197,
    failedRuns: 12,
    totalRowsWritten: 1482391,
    successRate: 92.1,
    recentRuns: [
      {
        id: 'run-001',
        syncId: 'sync-001',
        status: 'success',
        rowsRead: 12,
        rowsWritten: 12,
        rowsFailed: 0,
        durationMs: 18210,
        errorMessage: null,
        triggeredBy: 'scheduler',
        startedAt: '2026-05-04T06:00:00Z',
        finishedAt: '2026-05-04T06:00:18Z',
        syncName: 'Maritime Portfolio → Salesforce',
      },
      {
        id: 'run-002',
        syncId: 'sync-002',
        status: 'success',
        rowsRead: 4,
        rowsWritten: 4,
        rowsFailed: 0,
        durationMs: 7340,
        errorMessage: null,
        triggeredBy: 'on_change',
        startedAt: '2026-05-03T18:22:00Z',
        finishedAt: '2026-05-03T18:22:07Z',
        syncName: 'Legal Matters → HubSpot',
      },
      {
        id: 'run-004',
        syncId: 'sync-005',
        status: 'failed',
        rowsRead: 0,
        rowsWritten: 0,
        rowsFailed: 0,
        durationMs: 3040,
        errorMessage: 'Authentication failed: invalid API token. Re-test the Zendesk connection.',
        triggeredBy: 'scheduler',
        startedAt: '2026-04-27T11:17:00Z',
        finishedAt: '2026-04-27T11:17:03Z',
        syncName: 'Customer Tickets → Zendesk',
      },
    ],
  },

  connections: [
    {
      id: 'conn-001',
      tenantId: 'demo-org',
      name: 'Salesforce CRM — Production',
      destination: 'salesforce',
      status: 'active',
      credentialMeta: { instanceUrl: 'https://szlholdings.salesforce.com' },
      testedAt: '2026-05-04T08:12:00Z',
      createdAt: '2026-01-15T10:00:00Z',
      updatedAt: '2026-05-04T08:12:00Z',
    },
    {
      id: 'conn-002',
      tenantId: 'demo-org',
      name: 'HubSpot Marketing',
      destination: 'hubspot',
      status: 'active',
      credentialMeta: {},
      testedAt: '2026-05-03T14:40:00Z',
      createdAt: '2026-02-01T09:00:00Z',
      updatedAt: '2026-05-03T14:40:00Z',
    },
    {
      id: 'conn-003',
      tenantId: 'demo-org',
      name: 'Slack — #ops-alerts',
      destination: 'slack',
      status: 'active',
      credentialMeta: {},
      testedAt: '2026-05-04T06:00:00Z',
      createdAt: '2026-02-10T11:00:00Z',
      updatedAt: '2026-05-04T06:00:00Z',
    },
    {
      id: 'conn-004',
      tenantId: 'demo-org',
      name: 'Notion — Deal Room',
      destination: 'notion',
      status: 'active',
      credentialMeta: {},
      testedAt: '2026-04-29T16:30:00Z',
      createdAt: '2026-03-05T08:30:00Z',
      updatedAt: '2026-04-29T16:30:00Z',
    },
    {
      id: 'conn-005',
      tenantId: 'demo-org',
      name: 'Zendesk Support',
      destination: 'zendesk',
      status: 'error',
      credentialMeta: {},
      testedAt: '2026-04-27T11:15:00Z',
      createdAt: '2026-03-20T13:00:00Z',
      updatedAt: '2026-04-27T11:15:00Z',
    },
    {
      id: 'conn-006',
      tenantId: 'demo-org',
      name: 'Google Sheets — Finance Reports',
      destination: 'google_sheets',
      status: 'active',
      credentialMeta: {},
      testedAt: '2026-05-04T07:45:00Z',
      createdAt: '2026-04-01T09:00:00Z',
      updatedAt: '2026-05-04T07:45:00Z',
    },
  ],

  syncs: [
    {
      id: 'sync-001',
      tenantId: 'demo-org',
      name: 'Maritime Portfolio → Salesforce',
      sourceType: 'vessels',
      sourceMeta: { entity: 'fleet', filters: { status: 'underway' } },
      connectionId: 'conn-001',
      objectType: 'Contact',
      runMode: 'scheduled',
      scheduleExpr: '0 */6 * * *',
      semantics: 'upsert',
      upsertKey: 'id',
      status: 'active',
      lastRunId: 'run-001',
      lastRunAt: '2026-05-04T06:00:00Z',
      lastRunStatus: 'success',
      createdAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-05-04T06:00:00Z',
      mappingCount: 14,
      connection: {
        id: 'conn-001',
        tenantId: 'demo-org',
        name: 'Salesforce CRM — Production',
        destination: 'salesforce',
        status: 'active',
        credentialMeta: {},
        testedAt: '2026-05-04T08:12:00Z',
        createdAt: '2026-01-15T10:00:00Z',
        updatedAt: '2026-05-04T08:12:00Z',
      },
    },
    {
      id: 'sync-002',
      tenantId: 'demo-org',
      name: 'Legal Matters → HubSpot',
      sourceType: 'counsel',
      sourceMeta: { entity: 'matters', filters: { status: 'active' } },
      connectionId: 'conn-002',
      objectType: 'Deal',
      runMode: 'on_change',
      scheduleExpr: null,
      semantics: 'upsert',
      upsertKey: 'id',
      status: 'active',
      lastRunId: 'run-002',
      lastRunAt: '2026-05-03T18:22:00Z',
      lastRunStatus: 'success',
      createdAt: '2026-02-05T09:00:00Z',
      updatedAt: '2026-05-03T18:22:00Z',
      mappingCount: 8,
      connection: {
        id: 'conn-002',
        tenantId: 'demo-org',
        name: 'HubSpot Marketing',
        destination: 'hubspot',
        status: 'active',
        credentialMeta: {},
        testedAt: '2026-05-03T14:40:00Z',
        createdAt: '2026-02-01T09:00:00Z',
        updatedAt: '2026-05-03T14:40:00Z',
      },
    },
    {
      id: 'sync-003',
      tenantId: 'demo-org',
      name: 'Security Alerts → Slack',
      sourceType: 'sentra',
      sourceMeta: { entity: 'alerts', filters: { severity: ['critical', 'high'] } },
      connectionId: 'conn-003',
      objectType: 'Message',
      runMode: 'on_change',
      scheduleExpr: null,
      semantics: 'insert',
      upsertKey: null,
      status: 'active',
      lastRunId: 'run-003',
      lastRunAt: '2026-05-04T07:31:00Z',
      lastRunStatus: 'success',
      createdAt: '2026-02-14T11:00:00Z',
      updatedAt: '2026-05-04T07:31:00Z',
      mappingCount: 5,
      connection: {
        id: 'conn-003',
        tenantId: 'demo-org',
        name: 'Slack — #ops-alerts',
        destination: 'slack',
        status: 'active',
        credentialMeta: {},
        testedAt: '2026-05-04T06:00:00Z',
        createdAt: '2026-02-10T11:00:00Z',
        updatedAt: '2026-05-04T06:00:00Z',
      },
    },
    {
      id: 'sync-004',
      tenantId: 'demo-org',
      name: 'Real Estate Pipeline → Notion',
      sourceType: 'terra',
      sourceMeta: { entity: 'properties', filters: { status: ['pre-foreclosure', 'lis-pendens'] } },
      connectionId: 'conn-004',
      objectType: 'Page',
      runMode: 'scheduled',
      scheduleExpr: '0 8 * * *',
      semantics: 'mirror',
      upsertKey: 'id',
      status: 'active',
      lastRunId: 'run-005',
      lastRunAt: '2026-05-04T08:00:00Z',
      lastRunStatus: 'success',
      createdAt: '2026-03-10T08:00:00Z',
      updatedAt: '2026-05-04T08:00:00Z',
      mappingCount: 11,
      connection: {
        id: 'conn-004',
        tenantId: 'demo-org',
        name: 'Notion — Deal Room',
        destination: 'notion',
        status: 'active',
        credentialMeta: {},
        testedAt: '2026-04-29T16:30:00Z',
        createdAt: '2026-03-05T08:30:00Z',
        updatedAt: '2026-04-29T16:30:00Z',
      },
    },
    {
      id: 'sync-005',
      tenantId: 'demo-org',
      name: 'Customer Tickets → Zendesk',
      sourceType: 'custom',
      sourceMeta: { entity: 'tickets' },
      connectionId: 'conn-005',
      objectType: 'Ticket',
      runMode: 'scheduled',
      scheduleExpr: '0 */4 * * *',
      semantics: 'upsert',
      upsertKey: 'id',
      status: 'error',
      lastRunId: 'run-004',
      lastRunAt: '2026-04-27T11:17:00Z',
      lastRunStatus: 'failed',
      createdAt: '2026-03-25T13:00:00Z',
      updatedAt: '2026-04-27T11:17:00Z',
      mappingCount: 6,
      connection: {
        id: 'conn-005',
        tenantId: 'demo-org',
        name: 'Zendesk Support',
        destination: 'zendesk',
        status: 'error',
        credentialMeta: {},
        testedAt: '2026-04-27T11:15:00Z',
        createdAt: '2026-03-20T13:00:00Z',
        updatedAt: '2026-04-27T11:15:00Z',
      },
    },
    {
      id: 'sync-006',
      tenantId: 'demo-org',
      name: 'AI Decision Log → Google Sheets',
      sourceType: 'a11oy',
      sourceMeta: { entity: 'decisions', filters: { status: 'approved' } },
      connectionId: 'conn-006',
      objectType: 'Row',
      runMode: 'scheduled',
      scheduleExpr: '0 0 * * *',
      semantics: 'insert',
      upsertKey: null,
      status: 'active',
      lastRunId: 'run-006',
      lastRunAt: '2026-05-04T00:00:00Z',
      lastRunStatus: 'success',
      createdAt: '2026-04-05T09:00:00Z',
      updatedAt: '2026-05-04T00:00:00Z',
      mappingCount: 9,
      connection: {
        id: 'conn-006',
        tenantId: 'demo-org',
        name: 'Google Sheets — Finance Reports',
        destination: 'google_sheets',
        status: 'active',
        credentialMeta: {},
        testedAt: '2026-05-04T07:45:00Z',
        createdAt: '2026-04-01T09:00:00Z',
        updatedAt: '2026-05-04T07:45:00Z',
      },
    },
    {
      id: 'sync-007',
      tenantId: 'demo-org',
      name: 'Voyage Reports → Salesforce',
      sourceType: 'vessels',
      sourceMeta: { entity: 'voyages' },
      connectionId: 'conn-001',
      objectType: 'Opportunity',
      runMode: 'manual',
      scheduleExpr: null,
      semantics: 'upsert',
      upsertKey: 'id',
      status: 'paused',
      lastRunId: 'run-007',
      lastRunAt: '2026-04-30T14:00:00Z',
      lastRunStatus: 'success',
      createdAt: '2026-04-20T10:00:00Z',
      updatedAt: '2026-05-01T09:00:00Z',
      mappingCount: 7,
      connection: {
        id: 'conn-001',
        tenantId: 'demo-org',
        name: 'Salesforce CRM — Production',
        destination: 'salesforce',
        status: 'active',
        credentialMeta: {},
        testedAt: '2026-05-04T08:12:00Z',
        createdAt: '2026-01-15T10:00:00Z',
        updatedAt: '2026-05-04T08:12:00Z',
      },
    },
  ],

  syncRunsEnvelope: {
    data: [
      {
        id: 'run-001',
        syncId: 'sync-001',
        status: 'success',
        rowsRead: 12,
        rowsWritten: 12,
        rowsFailed: 0,
        durationMs: 18210,
        errorMessage: null,
        triggeredBy: 'scheduler',
        startedAt: '2026-05-04T06:00:00Z',
        finishedAt: '2026-05-04T06:00:18Z',
        syncName: 'Maritime Portfolio → Salesforce',
      },
      {
        id: 'run-002',
        syncId: 'sync-002',
        status: 'success',
        rowsRead: 4,
        rowsWritten: 4,
        rowsFailed: 0,
        durationMs: 7340,
        errorMessage: null,
        triggeredBy: 'on_change',
        startedAt: '2026-05-03T18:22:00Z',
        finishedAt: '2026-05-03T18:22:07Z',
        syncName: 'Legal Matters → HubSpot',
      },
      {
        id: 'run-003',
        syncId: 'sync-003',
        status: 'success',
        rowsRead: 2,
        rowsWritten: 2,
        rowsFailed: 0,
        durationMs: 4120,
        errorMessage: null,
        triggeredBy: 'on_change',
        startedAt: '2026-05-04T07:31:00Z',
        finishedAt: '2026-05-04T07:31:04Z',
        syncName: 'Security Alerts → Slack',
      },
      {
        id: 'run-004',
        syncId: 'sync-005',
        status: 'failed',
        rowsRead: 0,
        rowsWritten: 0,
        rowsFailed: 0,
        durationMs: 3040,
        errorMessage: 'Authentication failed: invalid API token. Re-test the Zendesk connection.',
        triggeredBy: 'scheduler',
        startedAt: '2026-04-27T11:17:00Z',
        finishedAt: '2026-04-27T11:17:03Z',
        syncName: 'Customer Tickets → Zendesk',
      },
      {
        id: 'run-005',
        syncId: 'sync-004',
        status: 'success',
        rowsRead: 8,
        rowsWritten: 8,
        rowsFailed: 0,
        durationMs: 22410,
        errorMessage: null,
        triggeredBy: 'scheduler',
        startedAt: '2026-05-04T08:00:00Z',
        finishedAt: '2026-05-04T08:00:22Z',
        syncName: 'Real Estate Pipeline → Notion',
      },
      {
        id: 'run-006',
        syncId: 'sync-006',
        status: 'success',
        rowsRead: 23,
        rowsWritten: 23,
        rowsFailed: 0,
        durationMs: 6830,
        errorMessage: null,
        triggeredBy: 'scheduler',
        startedAt: '2026-05-04T00:00:00Z',
        finishedAt: '2026-05-04T00:00:07Z',
        syncName: 'AI Decision Log → Google Sheets',
      },
      {
        id: 'run-007',
        syncId: 'sync-007',
        status: 'success',
        rowsRead: 6,
        rowsWritten: 6,
        rowsFailed: 0,
        durationMs: 9150,
        errorMessage: null,
        triggeredBy: 'manual',
        startedAt: '2026-04-30T14:00:00Z',
        finishedAt: '2026-04-30T14:00:09Z',
        syncName: 'Voyage Reports → Salesforce',
      },
    ],
    total: 7,
  },

  templates: [
    {
      id: 'tmpl-001',
      name: 'CRM Contact Sync',
      sourceType: 'custom',
      destination: 'salesforce',
      description: 'Syncs contact records with full address, email, and phone mapping.',
      category: 'CRM',
      icon: 'users',
      mappingCount: 4,
      mappings: [
        { sourceField: 'first_name', destinationField: 'FirstName', transform: null, transformConfig: {}, sortOrder: 0 },
        { sourceField: 'last_name', destinationField: 'LastName', transform: null, transformConfig: {}, sortOrder: 1 },
        { sourceField: 'email', destinationField: 'Email', transform: 'lowercase', transformConfig: {}, sortOrder: 2 },
        { sourceField: 'phone', destinationField: 'Phone', transform: null, transformConfig: {}, sortOrder: 3 },
      ],
    },
    {
      id: 'tmpl-002',
      name: 'Alert → Slack Notification',
      sourceType: 'custom',
      destination: 'slack',
      description: 'Posts critical alerts to a Slack channel with severity and timestamp.',
      category: 'Alerting',
      icon: 'bell',
      mappingCount: 3,
      mappings: [
        { sourceField: 'title', destinationField: 'text', transform: null, transformConfig: {}, sortOrder: 0 },
        { sourceField: 'severity', destinationField: 'color', transform: 'uppercase', transformConfig: {}, sortOrder: 1 },
        { sourceField: 'createdAt', destinationField: 'ts', transform: null, transformConfig: {}, sortOrder: 2 },
      ],
    },
    {
      id: 'tmpl-003',
      name: 'Deal Room → Notion',
      sourceType: 'custom',
      destination: 'notion',
      description: 'Mirrors deal pipeline data into a Notion database for stakeholder visibility.',
      category: 'Collaboration',
      icon: 'file-text',
      mappingCount: 4,
      mappings: [
        { sourceField: 'deal_name', destinationField: 'Name', transform: null, transformConfig: {}, sortOrder: 0 },
        { sourceField: 'stage', destinationField: 'Stage', transform: null, transformConfig: {}, sortOrder: 1 },
        { sourceField: 'value', destinationField: 'Value', transform: null, transformConfig: {}, sortOrder: 2 },
        { sourceField: 'owner', destinationField: 'Owner', transform: null, transformConfig: {}, sortOrder: 3 },
      ],
    },
    {
      id: 'tmpl-004',
      name: 'Audit Log → Google Sheets',
      sourceType: 'custom',
      destination: 'google_sheets',
      description: 'Appends audit events to a Google Sheet for compliance reporting.',
      category: 'Compliance',
      icon: 'shield-check',
      mappingCount: 4,
      mappings: [
        { sourceField: 'action', destinationField: 'Action', transform: null, transformConfig: {}, sortOrder: 0 },
        { sourceField: 'actor', destinationField: 'Actor', transform: null, transformConfig: {}, sortOrder: 1 },
        { sourceField: 'at', destinationField: 'Timestamp', transform: null, transformConfig: {}, sortOrder: 2 },
        { sourceField: 'result', destinationField: 'Result', transform: 'uppercase', transformConfig: {}, sortOrder: 3 },
      ],
    },
  ],
};
