const TODAY = new Date();
const d = (offsetDays: number) => new Date(TODAY.getTime() + offsetDays * 86400000).toISOString();

export const counselFixtures = {
  matters: {
    matters: [
      {
        id: 'M-GRF-2026-001',
        name: 'Greenfield Capital v. Apex Group',
        status: 'escalated',
        type: 'Litigation',
        nextDeadline: d(14),
        leadCounsel: 'R. Calloway',
        estimatedExposure: 3800000,
        pressureScore: 91,
        complexityScore: 87,
        jurisdiction: 'SDNY',
        obligations: [
          {
            id: 'OB-GRF-001',
            matterId: 'M-GRF-2026-001',
            title: 'Pre-trial brief filing',
            status: 'at-risk',
            dueDate: d(14),
            assignee: 'R. Calloway',
            consequence: 'Default judgment risk',
          },
          {
            id: 'OB-GRF-002',
            matterId: 'M-GRF-2026-001',
            title: 'Expert witness disclosure',
            status: 'pending',
            dueDate: d(28),
            assignee: 'M. Vega',
            consequence: 'Evidence exclusion',
          },
        ],
      },
      {
        id: 'M-SEC-2024-441',
        name: 'SEC Enforcement — SZL Holdings',
        status: 'active',
        type: 'Regulatory',
        nextDeadline: d(31),
        leadCounsel: 'T. Osei',
        estimatedExposure: 1600000,
        pressureScore: 76,
        complexityScore: 82,
        jurisdiction: 'SEC Washington DC',
        obligations: [
          {
            id: 'OB-SEC-001',
            matterId: 'M-SEC-2024-441',
            title: 'Document production — Phase II',
            status: 'pending',
            dueDate: d(31),
            assignee: 'T. Osei',
            consequence: 'Contempt of subpoena',
          },
          {
            id: 'OB-SEC-002',
            matterId: 'M-SEC-2024-441',
            title: 'Deposition — CFO',
            status: 'pending',
            dueDate: d(45),
            assignee: 'T. Osei',
            consequence: null,
          },
        ],
      },
      {
        id: 'M-TECH-2026-007',
        name: 'TechCo IP Dispute',
        status: 'active',
        type: 'IP / Patent',
        nextDeadline: d(60),
        leadCounsel: 'A. Ferreira',
        estimatedExposure: 2100000,
        pressureScore: 68,
        complexityScore: 74,
        jurisdiction: 'NDCA',
        obligations: [
          {
            id: 'OB-TCH-001',
            matterId: 'M-TECH-2026-007',
            title: 'Claim construction brief',
            status: 'pending',
            dueDate: d(60),
            assignee: 'A. Ferreira',
            consequence: null,
          },
        ],
      },
      {
        id: 'M-EMPL-2025-019',
        name: 'Employment Dispute — Hawkins v. SZL',
        status: 'active',
        type: 'Employment',
        nextDeadline: d(90),
        leadCounsel: 'S. Nakamura',
        estimatedExposure: 320000,
        pressureScore: 44,
        complexityScore: 38,
        jurisdiction: 'SDNY',
        obligations: [
          {
            id: 'OB-EMP-001',
            matterId: 'M-EMPL-2025-019',
            title: 'Mediation session',
            status: 'pending',
            dueDate: d(90),
            assignee: 'S. Nakamura',
            consequence: null,
          },
        ],
      },
      {
        id: 'M-CONT-2025-088',
        name: 'Apex Acquisition — Contract Review',
        status: 'pending',
        type: 'Transactional',
        nextDeadline: d(120),
        leadCounsel: 'R. Calloway',
        estimatedExposure: 580000,
        pressureScore: 29,
        complexityScore: 61,
        jurisdiction: 'N/A',
        obligations: [],
      },
    ],
    provenance: 'seeded',
  },

  matterBrief: {
    date: TODAY.toISOString().split('T')[0],
    headline: '5 active matters — Greenfield brief deadline in 14 days, $3.8M exposure escalated',
    metrics: {
      totalMatters: 5,
      activeMatters: 4,
      escalatedMatters: 1,
      totalExposureM: 8.4,
      overdueObligations: 0,
      atRiskObligations: 1,
    },
    topRisks: [
      {
        matterId: 'M-GRF-2026-001',
        name: 'Greenfield Capital v. Apex Group',
        pressureScore: 91,
        estimatedExposureM: 3.8,
        jurisdiction: 'SDNY',
        nextDeadline: d(14),
      },
      {
        matterId: 'M-TECH-2026-007',
        name: 'TechCo IP Dispute',
        pressureScore: 68,
        estimatedExposureM: 2.1,
        jurisdiction: 'NDCA',
        nextDeadline: d(60),
      },
      {
        matterId: 'M-SEC-2024-441',
        name: 'SEC Enforcement — SZL Holdings',
        pressureScore: 76,
        estimatedExposureM: 1.6,
        jurisdiction: 'SEC Washington DC',
        nextDeadline: d(31),
      },
    ],
    aegisRiskBadge: {
      level: 'high',
      score: 71,
      signals: ['Active SEC investigation', 'Pre-trial deadline at risk', 'Cross-matter exposure cluster'],
    },
    generatedAt: TODAY.toISOString(),
    source: 'counsel:pulse-brief:demo',
  },

  obligations: {
    obligations: [
      {
        id: 'OB-GRF-001',
        matterId: 'M-GRF-2026-001',
        title: 'Pre-trial brief filing',
        status: 'at-risk',
        dueDate: d(14),
        assignee: 'R. Calloway',
        consequence: 'Default judgment risk',
      },
      {
        id: 'OB-GRF-002',
        matterId: 'M-GRF-2026-001',
        title: 'Expert witness disclosure',
        status: 'pending',
        dueDate: d(28),
        assignee: 'M. Vega',
        consequence: 'Evidence exclusion',
      },
      {
        id: 'OB-SEC-001',
        matterId: 'M-SEC-2024-441',
        title: 'Document production — Phase II',
        status: 'pending',
        dueDate: d(31),
        assignee: 'T. Osei',
        consequence: 'Contempt of subpoena',
      },
      {
        id: 'OB-SEC-002',
        matterId: 'M-SEC-2024-441',
        title: 'Deposition — CFO',
        status: 'pending',
        dueDate: d(45),
        assignee: 'T. Osei',
        consequence: null,
      },
      {
        id: 'OB-TCH-001',
        matterId: 'M-TECH-2026-007',
        title: 'Claim construction brief',
        status: 'pending',
        dueDate: d(60),
        assignee: 'A. Ferreira',
        consequence: null,
      },
      {
        id: 'OB-EMP-001',
        matterId: 'M-EMPL-2025-019',
        title: 'Mediation session',
        status: 'pending',
        dueDate: d(90),
        assignee: 'S. Nakamura',
        consequence: null,
      },
    ],
    total: 6,
    exportedAt: TODAY.toISOString(),
  },

  forecast: {
    heads: [
      {
        headName: 'counsel:settlement-likelihood',
        label: 'Settlement Likelihood',
        alertThreshold: 0.45,
        thresholdBreached: false,
        intervals: [
          { horizon: '30d', point: 0.28, lower: 0.14, upper: 0.42, confidence: 0.88, unit: 'probability' },
          { horizon: '60d', point: 0.34, lower: 0.19, upper: 0.49, confidence: 0.82, unit: 'probability' },
          { horizon: '90d', point: 0.41, lower: 0.24, upper: 0.58, confidence: 0.76, unit: 'probability' },
        ],
        provenance: {
          modelId: 'counsel-forecast-v3',
          modelVersion: '3.1.2',
          adapterId: 'szl-legal-adapter',
          generatedAt: TODAY.toISOString(),
        },
      },
      {
        headName: 'counsel:obligation-breach-risk',
        label: 'Obligation Breach Risk',
        alertThreshold: 0.6,
        thresholdBreached: true,
        intervals: [
          { horizon: '30d', point: 0.67, lower: 0.52, upper: 0.79, confidence: 0.85, unit: 'probability' },
          { horizon: '60d', point: 0.58, lower: 0.44, upper: 0.72, confidence: 0.79, unit: 'probability' },
          { horizon: '90d', point: 0.49, lower: 0.35, upper: 0.63, confidence: 0.73, unit: 'probability' },
        ],
        provenance: {
          modelId: 'counsel-forecast-v3',
          modelVersion: '3.1.2',
          adapterId: 'szl-legal-adapter',
          generatedAt: TODAY.toISOString(),
        },
      },
    ],
    generatedAt: TODAY.toISOString(),
  },
};
