export const lyteFixtures = {
  signals: [
    {
      id: 's001',
      name: 'Revenue Velocity',
      value: 4280000,
      trend: 'up',
      change: 8.4,
      unit: 'USD',
      domain: 'finance',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's002',
      name: 'Fleet On-Time Delivery',
      value: 94.2,
      trend: 'stable',
      change: 0.3,
      unit: '%',
      domain: 'operations',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's003',
      name: 'Security Posture Score',
      value: 76,
      trend: 'down',
      change: -4.1,
      unit: 'pts',
      domain: 'security',
      severity: 'warning',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's004',
      name: 'Property Pipeline Value',
      value: 9580000,
      trend: 'up',
      change: 12.7,
      unit: 'USD',
      domain: 'real-estate',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's005',
      name: 'AI Decision Throughput',
      value: 127,
      trend: 'up',
      change: 18.2,
      unit: 'decisions/day',
      domain: 'governance',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's006',
      name: 'Human Override Rate',
      value: 2.4,
      trend: 'down',
      change: -0.8,
      unit: '%',
      domain: 'governance',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's007',
      name: 'Fuel Cost Per Voyage',
      value: 142300,
      trend: 'up',
      change: 6.1,
      unit: 'USD',
      domain: 'operations',
      severity: 'warning',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's008',
      name: 'Distress Property Acquisition Rate',
      value: 3,
      trend: 'stable',
      change: 0,
      unit: 'properties/month',
      domain: 'real-estate',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's009',
      name: 'Open Critical Alerts',
      value: 2,
      trend: 'up',
      change: 1,
      unit: 'alerts',
      domain: 'security',
      severity: 'critical',
      updatedAt: '2026-04-27T01:20:00Z',
    },
    {
      id: 's010',
      name: 'Governance Policy Compliance',
      value: 98.7,
      trend: 'stable',
      change: 0.1,
      unit: '%',
      domain: 'governance',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's011',
      name: 'Vessels in High-Risk Zones',
      value: 1,
      trend: 'stable',
      change: 0,
      unit: 'vessels',
      domain: 'operations',
      severity: 'warning',
      updatedAt: '2026-04-27T06:00:00Z',
    },
    {
      id: 's012',
      name: 'Monthly Recurring Revenue',
      value: 685000,
      trend: 'up',
      change: 5.2,
      unit: 'USD',
      domain: 'finance',
      severity: 'healthy',
      updatedAt: '2026-04-27T06:00:00Z',
    },
  ],
};
