export const sentraFixtures = {
  alerts: [
    {
      id: 'sa001',
      severity: 'critical',
      title: 'Lateral Movement Detected',
      description: 'Unusual east-west traffic between internal subnets detected by network sensor cluster',
      source: 'SIEM',
      status: 'open',
      detectedAt: '2026-04-27T01:15:00Z',
      asset: 'srv-prod-db-01',
      linkedIncidentId: 'INC-2026-001',
    },
    {
      id: 'sa002',
      severity: 'high',
      title: 'Brute Force Login Attempt',
      description: '235 failed SSH login attempts from IP 198.51.100.42 over 12-minute window',
      source: 'IDS',
      status: 'acknowledged',
      detectedAt: '2026-04-27T00:45:00Z',
      asset: 'bastion-host-01',
    },
    {
      id: 'sa003',
      severity: 'high',
      title: 'Anomalous Outbound Data Transfer',
      description: '3.2 GB transferred to unknown external endpoint 203.0.113.77 on port 443',
      source: 'DLP',
      status: 'open',
      detectedAt: '2026-04-26T23:30:00Z',
      asset: 'workstation-eng-04',
      linkedIncidentId: 'INC-2026-002',
    },
    {
      id: 'sa004',
      severity: 'medium',
      title: 'Certificate Expiry Warning',
      description: 'TLS certificate for api.internal expires in 14 days. Renewal required.',
      source: 'PKI Monitor',
      status: 'acknowledged',
      detectedAt: '2026-04-26T22:00:00Z',
      asset: 'api.internal',
    },
    {
      id: 'sa005',
      severity: 'critical',
      title: 'Ransomware Execution Attempt Blocked',
      description: 'EDR blocked execution of known ransomware dropper on finance workstation',
      source: 'EDR',
      status: 'suppressed',
      detectedAt: '2026-04-26T20:11:00Z',
      asset: 'ws-finance-07',
    },
    {
      id: 'sa006',
      severity: 'medium',
      title: 'Privileged Account Used Outside Business Hours',
      description: 'Admin account "svc-backup" authenticated at 03:42 UTC from unrecognised subnet',
      source: 'SIEM',
      status: 'open',
      detectedAt: '2026-04-26T18:42:00Z',
      asset: 'ad-domain-ctrl-01',
    },
    {
      id: 'sa007',
      severity: 'high',
      title: 'Supply Chain Dependency Compromise',
      description: 'CISA advisory: npm package with malicious payload found in dependency tree',
      source: 'Threat Intel',
      status: 'open',
      detectedAt: '2026-04-26T14:30:00Z',
      asset: 'api-server',
    },
    {
      id: 'sa008',
      severity: 'medium',
      title: 'Cloud Storage Bucket Made Public',
      description: 'S3 bucket ACL changed to public-read; automated remediation triggered',
      source: 'CSPM',
      status: 'suppressed',
      detectedAt: '2026-04-26T11:20:00Z',
      asset: 's3://szl-prod-exports',
    },
    {
      id: 'sa009',
      severity: 'high',
      title: 'DNS Tunneling Activity Detected',
      description: 'High volume of TXT record queries consistent with DNS exfiltration pattern',
      source: 'NDR',
      status: 'open',
      detectedAt: '2026-04-26T06:15:00Z',
      asset: 'vessels-ops-vlan',
    },
    {
      id: 'sa010',
      severity: 'low',
      title: 'Outdated Software Version in Production',
      description: 'Node.js v18.12.1 running on 3 prod hosts; patches available',
      source: 'Vulnerability Scanner',
      status: 'acknowledged',
      detectedAt: '2026-04-26T09:00:00Z',
      asset: 'api-cluster',
    },
  ],

  incidents: [
    {
      id: 'INC-2026-001',
      title: 'Lateral Movement — Production DB Cluster',
      description: 'Active threat actor moving laterally through production subnet toward database cluster. Linked to TA-2891 APT campaign targeting OT infrastructure.',
      severity: 'critical',
      status: 'triaging',
      mitreStage: 'Lateral Movement',
      detectedAt: '2026-04-27T01:15:00Z',
      updatedAt: '2026-04-27T01:45:00Z',
      assignedTo: 'soc-lead-01',
      affectedAssets: ['srv-prod-db-01', 'srv-prod-db-02', 'bastion-host-01'],
      tags: ['apt', 'lateral-movement', 'production'],
      timeline: [
        {
          id: 'tl001',
          type: 'detection',
          message: 'Anomalous east-west traffic detected by SIEM rule TA-2891-LATERAL',
          actor: 'SIEM',
          timestamp: '2026-04-27T01:15:00Z',
        },
        {
          id: 'tl002',
          type: 'system',
          message: 'Incident auto-created from correlated alert cluster (3 alerts)',
          actor: 'sentra-ai',
          timestamp: '2026-04-27T01:17:00Z',
        },
        {
          id: 'tl003',
          type: 'user',
          message: 'Assigned to SOC lead for immediate triage. Firewall rule staged for review.',
          actor: 'soc-lead-01',
          timestamp: '2026-04-27T01:30:00Z',
        },
        {
          id: 'tl004',
          type: 'escalation',
          message: 'Escalated to Critical — confirmed C2 beacon traffic to 45.227.252.12',
          actor: 'soc-analyst-02',
          timestamp: '2026-04-27T01:45:00Z',
        },
      ],
    },
    {
      id: 'INC-2026-002',
      title: 'Exfiltration Attempt — Engineering Workstation',
      description: 'Workstation-eng-04 transferred 3.2 GB to unknown external endpoint. DLP triggered. User account suspended pending investigation.',
      severity: 'high',
      status: 'contained',
      mitreStage: 'Exfiltration',
      detectedAt: '2026-04-26T23:30:00Z',
      updatedAt: '2026-04-27T00:20:00Z',
      assignedTo: 'soc-analyst-01',
      affectedAssets: ['workstation-eng-04'],
      tags: ['exfiltration', 'dlp', 'insider-threat'],
      timeline: [
        {
          id: 'tl005',
          type: 'detection',
          message: 'DLP alert fired on outbound traffic to 203.0.113.77:443 (3.2 GB)',
          actor: 'DLP',
          timestamp: '2026-04-26T23:30:00Z',
        },
        {
          id: 'tl006',
          type: 'user',
          message: 'Network isolation applied to workstation-eng-04',
          actor: 'soc-analyst-01',
          timestamp: '2026-04-26T23:45:00Z',
        },
        {
          id: 'tl007',
          type: 'resolution',
          message: 'User account suspended. Forensic image initiated. Endpoint isolated.',
          actor: 'soc-analyst-01',
          timestamp: '2026-04-27T00:20:00Z',
        },
      ],
    },
    {
      id: 'INC-2026-003',
      title: 'Ransomware Dropper Blocked — Finance',
      description: 'EDR successfully blocked ransomware dropper execution on finance workstation ws-finance-07. Dropper matched known sha256 hash from CISA advisory.',
      severity: 'critical',
      status: 'resolved',
      mitreStage: 'Execution',
      detectedAt: '2026-04-26T20:11:00Z',
      updatedAt: '2026-04-26T22:30:00Z',
      resolvedAt: '2026-04-26T22:30:00Z',
      assignedTo: 'incident-response',
      affectedAssets: ['ws-finance-07'],
      tags: ['ransomware', 'edr-block', 'finance'],
      timeline: [
        {
          id: 'tl008',
          type: 'detection',
          message: 'EDR blocked dropper (SHA256: 4e2a…b31f) on ws-finance-07',
          actor: 'EDR',
          timestamp: '2026-04-26T20:11:00Z',
        },
        {
          id: 'tl009',
          type: 'user',
          message: 'Full disk scan initiated. No lateral spread detected.',
          actor: 'incident-response',
          timestamp: '2026-04-26T20:45:00Z',
        },
        {
          id: 'tl010',
          type: 'resolution',
          message: 'Incident resolved. Workstation reimaged. Hash added to block list.',
          actor: 'incident-response',
          timestamp: '2026-04-26T22:30:00Z',
        },
      ],
    },
  ],

  summary: {
    source: 'seed',
    activeIncidents: 2,
    criticalAlerts: 2,
    totalAlerts: 10,
    lastUpdated: '2026-04-27T01:55:00Z',
  },

  agents: [
    {
      id: 'ag001',
      hostname: 'srv-prod-db-01',
      os: 'linux',
      version: '1.4.2',
      tenantId: 'szl-prod',
      tags: ['prod', 'db', 'critical'],
      status: 'healthy',
      lastHeartbeatAt: '2026-04-27T01:54:00Z',
      enrolledAt: '2026-01-15T09:00:00Z',
      updatedAt: '2026-04-27T01:54:00Z',
      auditTrail: [],
    },
    {
      id: 'ag002',
      hostname: 'bastion-host-01',
      os: 'linux',
      version: '1.4.2',
      tenantId: 'szl-prod',
      tags: ['prod', 'network'],
      status: 'stale',
      lastHeartbeatAt: '2026-04-26T22:00:00Z',
      enrolledAt: '2026-01-15T09:05:00Z',
      updatedAt: '2026-04-26T22:00:00Z',
      auditTrail: [],
    },
    {
      id: 'ag003',
      hostname: 'workstation-eng-04',
      os: 'macos',
      version: '1.4.1',
      tenantId: 'szl-prod',
      tags: ['engineering', 'isolated'],
      status: 'isolated',
      lastHeartbeatAt: '2026-04-26T23:48:00Z',
      enrolledAt: '2026-02-10T14:00:00Z',
      updatedAt: '2026-04-26T23:48:00Z',
      auditTrail: [
        {
          id: 'aa001',
          action: 'isolate',
          actor: 'soc-analyst-01',
          timestamp: '2026-04-26T23:48:00Z',
          detail: 'Isolated following DLP exfiltration incident INC-2026-002',
        },
      ],
    },
    {
      id: 'ag004',
      hostname: 'ws-finance-07',
      os: 'windows',
      version: '1.4.2',
      tenantId: 'szl-prod',
      tags: ['finance', 'reimaged'],
      status: 'healthy',
      lastHeartbeatAt: '2026-04-27T01:50:00Z',
      enrolledAt: '2026-03-01T11:00:00Z',
      updatedAt: '2026-04-27T01:50:00Z',
      auditTrail: [],
    },
    {
      id: 'ag005',
      hostname: 'ad-domain-ctrl-01',
      os: 'windows',
      version: '1.4.0',
      tenantId: 'szl-prod',
      tags: ['prod', 'identity', 'critical'],
      status: 'healthy',
      lastHeartbeatAt: '2026-04-27T01:53:00Z',
      enrolledAt: '2026-01-15T09:10:00Z',
      updatedAt: '2026-04-27T01:53:00Z',
      auditTrail: [],
    },
    {
      id: 'ag006',
      hostname: 'api-server-01',
      os: 'linux',
      version: '1.4.2',
      tenantId: 'szl-prod',
      tags: ['prod', 'api'],
      status: 'healthy',
      lastHeartbeatAt: '2026-04-27T01:54:00Z',
      enrolledAt: '2026-01-20T10:00:00Z',
      updatedAt: '2026-04-27T01:54:00Z',
      auditTrail: [],
    },
  ],

  remediationCases: [
    {
      id: 'rem-001',
      cveId: 'CVE-2024-3094',
      title: 'XZ Utils Backdoor — Build Pipeline',
      description: 'Backdoored version of XZ Utils detected in build pipeline dependency. Supply chain compromise.',
      severity: 'critical',
      source: 'Threat Intel',
      sourceRef: 'CISA-AA24-0001',
      affectedAsset: 'build-pipeline-01',
      affectedAssets: ['build-pipeline-01', 'ci-runner-02'],
      stage: 'recommend',
      outcome: 'open',
      context: { exploitabilityScore: 9.8, patchAvailable: true, patchVersion: '5.6.1' },
      recommendation: null,
      simulation: null,
      policy: null,
      execution: null,
      verification: null,
      proofChainIds: [],
      timeline: [
        {
          id: 'rt001',
          stage: 'ingest',
          message: 'Finding ingested from CISA advisory CISA-AA24-0001',
          actor: 'sentra-ai',
          timestamp: '2026-04-26T10:00:00Z',
        },
        {
          id: 'rt002',
          stage: 'recommend',
          message: 'Recommendation queued: downgrade to xz-utils 5.4.6 and rotate signing keys',
          actor: 'sentra-ai',
          timestamp: '2026-04-26T10:05:00Z',
        },
      ],
      assignedTo: 'platform-team',
      detectedAt: '2026-04-26T10:00:00Z',
      updatedAt: '2026-04-26T10:05:00Z',
      createdAt: '2026-04-26T10:00:00Z',
    },
    {
      id: 'rem-002',
      cveId: 'CVE-2023-44487',
      title: 'HTTP/2 Rapid Reset — API Gateway',
      description: 'API gateway susceptible to HTTP/2 Rapid Reset DDoS attack. Patch or mitigation required.',
      severity: 'high',
      source: 'Vulnerability Scanner',
      sourceRef: null,
      affectedAsset: 'api-gateway-prod',
      affectedAssets: ['api-gateway-prod'],
      stage: 'approve',
      outcome: 'open',
      context: { exploitabilityScore: 7.5, patchAvailable: true },
      recommendation: null,
      simulation: null,
      policy: null,
      execution: null,
      verification: null,
      proofChainIds: [],
      timeline: [
        {
          id: 'rt003',
          stage: 'ingest',
          message: 'Vulnerability detected on api-gateway-prod during scheduled scan',
          actor: 'vuln-scanner',
          timestamp: '2026-04-25T08:00:00Z',
        },
      ],
      assignedTo: 'infra-team',
      detectedAt: '2026-04-25T08:00:00Z',
      updatedAt: '2026-04-25T08:00:00Z',
      createdAt: '2026-04-25T08:00:00Z',
    },
    {
      id: 'rem-003',
      cveId: null,
      title: 'Privileged Account Lockdown — svc-backup',
      description: 'Service account svc-backup used outside business hours. Requires MFA enforcement and schedule restriction.',
      severity: 'medium',
      source: 'SIEM',
      sourceRef: null,
      affectedAsset: 'ad-domain-ctrl-01',
      affectedAssets: ['ad-domain-ctrl-01'],
      stage: 'verify',
      outcome: 'open',
      context: {},
      recommendation: null,
      simulation: null,
      policy: null,
      execution: null,
      verification: null,
      proofChainIds: [],
      timeline: [
        {
          id: 'rt004',
          stage: 'ingest',
          message: 'Alert escalated from SIEM: admin account used at 03:42 UTC',
          actor: 'sentra-ai',
          timestamp: '2026-04-26T18:42:00Z',
        },
      ],
      assignedTo: 'soc-analyst-01',
      detectedAt: '2026-04-26T18:42:00Z',
      updatedAt: '2026-04-26T19:00:00Z',
      createdAt: '2026-04-26T18:42:00Z',
    },
  ],

  remediationMetrics: {
    source: 'seed',
    total: 3,
    open: 3,
    resolved: 0,
    failed: 0,
    successRate: 0,
    meanTimeToRemediateSeconds: null,
    byStage: { ingest: 0, contextualize: 0, recommend: 1, simulate: 0, policy: 0, approve: 1, execute: 0, verify: 1, done: 0 },
    bySeverity: { critical: 1, high: 1, medium: 1, low: 0 },
    approvalBottleneck: { pending: 1, oldestAgeMinutes: 2880 },
    lastUpdated: '2026-04-27T02:00:00Z',
  },

  aegisIncidents: [
    {
      id: 1,
      title: 'Lateral Movement — Production DB Cluster',
      description: 'Active threat actor moving laterally through production subnet toward database cluster.',
      severity: 'critical',
      status: 'triaging',
      mitreStage: 'Lateral Movement',
      detectedAt: '2026-04-27T01:15:00Z',
      updatedAt: '2026-04-27T01:45:00Z',
      assignedTo: 'soc-lead-01',
      affectedAssets: ['srv-prod-db-01', 'bastion-host-01'],
      tags: ['apt', 'lateral-movement'],
    },
    {
      id: 2,
      title: 'Exfiltration Attempt — Engineering Workstation',
      description: 'Workstation-eng-04 transferred 3.2 GB to unknown external endpoint.',
      severity: 'high',
      status: 'contained',
      mitreStage: 'Exfiltration',
      detectedAt: '2026-04-26T23:30:00Z',
      updatedAt: '2026-04-27T00:20:00Z',
      assignedTo: 'soc-analyst-01',
      affectedAssets: ['workstation-eng-04'],
      tags: ['exfiltration', 'dlp'],
    },
    {
      id: 3,
      title: 'Ransomware Dropper Blocked — Finance',
      description: 'EDR blocked ransomware dropper on finance workstation. Resolved.',
      severity: 'critical',
      status: 'resolved',
      mitreStage: 'Execution',
      detectedAt: '2026-04-26T20:11:00Z',
      updatedAt: '2026-04-26T22:30:00Z',
      assignedTo: 'incident-response',
      affectedAssets: ['ws-finance-07'],
      tags: ['ransomware', 'edr-block'],
    },
  ],
};
