import { sql } from "drizzle-orm";
import { pgTable, serial, text, integer, boolean, date, timestamp, jsonb, real, unique } from "drizzle-orm/pg-core";

export const alloyChannelConfigs = pgTable("alloy_channel_configs", {
  id: text("id").primaryKey(),
  channelType: text("channel_type").notNull().default("slack"),
  channelId: text("channel_id").notNull(),
  channelName: text("channel_name"),
  workspaceId: text("workspace_id"),
  trustLevel: text("trust_level").notNull().default("standard"),
  allowedSkills: jsonb("allowed_skills").default([]),
  approvalClass: text("approval_class").notNull().default("standard"),
  isEnabled: boolean("is_enabled").notNull().default(true),
  metadata: jsonb("metadata").default({}),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [unique("alloy_channel_configs_type_id_unique").on(t.channelType, t.channelId)]);

export const alloyChannelAudit = pgTable("alloy_channel_audit", {
  id: text("id").primaryKey(),
  channelType: text("channel_type").notNull(),
  channelId: text("channel_id").notNull(),
  channelName: text("channel_name"),
  userId: text("user_id"),
  userName: text("user_name"),
  message: text("message"),
  skillInvoked: text("skill_invoked"),
  workflowId: text("workflow_id"),
  approvalStatus: text("approval_status"),
  outcome: text("outcome"),
  outcomeDetail: text("outcome_detail"),
  trustLevel: text("trust_level"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const alloyPendingApprovalsChat = pgTable("alloy_pending_approvals_chat", {
  id: text("id").primaryKey(),
  channelType: text("channel_type").notNull(),
  channelId: text("channel_id").notNull(),
  messageTs: text("message_ts"),
  workflowId: text("workflow_id"),
  approvalId: text("approval_id"),
  requesterUserId: text("requester_user_id"),
  requesterName: text("requester_name"),
  actionDescription: text("action_description"),
  approvalClass: text("approval_class").notNull().default("standard"),
  status: text("status").notNull().default("pending"),
  reviewedBy: text("reviewed_by"),
  reviewNote: text("review_note"),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyDailyDigests = pgTable("alloy_daily_digests", {
  id: text("id").primaryKey(),
  digestDate: date("digest_date").notNull().default(sql`CURRENT_DATE`),
  roleScope: text("role_scope").notNull().default("executive"),
  userId: integer("user_id"),
  content: jsonb("content").notNull().default({}),
  markdownContent: text("markdown_content"),
  keyDecisions: jsonb("key_decisions").default([]),
  pendingApprovals: jsonb("pending_approvals").default([]),
  workflowSummary: jsonb("workflow_summary").default({}),
  signalsSummary: jsonb("signals_summary").default({}),
  metrics: jsonb("metrics").default({}),
  suggestedPriorities: jsonb("suggested_priorities").default([]),
  deliveryChannels: jsonb("delivery_channels").default(["in_app"]),
  deliveredAt: jsonb("delivered_at").default({}),
  status: text("status").notNull().default("draft"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => [unique("alloy_daily_digests_date_scope_user_unique").on(t.digestDate, t.roleScope, t.userId)]);

export const alloyEmailTriage = pgTable("alloy_email_triage", {
  id: text("id").primaryKey(),
  subject: text("subject").notNull(),
  senderEmail: text("sender_email").notNull(),
  senderName: text("sender_name"),
  recipientEmail: text("recipient_email"),
  bodyText: text("body_text"),
  bodyHtml: text("body_html"),
  priority: text("priority").notNull().default("medium"),
  category: text("category").notNull().default("general"),
  status: text("status").notNull().default("pending"),
  aiSummary: text("ai_summary"),
  aiIntent: text("ai_intent"),
  aiPriorityScore: integer("ai_priority_score").default(50),
  autoDraft: text("auto_draft"),
  draftApproved: boolean("draft_approved").default(false),
  routedToWorkflow: text("routed_to_workflow"),
  routedAt: timestamp("routed_at"),
  labels: jsonb("labels").default([]),
  alloySignalId: text("alloy_signal_id"),
  metadata: jsonb("metadata").default({}),
  receivedAt: timestamp("received_at").notNull().defaultNow(),
  processedAt: timestamp("processed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyEmailRules = pgTable("alloy_email_rules", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  isEnabled: boolean("is_enabled").notNull().default(true),
  conditions: jsonb("conditions").notNull().default([]),
  action: text("action").notNull(),
  actionParams: jsonb("action_params").default({}),
  priority: integer("priority").notNull().default(50),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyIntegrationConnections = pgTable("alloy_integration_connections", {
  id: text("id").primaryKey(),
  integrationType: text("integration_type").notNull(),
  integrationName: text("integration_name").notNull(),
  displayName: text("display_name"),
  tenantId: text("tenant_id"),
  authType: text("auth_type").notNull().default("webhook"),
  status: text("status").notNull().default("pending"),
  isEnabled: boolean("is_enabled").notNull().default(true),
  scope: jsonb("scope").default([]),
  approvalClass: text("approval_class").notNull().default("standard"),
  config: jsonb("config").default({}),
  rateLimitRpm: integer("rate_limit_rpm").default(60),
  rateLimitRph: integer("rate_limit_rph").default(1000),
  failureCount: integer("failure_count").default(0),
  lastFailureAt: timestamp("last_failure_at"),
  lastSuccessAt: timestamp("last_success_at"),
  metadata: jsonb("metadata").default({}),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyIntegrationEvents = pgTable("alloy_integration_events", {
  id: text("id").primaryKey(),
  connectionId: text("connection_id").notNull(),
  integrationType: text("integration_type").notNull(),
  eventType: text("event_type").notNull(),
  direction: text("direction").notNull().default("inbound"),
  payload: jsonb("payload"),
  status: text("status").notNull().default("received"),
  errorMessage: text("error_message"),
  processedAt: timestamp("processed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const alloyWebhookEndpoints = pgTable("alloy_webhook_endpoints", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  secret: text("secret").notNull(),
  isEnabled: boolean("is_enabled").notNull().default(true),
  allowedEvents: jsonb("allowed_events").default(["*"]),
  targetSkill: text("target_skill"),
  targetWorkflowType: text("target_workflow_type"),
  headersToCapture: jsonb("headers_to_capture").default([]),
  metadata: jsonb("metadata").default({}),
  eventCount: integer("event_count").default(0),
  lastReceivedAt: timestamp("last_received_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyMeetings = pgTable("alloy_meetings", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  meetingDate: timestamp("meeting_date"),
  durationMinutes: integer("duration_minutes"),
  attendees: jsonb("attendees").default([]),
  transcript: text("transcript"),
  recordingUrl: text("recording_url"),
  structuredNotes: jsonb("structured_notes").default({}),
  decisions: jsonb("decisions").default([]),
  actionItems: jsonb("action_items").default([]),
  followUpDraft: text("follow_up_draft"),
  summary: text("summary"),
  status: text("status").notNull().default("processing"),
  contextCompiled: jsonb("context_compiled").default({}),
  workflowIds: jsonb("workflow_ids").default([]),
  metadata: jsonb("metadata").default({}),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyMeetingActionItems = pgTable("alloy_meeting_action_items", {
  id: text("id").primaryKey(),
  meetingId: text("meeting_id").notNull().references(() => alloyMeetings.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  description: text("description"),
  assignee: text("assignee"),
  assigneeEmail: text("assignee_email"),
  dueDate: text("due_date"),
  priority: text("priority").notNull().default("medium"),
  status: text("status").notNull().default("open"),
  alloyTaskId: text("alloy_task_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const alloyMeetingDecisions = pgTable("alloy_meeting_decisions", {
  id: text("id").primaryKey(),
  meetingId: text("meeting_id").notNull().references(() => alloyMeetings.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  description: text("description"),
  decidedBy: text("decided_by"),
  impact: text("impact"),
  rationale: text("rationale"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const alloyResearchSpaces = pgTable("alloy_research_spaces", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  query: text("query").notNull(),
  status: text("status").notNull().default("idle"),
  findings: jsonb("findings").notNull().default([]),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  lastRunAt: timestamp("last_run_at"),
  metadata: jsonb("metadata").default({}),
});

export const alloyBrowserTasks = pgTable("alloy_browser_tasks", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  startUrl: text("start_url").notNull(),
  objective: text("objective").notNull(),
  status: text("status").notNull().default("idle"),
  actions: jsonb("actions").notNull().default([]),
  plannedActions: jsonb("planned_actions"),
  error: text("error"),
  durationMs: integer("duration_ms"),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  metadata: jsonb("metadata").default({}),
});

export const alloyUrlAllowlist = pgTable("alloy_url_allowlist", {
  id: text("id").primaryKey(),
  pattern: text("pattern").notNull(),
  scope: text("scope").notNull().default("read"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const alloyVoiceNotes = pgTable("alloy_voice_notes", {
  id: text("id").primaryKey(),
  title: text("title"),
  transcription: text("transcription"),
  aiSummary: text("ai_summary"),
  detectedIntent: text("detected_intent"),
  convertedTo: text("converted_to"),
  convertedId: text("converted_id"),
  durationSeconds: real("duration_seconds"),
  language: text("language").default("en"),
  audioSizeBytes: integer("audio_size_bytes"),
  audioMimeType: text("audio_mime_type"),
  status: text("status").notNull().default("processing"),
  metadata: jsonb("metadata").default({}),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
