import { pgTable, serial, text, integer, real, boolean, jsonb, timestamp } from "drizzle-orm/pg-core";

export const alloyAiDecisions = pgTable("alloy_ai_decisions", {
  decisionId: text("decision_id").primaryKey(),
  orgId: integer("org_id"),
  workflowId: text("workflow_id"),
  signalIds: jsonb("signal_ids").notNull().default([]),
  recommendedAction: text("recommended_action").notNull(),
  rationaleSummary: text("rationale_summary").notNull(),
  evidenceRefs: jsonb("evidence_refs").notNull().default([]),
  confidence: real("confidence").notNull().default(0.5),
  ownerSuggestion: text("owner_suggestion"),
  approvalRequired: boolean("approval_required").notNull().default(false),
  riskLevel: text("risk_level").notNull(),
  fallbackPlan: text("fallback_plan"),
  modelRoute: text("model_route").notNull(),
  schemaVersion: text("schema_version").notNull().default("2.0.0"),
  status: text("status").notNull().default("proposed"),
  approvedBy: text("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rejectedBy: text("rejected_by"),
  rejectedAt: timestamp("rejected_at", { withTimezone: true }),
  rejectionReason: text("rejection_reason"),
  executedAt: timestamp("executed_at", { withTimezone: true }),
  executionOutcome: text("execution_outcome"),
  rawInput: text("raw_input"),
  rawOutput: text("raw_output"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const alloyAiAuditLog = pgTable("alloy_ai_audit_log", {
  id: serial("id").primaryKey(),
  decisionId: text("decision_id"),
  orgId: integer("org_id"),
  endpoint: text("endpoint").notNull(),
  model: text("model"),
  routeClass: text("route_class"),
  confidence: real("confidence"),
  latencyMs: integer("latency_ms"),
  approverUserId: integer("approver_user_id"),
  approverRoles: jsonb("approver_roles"),
  metadata: jsonb("metadata").notNull().default({}),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
