import {
  pgTable,
  text,
  serial,
  timestamp,
  integer,
  jsonb,
  index,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { organizationsTable } from "./organizations";

/**
 * cortex_action_drafts — autonomous action drafts generated by CORTEX intelligence engine.
 *
 * Each row represents one draft action awaiting human approval.
 * Draft lifecycle: pending → approved | dismissed.
 * Approved drafts are surfaced to the Alloy governance execution queue.
 */
export const cortexActionDraftsTable = pgTable("cortex_action_drafts", {
  id: serial("id").primaryKey(),
  draftUuid: text("draft_uuid").notNull().unique(),
  orgId: integer("org_id").references(() => organizationsTable.id, { onDelete: "cascade" }),
  alertId: text("alert_id").notNull(),
  alertTitle: text("alert_title").notNull(),
  domain: text("domain").notNull(),
  draftType: text("draft_type", {
    enum: ["legal_hold", "lp_notification", "insurance_claim", "route_change", "compliance_memo", "incident_report", "risk_brief"],
  }).notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  recipient: text("recipient"),
  priority: text("priority", {
    enum: ["urgent", "high", "normal"],
  }).notNull().default("normal"),
  status: text("status", {
    enum: ["pending", "approved", "dismissed"],
  }).notNull().default("pending"),
  metadata: jsonb("metadata").default({}),
  generatedAt: timestamp("generated_at").notNull().defaultNow(),
  approvedAt: timestamp("approved_at"),
  approvedBy: text("approved_by"),
  dismissedAt: timestamp("dismissed_at"),
  dismissedBy: text("dismissed_by"),
}, (table) => [
  index("cortex_action_drafts_alert_idx").on(table.alertId),
  index("cortex_action_drafts_status_idx").on(table.status),
  index("cortex_action_drafts_domain_idx").on(table.domain),
  index("cortex_action_drafts_generated_at_idx").on(table.generatedAt),
  index("cortex_action_drafts_org_idx").on(table.orgId),
]);

export const insertCortexActionDraftSchema = createInsertSchema(cortexActionDraftsTable).omit({
  id: true,
  generatedAt: true,
});

export type InsertCortexActionDraft = z.infer<typeof insertCortexActionDraftSchema>;
export type CortexActionDraft = typeof cortexActionDraftsTable.$inferSelect;
