import { pgTable, serial, text, integer, bigint, jsonb, timestamp } from "drizzle-orm/pg-core";

export const covenantSimulationRuns = pgTable("covenant_simulation_runs", {
  id: serial("id").primaryKey(),
  requestId: text("request_id").notNull().unique(),
  subjectRoles: text("subject_roles").array().notNull().default([]),
  subjectUserId: text("subject_user_id"),
  subjectTenantId: text("subject_tenant_id"),
  resourceType: text("resource_type").notNull(),
  resourceId: text("resource_id"),
  resourceDomain: text("resource_domain"),
  action: text("action").notNull(),
  effect: text("effect", { enum: ["allow", "deny"] }).notNull(),
  allowed: integer("allowed").notNull().default(0),
  matchedPolicies: text("matched_policies").array().notNull().default([]),
  deniedBy: text("denied_by"),
  reason: text("reason"),
  explanation: text("explanation").array().notNull().default([]),
  context: jsonb("context"),
  evaluatedAt: bigint("evaluated_at", { mode: "number" }).notNull(),
  durationMs: integer("duration_ms").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const policySimScenarios = pgTable("policy_sim_scenarios", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  subjectRoles: text("subject_roles").array().notNull().default([]),
  subjectUserId: text("subject_user_id"),
  subjectTenantId: text("subject_tenant_id"),
  resourceType: text("resource_type").notNull(),
  resourceId: text("resource_id"),
  resourceDomain: text("resource_domain"),
  action: text("action").notNull(),
  context: jsonb("context"),
  lastResult: jsonb("last_result"),
  lastRunAt: timestamp("last_run_at"),
  runCount: integer("run_count").notNull().default(0),
  createdBy: text("created_by"),
  orgId: integer("org_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
