import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  serial,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { createInsertSchema } from 'drizzle-zod';
import type { z } from 'zod/v4';
import { organizationsTable } from './organizations.js';

/**
 * daily_briefings — server-generated daily intelligence summaries.
 *
 * Each row is one briefing document keyed by (orgId, date).
 * The signals JSONB column stores an array of aggregated cross-domain signals.
 * Briefings are generated by the BriefingAggregatorService and cached here.
 */
export const dailyBriefingsTable = pgTable(
  'daily_briefings',
  {
    id: serial('id').primaryKey(),
    orgId: integer('org_id').references(() => organizationsTable.id, { onDelete: 'cascade' }),
    briefingDate: text('briefing_date').notNull(),
    headline: text('headline').notNull(),
    executiveSummary: text('executive_summary').notNull(),
    signals: jsonb('signals').notNull().default([]),
    domainScores: jsonb('domain_scores').notNull().default({}),
    totalAlerts: integer('total_alerts').notNull().default(0),
    criticalCount: integer('critical_count').notNull().default(0),
    highCount: integer('high_count').notNull().default(0),
    overallHealth: text('overall_health').notNull().default('nominal'),
    generatedAt: timestamp('generated_at').notNull().defaultNow(),
    isPublished: boolean('is_published').notNull().default(false),
  },
  (table) => [
    index('daily_briefings_org_date_idx').on(table.orgId, table.briefingDate),
    index('daily_briefings_date_idx').on(table.briefingDate),
    index('daily_briefings_generated_at_idx').on(table.generatedAt),
  ],
);

export const insertDailyBriefingSchema = createInsertSchema(dailyBriefingsTable).omit({
  id: true,
  generatedAt: true,
});
export type InsertDailyBriefing = z.infer<typeof insertDailyBriefingSchema>;
export type DailyBriefingRow = typeof dailyBriefingsTable.$inferSelect;
