import {
  boolean,
  integer,
  jsonb,
  pgTable,
  real,
  serial,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

export const decisionReceipts = pgTable('decision_receipts', {
  id: serial('id').primaryKey(),
  receiptId: text('receipt_id').notNull().unique(),
  domain: text('domain').notNull(),
  actionType: text('action_type').notNull(),
  actionLabel: text('action_label').notNull(),
  actorUserId: integer('actor_user_id'),
  actorName: text('actor_name'),
  actorRole: text('actor_role'),
  timestamp: timestamp('timestamp', { withTimezone: true }).notNull().defaultNow(),
  dataSnapshot: jsonb('data_snapshot').notNull().default({}),
  aiRecommendation: jsonb('ai_recommendation'),
  alternativesConsidered: jsonb('alternatives_considered').notNull().default([]),
  rationale: text('rationale'),
  outcome: text('outcome').notNull(),
  riskLevel: text('risk_level'),
  confidence: real('confidence'),
  decisionId: text('decision_id'),
  workflowId: text('workflow_id'),
  approvalId: integer('approval_id'),
  nonRepudiationHash: text('non_repudiation_hash').notNull(),
  hashAlgorithm: text('hash_algorithm').notNull().default('sha256'),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});
