import { pgTable, serial, integer, text, timestamp, boolean, jsonb, real } from "drizzle-orm/pg-core";

export const pcChangeEventsTable = pgTable("pc_change_events", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  changeType: text("change_type").notNull(),
  sourceType: text("source_type").notNull(),
  sourceRef: text("source_ref"),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  details: jsonb("details"),
  severity: text("severity").notNull().default("info"),
  isRead: boolean("is_read").notNull().default(false),
  actorId: integer("actor_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pcReviewItemsTable = pgTable("pc_review_items", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  reviewType: text("review_type").notNull(),
  title: text("title").notNull(),
  draftContent: text("draft_content"),
  sourceSupport: jsonb("source_support"),
  unsupportedStatements: jsonb("unsupported_statements"),
  contradictionWarnings: jsonb("contradiction_warnings"),
  privilegeWarnings: jsonb("privilege_warnings"),
  reviewState: text("review_state").notNull().default("pending"),
  approvalState: text("approval_state").notNull().default("none"),
  safeToSend: boolean("safe_to_send").notNull().default(false),
  reviewedBy: integer("reviewed_by"),
  approvedBy: integer("approved_by"),
  proofChainId: integer("proof_chain_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const pcSignoffQueueTable = pgTable("pc_signoff_queue", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  requestType: text("request_type").notNull(),
  title: text("title").notNull(),
  reason: text("reason").notNull(),
  supportSummary: text("support_summary"),
  riskSummary: text("risk_summary"),
  ifApproved: text("if_approved"),
  ifRejected: text("if_rejected"),
  status: text("status").notNull().default("pending"),
  requestedBy: integer("requested_by"),
  resolvedBy: integer("resolved_by"),
  resolvedAt: timestamp("resolved_at"),
  reviewItemId: integer("review_item_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pcWordExportsTable = pgTable("pc_word_exports", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  exportType: text("export_type").notNull(),
  title: text("title").notNull(),
  filePath: text("file_path"),
  fileSize: integer("file_size"),
  proofChainRef: text("proof_chain_ref"),
  generatedBy: integer("generated_by"),
  accessLog: jsonb("access_log"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pcMorningBriefsTable = pgTable("pc_morning_briefs", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  userId: integer("user_id").notNull(),
  briefDate: timestamp("brief_date").notNull(),
  mattersChanged: jsonb("matters_changed"),
  deadlinesApproaching: jsonb("deadlines_approaching"),
  silenceWindows: jsonb("silence_windows"),
  newFilesReceived: jsonb("new_files_received"),
  draftsWaiting: jsonb("drafts_waiting"),
  bestActions: jsonb("best_actions"),
  quietRisks: jsonb("quiet_risks"),
  isViewed: boolean("is_viewed").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pcQuietRisksTable = pgTable("pc_quiet_risks", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  riskType: text("risk_type").notNull(),
  title: text("title").notNull(),
  explanation: text("explanation").notNull(),
  severity: text("severity").notNull().default("medium"),
  daysSilent: integer("days_silent"),
  deadlineDaysRemaining: integer("deadline_days_remaining"),
  isResolved: boolean("is_resolved").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const pcIngestionJobsTable = pgTable("pc_ingestion_jobs", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  sourceType: text("source_type").notNull(),
  sourceRef: text("source_ref"),
  matterId: integer("matter_id"),
  status: text("status").notNull().default("pending"),
  itemCount: integer("item_count").notNull().default(0),
  processedCount: integer("processed_count").notNull().default(0),
  errorCount: integer("error_count").notNull().default(0),
  errorDetails: jsonb("error_details"),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pcNextActionsTable = pgTable("pc_next_actions", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  actionType: text("action_type").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  impactScore: real("impact_score").notNull().default(0),
  estimatedMinutes: integer("estimated_minutes").notNull().default(15),
  blocksItems: jsonb("blocks_items"),
  status: text("status").notNull().default("suggested"),
  completedAt: timestamp("completed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const pcMatterDeskSnapshotsTable = pgTable("pc_matter_desk_snapshots", {
  id: serial("id").primaryKey(),
  orgId: integer("org_id").notNull(),
  matterId: integer("matter_id").notNull(),
  summary: text("summary"),
  lastChanges: jsonb("last_changes"),
  commsSummary: jsonb("comms_summary"),
  newFiles: jsonb("new_files"),
  deadlineWatch: jsonb("deadline_watch"),
  missingSupport: jsonb("missing_support"),
  pressureSummary: jsonb("pressure_summary"),
  forecastSummary: jsonb("forecast_summary"),
  nextBestAction: text("next_best_action"),
  signoffStatus: text("signoff_status").notNull().default("clear"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
