export { ATLAS_CORE_VERSION } from '@szl-holdings/atlas-core';
export * from './adapter.js';
export { aegisAdapter } from './adapters/aegis.js';
export { carlotaJoAdapter } from './adapters/carlota-jo.js';
export { imperiumAdapter } from './adapters/imperium.js';
export { lyteAdapter } from './adapters/lyte.js';
export { prismAdapter } from './adapters/prism.js';
export { terraAdapter } from './adapters/terra.js';
export { vesselsAdapter } from './adapters/vessels.js';
export * from './confidence-fusion.js';
export * from './contradiction-detection.js';
export * from './cross-domain.js';
export * from './entity-resolution.js';
export * from './evidence-ranking.js';
export * from './freshness-decay.js';
export * from './query.js';
export * from './registry.js';
export * from './relationship-inference.js';
export * from './schema.js';
export * from './store.js';
export * from './types.js';

export const CONSTELLATION_VERSION = '2.0.0' as const;
