"""
Seven FabricLayer interfaces as Python typing.Protocol classes.

Each layer is the public contract a vertical pack implements.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..models import (
    BusinessSignal, BusinessTwin, Outcome, ActionBrief,
    CovenantPolicy, ProofPacket, Workcell,
)


@runtime_checkable
class CoverageGraphLayer(Protocol):
    def get_coverage(self, vertical: str) -> dict[str, float]: ...
    def register_twin(self, twin: BusinessTwin) -> None: ...
    def get_twins(self, vertical: str | None = None) -> list[BusinessTwin]: ...


@runtime_checkable
class SignalMeshLayer(Protocol):
    def ingest(self, signal: BusinessSignal) -> None: ...
    def query(self, vertical: str | None = None, severity: str | None = None) -> list[BusinessSignal]: ...
    def count(self) -> int: ...


@runtime_checkable
class StateEngineLayer(Protocol):
    def get_outcomes(self, vertical: str | None = None) -> list[Outcome]: ...
    def upsert_outcome(self, outcome: Outcome) -> None: ...
    def transition(self, outcome_id: str, new_status: str) -> Outcome | None: ...


@runtime_checkable
class CausalCoreLayer(Protocol):
    def link(self, signal_id: str, outcome_id: str) -> None: ...
    def get_causes(self, outcome_id: str) -> list[str]: ...
    def get_effects(self, signal_id: str) -> list[str]: ...


@runtime_checkable
class ActionRailLayer(Protocol):
    def propose(self, action: ActionBrief) -> ActionBrief: ...
    def list_actions(self, vertical: str | None = None) -> list[ActionBrief]: ...
    def approve(self, action_id: str) -> ActionBrief | None: ...
    def reject(self, action_id: str) -> ActionBrief | None: ...


@runtime_checkable
class CovenantLayerProtocol(Protocol):
    def register_policy(self, policy: CovenantPolicy) -> None: ...
    def evaluate(self, action: ActionBrief) -> tuple[bool, list[CovenantPolicy]]: ...
    def get_policies(self, vertical: str | None = None) -> list[CovenantPolicy]: ...


@runtime_checkable
class ProofLedgerLayer(Protocol):
    def record(self, packet: ProofPacket) -> None: ...
    def get_chain(self, entity_id: str) -> list[ProofPacket]: ...
    def verify_chain(self, entity_id: str) -> bool: ...
