const now = Date.now();
const minsAgo = (m: number) => new Date(now - m * 60 * 1000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 24 * 3600 * 1000).toISOString();
const daysFromNow = (d: number) => new Date(now + d * 24 * 3600 * 1000).toISOString();

export type Severity = "critical" | "high" | "medium" | "low";
export type Status = "open" | "active" | "acknowledged" | "resolved" | "closed" | "in_progress" | "blocked" | "done";

export interface DemoSignal {
  id: string;
  source: string;
  sourceType: "crm" | "slack" | "jira" | "email" | "monitoring" | "erp" | "hr" | "billing" | "cs_platform" | "project_mgmt";
  severity: Severity;
  title: string;
  summary: string;
  status: "active" | "acknowledged" | "resolved";
  detectedAt: string;
  affectedFunction: string;
  owner: string;
  valueAtRisk: number;
  tags: string[];
}

export interface DemoAlert {
  id: string;
  name: string;
  alertType: "threshold" | "anomaly" | "composite" | "sla_breach";
  service: string;
  metricName: string;
  condition: string;
  threshold: number | null;
  severity: Severity;
  status: "active" | "firing" | "resolved" | "silenced" | "draft";
  firingCount: number;
  lastFiredAt: string | null;
  description: string;
  notificationChannels: string[];
}

export interface DemoPriority {
  id: string;
  rank: number;
  title: string;
  owner: string;
  team: string;
  urgency: "immediate" | "today" | "this_week" | "next_week";
  scoreFactors: { label: string; weight: number; score: number }[];
  totalScore: number;
  valueProtected: number;
  dueBy: string;
  status: Status;
  signalIds: string[];
  role: "executive" | "operator" | "manager" | "compliance";
}

export interface DemoWorkflow {
  id: string;
  name: string;
  description: string;
  function: string;
  status: "running" | "stalled" | "completed" | "failed" | "paused";
  owner: string;
  team: string;
  startedAt: string;
  lastActivityAt: string;
  expectedCompletionAt: string;
  stallReason?: string;
  stages: { name: string; status: "done" | "active" | "pending" | "blocked"; daysSpent: number; expectedDays: number; owner: string }[];
  valueAtRisk: number;
  severity: Severity;
}

export interface DemoRun {
  id: string;
  workflowId: string;
  workflowName: string;
  triggeredBy: string;
  startedAt: string;
  completedAt: string | null;
  status: "running" | "completed" | "failed" | "timed_out";
  duration: number | null;
  steps: { step: string; status: "done" | "running" | "failed" | "skipped" | "pending"; durationMs: number; output?: string; error?: string }[];
  inputContext: string;
  outputSummary: string | null;
}

export interface DemoRecommendation {
  id: string;
  title: string;
  category: "revenue" | "risk_mitigation" | "operational" | "compliance" | "growth";
  confidence: "high" | "medium" | "low";
  confidenceScore: number;
  impact: "high" | "medium" | "low";
  valueEstimate: number;
  reasoning: string;
  evidence: string[];
  suggestedAction: string;
  owner: string;
  signalIds: string[];
  status: "pending" | "accepted" | "dismissed" | "in_progress";
  detectedAt: string;
}

export interface DemoAuditEvent {
  id: string;
  timestamp: string;
  actor: string;
  actorRole: string;
  action: string;
  resource: string;
  resourceId: string;
  context: string;
  outcome: "success" | "failure" | "partial";
  ipAddress: string;
  tags: string[];
}

export interface DemoException {
  id: string;
  title: string;
  category: "sla_breach" | "ownership_gap" | "data_quality" | "process_violation" | "capacity" | "compliance";
  severity: Severity;
  status: "open" | "acknowledged" | "escalated" | "resolved";
  detectedAt: string;
  owner: string | null;
  affectedSystem: string;
  description: string;
  resolution?: string;
  valueAtRisk: number;
  slaBreachAt?: string;
}

export interface DemoReadinessItem {
  id: string;
  category: string;
  title: string;
  description: string;
  status: "complete" | "in_progress" | "blocked" | "pending";
  score: number;
  owner: string;
  dueBy: string;
  complianceRef?: string;
  blockedReason?: string;
  lastReviewedAt?: string;
}

export interface DemoIntegration {
  id: string;
  name: string;
  type: "crm" | "ticketing" | "communication" | "monitoring" | "erp" | "hr" | "identity" | "analytics" | "billing" | "cs_platform";
  status: "connected" | "degraded" | "disconnected" | "configuring";
  lastSyncAt: string | null;
  syncFrequency: string;
  recordsIngested: number;
  errorsLast24h: number;
  owner: string;
  description: string;
  signalSources: number;
}

export interface DemoReport {
  id: string;
  name: string;
  type: "executive_summary" | "signal_digest" | "workflow_health" | "audit_log" | "readiness_assessment" | "forecast_variance";
  generatedAt: string;
  generatedBy: string;
  status: "complete" | "generating" | "scheduled" | "failed";
  recipientCount: number;
  format: "pdf" | "csv" | "html";
  schedule: string;
  fileSizeKb: number;
  summary: string;
}

export const demoSignals: DemoSignal[] = [
  {
    id: "DS-001",
    source: "Salesforce CRM",
    sourceType: "crm",
    severity: "critical",
    title: "Enterprise approval queue: 8 deals averaging 14.2 days — 340% above SLA",
    summary: "Eight enterprise deals totaling $4.2M ARR have been pending legal and finance approval for 10–18 business days. SLA target is 3.2 days.",
    status: "active",
    detectedAt: minsAgo(18),
    affectedFunction: "Enterprise Sales",
    owner: "Marcus Webb",
    valueAtRisk: 2100000,
    tags: ["approval_latency", "q1", "enterprise"],
  },
  {
    id: "DS-002",
    source: "Project Management System",
    sourceType: "project_mgmt",
    severity: "critical",
    title: "14 implementation projects stalled at handoff — zero assignees, SLA breached",
    summary: "Post-sale implementation queue has 14 projects with no CSM or implementation engineer assigned. All 14 exceed the 5-day first-contact SLA.",
    status: "active",
    detectedAt: minsAgo(35),
    affectedFunction: "Customer Success",
    owner: "Diana Reyes",
    valueAtRisk: 890000,
    tags: ["stalled_workflow", "onboarding", "sla_breach"],
  },
  {
    id: "DS-003",
    source: "Revenue Intelligence Platform",
    sourceType: "crm",
    severity: "critical",
    title: "Q1 mid-market forecast dropped $3.8M — 22 deals reclassified commit → best case",
    summary: "Steepest 10-day forecast decline in 6 quarters. Board commitment of $11.2M is at risk — current trajectory implies a $2.6M miss.",
    status: "active",
    detectedAt: minsAgo(8),
    affectedFunction: "Revenue",
    owner: "Priya Nair",
    valueAtRisk: 3800000,
    tags: ["forecast_drift", "q1", "mid_market"],
  },
  {
    id: "DS-004",
    source: "Salesforce CRM",
    sourceType: "crm",
    severity: "high",
    title: "7 enterprise renewals ($2.3M ARR) have no named owner — 60d to expiry",
    summary: "Seven enterprise accounts approaching renewal with no assigned AE or CSM. Unowned renewals churn at 4.2x the rate of owned accounts.",
    status: "active",
    detectedAt: minsAgo(52),
    affectedFunction: "Account Management",
    owner: "Unassigned",
    valueAtRisk: 2300000,
    tags: ["ownership_gap", "renewals", "enterprise"],
  },
  {
    id: "DS-005",
    source: "SE Queue Management",
    sourceType: "project_mgmt",
    severity: "high",
    title: "SE handoff queue at 31 deals — 9-day median wait vs 2-day SLA",
    summary: "SE team is receiving pre-sales technical requests 9 days after initial qualification. Queue has grown 47% in 3 weeks.",
    status: "acknowledged",
    detectedAt: minsAgo(74),
    affectedFunction: "Pre-Sales",
    owner: "James Okafor",
    valueAtRisk: 1400000,
    tags: ["handoff_failure", "pre_sales", "capacity"],
  },
  {
    id: "DS-006",
    source: "CRM Activity Logs",
    sourceType: "crm",
    severity: "high",
    title: "41% of pipeline opportunities inactive for 14+ days — $8.4M forecast inflation",
    summary: "116 of 284 active opportunities show no logged activity and no next step date. Pipeline hygiene at multi-quarter low.",
    status: "active",
    detectedAt: minsAgo(110),
    affectedFunction: "Sales Operations",
    owner: "Rosa Kim",
    valueAtRisk: 840000,
    tags: ["pipeline_hygiene", "forecast", "ops"],
  },
  {
    id: "DS-007",
    source: "Contract Management System",
    sourceType: "project_mgmt",
    severity: "high",
    title: "12 PS SOWs awaiting client signature — average 19 days outstanding",
    summary: "Professional services statements of work have been sent and are awaiting signature. $1.1M in delivery revenue is blocked.",
    status: "active",
    detectedAt: minsAgo(130),
    affectedFunction: "Professional Services",
    owner: "Anika Mehta",
    valueAtRisk: 1100000,
    tags: ["stalled_workflow", "delivery", "sow"],
  },
  {
    id: "DS-008",
    source: "Billing System",
    sourceType: "billing",
    severity: "medium",
    title: "23 accounts under-billed by $340K — usage tier rules not propagated",
    summary: "Usage telemetry shows 23 accounts consuming beyond contracted tier limits for 2+ billing cycles without overage charges applied.",
    status: "acknowledged",
    detectedAt: minsAgo(195),
    affectedFunction: "Finance",
    owner: "Tom Farrell",
    valueAtRisk: 340000,
    tags: ["revenue_leakage", "billing", "finance"],
  },
  {
    id: "DS-009",
    source: "Deal Desk System",
    sourceType: "crm",
    severity: "medium",
    title: "Discount approval chain averaging 5.8 days — 3 deals at close-date risk",
    summary: "Non-standard discount requests averaging 5.8 business days to approval vs 2-day standard. 3 deals with committed close dates blocked.",
    status: "active",
    detectedAt: minsAgo(220),
    affectedFunction: "Deal Desk",
    owner: "Kenji Watanabe",
    valueAtRisk: 870000,
    tags: ["approval_latency", "deal_desk", "enterprise"],
  },
  {
    id: "DS-010",
    source: "Slack #sales-ops",
    sourceType: "slack",
    severity: "medium",
    title: "18 deals in 'Proposal Sent' 30+ days — no response logged",
    summary: "Eighteen deals inflate pipeline by $2.1M but have negligible realistic probability. Proposal acceptance rate drops 60% after 3 weeks.",
    status: "active",
    detectedAt: minsAgo(280),
    affectedFunction: "Sales",
    owner: "Various",
    valueAtRisk: 420000,
    tags: ["pipeline_hygiene", "proposals", "mid_market"],
  },
  {
    id: "DS-011",
    source: "Revenue Intelligence Platform",
    sourceType: "crm",
    severity: "medium",
    title: "Enterprise Q1 pipeline coverage below 1.0x — first time in 5 quarters",
    summary: "Enterprise pipeline coverage against Q1 commit dropped to 0.94x. Historical target is 1.3x at this stage.",
    status: "active",
    detectedAt: minsAgo(340),
    affectedFunction: "Revenue",
    owner: "Sarah Donovan",
    valueAtRisk: 1800000,
    tags: ["forecast_drift", "enterprise", "q1"],
  },
  {
    id: "DS-012",
    source: "CS Platform",
    sourceType: "cs_platform",
    severity: "low",
    title: "QBR completion rate 61% — 29 enterprise accounts unreviewed",
    summary: "29 of 74 enterprise accounts due for QBR have not had a review completed or scheduled. Quarter ends in 22 business days.",
    status: "acknowledged",
    detectedAt: minsAgo(390),
    affectedFunction: "Customer Success",
    owner: "Maria Vasquez",
    valueAtRisk: 820000,
    tags: ["handoff_failure", "cs", "qbr"],
  },
  {
    id: "DS-013",
    source: "Email / Gmail",
    sourceType: "email",
    severity: "high",
    title: "Legal counsel flagged enterprise contract clause — deal blocked for 9 days",
    summary: "An email thread from SVP Legal surfaced a liability clause concern in the Accenture master agreement. The deal ($840K ARR) has been blocked pending legal redline. No owner has been assigned to drive resolution.",
    status: "active",
    detectedAt: hoursAgo(4),
    affectedFunction: "Legal / Enterprise Sales",
    owner: "Marcus Webb",
    valueAtRisk: 840000,
    tags: ["contract_block", "legal", "enterprise"],
  },
  {
    id: "DS-014",
    source: "Jira",
    sourceType: "jira",
    severity: "high",
    title: "38 engineering tickets tagged 'customer-blocker' unresolved — avg age 12 days",
    summary: "Customer-facing blocker tickets in Jira have accumulated to 38 open items averaging 12 days without resolution. 6 enterprise customers are impacted and 3 have escalated via CSM.",
    status: "active",
    detectedAt: hoursAgo(7),
    affectedFunction: "Engineering / Customer Success",
    owner: "Diana Reyes",
    valueAtRisk: 650000,
    tags: ["product_blocker", "jira", "escalation"],
  },
  {
    id: "DS-015",
    source: "Infrastructure Monitoring",
    sourceType: "monitoring",
    severity: "critical",
    title: "API p99 latency spike: 4,200ms — 3x SLO breach, affecting 12 enterprise tenants",
    summary: "Production API gateway latency exceeded SLO threshold (1,400ms p99) for 47 consecutive minutes. Affecting Tier 1 and Tier 2 enterprise tenants. Root cause: cache eviction cascade following the 03:00 UTC deploy.",
    status: "active",
    detectedAt: minsAgo(52),
    affectedFunction: "Platform Engineering",
    owner: "Alex Kim",
    valueAtRisk: 1200000,
    tags: ["slo_breach", "latency", "production"],
  },
];

export const demoAlerts: DemoAlert[] = [
  {
    id: "ALT-001",
    name: "Approval Latency > 10 Days",
    alertType: "threshold",
    service: "CRM Workflow Engine",
    metricName: "avg_approval_dwell_days",
    condition: "gt",
    threshold: 10,
    severity: "critical",
    status: "firing",
    firingCount: 14,
    lastFiredAt: minsAgo(18),
    description: "Triggers when average deal approval latency exceeds 10 business days across the enterprise segment.",
    notificationChannels: ["slack:#revenue-ops", "email:marcus.webb@company.com", "pagerduty:sales-oncall"],
  },
  {
    id: "ALT-002",
    name: "Implementation Queue SLA Breach",
    alertType: "sla_breach",
    service: "Project Management System",
    metricName: "implementation_handoff_days",
    condition: "gt",
    threshold: 5,
    severity: "critical",
    status: "firing",
    firingCount: 8,
    lastFiredAt: minsAgo(35),
    description: "Fires when any implementation project goes beyond 5 business days without an assigned CSM or implementation engineer.",
    notificationChannels: ["slack:#cs-ops", "email:diana.reyes@company.com"],
  },
  {
    id: "ALT-003",
    name: "Forecast Variance Anomaly",
    alertType: "anomaly",
    service: "Revenue Intelligence Platform",
    metricName: "commit_forecast_delta_7d",
    condition: "anomaly",
    threshold: null,
    severity: "critical",
    status: "firing",
    firingCount: 3,
    lastFiredAt: minsAgo(8),
    description: "Anomaly detection on 7-day forecast movement. Triggers when drift exceeds 2.5 standard deviations from 90-day baseline.",
    notificationChannels: ["slack:#revenue-leadership", "email:cro@company.com"],
  },
  {
    id: "ALT-004",
    name: "Unowned High-Value Renewals",
    alertType: "threshold",
    service: "CRM Ownership Engine",
    metricName: "unowned_renewal_arr",
    condition: "gt",
    threshold: 500000,
    severity: "high",
    status: "firing",
    firingCount: 6,
    lastFiredAt: minsAgo(52),
    description: "Alerts when total ARR of renewals without an assigned owner exceeds $500K at 60+ days to expiry.",
    notificationChannels: ["slack:#account-management", "email:enterprise-cs@company.com"],
  },
  {
    id: "ALT-005",
    name: "SE Queue Median Wait > 5 Days",
    alertType: "threshold",
    service: "SE Queue Manager",
    metricName: "se_queue_median_wait_days",
    condition: "gte",
    threshold: 5,
    severity: "high",
    status: "active",
    firingCount: 2,
    lastFiredAt: hoursAgo(6),
    description: "Fires when the median time for SE queue assignment exceeds 5 days — impacts pre-sales win rates.",
    notificationChannels: ["slack:#solutions-engineering"],
  },
  {
    id: "ALT-006",
    name: "Pipeline Activity Staleness > 35%",
    alertType: "threshold",
    service: "CRM Activity Monitor",
    metricName: "pct_pipeline_stale_14d",
    condition: "gt",
    threshold: 35,
    severity: "high",
    status: "active",
    firingCount: 4,
    lastFiredAt: hoursAgo(2),
    description: "Tracks what percentage of active pipeline has had no logged activity in 14+ days. Target is < 20%.",
    notificationChannels: ["slack:#revenue-ops", "email:rosa.kim@company.com"],
  },
  {
    id: "ALT-007",
    name: "Billing Reconciliation Discrepancy",
    alertType: "composite",
    service: "Billing Reconciliation Engine",
    metricName: "billing_mismatch_usd",
    condition: "gt",
    threshold: 50000,
    severity: "medium",
    status: "active",
    firingCount: 1,
    lastFiredAt: hoursAgo(4),
    description: "Composite rule: fires when usage telemetry and billed amounts diverge by more than $50K for any trailing 30-day window.",
    notificationChannels: ["slack:#finance-ops", "email:tom.farrell@company.com"],
  },
  {
    id: "ALT-008",
    name: "QBR Coverage < 70%",
    alertType: "threshold",
    service: "CS Platform",
    metricName: "enterprise_qbr_completion_pct",
    condition: "lt",
    threshold: 70,
    severity: "medium",
    status: "active",
    firingCount: 1,
    lastFiredAt: hoursAgo(8),
    description: "Fires when quarterly business review completion rate for enterprise accounts falls below 70% with 30+ days remaining in the quarter.",
    notificationChannels: ["slack:#customer-success"],
  },
  {
    id: "ALT-009",
    name: "Critical Signal Threshold",
    alertType: "threshold",
    service: "Lyte Signal Engine",
    metricName: "active_critical_signals",
    condition: "gte",
    threshold: 3,
    severity: "critical",
    status: "active",
    firingCount: 22,
    lastFiredAt: minsAgo(5),
    description: "Master alert: fires when 3 or more critical severity signals are active simultaneously. Indicates systemic operational stress.",
    notificationChannels: ["slack:#lyte-critical", "pagerduty:executive-oncall", "email:coo@company.com"],
  },
  {
    id: "ALT-010",
    name: "SOW Signature Latency",
    alertType: "threshold",
    service: "Contract Management System",
    metricName: "sow_avg_days_outstanding",
    condition: "gt",
    threshold: 14,
    severity: "medium",
    status: "silenced",
    firingCount: 0,
    lastFiredAt: daysAgo(2),
    description: "Alerts when average SOW signature wait time exceeds 14 days. Silenced pending client legal team availability review.",
    notificationChannels: ["slack:#delivery-ops"],
  },
];

export const demoPriorities: DemoPriority[] = [
  {
    id: "PRI-001",
    rank: 1,
    title: "Escalate 3 enterprise deals to CFO approval track",
    owner: "Marcus Webb",
    team: "Revenue Operations",
    urgency: "immediate",
    scoreFactors: [
      { label: "Value at Risk", weight: 0.4, score: 95 },
      { label: "Time Sensitivity", weight: 0.3, score: 98 },
      { label: "Probability Decay", weight: 0.2, score: 88 },
      { label: "Exec Visibility", weight: 0.1, score: 90 },
    ],
    totalScore: 94,
    valueProtected: 2100000,
    dueBy: "Today, 5 PM",
    status: "open",
    signalIds: ["DS-001"],
    role: "executive",
  },
  {
    id: "PRI-002",
    rank: 2,
    title: "Assign implementation engineers to 14 stalled onboarding projects",
    owner: "Diana Reyes",
    team: "Delivery Operations",
    urgency: "immediate",
    scoreFactors: [
      { label: "SLA Breach Severity", weight: 0.4, score: 100 },
      { label: "Churn Risk", weight: 0.35, score: 92 },
      { label: "Account Health Impact", weight: 0.15, score: 85 },
      { label: "Time Elapsed", weight: 0.1, score: 78 },
    ],
    totalScore: 93,
    valueProtected: 890000,
    dueBy: "Today",
    status: "in_progress",
    signalIds: ["DS-002"],
    role: "operator",
  },
  {
    id: "PRI-003",
    rank: 3,
    title: "Convene Q1 forecast recovery session with VP Sales and segment leads",
    owner: "Priya Nair",
    team: "Mid-Market Sales",
    urgency: "today",
    scoreFactors: [
      { label: "Revenue Impact", weight: 0.45, score: 98 },
      { label: "Board Commitment Risk", weight: 0.3, score: 95 },
      { label: "Pipeline Coverage", weight: 0.15, score: 60 },
      { label: "Lead Time to Act", weight: 0.1, score: 72 },
    ],
    totalScore: 89,
    valueProtected: 3800000,
    dueBy: "Today, EOD",
    status: "open",
    signalIds: ["DS-003", "DS-011"],
    role: "executive",
  },
  {
    id: "PRI-004",
    rank: 4,
    title: "Assign AE/CSM pairs to 7 unowned enterprise renewals",
    owner: "Sarah Donovan",
    team: "Enterprise Sales",
    urgency: "today",
    scoreFactors: [
      { label: "Churn Probability", weight: 0.4, score: 88 },
      { label: "ARR at Risk", weight: 0.35, score: 82 },
      { label: "Days to Renewal", weight: 0.15, score: 70 },
      { label: "Historical Win Rate Decay", weight: 0.1, score: 85 },
    ],
    totalScore: 84,
    valueProtected: 2300000,
    dueBy: "Today",
    status: "open",
    signalIds: ["DS-004"],
    role: "manager",
  },
  {
    id: "PRI-005",
    rank: 5,
    title: "Triage SE queue — fast-track 6 deals >$500K TCV",
    owner: "James Okafor",
    team: "Solutions Engineering",
    urgency: "today",
    scoreFactors: [
      { label: "Win Rate Impact", weight: 0.4, score: 80 },
      { label: "Deal Value", weight: 0.3, score: 78 },
      { label: "Queue Age", weight: 0.2, score: 82 },
      { label: "Competitive Pressure", weight: 0.1, score: 65 },
    ],
    totalScore: 79,
    valueProtected: 1400000,
    dueBy: "Today, 3 PM",
    status: "open",
    signalIds: ["DS-005"],
    role: "operator",
  },
  {
    id: "PRI-006",
    rank: 6,
    title: "Pipeline review: all reps must log next steps on stale opportunities",
    owner: "Rosa Kim",
    team: "Revenue Operations",
    urgency: "this_week",
    scoreFactors: [
      { label: "Forecast Accuracy Impact", weight: 0.4, score: 72 },
      { label: "Pipeline Credibility", weight: 0.3, score: 68 },
      { label: "Rep Capacity", weight: 0.2, score: 55 },
      { label: "Process Risk", weight: 0.1, score: 60 },
    ],
    totalScore: 67,
    valueProtected: 840000,
    dueBy: "Friday",
    status: "open",
    signalIds: ["DS-006", "DS-010"],
    role: "operator",
  },
  {
    id: "PRI-007",
    rank: 7,
    title: "Finance audit: reconcile usage billing for 23 accounts",
    owner: "Tom Farrell",
    team: "Finance Operations",
    urgency: "this_week",
    scoreFactors: [
      { label: "Revenue Leakage", weight: 0.45, score: 70 },
      { label: "Billing Accuracy Risk", weight: 0.3, score: 65 },
      { label: "Customer Impact", weight: 0.15, score: 55 },
      { label: "Audit Trail Completeness", weight: 0.1, score: 80 },
    ],
    totalScore: 67,
    valueProtected: 340000,
    dueBy: "Thursday",
    status: "open",
    signalIds: ["DS-008"],
    role: "compliance",
  },
  {
    id: "PRI-008",
    rank: 8,
    title: "CS outreach to 29 enterprise accounts — schedule QBRs before quarter-end",
    owner: "Maria Vasquez",
    team: "Enterprise Customer Success",
    urgency: "this_week",
    scoreFactors: [
      { label: "Churn Risk at Renewal", weight: 0.4, score: 65 },
      { label: "ARR Exposure", weight: 0.3, score: 70 },
      { label: "Days Remaining in Quarter", weight: 0.2, score: 60 },
      { label: "Relationship Health", weight: 0.1, score: 50 },
    ],
    totalScore: 64,
    valueProtected: 820000,
    dueBy: "Friday",
    status: "in_progress",
    signalIds: ["DS-012"],
    role: "operator",
  },
];

export const demoWorkflows: DemoWorkflow[] = [
  {
    id: "WF-001",
    name: "Enterprise Deal Approval",
    description: "Multi-stage approval chain for enterprise deals requiring legal review, finance sign-off, and executive authorization.",
    function: "Revenue / Legal / Finance",
    status: "stalled",
    owner: "Marcus Webb",
    team: "Revenue Operations",
    startedAt: daysAgo(18),
    lastActivityAt: daysAgo(7),
    expectedCompletionAt: daysAgo(15),
    stallReason: "Legal review assigned to single reviewer handling 12 concurrent deals. Finance approval queue auto-paused pending CISO sign-off.",
    stages: [
      { name: "Deal Desk Review", status: "done", daysSpent: 1.8, expectedDays: 1.0, owner: "Deal Desk" },
      { name: "Legal Review", status: "blocked", daysSpent: 7.1, expectedDays: 1.5, owner: "Legal" },
      { name: "Finance Approval", status: "pending", daysSpent: 0, expectedDays: 0.5, owner: "CFO Office" },
      { name: "Executive Sign-off", status: "pending", daysSpent: 0, expectedDays: 0.2, owner: "VP Sales" },
    ],
    valueAtRisk: 2100000,
    severity: "critical",
  },
  {
    id: "WF-002",
    name: "Implementation Handoff Protocol",
    description: "Automated handoff from sales close to customer success and implementation engineering assignment.",
    function: "Customer Success / Delivery",
    status: "stalled",
    owner: "Diana Reyes",
    team: "Delivery Operations",
    startedAt: daysAgo(11),
    lastActivityAt: daysAgo(5),
    expectedCompletionAt: daysAgo(9),
    stallReason: "2 senior implementation managers on unplanned leave. Auto-assignment pool exhausted. Manual escalation required.",
    stages: [
      { name: "Sales Close Logged", status: "done", daysSpent: 0.5, expectedDays: 0.5, owner: "Sales Ops" },
      { name: "CS Handoff", status: "blocked", daysSpent: 4.2, expectedDays: 0.5, owner: "Sales Ops" },
      { name: "CSM Assignment", status: "pending", daysSpent: 0, expectedDays: 0.5, owner: "CS Leadership" },
      { name: "IM Assignment", status: "pending", daysSpent: 0, expectedDays: 1.0, owner: "Delivery Ops" },
    ],
    valueAtRisk: 890000,
    severity: "critical",
  },
  {
    id: "WF-003",
    name: "PS Statement of Work Signature",
    description: "Client-facing SOW review and signature collection for professional services engagements.",
    function: "Professional Services / Delivery",
    status: "stalled",
    owner: "Anika Mehta",
    team: "Delivery",
    startedAt: daysAgo(19),
    lastActivityAt: daysAgo(3),
    expectedCompletionAt: daysAgo(12),
    stallReason: "Client legal teams at 3 accounts have entered extended review cycles. E-signature platform auto-expiry triggered on 2 documents.",
    stages: [
      { name: "PS Scoping Complete", status: "done", daysSpent: 2.0, expectedDays: 2.0, owner: "PS Team" },
      { name: "Internal SOW Draft", status: "done", daysSpent: 3.5, expectedDays: 2.0, owner: "Legal" },
      { name: "Client Review", status: "active", daysSpent: 10.5, expectedDays: 3.0, owner: "Client" },
      { name: "Countersignature", status: "pending", daysSpent: 0, expectedDays: 0.5, owner: "Anika Mehta" },
    ],
    valueAtRisk: 1100000,
    severity: "high",
  },
  {
    id: "WF-004",
    name: "SE Engagement Assignment",
    description: "Solutions engineer assignment queue from initial qualification through technical discovery kickoff.",
    function: "Pre-Sales",
    status: "stalled",
    owner: "James Okafor",
    team: "Solutions Engineering",
    startedAt: daysAgo(9),
    lastActivityAt: daysAgo(1),
    expectedCompletionAt: daysAgo(7),
    stallReason: "SE team at 94% capacity. Priority matrix not updated to reflect Q1 deal urgency. 6 deals >$500K TCV waiting without triage.",
    stages: [
      { name: "Qualification Logged", status: "done", daysSpent: 1.0, expectedDays: 0.5, owner: "Sales" },
      { name: "SE Queue Entry", status: "blocked", daysSpent: 5.8, expectedDays: 0.5, owner: "SE Ops" },
      { name: "SE Assignment", status: "pending", daysSpent: 0, expectedDays: 1.0, owner: "SE Leadership" },
      { name: "Discovery Call Booked", status: "pending", daysSpent: 0, expectedDays: 0.5, owner: "SE" },
    ],
    valueAtRisk: 1400000,
    severity: "high",
  },
  {
    id: "WF-005",
    name: "Enterprise Renewal Cycle",
    description: "90-day renewal engagement workflow from early warning flag through commercial close.",
    function: "Account Management",
    status: "running",
    owner: "Sarah Donovan",
    team: "Enterprise Sales",
    startedAt: daysAgo(22),
    lastActivityAt: hoursAgo(3),
    expectedCompletionAt: daysFromNow(30),
    stages: [
      { name: "Renewal Flag (90d)", status: "done", daysSpent: 5.0, expectedDays: 1.0, owner: "RevOps" },
      { name: "Owner Assignment", status: "active", daysSpent: 9.0, expectedDays: 2.0, owner: "Enterprise Sales" },
      { name: "Health Check", status: "pending", daysSpent: 0, expectedDays: 3.0, owner: "CSM" },
      { name: "Negotiation", status: "pending", daysSpent: 0, expectedDays: 8.0, owner: "AE" },
    ],
    valueAtRisk: 2300000,
    severity: "high",
  },
  {
    id: "WF-006",
    name: "Discount Approval Chain",
    description: "Non-standard discount authorization requiring VP-level and CFO sign-off for deals requiring >25% discount.",
    function: "Deal Desk / Finance",
    status: "running",
    owner: "Kenji Watanabe",
    team: "Deal Desk",
    startedAt: daysAgo(6),
    lastActivityAt: hoursAgo(1),
    expectedCompletionAt: daysAgo(4),
    stages: [
      { name: "Deal Desk Intake", status: "done", daysSpent: 0.5, expectedDays: 0.5, owner: "Deal Desk" },
      { name: "VP Sales Approval", status: "active", daysSpent: 3.8, expectedDays: 1.0, owner: "VP Sales" },
      { name: "CFO Sign-off", status: "pending", daysSpent: 0, expectedDays: 0.5, owner: "CFO Office" },
      { name: "Deal Desk Close", status: "pending", daysSpent: 0, expectedDays: 0.5, owner: "Deal Desk" },
    ],
    valueAtRisk: 870000,
    severity: "medium",
  },
  {
    id: "WF-007",
    name: "QBR Scheduling & Delivery",
    description: "Quarterly business review outreach, scheduling, and delivery for enterprise accounts.",
    function: "Customer Success",
    status: "running",
    owner: "Maria Vasquez",
    team: "Enterprise Customer Success",
    startedAt: daysAgo(14),
    lastActivityAt: hoursAgo(2),
    expectedCompletionAt: daysFromNow(8),
    stages: [
      { name: "Account Identification", status: "done", daysSpent: 1.0, expectedDays: 1.0, owner: "CS Ops" },
      { name: "CSM Outreach", status: "active", daysSpent: 8.0, expectedDays: 3.0, owner: "CSM Team" },
      { name: "Session Scheduling", status: "active", daysSpent: 5.0, expectedDays: 2.0, owner: "CS Team" },
      { name: "QBR Delivery", status: "pending", daysSpent: 0, expectedDays: 5.0, owner: "CSM" },
    ],
    valueAtRisk: 820000,
    severity: "medium",
  },
  {
    id: "WF-008",
    name: "Billing Reconciliation Audit",
    description: "Monthly billing reconciliation between usage telemetry and invoiced amounts with automated discrepancy flagging.",
    function: "Finance / Operations",
    status: "completed",
    owner: "Tom Farrell",
    team: "Finance Operations",
    startedAt: daysAgo(5),
    lastActivityAt: hoursAgo(18),
    expectedCompletionAt: daysAgo(3),
    stages: [
      { name: "Usage Data Pull", status: "done", daysSpent: 0.5, expectedDays: 0.5, owner: "Data Eng" },
      { name: "Billing System Extract", status: "done", daysSpent: 0.5, expectedDays: 0.5, owner: "Finance Ops" },
      { name: "Discrepancy Detection", status: "done", daysSpent: 1.0, expectedDays: 1.0, owner: "Billing Engine" },
      { name: "Remediation Plan", status: "done", daysSpent: 1.5, expectedDays: 2.0, owner: "Tom Farrell" },
    ],
    valueAtRisk: 340000,
    severity: "medium",
  },
];

export const demoRuns: DemoRun[] = [
  {
    id: "RUN-001",
    workflowId: "WF-001",
    workflowName: "Enterprise Deal Approval",
    triggeredBy: "Lyte Signal Engine (DS-001)",
    startedAt: daysAgo(18),
    completedAt: null,
    status: "running",
    duration: null,
    steps: [
      { step: "Detect approval latency anomaly", status: "done", durationMs: 234, output: "14.2 days avg detected — threshold 3.2 days" },
      { step: "Identify affected deal IDs", status: "done", durationMs: 1820, output: "8 deals identified: VER-001, APX-004, MRD-002..." },
      { step: "Route notification to RevOps", status: "done", durationMs: 412, output: "Slack notification sent to #revenue-ops" },
      { step: "Assign escalation owner", status: "done", durationMs: 890, output: "Marcus Webb assigned as escalation owner" },
      { step: "Generate CFO briefing draft", status: "running", durationMs: 0 },
      { step: "Await CFO approval action", status: "pending", durationMs: 0 },
    ],
    inputContext: "Signal DS-001: 8 enterprise deals averaging 14.2d approval latency",
    outputSummary: null,
  },
  {
    id: "RUN-002",
    workflowId: "WF-002",
    workflowName: "Implementation Handoff Protocol",
    triggeredBy: "Scheduled Check + Signal DS-002",
    startedAt: daysAgo(11),
    completedAt: null,
    status: "running",
    duration: null,
    steps: [
      { step: "Scan implementation queue for unassigned projects", status: "done", durationMs: 1203, output: "14 projects found without assignee > 5 business days" },
      { step: "Check bench capacity pool", status: "done", durationMs: 2100, output: "0 IMs available — 2 on unplanned leave, 3 at 100% capacity" },
      { step: "Trigger auto-escalation to CS Leadership", status: "done", durationMs: 680, output: "Escalation email sent to Diana Reyes" },
      { step: "Attempt overflow staffing lookup", status: "failed", durationMs: 3200, error: "Staffing platform API timeout — retry queued" },
      { step: "Manual intervention required", status: "running", durationMs: 0 },
    ],
    inputContext: "14 implementation projects, 0 available IMs, SLA breached on all 14",
    outputSummary: null,
  },
  {
    id: "RUN-003",
    workflowId: "WF-008",
    workflowName: "Billing Reconciliation Audit",
    triggeredBy: "Monthly Scheduled Trigger",
    startedAt: daysAgo(5),
    completedAt: hoursAgo(18),
    status: "completed",
    duration: 345600000,
    steps: [
      { step: "Pull usage telemetry for all accounts", status: "done", durationMs: 8420, output: "2,847 account-months of usage data loaded" },
      { step: "Extract billing system invoiced amounts", status: "done", durationMs: 12300, output: "Invoice data for 2,847 accounts loaded" },
      { step: "Run discrepancy detection algorithm", status: "done", durationMs: 45200, output: "23 accounts flagged: total gap $340,200" },
      { step: "Categorize by root cause", status: "done", durationMs: 3100, output: "All 23: usage tier rule propagation failure on migration" },
      { step: "Generate remediation report", status: "done", durationMs: 2800, output: "Report sent to finance-ops@company.com" },
      { step: "Create Jira tickets for corrections", status: "done", durationMs: 1900, output: "23 tickets created — assigned to billing ops team" },
    ],
    inputContext: "Monthly reconciliation: April 2025 billing cycle",
    outputSummary: "23 accounts identified with $340K billing gap. Root cause: tier rule migration failure. 23 Jira tickets created.",
  },
  {
    id: "RUN-004",
    workflowId: "WF-006",
    workflowName: "Discount Approval Chain",
    triggeredBy: "Deal Desk Submission (Kenji Watanabe)",
    startedAt: daysAgo(6),
    completedAt: null,
    status: "running",
    duration: null,
    steps: [
      { step: "Validate discount request parameters", status: "done", durationMs: 450, output: "3 deals qualify for CFO track (>25% discount)" },
      { step: "Route to VP Sales approval queue", status: "done", durationMs: 310, output: "Approval request sent to VP Sales inbox" },
      { step: "Await VP approval", status: "running", durationMs: 0 },
      { step: "Route to CFO sign-off", status: "pending", durationMs: 0 },
    ],
    inputContext: "3 deals with non-standard discount requests pending VP + CFO approval",
    outputSummary: null,
  },
  {
    id: "RUN-005",
    workflowId: "WF-003",
    workflowName: "PS Statement of Work Signature",
    triggeredBy: "Contract Management System (auto)",
    startedAt: daysAgo(19),
    completedAt: null,
    status: "running",
    duration: null,
    steps: [
      { step: "Validate SOW completeness", status: "done", durationMs: 820, output: "12 SOWs validated — all complete and signed internally" },
      { step: "Send to client via DocuSign", status: "done", durationMs: 2300, output: "12 envelopes sent to client legal teams" },
      { step: "Monitor signature status", status: "running", durationMs: 0 },
      { step: "Follow-up trigger (7 days)", status: "pending", durationMs: 0 },
      { step: "Executive escalation (14 days)", status: "pending", durationMs: 0 },
    ],
    inputContext: "12 PS SOWs sent to clients for signature. Target turnaround: 7 days.",
    outputSummary: null,
  },
  {
    id: "RUN-006",
    workflowId: "WF-001",
    workflowName: "Enterprise Deal Approval",
    triggeredBy: "Manual Trigger (Marcus Webb)",
    startedAt: daysAgo(25),
    completedAt: daysAgo(20),
    status: "completed",
    duration: 432000000,
    steps: [
      { step: "Detect approval latency anomaly", status: "done", durationMs: 210, output: "11.8 days avg — threshold 3.2 days (previous run)" },
      { step: "Identify affected deal IDs", status: "done", durationMs: 1650, output: "5 deals identified" },
      { step: "Route notification to RevOps", status: "done", durationMs: 380, output: "Notification sent" },
      { step: "Assign escalation owner", status: "done", durationMs: 720, output: "Marcus Webb assigned" },
      { step: "Generate CFO briefing draft", status: "done", durationMs: 4200, output: "Briefing doc generated and sent" },
      { step: "Await CFO approval action", status: "done", durationMs: 86400000, output: "CFO approved 4 of 5 deals — 1 returned for revision" },
    ],
    inputContext: "Signal: 5 enterprise deals with 11.8d avg approval latency (prior period)",
    outputSummary: "4 deals approved, 1 returned for revision. Average approval time reduced to 5.2 days on approved deals.",
  },
];

export const demoRecommendations: DemoRecommendation[] = [
  {
    id: "REC-001",
    title: "Implement parallel legal review track for deals >$1M TCV",
    category: "revenue",
    confidence: "high",
    confidenceScore: 91,
    impact: "high",
    valueEstimate: 1800000,
    reasoning: "Analysis of 24 months of enterprise deal data shows that deals >$1M TCV spend 42% of total approval latency in sequential legal review. A parallel track where two reviewers share the load would reduce average legal dwell from 7.1 days to 3.2 days based on comparable workflows at 3 peer companies in the dataset.",
    evidence: [
      "Current legal dwell: 7.1 days avg (SIG-001)",
      "Peer company benchmark: 3.2 days with parallel review",
      "8 deals currently blocked in this stage",
      "Q1 forecast impact of $2.1M if not resolved",
    ],
    suggestedAction: "Establish a two-reviewer rotation for enterprise legal review. Assign backup counsel to all deals >$1M TCV at submission time, not after bottleneck occurs.",
    owner: "Legal / Revenue Operations",
    signalIds: ["DS-001"],
    status: "pending",
    detectedAt: minsAgo(22),
  },
  {
    id: "REC-002",
    title: "Pre-approve discount bands to eliminate CFO bottleneck for standard cases",
    category: "operational",
    confidence: "high",
    confidenceScore: 87,
    impact: "high",
    valueEstimate: 870000,
    reasoning: "Of the 11 current discount approval requests, 8 fall within a narrow range of 25–30% that represents 73% of all historical non-standard discount requests. Pre-approving a 30% band with appropriate safeguards (deal size, segment, quarter) would eliminate CFO involvement in the majority of cases and reduce average approval cycle by 4.1 days.",
    evidence: [
      "73% of all discount requests fall in 25–30% range (DS-009)",
      "Current approval avg: 5.8 days (target: 2 days)",
      "3 deals at risk of missing close dates in 7 days",
      "VP/CFO travel adds 2.1 days average to cycle",
    ],
    suggestedAction: "Define pre-approved discount band (25–30%) for mid-market deals <$150K TCV with minimum 12-month term. Route only outliers above 30% to CFO. Review quarterly.",
    owner: "CFO / Deal Desk",
    signalIds: ["DS-009"],
    status: "pending",
    detectedAt: hoursAgo(4),
  },
  {
    id: "REC-003",
    title: "Activate overflow implementation capacity protocol for Q1 surge",
    category: "risk_mitigation",
    confidence: "high",
    confidenceScore: 94,
    impact: "high",
    valueEstimate: 890000,
    reasoning: "Current implementation queue volume is 67% above 30-day average. Two senior IMs on simultaneous leave has exposed a single point of failure in the capacity model. Activating the overflow staffing protocol (partner network + contractor pool) would reduce queue dwell from 11.4 days to under 3 days within 4 business days.",
    evidence: [
      "14 stalled projects, 0 available IMs (DS-002)",
      "All 14 exceed 5-day SLA",
      "Queue volume 67% above 30d average",
      "4 accounts showing early churn signals",
    ],
    suggestedAction: "Activate overflow staffing protocol immediately. Engage contractor pool for temporary capacity. Prioritize 4 highest-ARR accounts for same-day assignment. Brief executive team on churn risk.",
    owner: "Diana Reyes / VP CS",
    signalIds: ["DS-002"],
    status: "in_progress",
    detectedAt: hoursAgo(6),
  },
  {
    id: "REC-004",
    title: "Accelerate Q1 close via pull-forward strategy for 3 late-stage Q2 deals",
    category: "revenue",
    confidence: "medium",
    confidenceScore: 72,
    impact: "high",
    valueEstimate: 2600000,
    reasoning: "Q1 board commitment of $11.2M is currently at $2.6M gap risk. Analysis of Q2 pipeline shows 3 deals in late stage (>70% probability) totaling $3.1M TCV with customers who have indicated budget availability in Q1 if incentive is offered. Estimated pull-forward probability at 58% based on similar historical pull-forward campaigns.",
    evidence: [
      "Q1 forecast gap: $2.6M (DS-003)",
      "3 Q2 deals >70% probability, combined TCV: $3.1M",
      "Historical pull-forward success rate: 58%",
      "Board commitment at risk if no action by end of week",
    ],
    suggestedAction: "VP Sales to personally outreach to 3 target accounts with Q1 incentive offer (expedited onboarding + Q1 pricing commitment). Engage executive sponsor at each account.",
    owner: "VP Sales",
    signalIds: ["DS-003", "DS-011"],
    status: "pending",
    detectedAt: minsAgo(15),
  },
  {
    id: "REC-005",
    title: "Automate renewal owner assignment from AE departure workflow",
    category: "operational",
    confidence: "high",
    confidenceScore: 89,
    impact: "medium",
    valueEstimate: 1200000,
    reasoning: "Root cause analysis shows that both ownership gaps on renewals were created when AEs departed without triggering territory reassignment. The HR offboarding workflow and CRM are not integrated — ownership gaps are only discovered when renewals are 60+ days out. An automated trigger from HR termination events to CRM territory reassignment would prevent recurrence.",
    evidence: [
      "7 unowned renewals traced to 2 recent AE departures (DS-004)",
      "Average gap discovery delay: 47 days",
      "HR offboarding and CRM not integrated",
      "Historical unowned renewal churn rate: 4.2x",
    ],
    suggestedAction: "Build HR → CRM integration trigger on employee offboarding events. Auto-flag all accounts owned by departing AE. Route to territory manager within 24 hours of termination event.",
    owner: "RevOps / IT",
    signalIds: ["DS-004"],
    status: "pending",
    detectedAt: hoursAgo(12),
  },
  {
    id: "REC-006",
    title: "Revise SE priority matrix to weight deal TCV over submission order",
    category: "growth",
    confidence: "medium",
    confidenceScore: 76,
    impact: "medium",
    valueEstimate: 800000,
    reasoning: "Current SE queue operates on FIFO basis. Analysis shows 6 deals >$500K TCV are waiting behind 14 deals <$100K in queue. Win rate correlation analysis shows SE engagement in first 7 days of qualification has 28% higher win rate. Re-weighting queue by TCV and stage would prioritize $1.4M at-risk deals without requiring additional headcount.",
    evidence: [
      "6 deals >$500K TCV in queue, median wait 9 days (DS-005)",
      "SE engagement <7 days correlates with 28% higher win rate",
      "Current FIFO queue: 31 deals, no priority weighting",
      "Queue growth 47% over 3 weeks",
    ],
    suggestedAction: "Update SE queue algorithm: weight by (TCV × stage probability) / days in queue. Apply immediately to existing queue. Review with SE leadership weekly.",
    owner: "James Okafor / SE Leadership",
    signalIds: ["DS-005"],
    status: "pending",
    detectedAt: hoursAgo(18),
  },
];

export const demoAuditEvents: DemoAuditEvent[] = [
  {
    id: "AUD-001",
    timestamp: minsAgo(8),
    actor: "Lyte Signal Engine",
    actorRole: "System",
    action: "Signal Detected",
    resource: "Signal",
    resourceId: "DS-003",
    context: "Q1 forecast variance anomaly detected — $3.8M drop over 10-day window exceeds 2.5σ baseline. Notification dispatched to revenue leadership.",
    outcome: "success",
    ipAddress: "10.0.1.45",
    tags: ["signal", "automated", "forecast"],
  },
  {
    id: "AUD-002",
    timestamp: minsAgo(18),
    actor: "Marcus Webb",
    actorRole: "VP Revenue Operations",
    action: "Signal Acknowledged",
    resource: "Signal",
    resourceId: "DS-001",
    context: "Marcus Webb acknowledged approval latency signal and created escalation action item for CFO approval track. Assigned follow-up to self.",
    outcome: "success",
    ipAddress: "192.168.1.102",
    tags: ["signal", "escalation", "manual"],
  },
  {
    id: "AUD-003",
    timestamp: minsAgo(35),
    actor: "Lyte Workflow Engine",
    actorRole: "System",
    action: "Escalation Triggered",
    resource: "Workflow",
    resourceId: "WF-002",
    context: "Auto-escalation triggered on Implementation Handoff workflow — 14 projects exceeded 5-day SLA threshold. Escalation email dispatched to Diana Reyes (VP CS).",
    outcome: "success",
    ipAddress: "10.0.1.45",
    tags: ["workflow", "escalation", "automated", "sla_breach"],
  },
  {
    id: "AUD-004",
    timestamp: hoursAgo(2),
    actor: "Diana Reyes",
    actorRole: "VP Customer Success",
    action: "Priority Updated",
    resource: "Priority",
    resourceId: "PRI-002",
    context: "Diana Reyes updated priority PRI-002 status from 'open' to 'in_progress'. Added comment: 'Activated overflow staffing protocol — contractor pool onboarding started.'",
    outcome: "success",
    ipAddress: "192.168.1.88",
    tags: ["priority", "status_change", "manual"],
  },
  {
    id: "AUD-005",
    timestamp: hoursAgo(4),
    actor: "Lyte Alert Engine",
    actorRole: "System",
    action: "Alert Fired",
    resource: "Alert",
    resourceId: "ALT-003",
    context: "Forecast variance anomaly alert fired for the 3rd time in the current period. Alert configured with escalating notification — PagerDuty incident created for revenue on-call.",
    outcome: "success",
    ipAddress: "10.0.1.45",
    tags: ["alert", "automated", "pagerduty"],
  },
  {
    id: "AUD-006",
    timestamp: hoursAgo(6),
    actor: "Tom Farrell",
    actorRole: "Finance Operations Manager",
    action: "Workflow Completed",
    resource: "Workflow Run",
    resourceId: "RUN-003",
    context: "Tom Farrell marked Billing Reconciliation Audit workflow as complete. 23 accounts flagged, $340K gap identified and documented. Jira tickets created for billing ops remediation.",
    outcome: "success",
    ipAddress: "192.168.1.145",
    tags: ["workflow", "completion", "finance"],
  },
  {
    id: "AUD-007",
    timestamp: hoursAgo(8),
    actor: "Kenji Watanabe",
    actorRole: "Deal Desk Lead",
    action: "Alert Silenced",
    resource: "Alert",
    resourceId: "ALT-010",
    context: "Alert ALT-010 (SOW Signature Latency) silenced for 72 hours by Kenji Watanabe. Reason: 'Client legal teams at 3 accounts scheduled reviews — expect signature within 3 business days.'",
    outcome: "success",
    ipAddress: "192.168.1.67",
    tags: ["alert", "silenced", "manual"],
  },
  {
    id: "AUD-008",
    timestamp: hoursAgo(12),
    actor: "Priya Nair",
    actorRole: "VP Mid-Market Sales",
    action: "Recommendation Reviewed",
    resource: "Recommendation",
    resourceId: "REC-004",
    context: "Priya Nair reviewed Q1 pull-forward recommendation. Added note: 'Reaching out to Hartwell Group and Meridian today — confirming budget availability.' Status set to in_progress.",
    outcome: "success",
    ipAddress: "192.168.1.201",
    tags: ["recommendation", "manual", "revenue"],
  },
  {
    id: "AUD-009",
    timestamp: hoursAgo(18),
    actor: "Lyte Signal Engine",
    actorRole: "System",
    action: "Signal Auto-Resolved",
    resource: "Signal",
    resourceId: "DS-008",
    context: "Signal DS-008 auto-resolved following billing system patch deployment. Usage tier rules confirmed propagated to all 23 affected accounts. Reconciliation workflow closed.",
    outcome: "success",
    ipAddress: "10.0.1.45",
    tags: ["signal", "automated", "resolved"],
  },
  {
    id: "AUD-010",
    timestamp: daysAgo(1),
    actor: "Rosa Kim",
    actorRole: "Revenue Operations Analyst",
    action: "Exception Created",
    resource: "Exception",
    resourceId: "EXC-003",
    context: "Rosa Kim manually created data quality exception for 116 stale pipeline opportunities. Tagged as pipeline_hygiene violation. Assigned to sales ops team for remediation by Friday.",
    outcome: "success",
    ipAddress: "192.168.1.33",
    tags: ["exception", "pipeline", "manual"],
  },
  {
    id: "AUD-011",
    timestamp: daysAgo(1),
    actor: "Admin System",
    actorRole: "System",
    action: "User Access Reviewed",
    resource: "User",
    resourceId: "USR-044",
    context: "Quarterly access review completed for 44 active Lyte users. 3 users flagged for role downgrade (last login >90 days). Access review report generated and sent to IT Security.",
    outcome: "success",
    ipAddress: "10.0.1.10",
    tags: ["compliance", "access_review", "automated"],
  },
  {
    id: "AUD-012",
    timestamp: daysAgo(2),
    actor: "Sarah Donovan",
    actorRole: "Enterprise Sales Director",
    action: "Priority Escalated",
    resource: "Priority",
    resourceId: "PRI-004",
    context: "Sarah Donovan escalated renewal assignment priority from 'today' to 'immediate'. Comment: 'Nexus Group health score dropped to 42 overnight — immediate AE assignment critical.'",
    outcome: "success",
    ipAddress: "192.168.1.98",
    tags: ["priority", "escalation", "manual", "renewals"],
  },
  {
    id: "AUD-013",
    timestamp: daysAgo(2),
    actor: "Lyte Compliance Engine",
    actorRole: "System",
    action: "Compliance Check Failed",
    resource: "Readiness Item",
    resourceId: "RDY-007",
    context: "Quarterly SOC 2 evidence collection check failed — 3 of 12 required control evidence files not updated within 90-day requirement. Exception flagged for compliance team.",
    outcome: "failure",
    ipAddress: "10.0.1.45",
    tags: ["compliance", "soc2", "automated", "failure"],
  },
  {
    id: "AUD-014",
    timestamp: daysAgo(3),
    actor: "James Okafor",
    actorRole: "SE Team Lead",
    action: "Signal Reviewed",
    resource: "Signal",
    resourceId: "DS-005",
    context: "James Okafor reviewed SE queue signal. Added context: 'Two ICP deals expedited manually. FIFO queue reorder not yet approved by leadership.' Status remains acknowledged.",
    outcome: "success",
    ipAddress: "192.168.1.75",
    tags: ["signal", "manual", "review"],
  },
];

export const demoExceptions: DemoException[] = [
  {
    id: "EXC-001",
    title: "Enterprise approval SLA breach — 8 deals exceeding 10-day threshold",
    category: "sla_breach",
    severity: "critical",
    status: "escalated",
    detectedAt: daysAgo(5),
    owner: "Marcus Webb",
    affectedSystem: "CRM Workflow Engine",
    description: "Eight enterprise deals have breached the 10-business-day approval SLA. Oldest deal is at 18 days with no legal reviewer activity for 7 days. CFO approval track has been requested but not yet activated.",
    valueAtRisk: 2100000,
    slaBreachAt: daysAgo(5),
  },
  {
    id: "EXC-002",
    title: "Implementation handoff SLA violated — 14 projects, 0 assignees",
    category: "sla_breach",
    severity: "critical",
    status: "escalated",
    detectedAt: daysAgo(6),
    owner: "Diana Reyes",
    affectedSystem: "Project Management System",
    description: "Post-sale implementation handoff SLA of 5 business days has been violated for all 14 projects currently in the queue. No implementation engineers or CSMs are assigned. Root cause: 2 IMs on simultaneous unplanned leave without coverage.",
    valueAtRisk: 890000,
    slaBreachAt: daysAgo(6),
  },
  {
    id: "EXC-003",
    title: "Pipeline hygiene violation — 116 opportunities stale for 14+ days",
    category: "data_quality",
    severity: "high",
    status: "acknowledged",
    detectedAt: daysAgo(7),
    owner: "Rosa Kim",
    affectedSystem: "CRM Activity Tracker",
    description: "116 active pipeline opportunities have no logged activity (call, email, meeting) or next step date for 14 or more days. This violates the revenue operations pipeline hygiene policy which requires activity logged every 7 days for active opportunities.",
    valueAtRisk: 840000,
  },
  {
    id: "EXC-004",
    title: "Unowned renewal accounts — territory reassignment process failed",
    category: "ownership_gap",
    severity: "high",
    status: "open",
    detectedAt: daysAgo(4),
    owner: null,
    affectedSystem: "CRM Ownership Engine",
    description: "7 enterprise accounts with renewal dates in 60 days have no assigned AE or CSM. Two AE departures in the prior 30 days did not trigger the territory reassignment protocol because the HR and CRM systems are not integrated.",
    valueAtRisk: 2300000,
  },
  {
    id: "EXC-005",
    title: "SOC 2 evidence collection 25% incomplete — compliance deadline at risk",
    category: "compliance",
    severity: "high",
    status: "open",
    detectedAt: daysAgo(2),
    owner: null,
    affectedSystem: "Compliance Platform",
    description: "3 of 12 required SOC 2 control evidence files have not been updated within the 90-day compliance window. Annual audit is scheduled in 34 days. Non-compliance would jeopardize enterprise customer contractual commitments.",
    valueAtRisk: 0,
    slaBreachAt: daysFromNow(32),
  },
  {
    id: "EXC-006",
    title: "SE team at 94% capacity — queue growth unsustainable",
    category: "capacity",
    severity: "high",
    status: "acknowledged",
    detectedAt: daysAgo(3),
    owner: "James Okafor",
    affectedSystem: "SE Queue Manager",
    description: "Solutions Engineering team is operating at 94% of stated capacity while the incoming queue is growing at 47% above the 30-day average. Without capacity expansion or demand throttling, wait times will continue to increase and win rates on high-value deals will decline.",
    valueAtRisk: 1400000,
  },
  {
    id: "EXC-007",
    title: "Billing rule migration failure — 23 accounts under-billed $340K",
    category: "process_violation",
    severity: "medium",
    status: "acknowledged",
    detectedAt: daysAgo(8),
    owner: "Tom Farrell",
    affectedSystem: "Billing System",
    description: "Usage-based billing tier rules were not correctly propagated to 23 accounts migrated to the new billing system before the platform cutover. Accounts have been consuming above their contracted tier limits for 2+ billing cycles without overage charges.",
    valueAtRisk: 340000,
    resolution: "Billing ops team is applying corrections. CSM outreach planned before corrective invoicing.",
  },
  {
    id: "EXC-008",
    title: "QBR process adherence below 70% threshold",
    category: "process_violation",
    severity: "medium",
    status: "acknowledged",
    detectedAt: daysAgo(5),
    owner: "Maria Vasquez",
    affectedSystem: "CS Platform",
    description: "Enterprise QBR completion rate has fallen to 61%, below the 70% minimum defined in the CS operations policy. 29 of 74 enterprise accounts have not received a QBR this quarter with 22 business days remaining.",
    valueAtRisk: 820000,
  },
];

export const demoReadinessItems: DemoReadinessItem[] = [
  {
    id: "RDY-001",
    category: "Approval Governance",
    title: "Approval SLA policy documented and distributed",
    description: "All approval chains must have documented SLAs, owner accountability, and escalation paths defined and communicated to stakeholders.",
    status: "in_progress",
    score: 60,
    owner: "Marcus Webb",
    dueBy: "Apr 15, 2025",
    lastReviewedAt: daysAgo(3),
  },
  {
    id: "RDY-002",
    category: "Approval Governance",
    title: "CFO approval delegation matrix in place",
    description: "Defined backup approvers and delegation rules when primary approvers are unavailable for >24 hours.",
    status: "blocked",
    score: 20,
    owner: "CFO Office",
    dueBy: "Apr 10, 2025",
    blockedReason: "CFO office has not responded to 2 requests for delegation matrix review.",
  },
  {
    id: "RDY-003",
    category: "Implementation Operations",
    title: "Overflow staffing protocol active",
    description: "A documented and tested protocol for activating contractor or partner implementation capacity when internal bench is exhausted.",
    status: "in_progress",
    score: 55,
    owner: "Diana Reyes",
    dueBy: "Apr 8, 2025",
  },
  {
    id: "RDY-004",
    category: "Implementation Operations",
    title: "Coverage assignment for leave periods",
    description: "All senior implementation managers must have a designated backup and handoff procedure for planned and unplanned absences.",
    status: "blocked",
    score: 15,
    owner: "Delivery Operations",
    dueBy: "Apr 5, 2025",
    blockedReason: "HR policy update required before coverage assignments can be formalized.",
  },
  {
    id: "RDY-005",
    category: "Revenue Operations",
    title: "CRM pipeline hygiene enforcement rules configured",
    description: "Automated rules in CRM that move stale opportunities to appropriate stages and alert reps when activity lapses.",
    status: "pending",
    score: 30,
    owner: "Rosa Kim",
    dueBy: "Apr 18, 2025",
  },
  {
    id: "RDY-006",
    category: "Revenue Operations",
    title: "Forecast accuracy monitoring dashboard live",
    description: "Real-time forecast variance monitoring with automated alerts when commit-to-best-case reclassification rate exceeds 2x baseline.",
    status: "complete",
    score: 100,
    owner: "RevOps",
    dueBy: "Apr 1, 2025",
    lastReviewedAt: daysAgo(7),
  },
  {
    id: "RDY-007",
    category: "Compliance",
    title: "SOC 2 evidence collection complete and current",
    description: "All 12 control evidence files updated within the 90-day compliance window prior to scheduled annual audit.",
    status: "blocked",
    score: 75,
    owner: "Compliance Team",
    dueBy: "Apr 12, 2025",
    complianceRef: "SOC 2 CC6.1, CC6.3",
    blockedReason: "3 control owners have not submitted updated evidence. Follow-up in progress.",
    lastReviewedAt: daysAgo(2),
  },
  {
    id: "RDY-008",
    category: "Compliance",
    title: "Quarterly access review completed",
    description: "Review of all user access levels in Lyte, CRM, and financial systems. Remove or downgrade inactive or over-provisioned accounts.",
    status: "complete",
    score: 100,
    owner: "IT Security",
    dueBy: "Apr 1, 2025",
    complianceRef: "SOC 2 CC6.2",
    lastReviewedAt: daysAgo(1),
  },
  {
    id: "RDY-009",
    category: "Customer Success",
    title: "QBR coverage >80% for enterprise accounts",
    description: "At least 80% of enterprise accounts must complete a QBR in each quarter, with documentation uploaded to CS platform.",
    status: "in_progress",
    score: 61,
    owner: "Maria Vasquez",
    dueBy: "Apr 30, 2025",
    lastReviewedAt: daysAgo(1),
  },
  {
    id: "RDY-010",
    category: "Customer Success",
    title: "All enterprise accounts have named CSM and AE",
    description: "Zero enterprise accounts may be unowned at any point. Automated ownership assignment must trigger within 24 hours of any gap detected.",
    status: "blocked",
    score: 25,
    owner: "Enterprise CS / Sales",
    dueBy: "Apr 7, 2025",
    blockedReason: "7 accounts currently unowned pending AE assignment. HR/CRM integration not yet in place.",
  },
  {
    id: "RDY-011",
    category: "Data Quality",
    title: "CRM data completeness score >90%",
    description: "All active opportunities must have required fields populated: owner, next step, close date, and stage. Completeness monitored weekly.",
    status: "in_progress",
    score: 72,
    owner: "Revenue Operations",
    dueBy: "Apr 15, 2025",
    lastReviewedAt: daysAgo(4),
  },
  {
    id: "RDY-012",
    category: "Data Quality",
    title: "Billing system usage tier rules validated post-migration",
    description: "All accounts migrated in the last 6 months must have their billing tier rules independently verified against usage telemetry.",
    status: "in_progress",
    score: 80,
    owner: "Tom Farrell",
    dueBy: "Apr 10, 2025",
    lastReviewedAt: hoursAgo(18),
  },
];

export const demoIntegrations: DemoIntegration[] = [
  {
    id: "INT-001",
    name: "Salesforce CRM",
    type: "crm",
    status: "connected",
    lastSyncAt: minsAgo(5),
    syncFrequency: "Every 5 minutes",
    recordsIngested: 284621,
    errorsLast24h: 0,
    owner: "RevOps",
    description: "Primary CRM integration for pipeline, opportunities, accounts, contacts, and activity logs. Bidirectional sync with Lyte signal engine.",
    signalSources: 6,
  },
  {
    id: "INT-002",
    name: "Slack",
    type: "communication",
    status: "connected",
    lastSyncAt: minsAgo(1),
    syncFrequency: "Real-time webhook",
    recordsIngested: 48293,
    errorsLast24h: 0,
    owner: "IT",
    description: "Notification delivery for signals, alerts, and priority assignments. Bidirectional command interface for signal acknowledgment.",
    signalSources: 2,
  },
  {
    id: "INT-003",
    name: "Jira",
    type: "ticketing",
    status: "connected",
    lastSyncAt: minsAgo(12),
    syncFrequency: "Every 10 minutes",
    recordsIngested: 18432,
    errorsLast24h: 2,
    owner: "Engineering Ops",
    description: "Workflow ticket creation and status sync. Exceptions and action items in Lyte create corresponding Jira tickets. Inbound status updates close Lyte items.",
    signalSources: 1,
  },
  {
    id: "INT-004",
    name: "Gainsight (CS Platform)",
    type: "cs_platform",
    status: "connected",
    lastSyncAt: minsAgo(20),
    syncFrequency: "Every 15 minutes",
    recordsIngested: 8924,
    errorsLast24h: 0,
    owner: "CS Ops",
    description: "Customer health scores, QBR tracking, and CS activity data. Health score drops trigger Lyte signals automatically.",
    signalSources: 2,
  },
  {
    id: "INT-005",
    name: "PagerDuty",
    type: "monitoring",
    status: "connected",
    lastSyncAt: minsAgo(2),
    syncFrequency: "Real-time webhook",
    recordsIngested: 1248,
    errorsLast24h: 0,
    owner: "IT Operations",
    description: "Incident routing for critical Lyte alerts. PagerDuty incidents created automatically for severity: critical alerts with appropriate escalation paths.",
    signalSources: 0,
  },
  {
    id: "INT-006",
    name: "Workday HCM",
    type: "hr",
    status: "degraded",
    lastSyncAt: hoursAgo(3),
    syncFrequency: "Every 2 hours",
    recordsIngested: 12847,
    errorsLast24h: 14,
    owner: "IT / HR",
    description: "Employee status, department structure, and leave management. HR offboarding events should trigger CRM ownership reassignment. Currently experiencing API rate limit errors.",
    signalSources: 1,
  },
  {
    id: "INT-007",
    name: "Clari (Forecast Intelligence)",
    type: "analytics",
    status: "connected",
    lastSyncAt: minsAgo(8),
    syncFrequency: "Every 30 minutes",
    recordsIngested: 94283,
    errorsLast24h: 1,
    owner: "RevOps",
    description: "Forecast intelligence, deal progression analytics, and pipeline coverage metrics. Forecast variance signals sourced directly from Clari's anomaly engine.",
    signalSources: 3,
  },
  {
    id: "INT-008",
    name: "Stripe (Billing)",
    type: "billing",
    status: "connected",
    lastSyncAt: minsAgo(15),
    syncFrequency: "Every 15 minutes",
    recordsIngested: 38421,
    errorsLast24h: 0,
    owner: "Finance Ops",
    description: "Usage telemetry and billing data for revenue leakage detection. Monthly reconciliation runs automatically and feeds into Lyte exception queue.",
    signalSources: 1,
  },
  {
    id: "INT-009",
    name: "DocuSign",
    type: "ticketing",
    status: "connected",
    lastSyncAt: minsAgo(30),
    syncFrequency: "Every 15 minutes",
    recordsIngested: 4821,
    errorsLast24h: 0,
    owner: "Legal",
    description: "Contract signature tracking. SOW and approval document status feeds into workflow signals. Unsigned document age triggers Lyte alerts.",
    signalSources: 1,
  },
  {
    id: "INT-010",
    name: "Okta (Identity)",
    type: "identity",
    status: "connected",
    lastSyncAt: minsAgo(60),
    syncFrequency: "Every 60 minutes",
    recordsIngested: 2841,
    errorsLast24h: 0,
    owner: "IT Security",
    description: "User identity and access management. Lyte role assignments synchronized with Okta groups. Access review data sourced from Okta audit logs.",
    signalSources: 0,
  },
  {
    id: "INT-011",
    name: "Snowflake Data Warehouse",
    type: "analytics",
    status: "connected",
    lastSyncAt: hoursAgo(1),
    syncFrequency: "Hourly",
    recordsIngested: 1284921,
    errorsLast24h: 0,
    owner: "Data Engineering",
    description: "Central data warehouse for historical signal analysis, trend modeling, and forecast baseline computation. Powers Lyte's anomaly detection ML models.",
    signalSources: 0,
  },
  {
    id: "INT-012",
    name: "SAP ERP",
    type: "erp",
    status: "disconnected",
    lastSyncAt: daysAgo(3),
    syncFrequency: "Daily (scheduled)",
    recordsIngested: 0,
    errorsLast24h: 0,
    owner: "IT / Finance",
    description: "Financial data integration for revenue recognition and budget vs. actuals. Integration under reconfiguration following SAP version upgrade. Expected reconnection: Apr 10.",
    signalSources: 0,
  },
];

export const demoReports: DemoReport[] = [
  {
    id: "RPT-001",
    name: "Q1 Executive Business Review",
    type: "executive_summary",
    generatedAt: hoursAgo(2),
    generatedBy: "Lyte Auto-Report Engine",
    status: "complete",
    recipientCount: 8,
    format: "pdf",
    schedule: "Weekly — Mondays 6 AM",
    fileSizeKb: 842,
    summary: "Executive summary of all active signals, value at risk ($17.6M), top 5 priorities, and Q1 forecast variance ($3.8M mid-market, $1.8M enterprise coverage). Includes role-based views for CEO, CFO, COO.",
  },
  {
    id: "RPT-002",
    name: "Daily Signal Digest",
    type: "signal_digest",
    generatedAt: hoursAgo(6),
    generatedBy: "Lyte Auto-Report Engine",
    status: "complete",
    recipientCount: 24,
    format: "html",
    schedule: "Daily — 7 AM",
    fileSizeKb: 124,
    summary: "Daily digest of all new and active signals with severity distribution, owner assignments, and recommended actions. Segmented by business function.",
  },
  {
    id: "RPT-003",
    name: "Workflow Health Report",
    type: "workflow_health",
    generatedAt: daysAgo(1),
    generatedBy: "Lyte Auto-Report Engine",
    status: "complete",
    recipientCount: 12,
    format: "pdf",
    schedule: "Weekly — Fridays 5 PM",
    fileSizeKb: 634,
    summary: "Status of all active workflows: 4 stalled, 3 running, 1 completed. Average stall duration: 8.7 business days. Total value at risk from stalled workflows: $6.4M.",
  },
  {
    id: "RPT-004",
    name: "April Audit Trail Export",
    type: "audit_log",
    generatedAt: hoursAgo(18),
    generatedBy: "Rosa Kim",
    status: "complete",
    recipientCount: 3,
    format: "csv",
    schedule: "Ad hoc",
    fileSizeKb: 289,
    summary: "Full audit event log for April 1–3, 2025. 847 events across 44 active users. Generated for compliance review by IT Security.",
  },
  {
    id: "RPT-005",
    name: "Operational Readiness Assessment — Q1 Close",
    type: "readiness_assessment",
    generatedAt: daysAgo(2),
    generatedBy: "Lyte Auto-Report Engine",
    status: "complete",
    recipientCount: 6,
    format: "pdf",
    schedule: "Monthly — 1st of month",
    fileSizeKb: 512,
    summary: "Readiness score: 58/100. 3 critical items blocked, 5 in progress. SOC 2 evidence gap is primary risk. Renewal ownership gap second. Estimated readiness to 80% by April 15 if blockers resolved.",
  },
  {
    id: "RPT-006",
    name: "Forecast Variance Report — Week of Apr 3",
    type: "forecast_variance",
    generatedAt: minsAgo(45),
    generatedBy: "Lyte Auto-Report Engine",
    status: "complete",
    recipientCount: 5,
    format: "pdf",
    schedule: "Weekly — Thursdays 8 AM",
    fileSizeKb: 394,
    summary: "Mid-market commit: $8.6M (down $3.8M from prior report). Enterprise coverage: 0.94x (below 1.0x for first time in 5 quarters). 3 acceleration opportunities identified.",
  },
  {
    id: "RPT-007",
    name: "Weekly Signal Digest — Apr 7",
    type: "signal_digest",
    generatedAt: minsAgo(5),
    generatedBy: "Lyte Auto-Report Engine",
    status: "generating",
    recipientCount: 24,
    format: "html",
    schedule: "Weekly — Mondays 6 AM",
    fileSizeKb: 0,
    summary: "Generating...",
  },
];

export const demoRoleSummaries = {
  executive: {
    title: "Executive View",
    headline: "$17.6M at risk across 3 critical signals. Q1 forecast gap: $2.6M. Immediate CFO action required on 3 enterprise deals.",
    kpis: [
      { label: "Total Value at Risk", value: "$17.6M", trend: "+12.4%", severity: "critical" },
      { label: "Q1 Forecast Gap", value: "$2.6M", trend: "-23%", severity: "critical" },
      { label: "Critical Signals", value: "3", trend: "+1", severity: "critical" },
      { label: "Approval Latency", value: "14.2d", trend: "+21%", severity: "critical" },
    ],
    priorities: ["PRI-001", "PRI-003"],
  },
  operator: {
    title: "Operations View",
    headline: "14 implementation projects breaching SLA. 8 unassigned workflows. 116 stale pipeline records need cleanup.",
    kpis: [
      { label: "SLA Breaches", value: "14", trend: "+67%", severity: "critical" },
      { label: "Stalled Workflows", value: "4", trend: "+2", severity: "high" },
      { label: "Unassigned Items", value: "21", trend: "+16%", severity: "high" },
      { label: "Queue Depth", value: "31", trend: "+47%", severity: "high" },
    ],
    priorities: ["PRI-002", "PRI-005", "PRI-006"],
  },
  manager: {
    title: "Manager View",
    headline: "7 enterprise renewals at risk, 4 with early churn signals. Team capacity at 94%. Assign AE/CSM pairs today.",
    kpis: [
      { label: "Unowned Renewals", value: "7", trend: "+7", severity: "high" },
      { label: "Team Capacity", value: "94%", trend: "+8%", severity: "high" },
      { label: "Churn Risk ARR", value: "$2.3M", trend: "+$2.3M", severity: "high" },
      { label: "QBR Coverage", value: "61%", trend: "-9%", severity: "medium" },
    ],
    priorities: ["PRI-004", "PRI-008"],
  },
  compliance: {
    title: "Audit / Compliance View",
    headline: "SOC 2 evidence gap: 3 controls unresolved. Audit in 34 days. 847 audit events this period. Access review complete.",
    kpis: [
      { label: "Open Compliance Items", value: "3", trend: "+3", severity: "high" },
      { label: "Days to Audit", value: "34", trend: "-1", severity: "medium" },
      { label: "Audit Events (Period)", value: "847", trend: "+12%", severity: "low" },
      { label: "Access Review", value: "Complete", trend: "0", severity: "stable" },
    ],
    priorities: ["PRI-007"],
  },
};

export function getDemoSeed() {
  return {
    signals: demoSignals,
    alerts: demoAlerts,
    priorities: demoPriorities,
    workflows: demoWorkflows,
    runs: demoRuns,
    recommendations: demoRecommendations,
    auditEvents: demoAuditEvents,
    exceptions: demoExceptions,
    readinessItems: demoReadinessItems,
    integrations: demoIntegrations,
    reports: demoReports,
    roleSummaries: demoRoleSummaries,
  };
}
