name: DCO
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: read
jobs:
  dco:
    uses: szl-holdings/.github/.github/workflows/reusable-dco.yml@9095ae9ef3bac93a2a6faf6c7120186177b3a9ec # main
    secrets: inherit
