name: Doctrine
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    uses: szl-holdings/.github/.github/workflows/doctrine-check.yml@5b0d38fadadc073812bfc6175a1e823cd529939f # main
