import type { DomainProfile } from "../types.js";

export const aegisSecurityIncident: DomainProfile = {
  profileId: "aegis_security_incident",
  version: "1.0.0",
  domain: "cyber",
  displayName: "Aegis — Security Incident Intelligence",
  description:
    "Retrieval profile for the Aegis Cyber Resilience Command platform. Optimized for threat intelligence retrieval, CVE lookup, incident correlation, MITRE ATT&CK technique search, and vulnerability assessment. Priority entity classes include CVE identifiers, incident IDs, hostname patterns, endpoint IDs, and threat-actor names.",
  priorityTerms: [
    "CVE",
    "vulnerability",
    "incident",
    "threat",
    "actor",
    "malware",
    "ransomware",
    "phishing",
    "intrusion",
    "lateral movement",
    "C2",
    "exfiltration",
    "MITRE",
    "ATT&CK",
    "IOC",
    "indicator",
    "TTP",
    "CVSS",
    "patch",
    "exploit",
    "zero-day",
    "endpoint",
    "hostname",
    "IP address",
  ],
  boostTerms: [
    { term: "CVE ID", pattern: "cve-\\d{4}-\\d{4,}", multiplier: 2.0, fieldHint: "cveId" },
    { term: "incident ID", pattern: "inc[-_]\\d{4,}", multiplier: 1.8, fieldHint: "incidentId" },
    { term: "MITRE technique", pattern: "t\\d{4}(?:\\.\\d{3})?", multiplier: 1.7, fieldHint: "mitreId" },
    { term: "hostname", pattern: "[a-z0-9\\-]+\\.[a-z]{2,}", multiplier: 1.5, fieldHint: "hostname" },
    { term: "endpoint ID", pattern: "ep[-_]\\d{4,}|endpoint[-_]\\w+", multiplier: 1.6, fieldHint: "endpointId" },
  ],
  exactMatchFieldClasses: [
    {
      classId: "cve-id",
      description: "Common Vulnerabilities and Exposures identifier",
      examplePatterns: ["CVE-2024-12345", "CVE-2023-44487"],
      metadataField: "cveId",
      boostMultiplier: 2.0,
    },
    {
      classId: "incident-id",
      description: "Security incident tracking identifier",
      examplePatterns: ["INC-20240101", "INC_4521"],
      metadataField: "incidentId",
      boostMultiplier: 1.9,
    },
    {
      classId: "mitre-technique",
      description: "MITRE ATT&CK technique or sub-technique identifier",
      examplePatterns: ["T1566", "T1566.001"],
      metadataField: "mitreId",
      boostMultiplier: 1.7,
    },
    {
      classId: "hostname",
      description: "Network hostname or FQDN",
      examplePatterns: ["server01.corp.example.com"],
      metadataField: "hostname",
      boostMultiplier: 1.5,
    },
    {
      classId: "endpoint-id",
      description: "Endpoint management system device identifier",
      examplePatterns: ["EP-00441", "ENDPOINT-LAPTOP-007"],
      metadataField: "endpointId",
      boostMultiplier: 1.6,
    },
  ],
  defaultMetadataFilters: {},
  rerankEnabled: true,
  maxCandidates: 200,
  maxResults: 20,
  denseWeight: 0.7,
  keywordWeight: 0.3,
  truncationPolicy: { strategy: "truncate", maxTokens: 512, warnAtTokens: 480 },
  promptContextPrefix:
    "You are reviewing cybersecurity intelligence. The following evidence contains threat indicators, vulnerability disclosures, and incident records:",
  retentionDays: 365,
  provenanceRequired: true,
  metadata: { vertical: "aegis" },
};
