import type { DomainProfile } from "../types.js";

export const carlotaPrivateAdvisory: DomainProfile = {
  profileId: "carlota_private_advisory",
  version: "1.0.0",
  domain: "advisory",
  displayName: "Carlota Jo — Private Advisory Intelligence",
  description:
    "Retrieval profile for the Carlota Jo Consulting advisory platform. Optimized for private advisory document retrieval, engagement record search, client correspondence analysis, and strategic briefing lookup. Priority entity classes include engagement IDs, vendor identifiers, residency reference numbers, and compliance control designators relevant to advisory workflows.",
  priorityTerms: [
    "engagement",
    "advisory",
    "client",
    "recommendation",
    "briefing",
    "strategic",
    "deliverable",
    "scope",
    "workstream",
    "vendor",
    "due diligence",
    "assessment",
    "roadmap",
    "milestone",
    "stakeholder",
    "governance",
    "risk",
    "compliance",
    "reporting",
  ],
  boostTerms: [
    { term: "engagement ID", pattern: "eng[-_]\\w+|engagement[-_]\\w+", multiplier: 1.8, fieldHint: "engagementId" },
    { term: "vendor ID", pattern: "vendor[-_]\\w+|vend[-_]\\d+", multiplier: 1.6, fieldHint: "vendorId" },
    { term: "residence ID", pattern: "res[-_]\\d{4,}", multiplier: 1.5, fieldHint: "residenceId" },
    { term: "control ID", pattern: "ctrl[-_]\\w+|control\\s+\\w+", multiplier: 1.6, fieldHint: "controlId" },
    { term: "deliverable ID", pattern: "dlv[-_]\\w+|deliverable[-_]\\w+", multiplier: 1.5, fieldHint: "deliverableId" },
  ],
  exactMatchFieldClasses: [
    {
      classId: "engagement-id",
      description: "Advisory engagement or project tracking identifier",
      examplePatterns: ["ENG-2024-001", "ENGAGEMENT-Q1-2024"],
      metadataField: "engagementId",
      boostMultiplier: 1.8,
    },
    {
      classId: "vendor-id",
      description: "Vendor or supplier system identifier",
      examplePatterns: ["VEND-0042", "VENDOR-CORP-007"],
      metadataField: "vendorId",
      boostMultiplier: 1.6,
    },
    {
      classId: "residence-id",
      description: "Residency or facility reference identifier",
      examplePatterns: ["RES-10041"],
      metadataField: "residenceId",
      boostMultiplier: 1.5,
    },
    {
      classId: "compliance-control-id",
      description: "Compliance control identifier used in advisory engagements",
      examplePatterns: ["CTRL-ACC-001", "CONTROL-GOV-044"],
      metadataField: "controlId",
      boostMultiplier: 1.6,
    },
    {
      classId: "deliverable-id",
      description: "Engagement deliverable or work product identifier",
      examplePatterns: ["DLV-2024-0012"],
      metadataField: "deliverableId",
      boostMultiplier: 1.5,
    },
  ],
  defaultMetadataFilters: {},
  rerankEnabled: false,
  maxCandidates: 80,
  maxResults: 10,
  denseWeight: 0.65,
  keywordWeight: 0.35,
  truncationPolicy: { strategy: "truncate", maxTokens: 512 },
  promptContextPrefix:
    "You are reviewing private advisory intelligence. The following evidence contains engagement documents, client briefs, and strategic recommendations:",
  retentionDays: 1825,
  provenanceRequired: false,
  metadata: { vertical: "carlota-jo" },
};
