import type { DomainProfile } from "../types.js";

export const lyteGovernanceOps: DomainProfile = {
  profileId: "lyte_governance_ops",
  version: "1.0.0",
  domain: "compliance",
  displayName: "Lyte — Governance Operations",
  description:
    "Retrieval profile for the Lyte Decision Intelligence platform. Optimized for regulatory compliance retrieval, policy term search, control framework mapping, and audit evidence lookup. Priority entity classes include regulation codes, compliance control identifiers, framework designations (NIST, ISO 27001, SOC 2, PCI-DSS, GDPR), and sanction entities.",
  priorityTerms: [
    "compliance",
    "regulation",
    "control",
    "framework",
    "policy",
    "audit",
    "risk",
    "governance",
    "NIST",
    "ISO 27001",
    "SOC 2",
    "PCI-DSS",
    "GDPR",
    "CCPA",
    "HIPAA",
    "control objective",
    "evidence",
    "finding",
    "remediation",
    "attestation",
  ],
  boostTerms: [
    { term: "NIST", pattern: "nist\\s+(?:sp\\s+)?\\d{3}(?:-\\d+)?", multiplier: 1.7, fieldHint: "regulationCode" },
    { term: "ISO 27001", pattern: "iso\\s*27001(?:\\s+clause\\s+\\d+)?", multiplier: 1.7, fieldHint: "regulationCode" },
    { term: "SOC 2", pattern: "soc\\s*2(?:\\s+type\\s+[12])?", multiplier: 1.6, fieldHint: "regulationCode" },
    { term: "control ID", pattern: "ctrl[-_]\\w+|control\\s+id\\s+\\w+", multiplier: 1.8, fieldHint: "controlId" },
    { term: "finding", pattern: "finding\\s+(?:id\\s+)?\\w+", multiplier: 1.5, fieldHint: "findingId" },
  ],
  exactMatchFieldClasses: [
    {
      classId: "regulation-code",
      description: "Regulatory framework or standard identifier",
      examplePatterns: ["NIST SP 800-53", "ISO 27001", "SOC 2 Type II"],
      metadataField: "regulationCode",
      boostMultiplier: 1.7,
    },
    {
      classId: "control-id",
      description: "Compliance control unique identifier",
      examplePatterns: ["AC-2", "CC6.1", "PCI Req 8.2"],
      metadataField: "controlId",
      boostMultiplier: 1.8,
    },
    {
      classId: "finding-id",
      description: "Audit finding or gap identifier",
      examplePatterns: ["FINDING-2024-001"],
      metadataField: "findingId",
      boostMultiplier: 1.6,
    },
    {
      classId: "sanctions-name",
      description: "Sanctions list entity name",
      examplePatterns: ["OFAC SDN entity"],
      metadataField: "sdnEntity",
      boostMultiplier: 2.0,
    },
  ],
  defaultMetadataFilters: {},
  rerankEnabled: true,
  maxCandidates: 100,
  maxResults: 12,
  denseWeight: 0.6,
  keywordWeight: 0.4,
  truncationPolicy: { strategy: "truncate", maxTokens: 512, warnAtTokens: 480 },
  promptContextPrefix:
    "You are reviewing governance and compliance evidence. The following sources contain regulatory guidance, control documentation, and audit findings:",
  retentionDays: 730,
  provenanceRequired: true,
  metadata: { vertical: "lyte" },
};
