import type { DomainProfile } from "../types.js";

export const prismLegalMatter: DomainProfile = {
  profileId: "prism_legal_matter",
  version: "1.0.0",
  domain: "legal",
  displayName: "PRISM Counsel — Legal Matter Intelligence",
  description:
    "Retrieval profile for the PRISM Counsel Legal Matter Command platform. Optimized for legal document retrieval, docket search, case law lookup, contract analysis, and regulatory filing retrieval. Priority entity classes include docket numbers, case numbers, matter IDs, statute citations, and contract reference identifiers.",
  priorityTerms: [
    "matter",
    "case",
    "docket",
    "court",
    "filing",
    "motion",
    "pleading",
    "brief",
    "opinion",
    "statute",
    "regulation",
    "contract",
    "clause",
    "exhibit",
    "deposition",
    "discovery",
    "jurisdiction",
    "defendant",
    "plaintiff",
    "counsel",
    "precedent",
    "holding",
    "citation",
  ],
  boostTerms: [
    { term: "docket ID", pattern: "\\d{1,2}[-:]\\d{2,5}[-:][a-z]{2,4}", multiplier: 1.9, fieldHint: "docketId" },
    { term: "case number", pattern: "case\\s*(?:no\\.?|number)?\\s*[a-z0-9\\-]+", multiplier: 1.8, fieldHint: "caseNumber" },
    { term: "matter ID", pattern: "matter[-_]\\w+|mtr[-_]\\w+", multiplier: 1.8, fieldHint: "matterId" },
    { term: "statute citation", pattern: "\\d+\\s+u\\.s\\.c\\.\\s+§\\s*\\d+|\\d+\\s+cfr\\s+§\\s*\\d+", multiplier: 1.7, fieldHint: "statuteCitation" },
    { term: "contract ID", pattern: "contract\\s*(?:id|#)?\\s*[a-z0-9\\-]+", multiplier: 1.6, fieldHint: "contractId" },
  ],
  exactMatchFieldClasses: [
    {
      classId: "docket-id",
      description: "Federal or state court docket number",
      examplePatterns: ["24-1234-CV", "3:24-cv-00123"],
      metadataField: "docketId",
      boostMultiplier: 1.9,
    },
    {
      classId: "matter-id",
      description: "Internal legal matter management identifier",
      examplePatterns: ["MTR-2024-0041", "MATTER-CORP-001"],
      metadataField: "matterId",
      boostMultiplier: 1.8,
    },
    {
      classId: "case-number",
      description: "Court case reference number",
      examplePatterns: ["Case No. 24-CV-01234"],
      metadataField: "caseNumber",
      boostMultiplier: 1.8,
    },
    {
      classId: "statute-citation",
      description: "Statutory or regulatory code citation",
      examplePatterns: ["15 U.S.C. § 78j", "17 CFR § 240.10b-5"],
      metadataField: "statuteCitation",
      boostMultiplier: 1.7,
    },
    {
      classId: "contract-id",
      description: "Contract or agreement reference identifier",
      examplePatterns: ["CONTRACT-2024-A001"],
      metadataField: "contractId",
      boostMultiplier: 1.6,
    },
  ],
  defaultMetadataFilters: {},
  rerankEnabled: true,
  maxCandidates: 100,
  maxResults: 12,
  denseWeight: 0.6,
  keywordWeight: 0.4,
  truncationPolicy: { strategy: "truncate", maxTokens: 512, warnAtTokens: 480 },
  promptContextPrefix:
    "You are reviewing legal matter intelligence. The following evidence contains case documents, docket records, and regulatory filings:",
  retentionDays: 2555,
  provenanceRequired: true,
  metadata: { vertical: "prism-counsel" },
};
