import type { DomainProfile } from "../types.js";

export const terraRealEstateIntel: DomainProfile = {
  profileId: "terra_real_estate_intel",
  version: "1.0.0",
  domain: "real-estate",
  displayName: "Terra — Real Estate Intelligence",
  description:
    "Retrieval profile for the Terra Real Estate Intelligence platform. Optimized for property record search, parcel ID lookup, comparable transaction retrieval, zoning code search, and portfolio document analysis. Priority entity classes include parcel identifiers, assessor parcel numbers (APN), property addresses, and contract reference numbers.",
  priorityTerms: [
    "parcel",
    "APN",
    "property",
    "address",
    "zoning",
    "title",
    "deed",
    "appraisal",
    "comps",
    "comparable",
    "lease",
    "mortgage",
    "encumbrance",
    "easement",
    "cap rate",
    "NOI",
    "assessment",
    "tax",
    "permit",
    "occupancy",
  ],
  boostTerms: [
    { term: "parcel ID", pattern: "\\d{3}-\\d{3}-\\d{3,}", multiplier: 2.0, fieldHint: "parcelId" },
    { term: "APN", pattern: "apn\\s*[:#]?\\s*[\\d-]+", multiplier: 1.9, fieldHint: "apn" },
    { term: "address", pattern: "\\d+\\s+[a-z]+\\s+(?:st|ave|blvd|dr|ln|rd|ct|pl|way)", multiplier: 1.6, fieldHint: "streetAddress" },
    { term: "contract ID", pattern: "contract\\s*(?:id|#)?\\s*[a-z0-9\\-]+", multiplier: 1.7, fieldHint: "contractId" },
    { term: "lease ID", pattern: "lease\\s*(?:id|#)?\\s*[a-z0-9\\-]+", multiplier: 1.6, fieldHint: "leaseId" },
  ],
  exactMatchFieldClasses: [
    {
      classId: "parcel-id",
      description: "Assessor parcel number or parcel identifier (county recorder format)",
      examplePatterns: ["123-456-789", "APN 123-456-789-0"],
      metadataField: "parcelId",
      boostMultiplier: 2.0,
    },
    {
      classId: "property-address",
      description: "Full street address of the property",
      examplePatterns: ["1234 Oak Street, Dallas TX 75201"],
      metadataField: "streetAddress",
      boostMultiplier: 1.7,
    },
    {
      classId: "contract-id",
      description: "Purchase agreement or lease contract identifier",
      examplePatterns: ["CONTRACT-2024-0781"],
      metadataField: "contractId",
      boostMultiplier: 1.7,
    },
    {
      classId: "residence-vendor-id",
      description: "Property management or vendor system identifier",
      examplePatterns: ["RES-00441", "VEND-0012"],
      metadataField: "vendorId",
      boostMultiplier: 1.4,
    },
  ],
  defaultMetadataFilters: {},
  rerankEnabled: false,
  maxCandidates: 100,
  maxResults: 10,
  denseWeight: 0.55,
  keywordWeight: 0.45,
  truncationPolicy: { strategy: "truncate", maxTokens: 512 },
  promptContextPrefix:
    "You are reviewing real estate intelligence. The following evidence contains property records, transaction data, and portfolio analysis:",
  retentionDays: 1825,
  provenanceRequired: false,
  metadata: { vertical: "terra" },
};
