import type { DomainProfile } from "../types.js";

export const vesselsMaritime_Risk: DomainProfile = {
  profileId: "vessels_maritime_risk",
  version: "1.0.0",
  domain: "maritime",
  displayName: "Vessels — Maritime Risk Intelligence",
  description:
    "Retrieval profile for Vessels Maritime Intelligence. Optimized for fleet tracking, sanctions screening, port state control records, flag-state intelligence, and incident correlation. Priority entity classes include vessel IMO numbers, MMSI identifiers, port codes, flag-state designations, and sanctions list entries.",
  priorityTerms: [
    "IMO",
    "MMSI",
    "vessel",
    "ship",
    "fleet",
    "flag state",
    "port",
    "sanctions",
    "OFAC",
    "AIS",
    "dark vessel",
    "spoofing",
    "PSC",
    "detention",
    "casualty",
    "incident",
    "cargo",
    "classification",
  ],
  boostTerms: [
    { term: "IMO number", pattern: "imo\\s*\\d{7}", multiplier: 2.0, fieldHint: "imo" },
    { term: "MMSI", pattern: "mmsi\\s*\\d{9}", multiplier: 1.8, fieldHint: "mmsi" },
    { term: "sanctions", pattern: "sanction(?:s|ed)?", multiplier: 1.7, fieldHint: "sanctionsStatus" },
    { term: "dark vessel", pattern: "dark\\s+vessel|ais\\s+gap", multiplier: 1.9, fieldHint: "darkVessel" },
    { term: "PSC detention", pattern: "psc\\s+detention|port\\s+state\\s+control", multiplier: 1.6, fieldHint: "pscDetention" },
  ],
  exactMatchFieldClasses: [
    {
      classId: "imo-number",
      description: "IMO vessel registration number (7 digits, globally unique)",
      examplePatterns: ["IMO 9123456", "IMO9123456"],
      metadataField: "imo",
      boostMultiplier: 2.0,
    },
    {
      classId: "mmsi",
      description: "Maritime Mobile Service Identity (9-digit radio identifier)",
      examplePatterns: ["MMSI 123456789"],
      metadataField: "mmsi",
      boostMultiplier: 1.8,
    },
    {
      classId: "call-sign",
      description: "Vessel radio call sign",
      examplePatterns: ["CALL SIGN ABCD1"],
      metadataField: "callSign",
      boostMultiplier: 1.5,
    },
    {
      classId: "unlocode",
      description: "UN/LOCODE port identifier",
      examplePatterns: ["USMIA", "SGSIN"],
      metadataField: "portCode",
      boostMultiplier: 1.4,
    },
    {
      classId: "sanctions-entity",
      description: "Named entity on a sanctions list (OFAC, EU, UN)",
      examplePatterns: ["OFAC SDN", "SDN List entry"],
      metadataField: "sdnEntityId",
      boostMultiplier: 2.0,
    },
  ],
  defaultMetadataFilters: {},
  rerankEnabled: true,
  maxCandidates: 150,
  maxResults: 15,
  denseWeight: 0.65,
  keywordWeight: 0.35,
  truncationPolicy: { strategy: "truncate", maxTokens: 512, warnAtTokens: 480 },
  promptContextPrefix:
    "You are reviewing maritime intelligence. The following evidence pertains to vessel operations, flag-state records, and sanctions exposure:",
  retentionDays: 365,
  provenanceRequired: true,
  metadata: { vertical: "vessels" },
};
